### ISSUE TITLE
Longpress on attachment (image) in chat locks app in unusable state

### ISSUE THREAD

**Issue by cenzovit** [GetStream/stream-chat-react-native#100]
If you press on an image attachment and have it open the viewer, if you then long press on the image (which most users believe will let you copy the image to the clipboard), the app gets stuck in an unusable state.

**Comment by tbarbugli** [comment]
thank you for reporting this; I just tried reproducing this on my end but I did not get the same outcome (nothing happens for me when I long-press). We will keep try to reproduce this as well, in the meantime if you can share more information on how you test this that would be great (simulator/real phone, SDK, relevant code if applicable, ...)

**Comment by vishalnarkhede** [comment]
Thanks for reporting this. I managed to reproduce this on my device. I will look into it and get back to you :)

**Comment by vishalnarkhede** [comment]
@cenzovit this has been fixed as part of [`v0.5.0`](https://github.com/GetStream/stream-chat-react-native/releases/tag/v0.5.0). We are disabling long press on image viewer for now to avoid freezing of UI. When we implement the functionality to save images on device, we will re-enable it!

Please let us know if that solves the issue for you!!

**Comment by cenzovit** [comment]
Appears fixed!
