### ISSUE TITLE
Gallery customization - add a loading indicator and make it customizable

### ISSUE THREAD

**Issue by KarinZvereva** [GetStream/stream-chat-react-native#1005]
Hi. Unfortunately, i couldn't find information about this case. I would like to show activity indicator of image in attachment? Is there a way to do this, except pass custom gallery in `Channel`?

Like this
![example](https://user-images.githubusercontent.com/38095464/142227457-2b46cb2d-d4c0-4811-93a4-813727003262.png)

gz#16815

**Comment by madsroskar** [comment]
For internal tracking: CRNS-484

**Comment by KarinZvereva** [comment]
Thanks for your reply

**Comment by vanGalilea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/1005?planning-poker) with ZenHub @Enigma-I-am @khushal87 @madsroskar @vishalnarkhede

**Comment by vanGalilea** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/1005?planning-poker) with ZenHub @santhoshvai

**Comment by vanGalilea** [comment]
We agreed to add:
- loading indicator TBD
- customize the whole grid item
