### ISSUE TITLE
MessageInput with imagepicker and filepicker doesn't open actionsheet to choose properly

### ISSUE THREAD

**Issue by cenzovit** [GetStream/stream-chat-react-native#101]
When hasImagePicker and hasFilePicker are both set to true for the MessageInput component, attempting to do either action often fails to properly open their respective action sheets (opens and then closes immediately). Seems to be some sort of race condition between the intermediate menu closing the the action sheets opening.

**Comment by vishalnarkhede** [comment]
Thanks for raising this @cenzovit . I will look into it and get back to you !!

**Comment by vishalnarkhede** [comment]
Hey @cenzovit I haven't been able to replicate the issue so fat. Can you give us the following details:

1. Version of `stream-chat-react-native` that you are using
2. Device/emulator that you are testing on
3. Version of react-native or expo that you are using

That will really help us resolve this quickly :)

**Comment by vishalnarkhede** [comment]
@cenzovit ping!!

**Comment by vishalnarkhede** [comment]
Going to close this issue now due to inactivity. Please reopen if you still need help with this!
