### ISSUE TITLE
User can see "deleted message" in message preview 

### ISSUE THREAD

**Issue by RomanBob123** [GetStream/stream-chat-react-native#1011]
User can see "deleted message" in message preview
This message should not be seen by anyone except the one who deleted the messages. But it can be seen by all users in the channel list.
![Screenshot from 2021-11-22 16-37-33](https://user-images.githubusercontent.com/91616406/142880620-d5f0d8b7-4c4c-4386-bc66-ccf30d24c837.png)

gz#16929

**Comment by madsroskar** [comment]
Hi @RomanBob123 - thanks for raising the issue. We're looking into it, and will get back to you once we know more about why this is happening.

**Comment by vishalnarkhede** [comment]
Hey @RomanBob123 thanks for bringing this up. This will require some improvements on our api side to support this behaviour and we are already looking into it. I can't say exactly the timeline about this, but I will keep you updated :)

**Comment by bkit4u** [comment]
Hi @madsroskar,
How can I enable or edit to show message was deleted by someone in core source code ?
I need custom some feature with message deleted, but user cannot see all message deleted except message deleted by themselves

**Comment by madsroskar** [comment]
To change the visibility of deleted messages, you can set the prop `deletedMessagesVisibilityType` on the `Channel` component to one of the following:

<table>
<tr>
	<td> `"always"`
	<td> Display deleted messages for everybody in the channel
<tr>
	<td> `"never"`
	<td> Don't display deleted messages at all in a channel
<tr>
	<td> `"sender"`
	<td> Show deleted messages only for the user that sent the message
<tr>
	<td> `"receiver"`
	<td> Show deleted messages for everybody *except* the sender of the message
</table>

If you want to customize the look of the deleted message bubble itself, you can create a custom version of the [`MessageDeleted`](https://getstream.io/chat/docs/sdk/reactnative/ui-components/message-deleted/) component, and pass it to the `Channel` component in the [`MessageDeleted`](https://getstream.io/chat/docs/sdk/reactnative/core-components/channel/#messagedeleted) prop.

Does this answer you question, @bkit4u, or am I misunderstanding what you're trying to achieve?

**Comment by bkit4u** [comment]
Yes, that's my question. But I cannot find any prop **deletedMessagesVisibilityType** on the **Channel** component. Can you give me the link docs or something about it prop ?

**Comment by vishalnarkhede** [comment]
FYI its only available in `v4.0.0-beta.1` - https://getstream.io/chat/docs/sdk/reactnative/4.0.0/basics/upgrading-from-v3/#deleted-messages
