### ISSUE TITLE
Bug with deleted thread messages

### ISSUE THREAD

**Issue by RomanBob123** [GetStream/stream-chat-react-native#1012]
If a users deleted their messages in the thread, the number of messages will still count for deleted messages.
If the user deletes all messages in the thread, the thread is not closed

Step to reproduce:
- Create a thread.
- Write a message in it.
- Delete this message.
- Log in as a different user and go to this thread.

![Screenshot from 2021-11-22 17-23-54](https://user-images.githubusercontent.com/91616406/142890458-14948357-aceb-42da-bad9-e0cd3a021c71.png)

![Screenshot from 2021-11-22 17-24-14](https://user-images.githubusercontent.com/91616406/142890469-836e0ad3-f534-4f12-a539-3d05b053ff34.png)

![Screenshot from 2021-11-22 17-25-57](https://user-images.githubusercontent.com/91616406/142890477-9cc5ec37-842c-4abd-b8dc-316fb44bda20.png)

![Screenshot from 2021-11-22 17-26-03](https://user-images.githubusercontent.com/91616406/142890486-2fa128f0-534e-4c54-b541-c213af38a464.png)

gz#16934

**Comment by madsroskar** [comment]
Hi @RomanBob123 - thanks for raising the issue. We're looking into it, and will get back to you once we know more about why this is happening.

**Comment by vishalnarkhede** [comment]
Hey @RomanBob123 this is a behaviour of the API for soft deleted messages. Please take a look at the documentation for the difference between soft delete and hard delete - https://getstream.io/chat/docs/javascript/send_message/?language=javascript&q=deleteMes#delete-a-message

If you want to opt for hard delete, you can look into customizing message actions

- https://getstream.io/chat/docs/sdk/reactnative/guides/customize-message-actions/
- https://github.com/GetStream/stream-chat-react-native/blob/develop/package/src/components/Message/utils/messageActions.ts
