### ISSUE TITLE
Delete message fails when message was not able to send

### ISSUE THREAD

**Issue by sandergo90** [GetStream/stream-chat-react-native#1020]
**Describe the bug**

**Dev environment info (please complete/provide the following information):**

- Package version stream-chat-react-native@3.10.1
- react-native
- Device/Emulator --> on all operation systems

**To Reproduce**

- Open a channel, go offline, and send a message.
- An exclamation mark will be shown next to the message
- Go back online/ or stay offline, and long press the message and press delete message
- Error occurs: "Message with id ... doesn't exist".

**Expected behavior**

I would expect not to be able to delete a message that was not send.

gz#17027

**Comment by vishalnarkhede** [comment]
Hey @sandergo90 thanks for bringing this up. I am able to reproduce this issue and we will soon publish a fix for this :)

**Comment by vishalnarkhede** [comment]
For internal tracking - https://stream-io.atlassian.net/browse/CRNS-491

**Comment by vishalnarkhede** [comment]
Hey @jehartzog we have published our next major version of RN Chat SDK - `v4.1.0` 🎉.

This release includes the fix for this issue. Please take a look at [**Release Notes**](https://github.com/GetStream/stream-chat-react-native/releases/tag/v4.1.0) for details.
