### ISSUE TITLE
Array mentioned_users empty after message edited

### ISSUE THREAD

**Issue by bkit4u** [GetStream/stream-chat-react-native#1023]
**Describe the bug**
I'm mention one account with **@name**.  But when I edited message, the array mentioned_users is empty

**Dev environment info (please complete/provide the following information):**

- "stream-chat-react-native": "^3.10.2"
- "react-native": "0.66.0"
- "react": "17.0.2"

**To Reproduce**

1.Mention one name account in your message input and send this message. Example: @yourname - my message
2. Click edit that message
3. Edit some text. Example @yourname - my message edited
4. Check message object to get **mentioned_users** empty array

gz#17051

**Comment by vishalnarkhede** [comment]
Thanks for bringing this up @bkit4u ! We have managed to reproduced this issue on our side and added it to our backlog. We will update you once the fix is ready :)

**Comment by vishalnarkhede** [comment]
For internal tracking purpose - https://stream-io.atlassian.net/browse/CRNS-493

**Comment by vishalnarkhede** [comment]
Hey @bkit4u  we have published our next major version of RN Chat SDK - `v4.1.0` 🎉.

This release includes the fix for this issue. Please take a look at [**Release Notes**](https://github.com/GetStream/stream-chat-react-native/releases/tag/v4.1.0) for details.
