### ISSUE TITLE
Failed to get size for image

### ISSUE THREAD

**Issue by sandergo90** [GetStream/stream-chat-react-native#1025]
Describe the bug

Dev environment info (please complete/provide the following information):

Package version stream-chat-react-native@3.10.1
react-native
Device/Emulator --> All android devices
To Reproduce

I'm having a Channel with a lot of images inside. Sometimes 7 images uploaded at once so displaying as multiple images.
When opening my channel on Android, some images will not load (not all the time), giving me the error `Failed to get size for image: http://dublin.stream-io.cdn.com/xxx`

When opening the link of the image in the browser, no problem here. It's just a jpg image.

gz#17060

**Comment by sandergo90** [comment]
Error comes from react native function `getSize` calling `NativeImageLoaderAndroid.getSize(url)`. So something goes wrong at the CDN while requesting a lot of images perhaps?

**Comment by Marcoo09** [comment]
I have the same problem in **some** android devices not in all.
I'm executing on release mode without any debugger. I also checked [this](https://getstream.io/chat/docs/sdk/reactnative/basics/troubleshooting/) page to double check that any setup it's missing.

On my end on some android devices I'm not able to see the gallery images or in the message input attachement, I can send the message and in this moment I receive the get size image problem.
![image](https://user-images.githubusercontent.com/18408823/144349012-eaa0444d-a960-48f1-b1ee-eafebcb2da2e.png)

**Comment by vishalnarkhede** [comment]
@sandergo90 could you please try setting a prop `legacyImageViewerSwipeBehaviour={false}` on Channel component?

https://getstream.io/chat/docs/sdk/reactnative/core-components/channel/#legacyimageviewerswipebehaviour

**Comment by sandergo90** [comment]
Hi @vishalnarkhede that sadly doesn't make a difference

**Comment by sandergo90** [comment]
Any update on this? We have a paid plan at get stream, and our customers suffer a lot from this. Thanks!

**Comment by vishalnarkhede** [comment]
Hey @sandergo90 we will soon publish next beta version of v4 (I will update you soon). This issue should be resolved as part of it.

**Comment by Marcoo09** [comment]
@vishalnarkhede  is there an estimated date for the release of this version? Is there any workaround? We have some users with this problem on production
