### ISSUE TITLE
undefined is not an object (evaluating 'deleteanimationCopy.callback')  in Expo app

### ISSUE THREAD

**Issue by Chibuzo15** [GetStream/stream-chat-react-native#1034]
App crashes whenever I add components from 'stream-chat-expo', components such as <OverlayProvider>, <MessageList>
I am currently following the docs so I'm trying to place OverlayProvider above all navigation stacks

  ```
  return <NavigationContainer
        theme={scheme === 'dark' ? MyThemes.MyDarkTheme : MyThemes.MyLightTheme}
    >
        <OverlayProvider
        >
            <Chat client={chatClient}>
                <RootNav />
                <Loader />
                <SuccessModal />
                <ErrorModal />
            </Chat>
        </OverlayProvider>
    </NavigationContainer>

```
**Dev environment info (please complete/provide the following information):**

- Package version stream-chat-expo^3.10.2
- expo version ~43.0.0
- Device/Emulator Android 10

**To Reproduce**
Install stream-chat-expo and all dependencies using "expo install"

My package.json 
```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@expo-google-fonts/dm-sans": "^0.2.0",
    "@react-native-async-storage/async-storage": "^1.15.11",
    "@react-native-community/masked-view": "0.1.5",
    "@react-native-community/netinfo": "6.0.2",
    "@react-navigation/bottom-tabs": "^6.0.9",
    "@react-navigation/drawer": "^6.1.8",
    "@react-navigation/native": "^6.0.6",
    "@react-navigation/native-stack": "^6.2.5",
    "@reduxjs/toolkit": "^1.6.2",
    "@types/react-native-snap-carousel": "^3.8.5",
    "axios": "^0.24.0",
    "d3-shape": "^3.0.1",
    "expo": "~43.0.0",
    "expo-app-loading": "~1.2.1",
    "expo-barcode-scanner": "~11.1.2",
    "expo-blur": "~10.0.3",
    "expo-document-picker": "~10.0.3",
    "expo-file-system": "~13.0.3",
    "expo-haptics": "~11.0.3",
    "expo-image-manipulator": "~10.1.2",
    "expo-image-picker": "~11.0.3",
    "expo-location": "~13.0.4",
    "expo-media-library": "~13.0.3",
    "expo-sharing": "~10.0.3",
    "expo-status-bar": "~1.1.0",
    "libphonenumber-js": "^1.9.43",
    "metro-react-native-babel-preset": "^0.66.2",
    "moment": "^2.29.1",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.2",
    "react-native-country-picker-modal": "^2.0.0",
    "react-native-dotenv": "^3.3.0",
    "react-native-gesture-handler": "~1.10.2",
    "react-native-maps": "0.28.1",
    "react-native-pager-view": "5.4.6",
    "react-native-popup-menu": "^0.15.11",
    "react-native-reanimated": "~2.2.0",
    "react-native-safe-area-context": "3.3.2",
    "react-native-screens": "~3.8.0",
    "react-native-signature-canvas": "^4.3.0",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-svg": "12.1.1",
    "react-native-svg-charts": "^5.4.0",
    "react-native-tab-view": "^3.1.1",
    "react-native-toast-message": "^2.0.2",
    "react-native-web": "0.17.1",
    "react-native-webview": "11.13.0",
    "react-redux": "^7.2.6",
    "redux-persist": "^6.0.0",
    "stream-chat-expo": "^3.10.2"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@types/react": "~17.0.21",
    "@types/react-native": "~0.64.12",
    "typescript": "~4.3.5"
  },
  "private": true
}

```
![bug](https://user-images.githubusercontent.com/15633719/144036027-30f9b48e-1b95-4a05-afe8-54c083fda1fa.jpg)
![image](https://user-images.githubusercontent.com/15633719/144036407-c62c2837-557e-46ae-86a0-8cd6e1ea88fe.png)

gz#17142

**Comment by madsroskar** [comment]
Hi, @Chibuzo15! Thanks for raising the issue, we'll look into it and get back to you once we know more. 

Just wondering, do you happen to use `npm` (as opposed to `yarn`) in your project?

**Comment by Chibuzo15** [comment]
Alright thanks, I make use of `yarn`  (the 'expo install' command uses yarn in background ) however while trying to fix this issue , I've deleted the node_modules folder multiple times and reinstalled using `npm` but the error still persists

**Comment by vishalnarkhede** [comment]
@Chibuzo15 we would really appreciate if you could fork this repository and try to reproduce this issue in [ExpoMessaging](https://github.com/GetStream/stream-chat-react-native/tree/develop/examples/ExpoMessaging) example app.

**Comment by Chibuzo15** [comment]
Alright, I'll try that soon and give the feedback

**Comment by Chibuzo15** [comment]
I forked the repository, and ran yarn install,  however I keep getting this error after metro builds 

`Android Bundling failed 7008ms
Unable to resolve module @react-native-community/netinfo from C:\projects\stream-chat-react-native\package\expo-package\src\index.js: @react-native-community/netinfo could not 
be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
  1 | import React from 'react';
  2 | import { FlatList } from 'react-native';
> 3 | import NetInfo from '@react-native-community/netinfo';
    |                      ^
  4 | import { BlurView as ExpoBlurView } from 'expo-blur';
  5 | import * as DocumentPicker from 'expo-document-picker';
  6 | import * as FileSystem from 'expo-file-system';
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
`

**Comment by Chibuzo15** [comment]
After lots of digging, I discovered the issue was from some babel configurations I added 

`module.exports = function (api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo',
      'module:metro-react-native-babel-preset',
    ],
    plugins: [
      ["module:react-native-dotenv", {
        "moduleName": "@env",
        "path": ".env",
        "blacklist": null,
        "whitelist": null,
        "safe": false,
        "allowUndefined": true
      }],
      "react-native-reanimated/plugin"
    ]
  };
};`

changing it to  

`module.exports = function(api) {
  api.cache(true);
  return {
    plugins: ['react-native-reanimated/plugin'],
    presets: ['babel-preset-expo'],
  };
};
`

solved the issue

**Comment by madsroskar** [comment]
Good to hear you figured it out and got it running! Thanks for getting back to us with an update. :)
