### ISSUE TITLE
UserResponse<LocalUserType> is not assignable to type 'UserResponse<LocalUserType & OwnUserBase<LocalChannelType, string, LocalUserType>>'

### ISSUE THREAD

**Issue by skam22** [GetStream/stream-chat-react-native#1038]
**Describe the bug**
Typescript 4.4.4 error with v3.10.2:

Type 'UserResponse<LocalUserType>' is missing the following properties from type 'OwnUserBase<LocalChannelType, string, LocalUserType>': channel_mutes, devices, mutes, total_unread_count, and 2 more.

**Dev environment info (please complete/provide the following information):**

- Package version stream-chat-react-native 3.10.2
- react-native
- Device/Emulator (iOS & simulator) and OS version 15.0

**To Reproduce**

1.

```
export type LocalAttachmentType = Record<string, unknown>;
export type LocalChannelType = Record<string, unknown>;
export type LocalCommandType = string;
export type LocalEventType = Record<string, unknown>;
export type LocalMessageType = Record<string, unknown>;
export type LocalReactionType = Record<string, unknown>;
export type LocalUserType = Record<string, unknown>;
```

2. 

```
const chatClient = StreamChat.getInstance<
  LocalAttachmentType,
  LocalChannelType,
  LocalCommandType,
  LocalEventType,
  LocalMessageType,
  LocalReactionType,
  LocalUserType
>(API_KEY);
```

3.

```
const ChatScreen = (): JSX.Element => {
  return (
    <SafeAreaView>
      <Chat client={chatClient}>
      ...
      </Chat>
    </SafeAreaView>
  );
};

```

4. See error types of _user are incompatible

**Expected behavior**

expected to compile without typescript errors.

**Screenshots*
![Screen Shot 2021-12-02 at 10 58 29 AM](https://user-images.githubusercontent.com/50343717/144485660-2a3e9294-c781-4b51-920b-0b1741a23b94.png)
*

gz#17229

**Comment by vishalnarkhede** [comment]
Hey @skam22 could you please fork the repository and try to reproduce this issue in one of the example apps? https://github.com/GetStream/stream-chat-react-native/tree/develop/examples

**Comment by delantai** [comment]
I am also experiencing this exact problem.  @skam22 did you find a work around?  

I'm playing around with the stream-chat-react-native `TypeScriptMessaging` example and see the same problem there too:

![image](https://user-images.githubusercontent.com/8430216/145672183-c17c74d5-21f0-4458-af68-be8514de9bbb.png)

**Comment by madsroskar** [comment]
I can reproduce this in our sample apps. It looks like we have a couple of types that need updating, I'm looking into it. We're working on simplifying the types for the SDK at the moment, but I'll make a PR to resolve this in the sample apps in the meantime.

**Comment by madsroskar** [comment]
#This is a bit trickier to work around than I thought, so I don't have a solution just yet. For the time being, you could tell typescript to expect there to be an error reported there with `@ts-expect-error` in a comment on the line above the line it's reporting the error to suppress the error message until we have a proper solution in place.

This seems to be an issue with our js client checking the wrong type for the User when it's being updated from an Event, so it looks like we'll have to fix the type definition there.

I'm creating an issue in our internal issue tracker, thanks for reporting it!

**Comment by skam22** [comment]
@delantai sorry for the late reply, I actually had implemented what @madsroskar suggested, basically commenting out the typescript error since it wasn’t preventing a successful build.

**Comment by delantai** [comment]
Thanks for the replies, very helpful!

**Comment by delantai** [comment]
Side note, I'm seeing a similar thing for the `channel` typing which is being passed via context in the example app.  

In the `onSelect` of `ChannelListScreen` in the example app I'm seeing this:

![image](https://user-images.githubusercontent.com/8430216/146110498-42175854-dd96-446e-be8f-86ec8e9f3c5a.png)

In my app I'm also trying to access a channel in state via hook, and having the same difficulties as above.

**Comment by vanGalilea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/1038?planning-poker) with ZenHub @Enigma-I-am @khushal87 @madsroskar @santhoshvai @vishalnarkhede

**Comment by vanGalilea** [comment]
Relates to [1357](https://github.com/GetStream/stream-chat-react-native/issues/1357)

**Comment by vanGalilea** [comment]
This issue has become stale, due to old SDK and TS versions.
