### ISSUE TITLE
[feature request] video/audio call integrations

### ISSUE THREAD

**Issue by wangsha** [GetStream/stream-chat-react-native#1039]
currently https://dolby.io/ example is a native ios app. Looking forward to have video/audio call capability in react-native and react sdks to build chat experience similar to microsoft teams chat.

gz#17243

**Comment by vishalnarkhede** [comment]
I would recommend you to take a look at - https://getstream.io/blog/build-a-video-conferencing-app-using-dolby-voxeet-and-stream-chat/
