### ISSUE TITLE
Expo app crash when adding OverlayProvider

### ISSUE THREAD

**Issue by ngochnvn** [GetStream/stream-chat-react-native#1041]
**Describe the bug**
Expo app crash when adding OverlayProvider. On IOS Expo just crashed, and on Android, I got this error: "Tried to synchronously call function {assign} from a different thread". 

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native/stream-chat-expo)
    "stream-chat-expo": "^3.10.2",
    "stream-chat-react-native-core": "^3.10.2",
- react-native or expo version     "expo": "^42.0.0"
- Device/Emulator (android/ios) and OS version: Both Android and iOS crashed

**To Reproduce**
Not sure how, attached is my package json

**Expected behavior**
App doesn't crash

**Additional context**
My package json is attached and I have copied all dependencies from the example app

**Screenshots**
![Screenshot_20211206-133256_Expo Go](https://user-images.githubusercontent.com/1898917/144798758-5f32e565-1a3b-48fc-883f-e19933d8d853.jpg)
[package.json.txt](https://github.com/GetStream/stream-chat-react-native/files/7662851/package.json.txt)
[babel.config.txt](https://github.com/GetStream/stream-chat-react-native/files/7662858/babel.config.txt)

gz#17287

**Comment by madsroskar** [comment]
Hi @ngochnvn, we'll look into this, and see if we can reproduce it. The `package.json.txt` file you've attached doesn't seem to contain the contents of the package.json - could you maybe try to attach the json file directly? Also, could you add the content of your babel configuration (`babel.config.js` for example)?

**Comment by ngochnvn** [comment]
Thank you for your quick reply. I have added the package.json and babel config (Updated the original post)
https://github.com/GetStream/stream-chat-react-native/files/7662851/package.json.txt
https://github.com/GetStream/stream-chat-react-native/files/7662858/babel.config.txt

**Comment by vishalnarkhede** [comment]
Hey @ngochnvn we are looking into it. We will get back to you soon

**Comment by vishalnarkhede** [comment]
Hey @ngochnvn I am not sure whats the best way to reproduce this issue on our side. Although I did notice that you are using expo web with nextjs, which we currently don't support on our SDK.

Is it possible for you to test the integration **without** following babel presets?

- `module:metro-react-native-babel-preset`
- `@expo/next-adapter/babel`

**Comment by ngochnvn** [comment]
Hi vishalnarkhede@,

Thank you very much. We removed those two lines and it worked. It must be something with next-adapter.

**Comment by thuytony** [comment]
Looks like I'm facing the same issue when trying to add OverlayProvider. Any ideas on how to fix this?
[babel.config.js](https://github.com/thuytony/ask-git/blob/main/babel.config.js)
[package.json](https://github.com/thuytony/ask-git/blob/main/package.json)
![Simulator Screen Shot - iPhone 11 - 2022-05-10 at 14 37 58](https://user-images.githubusercontent.com/34490002/167574907-2e7740e5-a4b3-4f2c-b41e-6bdc5a50e336.png)
