### ISSUE TITLE
defaultValue not being passed through

### ISSUE THREAD

**Issue by SamRichards** [GetStream/stream-chat-react-native#1052]
**Describe the bug**

When using the <MessageInput component, using the defaultValue inside of additionalTextInputProps, does not pass the default value down. Other values are passed down using this method, placeholder, placeholder colours, on change events, value, the only one that doesn't is default value.

According to the documentation https://getstream.io/chat/docs/sdk/reactnative/ui-components/message-input/#additionaltextinputprops and https://reactnative.dev/docs/textinput#props it should be able too.

**Dev environment info (please complete/provide the following information):**

- versions: "stream-chat": "^4.3.0", "stream-chat-react-native": "^3.9.2", "react-native": "0.64.0",
- iOS emulator, Android physical

**To Reproduce**

On react native with the component of similar to:

```
<MessageInput
        additionalTextInputProps={{
          defaultValue: 'hello',
        }}
      />
```

It should have the message input component have a default value and it doesn't.

**Expected behavior**

To have the message input start with the default value as expected.

Thanks in advance,

Sam

gz#17540

**Comment by madsroskar** [comment]
Thanks for raising the issue, we'll look into it and get back to you as soon as we have more information about what's going on.

**Comment by vishalnarkhede** [comment]
@SamRichards to set the default value on input box, please use following prop instead, on `Channel` component - https://getstream.io/chat/docs/sdk/reactnative/core-components/channel/#initialvalue
