### ISSUE TITLE
Upgrade @gorhom/bottom-sheet to v4

### ISSUE THREAD

**Issue by andreibarabas** [GetStream/stream-chat-react-native#1053]
**Describe the bug**
v3 of the bottom sheet uses some legacy React Native APIs which are deprecated in RN 67

**Dev environment info (please complete/provide the following information):**

- "stream-chat-react-native": "~3.10.2",
- RN 0.67
- All Devices / Simulators

**To Reproduce**

1. Upgrade to RN 0.67.0-rc.5
2. Unmount the chat
3. when it unmounts, you should see this warning

According to the [Bottom Sheet changelog](https://github.com/gorhom/react-native-bottom-sheet/blob/8d9b0502fda114a348606ad421d732d3a8bcbaa5/CHANGELOG.md#v410---2021-09-26), this has been fixed in 4.1

**Screenshots**
![Simulator Screen Shot - iPhone 13 Pro - 2021-12-15 at 05 21 10](https://user-images.githubusercontent.com/2101405/146117235-60eb12c5-4933-4c03-880c-dcf835b45c45.png)

gz#17590

**Comment by madsroskar** [comment]
Thanks for creating the issue! 

We have a task to upgrade the dependency in our backlog, but I don't yet know how fast we'll be able to prioritize this just yet. This should not break anything in your application, and for the time being you could suppress the warning by passing it as a string in an array to the React Native LogBox (Something like `LogBox.ignoreLogs(["EventEmitter.removeListener"])` for example) until we have a release ready that handles the deprecation.

We'll get back to you when we have more information on this.  

Link so this is referenced In our Jira issue: CRNS-494

**Comment by izakfilmalter** [comment]
I just did this as a patch, lol. It does break the app forcing `@gorhom/bottom-sheet@4.1.5`. It's a fairly easy upgrade though. 

I had to do the following:

1. Add `enablePanDownToClose` to both instances of BottomSheet.
2. The api for `snapTo` changed to `snapToIndex`:
  ```
    -      bottomSheetRef.current.snapTo(1);
    +      bottomSheetRef.current.snapToIndex(0);
   ```
3.  I also had to do the following to `ImageGallery.tsx`
  ```
  -  const snapPoints = React.useMemo(() => [0, (screenHeight * 9) / 10], []);
  +  const snapPoints = React.useMemo(() => [(screenHeight * 9) / 10], []);
  ```
  
That seemed to do the tick for me. I think the real upgrade would be changing these to both be Modals, but that was a larger refactor than what I wanted as a patch. The nice thing about it all is that I was able to use `BottomSheetModalProvider` and `useBottomSheet` without any other changes to this lib.

**Comment by madsroskar** [comment]
Thanks for reporting back with the changes you made for it to work, that's very helpful.

>  I think the real upgrade would be changing these to both be Modals

The modal wrapper in v4 does look nice, we'll look into that as part of the upgrade.

**Comment by andreibarabas** [comment]
Thanks guys. @izakfilmalter for the patch

**Comment by andreibarabas** [comment]
Yes. I can confirm it's upgraded and working now. Thanks @vishalnarkhede
