### ISSUE TITLE
Frozen field in firebase data template 

### ISSUE THREAD

**Issue by KarinZvereva** [GetStream/stream-chat-react-native#1058]
Hi. I am trying to pass frozen field to firebase payload, but every time I get empty line. But channel's id and type is fine. Is it possible get frozen value?

1. Go to dashboard ->  firebase
2. Click on Data Template
3. Set data
`{
    "channel": {
        "type": "{{ channel.type }}",
        "id": "{{ channel.id }}",
        "frozen": "{{ channel.frozen }}"
    }
}`

**Expected behavior**
frozen has value (false or true)

gz#17907

**Comment by madsroskar** [comment]
Hi @KarinZvereva, could you send us an email on <support@getstream.io> with the App ID or API key for the application you have set the data template on?

**Comment by vishalnarkhede** [comment]
Closing this issue since its not related to RN Chat SDK
