### ISSUE TITLE
Add isMounted check for resetting MessageOverlayProvider state

### ISSUE THREAD

**Issue by madsroskar** [GetStream/stream-chat-react-native#1065]
Originated in #943 - A [`TODO`](https://github.com/GetStream/stream-chat-react-native/blob/9c3482f0e2673dd2a216a461db28e21ef5790df1/package/src/contexts/messageOverlayContext/MessageOverlayContext.tsx#L111) was to check whether MessageOverlayProvider is still mounted before resetting its state.

**Comment by vishalnarkhede** [comment]
Fixed in v4.1.0
