### ISSUE TITLE
Crash when list contains empty list item.

### ISSUE THREAD

**Issue by diego-paired** [GetStream/stream-chat-react-native#1067]
Using version `3.10.2` of the SDK.

We've had reports of users who are unable to access the chat. After investigating the matter, they are experiencing the following crash:

```
TypeError: Cannot read property 'type' of undefined

This error is located at:
    in Markdown (at renderText.tsx:305)
```

Specifically in this line of the code:
```
          const isTopLevelText =
            ['text', 'paragraph', 'strong'].includes(item[0].type) && withinList === false;
```
As item[0] is undefined.

The message text is the following:
```text: "1. Something \n2. \n3. Something "``` 

Notice n2 being empty.

Thanks in advance.

gz#18017

**Comment by madsroskar** [comment]
Thanks for raising the issue, and adding the info you have, that's very helpful. I'm looking into this, I'll get back to you once I have an update for you about this.

**Comment by madsroskar** [comment]
Ah yeah, that's not quite right. Adding a task to sort this out, thanks for reporting it!

**Comment by diego-paired** [comment]
@madsroskar thanks
