### ISSUE TITLE
How to show preview count for unread messages?

### ISSUE THREAD

**Issue by thedewpoint** [GetStream/stream-chat-react-native#1070]
I'm using the default ChannelList component, and by default there is a preview component according to the documentation. But the channels don't show the unread count. Is there a flag to enable this? Or is there a minimal example of how to do this?

gz#18176

**Comment by vishalnarkhede** [comment]
Could you please check the dashboard to confirm that you have enabled read events?

<img width="1379" alt="Screenshot 2022-01-07 at 16 04 55" src="https://user-images.githubusercontent.com/11586388/148531618-602e360a-bb96-4c87-aede-bdb06a524b78.png">

**Comment by thedewpoint** [comment]
@vishalnarkhede yes it was enabled. I was able to get help from support to do this. I had to include some preview components in the channel list. Providing the snippet here:

```
    <ChannelList 
          Preview={ChannelPreviewMessenger}
          ChannelPreviewUnreadCount={ChannelPreviewUnreadCount}
          onSelect={setChannel} />
```

**Comment by vishalnarkhede** [comment]
@thedewpoint thats strange, those are the default components ... so you shouldn't need to provide them explicitely!!

**Comment by thedewpoint** [comment]
@vishalnarkhede thats what i thought as well, but i didn't observe unread messages until i passed them
