### ISSUE TITLE
UI broken on Overlay reactions

### ISSUE THREAD

**Issue by rajkapoordev** [GetStream/stream-chat-react-native#1074]
**Describe the bug**
When long press on message. Sometimes , Overlay Reactions screen UI is broken.
This issue only happen sometimes. When you repeatedly long press on message.

**Dev environment info**

- "stream-chat-react-native" : 3.10.2
- "react-native" :0. 63.4
- Device/Simulator only iOS

**To Reproduce**

Long Press on message repeatedly.

**Expected behaviour**
- UI should be proper

**Screenshots**

![Simulator Screen Shot - iPhone 11 - 2022-01-08 at 16 40 52](https://user-images.githubusercontent.com/11647774/148642221-e9b07a28-9991-453a-b91e-57c6fe1d0e8f.png)

gz#18245

**Comment by madsroskar** [comment]
@rajkapoordev are you getting any errors logged to the console when this happens?

**Comment by rajkapoordev** [comment]
@madsroskar Not get any error or log.

**Comment by vishalnarkhede** [comment]
Hey @rajkapoordev I would like to request you to test it on v4 of stream-chat-react-native as well. We are still currently in beta version right now, but you can give it a try using this upgrade helper guide - https://getstream.io/chat/docs/sdk/reactnative/4.0.0/basics/upgrading-from-v3/

You can upgrade to [`v4.0.0-beta.4`](https://github.com/GetStream/stream-chat-react-native/releases/tag/v4.0.0-beta.4)

**Comment by sandergo90** [comment]
Hi @vishalnarkhede the layout is also broken on v4 version. We didn't have problems on v3, but v4 is now broken (see screen recording).

https://user-images.githubusercontent.com/1516413/158144459-18e955b3-b43d-460b-9327-27136da8de1b.MP4

**Comment by vishalnarkhede** [comment]
@sandergo90 by broken UI, do you mean you are not able to see reactions?

Could you please share some code around Channel and OverlayProvider component?

**Comment by sandergo90** [comment]
I mean that the position of the message in overlay with its actions is not position well and at random so it seems?

**Comment by sandergo90** [comment]
@vishalnarkhede any update on this?

**Comment by vishalnarkhede** [comment]
Hey @sandergo90 you can customize the overlay background by theming, to choose lower opacity
- https://github.com/GetStream/stream-chat-react-native/blob/master/package/src/contexts/themeContext/utils/theme.ts#L25
- https://getstream.io/chat/docs/sdk/reactnative/customization/theming/#dark-mode

For now we don't have any plans for changing this behaviour. But I will give it some thought and add it to roadmap.

**Comment by vanGalilea** [comment]
This will be solved after implementing [this issue](https://github.com/GetStream/stream-chat-react-native/issues/1322) I'm going to close this
