### ISSUE TITLE
How to fetch images belonging to a channel

### ISSUE THREAD

**Issue by sandergo90** [GetStream/stream-chat-react-native#1075]
### Discussed in https://github.com/GetStream/stream-chat-react-native/discussions/1061

<div type='discussions-op-text'>

<sup>Originally posted by **sandergo90** December 28, 2021</sup>
Hi,

We would like to store some metadata on a channel. Tis meta data contains some plain text which is easy to store, but also contains some images.

At this moment we store the meta images on the channel using the channel.sendImage method. The file uploads correctly, but in which way can we retrieve the images uploaded to the channel without sending them as a message? This SendFileAPIResponse does return the CDN url, but we cannot just store those URL's because they expire in a few days.

Are there any other methods available to retrieve those images?

Thanks!</div>

gz#18270

**Comment by vishalnarkhede** [comment]
Hey @sandergo90 thanks for the reminder, we will get back to you shortly on the gh discussion.

**Comment by sandergo90** [comment]
Hi @vishalnarkhede can you already give me some idea? Is it possible or do we have to implement something ourselves? We are on a deadline for our project, so we'll have to move on fast. Thanks!

**Comment by vishalnarkhede** [comment]
@sandergo90 currently this is not possible. But I have triggered a discussion internally to look more into it, so that in future all the urls could be refreshed. Currently we only refresh attachment urls.
