### ISSUE TITLE
When Cancelling add attachment app crashes

### ISSUE THREAD

**Issue by JJ-Kidd** [GetStream/stream-chat-react-native#110]
**Describe the bug**
Application throws an unhandled error due to a rejected promise.
When a user clicks to add an attachment, then clicks 'Upload a file', then 'Cancel' I receive "mimeType.startsWith is not a function". 
The error is surfaced from stream-chat-react-native-core.

**Dev environment info (please complete/provide the following information):**

- stream-chat-react-native-core: v0.5.1
- react-native
- Simulator: iPhone 8 and iPhone 11

**To Reproduce**

1. Open a chat
2. Select to add an attachment 
3. Select "Upload a file"
4. Click "Cancel" in top right corner

**Expected behavior**
A user should be returned to the chat and handle the error correctly

**Screenshots**
<img width="339" alt="Screenshot 2020-01-06 at 11 58 57" src="https://user-images.githubusercontent.com/43133297/71817316-5991e400-307d-11ea-854b-c7be47ffd1eb.png">

**Comment by vishalnarkhede** [comment]
Thanks for reporting ti @JJ-Kidd . We will look into it and fix it asap!!

**Comment by vishalnarkhede** [comment]
We will publish a fix for this tomorrow :)

**Comment by vishalnarkhede** [comment]
Hey @JJ-Kidd fixed -[v0.6.0](https://github.com/GetStream/stream-chat-react-native/releases/tag/v0.6.0)

Please confirm if it works for you!!

**Comment by lokewk** [comment]
![Screenshot 2020-10-13 at 2 46 49 PM](https://user-images.githubusercontent.com/68896130/95825111-f008d980-0d62-11eb-873e-f872c7f9a4ce.png)

@vishalnarkhede I am facing the same issue, when a user clicks to add an attachment, then clicks 'Upload a file', then 'Cancel'. User will have the above message.

**Comment by lokewk** [comment]
@vishalnarkhede any update on this?
