### ISSUE TITLE
fbjs/lib/invariant could not be found within the project

### ISSUE THREAD

**Issue by madsroskar** [GetStream/stream-chat-react-native#1101]
This is a result of [react-native-cameraroll/react-native-cameraroll ](https://github.com/react-native-cameraroll/react-native-cameraroll) depending on `fbjs/lib/invariant` without declaring it as a dependency in their manifest. There is a [PR addressing this](https://github.com/react-native-cameraroll/react-native-cameraroll/pull/367) but it has yet to be merged.

To avoid this error, you can **add fbjs as a dependency in your project** until this has been solved in react-native-cameraroll.

```sh
yarn add fbjs # or npm install fbjs
```

gz#18773

**Comment by khushal87** [comment]
I faced this issue recently while setting up an app from scratch. Adding `fbjs` as a dependency works as a fix.

**Comment by santhoshvai** [comment]
yup i can confirm.. i did the same
