### ISSUE TITLE
ImageGalleryHeader parsedDate.fromNow is undefined when passing DateTimeParser to Streami18n

### ISSUE THREAD

**Issue by maxsonm** [GetStream/stream-chat-react-native#1116]
**Describe the bug**
Passing a Moment or Dayjs instance to the Streami18n object results in ImageGalleryHeader throwing an error when parsing the date. 
`parsedDate.fromNow is not a function. (In 'parsedDate.fromNow()', 'parsedDate.fromNow' is undefined)`
Call Stack: ImageGalleryHeader.tsx:116:11

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native/stream-chat-expo): 3.8.2 (also tried on 3.10.2)
- react-native or expo version: RN .65
- Device/Emulator (android/ios) and OS version: iOS 14.5 and Android 11

**To Reproduce**

1. Create Streami18n instance with a moment (or dayjs) instance passed to the constructor as described in https://getstream.io/chat/docs/sdk/reactnative/basics/translations/#overriding-datetime-format
2. Open the screen with the OverlayProvider for the first time

**Expected behavior**
No errors on initial render, dates/times should be formatted by moment for the selected locale

**Additional context**
In ImageGalleryHeader.tsx at the date definition, there is a comment about .calendar not being available on first render, from experimenting with this, it looks like .fromNow is also not available on first render. Adding another ternary check for .fromNow and returning null if not results in no error and proper translations.

The app is not utilizing the gallery in anyway, it only supports text messages.

gz#18950

**Comment by madsroskar** [comment]
Thank you for bringing this to our attention, I could reproduce this on my end as well

**Comment by madsroskar** [comment]
For internal tracking: CRNS-519

**Comment by vishalnarkhede** [comment]
This has been fixed and been included in `v4.0.0-beta.5` release.

**Comment by vishalnarkhede** [comment]
Hey @maxsonm  we have published our next major version of RN Chat SDK - `v4.1.0` 🎉.

This release includes the fix for this issue. Please take a look at [**Release Notes**](https://github.com/GetStream/stream-chat-react-native/releases/tag/v4.1.0) for details.
