### ISSUE TITLE
Unable to select channel from channel list after upgrading to expo 44

### ISSUE THREAD

**Issue by thedewpoint** [GetStream/stream-chat-react-native#1121]
I have an app written in expo sdk 42 that was working fine, and then after upgrading to expo sdk 44 and navigating to my messages tab, i try to select a channel from the list and nothing happens. I added a console.log to the onSelect and it's not firing at all. Something weird with detecting onpress maybe? 

gz#19129

**Comment by thedewpoint** [comment]
Additional information. I set the channel programmatically and it loaded all of the messages, however when i try to send a new message, the send button is also unresponsive. Additionally if I try to reply in a thread or react to a message it crashes. Any insight would be greatly appreciated

**Comment by thedewpoint** [comment]
bump!

**Comment by madsroskar** [comment]
Hi, @thedewpoint - I just built [this small app](https://github.com/madsroskar/stream-chat-expo-with-channel-list) with Expo 44 to try to reproduce the issue, but it doesn't seem to happen there for me. Could you see if you face the same issue if you clone it and build it on your end?

I'll keep trying to reproduce it, and will get back to you when I figure out more about this.

**Comment by Rappo-Ghad** [comment]
Hello, @madsroskar. I'm having the same problem, but with the stream-chat-expo package. Expo SDK 44 is what I'm using. Because the channels are unclickable for whatever reason, the onSelect function is not invoked.

**Comment by vishalnarkhede** [comment]
Hey @Rappo-Ghad can you confirm if you have followed the installation steps for RN Gesture handler - https://docs.expo.dev/versions/latest/sdk/gesture-handler/#api

**Comment by Rappo-Ghad** [comment]
Hello, @vishalnarkhede. I appreciate your taking the time to notice my problem. I followed the RN Gesture Handler installation instructions, but the channels do not appear to be clickable.

**Comment by vishalnarkhede** [comment]
@Rappo-Ghad https://github.com/GetStream/stream-chat-react-native/issues/1121#issuecomment-1031881781

If you are not able to reproduce this issue in app shared by @madsroskar , then could you please setup a new simple expo app and share it with us, where we can reproduce this issue.

**Comment by Rappo-Ghad** [comment]
Hello, @vishalnarkhede , I forgot to mention that I am using Typescript.

**Comment by Rappo-Ghad** [comment]
Hello, @vishalnarkhede, the issue persists. Is it likely that the error comes from one of my node's or yarn's versions?
Versions:
Yarn - 1.22.17
Node - 14.18.3
