### ISSUE TITLE
MessageFooter doesn't have access to the message object prop

### ISSUE THREAD

**Issue by micahgoodman** [GetStream/stream-chat-react-native#1127]
**Describe the bug**
Author names weren't showing up under messages automatically, so I tried to implement it myself. I found that I couldn't access the props.message object for the MessageFooter component. In the code snippet below, the output is "message object is undefined". Whereas when I pass the same custom component to MessageHeader, it correctly outputs the message object. The other props in MessageFooter seem to be available.

**Dev environment info:**
- stream-chat version 5.5.0 and stream-chat-react-native version 3.10.2
- react-native version 0.62.3
- iOS 14.4

**To Reproduce**
```
const CustomMessageFooter = (props) => {
  console.log('message object is', props.message);
};

<OverlayProvider bottomInset={bottom}>
  <Chat client={chatClient}>
    <Channel
      channel={channel}
      keyboardVerticalOffset={headerHeight}
      MessageFooter={CustomMessageFooter}
    >
      <View style={{ flex: 1 }}>
        <MessageList />
        <MessageInput />
      </View>
    </Channel>
  </Chat>
</OverlayProvider>
```

gz#19300

**Comment by vishalnarkhede** [comment]
Hey, to access message you should use the `MessageContext`

```tsx
import { useMessageContext } from 'stream-chat-react-native';

const CustomMessageFooter = () => {
  const { message } = useMessageContext();
  console.log('message object is', message);
};
```

**Comment by micahgoodman** [comment]
I see, thank you!
