### ISSUE TITLE
Bug: Enumerated List

### ISSUE THREAD

**Issue by cleandevcode** [GetStream/stream-chat-react-native#1129]
Hi, talented.
First of all, I wanna appreciate your wonderful SDK.
I develop a mobile application using this SDK and I found a bug when trying to make an enumerated list in chat with ". ".
This is the screenshot.
- without Space after dot, seems it is working well (i.e. `1.`)

- with Space after dot and trying to make the enumerated list, it happens the unexpected results. (i.e. `1. `)

This is the screenshot.
![image](https://user-images.githubusercontent.com/52365167/153011865-20bbd7bf-223a-468d-94bc-7453d5c70db5.png)

I`d really appreciate it if you take a look this issue, and let me know the solution or any things.
Sincerely.

gz#19339

**Comment by madsroskar** [comment]
Hi, @cleandevcode, could I ask which version of the SDK you're using? 

What's happening here is that the empty list item (meaning there isn't any text following the space you add after `1.`) makes the following indexed number considered a new list, and therefore reindexed from 1.

We've made some changes to lists in messages in the version currently published as beta version `4.0.0-beta.5` -- could you try it out there and see if you experience the same there? I tried it out myself just now, and it seems to work as you expect it to there.

**Comment by vishalnarkhede** [comment]
Hey @cleandevcode we have fixed alot of issues around list markdown. So I would recommend you to upgrade you to v4 of stream-chat-expo
- Releases - https://github.com/GetStream/stream-chat-react-native/releases
- Upgrade Helper guide - https://getstream.io/chat/docs/sdk/reactnative/basics/upgrading-from-v3/
