### ISSUE TITLE
Navigation goBack() not working when using OverlayProvider

### ISSUE THREAD

**Issue by 2maleek** [GetStream/stream-chat-react-native#1132]
When im using <OverlayProvider> navigation.goBack() isn't working on android device, and there some different to navigate another screen, the oppacity of screen gets blurry. but in ios working well.

This Video Using OverlayProvider and navigation goBack not work, just blank screen.

<img width="645" alt="Screen Shot 2022-02-08 at 11 35 49" src="https://user-images.githubusercontent.com/56329434/153175736-9cd7b697-a590-4745-8544-af43c0fa0e1f.png">

https://user-images.githubusercontent.com/56329434/153172156-2a78d7f7-1c6f-4a69-919b-6a61b9e25ab5.mp4

And this video i remove <OverlayProvider> and navigation working well

<img width="647" alt="Screen Shot 2022-02-08 at 11 41 06" src="https://user-images.githubusercontent.com/56329434/153176218-bd03a797-f92b-4095-8753-31322460223a.png">

https://user-images.githubusercontent.com/56329434/153176324-7f61aa7f-cd7f-484d-ada5-c38de1318c45.mp4

gz#19373

**Comment by vishalnarkhede** [comment]
Closing since its a duplicate!!
