### ISSUE TITLE
App Crashed when uploading photo / taking photo on android

### ISSUE THREAD

**Issue by charltongroves** [GetStream/stream-chat-react-native#114]
**Describe the bug**
Reactive Native: 0.61.5

App is crashing on android (both emulator (pixel 3) and physical (samsung s10)) when i attempt to attach a photo or take a photo in a conversation
I've made a few changes to the styles of some of your stock components but otherwise no changes, so i believe this is to do with code in this package.

Gif example:
![crashing](https://user-images.githubusercontent.com/15869505/72315561-ecb2c580-36de-11ea-8774-96e86edcca43.gif)

I've also noticed that attaching stuff like pdf's does not work at all on either android and iphone. Is that a known bug? is there a solution?

I've also noticed that sometimes photos of a presumably large size don't send properly.

**Dev environment info (please complete/provide the following information):**

0.6.0
Reactive Native: 0.61.5
Pixel 3xl latest android

**To Reproduce**

Go to a channel
Click on attach image/file
attempt to attach image/file
notice that the app crashes

**Expected behavior**
It shouldnt crash

**Additional context**
We recently upgraded from RN 0.59 to RN 0.61.5. This error may be due to something related to that upgrade

**Comment by charltongroves** [comment]
On further analysis, it looks like its not 'crashing' the app, but its instead just not returning to the app correctly. It instead just minimises the app.

**Comment by shodgetts** [comment]
Hey, Charlton thanks for bringing this up. Always happy to get feedback and bug reports. 

@jaapbakker88 might this bug be related to our most recent release?

**Comment by charltongroves** [comment]
Hey i finally found what cause this.

I had some dodgy code that terminated our app whenever it was suspended. Since the camera / image picker 'suspends' the app while it picks, it meant that our app got terminated in the background.

We fixed it and everything works fine now, not a problem with this package :)

**Comment by himanshi7046** [comment]
how can we show popup of choose image from photo or camera

**Comment by vishalnarkhede** [comment]
@himanshi7046 I will setup an example in cookbook on how to do it :)

**Comment by himanshi7046** [comment]
> @himanshi7046 I will setup an example in cookbook on how to do it :)

Can you please provide example as soon as possible

**Comment by vishalnarkhede** [comment]
@himanshi7046 https://getstream.io/chat/docs/sdk/reactnative/guides/message-input-customization/#replacing-attachmentpicker-with-native-image-picker
