### ISSUE TITLE
Overlay not clickable

### ISSUE THREAD

**Issue by dpark4574** [GetStream/stream-chat-react-native#1140]
IOS works fine, but on Android, the message action after long-pressing on a message is not clickable. Same with image picker. The images in the bottom sheet are not clickable for Android.

Package version:
-  "stream-chat": "^5.4.0",
    "stream-chat-react": "^6.12.2",
    "stream-chat-react-native": "^4.0.0-beta.5",
React-native version:
- "react-native": "0.66.3",

Device/Emulator (android/ios) and OS version:
- ios 13.0
- buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
        ndkVersion = "21.4.7075529"
    }

**To Reproduce**
Pretty sure the Stream React Native Sample App exhibits the same behavior.

**Expected behavior**
Should be able to click on the message actions and images.

**Additional context**
I couldn't click other overlay components on Android such as UserInfoOverlay, ChannelInfoOverlay, etc, but I was able to fix the issue by following the instructions here, https://docs.swmansion.com/react-native-gesture-handler/docs/ (wrapping the components with gestureHandlerRootHOC), but I am not sure how to go about fixing the messageAction and image picker overlays.

**Screenshots**
![Screen Shot 2022-02-08 at 12 12 58 PM](https://user-images.githubusercontent.com/63222999/153775737-907f044e-619c-4a53-9701-9b30b5ae0c16.png)
![Screen Shot 2022-02-08 at 12 18 12 PM](https://user-images.githubusercontent.com/63222999/153775740-ce750c02-b091-45bc-9f4b-4dd359e97724.png)

gz#19511

**Comment by OPNutrition** [comment]
I'm having this same issue. what was the resolution?

**Comment by OPNutrition** [comment]
I'm having this same issue. what was the resolution to this?
