### ISSUE TITLE
TypeError: setMaxNumberOfFiles is not a function. 

### ISSUE THREAD

**Issue by jr00n** [GetStream/stream-chat-react-native#1141]
```
 const userToken = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiY29vbC1ibG9jay02IiwiZXhwIjoxNjQ0NzczNzYwfQ.p8P7R93KSLsEAqhZPjFt6dbWz44GpR94GprwGejNDqM';

const streamChatUser = {id: 'cool-block-6'};
const chatClient = StreamChat.getInstance('xxx');
const connectUserPromise = chatClient.connectUser(
  streamChatUser,
  userToken,
);
const channel = chatClient.channel('livestream', 'livemeditatie'); 

<Chat client={chatClient}>
    <Channel channel={channel}>
        <MessageList />
        <MessageInput/>
   </Channel>
</Chat>

```

is producing this error:

TypeError: setMaxNumberOfFiles is not a function. (In 'setMaxNumberOfFiles(maxNumberOfFiles != null ? maxNumberOfFiles : 10)', 'setMaxNumberOfFiles' is undefined)

Just try to follow this tutorial: https://getstream.io/chat/react-native-chat/tutorial/#setup

using   "stream-chat-react-native": "3.10.2"

gz#19512

**Comment by vishalnarkhede** [comment]
@jr00n I think you missing the OverlayProvider component - https://getstream.io/chat/docs/sdk/reactnative/basics/hello_stream_chat/#overlay-provider

**Comment by vishalnarkhede** [comment]
Hey I am going to close this issue for now.
