### ISSUE TITLE
Can't see last massage sender name in channels list

### ISSUE THREAD

**Issue by ChenDimri** [GetStream/stream-chat-react-native#1143]
**Describe the bug**
Is there a way to see the name of the sender of the last massage of each channel in channels list?
I'm only able to see "you" if the last message was sent by me:

**Dev environment info (please complete/provide the following information):**

- Package version: stream-chat-react-native 3.10.2
- react-native: 0.63.3
- Emulator

**To Reproduce**
Go to channel list screen 

**Screenshots**
![Simulator Screen Shot - iPhone 11 - 2022-02-13 at 15 20 20](https://user-images.githubusercontent.com/92083836/153849465-7bac17ad-c61d-4e2d-afad-570f6ab615c2.png)

gz#19535

**Comment by vishalnarkhede** [comment]
Hey you can customize `ChannelPreviewMessage` component to implement the required UI - https://getstream.io/chat/docs/sdk/reactnative/ui-components/channel-preview-message/

**Comment by ChenDimri** [comment]
> Hey you can customize `ChannelPreviewMessage` component to implement the required UI - https://getstream.io/chat/docs/sdk/reactnative/ui-components/channel-preview-message/

I looked at it but the data that comes from preview object doesn't contain a sender name but an empty string instead when the sender is someone else..
Is this data exists at all? If not then the UI adjustments that I would implement won't matter

**Comment by ChenDimri** [comment]
Updating: There must be more than 2 members in the channel in order to see the sender name. 
Watcher user is not enough..
