### ISSUE TITLE
Image Gallery will occasionally not show the modal on image attachment tap

### ISSUE THREAD

**Issue by bryceredd** [GetStream/stream-chat-react-native#1148]
**Describe the bug**
The image gallery will sometimes incorrectly hide the UI.  Buttons are still tappable, but the only the half-opacity black background is visible

**Dev environment info (please complete/provide the following information):**

- Package version 
`"stream-chat-react-native": "4.0.0-beta.5`

- react-native or expo version
`"react-native": "^0.66.4",`

- Device/Emulator (android/ios) and OS version
iOS simulator, but also reproducible on physical iPhone

**To Reproduce**

1. Post a message with some images
2. Move from channel list screen and quickly tap on an image
3. _sometimes_ it works, _sometimes_ you only see the black overlay

**Expected behavior**
The image gallery should appear consistently.

**Additional context**
I've gone back and forth between the latest 3.10.x release and the 4.0 beta, this only happens in 4.0

**Screenshots**

https://user-images.githubusercontent.com/871014/154123613-79bf3d8d-79e3-4c47-99fe-da4f04473710.mp4

I click the image three times in the video, the first and third will correctly open the ImageGallery, the second shows only the faded black background.  Curiously though, you can dismiss the background by tapping where the X button would be, or by swiping away

gz#19663

**Comment by vishalnarkhede** [comment]
Hey @bryceredd we have managed to track down this issue and we will soon publish a patch for this!!

**Comment by vishalnarkhede** [comment]
For internal tracking - https://stream-io.atlassian.net/browse/CRNS-532?atlOrigin=eyJpIjoiMzBlY2IyMDRkYmFmNDRjMDhiMGYzMGQ3OGE5MTlmNTUiLCJwIjoiaiJ9

**Comment by andreibarabas** [comment]
For me it happens every time. I tap and see the backdrop, no matter how slow I tap on it. Can it be related @vishalnarkhede ?

**Comment by andreibarabas** [comment]
<img width="444" alt="Screenshot 2022-03-01 at 17 02 47" src="https://user-images.githubusercontent.com/2101405/156193234-71554d01-6ae9-48e6-9b56-1f0af5dc1e78.png">

**Comment by vishalnarkhede** [comment]
Hey @andreibarabas @bryceredd we have added a fix for this in `v4.1.1-beta.2`. If you can upgrade and test it, that would be really helpful :)

**Comment by bryceredd** [comment]
Tested this for a few minutes on an iOS simulator and device, both worked perfectly.  Thanks @vishalnarkhede!

@andreibarabas make sure your OverlayProvider is in the correct place, for us it was just above our `<Tab.Navigator />`
