### ISSUE TITLE
yarn start is not an available command, project won't start

### ISSUE THREAD

**Issue by danstepanov** [GetStream/stream-chat-react-native#1155]
**Describe the bug**

The docs indicate to run `yarn && yarn start` to run the project; however, `start` is not an available script.

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native/stream-chat-expo)
- react-native or expo version
- Device/Emulator (android/ios) and OS version

**To Reproduce**

1. Clone the project
2. Run `yarn && yarn start`
3. `error Command "start" not found.`

**Expected behavior**

I expect the app to run in the simulator.

**Additional context**
Node:  14.17.4
Yarn: 1.22.17

**Screenshots**
<img width="610" alt="Screen Shot 2022-02-19 at 6 26 41 PM" src="https://user-images.githubusercontent.com/5482800/154822506-59bc053d-1810-4b94-b59f-36a470e32404.png">

gz#19831

**Comment by vishalnarkhede** [comment]
Hey, root directory is not exactly yarn runnable project. If you want to run some example application, then you should `cd` into one of the example directories and then do `yarn && npx pod-install && npx react-native run-ios`

**Comment by danstepanov** [comment]
@vishalnarkhede worth updating the README to reflect that?
