### ISSUE TITLE
Messages not being auto marked as read while inside chat on iOS

### ISSUE THREAD

**Issue by estampscvt** [GetStream/stream-chat-react-native#1159]
When you open a channel, it immediately marks all messages as read. However, if you stay in that channel and talk to someone, all of the messages that get sent in that channel will stay marked as 'unread' until you make a scroll action on the screen or close/reopen.

Dev environment info (please complete/provide the following information):

Package version. 3.8.2
Device/Emulator (iOS): iPhone 12 - iOS 14.1

1. Go into a chat from an ios device (user A)
2 Send some messages to that user from another device (user B)
3 Notice the read receipts for User B dont update until user A does a scroll action. Also if they exit the chat the messageslist will show unread messages for User A

Expected behavior
Messages coming into a channel which you are currently looking at should mark those messages as read.

gz#19987

**Comment by vishalnarkhede** [comment]
Hey @estampscvt I would recommend you to upgrade to v3.10.2, since we made some fixes around this in recent versions.

**Comment by vishalnarkhede** [comment]
Please let me know if you are able to reproduce this on latest version.

**Comment by estampscvt** [comment]
@vishalnarkhede Thanks for the quick response. It is still persisting on the latest version unfortunately. I updated my comment with a bit more information about the test device I am using

**Comment by vishalnarkhede** [comment]
Hey @estampscvt could you please check if the read events are enabled on your dashboard?

<img width="1122" alt="Screenshot 2022-02-25 at 16 24 36" src="https://user-images.githubusercontent.com/11586388/155741307-dd73a27a-d850-42e2-980e-29120da609c3.png">

**Comment by estampscvt** [comment]
@vishalnarkhede read events are working when I make a scroll action on the messages list or exit/return. It is also working as expected on Android

**Comment by raksahb** [comment]
Read events are enabled for our app
![Stream___Channel_Type](https://user-images.githubusercontent.com/2277664/156254869-fdce487c-b5dd-4ff0-8327-2298777e7ce6.png)
d

**Comment by vishalnarkhede** [comment]
@raksahb could you share some screenrecording?

**Comment by estampscvt** [comment]
https://user-images.githubusercontent.com/91638012/156452717-56ce359a-12df-4e7d-9560-678a5b92dbd9.mov

@vishalnarkhede Here is a video with an iOS device on the right and android device on the left. You will see that when a chat is sent to the iOS device that the read receipt doesnt update. Event after I am typing send a follow up. The read receipt updates correctly from the opposite scenario. Then at the end I scroll on the screen of the iOS device and the read receipt finally updates.

So there seems to be some iOS specific issue

**Comment by vishalnarkhede** [comment]
@estampscvt thanks for the screenrecording. Could you please confirm one more scenario for me?

I can see from the screen recording that the messages length is lesser than visible screen. Could you also please test it for the case when you have more messages than the visible screen height (basically when list is scrollable)?

**Comment by estampscvt** [comment]
@vishalnarkhede same issues in that scenario unfortunately

**Comment by estampscvt** [comment]
@vishalnarkhede We are just wondering if you have everything you need to determine if this is a bug

**Comment by khushal87** [comment]
@estampscvt Are you still facing this issue?

**Comment by estampscvt** [comment]
@khushal87 Yes this is still occurring. We are on version 6.4 currently

**Comment by vanGalilea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/1159?planning-poker) with ZenHub @khushal87 @madsroskar @santhoshvai @vishalnarkhede

**Comment by vanGalilea** [comment]
Hey @estampscvt we tried to reproduce this behavior, yet no success.

To pinpoint this issue as fast as possible, we would like to ask you to share a minimalistic repo where the problem is reproduced.
The fastest way to achieve this is with the following command to create a new RN project with Stream chat in it:

`npx react-native init MyApp --template stream-chat-react-native-template`

Please then share a Github repo with us, where we can explore the issue ourselves.

**Comment by santhoshvai** [comment]
I am closing this issue due to lack of response. Feel free to reopen if this occurs again

**Comment by enisit** [comment]
**@khushal87** 

I’m facing a similar issue and have attached a screen recording for reference. The problem occurs when sending the first message while the last message in the channel is from another user. 

In this case:

1. The `MessageList` does not auto-scroll to the new message.
2. The message is not marked as "read."

However, once the user manually scrolls to the bottom, the message gets marked as "read," and subsequent new messages function correctly, with proper auto-scroll and read status.

---

https://github.com/user-attachments/assets/7e715359-9d1c-41d2-9cae-8f4d9241be13
