### ISSUE TITLE
System message displays current time, not sent time

### ISSUE THREAD

**Issue by bscharfstein** [GetStream/stream-chat-react-native#117]
**Describe the bug**
When we send a system message is displays the time sent as the current time, not the time the message was sent. 

- Package version: 0.6.0
- react-native
-iOS and android

**To Reproduce**

1. send a system message
2. observe that time always displays current time

**Expected behavior**
Time displays time sent

**Comment by cenzovit** [comment]
Appears MessageSystem references message.received_at (which is undefined) causing Moment.js to create a Moment object for the current time. MessageSystem should instead reference message.created_at.

**Comment by vishalnarkhede** [comment]
@bscharfstein thanks for reporting this. I will look into it and get back to you soonish !!

**Comment by vishalnarkhede** [comment]
@bscharfstein  @cenzovit  Fix has been published - [v0.6.3](https://github.com/GetStream/stream-chat-react-native/releases/tag/v0.6.3)

Please let us know if it works !!
