### ISSUE TITLE
ChannelPreviewMessage incorrect props in documentation

### ISSUE THREAD

**Issue by treyshedrick** [GetStream/stream-chat-react-native#1173]
**Describe the bug**
Docs say to use lastMessagePreview as props for the ChannelPreviewMessage component. The correct props are latestMessagePreview

**To Reproduce**

1. Go to [docs page](https://getstream.io/chat/docs/sdk/reactnative/ui-components/channel-preview-message/)
2. Log correct props in console when creating component
3. Compare

**Comment by vishalnarkhede** [comment]
Thanks for bringing this up @treyshedrick !! We have updated our docs!
