### ISSUE TITLE
No push notification to firebase when app is still in foreground

### ISSUE THREAD

**Issue by sandergo90** [GetStream/stream-chat-react-native#1178]
Hi,

We are trying out the new v2 push notifications, but are having trouble implementing foreground notifications.

As the new docs are saying, it shouldn't matter anymore if a user is online or offline to receive notifications.
When looking at the Webhook & Push Logs dashboard on the stream website, there is no push log when my application is still in foreground.

When I go to the background, and then send a new message to that specific user, I can see a log inside this table and I'm receiving the notification inside my background handler. 

What should be the correct behaviour now?

Kind regards,
Sander

gz#20202

**Comment by sergeyzhukov** [comment]
Same issue, background / foreground not receiving pushes. But stream chat:push:test --user_id works fine, so everything connected correctly. But no push on any of new message inside the channel @vishalnarkhede

**Comment by vishalnarkhede** [comment]
@sergeyzhukov could you confirm if all the following requirements are matched for the channel/user? https://getstream.io/chat/docs/sdk/reactnative/guides/push-notifications-v2/#requirements

**Comment by sandergo90** [comment]
@vishalnarkhede can you verify if foreground notifications are broken?

**Comment by sergeyzhukov** [comment]
@vishalnarkhede yes. User is member of the channel, user not muted, user device is added to user (test push from CLI working fine), no skip_push, user have only one device

**Comment by sergeyzhukov** [comment]
And, you know, push V1 was absolutely great, templates were amazing and fill all necessary use cases. The only thing missing there - push notifications for online users. 

Now its completely broken, in order to display push notification from background app should wake up and try to load data from server, which consumes battery and not working correctly all the time (low power mode, disabled background fetch, etc)

**Comment by vishalnarkhede** [comment]
@sergeyzhukov we are working on including more information about message in push v2 at the moment, so that network calls won't be necessary

**Comment by sergeyzhukov** [comment]
@vishalnarkhede any updates? customers are already angry without working push notifications. And maybe you have more info why getstream service are even not trying to send push?

**Comment by vishalnarkhede** [comment]
@sergeyzhukov btw we are not planning to drop support for v1 push notifications. We recommend to move to v2 in case you need more control over the notifications, but v1 will stay as well if thats working well for you. So if v1 worked well for you without issues, I would suggest you switch back to it.

**Comment by sandergo90** [comment]
But as stated in the changelog, a couple of issues we are having with v1 should be resolved in v2, so we would rather use the v2 version of course. But not only will v2 version not work for foreground notifications, how would you suggest we implement notifications if the application is killed? I've already tried logging an issue for it at fresh desk, but no response...

> Hi,
I would like to raise another issue with the v2 push notifications.
Currently it’s not possible to show a notification, using notifee for example, when the application is in a quit state (meaning app is killed, swiped away by the user).
I’ve already created a ticket for this on the GitHub Issue stream of notifee (https://github.com/invertase/notifee/issues/330). But as they are saying, data-only notifications coming from stream, cannot be used when the application is killed.
How would you suggest we implement push notifications when the app is killed?

**Comment by vishalnarkhede** [comment]
@sandergo90 I will update you on this part soon :)

**Comment by vishalnarkhede** [comment]
> And, you know, push V1 was absolutely great, templates were amazing and fill all necessary use cases. The only thing missing there - push notifications for online users.

@sandergo90 quick fyi about this, we now allow push notification v1 also for online users. It's enabled by default for new apps. For your case, if you can drop us a request on support@getstream.io with your app id, we can enable it for your app as well.

**Comment by sergeyzhukov** [comment]
@vishalnarkhede in push v1 APN badge is empty for some reason, but in template we are using

        "badge": "{{ unread_count }}", 
        
        
APP ID 86661

**Comment by sergeyzhukov** [comment]
@vishalnarkhede please correct documentation here https://getstream.io/chat/docs/react/push_template/, section Defaults
<img width="564" alt="Screen Shot 2022-03-15 at 17 19 28" src="https://user-images.githubusercontent.com/1446268/158386394-ccad8b0c-295a-40c0-9710-06ec47be5f00.png">

**Comment by vishalnarkhede** [comment]
@sergeyzhukov thanks for pointing it out, we have updated it.

**Comment by sergeyzhukov** [comment]
@vishalnarkhede I tried the following case related to allowing push notifications in V1 for online users and looks like its not working. 

I logged in as a same user both on web and iOS. Selected different channels as an active on the web and iOS. No push notifications in mobile at all. If I will close web version - push notifications will be received.

**Comment by vishalnarkhede** [comment]
@sergeyzhukov we haven't enabled it (push for online users) yet for your app. Just needed confirmation about it. I will ask the backend team to do so now

**Comment by sergeyzhukov** [comment]
@sandergo90 for V1 library https://github.com/wix/react-native-notifications working perfectly for both foreground / background / killed mode.

**Comment by sandergo90** [comment]
Yes, for v1 library no problem. But as the v2 documentation suggested, this should be possible but no notifications received when in foreground.

**Comment by vishalnarkhede** [comment]
@sandergo90 are you atleast able to receive data notification while in foreground? Can you see the console.log in following code:

```tsx
  useEffect(() => {
    const unsubscribe = messaging().onMessage(async remoteMessage => {
      console.log('received a message ', client.tokenManager.getToken());
      const message = await client.getMessage(remoteMessage.data.id);
      await notifee.displayNotification({
        title: message.message.text,
        body: message.message.text,
        android: {
          channelId: 'msg',
        },
      });
    });

    return unsubscribe;
  }, []);
```

**Comment by sandergo90** [comment]
@vishalnarkhede Well no, that's the problem. When app is still in foreground, no data message is received.

**Comment by vishalnarkhede** [comment]
@sandergo90 whats your app id?

**Comment by sandergo90** [comment]
1153899

**Comment by terrynip506** [comment]
hi @vishalnarkhede, i am having the same problem after migrating to v2. My notification works fine on v1 (with nicely customise the notification content) , except i am wondering v1 only supports pushing to first 100 members in a channel? that's something pushing me to upgrade to v2

**Comment by mfbx9da4** [comment]
Something I am missing from v2 is how to set app badge count, this no longer seems to be in the payload? Any guidance on this?

**Comment by santhoshvai** [comment]
@sandergo90 In your app "1153899", I do see that the push notification is only enabled for offline users. If you can drop us a request on [support@getstream.io](mailto:support@getstream.io) with your app id, we can enable push notifications for online users as well. Then you should get the push notification while in foreground (for the online user). 

To be clear, we enable push notifications for online users by default for new apps. For apps migrating to V2 from V1. We dont enable push notifications for online users by default to not break the previous behaviour. 

I hope this is clear. If you would any more clarification or support please don't hesitate to contact us.

**Comment by sandergo90** [comment]
Hi,

Thanks, I've requested it now.
