### ISSUE TITLE
Custom attach icon of MessageInput component

### ISSUE THREAD

**Issue by renanmav** [GetStream/stream-chat-react-native#119]
**Describe the feature**
I would like to provide a custom attach icon to the `MessageInput` component

Currently its hard coded, see: 
- https://github.com/GetStream/stream-chat-react-native/blob/fa5e2b60df3fcaaf186cc85a047436e301900043/src/components/MessageInput.js#L762
- https://github.com/GetStream/stream-chat-react-native/blob/fa5e2b60df3fcaaf186cc85a047436e301900043/src/components/MessageInput.js#L25

**Comment by vishalnarkhede** [comment]
Hey @renanmav Thanks for brining this up. We will add a prop for this feature soonish :)

**Comment by vishalnarkhede** [comment]
@renanmav this has been published - [v0.6.3](https://github.com/GetStream/stream-chat-react-native/releases/tag/v0.6.3)

You can pass `AttachButton` prop to `MessageInput` component. Check our default AttachButton component to build your own - https://github.com/GetStream/stream-chat-react-native/blob/master/src/components/AttachButton.js

Please let us know if it works for you :)

**Comment by plotic** [comment]
Hey guys can you please provide a sample that would work with functional component ?
