### ISSUE TITLE
Cannot start new direct chat: "You can't send messages in this channel"

### ISSUE THREAD

**Issue by jordanj77** [GetStream/stream-chat-react-native#1191]
**Describe the bug**
Can't start a new chat with an individual - it says "You can't send messages in this channel".  See Screenshot below.

**Dev environment info:**

- Package version: stream-chat-react-native v4.1.2
- Device/Emulator: iOS Simulator - iPhone 13 - iOS 15.0

**To Reproduce**
1. Clone & install this repo, launch the Sample App
2. Click the pencil icon in the top right to start a new chat
3. Choose a user to chat with (a user with which you don't already have an open conversation)
4. BUG

**Expected behavior**
User should be able to start the new conversation.

**Additional context**
We are facing the same problem in our app when trying to upgrade from v3 to v4.

**Screenshots**
![IMAGE 2022-03-07 18:14:27](https://user-images.githubusercontent.com/1179844/157152717-4f342403-0269-4ae1-8668-b43126b3e3fb.jpg)

gz#20342

**Comment by khushal87** [comment]
@jordanj77 I have fixed this in #1203. Thanks for reporting 😄

**Comment by jordanj77** [comment]
Great, fix confirmed, thanks!

**Comment by jordanj77** [comment]
Great, fix confirmed, thanks!
