### ISSUE TITLE
ChannelList "Pull to refresh" no longer works in v4

### ISSUE THREAD

**Issue by andreibarabas** [GetStream/stream-chat-react-native#1192]
**Describe the bug**
You have a channel list, and then you do a pull to refresh, the channels will not actually be queried. 

**Dev environment info (please complete/provide the following information):**

- Package version: stream-chat-react-native@4.1.1
- react-native
- device & emulator

**To Reproduce**
It's a little bit harder to reproduce as your example has event listeners that automatically add new channels to the list, but by simply looking at this condition https://github.com/GetStream/stream-chat-react-native/blob/develop/package/src/components/ChannelList/hooks/usePaginatedChannels.ts#L75-L77

and the fact that `hasUpdated` only listens for `loadChannels` (next page) and not `refresh` I think you can see the point

https://github.com/GetStream/stream-chat-react-native/blob/develop/package/src/components/ChannelList/hooks/usePaginatedChannels.ts#L63

**Expected behavior**
Pull to refresh to always work

**Possible solution**
The way we patched it internally is to add, but not quite sure if it's the way it should be solved in the SDK
```
    const hasUpdatedData =
      queryType === 'loadChannels' ||
      queryType === 'refresh' ||
      ...
```

gz#20345

**Comment by vishalnarkhede** [comment]
Thanks alot @andreibarabas for bringing this up and doing a thorough investigation as well. We will try to publish a patch for this ASAP :)
