### ISSUE TITLE
Avatar component breaks inside react-native-paper Portal component

### ISSUE THREAD

**Issue by treyshedrick** [GetStream/stream-chat-react-native#1194]
**Describe the bug**
When using react-native-paper with this library. If a stream chat `Avatar` is placed inside a Portal, we receive the error 

```
 Unhandled Promise Rejection (id: 3):
TypeError: undefined is not an object (evaluating '_useTheme$theme$avata.container')
Avatar{avatar
```

**Dev environment info (please complete/provide the following information):**

- stream-chat-react-native 4.1.0
- react-native
- ios 14.4

**To Reproduce**

1. Download other react-native-paper
2. Place Avatar component inside a Portal component
3. See error

**Expected behavior**
Avatar component should render and have no errors

**Additional context**
This is an issue if anyone wants to use this component inside of a modal.

**Screenshots**
![Screen Shot 2022-03-08 at 3 03 04 PM](https://user-images.githubusercontent.com/35882658/157325404-48c30ea4-aca0-41b0-97aa-3c45c370da3a.png)

gz#20377

**Comment by vishalnarkhede** [comment]
@treyshedrick Is the Portal/Modal getting rendered outside the OverlayProvider/Chat component tree? In that case chat components won't have access to the ThemeProvider context.

**Comment by treyshedrick** [comment]
Yes it is. Makes sense now. Went ahead and wrapped ThemeProvider around the `react-native-paper` Provider so it can be accessible in the Portal component if anyone else does run into this issue. 

Let me know if you can think of any issues this may cause. Thanks!

```
import { ThemeProvider } from "stream-chat-react-native";
import { Provider } from "react-native-paper";

<ThemeProvider>
    <Provider>{children}</Provider>
<ThemeProvider>
```

**Comment by vishalnarkhede** [comment]
It should be fine :)
