### ISSUE TITLE
Missing SendButton prop of MessageInput on typescript type definition

### ISSUE THREAD

**Issue by renanmav** [GetStream/stream-chat-react-native#120]
This prop exists but isn’t declared on the `.d.ts` file.
https://github.com/GetStream/stream-chat-react-native/blob/fa5e2b60df3fcaaf186cc85a047436e301900043/src/components/MessageInput.js#L179-L182

https://github.com/GetStream/stream-chat-react-native/blob/fa5e2b60df3fcaaf186cc85a047436e301900043/types/index.d.ts#L198

**Comment by tbarbugli** [comment]
thank you for reporting this; we are doing a major update to improve TS support. Jaap will either patch this on current version or include it on the next release

**Comment by vishalnarkhede** [comment]
@renanmav fix has been published - [v0.6.3](https://github.com/GetStream/stream-chat-react-native/releases/tag/v0.6.3)
