### ISSUE TITLE
Unable to interact with message reactions and add members overlays on Android

### ISSUE THREAD

**Issue by gavinv** [GetStream/stream-chat-react-native#1202]
**Describe the bug**
On Android, long-pressing a message will open the reactions context menu but unable to interact. This seems to happen with other overlays in the demo app such as the "Add Members to Channel" overlay menu. Must use device back button to close the overlay. No errors logged.

**Dev environment info (please complete/provide the following information):**

- stream-chat-react-native/stream-chat-expo 3.10.2
- react-native 0.64.3 expo 44.0.0
- Running on Samsung Galaxy Note 20 Ultra, Android version 12

**To Reproduce**

1. Go to any message/channel
2. Long-press single message
3. Attempt to add reaction, start thread, etc.

**Expected behavior**
Ability to interact with overlay menus.

**Additional context**
I assume this may be coming from the OverlayProvider, but I haven't been able to find the root issue.

**Screenshots**

gz#20466

**Comment by khushal87** [comment]
@gavinv This is solved in 4.1.1. Can you please try updating the app and try again?
Go through the upgrade helper guide - https://getstream.io/chat/docs/sdk/reactnative/basics/upgrading-from-v3/
Let us know if it doesn't work after the upgrade. Thanks, hope this helps 😄

**Comment by vishalnarkhede** [comment]
Also what version of react-native-gesture-handler are you using?

**Comment by vishalnarkhede** [comment]
Going to close this issue for now. But I would recommend you to check the version of gesture handler dependency and follow the necessary installation steps - https://getstream.io/chat/docs/sdk/reactnative/#additional-steps

**Comment by OPNutrition** [comment]
@vishalnarkhede I just updated all my dependencies and am still running into this issue

react-native: 0.68.2
react-native-gesture-handler: 2.2.1
react-native-reanimated: 2.8.0
stream-chat-expo: 4.5.0

Running on Samsung Galaxy J3 Orbit, Android version 9

**Comment by OPNutrition** [comment]
Oops. Forgot to wrap with GestureHandlerRootView
