### ISSUE TITLE
Error: Component Exception

### ISSUE THREAD

**Issue by cleandevcode** [GetStream/stream-chat-react-native#1205]
`increaseSubscriberCount is not a function.(In 'increaseSubscriberCount({cid: cid})', 'increaseSubscriberCount' is not undefined.`

![image](https://user-images.githubusercontent.com/52365167/158076031-0d5a971c-d652-49f6-bdc6-11e8dbcc6bed.png)

My stack:
stream-chat: 6.1.0
stream-chat-expo: ^4.1.0
expo: ^40.0.0

Now I could see `Channel List` items.
When I try to go `thread`, I see this error.

Please Help me.

gz#20577

**Comment by vishalnarkhede** [comment]
@cleandevcode have you configured OverlayProvider component?

**Comment by cleandevcode** [comment]
@vishalnarkhede Thank you. After wrapping with OverlayProvider, it works well.
