### ISSUE TITLE
Unable to use sendMessage function when customizing Message Input

### ISSUE THREAD

**Issue by cleandevcode** [GetStream/stream-chat-react-native#1213]
Hello, talented.
My tech stack:
stream-chat: 6.1.0
stream-chat-expo: ^4.1.0
expo: ^40.0.0

This is my code (brief updated):
```
const CustomSendButton = () => {
   const { sendMessage } = useMessageInputContext();
   return (
     <View>
        <TextInput ... />
        <TouchableOpacity onPress={sendMessage}>
            <Text>Send Message</Text>
        </TouchableOpacity>
     </View>
   )
}


const CustomMessageInput = () => (
   <MessageInput 
        channel={channel}
        Input={()=><CustomSendButton  />}
    />
);
```

But I could not send a message.

Please help me.
Thank you

gz#20701

**Comment by monstaro** [comment]
Hi @cleandevcode - what version of stream-chat-react-native are you on? And are you getting any errors when attempting to send the message?

**Comment by cleandevcode** [comment]
@monstaro I did not use `stream-chat-react-native`. 
I`ve used `stream-chat-expo`: ^4.1.0

**Comment by sergeyzhukov** [comment]
@cleandevcode do not forget to pass props to custom input like this

`Input={props => <ChatInput {...props} />}`

and be sure that CustomMessageInput is inside all necessary providers / contexts

**Comment by cleandevcode** [comment]
Thank you for your quick response.
I could fix by setting `text` and `onChange` in `useMessageInputContext`
```
const { sendMessage, text, onChange } = useMessageInputContext();

return (
<View>
   <TextInput value={text} onChange={onChange} />
   <Button onPress={sendMessage}>
     <Text>Send Message</Text>
   </Button>
</View>
)


```


Thanks all, again.
