### ISSUE TITLE
Date separator remain when all messages have been deleted

### ISSUE THREAD

**Issue by hankwz** [GetStream/stream-chat-react-native#1216]
We have a customization that hides all the deleted messages in chat using the following in the Channel component from `stream-chat-react-native`

> MessageDeleted={() => null}

When all the messages have been deleted by the user, the date separator still show up on the message list. 

- Package version stream-chat-react-native: 4.1.4
- react-native: 0.66.4
- iOS 15.2 simulator and Android 11 emulator

**To Reproduce**
1. Send a message on a new date 
2. Delete the sent message

**Expected behavior**
The date separator should not display when all messages are deleted for that date
![Simulator Screen Shot - iPhone 13 - 2022-03-17 at 11 17 46](https://user-images.githubusercontent.com/10568063/158871905-144f9dc5-16a2-4f9a-94ab-a56455309da4.png)

**Comment by vishalnarkhede** [comment]
Hey @hankwz please use instead https://getstream.io/chat/docs/sdk/reactnative/core-components/channel/#deletedmessagesvisibiltytype. MessageDeleted prop is only for customization purpose.
