### ISSUE TITLE
Latest message only show first 20 chars

### ISSUE THREAD

**Issue by familywiser1** [GetStream/stream-chat-react-native#122]
**Describe the bug**
Latest message only show first 20 chars. I want to show more than 20 chars. 

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native/stream-chat-expo): stream-chat-expo
- react-native or expo version: expo 
- Device/Emulator (android/ios) and OS version: all

**To Reproduce**

Follow react native tutorials https://getstream.io/chat/react-native-chat/tutorial/#custom-preview. I think the problem is at https://github.com/GetStream/stream-chat-react-native/blob/master/src/components/ChannelPreview.js#L75 

**Expected behavior**
Return full text of the latest message. You can use Text element and truncate to 1 line.

**Comment by vishalnarkhede** [comment]
Hey @familywiser1 , thanks for bringing this up. We will add the required feature to our ChannelPreview component soon :)

**Comment by vishalnarkhede** [comment]
@familywiser1 this has been published - [v0.6.3](https://github.com/GetStream/stream-chat-react-native/releases/tag/v0.6.3)

Please let us know if it works for you :)
