### ISSUE TITLE
Support photo albums in the AttachmentPicker

### ISSUE THREAD

**Issue by madsroskar** [GetStream/stream-chat-react-native#1222]
The current implementation gets photos from [the camera roll](https://github.com/react-native-cameraroll/react-native-cameraroll#getphotos). 

We could also allow users to navigate their [albums](https://github.com/react-native-cameraroll/react-native-cameraroll#getalbums) and upload photos that way.

**Comment by vanGalilea** [comment]
Let's suggest[this](https://getstream.io/chat/docs/sdk/reactnative/guides/message-input-customization/#replacing-attachmentpicker-with-native-image-picker) in the meanwhile

**Comment by vanGalilea** [comment]
This issue was moved to an internal backlog list of less urgent feature/docs requests.
