### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'updated_at.toISOString') when trying to send a message

### ISSUE THREAD

**Issue by cheejiayuan512** [GetStream/stream-chat-react-native#1227]
**Describe the bug**
On sending a message using default components, I am getting an error as follows
**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native/stream-chat-expo)
- ```"expo": "~44.0.0",
    "expo-apple-authentication": "~4.1.0",
    "expo-application": "^4.0.2",
    "expo-auth-session": "~3.5.0",
    "expo-blur": "~11.0.0",
    "expo-camera": "~12.1.2",
    "expo-constants": "~13.0.1",
    "expo-document-picker": "~10.1.3",
    "expo-facebook": "~12.1.0",
    "expo-file-system": "~13.1.4",
    "expo-haptics": "~11.1.0",
    "expo-image-manipulator": "~10.2.0",
    "expo-image-picker": "~12.0.1",
    "expo-media-library": "~14.0.0",
    "expo-random": "~12.1.1",
    "expo-sharing": "~10.1.0",
    "expo-status-bar": "~1.2.0",
    "expo-updates": "~0.11.6",
    "expo-web-browser": "~10.1.0",
    "firebase": "^9.6.6",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-gesture-handler": "~2.1.0",
    "react-native-reanimated": "~2.3.1",
    "react-native-safe-area-context": "3.3.2",
    "react-native-screens": "~3.10.1",
    "react-native-svg": "12.1.1",
    "react-native-web": "0.17.1",
    "stream-chat": "^6.0.0",
    "stream-chat-expo": "4.2.0",
    "stream-chat-react-native-core": "4.2.0"```
- Device/Emulator (android/ios) and OS version
- I have tried it out on my android and iOS device

**To Reproduce**

**Expected behavior**
It worked before I upgraded to stream-chat-expo 4.2.0
**Additional context**

**Screenshots**

![image](https://user-images.githubusercontent.com/13083403/160358020-8402f9be-8a9f-499d-b1b3-bc8c66b20b63.png)

gz#21123

**Comment by cheejiayuan512** [comment]
After deleting node-modules and yarn.lock, removing stream-chat and stream-chat-react-native-core from package.json, runs perfectly again.

**Comment by rajkapoordev** [comment]
> After deleting node-modules and yarn.lock, removing stream-chat and stream-chat-react-native-core from package.json, runs perfectly again.

This thing won't help me

**Comment by vishalnarkhede** [comment]
Hey @rajkapoordev please upgrade to `v4.3.0-beta.4`.  This issue has been fixed, we will publish the stable version soon :)

**Comment by mattlennon3** [comment]
Seeing this too. Thanks for the fix :)

**Comment by mattlennon3** [comment]
Can't see this mentioned in the latest `4.3.0` release notes, but it appears to be fixed 🤞 
Thanks @vishalnarkhede

**Comment by ayush-shta** [comment]
Seeing similar issue when sending a message in thread.

**Comment by denizmersinlioglu** [comment]
@vishalnarkhede  we use `"stream-chat-react-native": "^4.3.1"` and have the same problem with @ayush-shta

`Seeing similar issue when sending a message in thread.`

**Comment by madsroskar** [comment]
I'll reopen this issue - I think the fix that was merged didn't cover all cases where this could happen, I'm guessing doing a similar fix for threads should be possible.
