### ISSUE TITLE
Avatar initials are not displayed in ChannelList

### ISSUE THREAD

**Issue by familywiser1** [GetStream/stream-chat-react-native#123]
**Describe the bug**
Avatar initials are not displayed in ChannelList. Channel Screens shows the avatar initials correctly. 

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native/stream-chat-expo): latest stream-chat-expo
- react-native or expo version: expo
- Device/Emulator (android/ios) and OS version: all

**To Reproduce**
Follow getting started with react native tutorial at https://getstream.io/chat/react-native-chat/tutorial/
I think the problem is at https://github.com/GetStream/stream-chat-react-native/blob/master/src/components/ChannelPreviewMessenger.js#L84. This method does not pass `name` to Avatar

**Expected behavior**
Avatar initials are shown by ChannelPreviewMessenger in ChannelList.

**Comment by vishalnarkhede** [comment]
@familywiser1 Thanks for reporiting this. We will fix it as soon as possible!!
