### ISSUE TITLE
Channels in ChannelList aren't clickable (?)

### ISSUE THREAD

**Issue by exhilaratedguy** [GetStream/stream-chat-react-native#1232]
**Describe the bug**
The channels visible under ChannelList aren't clickable. Or rather, I hear a clicking noise on the emulator, but nothing happens. Passing the `onSelect` prop to the ChannelList component as `onSelect={ (channel) => { console.log("pressed"); }}` produces no output in the terminal.

**Dev environment info (please complete/provide the following information):**

- stream-chat-expo 4.2.0
- expo 44.0.6
- Android emulator API 30 - Android 11.0 + running on my own device (MIUI 12.5 - Android 11) through the Expo Go app

**To Reproduce**

1. Create project with `expo init Messenger -t tabs`
2. Follow [Hello Stream Chat tutorial](https://getstream.io/chat/docs/sdk/reactnative/basics/hello_stream_chat/) up until the ChannelList entry.
3. Add `onSelect={ (channel) => { console.log("pressed"); }}` to ChannelList component
4. Run the build on emulator
5. Click on a channel. The clicking sound is played, but no animation indicating it was pressed is displayed and nothing is logged to the console.

**Expected behavior**
The message "pressed" should have been printed on the terminal.

**Additional context**
No errors or warnings. Pastebin link of [App.tsx](https://pastebin.com/xhzFcrF1).
I have also created one without the tabs template just in case, and it produces the same behaviour.

**Screenshots**
Not really applicable.

gz#21172

**Comment by vishalnarkhede** [comment]
@exhilaratedguy Is this an option for you? https://github.com/GetStream/stream-chat-react-native/issues/976#issuecomment-962428909

**Comment by exhilaratedguy** [comment]
@vishalnarkhede I am not using any Navigators at all. I put a Pastebin link to my App.tsx on the issue, [this link](https://pastebin.com/xhzFcrF1). You can see my only structure is SafeAreaProvider -> OverlayProvider -> Chat -> ChannelList (as according to the Hello Stream Chat docs).

**Comment by vishalnarkhede** [comment]
@exhilaratedguy is this Android only issue? Or can you see this on iOS as well

**Comment by exhilaratedguy** [comment]
I only have means to test this on Android. Sorry, I forgot to mention that detail. I'm on a Windows machine and have no access to Macs or iPhones really.

**Comment by exhilaratedguy** [comment]
@santhoshvai This worked perfectly, thank you. I hadn't found the troubleshooting docs page when googling before opening the issue (I think I googled something like 'stream chat components not clickable/pressable'), an oversight on my part. Maybe you can add a footnote linking to that solution on the Hello Stream docs :)

Thanks once again.
