### ISSUE TITLE
Feature Request: (optionally) show unread count for each channel in ChannelList

### ISSUE THREAD

**Issue by familywiser1** [GetStream/stream-chat-react-native#124]
I want to show the unread count for each channel. I am able to do that by customizing `ChannelPreviewMessenger` the as suggested in https://getstream.io/chat/react-native-chat/tutorial/. 

However, it would be nice to have an option in ChannelList component to show the unread count. 

```
<Chat client={chatClient} style={theme}>
                <ChannelList  filters={filters}  sort={sort}  options={options}
                 showUnreadCount={true}/>
</Chat>
```

**Comment by vishalnarkhede** [comment]
Hey @familywiser1 this will be added soon on our end!!

**Comment by tharun208** [comment]
@vishalnarkhede , I like to work on this

**Comment by sclavijo93** [comment]
Hi, any news with this? 😅

**Comment by virdesai** [comment]
@sclavijo93 we are implementing this in some redesigns that are underway

**Comment by vishalnarkhede** [comment]
Closing this for now. Please keep an eye for next major release for new UI components :)
