### ISSUE TITLE
Use app setting for permitted attachment types

### ISSUE THREAD

**Issue by vishalnarkhede** [GetStream/stream-chat-react-native#1254]
App settings can be accessed from `/app` endpoint, which provides configured/allowed attachment (image/file) types. This setting should be used within SDK to only show the allowed attachment types within image picker and file picker.

**Comment by Enigma-I-am** [comment]
We currently can't tell the file/image type before sending it to the client on iOS implying we can't tell if the file is supported or not using appSettings. 
We are currently implementing this feature be updating the state of the app based on the response from backend informing us whether a file/image is not supported.
