### ISSUE TITLE
Broken URL expansion with the v3 wiki tutorial

### ISSUE THREAD

**Issue by madsroskar** [GetStream/stream-chat-react-native#1258]
When following [this tutorial](https://github.com/GetStream/stream-chat-react-native/wiki/Tutorial-v3.0), a customer has reported an issue where switching from the example API key used to their own API key, URLs aren't expanded as expected.

**Comment by vanGalilea** [comment]
A lot of links are broken, in the short term let's fix it, and in the long term discuss having one source of truth for the tutorial via Stream's website or such

**Comment by vanGalilea** [comment]
Closing this due to new tutorial
