### ISSUE TITLE
No option to configure APNS payload with mutable-content to activate the notification service extension (for Firebase)

### ISSUE THREAD

**Issue by mfbx9da4** [GetStream/stream-chat-react-native#1260]
I am trying to configure a notification service extension with stream. This is possible for the [swift SDK](https://getstream.io/chat/docs/sdk/ios/guides/push-notifications/#notification-service-extension).

As far as I can see, there is no way to configure the APNS payload and enable `mutable-content` neither with v1 push notifications nor with v2 push notifications. Could you please confirm there is no way to configure this at this point in time?

Thanks

gz#21472

**Comment by santhoshvai** [comment]
@mfbx9da4 , thanks for raising this issue. We will need to clarify regarding customization in our documentation. 

A new default APNS template is being deployed soon by our backend team with ` "mutable-content" : 1`, We would enable further APNS template customization through updating app settings via our backend SDKs. Via template customization, you would be able to customize the APNS payload. 

Our backend team is actively working in this space and we will update the documentation regarding template customization very soon.

**Comment by santhoshvai** [comment]
@mfbx9da4 our default payload now has `"mutable-content" : 1`.  Please look at the details of the default templates at https://getstream.io/chat/docs/javascript/push_template/?language=javascript. You can also use the JS SDK to customize the payload to your liking as described in the link.

The react-native SDK documentation at https://getstream.io/chat/docs/sdk/reactnative/guides/push-notifications-v2/ has also been updated with the template customization support and the differences between Android & iOS. I am closing this issue as I believe the new update to documentation clarifies your remark. Please feel free to reopen or file a new issue if you would have any more suggestions to improve in this regard.
