### ISSUE TITLE
I got this error when I put a DM

### ISSUE THREAD

**Issue by luigicr18** [GetStream/stream-chat-react-native#1269]
<img width="398" alt="Screen Shot 2022-04-07 at 10 58 14" src="https://user-images.githubusercontent.com/9205551/162257186-00bcd1a0-b594-4866-99dd-ef41976c3e32.png">

The message is saved, but every time that I send a message fails

gz#21591

**Comment by madsroskar** [comment]
Hi, @luigicr18 - this was fixed in version [4.3.0](https://github.com/GetStream/stream-chat-react-native/releases/tag/v4.3.0) - could you try to upgrade to this version and see whether it resolves the issue on your end?

**Comment by luigicr18** [comment]
I changed to 4.3.0 on my package.json and reinstall all, but the error continues.

**Comment by luigicr18** [comment]
Issue resolved! Thanks!
