### ISSUE TITLE
Deprecate v3 Tutorial

### ISSUE THREAD

**Issue by vanGalilea** [GetStream/stream-chat-react-native#1270]
### Motive

- Having one source of truth
- Broken links

https://github.com/GetStream/stream-chat-react-native/wiki/Tutorial-v3.0#setup

### Acceptance Criteria:

- Add deprecated note on wiki pages
- Fix the links on v3 docs

**Comment by vishalnarkhede** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/1270?planning-poker) with ZenHub @Enigma-I-am @khushal87 @madsroskar @santhoshvai @vanGalilea
