### ISSUE TITLE
Giphy Shuffle is broken in Thread Reply Screen

### ISSUE THREAD

**Issue by khushal87** [GetStream/stream-chat-react-native#1294]
When you try to click on the shuffle button on the Giphy for the Thread screen, the new giphy doesn't rerender on the screen.

Ref - https://github.com/GetStream/stream-chat-react-native/issues/1266#issuecomment-1100748452

gz#21984

**Comment by vanGalilea** [comment]
@khushal87 couldn't reproduce the issue

**Comment by vanGalilea** [comment]
@madsroskar will share an app where this might be easy to reproduce and might have to do with shards.

**Comment by vanGalilea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/1294?planning-poker) with ZenHub @Enigma-I-am @khushal87 @madsroskar @santhoshvai @vishalnarkhede

**Comment by madsroskar** [comment]
I was not able to reproduce this either - closing the issue for now.
