### ISSUE TITLE
useChannelPreviewDisplayName returns ', +1' when charachterLength is limited

### ISSUE THREAD

**Issue by vanGalilea** [GetStream/stream-chat-react-native#1297]
**Describe the bug**
`useChannelPreviewDisplayName` returns ', +1' when `charachterLength` is limited
This seems to happen on 1 on 1 channels.

**To Reproduce**

1. Call func `useChannelPreviewDisplayName(channel, 15)`
2. Make sure you use a low amount of `charachterLength`
3. This will result in the func returning ',+1'

**Expected behavior**
the display name is being returned containing the name of the other member.
i.e., if we use `charachterLength` 7 and the other member's name is 'Gerri Eickhof' the returned value should be 'Gerri E'

**Screenshots**
<img src="https://images.zenhubusercontent.com/624ef90ddad7ba759bd39665/4e869eed-7fc1-4c70-808c-a72d845c28c0" width="320"/>

gz#22037

**Comment by vishalnarkhede** [comment]
@vanGalilea  Screenshot seems broken

**Comment by vanGalilea** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/1297?planning-poker) with ZenHub @vishalnarkhede

**Comment by vanGalilea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/1297?planning-poker) with ZenHub @madsroskar @Enigma-I-am @khushal87

**Comment by vanGalilea** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/1297?planning-poker) with ZenHub @santhoshvai
