### ISSUE TITLE
Version Compabilities part of the docs, misses react native 0.68

### ISSUE THREAD

**Issue by santhoshvai** [GetStream/stream-chat-react-native#1300]
**Description**
The [version-compabilities](https://getstream.io/chat/docs/sdk/reactnative/#version-compabilities) part of the docs miss react native 0.67 and 0.68

**Acceptance criteria**
- Add the minimum stream sdk version needed for 0.67 and 0.68
- Add the minimum reanimated version needed for 0.67 and 0.68

**Comment by vanGalilea** [comment]
0.67 was added by @madsroskar
