### ISSUE TITLE
Incompatible with react-native v0.68

### ISSUE THREAD

**Issue by Blargel** [GetStream/stream-chat-react-native#1306]
**Describe the bug**
Adding stream-chat-react-native to a freshly created react-native project causes a runtime error:
```
Invariant Violation: `new NativeEventEmitter()` requires a non-null argument.
```

**Dev environment info (please complete/provide the following information):**

- stream-chat-react-native v4.3.1
- react-native v0.68.1
- Simulator, iPhone 13, iOS 15.4

**To Reproduce**

1. Create a new react-native project: `npx react-native init StreamChatTest --template react-native-template-typescript`
2. Add stream-chat-react-native package: `npm install stream-chat-react-native`
4. Wrap the app in the `OverlayProvider` in `App.tsx`
5. Build and run the app
6. Observe the error

**Expected behavior**
There should not be an error

**Comment by Blargel** [comment]
It seems like a newer version of npm actually is not correctly installing peer dependencies automatically. This might not actually be a problem with this package.

**Comment by Blargel** [comment]
So, when npm automatically installed the peer dependencies for me, it seems like the Podfile was not updated. This is strange because I could've sworn it *did* update the Podfile the last time I tried this, but I might just be remembering incorrectly now.

**Comment by ChristopherGillis** [comment]
This is not working for me at all... @Blargel could you possibly help with more insight? Which peer dependencies?
