### ISSUE TITLE
Support customisation of message overlay background

### ISSUE THREAD

**Issue by vanGalilea** [GetStream/stream-chat-react-native#1322]
**Motivation**
Customers would like to have more control (currently theming only) over the overlay background of the message. Others would like to use a blurred backdrop i.e., [RN blur](https://github.com/Kureev/react-native-blur).
A variety of wishes need to be addressed.

This is related to this [issue](https://github.com/GetStream/stream-chat-react-native/issues/1074)

**Proposed solution**
Have the ability to pass a custom component to OverlayProvider

**Acceptance Criteria**
The customer can specify a custom background to use as an overlay background for the message

gz#22660

**Comment by vanGalilea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/1322?planning-poker) with ZenHub @Enigma-I-am @khushal87 @madsroskar @santhoshvai @vishalnarkhede

**Comment by khushal87** [comment]
Added to our internal chat backlog. Will be closing it from here. Will be picked in the future.
