### ISSUE TITLE
Audio attachment analysis and research

### ISSUE THREAD

**Issue by vanGalilea** [GetStream/stream-chat-react-native#1329]
DOD and research questions:

- [ ] Libs. candidates, what is the best lib. for this feature?
- [ ] Architectural choices.
- [ ] Product and UI/UX doubts/collect info.

Linked to Zendesk issue 

gz#22797

**Comment by khushal87** [comment]
Architectural choice
- The only problem with the audio attachments is synchronizing the play and pause events when we have multiple audios in the message input or in the attachments section.
- The props are almost the same as we have using in the implementation of video attachment support and the APIs also remain the same except for the case of expo-av where you use `Audio.Sound` with params which returns the sound object with all the necessary functions.
