### ISSUE TITLE
Use PNPM throughout project

### ISSUE THREAD

**Issue by vanGalilea** [GetStream/stream-chat-react-native#1335]
**Motivation**
@madsroskar is constantly frustrated with yarn, and node modules are being managed.

**Proposed solution**
Use ppnpm by following where @madsroskar left in this [PR]( https://github.com/GetStream/stream-chat-react-native/pull/1076/files)

**Acceptance Criteria**
pnpm is easy to use and configured correctly through our project. Migration from yarn to pnpm is well documented in readme/contribution MD and communicated to all collaborators.

**Comment by madsroskar** [comment]
Tricky parts to deal with: 

- [ ] release scripts will have to be refactored
- [ ] Example apps using metro, will need custom metro config

**Comment by vanGalilea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/1335?planning-poker) with ZenHub @Enigma-I-am @khushal87 @madsroskar @santhoshvai @vishalnarkhede

**Comment by santhoshvai** [comment]
@madsroskar https://microsoft.github.io/rnx-kit/docs/tools/metro-resolver-symlinks this could help with pnpm symlink easiness

**Comment by vanGalilea** [comment]
This issue was moved to an internal backlog list of less urgent feature/docs requests.
