### ISSUE TITLE
Bug - "Could not find root view for a given ancestor with tag" error in the Sample App

### ISSUE THREAD

**Issue by santhoshvai** [GetStream/stream-chat-react-native#1339]
**Describe the bug**
Open the sample App. Just randomly open and close channels from the channel list. You will get a crash.

**Proposed fix**
This is due to https://github.com/software-mansion/react-native-gesture-handler/issues/1675. The fix is to migrate to react-native-gesture-handler to the latest version(2.4) in the core and also [follow the migration docs](https://docs.swmansion.com/react-native-gesture-handler/docs/next/guides/migrating-off-rnghenabledroot) in the app. Might also need to link this doc to the troubleshooting page.

**Comment by vanGalilea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/1339?planning-poker) with ZenHub @Enigma-I-am @khushal87 @madsroskar @santhoshvai @vishalnarkhede

**Comment by vanGalilea** [comment]
Closing this issue, due to irrelevance and the latest version of RNGH (2.7.1)
