### ISSUE TITLE
Add "options" button on the  Image gallery

### ISSUE THREAD

**Issue by santhoshvai** [GetStream/stream-chat-react-native#1341]
## Description
Add an "options" button in the image gallery. This task aligns our image gallery with other SDKs.
The design is already available in [Figma](https://www.figma.com/file/ekifwChR9tR7zRJg1QEzSM/Chat-Design-Kit---Current-version?node-id=12494%3A9157).

## Acceptance Criteria
- A user can tap on the options button and access four options as below,
![image](https://user-images.githubusercontent.com/3846977/167146249-54f326fc-4708-4330-aa7c-a83f7e6702c4.png)

**Comment by vanGalilea** [comment]
This issue was moved to an internal backlog list of less urgent feature/docs requests.
