### ISSUE TITLE
Channel new message animation

### ISSUE THREAD

**Issue by TianrenWang** [GetStream/stream-chat-react-native#1343]
**Describe the bug**
When the same user sends messages back-to-back, the sliding animation that happens to the new message moves the entire message history to the bottom of the screen and before sliding up to fit the new message.

**Dev environment info (please complete/provide the following information):**
```
"expo": "~43.0.0",
"react-native": "0.64.3",
"stream-chat": "^6.5.0",
"stream-chat-expo": "^4.3.1"
```
This is in my real device iPhone SE, version 15.4.1

**To Reproduce**

1. Start a development server running the example code in https://getstream.io/chat/react-native-chat/tutorial/#add-stream-chat-to-your-application.
2. Go to the screen that has the Channel
3. Type and send a message
4. Type and send another message, and observe the strange animation.

**Expected behavior**
Preferably, there is no animation at all, because no animation in this scenario will look natural.

**Screenshots**
<img width="425" alt="image" src="https://user-images.githubusercontent.com/23157077/167236568-82bb6c69-8063-4f9b-9bde-3548d059a9a6.png">
When a new message is sent, the whole chat history first moves to the bottom (above the message input, as labelled animation 1), and then moves up to make space for the new message (animation 2). This is unnatural animation.

**Comment by vishalnarkhede** [comment]
For everyone else's benefit, I am attaching a slow-mo screen recording of the referred issue here.

https://user-images.githubusercontent.com/11586388/167481008-48572295-520f-4776-b895-ad4120445fb5.mov

@TianrenWang we can look into this soon, but won't be able to keep it high priority for now.

**Comment by vishalnarkhede** [comment]
As far as I can see

- new message is sent
- datetime stamp on latest message is dropped, which is why list moves down a bit
- new message gets added to the list
- list scrolls down again

**Comment by TianrenWang** [comment]
@vishalnarkhede thank you for further clarifying the issue. Is there somewhere in the node package that I can change to disable this animation? I don't mind a hacky and temporary solution just for my case specifically.

**Comment by khushal87** [comment]
Hey @TianrenWang,

I will be closing this issue. Feel free to reach out in the future.

Thanks.
