### ISSUE TITLE
Channel list swipe to delete

### ISSUE THREAD

**Issue by finalight** [GetStream/stream-chat-react-native#1344]
**Motivation**
A clear and concise description of what the problem/opportunity is. Ex. I'm always frustrated when [...]

**Proposed solution**

**Acceptance Criteria**
A set of predefined requirements that must be met to mark a user story complete.

**Comment by vishalnarkhede** [comment]
@finalight we would appreciate if you kindly follow the template for raising the issues here. In this case I can see the template being left as it is.

For swipe to delete, you can checkout our sample app where we have implemented this behaviour
- https://github.com/GetStream/stream-chat-react-native/blob/develop/examples/SampleApp/src/screens/ChannelListScreen.tsx#L194
- https://github.com/GetStream/stream-chat-react-native/blob/develop/examples/SampleApp/src/components/ChannelPreview.tsx#L70
