### ISSUE TITLE
How to hide channels with no message?

### ISSUE THREAD

**Issue by finalight** [GetStream/stream-chat-react-native#1347]
I'm using the ChannelList UI Kit

```
<ChannelList
            onSelect={setToChannel}
            PreviewTitle={PreviewTitle}
            filters={{
              members: { $in: [viewer.id] },
              type: 'messaging'
            }}
          />
```

however, there are channels which are created but no message, I don't want user to see the channels with empty messages

how can i hide those?

**Comment by GregAtFramework** [comment]
You can add a a filter on `last_message_at` using an arbitrary date.

```
{
  members: { $in: [viewer.id] },
  type: 'messaging',
   last_message_at: { $gt: "2000-01-01T00:00:00.00Z" }
}
```

**Comment by finalight** [comment]
well, that's what i did like a few seconds ago

but is there a better way?

**Comment by vishalnarkhede** [comment]
The solution suggested by @GregAtFramework is the correct way of this this :)
