### ISSUE TITLE
Write a customization guide over recording/other audio related topics

### ISSUE THREAD

**Issue by khushal87** [GetStream/stream-chat-react-native#1354]
Adding a customization guide around how to achieve recording from our own SDK and add other audio related customization guides(if needed)

**Comment by vanGalilea** [comment]
We can base this on what I've been doing in the WhatsApp clone see [`VoiceMessageAttachment.tsx`](https://github.com/GetStream/react-native-samples/blob/main/projects/WhatsAppClone/src/components/channel/VoiceMessageAttachment.tsx)

**Comment by vanGalilea** [comment]
This issue was moved to an internal backlog list of less urgent feature/docs requests. I'll be closing this issue for now.
Please don't hesitate to contact us in the future if any other questions arise.
