### ISSUE TITLE
push notification custom template from dashboard

### ISSUE THREAD

**Issue by finalight** [GetStream/stream-chat-react-native#1355]
i'm relying on push notification from stream dashboard, and also the UI kit from the stream react native

i tested by sending a message from sender to recipient, and recipient receive the push notification. however, this is what the recipient receive on android device

![Screenshot_20220511-093420](https://user-images.githubusercontent.com/4475526/167751935-1b28b3cf-efcf-4383-9531-8ce8fee668a0.png)

i think the random alphanumeric after the word 'buyer @' is the channel ID, which is randomly generated by stream.

is there anyway to hide that without the need implement my own push notification mechanism in order to modify the template?

**Comment by vanGalilea** [comment]
Hi @finalight 👋🏻 did this happen after a specific change/upgrade to your codebase? Can you also share which configuration steps you made around PN?

**Comment by finalight** [comment]
> Hi @finalight 👋🏻 did this happen after a specific change/upgrade to your codebase? Can you also share which configuration steps you made around PN?

there was no change

i always thought that's the expected behaviour from stream, is it not?

**Comment by santhoshvai** [comment]
Hi @finalight, Based on your comments I assume that you are on push v1.

On V1 the default notification template is

```
{ 
    "title": "{{ sender.name }} @ {{ channel.name }}", 
    "body": "{{ truncate message.text 2000 }}", 
    "click_action": "OPEN_ACTIVITY_1", 
    "sound": "default" 
}
``` 

If you have not made changes, then `channel.name` is the random alphanumeric string. If not, please check the template that is set on your dashboard. 

You can modify the template to change it to what you need. It is fairly simple through the dashboard. We have more info in the [JS SDK documentation](https://getstream.io/chat/docs/javascript/push_template/). For example, to hide it, make the title as `title": "{{ sender.name }}"`.

**Comment by finalight** [comment]
> Hi @finalight, Based on your comments I assume that you are on push v1.
> 
> On V1 the default notification template is
> 
> ```
> { 
>     "title": "{{ sender.name }} @ {{ channel.name }}", 
>     "body": "{{ truncate message.text 2000 }}", 
>     "click_action": "OPEN_ACTIVITY_1", 
>     "sound": "default" 
> }
> ```
> 
> If you have not made changes, then `channel.name` is the random alphanumeric string. If not, please check the template that is set on your dashboard.
> 
> You can modify the template to change it to what you need. It is fairly simple through the dashboard. We have more info in the [JS SDK documentation](https://getstream.io/chat/docs/javascript/push_template/). For example, to hide it, make the title as `title": "{{ sender.name }}"`.

hi @santhoshvai i think i'm on v2

<img width="1317" alt="image" src="https://user-images.githubusercontent.com/4475526/167784455-33a95971-3251-4411-8f37-8da4cf15bebd.png">

and also, i don't see the options to edit the template in the dashboard

**Comment by finalight** [comment]
in case you need to check, the appID is `1162231`

**Comment by santhoshvai** [comment]
Yes, you are on V2. 

In v2, the notification template for Android is not set.. and setting through the dashboard is not yet available, but will be there soon. Since you havent made changes to the default template, whatever you are seeing now is what you are displaying in your app. I assume through Notifee library. We do have [detailed documentation](https://getstream.io/chat/docs/sdk/reactnative/guides/push-notifications-v2/#android) about this. Please do read the documentation, we have detailed it recently about how to handle push notifications in v2.

**Comment by finalight** [comment]
according to the documentation that you listed

```
When a user interacts with the notification by pressing on it, the default behavior is to open the application. In many cases, it is useful to detect whether the application was opened by pressing on a notification (so you could open a specific screen for example).
```

this behaviour is not working on android

**Comment by vanGalilea** [comment]
@finalight I'm going to close this, please don't hesitate to reach out if you have any other questions!

**Comment by finalight** [comment]
i'm reopening this, turns out that updating the notification template is a server side operation only

i am bewildered how can i do this if i don't intend to handle the push notification myself server-side
