### ISSUE TITLE
android: clicking on push notification doesn't open the app

### ISSUE THREAD

**Issue by finalight** [GetStream/stream-chat-react-native#1356]
so i did the push notification feature which is handled by stream

whenever android users receive the push notification, nothing happens when they click on it (app is not opened)

is there any configuration i need to do for android?

for iOS, it works fine

**Comment by santhoshvai** [comment]
Closing this. As it was answered previously:

https://github.com/GetStream/stream-chat-react-native/issues/1355#issuecomment-1124024540
