### ISSUE TITLE
Icon in Attachment Bar is not centered as expected

### ISSUE THREAD

**Issue by thuytony** [GetStream/stream-chat-react-native#1358]
**Dev environment info:**

- "stream-chat-expo": "^4.1.2"
- Expo SDK 44
- IOS

**To Reproduce**

1. Go to Chat Screen.
2. Open any conversation.
3. Click the attachment icon to open the attachment bar.

**Expected behavior**
The icon inside the attachment bar section should be centered.

**Screenshots*
![attachment_bar_section](https://user-images.githubusercontent.com/34490002/167968695-4c1a3ab6-27d4-43ed-9c15-1ad2641d2f13.png)
*

**Comment by khushal87** [comment]
Hey @thuytony, this is fixed with version 4.4.0. Can you please try upgrading the SDK version for your application? Thanks, and please let us know if you still face the same problem.

**Comment by thuytony** [comment]
Improved, but still not good enough.
"stream-chat-expo": "^4.4.0"

iPhone 11 simulator
![ios](https://user-images.githubusercontent.com/34490002/168035458-35b7434d-2548-45dd-b527-4b752e9bd0f3.png)

Google Pixel 3
![processed-51362328-5b63-4b11-aff4-237e05b8ffc2_IFZSefOz](https://user-images.githubusercontent.com/34490002/168035815-4f95d8e2-0dbb-4bd2-999c-d6219483f371.jpeg)

**Comment by vanGalilea** [comment]
@thuytony we've solved it with this [PR](https://github.com/GetStream/stream-chat-react-native/pull/1305) and it has been released and available from [v4.4.0](https://github.com/GetStream/stream-chat-react-native/releases/tag/v4.4.0)
