### ISSUE TITLE
Error: Undefined is not a function while using the ChannelList component

### ISSUE THREAD

**Issue by vinaygregoryjohn183** [GetStream/stream-chat-react-native#1359]
While using the ChannelList component as given the docs (The Multiple conversations section in https://getstream.io/chat/react-native-chat/tutorial/), getting an error 'undefined is not a function'

Versions:
stream-chat 6.5.1
stream-chat-react-native 4.4.0
react-native 0.63.4

**Screenshots**
<img width="419" alt="Screenshot 2022-05-12 at 4 23 02 PM" src="https://user-images.githubusercontent.com/82080446/168055844-9cbe8702-0dcd-46d7-b070-3bff9705963f.png">
<img width="426" alt="Screenshot 2022-05-12 at 4 29 00 PM" src="https://user-images.githubusercontent.com/82080446/168055909-445f7b26-08d1-4a55-87cc-62fbe6e84359.png">

**Comment by vanGalilea** [comment]
@vinaygregoryjohn183 thanks for reaching out! We have a new tutorial now, that has been released a few days ago. Can you please try it [here](https://getstream.io/chat/react-native-chat/tutorial/).

I'm gonna close this one and if you have any issues, just create a new issue 👋🏻
