### ISSUE TITLE
Access to android storage for images is broken when the app is set to target api 30 (Android 11)

### ISSUE THREAD

**Issue by santhoshvai** [GetStream/stream-chat-react-native#1360]
## Description
We use react-native-cameraroll library to access the device photos and the library is not maintained anymore. As a result, when an Android app is set to target Api 30, the device photos are not shown anymore. This is clearly described in the [Android Docs](https://developer.android.com/training/data-storage/use-cases#opt-out-in-production-app). 

> Caution: After you update your app to target Android 11 (API level 30), [the system ignores the requestLegacyExternalStorage attribute](https://developer.android.com/about/versions/11/privacy/storage#scoped-storage) when your app is running on Android 11 devices, so your app must be ready to support scoped storage and to [migrate app data](https://developer.android.com/training/data-storage/use-cases#migrate-legacy-storage) for users on those devices.

## Recommended Workaround
- Target to Api 29 for now.

## Possible fix
- Use patch-package and patch with this [PR](https://github.com/react-native-cameraroll/react-native-cameraroll/pull/322/files). Unfortunately, react-native-cameraroll is unmaintained so this PR hasn't been merged. The PR seems to fix the issue, but have to be verified.
- one more [patch-package option from a comment](https://github.com/react-native-cameraroll/react-native-cameraroll/pull/322#issuecomment-1113684725)

**Comment by vanGalilea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/1360?planning-poker) with ZenHub @Enigma-I-am @khushal87 @madsroskar @santhoshvai @vishalnarkhede
