### ISSUE TITLE
Missing translation for 'Pinned by (user)'

### ISSUE THREAD

**Issue by findawayer** [GetStream/stream-chat-react-native#1365]
**Describe the bug**
*****Pinned by {{ user }}***** text that appears around a pinned message does not get translated.

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native/stream-chat-expo): stream-chat-react-native
- react-native or expo version: react-native v0.67.3
- Device/Emulator (android/ios) and OS version:
 - Android Emulator: 31.2.10-8420304 (HAXM 7.6.5)
 - Android version: 11.0 (R) - API 30
 - Host machine: Windows 10 Pro

The same happens for any other environments in my use (e.g. iOS emulator or real devices).

**To Reproduce**

1. Change i18n config to anything else than English.
2. Pin any message.
3. *****Pinned by {{ user }}***** is still in English.

**Expected behavior**
Please add *****Pinned by {{ user }}***** to the available translation message list.

**Additional context**
It looks like `MessagePinnedHeader` component does not pass this message to the translation module.
- https://github.com/GetStream/stream-chat-react-native/blob/develop/package/src/components/Message/MessageSimple/MessagePinnedHeader.tsx#L58

**Screenshots**
![image](https://user-images.githubusercontent.com/26019822/168521022-c5d05d07-344c-41a6-a4e7-fa3f941d36ae.png)

**Comment by khushal87** [comment]
Hey, this is a valid issue. We will pick this up soon. Thank you. 😄

**Comment by vanGalilea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/1365?planning-poker) with ZenHub @Enigma-I-am @khushal87 @madsroskar @santhoshvai @vishalnarkhede
