### ISSUE TITLE
Tutorial improvements - add typescript code samples

### ISSUE THREAD

**Issue by vishalnarkhede** [GetStream/stream-chat-react-native#1368]
**Motivation**
Currently our tutorial is based on jsx based code samples. But it would be nice if tutorial also contains typescript implementation of Chat components.

**Proposed solution**
Add a separate tab for every code sample which is based on typescript.

**Comment by vanGalilea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/1368?planning-poker) with ZenHub @Enigma-I-am @khushal87 @madsroskar @santhoshvai @vishalnarkhede
