### ISSUE TITLE
Help wanted: is "channel.watch" needed with react native component?

### ISSUE THREAD

**Issue by familywiser1** [GetStream/stream-chat-react-native#137]
react native tutorials at https://getstream.io/chat/react-native-chat/tutorial/#stream-app is using "`channel.watch()`"

```
class ChannelScreen extends React.Component {
  render() {
    const channel = chatClient.channel("messaging", "raspy-paper-5");
    channel.watch();

    return (
      <SafeAreaView>
        <Chat client={chatClient}>
          <Channel channel={channel}>
            <View style={{ display: "flex", height: "100%" }}>
              <MessageList />
              <MessageInput />
            </View>
          </Channel>
        </Chat>
      </SafeAreaView>
    );
  }
}
```

However, the examples provided in your github repo ( https://github.com/GetStream/stream-chat-react-native/blob/master/examples/ExpoMessaging/App.js#L81 ) does not mention `"channel.watch"`

I am not sure if we need to use `"channel.watch"` with react native component. If "channel.watch" is required, how to remove the listener when component unmounts?

**Comment by vishalnarkhede** [comment]
Hey @familywiser1 , you don't really need to do `channel.watch()` before providing it to Channel component. We initialize/watch the channel in Channel component anyways - https://github.com/GetStream/stream-chat-react-native/blob/master/src/components/ChannelInner.js#L165
