### ISSUE TITLE
Full screen modal for image gallery grid in overlay

### ISSUE THREAD

**Issue by vishalnarkhede** [GetStream/stream-chat-react-native#1370]
## Motivation

As per our current implementation, image grid opens as a modal on top of image viewer. But it has no explicit backdrop, which creates a confusion between the header of image grid and underlying image viewer. Especially the close buttons for image viewer vs close button for image grid modal. We should improve the experience for user around this feature.

<img width="320" alt="Screenshot 2022-05-17 at 09 56 31" src="https://user-images.githubusercontent.com/11586388/168759753-795a1335-cb36-4088-8d47-b1c3b4c45a63.png">

## Proposed solution

Update the snap points for image grid modal so that it covers the entire screen. 

https://github.com/GetStream/stream-chat-react-native/blob/develop/package/src/components/ImageGallery/ImageGallery.tsx#L178

**NOTE**: Following code is just an idea, please don't copy-paste it for the fix

```js
const { top } = useSafeAreaInsets();
const snapPoints = React.useMemo(() => ([Dimensions.get('window').height - top]), [])
```

<img width="320" alt="Screenshot 2022-05-17 at 09 57 51" src="https://user-images.githubusercontent.com/11586388/168759980-959899e7-bd9f-4dec-9f24-67f938bb713e.png">

**Comment by khushal87** [comment]
Hey @vishalnarkhede this is the current behaviour from what I see. We improved this behavaiour and logic of snap points in #2490 and this seems to eliminate this issue.  I hope this is(the video below) what is expected, right?

https://github.com/GetStream/stream-chat-react-native/assets/39884168/1f9001ab-0c73-42a2-9a2c-28eabcf9aac9
