### ISSUE TITLE
Use RN team account instead of VIshal's in CI/CD workflows 

### ISSUE THREAD

**Issue by vanGalilea** [GetStream/stream-chat-react-native#1378]
**Motivation**
We're currently using @vishalnarkhede GH/NPM accounts throughout the SDK's CI/CD workflows.
This is not the best practice for many reasons such as security etc.

**Proposed solution**
Use a general RN team account instead of @vishalnarkhede 's

**Acceptance Criteria**
@vishalnarkhede GH/NPM accounts are not in use and have been exchanged with a general team account.

**Comment by vanGalilea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/1378?planning-poker) with ZenHub @Enigma-I-am @khushal87 @madsroskar @santhoshvai @vishalnarkhede

**Comment by santhoshvai** [comment]
We can also use the GitHub actions bot account, seems easier, ref: https://github.com/actions/checkout/discussions/479
