### ISSUE TITLE
Help needed: How to put "SendButton" outside of MessageInput?

### ISSUE THREAD

**Issue by familywiser1** [GetStream/stream-chat-react-native#138]
I want to put SendButton outside of MessageInput. 

This is similar to how other chat platforms such as WhatsApp/Telegram do.   I also think it is a better user experience since having a large button outside with extra padding helps with sending messages quickly. 

I tried this but I am not sure how to use existing "`sendMessage" `method from `MessageInput`

```
 <MessageInput hasFilePicker={false}/>
<SendButton editing={false} sendMessage={() => {}} />

```
I will really appreciate it if you can suggest how to how to put "SendButton" outside of MessageInput. If it is not possible,  please suggest to me how to add extra padding around SendButton and make it large.

**Comment by vishalnarkhede** [comment]
@familywiser1 Currently its not easily possible to keep send button outside MessageInput component. We kept send button inside MessageInput to avoid HOC mess. Although your use-case can easily be achieved by tweaking some styles.

```
const theme={
   // To modify top container of MessageInput component
   'messageInput.container': 'background-color: white';
   // To modify styles of container (which contains attach button, input box and send button)
   'messageInput.inputBoxContainer': 'margin: 12px';
   // To add padding around send button icon
   'messageInput.sendButton': 'padding: 20px';
   // To modify the size of send button icon itself
   'messageInput.sendButtonIcon': 'height: 30px; width: 30px;'
   // To modify styles for input box
   'messageInput.inputBox': 'background-color: black'
} 
...
<Chat style={theme}>
   ...
</Chat>
```

Hope that helps. Let us know if you have any followup question!

**Comment by familywiser1** [comment]
Thanks for the suggestion. I am able to modify the send button style that's fine for now.
