### ISSUE TITLE
Make MessageTextContainer Customisable

### ISSUE THREAD

**Issue by vanGalilea** [GetStream/stream-chat-react-native#1381]
**Motivation**
`MessageTextContainer` is not customizable. Several customers are interested in customizing this particular component to achieve a specific look and feel, such as a gradient background. More info [here](https://getstream.slack.com/archives/C02GBL5M1BK/p1652839611703699)

**Proposed solution**
Default `MessageTextContainer` can be replaced with any other component specified from `Channel`/`MessageList` level via a prop.

**Acceptance Criteria**
Default `MessageTextContainer` can be customized with a customer-specified component.

PS: Also check if [this](https://getstream.zendesk.com/agent/tickets/23104) and [this](https://getstream.zendesk.com/agent/tickets/23105) works after implementation.

**Comment by khushal87** [comment]
This is achievable using - https://stream-wiki.notion.site/Achieving-Linear-Gradient-in-Message-Bubble-b79afdb7409f4af5bcc47c09d0fd50f9

**Comment by vishalnarkhede** [comment]
Yes, but the objective here is to be able to change the background color of message without altering any other functionality. In your example, we are simply rendering the text of message within custom component.

**Comment by vanGalilea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/1381?planning-poker) with ZenHub @Enigma-I-am @khushal87 @madsroskar @santhoshvai @vishalnarkhede

**Comment by vanGalilea** [comment]
Let's add a guide to customize the message bubble with a gradient background

**Comment by vanGalilea** [comment]
This issue was moved to an internal backlog list of less urgent feature/docs requests.
