### ISSUE TITLE
ViewPropTypes will be removed from React Native.

### ISSUE THREAD

**Issue by AlexanderLindkjaer** [GetStream/stream-chat-react-native#1385]
After upgrading Expo
```json
"expo": "^45.0.0",
"react-native": "0.68.2",
"stream-chat": "^6.4.0",
"stream-chat-expo": "^4.5.0",
```

This warning is thrown on build
```bash
ViewPropTypes will be removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'.
at node_modules/react-native/index.js:470:4 in module.exports.get__ViewPropTypes
at node_modules/react-native-markdown-package/index.js:66:10 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at node_modules/stream-chat-react-native-core/src/components/Message/MessageSimple/utils/renderText.tsx:5:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at node_modules/stream-chat-react-native-core/src/components/Message/MessageSimple/MessageTextContainer.tsx:4:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at node_modules/stream-chat-react-native-core/src/components/Message/MessageSimple/MessageContent.tsx:4:0 in <global>
```

Just a heads up 🙂

**Comment by vanGalilea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/1385?planning-poker) with ZenHub @Enigma-I-am @khushal87 @madsroskar @santhoshvai @vishalnarkhede

**Comment by vanGalilea** [comment]
The solution is: let's replace the wrapper coming from RN markdown lib. and have the wrapper logic within our SDK. 
And replace ViewPropTypes in the wrapper.

**Comment by boblitex** [comment]
just a heads up team, this is no longer a warning but an outright error with react native 0.69.1
`Error: Requiring module "node_modules/stream-chat-react-native/src/index.js", which threw an exception: Invariant Violation: ViewPropTypes has been removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'. `

**Comment by sandergo90** [comment]
The latest release from the https://github.com/andangrd/react-native-markdown-package/releases/tag/v1.8.2 packages, should resolve this issue. Can this be updated?

**Comment by santhoshvai** [comment]
@sandergo90  Done in v14.13.0 🎉  Thanks!
