### ISSUE TITLE
Avatar initials are not displayed in ChannelList for one-one converstations

### ISSUE THREAD

**Issue by familywiser1** [GetStream/stream-chat-react-native#139]
**Describe the bug**
Avatar initials are not displayed in ChannelList for one-one converstations. Channel Screens shows the avatar initials correctly.

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native/stream-chat-expo): latest stream-chat-expo
- react-native or expo version: expo
- Device/Emulator (android/ios) and OS version: all

**To Reproduce**

1. Follow getting started with react native tutorial at https://getstream.io/chat/react-native-chat/tutorial/
2. create a one-one conversation (a channel with only 2 members and no name) by following instructions at https://getstream.io/chat/docs/channel_conversations/?language=js - (please note that there is no channel name since it is one-one)

**Expected behavior**
Avatar initials should be displayed in ChannelList for one-one conversations

**Additional context**
problem is here - https://github.com/GetStream/stream-chat-react-native/blob/master/src/components/ChannelPreviewMessenger.js#L107 . It takes` channel.data.name` which is empty for 1-1 conversations. You should send initials of 2nd member in this case. 

**Screenshots**

**Comment by vishalnarkhede** [comment]
@familywiser1 thanks for bringing this up. We will fix this in next release :)

**Comment by vishalnarkhede** [comment]
@familywiser1 this has been fixed as part of `0.6.6`. Please let us know if it works for you!

**Comment by familywiser1** [comment]
Thanks. it is working now.
