### ISSUE TITLE
'undefined is not a function' issue in the MessageInput Component

### ISSUE THREAD

**Issue by vinaygregoryjohn183** [GetStream/stream-chat-react-native#1391]
**Describe the bug**
Was trying to implement the Channel page as per the documentation: My code:
<img width="257" alt="Screenshot 2022-05-23 at 7 18 56 AM" src="https://user-images.githubusercontent.com/82080446/169729254-da9a6236-ccec-42cf-bef5-c0e5a881dbc9.png">

**Dev environment info (please complete/provide the following information):**
"react-native": "0.66.4",
"stream-chat": "^6.3.0",
"stream-chat-react-native": "^4.4.0",
Emulator OS version Android 11.

**Expected behavior**
The Channel page should be seen without any issues.

**Screenshots**
<img width="549" alt="Screenshot 2022-05-23 at 7 29 45 AM" src="https://user-images.githubusercontent.com/82080446/169729371-756d95c9-56ec-4d15-bb51-5ad2d80328f9.png">

**Comment by vanGalilea** [comment]
@vinaygregoryjohn183, thanks for reaching out. Can you please share a clean repo with us where this can be reproduced?

**Comment by vinaygregoryjohn183** [comment]
The issue was because I hadn't wrapped the code inside <OverlayProvider> component. Thank you.
