### ISSUE TITLE
Clarify the usage of the hardcoded 308 value in AttachmentPicker.tsx and AttachmentPickerError.tsx

### ISSUE THREAD

**Issue by santhoshvai** [GetStream/stream-chat-react-native#1394]
**Motivation**
The hardcoded value usage of 308 in `AttachmentPicker.tsx` and `AttachmentPickerError.tsx` is unmaintanable. 

308 is the default value of the prop `attachmentPickerBottomSheetHeight` in the `OverlayProvider`, so it seems like the value set in the prop must be used here.

**Proposed solution**
Use the value of the prop in both of these components instead of the hardcoded 308.

**Comment by vanGalilea** [comment]
This issue was moved to an internal backlog list of less urgent feature/docs requests.
