### ISSUE TITLE
Remove Reconnecting ui from ChannelList and Channel component

### ISSUE THREAD

**Issue by haresh12** [GetStream/stream-chat-react-native#1401]
**Describe the bug**
Whenever app goes to background and comes back to foreground we are seeing ui message saying reconnecting how can we remove that ui from app in ChannelList component there is no component available for that specific.

reproducible in both Android and Ios

- Package version (stream-chat-react-native/stream-chat-expo) "stream-chat": "^6.4.0", "stream-chat-expo": "^4.3.0"
- react-native or expo version : expo: "~44.0.2",
- Device/Emulator (android/ios) and OS version : Any

**To Reproduce**
Go to background for couple of second and then come back to foreground

**Expected behavior**
It should not show Reconnection bar ui in screen

![WhatsApp Image 2022-05-25 at 8 12 27 AM](https://user-images.githubusercontent.com/28671769/170169859-5f3e4c38-3986-4348-ac08-d4209d3c908e.jpeg)

**Comment by GregAtFramework** [comment]
I experienced this behaviour too.

You can disable it using a `ChannelList` prop: `HeaderNetworkDownIndicator={() => <React.Fragment />}`

However I would welcome Stream improving this behaviour, so I could retain this indicator, but have it show less frequently.

**Comment by haresh12** [comment]
Thanks @GregAtFramework saved my day worked well
