### ISSUE TITLE
Potential issue with KeyboardCompatibleView

### ISSUE THREAD

**Issue by jparkrr** [GetStream/stream-chat-react-native#141]
**Describe the bug**
In my app I was having an issue where, when I focused on MessageInput and the keyboard came up, the Channel didn't animate to a smaller height to accommodate the keyboard.

Not sure exactly why this doesn't happen in all apps. For example, I couldn't reproduce it in the example expo app. I've created a fix that works for me, see "Additional context below".

**Dev environment info (please complete/provide the following information):**

- Package version: stream-chat-expo 0.6.5
- expo version 35
- iOS 13.3.1

**Additional context**
I was able to fix the problem by editing inside node_modules and adding `initialHeight` in KeyboardCompatibleView to the component state and using setState. My theory is that it wasn't rerendering after onLayout where initialHeight was set and therefore not applying `channelHeight` to the `Animated.View`.

**Comment by vishalnarkhede** [comment]
Hey @jparkrr , thanks for brining this up. I will look into it and get back to you :)

**Comment by vishalnarkhede** [comment]
Hey @jparkrr , I have published one fix in `v0.6.6`. Can you please check and let me know if its working for you?

**Comment by jparkrr** [comment]
it's working! thanks!
