### ISSUE TITLE
Allow to use index in ChannelList custom Preview

### ISSUE THREAD

**Issue by jpalumickas** [GetStream/stream-chat-react-native#1422]
**Motivation**
We need to know a position of Channel List item to show different style, so we can use `renderItem` `index` for that, but currently it's not available in custom `ChannelList` `Preview`

**Proposed solution**
in `renderItem` we can get `index` which we can pass to custom Preview

**Acceptance Criteria**
`index` is available in custom provided `Preview`

**Comment by khushal87** [comment]
Hey @jpalumickas. Thanks for pointing out the issue and it really makes sense to add an `index` for the channel item which can be used in the `ChannelPreview` component. We have added this to our backlog. Keep on following this card.

**Comment by vanGalilea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/1422?planning-poker) with ZenHub @Enigma-I-am @khushal87 @madsroskar @santhoshvai @vishalnarkhede

**Comment by vishalnarkhede** [comment]
@jpalumickas we won't be able to prioritize this in near future. But you can use the following workaround:


```jsx
import {
  ChannelList,
  ChannelPreview,
} from 'stream-chat-react-native';

const PreviewContext = React.createContext({});

<ChannelList
  additionalFlatListProps={{
    renderItem: ({ index, item }) => (
      <PreviewContext.Provider data={{ index }}>
        <ChannelPreview channel={item} Preview={CustomPreviewComponent} />
      </PreviewContext.Provider>
    ),
  }}
  filters={filters}
/>
```

And within CustomPreviewComponent, use the PreviewContext consumer to access the index. Technically it should work
