### ISSUE TITLE
Being able to customize the color of the <Close /> button in the <ImageUploadPreview />

### ISSUE THREAD

**Issue by neopit** [GetStream/stream-chat-react-native#1424]
**Motivation**
We want to be able to change/customized the colour of the <Close /> icon in the ImageUploadPreview
Currently, we can change the colour via the Theming: colours: { black: 'red'} however changing the `black` attribute affects the entire theming especially the colour of the text.

The backgroundColor can be changed via this (see below) but we cannot change the color of the icon itself
    messageInput: {
      imageUploadPreview: {
        dismiss: {
          backgroundColor: '#FFFFFF'
        }
      }
    }

**Proposed solution**
Provide an extra parameter to the theming to messageInput.imageUploadPreview.dismiss
For example `pathFill` or `color`

    messageInput: {
      imageUploadPreview: {
        dismiss: {
          backgroundColor: '#FFFFFF'
          pathFill: 'red'. 
        }
      }
    }
![Screen Shot 2022-05-31 at 3 24 33 PM](https://user-images.githubusercontent.com/1306961/171294092-aafe8fc4-61b1-4e02-9db8-487f2ca6cf10.png)

and path this new colour to the icon
<Close pathFill={dismiss.pathFill} />

**Acceptance Criteria**
Be able to customize the color of <Close /> button use in the ImageUploadPreview

**Comment by khushal87** [comment]
Hey, @neopit thanks for bringing this up. It looks like you are correct and there isn't a way you can use to change the color of the dismiss `cross` icon. We have put this into our backlog and will get back to you with this feature soon.

**Comment by vanGalilea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/1424?planning-poker) with ZenHub @khushal87 @madsroskar @santhoshvai @vishalnarkhede
