### ISSUE TITLE
MessageInput shows AttachButton even when both hasFilePicker and  hasImagePicker are set to false

### ISSUE THREAD

**Issue by familywiser1** [GetStream/stream-chat-react-native#143]
**Describe the bug**
`MessageInput` shows `AttachButton` even when both `hasFilePicker` and  `hasImagePicker` are set to false. Clicking on this button does not do anything (which is fine). However, the `MessageInput` should not show `AttachButton` .

**Dev environment info (please complete/provide the following information):** 
- Package version (stream-chat-react-native/stream-chat-expo): stream-chat-expo
- react-native or expo version - expo
- Device/Emulator (android/ios) and OS version - all

**To Reproduce**
Steps to reproduce the behavior: follow getting started with react native guide and update the `MessageInput`

`<MessageInput hasFilePicker={false} hasImagePicker={false}  />
`

**Expected behavior**
 the `MessageInput` should not show `AttachButton` if both `hasFilePicker` and  `hasImagePicker` are set to false

**Comment by vishalnarkhede** [comment]
Hey @familywiser1 , thanks for bringing this up. We will take care of this in next release :)
