### ISSUE TITLE
Pinned Message Limit per Channel

### ISSUE THREAD

**Issue by tomSidebar** [GetStream/stream-chat-react-native#1446]
**Motivation**
I'd like to be able to limit how many pinned messages a given channel can have. For my use case specifically I want to limit it to only one pinned message per channel. Whenever a new message gets pinned it should unpin the previously pinned message.

Right now I could enforce that by overriding the handlePin function to also take care of unpinning the previously pinned message but ideally there's a built-in way to do that.

**Proposed solution**
Have a prop on the Channel object that allows setting a max number of pinned messages. If the max number of pinned messages has been reached then pinning a new message will also unpin the least recently pinned message.

**Acceptance Criteria**
- There's a prop (number) that can be set to define the max number of pinned messages in a given channel.
- Once the max number of pinned messages has been reached then any newly pinned message will unpin the least recently pinned message.

**Comment by khushal87** [comment]
Hey @tomSidebar,

Thanks for reaching out. We will add this to our backlog/wishlist to see if this feature would be helpful to more customers. I am gonna close this ticket as this is a very specific use case as of now and this can be achieved using our customization guides.

Thanks.

**Comment by tomSidebar** [comment]
@khushal87 Thank you!
