### ISSUE TITLE
Make UnsupportedFileTypeOrFileSizeIndicator customizable

### ISSUE THREAD

**Issue by khushal87** [GetStream/stream-chat-react-native#1447]
**Motivation**
The FileUploadPreview has an indicator for unsupported file types which isn't customizable yet. As a user, I want to customize the component `UnsupportedFileTypeOrFileSizeIndicator` using a prop from Channel/MessageInput whichever makes sense.

**Proposed solution**
Adding a prop for the same which receives a user-defined component. If the prop isn't provided, the default UI should be rendered.

**Acceptance Criteria**
- Adding the prop to customize the component.
- Adding a customization guide wherever possible.

**Comment by vanGalilea** [comment]
This issue was moved to an internal backlog list of less urgent feature/docs requests.
