### ISSUE TITLE
Guide for customization of MessageReplies component

### ISSUE THREAD

**Issue by khushal87** [GetStream/stream-chat-react-native#1448]
**Motivation**
As a user, I want to have a guide for customization of MessageReplies which I can't find in the documentation currently. 

**Proposed solution**
We can add a section in the https://getstream.io/chat/docs/sdk/reactnative/guides/message-customization/

**Acceptance Criteria**
- The guide should be short and simple but should cover the majority of customization criteria.

**Comment by vanGalilea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/1448?planning-poker) with ZenHub @khushal87 @madsroskar @santhoshvai @vishalnarkhede

**Comment by vanGalilea** [comment]
@{{user_name}} thanks for reaching out. 
This issue was moved to an internal backlog list of less urgent feature/docs requests. I'll be closing this issue for now.
Please don't hesitate to contact us in the future if any other questions arise.
