### ISSUE TITLE
Allow access to gallery issue after allowed permissions in chat attachment

### ISSUE THREAD

**Issue by praveenbalajia** [GetStream/stream-chat-react-native#1451]
**Describe the bug**
Not able to send gallery photos from the Android device. It asks for allow permission but i have already added in Androidmanifest file

**Dev environment info (please complete/provide the following information):**

- "stream-chat-react-native": "3.6.5"
- "react-native": "0.68.1"

**To Reproduce**

1. Go to MessageList
2. Click on any thread
3. Click an attachment icon in MessageInput

**Expected behavior**
Able to send gallery images in the chat

**Additional context**
Added the below permissions in manifest
      <uses-permission android:name="android.permission.INTERNET" />
      <uses-permission android:name="android.permission.CAMERA" />
      <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
      <uses-permission android:name="android.permission.QUERY_ALL_PACKAGES" />
      <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
      
Chat Component
      {chatClient ?
        <>
          <OverlayProvider bottomInset={10}>
          <Chat client={chatClient}>
            {channel ?
              <Channel
                channel={channel}
                disableTypingIndicator
                enforceUniqueReaction
                initialScrollToFirstUnreadMessage
                keyboardVerticalOffset={Platform.OS === 'ios' ? 0 : -300}
                // messageId={messageId}
                NetworkDownIndicator={() => null}
                thread={selectedThread}
              >
                {selectedThread ? (
                  <Thread />
                ) : (
                  <View style={{ flex: 1, height: "100%" }}>
                    <MessageList
                      // thread={selectedThread}
                      onThreadSelect={(thread) => {
                        setSelectedThread(thread);
                        props.navigation.navigate('ThreadScreen', {
                          channel: channel,
                          thread: thread,
                        });
                      }}
                    />
                    <MessageInput additionalTextInputProps={{ ...TextInputProps, autoCorrect: false }} />
                  </View>)}
              </Channel> : <ChannelList onSelect={(channel) => setChannel(channel)} />}
          </Chat>
          </OverlayProvider>
        </>
        : null}
**Screenshots*
![Screenshot_1654750431](https://user-images.githubusercontent.com/84975831/172785482-68c0b187-fd3b-4271-80bb-9e29e8a19d20.png)

**Comment by khushal87** [comment]
Hey @praveenbalajia,

I see that you are using an older version of stream-chat-react-native but a relatively new version of react-native.
Please follow this _version compatibility table_ - https://getstream.io/chat/docs/sdk/reactnative/#version-compabilities and it might be the reason for your problem.

Please upgrade/downgrade the packages and get back to us if you face any problems.

Thanks and regards,
Khushal Agarwal

**Comment by praveenbalajia** [comment]
@khushal87 same issue after upgrading the following versions
stream-chat-react-native: "4.2.0"
react-native-reanimated: "2.4.0"

**Comment by khushal87** [comment]
Hey @praveenbalajia,
Did you follow this guide for the package `@react-native-community/cameraroll` to update the permissions in the `AndroidManifest.xml` file?

https://github.com/react-native-cameraroll/react-native-cameraroll#permissions

**Comment by praveenbalajia** [comment]
Yes @khushal87 I have added those permissions in AndroidManifet.xml file but not working.

**Comment by khushal87** [comment]
Can you share your AndroidManifet.xml? @praveenbalajia

**Comment by vanGalilea** [comment]
links to this [issue](https://github.com/GetStream/stream-chat-react-native/issues/1360)

**Comment by santhoshvai** [comment]
Hey @praveenbalajia,

You can fix this by changing to a fork of the cameraroll library that we have created. 

Edit the following in your package.json:
`"@react-native-community/cameraroll": "git+https://github.com/GetStream/react-native-cameraroll.git"`

With the v5 release, we will update our dependency to this fork. Hence, I am closing this issue in favor of #1561
