### ISSUE TITLE
Not getting message payload for Android notifications

### ISSUE THREAD

**Issue by filipeGuerreiro** [GetStream/stream-chat-react-native#1454]
**Describe the bug**

Current project is on v2.
Trying to get notifications to display on Android, so want to have a `message` field in the notification payload. Here is what we are getting instead (just `data`):
```
{"data": {"channel_id": "!members-<...>", "channel_type": "messaging", "cid": "messaging:!members-<...>", "id": "<...>", "message_id": "<...>", "sender": "stream.chat", "type": "message.new", "version": "v2"}, "finish": [Function finish], "foreground": false, "id": "<...>", "userInteraction": false}
```

Following along from the [docs](https://getstream.io/chat/docs/sdk/reactnative/guides/push-notifications-v2/#add-notification-field-in-android-payload) and this [ticket](https://github.com/GetStream/stream-chat-react-native/issues/1355#issuecomment-1124024540), I am attempting to configure the android payload in the backend by calling this:

```
const client = StreamChat.getInstance(apiKey, apiSecret);
const notification_template = `{
    "title": "New message from {{ sender.name }}",
    "body": "{{ truncate message.text 2000 }}"
    "click_action": "OPEN_ACTIVITY_1",
    "sound": "default"
}`;

client.updateAppSettings({
  firebase_config: {
    notification_template,
  }
});
```

And what I am getting is an error with:

```
UpdateApp failed with error: "notification_template should be a JSON object after variables are interpolated
```

I have tried to set `title` and `body` to only have simple strings (no variables) and the error comes back the same.
Also, when setting `notification_template` with an empty string, the `updateAppSettings` call is successful but the notification payload that I receive on clients is unchanged (no `message` payload).

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native): 4.3.1
- react-native version: 0.67.4
- Device/Emulator (android) and OS version: Samsung S21. Android 12
- Back-end stream-chat-js version: 6.6.0

**To Reproduce**

1. With an empty project, try executing `updateAppSettings` with the above payload.
2. See that the call fails with an error.

**Expected behavior**

A message to be displayed when in background mode (a message field to come with the notification).

**Comment by finalight** [comment]
turns out in the documentation, they were missing a comma at the second line of the notification template

```
const notification_template = `{
    "title": "New message from {{ sender.name }}",
    "body": "{{ truncate message.text 2000 }}",
    "click_action": "OPEN_ACTIVITY_1",
    "sound": "default"
}`;
```

can you guys please update the documentation as well?

**Comment by madsroskar** [comment]
Thanks for pointing this out, I've created a PR to correct this in our docs

**Comment by filipeGuerreiro** [comment]
Thank you! It's resolved. Closing this issue
