### ISSUE TITLE
RTL Support: Latest message text direction

### ISSUE THREAD

**Issue by Enigma-I-am** [GetStream/stream-chat-react-native#1455]
## 🎯 Issue

Latest message text direction when TypescriptMessaging app is set to Hebrew does not follow the correct text direction as seen in the images below. in the first case we have "You: ווןןםםם .ךךכאגייח" while in RTL based languages like Hebrew it should be "ווןןםםם .ךךכאגייח :You". Also note that the translation for this "You" have not been provided for this case.

<table>
    <thead>
        <tr>
            <td>What we have currently </td>
            <td>Figma</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                <img src="https://user-images.githubusercontent.com/24194413/173100943-dc5064b3-2c10-4454-9340-8516c6d58d95.png" />
            </td>
            <td>
                <img src="https://user-images.githubusercontent.com/24194413/173101014-0ea9b07a-d340-4841-8d8c-f6ded989eb61.png" />
            </td>
        </tr>
    </tbody>
</table>

## 🛠 Recommendation
in the getLatestMessagePreview function we check if the application is set to RTL using `I18nManager.isRTL` reverse we generate/ the latest text from the latest message gotten from the client and append the translation of "You" to the end of the message string and ellipsis to the start of the message string.

**Comment by madsroskar** [comment]
<img width="369" alt="image" src="https://user-images.githubusercontent.com/1548276/179736739-528226df-3a19-4edc-a984-b99cbdf064b6.png">

This is solved for the case of `You:`, but not when the last message is sent by somebody else. I am, however, a bit unsure how this should look in RTL, so I'll look into how it looks in different apps.

**Comment by vanGalilea** [comment]
Closing due to descoping
