### ISSUE TITLE
RTL Support: TextInput  hint-text direction change and translations

### ISSUE THREAD

**Issue by Enigma-I-am** [GetStream/stream-chat-react-native#1458]
## 🎯 Issue

- Position on hint text in textfield is still LTR and not RTL
- No translation for "Send Message" in Hebrew and Arabic (RTL languages)

<table>
    <thead>
        <tr>
            <td>What we have currently </td>
            <td>Figma</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                <img src="https://user-images.githubusercontent.com/24194413/173185246-4267d290-7fc9-4a8b-a1ef-eb597db27a6e.png" />
            </td>
            <td>
                <img src="https://user-images.githubusercontent.com/24194413/173185239-d42db3f4-91f8-495e-a961-c6903ee204d5.png" />
            </td>
        </tr>
    </tbody>
</table>

## 🛠 Recommendation

- Check if application is set to RTL and apply `textAlign : "right"` to textInput field

**Comment by vanGalilea** [comment]
Let's try to solve this via the TextInput itself or flex styling
