### ISSUE TITLE
Broken link in doc

### ISSUE THREAD

**Issue by Ildarik** [GetStream/stream-chat-react-native#1464]
https://github.com/GetStream/stream-chat-react-native/blob/main/package/src/components/Message/MessageSimple/MessageText.md#rendertext

Link for `renderText` is wrong

**Comment by vanGalilea** [comment]
@Ildarik  thanks for reaching out. We have added this to our backlog. Follow this issue to stay posted!

**Comment by vishalnarkhede** [comment]
Hey @Ildarik please don't refer to raw files for docs. They are going to be removed soon since they are deprecated and unmaintained. Please use following as only source of documentation - https://getstream.io/chat/docs/sdk/reactnative/

**Comment by vishalnarkhede** [comment]
The link is not exactly broken, those .md files get compiled into a single page and the link refers to something which is expected to be in compiled docs.
