### ISSUE TITLE
Removed File reappears in the fileUploads array

### ISSUE THREAD

**Issue by vinaygregoryjohn183** [GetStream/stream-chat-react-native#1465]
**Describe the bug**
 have a use case where i want to remove a file which was selected from the attachment picker. I tried calling the removeFile() provided by the MessageInputContext. Once I call it the file gets deleted from the fileUploads but somehow reappears in the fileUploads array (fileUploads- provided by the MessageInputContext). How does this happen as I'm not manually re-selecting the removed file?PS: removeImage() is working fine. But removeFile() doesn't.
My code:
const MessageInputComponent = () => {
const {
toggleAttachmentPicker,
imageUploads,
removeImage,
fileUploads,
removeFile
} = useMessageInputContext();

// Working fine
useEffect(() => {
removeImage(imageUploads[0]?.id);
}, [imageUploads, removeImage]);

// Not working (the removed file reappears in the fileUploads array)
useEffect(() => {
removeFile(fileUploads[0]?.id);
}, [fileUploads, removeFile]);

![Screenshot 2022-06-14 at 10 29 36 AM](https://user-images.githubusercontent.com/82080446/173496776-61372849-33ed-46a8-b2ed-f623dc6eafc8.png)
--

**Dev environment info (please complete/provide the following information):**
Package Versions:
"react-native": "0.66.4",
"stream-chat": "^6.3.0",
"stream-chat-react-native": "^4.6.1”

**Expected behavior**
The removed file should not reappear in the fileUploads array provided by stream's MessageInputContext.

**Comment by vanGalilea** [comment]
Hi @vinaygregoryjohn183, thanks for reaching out. I've managed to reproduce this issue.

After removing the file, the file is not visible in the `MessageInput` component yet present in the `fileUploads` array originating from `useMessageInputContext`.

We might be over-memoizing something. We will take a look at it. You can keep on following this issue for any updates.

Out of curiosity, what impact does it have on you and your users if the UI works as expected?

**Comment by vanGalilea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/1465?planning-poker) with ZenHub @Enigma-I-am @khushal87 @madsroskar

**Comment by vanGalilea** [comment]
This issue became stale. I'll be closing this issue for now.
Please don't hesitate to contact us in the future if this issue or any questions arise.
