### ISSUE TITLE
Reactions indicator on message component breaks in RTL

### ISSUE THREAD

**Issue by Enigma-I-am** [GetStream/stream-chat-react-native#1467]
## 🎯 Issue

Reactions indicator on message component breaks in RTL. The bubbles are still in LTR mode and does not conform when app is set to RTL.

<table>
    <thead>
        <tr>
            <td>What we have currently </td>
            <td>Figma</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                <img src="https://user-images.githubusercontent.com/24194413/173500118-a5bba33d-5b65-401b-aece-2ed7cff14868.png" />
            </td>
            <td>
                <img src="https://user-images.githubusercontent.com/24194413/173500161-61230e33-3dab-45cc-a015-71b5b5ec24e0.png" />
            </td>
        </tr>
    </tbody>
</table>

## 🛠 Recommendation
check if app is in RTL and set the bubble to correct position

**Comment by vanGalilea** [comment]
Closing due to descoping

**Comment by samihabuawadSL** [comment]
I have found a away to hode it using theme: 
reactionList: {
          container: {
            // a away to hide the bubble
            width: 'auto',
            maxWidth: 200,
          },
       }
