### ISSUE TITLE
QueryChannels failed with error: Watch or Presence requires an active websocket connection - Logs

### ISSUE THREAD

**Issue by mishkeTz** [GetStream/stream-chat-react-native#1480]
**Describe the bug**
I get a lot of 400 errors in Logs on GetStream dashboard with error message:
```
QueryChannels failed with error: "Watch or Presence requires an active websocket connection, please make sure to include your websocket connection_id"
```

**Dev environment info (please complete/provide the following information):**

- 3.9.2 (stream-chat-react-native)
- 0.63.4 (react-native) 
- Device(Android/iOS) all versions

**To Reproduce**

1. Open the app and go to the screen where you show the list of channels
2. Leave the app and keep it in the background
3. After some time open the app, you should still be on the same screen with the list of channels, it should render 'Reconnecting...' info at the top
4. At that moment, while it's 'Reconnecting...', if you pull down to refresh the list I believe that's when the error above happens

**Expected behavior**
Fix this issue so that there are no more of these kinds of errors in Logs.

**Additional notes**
I might be wrong, however, I'd like to get an explanation of how to fix this error! :) 

**Screenshots**
![0-02-0a-a7f4a0b8f866d37fa97b911d78e4f3c629a1fa164b35e567fa66105c449e6e93_1c6dacc51f0818](https://user-images.githubusercontent.com/15350199/173895778-840d7c8f-ccf9-4b26-bf55-92c66f888f5e.jpg)

**Comment by mishkeTz** [comment]
BUMP!

**Comment by vanGalilea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/1480?planning-poker) with ZenHub @khushal87 @madsroskar @santhoshvai @vishalnarkhede

**Comment by vanGalilea** [comment]
@mishkeTz, thanks for reaching out. Sorry for the late response.

This is a behavior that I saw in the past and had to do with an outdated `stream-chat` version that originates in `stream-chat-react-native.`

Can you please specify the version installed by looking at your `yarn.lock` or `package-lock.json` file?

At the same time, I strongly suggest upgrading `stream-chat-react-native` to the latest stable version, 4.12.1. This will solve the issue, and you can do it easily by following [this migration guide](https://getstream.io/chat/docs/sdk/reactnative/basics/upgrading-from-v3/)

**Comment by mishkeTz** [comment]
Hello @vanGalilea,
In the meantime, I updated the package to 4.4.0.
Do you know in which version this issue was fixed?

**Comment by vanGalilea** [comment]
@mishkeTz please upgrade to https://github.com/GetStream/stream-chat-react-native/releases/tag/v4.7.0 which uses the more upgraded version of `stream-chat` lib.

I'll be closing this issue, please keep on monitoring this issue and don't hesitate to contact us
