### ISSUE TITLE
I can not find `friendship_request`

### ISSUE THREAD

**Issue by cleandevcode** [GetStream/stream-chat-react-native#1481]
Hello.
I am using this SDK for my RN app and it's really amazing.
I am gonna implement one feature for messaging requests.
So the idea is that there is a request to another user and he can approve or deny my request.
When checking the document, I found the event custom - https://getstream.io/chat/docs/react-native/custom_events/

I am think if I can use this `friendship_request` feature 
![image](https://user-images.githubusercontent.com/52365167/173929375-0cf17084-a92a-4763-bbeb-c9abd22905fd.png)

But actually this type did not exist.
I could not find it from EVENT_MAP.
![image](https://user-images.githubusercontent.com/52365167/173929818-bcac0584-ca01-4555-93af-6058f1105dbf.png)

But I am not sure if I can use this feature for my idea.
If I can use it, then which event type is for it?

```
stream-chat: 6.1.0
stream-chat-expo: ^4.1.0
react: 16.15.1
expo: ^40.0.0
react-natve: 0.63.4
```

Thanks.

**Comment by vishalnarkhede** [comment]
@cleandevcode the document that you are looking at is about custom events. You can checkout [`Invites Documentation`](https://getstream.io/chat/docs/react-native/channel_invites/?q=invite) for your usecase.

**Comment by cleandevcode** [comment]
@vishalnarkhede Thank you for your kind message.
I will try with the invites feature.

**Comment by cleandevcode** [comment]
@vishalnarkhede This was my codebase.

```
const channel = client.channel(`messaging`, null)
await channel.inviteMembers(memberArray)
```

But it returned error says `channel id is not defined` .

So I tried to set the distinct channel id manually like
```
const channel = client.channel(`messaging`, channelID)
```
but it also returns Error says `cannot invite members to the distinct channel, please create a new distinct channel with the desired members`

Then how can I initialize the channel to invite members?
Thanks.
