### ISSUE TITLE
The order  in the Gallery is incorrect

### ISSUE THREAD

**Issue by neopit** [GetStream/stream-chat-react-native#1482]
The order  in the GallerGallery is incorrect

Example:
Upload 4 images.
On the message list, the 4 images appear.

First bug: 
If we click on image number 2 then it is not the image 2 that appears in the ImageGallery. It always displays the image 4/4. 

Second bug:
When we click on an image then it opens the ImageGallery at the last position. Why the last position?

Third bug:
If we upload  4 images, then when we click on one of the images for opening the ImageGallery then the first image uploaded is at the position fort (last). It has to be first

**Expected behavior**
When we upload several images ( like 4), then if we click the first image for opening the ImageGallery then the ImageGallery has to 

- Display the selected image
- If the image selected is the number one then it has to be the first in the image gallery
- The first image uploaded has to be first all time

![Simulator Screen Shot - iPhone 13 - 2022-06-15 at 20 28 12](https://user-images.githubusercontent.com/1306961/173985008-a25b6907-bc84-459e-864a-be60e22577b4.png)
![Simulator Screen Shot - iPhone 13 - 2022-06-15 at 20 29 04](https://user-images.githubusercontent.com/1306961/173985016-e0bb3c06-e399-44b8-bc3a-8048831108cc.png)

**Comment by madsroskar** [comment]
Hi, thanks for reporting the issue. I've tested this on my end, and to summarize:

1. Images in the gallery are being rendered in the opposite order than in the preview in the MessageList
2. No matter which image you select, it's always the last image of the list that opens first.

**Comment by vanGalilea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/1482?planning-poker) with ZenHub @Enigma-I-am @khushal87 @madsroskar @santhoshvai @vishalnarkhede

**Comment by gpahal** [comment]
I am also facing this issue along with inconsistencies with swiping. I created a new issue here and added a screen recording - https://github.com/GetStream/stream-chat-react-native/issues/1627
