### ISSUE TITLE
UX Bug · Reactions are clunky

### ISSUE THREAD

**Issue by charltongroves** [GetStream/stream-chat-react-native#149]
**Describe the bug**
While they work as intented, the current reactions UX could use a lot of improvement.

1. Android has overflowing elements and weirdly low opacity emoji
![image](https://user-images.githubusercontent.com/15869505/75135470-533ef080-572d-11ea-8bcf-de5f3ede2967.png)

2. Pressing a reaction doesn't actually update the UI until (im guessing) the request succeeds. This means there is a ~500ms lag between pressing a reaction, and seeing that the press worked. This bad UX gets doubly bad because if you try to press it again, it will just undo the action (see attached video for example). Please use optimistic updating instead. (i cant overstate how bad of a UX this is lol, it has been massively frustrating in demos of our chat app)

3. There is some very strange behaviour when reacting to something with the keyboard open (see attached video)

I'm really keen to use reactions but its hard when they're so frustrating to use. Other apps like slack and fb messenger have pretty much flawless implementations. Can you guys look at those apps and copy how they did it?

If you guys have no plans to improve this, please let me know. I'll build out my own in that case.

Also on another note, is there anyway to change the speed of the animation of Messagelist when the keyboard opens and shuts, it is wayy too slow at the moment.

**Dev environment info (please complete/provide the following information):**

- Package version: 0.6.3
- Device/Emulator (android/ios) and OS version: both ios & android, version independent

**Video**
https://gfycat.com/charmingcolossalaustrianpinscher

**Comment by vishalnarkhede** [comment]
Hey @charltongroves , sorry to hear that you are having bad experience with reactions and keyboard. I will take a look at reactions in next few days and see what improvements can be done. I will get back to you on it.

Regarding animation of MessageList - in latest version (v0.6.6) of our sdk, I added support for custom animation duration. You can find description here - https://github.com/GetStream/stream-chat-react-native/blob/master/src/components/Channel.js#L96

**Comment by vishalnarkhede** [comment]
@charltongroves this should be published soon, I will let you know once this is out :)

**Comment by charltongroves** [comment]
awesome thanks!

**Comment by vishalnarkhede** [comment]
**Update**

@charltongroves the commits which had optimistic UI updates had to be reverted unfortunately because of some edge cases. Next week I will get back on it and try to make this change in some other way :)

**Comment by charltongroves** [comment]
ahhh shame, but understandable. 

Thanks

**Comment by dcsena** [comment]
^ Ping Would like to know as well.

**Comment by virdesai** [comment]
we're working on a new reaction pick design

**Comment by dcsena** [comment]
@virdesai awesome to hear - do you have an ETA on when we can use it ?

**Comment by virdesai** [comment]
@dcsena tough to say but the work is underway in [this](https://github.com/GetStream/stream-chat-react-native/pull/384) PR and the redesigns/customizations of this and many other areas of the SDK are a top priority of ours this quarter

**Comment by lokewk** [comment]
hey, have the fix been push?
I am facing this issue too.
