### ISSUE TITLE
The UI for Mentions is broken when there are many users to mention

### ISSUE THREAD

**Issue by santhoshvai** [GetStream/stream-chat-react-native#1490]
https://user-images.githubusercontent.com/3846977/174265552-e047a225-590d-4fa0-ba82-0a1febec06c8.mp4

The relevant component: `package/src/components/AutoCompleteInput/AutoCompleteSuggestionList.tsx`

**Comment by vanGalilea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/1490?planning-poker) with ZenHub @khushal87 @madsroskar @vishalnarkhede @santhoshvai
