### ISSUE TITLE
Can not invite members

### ISSUE THREAD

**Issue by cleandevcode** [GetStream/stream-chat-react-native#1492]
This is my environment.
```
stream-chat: 6.1.0
stream-chat-expo: ^4.1.0
react: 16.15.1
expo: ^40.0.0
react-natve: 0.63.4
```

I am gonna implement the invite members feature.

My solution was below:
![image](https://user-images.githubusercontent.com/52365167/174327860-221a040d-124a-469b-8ff3-ffb521f45767.png)

But it returned Error says `channel ID is undefined`.

So I updated the code this way.
![image](https://user-images.githubusercontent.com/52365167/174328109-003fe048-b507-4577-b073-0f0eeb4c0a6c.png)

But it also returns errors like: 
`Error: StreamChat error 4: GetOrCreateChannel failed with error: "When using member based IDs specify at lease 2 members"`

So I also updated again this way.
![image](https://user-images.githubusercontent.com/52365167/174329214-58d6924f-bdcb-438c-a2f1-500d82c60339.png)

Here `channelData` is object like
```
const channelData = {
 members: [userID1, userID2]
}
```

But it also returns another error like:
`Error: StreamChat error 17: UpdateChannel failed with error: "cannot invite members to the distinct channel, please create a new distinct channel with the desired members."`

I am really not sure. Regarding this error message, seems the channel is already created. But I did not create a new channel with this user. This is the new user I am gonna invite to the new channel.

Please give me some ideas how to fix it.

Thanks.

**Comment by cleandevcode** [comment]
@vishalnarkhede 
I also tried that way
![image](https://user-images.githubusercontent.com/52365167/174334210-e0c8d9d7-c058-4302-bf6a-a1c42fee71b2.png)

But it returns the same error
`Error: StreamChat error 17: UpdateChannel failed with error: "cannot invite members to the distinct channel, please create a new distinct channel with the desired members."`

**Comment by madsroskar** [comment]
To expand a bit on that:

The second parameter of `client.channel` is either a channel ID or an object of custom channel data. However, if you omit giving the channel an ID, you need to add the members to the third parameter of the channel call. For example:

```
  const members = [
    {
      user: {
        id: "vishal",
      },
    },
    {
      user: {
        id: "mads",
      },
    },
  ];

  try {
    await client.connectUser(
      { id: "mads" },
      "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoibWFkcyJ9.pMhj43K1nzs-T9MHuQVYwbxqLGPRMVZyWv8COBKj8wY"
    );
    const channel = client.channel("messaging", null, { members: members });
    await channel.create();

    console.log(`Channel members: ${Object.keys(channel.state.members)}`);
  } catch (error) {
    console.log(`Error: ${error}`);
  }

```

However, in this case you can't invite new members to this channel. You'll have to create a new channel with a new list of members - that's what meant by "distinct channel" in this case.


-----

The second case is where you have a channel with an ID. For that case, you can invite members with the `inviteMembers()` function. For example:

```
  const members = [
    {
      user: {
        id: "vishal",
      },
    },
    {
      user: {
        id: "mads",
      },
    },
  ];

  try {
    await client.connectUser(
      { id: "mads" },
      "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoibWFkcyJ9.pMhj43K1nzs-T9MHuQVYwbxqLGPRMVZyWv8COBKj8wY"
    );
    const channel = client.channel("messaging", "someChannelID");
    await channel.create();
    channel.inviteMembers(members);

    console.log(`Channel members: ${Object.keys(channel.state.members)}`);
  } catch (error) {
    console.log(`Error: ${error}`);
  }

```

The important thing to note here is that I'm **not** adding members in the third parameter of the channel call in the second example here.

Would either of these examples work for your case?

**Comment by cleandevcode** [comment]
Thank you for your updates.
The main issue I am facing is the `someChannelD`.
I dont have any new created channel for now, so I was trying to create a new channel with the new member with 
`null` as a 2nd param and `members` as a 3rd param.

So I tried this way

```
const channel = client.channel("messaging", null, { members: members });
await channel.create();  // I believed here will create a new channel
await channel.inviteMembers(members)  // Also I believed a new channel can invite the new member
```

I only work with client-side SDK, and are there any solution to invite members on my case?
