### ISSUE TITLE
Invite Member Feature

### ISSUE THREAD

**Issue by cleandevcode** [GetStream/stream-chat-react-native#1494]
Hello, there.

I am gonna implement invite member feature using this SDK.
The ideal workflow I want is Skype.
So there are 2 users - user 1 and user 2.

- User 1 requests an invitation with some message to user 2. (He will send some messages continuously  even User 2 does not accept yet)
- User 2 can accept or deny User 1`s request.
- Once User 2 accepts User 1`s request, then the previous invitation message will be the first chat history with him.

I checked this guide - https://getstream.io/chat/docs/react/channel_invites/

Is it possible to implement like above only on client-side?

Thanks.

**Comment by madsroskar** [comment]
I'm not entirely sure I understand what you're trying to achieve. Am i understanding correctly that you'd want for user 1 to be able to send messages to the channel, but when user 2 accepts the invite, only the invitation message is displayed - effectively removing all messages user 1 sent before user 2 accepted the invite?

**Comment by vanGalilea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/1494?planning-poker) with ZenHub @khushal87 @madsroskar @santhoshvai @vishalnarkhede

**Comment by vanGalilea** [comment]
@cleandevcode implementing a message request can be achieved as mentioned in our [docs in section channel incvites](https://getstream.io/chat/docs/react/channel_invites/). You've mentioned this specific docs page already, so it should be familiar to you.

I'll be closing this issue for now. Please don't hesitate to contact us in the future if this issue or any questions arise.

**Comment by brayohmurithidev** [comment]
> Hello, there.
> 
> I am gonna implement invite member feature using this SDK. The ideal workflow I want is Skype. So there are 2 users - user 1 and user 2.
> 
> * User 1 requests an invitation with some message to user 2. (He will send some messages continuously  even User 2 does not accept yet)
> * User 2 can accept or deny User 1`s request.
> * Once User 2 accepts User 1`s request, then the previous invitation message will be the first chat history with him.
> 
> I checked this guide - https://getstream.io/chat/docs/react/channel_invites/
> 
> Is it possible to implement like above only on client-side?
> 
> Thanks.

Were you able to take care of this? Am trying to implement a similar approach and I need help.
