### ISSUE TITLE
The Video inline on v4.7 is not render with the right dimension on Android.

### ISSUE THREAD

**Issue by juanjorge** [GetStream/stream-chat-react-native#1495]
**Describe the bug**
After the [full video support release](https://github.com/GetStream/stream-chat-react-native/releases/tag/v4.7.0) the and added the [react-native-video](https://getstream.io/chat/docs/sdk/reactnative/?utm_campaign=RNvideo_June2022%2F&utm_medium=Email&utm_content=Product_And_Developer&utm_source=RNvideo#add-optional-dependencies) package, on Android the dimension are not correct.

**Dev environment info (please complete/provide the following information):**

- Package version: `"stream-chat-react-native": "^4.7.2"`
- react-native or expo version: `react-native: 0.64.3` `expo: 5.4.8`

**Expected behavior**
The video on Android should be fit to the with of the screen like iOS does.

**Screenshots**

![Screenshot_20220617-144625](https://user-images.githubusercontent.com/4811095/174393248-8027e1e5-86a6-4f38-b545-a5501096ab90.jpg)

https://user-images.githubusercontent.com/4811095/174393012-e3dd126a-bc94-4049-a4d5-116bf981ab14.mp4

**Comment by valmotor2** [comment]
I have the same problem, can you help us about this ? we need some settings for android? 
Thanks

**Comment by madsroskar** [comment]
What device are you experiencing this on? I can't seem to reproduce it on a Samsung Galaxy S20.

Does it differ depending on the file type of the video at all?

**Comment by juanjorge** [comment]
@madsroskar I tested on Samsung Galaxy S21, also in the emulator Nexus_6P_API_31

**Comment by valmotor2** [comment]
> What device are you experiencing this on? I can't seem to reproduce it on a Samsung Galaxy S20.
> 
> Does it differ depending on the file type of the video at all?

Samsung S10

**Comment by vanGalilea** [comment]
Hey @juanjorge we're investigating this at the moment and working towards a solution that soon will be live

**Comment by khushal87** [comment]
Hey @juanjorge, can you mention your API version and other design-related stuff(if used any)? I couldn't reproduce it on end even on a Nexus 6P device.

<img width="430" alt="Screenshot 2022-08-01 at 17 50 33" src="https://user-images.githubusercontent.com/39884168/182146436-c45500fd-b929-4a8a-b478-44bbbaff00a4.png">

**Comment by santhoshvai** [comment]
Hi @juanjorge and @valmotor2 ,

After investigation, I found that his happens when exo player is not used for android. `React native video` should have made exo player as the default when linking but it hasn't don't that. It will be done in v6. You can make the library to use exo player by adding the following in your `settings.gradle`

```
include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')
```
