### ISSUE TITLE
Showing a placeholder or a spinner when images are loading in the message list instead of a white space

### ISSUE THREAD

**Issue by neopit** [GetStream/stream-chat-react-native#1496]
Being able to display a placeholder or a spinner (or any component) when an image is loading in the message list.

**Motivation**
Currently, when the image is loading there is only white space and the user is not informed that something is loading.

**Proposed solution**
For some big images or videos, it is confusing for the user to see white in the message list because it can take time for displaying them.
The solution is to be possible to override the ImageGallery component in the Gallery.tsx or possibly pass some props that belong to the react-native.Image component (like onLoad, onLoadStart, onLoadEnd) (https://reactnative.dev/docs/image)

**Acceptance Criteria**
 - Display a placeholder when the image is loading in the message list

**Comment by neopit** [comment]
Hmm It seems you have already a work in progress on this


https://github.com/GetStream/stream-chat-react-native/pull/1444

**Comment by madsroskar** [comment]
Hi, @neopit. Yes, this is being worked on, and is tracked with #1005. I'll close this issue, please add any comments you may have in that issue.
