### ISSUE TITLE
The top and the bottom right of the images are cut by one pixel and affects the rounded corne

### ISSUE THREAD

**Issue by neopit** [GetStream/stream-chat-react-native#1497]
**Describe the bug**
Even if we try to override the settle on the image (ImageGallery), the top and the bottom right of the images are cut by one pixel and affects the rounded corner (top and bottom right)

**Expected behavior**
Being able to correctly adjust the top and bottom right or the images

**Screenshots**
![Screen Shot 2022-06-17 at 4 43 39 PM](https://user-images.githubusercontent.com/1306961/174414557-6372623e-33b4-4edb-8748-6dba824cb543.png)

**Comment by madsroskar** [comment]
Thanks for raising this issue. We'll have to sort this out to not interfere with the rounded borders.

**Comment by vanGalilea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/1497?planning-poker) with ZenHub @khushal87 @madsroskar @vishalnarkhede

**Comment by madsroskar** [comment]
Hi, @neopit. I'm having some trouble with understanding what exactly is wrong here. With the attached image, I've set the `borderBottomRightRadius` and `borderTopRight` properties to 7, and as far as I can tell, it's behaving the way I would expect it to. 

![image](https://user-images.githubusercontent.com/1548276/190169461-fa3afe69-8ae2-4c53-8b7e-77de4ef8399f.png)

Could you maybe add a couple of screenshots of the issue on your end, and describe what's deviating from what you expect to see? it would also be helpful to see what you've added to your theme properties.

**Comment by vishalnarkhede** [comment]
@neopit ping!!

**Comment by vanGalilea** [comment]
@neopit thanks for reaching out. I'll be closing this issue for now.
Please don't hesitate to contact us in the future if this issue or any questions arise.
