### ISSUE TITLE
messaging app (SampleApp) navigation.goBack not defined when creating a new group

### ISSUE THREAD

**Issue by Agupta00** [GetStream/stream-chat-react-native#1506]
Hello, Please see the attached video below of the bug I described. 

The problem is when you go "New Group" -> "Name the Group" -> "Back Button", you get an error since `        navigation.goBack();` in `ScreenHeader.tsx` does not have anything to go back to. 

The expected behavior would be that it does / when you are back on the home screen you should be able to navigate to other chats, which you are not able to do. 

If there is a quick fix, please do let me know, thanks!
As a quick hack, I have tried to add this but it didn't work. 

```
        if (!navigation.canGoBack()) {
          navigation.reset({
            index: 0,
            routes: [
              {
                name: 'HomeScreen',
              },
            ],
          });
        } else {
          navigation.goBack();
        }
```

Error: ` ERROR  The action 'GO_BACK' was not handled by any navigator.`

https://user-images.githubusercontent.com/12666226/174914438-789d41f9-bf8a-42e8-b9ef-70cc4ac3687a.mov

**Comment by vanGalilea** [comment]
@Agupta00 thanks for reaching out. We have added this to our low-prio backlog. Follow this issue to stay posted!

**Comment by Vrunalbenke** [comment]
<img width="318" alt="Screenshot 2023-11-29 at 5 54 51 PM" src="https://github.com/GetStream/stream-chat-react-native/assets/88709028/9137bd65-b181-4efe-9d27-e053fffb74d4">
where is User profile ?
