### ISSUE TITLE
Focus on the message input automatically when giphy mode is active

### ISSUE THREAD

**Issue by khushal87** [GetStream/stream-chat-react-native#1508]
**Motivation**
When a user types `/giphy` or chooses the giphy command from the auto-complete suggestion list the message input doesn't get active after giphy mode is active. 

**Acceptance Criteria**
As a user I want the message input to be focused automatically so that I don't have to press the message input to start typing.

**Comment by vanGalilea** [comment]
Proposed solution: focus on input after [`setGiphyActive(true);`](https://github.com/GetStream/stream-chat-react-native/blob/0a574421a56aa0e536b6ad9043169b2f2f111d08/package/src/components/AutoCompleteInput/AutoCompleteInput.tsx#L272) and [here](https://github.com/GetStream/stream-chat-react-native/blob/0a574421a56aa0e536b6ad9043169b2f2f111d08/package/src/components/AutoCompleteInput/AutoCompleteInput.tsx#L397)

**Comment by vanGalilea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/1508?planning-poker) with ZenHub @vishalnarkhede @khushal87 @madsroskar
