### ISSUE TITLE
Undefined is not a function 

### ISSUE THREAD

**Issue by mMajch** [GetStream/stream-chat-react-native#1514]
**"TypeError: undefined is not a function (near '...onStartReachedInPromise.current.finally...')"**

This error happens in multiple different scenarios. Some of them: 
- Receiving a message 
- Going back with a swipe gesture from the messages list screen
- Scrolling to the top of the messages list   

This issue was already reported several months ago https://github.com/GetStream/stream-chat-react-native/issues/980 . It might be hard to reproduce it because the race condition might not always happen. I found a root cause and described it precisely.

The root cause of an error seems to be a race condition between `maybeCallOnStartReached` and `maybeCallOnEndReached`.   These functions are located in `node_modules/stream-chat-react-native-core/src/components/MessageList/MessageList.tsx`. When the message list is **short enough** both conditions `isScrollAtStart` and `isScrollAtEnd` are met and both of these functions are called (one after each other). That results in error in `maybeCallOnEndReached`

```
...

const handleScroll: ScrollViewProps['onScroll'] = (event) => {
  if (!channel || !initialScrollSet.current || !channelResyncScrollSet.current) {
    return;
  }

  const offset = event.nativeEvent.contentOffset.y;
  const visibleLength = event.nativeEvent.layoutMeasurement.height;
  const contentLength = event.nativeEvent.contentSize.height;
  // Check if scroll has reached either start of end of list.
  const isScrollAtStart = offset < 100;
  const isScrollAtEnd = contentLength - visibleLength - offset < 100;

  if (isScrollAtStart) {
    maybeCallOnStartReached();  // It is called!
  }

  if (isScrollAtEnd) {
    maybeCallOnEndReached(); // It is called!
  }
  
  ...
```
Error happens here: 

 ```
// If onStartReached is in progress, better to wait for it to finish for smooth UX
    if (onStartReachedInPromise.current) { 
      onStartReachedInPromise.current.finally(() => { 
        onEndReachedInPromise.current = (threadList ? loadMoreThread() : loadMore())
          .then(callback)
          .catch(onError);
      });
    }
```

https://user-images.githubusercontent.com/44026723/175552960-fcdbe214-d798-4c7c-ad58-860631226f4a.mov

The question is: should both conditions `isScrollAtStart` and `isScrollAtEnd` be true at the same time when `handleScroll` is triggered? If yes then how to refactor the code to avoid race condition and crash?

**Dev environment info (please complete/provide the following information):**

- stream-chat-react-native 4.6.1 and 4.7.3
- react-native 0.66 and 0.67
- android and ios, simulator and real device

**To Reproduce**

1. Go to screen with MessagesList when there are only 1-3 short messages (not covering whole screen)
2. Go back with swipe gesture or scroll to top
3. See error

**Expected behavior**
The error should not happen and the application should definitely not crash.

Conditions `isScrollAtStart` and `isScrollAtEnd` should not be met at the same time **OR** `maybeCallOnStartReached` and `maybeCallOnEndReached` should be refactored and handle the possible race condition.

**Comment by mMajch** [comment]
@santhoshvai Yes, we do use that. I have no idea how that could be related. What I discovered is that changing `.finally` to `.then `helped - the logic works as intended and there are no crashes. Looks like the promise didn't have `finally` 

That's my patch:

```
diff --git a/node_modules/stream-chat-react-native-core/src/components/MessageList/MessageList.tsx b/node_modules/stream-chat-react-native-core/src/components/MessageList/MessageList.tsx
index 2fcd0ea..23f5757 100644
--- a/node_modules/stream-chat-react-native-core/src/components/MessageList/MessageList.tsx
+++ b/node_modules/stream-chat-react-native-core/src/components/MessageList/MessageList.tsx
@@ -664,7 +664,7 @@ const MessageListWithContext = <
 
     // If onEndReached is in progress, better to wait for it to finish for smooth UX
     if (onEndReachedInPromise.current) {
-      onEndReachedInPromise.current.finally(() => {
+      onEndReachedInPromise.current.then(() => {
         onStartReachedInPromise.current = loadMoreRecent(limit).then(callback).catch(onError);
       });
     } else {
@@ -701,7 +701,7 @@ const MessageListWithContext = <
 
     // If onStartReached is in progress, better to wait for it to finish for smooth UX
     if (onStartReachedInPromise.current) {
-      onStartReachedInPromise.current.finally(() => {
+      onStartReachedInPromise.current.then(() => {
         onEndReachedInPromise.current = (threadList ? loadMoreThread() : loadMore())
           .then(callback)
           .catch(onError);
```

Sadly that fix doesn't solve all the problems. After applying this change some people reported that the app restarts in similar scenarios when it crashed before. I didn't reproduce it yet so can't share more details now. I twould be great if you investigate it

**Comment by santhoshvai** [comment]
Hey @mMajch,

This could happen if a library imports `import "core-js/modules/es.promise";`. Could you please inform me of the version of redux-persist that you use? Could be related.
