### ISSUE TITLE
Custom. guide- paste from clipboard button in MessageInput

### ISSUE THREAD

**Issue by vanGalilea** [GetStream/stream-chat-react-native#1515]
**Motivation**
A handful amount of customers were asking how they can add a button that will apply a paste from the clipboard and will populate message input

**Proposed solution**
Write a short custom. guide

**Acceptance Criteria**
A custom. guide is released with all relevant code snippets and screenshots.

**Comment by nabin700** [comment]
**Hi sir!**
I am keenly interested in contributing to this issue. hope you assign this to me :)
[x] I will make a short custom guide as per your instruction

**Comment by vanGalilea** [comment]
This issue was moved to an internal backlog list of less urgent feature/docs requests.
