### ISSUE TITLE
Add video specifications in our documentation

### ISSUE THREAD

**Issue by khushal87** [GetStream/stream-chat-react-native#1519]
**Motivation**
Improve the documentation by adding the video feature-related stuff in it.

**Proposed solution**
I would like you to add a video section to our docs (just like push notifications) where we summarise the following:
- [ ] in which version the feature introduced
- [ ] enabling CDN v2 (different pricing and link to what it will cost)
- [ ] enabling it via optional install- steps

**Acceptance Criteria**

Add the above points to our documentation by creating a section for it.

**Comment by vanGalilea** [comment]
This issue was moved to an internal backlog list of less urgent feature/docs requests.
