### ISSUE TITLE
Slash commands not working for user with spaces in name

### ISSUE THREAD

**Issue by vanGalilea** [GetStream/stream-chat-react-native#1522]
**Describe the bug**
When running slash commands if a user has a space in their name field, commands don’t work for them. 
In this case, it is happening with mutes. It seems to work fine for mentions.

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native/stream-chat-expo): 4.7.0
- react-native or expo version: both, current sample app 0.67
- Device/Emulator (android/ios) and OS version: both and N/A

**To Reproduce**
1. Go to a channel.
2. Use `/mute` slash command in combination with a user WITH spaces, i.e. `Steve Galili`
3. An error should appear `invalid mute cmd, please specify a valid user` in the messages list.

Repeat with a user WITHOUT spaces and muting will work.

See video below for more info

**Expected behavior**
Slash commands should work for all users both with or without spaces in the name.

**Additional context**
User with spaces in the name- `Steve Galili`
User WITHOUT spaces in the name- `Thierry`

**Screenshots**

https://user-images.githubusercontent.com/25864161/176456051-fbe35028-1456-4134-85fd-8f6287ee19a5.mp4

**Comment by vanGalilea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/1522?planning-poker) with ZenHub @vishalnarkhede @madsroskar @khushal87

**Comment by vanGalilea** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/1522?planning-poker) with ZenHub @santhoshvai

**Comment by santhoshvai** [comment]
this is also a problem in react, can be tested here  https://getstream.io/chat/demos/livestream/

**Comment by santhoshvai** [comment]
I have reported it to the backend team as a bug on their side https://getstream.slack.com/archives/CE5N802GP/p1672735676557879
