### ISSUE TITLE
Tutorial: Passing Channel object as a navigation prop should not be recommended

### ISSUE THREAD

**Issue by santhoshvai** [GetStream/stream-chat-react-native#1529]
In the tutorial, we recommend passing, the channel object as a navigation property. Ref: https://getstream.io/chat/react-native-chat/tutorial/#navigate-from-channellist-to-channel and also in the subsequent sections.

This causes a warning in the app (shown below)

```
Non-serializable values were found in the navigation state. Check:

ChannelScreen > params.channel._client.activeChannels["league_chat:754796"] (Circular reference)

This can break usage such as persisting and restoring state. This might happen if you passed non-serializable values such as function, class instances etc. in params. If you need to use components with callbacks in your options, you can use 'navigation.setOptions' instead. See https://reactnavigation.org/docs/troubleshooting#i-get-the-warning-non-serializable-values-were-found-in-the-navigation-state for more details. 
```
The presence of a circular reference may also crash the app.

## The other solutions:

- Pass channel through context, like how it is done in TS messaging app
- Pass channelId through the navigation params and then watch the channel in an useEffect.

**Comment by vanGalilea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/1529?planning-poker) with ZenHub @khushal87 @madsroskar @santhoshvai @vishalnarkhede

**Comment by boblitex** [comment]
@santhoshvai could use a little help here, passing the channel object as a navigation prop does bring that error and I tried to use the useEffect approach, but I keep getting the error as shown in the screenshot below:
![image](https://user-images.githubusercontent.com/39277975/180982254-79a455b7-d6da-4842-af36-2dbfcbaac3d8.png)

I console logged `channelId` so I know for sure it's not undefined or null 
`LOG  channelId is this:  !members-ptIH2TfVtbKJCYOpunteVTb0W7vf7mZ9sMh1DAJripw`
my init snippet: 
```
import Bugsnag from '@bugsnag/react-native';
import { streamChatClient } from '@common/StreamChat/Client/StreamChatClient';
import React, { useEffect, useState } from 'react';
import { SafeAreaView } from 'react-native';
import { MessageInput, MessageList, Channel } from 'stream-chat-react-native';

export const ChannelScreen = ({
  navigation: { goBack },
  route: {
    params: { channelId },
  },
}) => {
  const [channel, setChannel] = useState();
  console.log('channelId is this: ', channelId);
  useEffect(() => {
    const init = async () => {
      if (!channelId) {
        goBack();
      }
      try {
        const thisChannel = streamChatClient.channel('messaging', channelId);
        if (!thisChannel.initialized) {
          await thisChannel.watch();
        }
        setChannel(thisChannel);
      } catch (error) {
        Bugsnag.notify(error);
      }
    };
    init();
  }, [channelId]);
  return (
    <SafeAreaView>
      <Channel channel={channel}>
        <MessageList />
        <MessageInput />
      </Channel>
    </SafeAreaView>
  );
};
```
my ChannelList show up fine, this issue is in the navigation to the channel

**Comment by boblitex** [comment]
> @santhoshvai could use a little help here, passing the channel object as a navigation prop does bring that error and I tried to use the useEffect approach, but I keep getting the error as shown in the screenshot below: ![image](https://user-images.githubusercontent.com/39277975/180982254-79a455b7-d6da-4842-af36-2dbfcbaac3d8.png)
> 
> I console logged `channelId` so I know for sure it's not undefined or null `LOG channelId is this: !members-ptIH2TfVtbKJCYOpunteVTb0W7vf7mZ9sMh1DAJripw` my init snippet:
> 
> ```
> import Bugsnag from '@bugsnag/react-native';
> import { streamChatClient } from '@common/StreamChat/Client/StreamChatClient';
> import React, { useEffect, useState } from 'react';
> import { SafeAreaView } from 'react-native';
> import { MessageInput, MessageList, Channel } from 'stream-chat-react-native';
> 
> export const ChannelScreen = ({
>   navigation: { goBack },
>   route: {
>     params: { channelId },
>   },
> }) => {
>   const [channel, setChannel] = useState();
>   console.log('channelId is this: ', channelId);
>   useEffect(() => {
>     const init = async () => {
>       if (!channelId) {
>         goBack();
>       }
>       try {
>         const thisChannel = streamChatClient.channel('messaging', channelId);
>         if (!thisChannel.initialized) {
>           await thisChannel.watch();
>         }
>         setChannel(thisChannel);
>       } catch (error) {
>         Bugsnag.notify(error);
>       }
>     };
>     init();
>   }, [channelId]);
>   return (
>     <SafeAreaView>
>       <Channel channel={channel}>
>         <MessageList />
>         <MessageInput />
>       </Channel>
>     </SafeAreaView>
>   );
> };
> ```
> 
> my ChannelList show up fine, this issue is in the navigation to the channel

@khushal87 please see as well

**Comment by khushal87** [comment]
Hey @boblitex, can you check here, how we pass it?

https://github.com/GetStream/stream/pull/4043

I have already raised a PR to fix this and it will live soon. Follow the fixes in the changes and it should work for you. Thanks 
😄

**Comment by boblitex** [comment]
@khushal87 thanks for the quick response, I do get a 404 from that link you just sent. maybe I don't have permission to view?
