### ISSUE TITLE
"Pin to conversation" option doesn't change its state with GIFs

### ISSUE THREAD

**Issue by jay-s-kipl** [GetStream/stream-chat-react-native#1543]
**Describe the bug**
"Pin to conversation" option doesn't change its state with GIFs

**Dev environment info (please complete/provide the following information):**

- Package version - 4.8.0
- react-native - 0.66.3
- Device/Emulator (android/ios) and OS version - Both Android (Android 12) and iOS (15.5)

**To Reproduce**
Steps to reproduce the behaviour:

1. Long press on any GIF shared in a conversation.
2. Select option "Pin to conversation".
3. Long press and notice the pin button is still there. Press it and notice it doesn’t do anything.
5. Exit the chat and re-enter it.
6. Long press and notice an unpin button now appears and performs the expected behaviour.

**Expected behaviour**
If a GIF is already pinned, it should show "Unpin from conversation", instead of "Pin to conversation".

**Comment by khushal87** [comment]
Hey @jay-s-kipl, thanks for pointing this issue to us. On triaging, I found it as a valid issue. We will try to fix this as soon as possible.

**Comment by vanGalilea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/1543?planning-poker) with ZenHub @khushal87 @madsroskar @santhoshvai @vishalnarkhede

**Comment by santhoshvai** [comment]
This happens for reactions too. And also for overlay of Image attachments.

![image](https://user-images.githubusercontent.com/3846977/182320552-bc2d7596-bc1f-437d-b5d2-1ef7977cc1d6.png)
