### ISSUE TITLE
StreamChat messages not escaping `%`

### ISSUE THREAD

**Issue by brysonjonesy** [GetStream/stream-chat-react-native#1556]
**Describe the bug**
Anything typed and sent with a `.` and values on either side of that with a `%` after the `.` will automatically add `25` after the `%` (typing and sending `cool.pool%` will send appear like `cool.pool%25`)
I know this is a url escaping issue.
Where does the actual encoding happen?
Can I turn the feature off entirely?
Any input/advice is appreciated!

**Dev environment:**
- Package version = stream-chat-react-native `4.2.0`
- react-native `0.67.2`
- This bug affects android and ios running the latest os

**Expected behavior**
Chat messages should recognize a url but still escape certain chars

**Additional context**
Tried `skip_enrich_url: true` without success

**Screenshots**
![Screen Shot 2022-07-13 at 2 10 21 PM](https://user-images.githubusercontent.com/52015892/178825564-330e9dde-cdcc-41cf-8afd-59e6cf455d1f.png)

**Comment by khushal87** [comment]
Hey @brysonjonesy, thanks for reporting this issue to us. It looks like a valid issue. We are looking forward to solving the issue soon and have added it to our backlog.

**Comment by vanGalilea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/1556?planning-poker) with ZenHub @khushal87 @madsroskar @santhoshvai @vishalnarkhede

**Comment by vanGalilea** [comment]
suggested solution: remove the uri enconding

**Comment by brysonjonesy** [comment]
We ended up updating some packages that we thought had nothing to do with this library but it fixed the bug 🤷
