### ISSUE TITLE
Image gallery covers up attachment buttons on some Android phones

### ISSUE THREAD

**Issue by jeffjvick** [GetStream/stream-chat-react-native#1572]
**Describe the bug**
Only on Android (it's fine on iOS), when you click on the paperclip attachment button the draggable modal covers up the most of the attachment icons making them hard to see / click on.  This happened after we upgraded to stream 4.10.0 from 3.9.1 however we also upgraded to RN 0.67.4, RN Gesture Handler 1.6.0 -> 2.4.2 and some other 3rd party dependencies.  No code on this page changed.
On some Android devices it's more pronounced than others and it seems to be worse on "newer" devices, so possibly the issue is with devices that have screens surrounding cameras/speakers and thus the issue may be due to safe area calculations.

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native/stream-chat-expo)
4.10.0
- react-native or expo version
0.67.4
- Device/Emulator (android/ios) and OS version
Android only.  I tested on a Pixel 4a

**To Reproduce**
Click on the attachment paperclip icon, the draggable image gallery modal slides up too far, covering the attachment option buttons.

**Expected behavior**
Buttons not covered.

**Additional context**
While it would be nice for this to automatically set the sizing as it did before, if I could be pointed to where I can manually add some spacing to fix this that could work as a temporary solution.

**Screenshots**
![image000001](https://user-images.githubusercontent.com/203289/179822839-e41fa20f-aaa6-403e-aea8-6daf3d30af10.JPG)

**Comment by khushal87** [comment]
Hi @jeffjvick,

It is strange that you are facing this issue in the latest version of stream-chat-react-native. This was fixed long back in this release - https://github.com/GetStream/stream-chat-react-native/releases/tag/v4.4.0

I would ask you to check and confirm if your upgrade was successful and if you followed the appropriate changelogs and guide for the upgrade the version from 3 to 4.

Thanks

**Comment by vanGalilea** [comment]
@jeffjvick thanks for reaching out. I'll be closing this issue for now.
Please don't hesitate to contact us in the future if this issue or any questions arise.
