### ISSUE TITLE
undefined is not an object

### ISSUE THREAD

**Issue by abgaryanharutyun** [GetStream/stream-chat-react-native#1589]
**Describe the bug**
When tying to use imported component getting this error
```
TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[3], "stream-chat-react-native").OverlayProvider')
```

- Package version "stream-chat-react-native": "4.9.0"
- react-native : 0.69.3
- Emulator ios and OS version 15.5

**To Reproduce**

1. Importing component
2. Trying to use 
3. 
**Screenshots**
![simulator_screenshot_5B05ECA8-292A-4F2D-A958-2FE915D38B83](https://user-images.githubusercontent.com/5097588/181618489-8d07207a-a28a-4cd8-b03a-bd09150554a3.png)

**Comment by MoizAhmedd** [comment]
same issue, can't use the package without this

**Comment by abgaryanharutyun** [comment]
It solved for me by updating last version

**Comment by vishalnarkhede** [comment]
@MoizAhmedd are you still facing the issue after upgrading to latest stable version?

**Comment by vanGalilea** [comment]
@MoizAhmedd I'll be closing this issue for now.
Please don't hesitate to contact us in the future if this issue or any questions arise.
