### ISSUE TITLE
Invariant Violation: ViewPropTypes has been removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'. 

### ISSUE THREAD

**Issue by thechaudharysab** [GetStream/stream-chat-react-native#1598]
**Describe the bug**
Getting this error:

`Error: Requiring module "node_modules/stream-chat-react-native/src/index.js", which threw an exception: Invariant Violation: ViewPropTypes has been removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'. `

As soon as I add this code:

```
<Chat client={client}>
          <Channel channel={channel}>
            <MessageList />
            <MessageInput />
          </Channel>
</Chat>
```

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native/stream-chat-expo): `4.12.0`
- react-native or expo version: `0.69.1`
- Device/Emulator (android/ios) and OS version: iOS 15.2 iPhone 13

**To Reproduce**

Add any component from `stream-chat-react-native` and you'll start getting this error.

**Expected behavior**
Should load the message list and show the input field.

**Additional context**
None

**Screenshots**

![simulator_screenshot_6CE3DE69-6F09-4CF0-94C9-D98BEF05F66E](https://user-images.githubusercontent.com/6399152/181823048-37996ea9-eb03-405c-93fe-474a33559565.png)

**Comment by thechaudharysab** [comment]
A fix is needed for this library to work with the latest version of `react-native` a temporary solution is mentioned here: https://github.com/facebook/react-native/issues/33734#issuecomment-1190506381

**Comment by TianrenWang** [comment]
How would you fix this for people using Expo? I installed the version 4.13.0 AND 4.15.0 of `stream-chat-expo`, but neither one of them got rid of the error message?

**Comment by TianrenWang** [comment]
Update: I fixed the problem by updating some of the expo libraries.
