### ISSUE TITLE
Unsure of how to set background for ChannelList

### ISSUE THREAD

**Issue by HakuG** [GetStream/stream-chat-react-native#1604]
Hi team

I'm sure this is a really simple question, but I'm unsure of how to set a background for the ChannelList apart from the default white.

I've been using the slack example code to learn from the react-native framework, but I'm not sure exactly how to do this. Everything comes out white, and I've tried: 

```
<Chat client={chatClient}>
        <ChannelList
          style={tw`flex-1 bg-primary-900`}
          filters={filters}
          Preview={DirectMessagesChannelsPreview}
          setFlatListRef={setRef}
          )}
        />
      </Chat>
      
```
 
<img width="421" alt="image" src="https://user-images.githubusercontent.com/5514073/182233157-1d50bbfd-ad15-4fae-97a3-ee3be45ebe5a.png">

I've also updated the Theme.tx to have

```

channelListMessenger: {
      flatList: {
        backgroundColor: 'black',
      },
```

still nothing

**Comment by vishalnarkhede** [comment]
For this particular case, the theme should be:

```
    channelListMessenger: {
      flatListContent: {
        backgroundColor: 'black',
      }
    },

```

Although this won't exactly apply background color to list items. Those you will need to manually apply by setting following additional theme:

```
    channelPreview: {
      container: {
        backgroundColor: 'black',
      }
    }
```

Ideally we would recommend you to theme our default color pallet itself as mentioned in docs - https://getstream.io/chat/docs/sdk/reactnative/customization/theming/#dark-mode

Also you can take a look at our example app for implementation of dark mode - https://github.com/GetStream/stream-chat-react-native/blob/develop/examples/TypeScriptMessaging/useStreamChatTheme.ts

**Comment by vanGalilea** [comment]
@HakuG thanks for reaching out. I'll be closing this issue for now.
Please don't hesitate to contact us in the future if this issue or any questions arise.
