### ISSUE TITLE
Adroid links not opening

### ISSUE THREAD

**Issue by Marcoo09** [GetStream/stream-chat-react-native#1610]
**Describe the bug**
We are having trouble opening links via chat only on Android devices. We're sending and s3 url which contains a pdf.

**Dev environment info (please complete/provide the following information):**

- 4.7.0
- react-native 0.67.4
- Samsung A52, Android 11

**To Reproduce**

1. Go to the chat
2. Click on a link message 
4. See error 'Don't know how to open URI: ...'

**Expected behavior**
Redirect to navigator with the link as on ios.

**Comment by santhoshvai** [comment]
Hello @Marcoo09, please see this part of the documentation to fix this https://getstream.io/chat/docs/sdk/reactnative/basics/troubleshooting/#external-link-not-opening

**Comment by Marcoo09** [comment]
Really helpful, thanks!
