### ISSUE TITLE
ImageGallery swiping doesn't work properly

### ISSUE THREAD

**Issue by gpahal** [GetStream/stream-chat-react-native#1627]
**Describe the bug**
There are 2 issues we are facing with the image gallery that comes up when we click on a message image attachment

- The order of the images in the gallery is reverse of what it shows in the thumbnails and to the order in which the images were attached
- When the gallery is first opened, swiping right to the next image never works. The left swipe actually goes to the next image. After the initial swipe, swiping starts working as expected. I've attached a screen recording for this issue.

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native/stream-chat-expo): **`stream-chat-expo @ 4.12.1`**

- react-native or expo version: **`expo @ SDK 45`**

- Device/Emulator (android/ios) and OS version: **`Google PIxel 6 - Android 12`**

**To Reproduce**

1. Go to any chat channel
2. Upload 4 photos as attachments to a new message
3. Once the message is sent click on the 2nd or 3rd photo thumbnail
4. Try to swipe to go to the next photo
5. You'll see the order of images is reversed and you're not able to right swipe

**Expected behavior**

The photos are in the same order as the thumbnails and swiping right works to move to the next image

**Screen recording**

https://user-images.githubusercontent.com/7554454/183126683-5cd2e051-6125-46f6-8efc-e5afed3a0f93.mp4

**Comment by vanGalilea** [comment]
I'm going to close this, it is solved with [v5.0.0-beta.1](https://github.com/GetStream/stream-chat-react-native/releases/tag/v5.0.0-beta.1)

**Comment by gpahal** [comment]
Is the swiping issue also resolved in v5?

**Comment by madsroskar** [comment]
@gpahal It should be, yes.
