### ISSUE TITLE
useAppSettings.ts fails on app load.

### ISSUE THREAD

**Issue by izakfilmalter** [GetStream/stream-chat-react-native#1634]
**Describe the bug**
> An error occurred while getting app settings: Error: Both secret and user tokens are not set. Either client.connectUser wasn't called or client.disconnect was called

**Dev environment info (please complete/provide the following information):**

- Package version:
```
"expo": "45.0.6",
"react-native": "0.68.2",
"stream-chat": "6.7.3",
"stream-chat-expo": "4.10.0",
```
- Device/Emulator:

> Pixel 6 - Android 12
> iPhone 12 Pro Max - 15.6

**To Reproduce**
1. Clone https://github.com/izakfilmalter/stream-connect-error
2. `yarn install`
3. Add a token to line 10 in `App.tsx`.
4. Boot app. 
5. See the console for error

One odd thing is that iOS will start to work when you call `connectUser`. Android on the other hand just fails to load the channel list when you render it.

**Expected behavior**
Should be able to render `Chat` component before calling `connectUser`. The HOC should be able to wrap logged out screens.

**Additional context**
I don't get this error when I use `"stream-chat-expo": "3.10.2"`. Something happened on 4.0.

**Comment by izakfilmalter** [comment]
Would be great to get some insight on what is happening here.

**Comment by vanGalilea** [comment]
@izakfilmalter thanks for reaching out! This has been added to our backlog and will be refined next week

**Comment by vanGalilea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/1634?planning-poker) with ZenHub @khushal87 @madsroskar @vishalnarkhede

**Comment by izakfilmalter** [comment]
Is there an eta for this fix?

**Comment by juanjorge** [comment]
this still is happening
<img width="1796" alt="image" src="https://user-images.githubusercontent.com/4811095/193110823-be46c2f8-b3de-4268-8828-1ad6a86fcaf7.png">

```
"stream-chat-react-native": "^5.3.1"
"expo": "^45.0.0"
"react-native": "0.68.2"
"react": "17.0.2",
```

any news about it ?

**Comment by vanGalilea** [comment]
I have changed the prio of this issue to high and start trigaing. 
@izakfilmalter it seems like the repo you've mentioned above ("Clone https://github.com/izakfilmalter/stream-connect-error
"), had been moved/deleted.

**Comment by izakfilmalter** [comment]
@vanGalilea My fault, should be public now.
