### ISSUE TITLE
Changing groupStyles does not seem to change position of avatar in message group

### ISSUE THREAD

**Issue by ndrabins** [GetStream/stream-chat-react-native#1646]
**Describe the bug**
Grouping messages by user always has avatar at the bottom of the message group. 

Even when setting props according to documentation.  

** Environment **
- stream-chat-expo: 4.14.0
- expo - 46
- IOS & android

**To Reproduce**
On <MessageSimple />
enableMessageGroupingByUser={true}
groupStyles={["top"]} (or any opton)

Also have enableMessageGroupingByUser={true} on channel component. 

**Expected behavior**
Message avatar would be at the top of message group

**Additional context**
The "groupStyles" prop does not seem to do anything when changing the option. Not sure if this is because the code is expecting a value but the type needs to be passed as an array like `['top'` or what. Currently I have not been able to get it to work when changing to any groupStyles value ('top'|'single'|'bottom'|'middle')

**Comment by vanGalilea** [comment]
@ndrabins thanks for reaching out, we have added this issue to our backlog and we'll get back to you soon.

**Comment by vanGalilea** [comment]
> @ndrabins Are you trying to set `groupStyles` prop on Channel component? Because we currently don't support any such prop. Please correct me if I am missing something or if you can show me some code, that would be great. Also if you can share with us some design as to what you are trying to achieve exactly, that would be helpful.

@ndrabins can you please answer @vishalnarkhede's questions? Tnx for your cooperation!

**Comment by vanGalilea** [comment]
@ndrabins thanks for reaching out. I'll be closing this issue for now.
Please don't hesitate to contact us in the future if this issue or any questions arise.
