### ISSUE TITLE
Video controls do not work correctly when sharing multiple videos in a single message

### ISSUE THREAD

**Issue by aharwood9** [GetStream/stream-chat-react-native#1662]
**Describe the bug**
When you share a single message with multiple videos, the video controls do not work and seem to be playing both videos at the same time. 

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native/stream-chat-expo) - stream-chat-react-native
- react-native or expo version - react-native
- Device/Emulator (android/ios) and OS version - iOS & Android and 15.5

**To Reproduce**

1. Share two videos in a single message (easiest to repo with two videos of very different lengths)
2. Tap on the VideoThumbnail
3. Press play on the video within footer
4. See controls jump around and both videos are playing (or impacting each other in some way)

**Expected behavior**
Be able to play each video shared in a single message separately

**Additional context**
I was able to repo in the SampleApp and I think the issue is to do with using a single videoRef within `ImageGallery` for all videos. I would imagine you need a videoRef per video.

**Screenshots**

https://user-images.githubusercontent.com/45667737/185113023-3386ce84-f4f1-45b2-9483-874d3578d3cb.mov

**Comment by santhoshvai** [comment]
Hi @aharwood9, thanks for filing this issue. We have investigated this and are working on this, it needs some refactoring.
