### ISSUE TITLE
Add onLongPress Event Handler in ChannelList

### ISSUE THREAD

**Issue by asRizvi888** [GetStream/stream-chat-react-native#1665]
**Being able to launch a modal onLongPress in ChannelList**
So that, it gets easier to manage channel like pinning, deleting etc straight from the channelList

**Probable Approach**
May be a modified onSelect or implement native flatList's `onLongPress` function into `additionalFlatListProps` that will return a callback

**Comment by vanGalilea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/1665?planning-poker) with Zenhub @santhoshvai @madsroskar @khushal87

**Comment by vishalnarkhede** [comment]
@asRizvi888 Here is an alternative solutions you can implement. 

```tsx
import { ChannelList, ChannelPreviewMessenger } from 'stream-chat-react-native';

<ChannelList<StreamChatGenerics>
    filters={filters}
    Preview={(props) => (
        <TouchableOpacity
            onLongPress={() => console.log('LONG PRESSED', props.channel.id)}
            onPress={() => {
                navigation.navigate('ChannelScreen', {
                    channel: props.channel,
                });
            }}
        >
            <ChannelPreviewMessenger {...props} />
        </TouchableOpacity>
    )}
    sort={sort}
/>
```

**Comment by vishalnarkhede** [comment]
I am going to close this for now. The solution recommended above has been tested and seems to be working on our end. Please feel free to get back to us if you face any issues.
