### ISSUE TITLE
Reaction type has a missing type for id

### ISSUE THREAD

**Issue by aharwood9** [GetStream/stream-chat-react-native#1673]
**Describe the bug**

When overriding the `OverlayReactionsAvatar` component within `OverlayProvider`, the reaction type doesn't have the correct type as it is missing `id` of the user who left the reaction. `id` of the user who left the reaction is actually available so just the incorrect typing. 

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native/stream-chat-expo) - stream-chat-react-native
- react-native or expo version - react-native 
- Device/Emulator (android/ios) and OS version - type issue rather than a device issue.

**To Reproduce**

1. Try to customise the `OverlayReactionsAvatar` within `OverlayProvider`
2. See `reaction` prop doesn't have a type for `id`
3. console.log `reaction.id` and see you get the correct `id`

**Expected behavior**

Expect to have a type definition for `id` within reaction

**Additional context**

You can see id being supplied to reactions here in `MessageOverlay`.
```
reactions={
                                message.latest_reactions.map((reaction) => ({
                                  alignment:
                                    clientId && clientId === reaction.user?.id ? 'right' : 'left',
                                  id: reaction?.user?.id || '',
                                  image: reaction?.user?.image,
                                  name: reaction?.user?.name || reaction.user_id || '',
                                  type: reaction.type,
                                })) as Reaction[]
                              }

```

**Screenshots**

**Comment by madsroskar** [comment]
Thank you for reporting this! It does indeed look like the type should be updated to include the ID.
