### ISSUE TITLE
Creating new group chat doesn't have all the added members. 

### ISSUE THREAD

**Issue by Agupta00** [GetStream/stream-chat-react-native#1682]
**Describe the bug**
See video please / Title.  

**Dev environment info (please complete/provide the following information):**
Cloned the latest version as of this repo aug 25th 2022. 

**To Reproduce**
1. Press the new chat icon. 
2. Choose someone that you have not had a 1v1 conversation first and then add other members
3. Send a message to the group
4. You will see that not all added members are there. 

Also (another small issue) you can see at the end of the video that the selected user's state isn't cleared after the group chat is made.  

**Additional context**
It seems like the channel component is not re-rendering. Because of this, I think it has the old channel from its channel prop and thus creates a group chat from the old channel, maybe?

https://user-images.githubusercontent.com/12666226/186730440-de35c54f-dba1-497f-b849-f4d057dc6201.mp4

**Comment by Agupta00** [comment]
bump @vishalnarkhede @virdesai if you could take a look please

**Comment by vanGalilea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/1682?planning-poker) with Zenhub @khushal87 @madsroskar @santhoshvai @vishalnarkhede
