### ISSUE TITLE
v5: ChannelList that is expected to have 0 results will eventually fail in airplane mode

### ISSUE THREAD

**Issue by andreibarabas** [GetStream/stream-chat-react-native#1695]
Found one issue in the stable version, namely: if you have a filter with 0 results saved locally, then go in airplane mode and open the app, after the MAX_QUERY_CHANNELS_LIMIT is hit, the ui will error (although we did load from local database 0 channels). see recording

https://user-images.githubusercontent.com/2101405/187367700-df296105-a4a2-490e-9f54-ad9fb54c06ba.mp4

The issue comes from this line, as the `channels.length` is obviously 0

https://github.com/GetStream/stream-chat-react-native/blob/53a9c41981e0b602c2d817696490c66a8045b9f2/package/src/components/ChannelList/ChannelListMessenger.tsx#L125

_Originally posted by @andreibarabas in https://github.com/GetStream/stream-chat-react-native/discussions/1611#discussioncomment-3506104_

**Comment by vishalnarkhede** [comment]
Looking into it

**Comment by vishalnarkhede** [comment]
@andreibarabas we will soon publish a release for this fix. Beta release should be available in few mins after the completion of https://github.com/GetStream/stream-chat-react-native/runs/8256349337?check_suite_focus=true

**Comment by andreibarabas** [comment]
sure thing. thanks for checking in @vishalnarkhede . Today I'm focused on getting a new feature out so won't be able to tackle this, but added it to my todo list and can expect feedback early next week

**Comment by andreibarabas** [comment]
I got distracted by other urgent tasks, and forgot to reply to you guys. I can confirm the bug has been indeed solved
