### ISSUE TITLE
SQL execution error: no such table channelQueries

### ISSUE THREAD

**Issue by 1987cr** [GetStream/stream-chat-react-native#1713]
**Describe the bug**
SQL error is shown the first time rendering the `ChannelList` component after a clean install

**Dev environment info (please complete/provide the following information):**

- stream-chat-react-native 5.2.0
- react-native 0.69.4
- react-native-quick-sqlite 4.0.5
- Any device

**Screenshots**
![Screenshot 2022-09-07 at 11 57 03](https://user-images.githubusercontent.com/4684912/188850035-0ab946b1-31bf-42a4-a26d-d79df7956553.png)

**Comment by 1987cr** [comment]
@vishalnarkhede thanks for the quick follow up, I'll wait wor the release since it doesn't seem to be crashing or breaking anything atm, cheers!

**Comment by vanGalilea** [comment]
@1987cr  I'll be closing this issue for now, due to inactivity.
Please don't hesitate to contact us in the future if this issue or any questions arise.
