### ISSUE TITLE
Offline Support Docs Inconsistency 

### ISSUE THREAD

**Issue by aharwood9** [GetStream/stream-chat-react-native#1716]
**Describe the bug**
Hi 👋 I was reading the new offline docs and noticed a recent inconsistency with caching of Images. 

In the section about what is not supported is caching of Images/Profile Images but there is now a new section for how to cache images. You may be updating this shortly but just in case it is a mistake, I thought I would raise it. 

Please close this if not an actual issue.

**Comment by vishalnarkhede** [comment]
@aharwood9 you are correct. Our release is on the way for image caching. Beta release has already been published - `5.3.0-beta.2`
