### ISSUE TITLE
ChannelList crash caused by SQLite

### ISSUE THREAD

**Issue by 1987cr** [GetStream/stream-chat-react-native#1724]
**Describe the bug**
Is possible to get ChannelList to an unrecoverable state when offline mode is enabled

**Dev environment info (please complete/provide the following information):**

- stream-chat-react-native 5.3.0
- react-native 0.70.0
- react-native-quick-sqlite 4.0.7

**To Reproduce**
Non deterministic because we only have had it 2 or 3 times, but the steps are more or less the following:

1. User 1 triggers action that creates the channel on the backend
3. It appears on ChannelList for both users
3. User 2 triggers action that updates said channel on the backend
4. User 2 ChannelList throw errors attached

**Additional context**
- Recently we updated RN to 0.70 and had to update react-native-quick-sqlite to latest version to get RN 0.70 support
- Removing offline support seems to fix the issue for the moment

**Screenshots**

<img width="351" alt="Screenshot 2022-09-15 at 12 13 28" src="https://user-images.githubusercontent.com/4684912/190385518-72ab9bc7-ed21-4718-830e-00abd0447520.png">

<img width="351" alt="Screenshot 2022-09-15 at 12 13 36" src="https://user-images.githubusercontent.com/4684912/190385523-c64a8746-b248-4f10-8a87-218a442c5ab3.png">

<img src="https://user-images.githubusercontent.com/4684912/190382454-affccd37-4d89-4e78-b813-8b8a537b636f.png" width="400" />

<img src="https://user-images.githubusercontent.com/4684912/190382462-0a59b582-c317-4147-b326-b8e5199b4e66.png" width="400" />

<img src="https://user-images.githubusercontent.com/4684912/190382466-1199a4f4-71a6-47fd-862c-9da9a666b4e2.png" width="400" />

<img src="https://user-images.githubusercontent.com/4684912/190382469-18aea103-5388-4d6b-9090-e5901e65acb3.png" width="400" />

**Comment by vishalnarkhede** [comment]
@andreibarabas we are yet to test it on RN 0.70, but wondering if you faced this issue so far?

**Comment by andreibarabas** [comment]
@vishalnarkhede , no, we have not yet experienced this issue. we are on RN 0.70.1 with Turbo modules enabled (not fabric for the moment). will keep an eye out for such crashes and will circle back to you guys

**Comment by madsroskar** [comment]
Hi, @1987cr 

I'm having some trouble reproducing this issue. I was wondering whether you could give some information about what kind of change user 2 triggers for the channel before the error occurs?

**Comment by 1987cr** [comment]
Hi @madsroskar, sorry I haven't been able to reproduce this and have change quite some code since, app and backend wise, feel free to close this one, if I see error again I'll update issue with more details.

**Comment by vanGalilea** [comment]
@1987cr thanks for updating us. I'll be closing this issue for now.
Please don't hesitate to contact us in the future if this issue or any questions arise.

**Comment by billnbell** [comment]
It is still happening on v4 for me.

**Comment by vishalnarkhede** [comment]
So I think whats happening here is that one of the foreign key constrains fails somehow, and causes the database to be locked state forever (until you reopen the app). Investigating more ...
