### ISSUE TITLE
Issue while uploading images with a 64mp camera , specific to samsung devices

### ISSUE THREAD

**Issue by singh-026** [GetStream/stream-chat-react-native#1726]
i have the following versions installed
"react-native": "0.66.4",
"stream-chat": "6.7.3",
"stream-chat-react-native": "4.12.2",

**Comment by santhoshvai** [comment]
hey @singh-026, what was the issue? Can you attach logs and detail, please?

**Comment by vanGalilea** [comment]
Hey @singh-026 can you please provide the information that @santhoshvai requested and the device's specific type?

**Comment by singh-026** [comment]
it was a problem with a specific device only , didn't get much of info on that , so closing this as of now
