### ISSUE TITLE
Add documentation stating that we do not support Web for our SDK

### ISSUE THREAD

**Issue by khushal87** [GetStream/stream-chat-react-native#1727]
There are repeated questions which pop up in support around web support. Therefore, it would be great if we can add it to our documentation that we currently do not support it and that we plan to do so in the future.

**Comment by vanGalilea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/1727?planning-poker) with Zenhub @khushal87 @madsroskar @santhoshvai @vishalnarkhede

**Comment by vanGalilea** [comment]
Add sentence and link for the alternative solution to the Stream React SDK in the compatibilities section
