### ISSUE TITLE
Image Picker Not Clickable and Not Scrollable (Freezing) on Android (Works on iOS only)

### ISSUE THREAD

**Issue by GarryLaly** [GetStream/stream-chat-react-native#1731]
**Describe the bug**
When click attachment icon, will show the image picker on the bottom.
But it's not working on Android, can't scroll and tap anything (Freeze bottom section image picker).
But it's working well on iOS.

**Dev environment info (please complete/provide the following information):**

- Package version stream-chat-react-native 5.3.0
- react-native 0.67.1
- Device(Android Samsung A51) and OS version android 12 (One UI version 4.1)

**To Reproduce**

1. Go to Channel page for chat messages
2. Click on attachment icon, then show image picker on the bottom section
3. Scroll down is not working, and tap anything is not working also (It's like freeze section)
4. But when try file picker and camera picker it's working well on Android and iOS

**Expected behavior**
On android can scroll and tap the image picker on the bottom section

**Screenshots**
![photo_2022-09-20 16 15 42](https://user-images.githubusercontent.com/5617788/191220036-132b50fb-e871-495e-92ea-929e86a13047.jpeg)

**Comment by GarryLaly** [comment]
Anyone can help me? thanks

**Comment by vanGalilea** [comment]
Hey @GarryLaly thanks for reaching out, please have a look at our troubleshooting guide in the["Touchables not working"](https://getstream.io/chat/docs/sdk/reactnative/basics/troubleshooting/#touchables-not-working) section.

Please let us know if it works for you

**Comment by GarryLaly** [comment]
@vanGalilea it works. Thanks
