### ISSUE TITLE
Clear button not working when unsupported file types are uploaded 

### ISSUE THREAD

**Issue by singh-026** [GetStream/stream-chat-react-native#1732]
in stream chat admin

add some files to  File Configurations > Blocked file extensions
and then try to send those extensions in the message section

will look something like this :
<img width="369" alt="Screenshot 2022-09-21 at 12 46 40 PM" src="https://user-images.githubusercontent.com/89844188/191440123-0e9e0ea7-1837-42cc-bc83-bc0d670af274.png">

the clear button here which aims to clear the document doesn't works somehow

 versions : 
 "react-native": "0.66.4",
  "stream-chat": "6.7.3",
  "stream-chat-react-native": "4.12.2",

**Comment by khushal87** [comment]
Hey @singh-026, Thanks for pointing this issue to us. I have raised a PR to fix this and you will see it fixed probably by the next release. 😄
