### ISSUE TITLE
Updating channel images multiple times doesn't work

### ISSUE THREAD

**Issue by madsroskar** [GetStream/stream-chat-react-native#1759]
**Describe the bug**

If you update a channel image, the first image you set will be shown in the app, but the second image that's set won't. I'm suspecting this to be a memoization issue.

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native/stream-chat-expo): 5.4.1
- react-native or expo version: 0.70.1
- Device/Emulator (android/ios) and OS version: iPhone 13 - iOS 15

**To Reproduce**

1. open the channel list
2. Run a script to set an image for a channel
3. open a chat, and navigate back to the channel list - image should be updated for the channel
4. run a script to unset the image, then another script to set a new image for the channel
5. open a chat, and navigate back to the channel list - image isn't updated

**Expected behavior**
The image should be updated in the app each time

**Comment by vanGalilea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/1759?planning-poker) with Zenhub @khushal87 @madsroskar @santhoshvai @vishalnarkhede

**Comment by vanGalilea** [comment]
The issue became stale and . I'll be closing this issue for now.
