### ISSUE TITLE
The gallery is blank on Android

### ISSUE THREAD

**Issue by madsroskar** [GetStream/stream-chat-react-native#1761]
**Describe the bug**
When opening the gallery on an Android device, the gallery is rendered blank, which usually is an issue with permissions, but setting up the correct permissions (following our additional steps in the documentation) doesn't seem to fix the issue in this case.

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native/stream-chat-expo): 5.4.0
- react-native or expo version: 0.70.1
- Device/Emulator (android/ios) and OS version: Samsung Galaxy S20, Android 12

**To Reproduce**

1. Go to a channel
2. Open the gallery via the button next to the message input
3. The gallery will be blank

**Expected behavior**
It should show available images, based on the permissions given to the app

**Comment by santhoshvai** [comment]
This must be due to the outdated expo media that we use.

Its best to stay updated to align with new versions of android. 

Currently used version: 12.0.2
Latest: 14.2.0
