### ISSUE TITLE
Invalid Hook Call on Use of Stream-Chat-Expo Components

### ISSUE THREAD

**Issue by JSimai** [GetStream/stream-chat-react-native#1765]
**The Bug:**
After importing and using a stream-chat-expo component, such as OverlayProvider, and then running my app on an IOS simulator, there is in an error:

Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

After some research, it may be a mismatching version of React issue, as after running 'npm ls react', there are conflicting versions of react within stream-chat-expo (all are react@17.0.1, except at the bottom there is a react@17.0.2). This is the result:

![Screen Shot 2022-10-20 at 12 17 01 pm](https://user-images.githubusercontent.com/67139031/196833516-02e5cc4b-f020-4d3e-9ae7-670456410b42.png)

I'm not sure if this is the issue but it's my best guess and I'm unsure how to resolve it.

**Dev environment:**

- "stream-chat-expo": "^5.4.1"
- "react-native": "0.64.3"
- "expo": "~44.0.0"
- iOS Emulator - iPhone 13 Pro Max - iOS 15.0

**To Reproduce**
I'm unsure how to reproduce this externally to be honest.

**Expected behavior**
I expected the OverlayProvider to not turn up an error on load.

**Additional Context**
I'm fairly certain it isn't an issue with other code as I tested this change in complete isolation after pushing a working app.

**Comment by choudlet** [comment]
+1 

I am seeing this same issue in an app where the react version my app is using is 18.0.0. When i run npm ls react the react-art 17.0.2 react version 17.0.2 is the only one which is not deduped and is what I believe is breaking the application.

**Comment by vanGalilea** [comment]
@JSimai thanks for reaching out. This issue has a direct correlation with incompatible dependency versions. 

Can you please consider updating react-native to 0.69<= and expo 46<= respectively?

**Comment by JSimai** [comment]
Apologies for the delay @vanGalilea. I've updated both react-native and expo, uninstalled and then reinstalled stream-chat-expo along side its dependencies. However the same error is being retruned when trying to render OverlayProvider.

**Comment by vanGalilea** [comment]
@JSimai thanks for your response.

To pinpoint this issue as fast as possible, we would like to ask you to share a minimalistic repo where the problem is reproduced.
The fastest way to achieve this is with the following command to create a new RN project with Stream chat in it:

`npx react-native init MyApp --template stream-chat-react-native-template`

Please then share a Github repo with us, where we can explore the issue ourselves.

**Comment by vishalnarkhede** [comment]
Testing the shared repository with `yarn install; expo start`. Seems to be working fine, didn't receive any error yet.

Next I will try with `npm install`

**Comment by vishalnarkhede** [comment]
Ok so managed to reproduce the issue with `npm install; expo start`
![simulator_screenshot_604DC868-C1C5-4DDC-A9D0-579EF7D983BA](https://user-images.githubusercontent.com/11586388/201703185-1125f6ae-3b39-44cf-a415-f92e7efc9d63.png)

**Comment by vishalnarkhede** [comment]
`react-art` seems to be an unnecessary dependency, which was introduced in initial versions of stream-chat-react-native-core. It needs to be removed. We will do the change and make a release soon :) 

But I think if you simply use `yarn` instead of `npm`, it should be resolved @JSimai .

**Comment by JSimai** [comment]
Thanks for the speedy replies and help!
