### ISSUE TITLE
initial WS connection could not be established

### ISSUE THREAD

**Issue by billnbell** [GetStream/stream-chat-react-native#1777]
I am getting `initial WS connection could not be established`

No idea why. I am doing a connect.

```
connect {"code":"","StatusCode":"","message":"initial WS connection could not be established","isWSFailure":true}
```

**Comment by madsroskar** [comment]
Usually, this error message implies that the internet connection on the device in question isn't able to connect to our backend. However, as is this is a bit tricky to reproduce on our end without more information.

Could you give us some information about the following:
- Which version of the SDK you're using
- Which versions of react-native/expo you're using
- What device are you trying on, and what version of the OS is the device using

Even better would be if you're able to provide a minimal reproducible app we could use to try to reproduce this

**Comment by billnbell** [comment]
It is latest versions of React Native.

```
    "stream-chat": "8.1.0",
    "stream-chat-react-native": "^5.4.2",
    "stream-chat-react-native-core": "^5.4.2",
    "react-native": "0.70.5",
    "react": "18.1.0",
```

No expo.
IOS device - simulator.

**Comment by vishalnarkhede** [comment]
@billnbell I would recommend you to get in touch with support@getstream.io.

This sounds more of an integration issue, rather than bug within the SDK. If you can contact support along with some code around your stream chat integration, that will be helpful.

**Comment by billnbell** [comment]
If we do many connects/disconnects would there be a throttle that returns "initial WS connection could not be established" ?

**Comment by hotaryuzaki** [comment]
> If we do many connects/disconnects would there be a throttle that returns "initial WS connection could not be established" ?

same  issue, i think it's a bug

this is my code
```
          // GET THE TOKEN CHAT AND CONNECTING
          // LATER THIS connectUser WILL CALL AUTOMATICALLY BY GETSTREAM
          const response = await getStream.connectUser(user, async () => {
            const tokenChat = await this._getData("@Brambang:tokenChat");

            // JIKA MASIH ADA TOKEN CHAT
            if (tokenChat) {
              console.log('ReactContextProvider : _getStream connectUser tokenChat', tokenChat);
              return tokenChat; **<= THIS RETURN WILL RETRY CONNECTUSER IN EVERY SECOND WITHOUT RETURN ERROR IN CATCH FUNCTION, THEN WHEN THROTTLE RETURN initial WS connection could not be established"**
            }

            // REFRESH TOKEN CHAT
            else {
              console.log('ReactContextProvider : _getStream connectUser request new tokenChat');
              const token = await this._getData("@Brambang:token");
              const response = await axios.get(
                `${MyConfig.apiUrl}/v2/chat/getToken`,
                { headers: { Authorization: token }}
              );

              console.log('ReactContextProvider : _getStream connectUser NEW TOKEN', response.data.token);
              this._storeData('tokenChat', response.data.token) // SAVE NEW CHAT TOKEN
              return response.data.token;
            }
          });
```

**Comment by hotaryuzaki** [comment]
> > If we do many connects/disconnects would there be a throttle that returns "initial WS connection could not be established" ?
> 
> same issue, i think it's a bug
> 
> this is my code
> 
> ```
>           // GET THE TOKEN CHAT AND CONNECTING
>           // LATER THIS connectUser WILL CALL AUTOMATICALLY BY GETSTREAM
>           const response = await getStream.connectUser(user, async () => {
>             const tokenChat = await this._getData("@Brambang:tokenChat");
> 
>             // JIKA MASIH ADA TOKEN CHAT
>             if (tokenChat) {
>               console.log('ReactContextProvider : _getStream connectUser tokenChat', tokenChat);
>               return tokenChat; **<= I DON'T KNOW WHY THIS WILL RETRY CONNECTUSER IN EVERY SECOND WITHOUT RETURN ERROR IN CATCH FUNCTION, THEN WHEN THROTTLE CATCH FUNCTION RETURN initial WS connection could not be established"**
>             }
> 
>             // REFRESH TOKEN CHAT
>             else {
>               console.log('ReactContextProvider : _getStream connectUser request new tokenChat');
>               const token = await this._getData("@Brambang:token");
>               const response = await axios.get(
>                 `${MyConfig.apiUrl}/v2/chat/getToken`,
>                 { headers: { Authorization: token }}
>               );
> 
>               console.log('ReactContextProvider : _getStream connectUser NEW TOKEN', response.data.token);
>               this._storeData('tokenChat', response.data.token) // SAVE NEW CHAT TOKEN
>               return response.data.token;
>             }
>           });
> ```

tokenChat is from last connection, i found that connectUser always need new token from our server.

**Comment by billnbell** [comment]
Why would it need a new token ? Interesting - documentation should say this.

**Comment by hotaryuzaki** [comment]
> Why would it need a new token ? Interesting - documentation should say this.

My TokenChat is an AsyncStorage data that we save in our app, so if the app is close the app will try to connect with same tokenChat.
I don't know why it's like not return anything but keep reconnecting in every second.
Then get an error initial WS connection.

But the weird thing is if i used connectUser with tokenChat directly (not a function), the connection succeeded.
'''connectUser(user, tokenChat)'''
But this won't get refresh token if the token expired.

And 1 thing I learn today, if we used connectUser with function it will trigger automatically if there is a problem with a connection. It behaves like event listener.

**Comment by billnbell** [comment]
Can you give an example of the function ? Is it an event listener?

**Comment by billnbell** [comment]
What do you mean - this does not work?
```
const response = await getStream.connectUser(user, token);
```

**Comment by billnbell** [comment]
I would just move your code in the () => {} to above the function call.

```
const getToken = async () => {
           const tokenChat = await this._getData("@Brambang:tokenChat");

            // JIKA MASIH ADA TOKEN CHAT
            if (tokenChat) {
              console.log('ReactContextProvider : _getStream connectUser tokenChat', tokenChat);
              return tokenChat; **<= I DON'T KNOW WHY THIS WILL RETRY CONNECTUSER IN EVERY SECOND WITHOUT RETURN ERROR IN CATCH FUNCTION, THEN WHEN THROTTLE CATCH FUNCTION RETURN initial WS connection could not be established"**
            }

            // REFRESH TOKEN CHAT
            else {
              console.log('ReactContextProvider : _getStream connectUser request new tokenChat');
              const token = await this._getData("@Brambang:token");
              const response = await axios.get(
                `${MyConfig.apiUrl}/v2/chat/getToken`,
                { headers: { Authorization: token }}
              );

              console.log('ReactContextProvider : _getStream connectUser NEW TOKEN', response.data.token);
              this._storeData('tokenChat', response.data.token) // SAVE NEW CHAT TOKEN
              return response.data.token;
            }
}

const token = await getToken();
const response = await getStream.connectUser(user, token);

**Comment by hotaryuzaki** [comment]
> Can you give an example of the function ? Is it an event listener?

If you use the second parameter in connectUser as a function call like this:

```
connectUser (user, () => {
   ... Your logic here... 
   return token;
}
```

The function will trigger automatically every time getStream has an issue with the connection.
So it's like an event listener for the reinit connection.
With this, you will get a new token every time the function is triggered.

> Are you saying:
> 
> ```
> const response = await getStream.connectUser(user, async () => {
>   return newToken; 
> };
> 
> It has to return a new token each time?
> ```

No, what I'm saying is if you use the second parameter in connectUser with a token string (not a function), just like your coding above.
``` 
connectUser (user, token);
```
Then, when GetStream tries to reinitiate the connection automatically, it will use the same last token because the function getToken won't get called.

**Comment by hotaryuzaki** [comment]
Now i I have the details of my issue, i found that connectUser is inconsistent (there is a bug).

1. when we called connectUser with an expired token and a function as the second parameter, like this:

```
connectUser (user, () => {
   const token = await this._getData("@Brambang:token"); // GET DATA FROM ASYNCSTORAGE ~ THE TOKEN EXPIRED
   return token;
}
```

There is no response or error catch.
then getStream SDK will reinitiate connectUser every second.
It will eventually return the error catch: "initial WS connection could not be established" after a few attempts.
However, it is still reinitiating the connectUser.


2. but if i called connectUser with an expired token and a token string as the second parameter, like this:

```
const token = await this._getData("@Brambang:token"); // GET DATA FROM ASYNCSTORAGE ~ THE TOKEN EXPIRED
connectUser (user, token);
```

it will get an error catch.

```
{"code":40,"StatusCode":401,"message":"WS failed with code 40 and reason - Connect failed with error: \"Token expired\"","isWSFailure":false}
```

**It should receive the same error message.**
can anyone check this?
@madsroskar 
@vishalnarkhede
