### ISSUE TITLE
Override takePhoto() native handler in stream-chat-expo

### ISSUE THREAD

**Issue by edwinckc** [GetStream/stream-chat-react-native#1784]
**Describe the bug**
[The docs](https://getstream.io/chat/docs/sdk/reactnative/customization/native_handlers/#takephoto) describe a `takePhoto()` native handler which can be overrode with `registerNativeHandlers()`, but it doesn't seem to be available when using `stream-chat-expo`.

**Dev environment info (please complete/provide the following information):**

- stream-chat-expo 5.4.2
- RN 0.69.6, Expo 46
- Device/Emulator: N/A, related to docs/implementation

**To Reproduce**

1. Call `registerNativeHandlers()`.
2. Look at valid keys (Typescript) that can be passed to the method.
3. Only `BlurView` and `takePhoto` are missing from [the list here](https://getstream.io/chat/docs/sdk/reactnative/customization/native_handlers/#takephoto).

**Expected behavior**
I should be able to override `takePhoto()`.

**Additional context**
Since video recording is not available through `stream-chat-expo`, I expected to be able to override the `takePhoto` handler and use my own camera component. Alternatively I thought I could just replace the camera icon/component in the attachments picker, but I don't see anything related to a camera component.

The docs do show [how an action sheet can be used](https://getstream.io/chat/docs/sdk/reactnative/guides/message-input-customization/#replacing-attachmentpicker-with-native-image-picker) to customize the attachments picker, but it doesn't look as good as the included picker and icons.

**Screenshots**
I would like to override the "CameraSelectorIcon" here:
<img width="639" alt="image" src="https://user-images.githubusercontent.com/2934985/200252508-cc3fd9ab-c44c-4691-9a25-0fa763ea701e.png">

Thank you for your help!

**Comment by vishalnarkhede** [comment]
@edwinckc as far as I can see, `takePhoto` is specified in our typescript for native handlers - https://github.com/GetStream/stream-chat-react-native/blob/develop/package/src/native.ts#L221

And `BlurView` native handler has been dropped since v4 of sdk. But thanks for pointing it out, the docs need to be fixed accordingly.

**Comment by vishalnarkhede** [comment]
As far as I can see, this is not an issue. But if you can share a repository where you can reproduce the issue and share it with us, we would be happy to look into it.
