### ISSUE TITLE
Issue with SQLLite on 5.4.2

### ISSUE THREAD

**Issue by billnbell** [GetStream/stream-chat-react-native#1788]
On    
```
"stream-chat-react-native": "^5.4.2",
```

We are having error show up:

```
Error on resetting Sqlite db on GetStream disconnect Cannot read property 'user_version' of undefined
```

As a work around we turned off enableOfflineSupport. What can we do to not get this crash?

**Comment by vanGalilea** [comment]
Hey, @billnbell thanks for reaching out. Which `react-native-quick-sqlite` are you using?
Make sure you're using version `4.X.X`over v5 of `react-native-quick-sqlite`.  

Our SDK is currently not compatible with `react-native-quick-sqlite` lib. new APIs.

**Comment by billnbell** [comment]
Yes we are using v4.

And this is crashing the app.

**Comment by vishalnarkhede** [comment]
Closing this since its a duplicate of #1724 , more discussions to be followed on that other issue.
