### ISSUE TITLE
The input field doesn't clear if you send a message while typing

### ISSUE THREAD

**Issue by madsroskar** [GetStream/stream-chat-react-native#1797]
**Describe the bug**
If you send a message while still typing in the message field, a message with the current content is sent, but the input field does not clear out as expected. 

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native/stream-chat-expo): 5.4.2
- react-native or expo version: 0.70.1
- Device/Emulator (android/ios) and OS version: iphone 13, iOS 15.0

**To Reproduce**

1. Open any chat
2. Type a message
3. **while still typing**, hit send and continue to type
4. A message should have been sent, but you're continuing typing with the same content in the message input as before you hit send

**Expected behavior**
The message input should be cleared when you send a message

**Comment by vanGalilea** [comment]
Validated ✅

**Comment by santhoshvai** [comment]
During triaging, I can conclude that this is an unfixable one. The text remains on native when we keep typing and comes to JS even after sending. 

Hence closing this.
