### ISSUE TITLE
Offline Support Does not work with "stream-chat-expo"

### ISSUE THREAD

**Issue by Mattensor** [GetStream/stream-chat-react-native#1802]
**Describe the bug**

Hey there I've been following the react native tutorial for an expo application. When I try to setup offline support I get the following error: `please install react-native-quick-sqlite` but I have already installed the dependancy. Can I expect offline support to work for expo apps? I assume I may be missing an obvious step.

I have tried both versions `4.08` & `5.03` of react-native-quick-sqlite. 

<img width="323" alt="image" src="https://user-images.githubusercontent.com/10224902/201496229-db218992-b473-4ead-99e8-cc99d91601ab.png">

**Dev environment info (please complete/provide the following information):**

- Package version "stream-chat-expo": "^5.4.2"
- react-native or "expo": "^46.0.2"
- Device/Emulator (android/ios) and OS version: iPhone 14 Pro Max - iOS 16.0

**To Reproduce**

1. Install react-native-quick-sqlite
2. enable offline support 
```
<Chat client={chatClient} enableOfflineSupport={true}>
 ...
</Chat>
```

**Comment by vishalnarkhede** [comment]
@Mattensor we currently don't support offline support for Expo.

**Comment by vishalnarkhede** [comment]
I would suggest you to keep an eye on releases. I can't give exact timeline for this yet though.

I am going to close this issue for now.

**Comment by Mattensor** [comment]
Thanks @vishalnarkhede I'll keep an eye on future release notes
