### ISSUE TITLE
ChannelList crashes app on render

### ISSUE THREAD

**Issue by ajlars** [GetStream/stream-chat-react-native#1811]
Hi!

I have discovered an issue where for some users, but not all, rendering `ChannelList` crashes the application.

## The Issue

The error is `null is not an object (evaluating 'channels.map')`, at `useUserPresence.ts (24:37)`.
   <picture>
     <image width=500 src="https://user-images.githubusercontent.com/11019029/202027608-e1d050f6-6fbb-41ff-863f-016f3216e372.PNG" />
   </picture>

This is how I render ChannelList.
- ```typescript
   //...
     const memoizedFilters = useMemo(
       () => ({
         members: { $in: [userStore?.id] },
         type: {
           $eq: 'messaging',
         },
       }),
       [userStore?.id]
     )
   //...
     <ChannelList filters={memoizedFilters} onSelect={setChannel} />
   //...
   ```
- `memoizedFilters` ends up being something like this, the single ID being the only difference between users. 
   ```
      { "members": {
                                "$in": [ "d545a055-36f7-4178-be83-10c7550610e8" ] },
                              "type": {
                                "$eq": "messaging" } }
   ```
- `setChannel` is a simple navigation function


### Potential Cause

Digging through the users that work and don't, the dashboard and logs for those users, etc., I can't identify a pattern that might explain the race condition for "channels" being defined or not. Looking at the two hooks involved though, I did spot what I think may be a logic issue.

`usePaginatedChannels.ts` defines the default state of `channels` as `null`
   ```typescript
   const [channels, setChannels] = useState<Channel<StreamChatGenerics>[] | null>(null);
   ```

`useUserPresence.ts` assumes that `channels` will never be `null`
   ```typescript
   const handleEvent = (event: Event<StreamChatGenerics>) => {
      setChannels((channels) => {
        const newChannels = channels.map((channel) => {
          if (!event.user?.id || !channel.state.members[event.user.id]) {
            return channel;
          }
          channel.state.members[event.user.id].user = event.user;
          return channel;
        });
   
        return [...newChannels];
      });
   };
   ```

## Possible Fix

I was able to solve the crashing by fixing that logic. Your use cases might necessitate a different resolution, but it works by either:
1. Defaulting the state of `channels` to an empty array:
     - `usePaginatedChannels.ts` 
     ```typescript
     const [channels, setChannels] = useState<Channel<StreamChatGenerics>[] | null>([]);
     ```
2. Resolving a null value for `channels` in the `handleEvent` function
     - `useUserPresence.ts`
     ```typescript
     const handleEvent = (event: Event<StreamChatGenerics>) => {
       setChannels((channels) => {
         const newChannels = channels?.map((channel) => { // only call map if channels is not null
           if (!event.user?.id || !channel.state.members[event.user.id]) {
             return channel;
           }
           channel.state.members[event.user.id].user = event.user;
           return channel;
         }) ?? []; // and default to an empty array if it is
     
         return [...newChannels];
       });
     };
     ```

With either of those changes in place, `ChannelList` renders successfully as expected. I'd appreciate your feedback on the problem. Thanks!

**Comment by madsroskar** [comment]
Thank you for reporting this, @ajlars - the suggestions seem reasonable to me, though I can't immediately reproduce the error.

I'll try to find a way to reproduce it, but if you happen to stumble across anything that might be related, any additional info you may find would be appreciated :)

**Comment by vishalnarkhede** [comment]
@ajlars there are two cases when you would receive `user.presence.changed` or `user.updated` event

1. When you call queryChannels or channel.watch, in this case you will receive `user.presence.changed` events related to members of the channels requested. But since `channels` is null, so this shouldn't be the case. Basically you are receiving the event before calling `queryChannels` within `usePaginatedChannels` hook.
2. If you are explicitely calling `queryUsers` within your application, then also you will receive `user.presence.changed` and in this case you will receive events even before calling `queryChannels`. **Is this the case? Are you calling queryUsers within your application somewhere?**

**Comment by vishalnarkhede** [comment]
I have managed to reproduce this issue using 2nd approach in my previous comment.

**Comment by ajlars** [comment]
@vishalnarkhede Yes! We query the users to make sure that their displayed name and avatar are up to date before we render the channel.

**Comment by vishalnarkhede** [comment]
The attached PR should fix the issue. We will make a release soon :)
