### ISSUE TITLE
client:post - Error - url: https://chat.stream-io-api.com/sync

### ISSUE THREAD

**Issue by 1987cr** [GetStream/stream-chat-react-native#1813]
**Describe the bug**
We're getting lots of these errors when just opening the application and connecting to stream:

```
"tags:api,api_response,client;url:https://chat.stream-io-api.com/sync;error:Error: Request failed with status code 400;"
```

Doesn't seems to be breaking the app, as far as I know is more like a warning, but is creating lot of noise on monitoring platform. Any way to silence this warning? Could it have a side effect?

**Dev environment info (please complete/provide the following information):**

- stream-chat-react-native: 5.4.3 (Offline mode on)
- react-native: ^0.70.3

**To Reproduce**
Not clear

**Screenshots**

![image](https://user-images.githubusercontent.com/4684912/202187179-393b3374-a8fa-4db0-9407-fae75d2a39c4.png)

**Comment by vishalnarkhede** [comment]
@1987cr I think you logging these errors from chat client logger - https://github.com/GetStream/stream-chat-js/blob/master/docs/logging.md

Could you check if you are passing logger option when instantiate chat client?

**Comment by 1987cr** [comment]
Hey @vishalnarkhede you are indeed right, we do have a logger, you think it would be safe to ignore this specific error?

**Comment by vishalnarkhede** [comment]
It is safe to ignore this error!

**Comment by vishalnarkhede** [comment]
Although I would add a fix to avoid this particular api call from SDK itself. Will make a patch release soon.
