### ISSUE TITLE
Reload or Refresh of ChannelList

### ISSUE THREAD

**Issue by cleandevcode** [GetStream/stream-chat-react-native#1825]
Hello.
I want to reload or refresh the channel list after some actions.

I want to use `reloadList` or `refetchList` from `useChannelsContext`.
But I need to call it **_out_** of `ChannelList` component.

How can I refresh the channel list?

**Comment by vishalnarkhede** [comment]
We don't support this at the moment. The only way you can refresh the list by force reloading the ChannelList component. You can do this by setting the `key` on ChannelList and updating its value when you need to reload the list.

**Comment by cleandevcode** [comment]
Yup. So I tried to update the key whenever I need it.
But sometimes I see some errors like 
```
TypeError: null is not an object (evaluating 'channels.findIndex')
```


My implementation is:


```
const [key, setKey] = useState(0)

//After an action whenever I need to refresh
useEffect(()=> setKey((key)=>key+1), [`whenever I need it`])


// ChannelList
<ChannelList key={key}  ...props  />
```

**Comment by cleandevcode** [comment]
Yup. So I tried to update the key whenever I need it.
But sometimes I see some errors like 
```
TypeError: null is not an object (evaluating 'channels.findIndex')
```


My implementation is:


```
const [key, setKey] = useState(0)

//After an action whenever I need to refresh
useEffect(()=> setKey((key)=>key+1), [`whenever I need it`])


// ChannelList
<ChannelList key={key}  ...props  />
```
