### ISSUE TITLE
MessageSimple avatar display based on more than alignment

### ISSUE THREAD

**Issue by jake-danton** [GetStream/stream-chat-react-native#1836]
**Motivation**
I would like to be able to control visibility of the avatar in `MessageSimple` by a better mechanism than `alignment`. Specifically, I want the avatar to show up with right alignment on some occassions.

**Proposed solution**
Instead of having
```
        {alignment === 'left' && <MessageAvatar />}
        <MessageContent setMessageContentWidth={setMessageContentWidth} />
```

It should be something like

```
        {showAvatar && alignment === 'left' && <MessageAvatar />}
        <MessageContent setMessageContentWidth={setMessageContentWidth} />
        {showAvatar && alignment === 'right' && <MessageAvatar />}
```

OR

```
        {showAvatar(message) && alignment === 'left' && <MessageAvatar />}
        <MessageContent setMessageContentWidth={setMessageContentWidth} />
        {showAvatar(message) && alignment === 'right' && <MessageAvatar />}
```
where `showAvatar` function defaults to one where it doesn't show the current user's avatar but can be overridden to be whatever.

**Acceptance Criteria**
The ability to show avatars for any user (including current if desired) and any alignment.

**Comment by vishalnarkhede** [comment]
Thanks for the request and detailed description. We shall look into it and see if we can fit this in upcoming releases.

**Comment by khushal87** [comment]
Hey @JacobDanton, if I correctly understand your problem is it that you don't want to show avatars which are left-aligned and want to slow the avatars which are right-aligned, right?

**Comment by JacobDanton** [comment]
In my case, I want to show both. But the bigger ask is to have a more flexible hook that would make determining if an avatar shows or not be based on more than just alignment.
Thanks!

**Comment by vanGalilea** [comment]
@JacobDanton is this customisability matter still limit you?
