### ISSUE TITLE
Allow customization of message sender name

### ISSUE THREAD

**Issue by kyleqian** [GetStream/stream-chat-react-native#1852]
Right now sender name in the MessageFooter seems to use the user ID, which isn't ideal as those IDs can be arbitrary. Could there be a simple way to display `name` or `first_name` instead?

Using `stream-chat-expo: 4.15.0`

**Comment by vishalnarkhede** [comment]
@kyleqian we don't use user id, but `name` property on `message.user`, which is a custom property set on user either while creating the user or connecting the chat client.

**Comment by kyleqian** [comment]
Ah I see, I got mixed up because I think ID and name get initialized to the same value in the explorer, but ID doesn't seem `PATCH`-able. Thanks for clarifying, and for the useful code pointer!
