### ISSUE TITLE
bug: unread counts not the same between app and MessageList

### ISSUE THREAD

**Issue by kyleqian** [GetStream/stream-chat-react-native#1853]
**Describe the bug**

I noticed that my `ScrollToBottomButton` always shows a number regardless if I read messages or not (even when I click on it to scroll to bottom, the number doesn't go to 0).

I dug into it, and found that the the `channel` I use for my `ChannelScreen` has the correct unread counts, that is, 0. However, for some reason my `MessageList` has a stale reference to `channel`, which is returning non-0. Here is what my `ChannelScreen` looks like:
```js
const ChannelScreen = (props: { route: any; navigation: any }) => {
  const { route, navigation } = props
  const {
    params: { channelId, userId },
  } = route
  const { chatClient } = useChatClient({ userId })
  const channel = chatClient.channel('messaging', channelId)

  return (
    <SafeAreaView>
      <Chat client={chatClient}>
        <Channel channel={channel}>
          <View style={{ flex: 1 }}>
            <MessageList
              onThreadSelect={thread => {
                if (channel?.id) {
                  navigation.navigate('ThreadScreen', { channel, thread })
                }
              }}
            />
            <MessageInput />
          </View>
        </Channel>
      </Chat>
    </SafeAreaView>
  )
}
```

Is there a reason why the states being used by these components are out of sync? Possibly related: I'm currently not loading a `ChannelList` on app load, rather, I'm directly loading the `ChannelScreen` copied above.

**Package version**
- stream-chat-expo: 4.15.0 

**Smartphone (please complete the following information):**

- Device: Expo Go on iPhone

**Additional context**

**Comment by vanGalilea** [comment]
@kyleqian, thanks for reaching out; as you might've noticed, I moved this issue to the stream-chat-react-native-sdk repo. We will add this issue to our bugs backlog and get back to you!

**Comment by santhoshvai** [comment]
@kyleqian your channel has not been watched. This is why the unread counts are stale, and the mark read functions don't work if not watched before. Please change the channel as per the below snippet,

```
  const [channel, setChannel] = useState();

  useEffect(() => {
    const createAndWatchChannel = async () => {
      const newChannel = client.channel('messaging', channelId);
      await newChannel.watch(); // important to watch the channel before setting the channel to state
      setChannel(newChannel);
    };

    createAndWatchChannel();
  }, [chatClient , channelId]);
```

I am closing this issue as this should resolve the issue; please feel free to reopen it if it doesn't.
