### ISSUE TITLE
Overlay for reacting to a message cannot be dismissed on Android

### ISSUE THREAD

**Issue by QuinnStephens** [GetStream/stream-chat-react-native#1854]
**Describe the bug**
When I long-press a message on Android, I get the overlay menu from which I can choose a reaction to add, but I'm unable to select one or to dismiss the overlay. This problem does not occur on iOS.

**Dev environment info:**

- stream-chat-react-native 5.6.1
- react-native 0.66.3
- Device: Galaxy S9 with Android 10. Also occurs on every emulator I've tried so far

**To Reproduce**
1. Open a chat (presented by the `Channel` component) on an Android device or emulator
2. Long-press a message3. 
3. Confirm that the OverlayReactionList appears 
4. Tap on any reaction option or the background 

**Expected behavior**
Selecting a reaction should close the overlay and allow me to interact with the app. Alternatively, tapping the semi-transparent background should dismiss the overlay.

**Additional context**

**Screenshots**
![Screenshot_1670270770](https://user-images.githubusercontent.com/401306/205732798-63f7f0de-5fbc-44b4-acc0-a51357f6a7cf.png)

**Comment by vishalnarkhede** [comment]
@QuinnStephens Please take a look at https://getstream.io/chat/docs/sdk/reactnative/basics/troubleshooting/#touchables-not-working
