### ISSUE TITLE
How to stop font scaling in all getstream components?

### ISSUE THREAD

**Issue by Rakshit-Tagline** [GetStream/stream-chat-react-native#1857]
I have tried to apply allowfontscaling={false} in the whole library. but that doesn't work in messages.

**Comment by vanGalilea** [comment]
@Rakshit-Tagline thank's for reaching out, to get a better understanding of the issue please use one of the 2 templates we have either for a [bug report](https://github.com/GetStream/stream-chat-react-native/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md) or a [feature request](https://github.com/GetStream/stream-chat-react-native/blob/develop/.github/ISSUE_TEMPLATE/feature_request.md).

**Comment by vanGalilea** [comment]
@Rakshit-Tagline I gave it some thought, can you please try to apply the following in the root of your project `index.js/ts`

```
import {text} from 'eract-native'

Text.defaultProps = Text.defaultProps || {}
Text.defaultProps.allowFontScaling = false
```

I've tried it on my end. Please have a look and see if it works for you.

I'll be closing this issue in the meanwhile
