### ISSUE TITLE
Unable to view videos in chat on Macbook with Apple silicon

### ISSUE THREAD

**Issue by ngoue** [GetStream/stream-chat-react-native#1860]
**Describe the bug**
Trying to view open a video in `ImageGallery` when running on an Apple silicon Macbook causes the app to crash with the error `undefined is not a function`.

**Dev environment info (please complete/provide the following information):**

- `stream-chat-react-native@5.5.1`
- `react-native@0.70.3`
- Apple M1 Pro

**To Reproduce**
Install app on any Apple silicon Macbook and try to view a video in `stream-chat-react-native`.

**Expected behavior**
Be able to watch a video in the chat.

**Screenshots**
Here's the chat rendering the video preview thumbnails
<img width="754" alt="Screenshot 2022-12-09 at 10 36 50 AM" src="https://user-images.githubusercontent.com/6362408/206761655-5ebf1922-1330-4d21-b5a1-00c93ddd4be2.png">

When I tap on the video to watch it, the app crashes
<img width="754" alt="image" src="https://user-images.githubusercontent.com/6362408/206761831-c279c4a2-2ca7-403a-8029-08eb11c8e439.png">

The stack track from React Native indicating it's coming from inside the ImageGallery component
<img width="160" alt="image" src="https://user-images.githubusercontent.com/6362408/206762270-eb3185ee-644b-4422-95e2-b365075b31b9.png">

**Comment by vanGalilea** [comment]
@ngoue, thanks for reaching out are you running this on macOS, not iOS right?

**Comment by ngoue** [comment]
@vanGalilea that is correct – running on macOS.

**Comment by vanGalilea** [comment]
@ngoue, thanks for clarifying that. We're currently not supporting macOS officially and also some of our dependencies.
Therefore I'll be closing this issue.

**Comment by ngoue** [comment]
@vanGalilea thank you for taking the time to respond – I appreciate you looking into it.
