### ISSUE TITLE
Change Reaction Icon Colour

### ISSUE THREAD

**Issue by JSimai** [GetStream/stream-chat-react-native#1863]
**Motivation**
To the best of my knowledge and research, there's no clear way to change the colour of the reaction icons on messages (default blue). Also have not found a way to change the colour of the smaller bubbles below the reaction bubble.

**Proposed solution**
Currently there is 'messageSimple'->'reactionList'->'middleIcon' in the theme, I would hope that putting 'pathFill' or 'color' would change the icon colour.

**Acceptance Criteria**
The ability to change the reaction icon colour somewhere in the theme.

**Comment by JSimai** [comment]
Update: 
I gave my own CustomReactionList component: 
```
const CustomReactionList = () =>  {
    const {message} = useMessageContext();
    return (
      <ReactionList 
        color={Colours.myPrimary} 
        reactions={message.reactions} 
        // onReactionPress={(emoji) => console.log(`${emoji} pressed`)} 
      />
    );
  }
```

However it returned this error:
`
TypeError: undefined is not an object (evaluating 'reactions.some')
`

**Comment by vanGalilea** [comment]
@JSimai, thanks for reaching out. We will add this to our theme. Please follow this issue for more info.

**Comment by JSimai** [comment]
Amazing! Thanks for replying :)
