### ISSUE TITLE
Allow customizing the style of pinned messages

### ISSUE THREAD

**Issue by madsroskar** [GetStream/stream-chat-react-native#1865]
**Motivation**
Currently, you can't easily customize the style of pinned messages. You would have to customize the entire [Message](https://github.com/GetStream/stream-chat-react-native/blob/main/package/src/components/Message/Message.tsx#L700) component to do so.

**Proposed solution**
Add a theme variable for `message.pinned` or similar, typed as `ViewStyle`

**Acceptance Criteria**
☝🏻

**Comment by samihabuawadSL** [comment]
hi @vishalnarkhede -- for me this isn't working on v5.11.2, it could be a regression?

**Comment by lahiruSanjeewa2971** [comment]
> hi @vishalnarkhede -- for me this isn't working on v5.11.2, it could be a regression?

Hi,
I also using the same version. Any update on this???
could you be able to find any solution?
