### ISSUE TITLE
isValidMessage always returns true even if message input is empty

### ISSUE THREAD

**Issue by 1987cr** [GetStream/stream-chat-react-native#1866]
**Describe the bug**
`isValidMessage` function returns `true` even if input has no text or attachments, making send button always enabled.

From the documentation:

> [isValidMessage](https://getstream.io/chat/docs/sdk/reactnative/contexts/message-input-context/#isvalidmessage)
> 
> False if text within input box is empty and no images or files have been attached to a message yet. You can use this value to add > enabled/disabled Ui state on SendMessage button.

**Dev environment info (please complete/provide the following information):**

- stream-chat-react-native 5.6.1

**Expected behavior**
Send button (which internally is using `isValidMessage` to calculate `disabled` state) should be disabled if input is empty

**Additional context**

Taking a look at the code:

```
const isValidMessage = () => {
    if (text && text.trim()) { <---------------------------- Skips this because no text
      return true;
    }

    const imagesAndFiles = [...imageUploads, ...fileUploads];
    if (enableOfflineSupport) { <------------------------ Enters here because we have offline support enabled
      // Allow only if none of the attachments have unsupported status
      for (const file of imagesAndFiles) { <--------------- Skips this because no files or images attached
        if (file.state === FileState.NOT_SUPPORTED) {
          return false;
        }
      }

      return true; <-------------------------------------- Returns true here 
    }

    ...
  };
```

Applying this patch solves the issue:

```
diff --git a/node_modules/stream-chat-react-native-core/src/contexts/messageInputContext/MessageInputContext.tsx b/node_modules/stream-chat-react-native-core/src/contexts/messageInputContext/MessageInputContext.tsx
index fea533a..a58bb72 100644
--- a/node_modules/stream-chat-react-native-core/src/contexts/messageInputContext/MessageInputContext.tsx
+++ b/node_modules/stream-chat-react-native-core/src/contexts/messageInputContext/MessageInputContext.tsx
@@ -493,6 +493,10 @@ export const MessageInputProvider = <
 
     const imagesAndFiles = [...imageUploads, ...fileUploads];
     if (enableOfflineSupport) {
+      if (imagesAndFiles.length === 0) {
+        return false;
+      }
+
       // Allow only if none of the attachments have unsupported status
       for (const file of imagesAndFiles) {
         if (file.state === FileState.NOT_SUPPORTED) {
```

**Screenshots**

![Screenshot 2022-12-15 at 12 37 57](https://user-images.githubusercontent.com/4684912/207849857-b5885dd6-593b-4b39-a564-47c3e40ee4d8.png)
.

**Comment by vanGalilea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/1866?planning-poker) with Zenhub @madsroskar @khushal87

**Comment by vanGalilea** [comment]
@1987cr, thanks for reaching out, we appreciate your contribution, and we will have a look at your patch.
We've added it to our backlog!

**Comment by khushal87** [comment]
Hey, @1987cr, is this still an issue, on our TypescriptMessagingApp(examples/TypescriptMessagingApp) this isn't reproducible. If there's no text, the send button is disabled as you can see. Correct me if there's something else you are talking about here. Thanks 😄 

![simulator_screenshot_1236EC7B-A330-4CF7-82AD-B240ACBA1F1B](https://user-images.githubusercontent.com/39884168/213757007-8eb85ff4-6904-4cf0-8b5c-f4eac5b07c12.png)

**Comment by 1987cr** [comment]
Still having the issue without the patched code, maybe it's because we are using custom SendButton component, but either way if you check the function I linked, if you got offline support enabled the logic is not quite right:

stream-chat-react-native-core/src/contexts/messageInputContext/MessageInputContext.tsx L489
```
  /** Checks if the message is valid or not. Accordingly we can enable/disable send button */
  const isValidMessage = () => {
    if (text && text.trim()) {
      return true;
    }

    const imagesAndFiles = [...imageUploads, ...fileUploads];

    if (enableOfflineSupport) { <----------------------------------------- you go in here
      // Allow only if none of the attachments have unsupported status
      for (const file of imagesAndFiles) { <------------------------------- you skip this block because imagesAndFiles lenght is 0
        if (file.state === FileState.NOT_SUPPORTED) {
          return false;
        }
      }

      return true; <-------------------------------------------- you end up returning true here
    }

    for (const file of imagesAndFiles) {
      if (!file || file.state === FileState.UPLOAD_FAILED) {
        continue;
      }
      if (file.state === FileState.UPLOADING) {
        // TODO: show error to user that they should wait until image is uploaded
        return false;
      }

      return true;
    }

    return false;
  };
```

Patch we did is just adding this to the beginning of the function:

```
     if (imagesAndFiles.length === 0) {
       return false;
     }
```
