### ISSUE TITLE
onSELECT NOT WORKING REACT NATIVE EXPO

### ISSUE THREAD

**Issue by Trikcode** [GetStream/stream-chat-react-native#1872]
When I click the channel on the screen rendered by the channelList, I am unable to navigate to the channel screen
I am using react native expo and running the application on my phone! Is there anything am doing wrong?
![phoneimage](https://user-images.githubusercontent.com/73602565/208267371-93fb214e-38d5-4781-8443-4eb3e3ba324f.jpeg)
![Screenshot (145)](https://user-images.githubusercontent.com/73602565/208267375-cf14884d-185a-4124-bce3-0222122cc7bc.png)

**Comment by vanGalilea** [comment]
@Trikcode thanks for reaching out. Please have a look at this [guide](https://getstream.io/chat/docs/sdk/reactnative/basics/troubleshooting/#touchables-not-working
) and let us know if it works 👍🏻

**Comment by Trikcode** [comment]
Thanks @vanGalilea This was helpful!

**Comment by cheejiayuan512** [comment]
Facing this issue on expo 47. GestureHandlerRootView and non native StackNavigator is used. Anyone has any clue how to debug this?
