### ISSUE TITLE
Set Channel Using Channel ID

### ISSUE THREAD

**Issue by JSimai** [GetStream/stream-chat-react-native#1875]
**Motivation**
Stream is elite but I'm having trouble implementing it in a system where a chat channel is associated with an entity in my separate database. In my case, I have groups of users called Pods. On Pod creation, the members of the Pod are added to a chat channel which is great. However, each Pod has it's own few screens that can be accessed from the Home screen. On one of these screens, users can edit who is in the Pod. So, if adding another member, I would then want to add that new member to the chat as well. But the issue is that I can't set the channel so as to use channel.addMembers() without first going through the ChannelList screen. 

**Proposed solution**
I was hoping that there would be a function to set the channel using its ID. So when I go into a Pod from the home page, I can have the channel ID stored in my database and call this new function eg. getChannel(data.channel_ID). Allowing me to access channel methods without having to go through the ChannelList.

**Acceptance Criteria**
A way to set the channel without having to go through the ChannelList.

**Comment by vanGalilea** [comment]
@JSimai thanks for reaching out, if I understand your question correctly you should be able to achieve this by doing the following:

```
  const [channel, ...rest] = await chatClient.queryChannels({
    type: "messaging",
    id: "some-channel-id"
  });

  await channel.addMembers(["some-member-id"]);
```

Let me know if it works for your use case and please don't hesitate to contact us may you have any other questions.

**Comment by JSimai** [comment]
It works! Perfect, thank you! And sorry for not being able to figure that out....
