### ISSUE TITLE
Report error on the UI when file size is greater than the limit

### ISSUE THREAD

**Issue by khushal87** [GetStream/stream-chat-react-native#1877]
**Describe the bug**
Currently, the UI doesn't give any feedback when a file with a size of more than a limit is uploaded. The SDK by default starts uploading it and the loader is struck. This isn't a good user experience. 

Develop

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to Channel
2. Click on Message input and upload a file with a higher file size.
3. You would find no update on the UI and the loader is struck for a long time.

**Expected behaviour**
There should be feedback on the screen/disable such file uploads.

**Additional context**
NIL

**Screenshots**
NIL

**Comment by vanGalilea** [comment]
Where do we get the file size max. from? Let's figure this our first, might be app settings etc.

**Comment by vanGalilea** [comment]
Fixed with #1902
