### ISSUE TITLE
Performance lag when trying to search a message in the Channel

### ISSUE THREAD

**Issue by khushal87** [GetStream/stream-chat-react-native#1882]
**Describe the bug**
There's a performance lag when searching for messages in the Channel. This is related to the Zendesk issue - https://getstream.zendesk.com/agent/tickets/32028.

Note: Please read the last message by _Adam Wildman_ to understand the issue and save time.

**Dev environment info (please complete/provide the following information):**

Not shared by the customer

**To Reproduce**

1. Go to a Channel
2. Try searching for messages.
3. See the performance lag.

**Expected behavior**
The message should be queried/searched in the UI without any lag.

**Additional context**
NIL

**Screenshots**

Video - https://us02web.zoom.us/rec/share/USXoe5llhG8ittzCnKEEDaTZwfloidTpS_n7ZtUfQ63BsssXDBdbwHBKaldLZyM.AKZ8qr8aigw_X4HH
Passcode - z46#BxVf

**Comment by santhoshvai** [comment]
This issue was moved to an internal backlog list of less urgent feature/docs requests.
