### ISSUE TITLE
Code does not work when using expo 47

### ISSUE THREAD

**Issue by gregdevvv** [GetStream/stream-chat-react-native#1884]
**Describe the bug**

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native/stream-chat-expo)
- react-native or expo version
- Device/Emulator (android/ios) and OS version

**To Reproduce**

**Expected behavior**

**Additional context**

**Screenshots**

![image](https://user-images.githubusercontent.com/113376479/210256927-a5711fe3-1d20-4227-b910-6347b2cecfde.png)

**Comment by vanGalilea** [comment]
@gregdevvv thank's for reaching out, to get a better understanding of the issue please use one of the 2 templates we have, in your case a [bug report](https://github.com/GetStream/stream-chat-react-native/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md)

**Comment by vanGalilea** [comment]
closed in favor of #1887
