### ISSUE TITLE
Reconnecting status banner sometimes doesn't go away on ChannelList and Channel components

### ISSUE THREAD

**Issue by skudirka-tw** [GetStream/stream-chat-react-native#1889]
**Describe the bug**
We were testing Wifi connectivity and failed message sending and retry workflow, and intermittently we would get the `Reconnecting...` status banner remain on the screen, even well after the network has been reestablished. Our host app also has an `Offline Mode | No Connection Detected` red banner that displays, but goes away after the network is reestablished. You can see in the video and screenshots (by two different test users) that your banner sometimes remains. Again, it is intermittent.

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native/stream-chat-expo): `stream-chat-react-native@5.6.1`
- react-native or expo version: `react-native@0.68.5`
- Device/Emulator (android/ios) and OS version: `iPhone 14 Pro, IOS 16.0 & 16.1`

**To Reproduce**

1. Go to a screen with the ChannelList or Channel component.
2. Turn off your Wifi.
3. `Reconnecting...` banner should show.
4. Turn Wifi back on.
5. `Reconnecting...` sometimes remains on screen, even after app regains network connection and cannot be dismissed.

**Expected behavior**
`Reconnecting...` banner should always disappear as app regains network connection.

**Screenshots**

https://user-images.githubusercontent.com/115643473/210617379-ffeab847-836d-43a4-bdbf-1335850ba652.mov

![image](https://user-images.githubusercontent.com/115643473/210617587-a46c5f67-88e1-4c12-97fc-747f6823117f.png)

**Comment by khushal87** [comment]
Hey @skudirka-tw, thanks for reporting this bug. We were able to triage this issue and it indeed looks like and issue after the network is recovered. We will try to pick this up soon and fix it.

**Comment by khushal87** [comment]
This looks like an iOS simulator only issue and doesn't happen on real devices. Can you check and get back to us if you face it also in a real device? Thanks 😀

https://user-images.githubusercontent.com/39884168/214267693-e79b9c1b-f0ec-46ee-8194-fe7cd995a7b3.MOV

**Comment by neopit** [comment]
BTW, we saw this regularly on iOS and Android (simulator but don't know on real devices).
We don't know if this is a bug.

For reproducing, we have to  put the app in background and bak

**Comment by khushal87** [comment]
Can you test it on @neopit and see if this happens?

**Comment by neopit** [comment]
Yes it happens on real device as well I tested.
When we back from background then we can see the reconnection bar

**Comment by vanGalilea** [comment]
Thanks for reaching out. We couldn't reproduce this issue on our devices.

It would be awesome if you'd be able to share a minimalistic repo where the problem is reproduced.

The fastest way to achieve that is with the following command to create a new RN project with Stream chat in it: 

`npx react-native init StreamChatApp --template react-native-stream-chat-template`

More information about how to run the template after initialization can be found [here](https://github.com/GetStream/react-native-stream-chat-template#react-native-stream-chat-template)

Please then share a Github repo with us, where we can explore the issue ourselves.

**Comment by vanGalilea** [comment]
@skudirka-tw has reported internally that they're no longer experiencing the problem.

May this still be an issue for anyone, a [reproducible repo](https://github.com/GetStream/stream-chat-react-native/issues/1889#issuecomment-1457963021) is welcome and will be a reason to re-open this issue.
