### ISSUE TITLE
Channels of different channel type displayed to a member on new message received

### ISSUE THREAD

**Issue by khushal87** [GetStream/stream-chat-react-native#1893]
**Describe the bug**

A user receives a channel on the channel list's top of a different type when a new message is sent on that channel from a different user and has filters of different types. 

**Dev environment info (please complete/provide the following information):**
Latest

**To Reproduce**

1. Create two channel types: `ABC` and `XYZ`
2. Create a channel for each: `ABC-Channel` and `XYZ-Channel`
3. Add users to each channel: `User1` and `User2` should be members of each channel
4. Log in as User1 and view a Channel List with the following filter:
```
	{
		type: ‘ABC’,
		members: { $in: [User1] },
	}
```
5. You should see a single channel: `ABC-Channel`
6. On a separate device, login to User2 and send a message in channel `XYZ-Channel`
7. You will see `XYZ-Channel` show up in User1’s Channel List even though it should be filtered out

**Expected behavior**
The channel shouldn't be displayed in the Channel list on top if the correct filters are applied.

**Additional context**
None

**Screenshots**
None

**Comment by mattmcguin** [comment]
@aharwood9  A current workaround we're using is to create a ChannelPreviewWrapper component and return null if it's the incorrect channel type.

```
const ChannelPreviewWrapper = (props) => {
    if (props.channel.type !== 'ABC') {
        return null
    }

   return <StreamChannelPreview {...props} />
}
```

**Comment by aharwood9** [comment]
@mattmcguin - That looks like a better workaround than `lockChannelOrder` - thanks ⭐
