### ISSUE TITLE
Channel has incorrect unreadCount after checking another channel with unread messages

### ISSUE THREAD

**Issue by tbhorses** [GetStream/stream-chat-react-native#1894]
**Describe the bug**
`ChannelList` seems to be passing an incorrect value for `channel.state.unreadCount`

**Dev environment info (please complete/provide the following information):**
- Package version (stream-chat-react-native/stream-chat-expo)
  ```
    "stream-chat": "6.3.0",
    "stream-chat-react-native": "^4.3.1",
    "stream-chat-react-native-core": "^4.3.1",
  ```
- Device/Emulator: 
  - iOS Emulator: 15.02 / Device: iPhone 11 & 12
  - Android: Google Pixel 6 / Android Version 13

**To Reproduce**
1. Create a `Preview` component for the `ChannelList`
```
         <ChannelList
            filters={channelsFilter}
            LoadingIndicator={MessagingMainInboxLoadingIndicator}
            EmptyStateIndicator={MessagingMainInboxEmptyStateIndicator}
            Preview={MessagingMainInboxPreview}
            List={MessagingChannelsList}
          />
```
2. Have `MessagingMainInboxPreview` render the `channel.state.unreadCount` that is passed by the `ChannelList`. The Preview, when clicked, should navigate you to a page that renders the Channel
3. From two different channels, send the user a message. The ChannelList should display two channels having 1 new messages.
4. Click into one of the channels with the unread message.
5. Go back to the main ChannelList page
6. Notice, there is no longer any unread message indicators. (or the all say 0, depending on how it is implemented)

**Expected behavior**
The other channels with unread messages should still indicate that they have unread messages. 

**Additional Context** 
Ive read through the release notes for all the releases since 4.3.1 and none of them mention fixing this issue.
Further context. Here is the bit of code responsible for getting the `unreadCount` from the `Channel` in `MessagingMainInboxPreview`: 
```
  const MAX_UNREAD_COUNT = 9
   ///.....
  const channelUnreadCount = React.useMemo(() => {
    const unreadCount = channel.state.unreadCount;

    if (!unreadCount) {
      return undefined;
    }

    return unreadCount > MAX_UNREAD_COUNT ? `${MAX_UNREAD_COUNT}+` : unreadCount.toString();
  }, [channel.state.unreadCount]);
```

**Screenshots**

Before
![before](https://user-images.githubusercontent.com/109698467/210825121-390041ba-7fbd-464d-8761-b62e3646c7ee.png)
After clicking into a channel with unread messages (viewing <Channel/>)
![click-in](https://user-images.githubusercontent.com/109698467/210825123-13757cba-bed3-4f46-9fe3-66e28e09332b.png)
After (no indicators on any messages)
![after](https://user-images.githubusercontent.com/109698467/210825126-8018e3f2-137d-4c6c-afd2-e2554abb2f1e.png)

**Comment by santhoshvai** [comment]
Hi, this is not currently repducible for us. I suspect that this might be due to the `"stream-chat": "6.3.0"` version..

Could you please update to `"stream-chat": "6.5.0"` and inform us if it fixes it for you.

**Comment by tbhorses** [comment]
upgrading to "6.5.0" seems to work! thanks

**Comment by tbhorses** [comment]
I perhaps posted the above comment a little prematurely:
It does seem like upgrading the package did fix my problem, but I am struggling to match the versions up between all the dependencies. I now have, but I'm getting a lot of typescript errors. 
```
  "stream-chat": "6.5.0",
  "stream-chat-react-native": "^4.3.1",
  "stream-chat-react-native-core": "^4.3.1",
  ```
  
  reading [this page about generics](https://getstream.io/chat/docs/sdk/react/guides/typescript_and_generics/) I was able to figure out I needed to pass in the correct `DefaultStreamChatGenerics` type on client creation, but now I'm getting what seems to be a mismatch of dependencies from the packages. 
  
  I can't find anywhere what versions correspond with what. 
  
 Installing the most recent version requires upgrading my `node` version... and I want to avoid that at the moment if I can. I looked at this [typescript app example](https://github.com/GetStream/stream-chat-react-native/blob/develop/examples/TypeScriptMessaging/package.json) and it looks like it doesn't even import `stream-chat` package at all. (looks like it is a dependency of both `stream-chat-react-native` & `stream-chat-react-native-core`). Any help getting the correct

**Comment by santhoshvai** [comment]
@tbhorses you dont need add "stream-chat" as a dependency to your app actually. Since "stream-chat" is a dependency of the "stream-chat-react-native-core".  I have looked at the history now, if you upgrade to v4.9.0 your stream-chat would be upgraded. 

In fact can you replace the following three lines 

```
 "stream-chat": "6.5.0",
  "stream-chat-react-native": "^4.3.1",
  "stream-chat-react-native-core": "^4.3.1",
```

with one line,

```
 "stream-chat-react-native": "^4.9.0",
```

Can you please do this and check again.
