### ISSUE TITLE
Crash if project imports newer react-native-svg library (13.x)

### ISSUE THREAD

**Issue by akenger** [GetStream/stream-chat-react-native#1898]
**Describe the bug**
Crash if your project uses newer react-native-svg library

**Dev environment info (please complete/provide the following information):**
stream-chat-react-native
react-native
All devices

**To Reproduce**

Add react-native-svg 13.6.0 as a local project dependency
Use stream-chat react native components
App crashes due to incompatible react-native-svg libraries

**Expected behavior**
Expect chat message list to appear and not crash

**Additional context**
We solved this by adding the below to our package.json

```
"overrides": {
    "react-native-svg": "$react-native-svg"
  },

```

Recommend stream-chat update dependency in stream-chat-react-native-core to 13.6.0

**Screenshots**

**Comment by akenger** [comment]
Workaround above - providing for anyone else having this issue.

Recommend update dependency in stream-chat-react-native-core to react-native-svg  ^13.6.0

**Comment by vanGalilea** [comment]
@akenger, thanks for reaching out, what does the crash entail? Can you give us more info like the error that is being logged?
