### ISSUE TITLE
End-to-end encryption

### ISSUE THREAD

**Issue by mishkeTz** [GetStream/stream-chat-react-native#1907]
**Proposed solution**
End-to-end encryption.

**Acceptance Criteria**
Messages are end-to-end encrypted.

Hello, it seems that there is already out of the box support for end-to-end encryption for flutter apps https://getstream.io/chat/docs/sdk/flutter/guides/end_to_end_chat_encryption/

I am wondering if there is a plan to implement this in the RN project?

**Comment by khushal87** [comment]
Hey,

Thanks for reaching out. We will add this to our backlog/wishlist to see if this feature would be helpful to more customers. We don't plan to add it in the near future. I will close this ticket as this is a particular use case, and we will try to pick this up later in the future.

Thanks for providing us with your valuable requests and input to improve our product.

**Comment by bogdanovic91** [comment]
@khushal87 hello, any plans to add encryption to RN nowadays?

**Comment by Saad-Bashar** [comment]
This is a much-needed feature! 🙏
