### ISSUE TITLE
Users aren't able to receive or send messages

### ISSUE THREAD

**Issue by DaveHellsmith** [GetStream/stream-chat-react-native#1910]
**Describe the bug**

I am not particularly sure if this has to do with how we are using the SDK for react-native,
or with the SDK itself - however the users of our app are experiencing issues. Specifically message loss in the sense that 
messages aren't being sent/received properly.

It seems to happen more frequently when the app has been in the background for far too long, however neither our devs nor our QA were capable of reproducing it, so any suggestions would be very welcome.

Here is the rough outline of our usage - 

```jsx
const App = () => {
  return (
    <GestureHandlerRootView style={styles.container}>
      <OverlayProvider MessageActionListItem={CustomMessageActionListItem}>
        <ApolloProvider client={client}>
          <NativeBaseProvider theme={theme}>
            <AppContext.Provider value={{ alert, handleSetAlert }}>
                <IAPHubProvider>
                  <NavigationContainer>
                    <Wrapper />
                  </NavigationContainer>
                </IAPHubProvider>
            </AppContext.Provider>
          </NativeBaseProvider>
        </ApolloProvider>
      </OverlayProvider>
    </GestureHandlerRootView>
  );
};

const Wrapper = () => {
  const [clientReady, setClientReady] = useState(false);
  const user = useReactiveVar(currentUserVar);
  const streamClientInitialized = useReactiveVar(streamClientInitializedVar);

  useEffect(() => {
    const setupClient = async () => {
      if (
        !user?.id ||
        !user?.streamToken ||
        clientReady ||
        streamClientInitialized
      ) {
        return;
      }

      await streamChatClient.connectUser(
        {
          id: user.uuid,
          name: `${user.profile?.firstName}`,
        },
        user.streamToken,
      );

      setClientReady(true);
      streamClientInitializedVar(true);
    };

    setupClient();
  }, [user, clientReady, streamClientInitialized]);

  return clientReady ? (
    <Chat style={streamTheme} client={streamChatClient}>
      <Screens />
    </Chat>
  ) : (
    <Screens />
  );
};
```

The poorly named `Wrapper` component is used due to us also using [React Navigation](https://reactnavigation.org/). The user token will be in the reactive variable only after a screen responsible for authenticating against firebase and retrieving user details from our backend renders. So essentially the expectation here is that it will render `AuthLoading` - then that will set the reactive variable and `Wrapper` will rerender, now with a connected stream client and the `Chat` HOC wrapping around the `Screens` from react navigation.

The only other component we use from the SDK is the channel, in the bellow code aliased as `StreamChannel`:

```jsx
const Channel = ({
  channel,
}: Props) => {

  return (
    <StreamChannel
      channel={channel}
      keyboardVerticalOffset={0}
    >
      <MessageList />
      {!isReadonly ? <MessageInput /> : null}
    </StreamChannel>
  );
};

export default Channel;
```

And this is used in a `react-navigation` screen that passes in the channel after our backend creates it.

**Dev environment info (please complete/provide the following information):**

-  `"stream-chat-react-native": "^5.4.2"`
- react-native
- Any android or iOS version

**To Reproduce**

1. Users A and B initiate a chat
2. User A sends the app to the background
3. User B keeps sending messages
4. User A reopens the app, after which is no longer receiving messages from user B
5. User B is no longer receiving messages from user A.

**Expected behavior**
It should not lose messages.

**Additional context**
The MAU on the dashboard seems to exceed the actual number of users significantly.

**Screenshots**
N/A

**Comment by llausa** [comment]
We're having a similar issue - reproducible with ios simulator.

User leaves app and goes to foreground, and is not able to receive messages after coming back to app. But is able to send messages and others can see the new messages.

**Comment by llausa** [comment]
It seems like the `<Chat />` component isn't re-rendering when the user returns from foreground back to a chat channel.

**Comment by DaveHellsmith** [comment]
@llausa I did end up doing kind of a workaround for this.

```jsx
  useEffect(() => {
    const subscription = AppState.addEventListener(
      'change',
      async nextAppState => {
        if (
          appState.current.match(/inactive|background/) &&
          nextAppState === 'active'
        ) {
          await streamChatClient.connect();
          await streamChatClient.recoverState();
          streamClientInitializedVar(true);
        } else {
          streamClientInitializedVar(false);
        }

        appState.current = nextAppState;
      },
    );

    return () => {
      subscription.remove();
    };
  }, [navigation]);

  return clientReady ? (
    <Chat style={streamTheme} client={streamChatClient}>
      <Screens />
    </Chat>
  ) : (
    <Screens />
  );
```

And then in the component were I render the channel

```jsx
  if (!streamClientInitialized) {
    return null;
  }
```

Basically tracking the app state changes and manually calling a connection, got the inspiration from https://github.com/GetStream/stream-chat-js/issues/100#issuecomment-706073387 .

It seems that it's supposed to do this on it's own, however in the sources I can see this comment:

```typescript
  /**
   * Disconnects the websocket connection, without removing the user set on client.
   * client.closeConnection will not trigger default auto-retry mechanism for reconnection. You need
   * to call client.openConnection to reconnect to websocket.
   *
   * This is mainly useful on mobile side. You can only receive push notifications
   * if you don't have active websocket connection.
   * So when your app goes to background, you can call `client.closeConnection`.
   * And when app comes back to foreground, call `client.openConnection`.
   *
   * @param timeout Max number of ms, to wait for close event of websocket, before forcefully assuming succesful disconnection.
   *                https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent
   */
  closeConnection = async (timeout?: number) => {
    if (this.cleaningIntervalRef != null) {
      clearInterval(this.cleaningIntervalRef);
      this.cleaningIntervalRef = undefined;
    }

    await Promise.all([this.wsConnection?.disconnect(timeout), this.wsFallback?.disconnect(timeout)]);
    return Promise.resolve();
  };
```

Which suggests that the devs on this are expecting consumers to manually do connect reconnect in their apps similarly to what I did. 🤷

**Comment by vanGalilea** [comment]
@DaveHellsmith tnx for reaching out, we're on it. Please follow this issue for future updates.

**Comment by billnbell** [comment]
Note I am ok with this version. But if I upgrade it breaks again.

```
    "react-native-quick-sqlite": "4.0.8",
    "stream-chat": "^8.2.0",
    "stream-chat-react-native": "5.5.1",
    "stream-chat-react-native-core": "5.5.1",
```

Maybe this helps others?

**Comment by llausa** [comment]
I'll give this a go while we wait for fixes  - thanks @billnbell!

**Comment by llausa** [comment]
We ended up passing `key={key}` to the `Chat` component and incrementing key using a appStateListener to increment the key (originally initiated as a hook with value of 0):
```
 useAppStateListener(async () => {
    setKey((key) => key + 1);
  });
```

**Comment by vanGalilea** [comment]
> 

Hey @llausa can you specify what was the approximate duration of the app in background?

**Comment by vanGalilea** [comment]
@DaveHellsmith and @llausa, we have been trying to reproduce this issue, yet no success. 
We also tried physical devices and in-production builds.

These kinds of issues are complex and hard to triage. Therefore, to pinpoint it as fast as possible. 
We would like to ask you to share a minimalistic repo where the problem is reproduced.

May you have any other information (Sentry/Bugsnag logs etc.) that will assist us in getting closer to the root cause of this problem, please share it with us.

**Comment by DaveHellsmith** [comment]
@vanGalilea any chance that you could share the exact codebase on which you tried to reproduce this?

**Comment by khushal87** [comment]
We tested our TypescriptMessagingApp, and SampleApp. You can find them inside `examples` directory. @DaveHellsmith

**Comment by billnbell** [comment]
My background issue is literally 1 second.

1. User 1. Open Chat, and type a message
2. User 2. Other user - type a message to user 1.
3. User 1 - put app in background for 1 second. Then open it - and you should be on Chat.
4. User 2 - send message to user 1.
5. User 1 - never receives message from user 2.

**Comment by billnbell** [comment]
> We ended up passing `key={key}` to the `Chat` component and incrementing the key (originally initiated as a hook with value of 0) using an appStateListener hook:
> 
> ```
>  useAppStateListener(async () => {
>     setKey((key) => key + 1);
>   });
> ```
> 
> While we await for a fix from getStream

Did you try the versions I posted?

**Comment by vanGalilea** [comment]
> Note I am ok with these versions listed below, it reconnects when I use 5.5.1. But if I upgrade past 5.5.1 it breaks again.
> 
> ```
>     "react-native-quick-sqlite": "4.0.8",
>     "stream-chat": "^8.2.0",
>     "stream-chat-react-native": "5.5.1",
>     "stream-chat-react-native-core": "5.5.1",
> ```
> 
> Maybe this helps others?

Another thing that seems very puciliour, you shouldn't add `stream-chat` and/or `stream-chat-react-native-core` as dependencies to your app. Those dependencies are already installed and provided through our chat SDK. This has caused weird behaviours in the past, can you please make sure you only install `stream-chat-react-native` as a dependency (and all our peer dependencies)

**Comment by vanGalilea** [comment]
> > We ended up passing `key={key}` to the `Chat` component and incrementing the key (originally initiated as a hook with value of 0) using an appStateListener hook:
> > ```
> >  useAppStateListener(async () => {
> >     setKey((key) => key + 1);
> >   });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > While we await for a fix from getStream
> 
> Did you try the versions I posted?

@khushal87 tried to reproduce with the versions you gave us, yet without success.

Can somewhen try to reproduce this and share a repo with us? We will appreciate it 😁

**Comment by billnbell** [comment]
> > Note I am ok with these versions listed below, it reconnects when I use 5.5.1. But if I upgrade past 5.5.1 it breaks again.
> > ```
> >     "react-native-quick-sqlite": "4.0.8",
> >     "stream-chat": "^8.2.0",
> >     "stream-chat-react-native": "5.5.1",
> >     "stream-chat-react-native-core": "5.5.1",
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Maybe this helps others?
> 
> Another thing that seems very puciliour, you shouldn't add `stream-chat` and/or `stream-chat-react-native-core` as dependencies to your app. Those dependencies are already installed and provided through our chat SDK. This has caused weird behaviours in the past, can you please make sure you only install `stream-chat-react-native` as a dependency (and all our peer dependencies)

I get this:

TheClub/src/utils/notificationHandler.ts
  16:1  error  'stream-chat' should be listed in the project's dependencies. Run 'npm i -S stream-chat' to add it  import/no-extraneous-dependencies

**Comment by billnbell** [comment]
I just set in eslint to off for `import/no-extraneous-dependencies` for now. Unsure the correct way to handle this.

**Comment by santhoshvai** [comment]
@billnbell additionally could also check if removing `package-lock.json` helps

**Comment by vanGalilea** [comment]
@DaveHellsmith and rest, we've just released a beta release [v5.9.1-beta.1](https://www.npmjs.com/package/stream-chat-react-native/v/5.9.1-beta.1).

Can you let us if it works for you guys?

**Comment by billnbell** [comment]
> @billnbell additionally could you please also check if removing `package-lock.json` help

We dont use package-lock.json we are using yarn, and yes we remove yarn.lock all the time, and have tested that.

**Comment by billnbell** [comment]
> > I just set in eslint to off for `import/no-extraneous-dependencies` for now. Unsure the correct way to handle this.
> 
> What is the npm version you're using?

We are using yarn. v1.22.18

**Comment by billnbell** [comment]
> I just set in eslint to off for `import/no-extraneous-dependencies` for now. Unsure the correct way to handle this.

This no-extraneous-dependencies is a feature of jest. Unsure why I get it, but I turned it off in eslint.json

**Comment by billnbell** [comment]
> @DaveHellsmith and rest, we've just released a beta release [v5.9.1-beta.1](https://www.npmjs.com/package/stream-chat-react-native/v/5.9.1-beta.1).
> 
> Can you let us know if this fix works for you guys?

What is in it? I cannot find a changeset/branch ?

**Comment by khushal87** [comment]
Hey @billnbell, you can find the changes yet to be rolled out [here](https://github.com/GetStream/stream-chat-react-native/pull/1944). The one we have shared almost has the same changes but is in beta for testing.

Feel free to reach us with queries, if any.

**Comment by vanGalilea** [comment]
> > @DaveHellsmith and rest, we've just released a beta release [v5.9.1-beta.1](https://www.npmjs.com/package/stream-chat-react-native/v/5.9.1-beta.1).
> > Can you let us know if this fix works for you guys?
> 
> What is in it? I cannot find a changeset/branch ?

[v5.9.1](https://github.com/GetStream/stream-chat-react-native/releases/tag/v5.9.1)

**Comment by billnbell** [comment]
> > > @DaveHellsmith and rest, we've just released a beta release [v5.9.1-beta.1](https://www.npmjs.com/package/stream-chat-react-native/v/5.9.1-beta.1).
> > > Can you let us know if this fix works for you guys?
> > 
> > 
> > What is in it? I cannot find a changeset/branch ?
> 
> [v5.9.1](https://github.com/GetStream/stream-chat-react-native/releases/tag/v5.9.1)

What is the difference between v5.9.1 and v5.9.1-beta.1 
?

**Comment by llausa** [comment]
I'll remove our hack and test `v5.9.1` - that's for all the support @vanGalilea!

Thanks for battling with me on this one @billnbell!

**Comment by llausa** [comment]
Updating to `v5.9.1` has resolved our issue 👍 thank you all!

**Comment by DaveHellsmith** [comment]
@vanGalilea the update has indeed resolved this particular issue, thank you.

**Comment by arekkubaczkowski** [comment]
I got the same issue on `v6.1.1` @khushal87, it literally stops refreshing the chat list after 1 second app in the background.

**Comment by arekkubaczkowski** [comment]
I tried disabling `closeConnectionOnBackground` but the issue remains.
