### ISSUE TITLE
Implementing InLineDateSeparator for every grouped message.

### ISSUE THREAD

**Issue by GirugaCode** [GetStream/stream-chat-react-native#1912]
**Describe the bug**
I am attempting to render `InLineDateSeparator` for each group messages after a period of time. I've attempted using `maxTimeBetweenGroupedMessages` to separate and display `InLineDateSeparator` again after a set amount of time (ex. 2hrs).  But there is no given render.

I know running the computation for the dates are a heavy operation but is there any way of achieving this result for `InLineDateSeparator`?

**Dev environment info:**

- Package version - stream-chat-react-native
- react-native
- iPhone Xs Max Device

**Expected behavior**
I'm looking for a way to render `InLineDateSeparator` for every grouped message.

**Comment by vanGalilea** [comment]
@GirugaCode thank's for reaching out, we will look into it and get back to you.

**Comment by GirugaCode** [comment]
Thank you! Please do let me know If there is any additional details I can provide on my end for this.

**Comment by vishalnarkhede** [comment]
@GirugaCode 

> But there is no given render.

What do you mean exactly? Pardon us for the delays.

**Comment by isekovanic** [comment]
Marking this issue as stale since there's no reply and closing in favor of that.
