### ISSUE TITLE
The return type from messageActions does not match the type from prop messageActions on the Channel component.

### ISSUE THREAD

**Issue by DannyBiezen** [GetStream/stream-chat-react-native#1917]
**Describe the bug**
I'm trying to remove thread functionality from my app. To accomplish this I'm trying to overwrite the `messageActions` prop on the `Channel` component. I want to keep all of the default functionality and only remove the `threadReply` option. I'm using the `messageActions` function to generate the correct array of message actions.

Unfortunately the typings for `messageActions` seem to be incorrect. The return type from this function is `(MessageActionType | null)[] | undefined` while I would've expected it to be `MessageActionType[] | undefined`. This causes issues when using the `messageActions` prop on the `Channel` component as this prop expect the type to be  `MessageActionType[] | undefined`.

**Dev environment info (please complete/provide the following information):**
"stream-chat": "8.1.2",
"stream-chat-expo": "^5.7.0"
"expo": "^47.0.12"

**To Reproduce**
Create the `Channel` component with the following code:
```
import { Channel, messageActions } from "stream-chat-expo";
...
<Channel
  messageActions={(params) => {
    const actions = messageActions({ ...params });
    return actions?.filter((a) => a?.actionType !== "threadReply") ?? [];
   }}
/>
```
This will cause the following error:
![image](https://user-images.githubusercontent.com/94181463/213426197-b511464f-5bd3-4092-857f-a2d3bc460f90.png)

I believe the fix for this would be to remove `| null` from this array definition.
https://github.com/GetStream/stream-chat-react-native/blob/8e50538d2d7288f58fb39a61a957c1fc230eca2b/package/src/components/Message/utils/messageActions.ts#L55

**Expected behavior**
The return type from `messageActions` should be `MessageActionType[] | undefined`

**Comment by khushal87** [comment]
Thanks for reporting this bug, @DannyBiezen; we will look into it and fix it soon.

**Comment by atsss** [comment]
Hi Team!
I'm not sure where I should report this. but I've found something weird. I'm using version 5.9.0 and my `copyMessage` returns `undefined`. The following code lines are what I exactly ran on my local.

```codesnipet.tsx
    <SafeAreaView>
      <Chat client={chatClient} i18nInstance={streamI18n}>
        <Channel
          channel={channel}
          messageActions={(props) => {
            const { quotedReply, copyMessage, editMessage, deleteMessage, isMyMessage }  = props;
            console.log(props);
            return isMyMessage ? [quotedReply, copyMessage, editMessage, deleteMessage] : [quotedReply, copyMessage]
          }}
        >
          <View style={{ flex: 1 }}>
            <MessageList />
            <MessageInput />
          </View>
        </Channel>
      </Chat>
    </SafeAreaView>
```
then the object has `"copyMessage": undefined` in my log.  Based on [this docs](https://getstream.io/chat/docs/sdk/reactnative/guides/customize-message-actions/), the `copyMessage` can't be `undefined`. Let me know if I'm missing anything or misunderstood anything.

**Comment by ngoue** [comment]
We are also seeing the same `undefined` action for `copyMessage` that @atsss reported.

We're on version `5.11.2`.
