### ISSUE TITLE
selected video attachment in attachment picker isnt recognized as selected

### ISSUE THREAD

**Issue by megantaylor** [GetStream/stream-chat-react-native#1925]
**Describe the bug**
In iOS Simulator and on iOS device, open attachment picker and select video. Video correctly show up in the message input, but does not receive the selected overlay UI. 

Seems to be related to https://github.com/GetStream/stream-chat-react-native/pull/1440/files; the file.uri and the asset.uri don't match because file uri is using the localAssetURI value, asset uri is using the original uri value, and the check for selected tries to match asset.uri to file.uri `selectedFiles.some((file) => file.uri === asset.uri`

Selected UI seems to work on android.

**Dev environment info (please complete/provide the following information):**

    "stream-chat": "^8.3.0",
    "stream-chat-expo": "^5.8.0",

**To Reproduce**

open attachment picker and select a video

**Expected behavior**

expected to see selected UI on a selected video in attachment picker

**Comment by megantaylor** [comment]
I've patched this for myself using the changes below:

```
diff --git a/node_modules/stream-chat-react-native-core/src/components/AttachmentPicker/AttachmentPicker.tsx b/node_modules/stream-chat-react-native-core/src/components/AttachmentPicker/AttachmentPicker.tsx
--- a/node_modules/stream-chat-react-native-core/src/components/AttachmentPicker/AttachmentPicker.tsx
+++ b/node_modules/stream-chat-react-native-core/src/components/AttachmentPicker/AttachmentPicker.tsx
 
@@ -194,7 +194,7 @@ export const AttachmentPicker = React.forwardRef(
       numberOfUploads: selectedFiles.length + selectedImages.length,
       selected:
         selectedImages.some((image) => image.uri === asset.uri) ||
-        selectedFiles.some((file) => file.uri === asset.uri),
+        selectedFiles.some((file) => file.id === asset.id),
       setSelectedFiles,
       setSelectedImages,
     }));

diff --git a/node_modules/stream-chat-react-native-core/src/components/AttachmentPicker/components/AttachmentPickerItem.tsx b/node_modules/stream-chat-react-native-core/src/components/AttachmentPicker/components/AttachmentPickerItem.tsx
--- a/node_modules/stream-chat-react-native-core/src/components/AttachmentPicker/components/AttachmentPickerItem.tsx
+++ b/node_modules/stream-chat-react-native-core/src/components/AttachmentPicker/components/AttachmentPickerItem.tsx
@@ -68,7 +68,7 @@ const AttachmentVideo: React.FC<AttachmentVideoProps> = (props) => {
     // For the case of expo messaging app where you need to fetch the asset uri from asset id
     const localAssetURI = asset.id && (await getLocalAssetUri(asset.id));
     if (selected) {
-      setSelectedFiles((files) => files.filter((file) => file.uri !== asset.uri));
+      setSelectedFiles((files) => files.filter((file) => file.id !== asset.id));
     } else {
       setSelectedFiles((files) => {
         if (numberOfUploads >= maxNumberOfFiles) {
@@ -83,6 +83,7 @@ const AttachmentVideo: React.FC<AttachmentVideoProps> = (props) => {
             size: asset.fileSize,
             type: 'video',
             uri: localAssetURI || asset.uri,
+            id: asset.id
           },
         ];
       });
       
       diff --git a/node_modules/stream-chat-react-native-core/src/types/types.ts b/node_modules/stream-chat-react-native-core/src/types/types.ts
--- a/node_modules/stream-chat-react-native-core/src/types/types.ts
+++ b/node_modules/stream-chat-react-native-core/src/types/types.ts
@@ -20,6 +20,7 @@ export type File = {
   size?: number | string;
   type?: string;
   uri?: string;
+  id?: string;
 };
```

**Comment by khushal87** [comment]
Hey @megantaylor, testing this behaviour on our TypeScriptMessagingApp on iPhone 14 Pro simulator seems to work fine as it should. Can you confirm that you aren't adding customization to the existing behaviour?

<video src="https://user-images.githubusercontent.com/39884168/214226634-dde3ea7a-bdb5-4a51-8093-864e255fb65d.mp4" alt="drawing" width="200px"/>

**Comment by megantaylor** [comment]
The TypeScriptMessagingApp doesn't use the expo package, correct? I'm using "stream-chat-expo": "^5.8.0"

**Comment by khushal87** [comment]
Okay, @megantaylor, sorry for it. Can you raise a PR for it if you feel this patch fixes it, and we will be happy to try and merge it(after review and testing)?

**Comment by khushal87** [comment]
Hey @megantaylor, thanks for reporting the bug we were able to reproduce it on Expo apps. Sorry for the confusion. The patch you have suggested is valid for expo apps and breaks the implementation on Native apps. So, to fix the problem everywhere, I have added a PR and this should solve it. Please track it here #1931
