### ISSUE TITLE
How to hide/remove camera in attachment input?

### ISSUE THREAD

**Issue by ArcherEmiya05** [GetStream/stream-chat-react-native#1929]
**Describe the bug**
Is there a way to remove or hide camera icon when opening attachment section?

- Package version stream-chat-react-native ^5.7.0
- react-native 0.693
- Device/Emulator: Android SDK 22

**To Reproduce**
N/A

**Expected behavior**
Properties to remove camera option in attachment

**Screenshots**

![viber_image_2023-01-25_06-37-34-637](https://user-images.githubusercontent.com/38008900/214447974-3c641d4b-d5ca-44c7-94e2-78870a12146b.png)

**Comment by vishalnarkhede** [comment]
@ArcherEmiya05 please set `CameraSelectorIcon` prop as empty component on OverlayProvider. https://getstream.io/chat/docs/sdk/reactnative/core-components/overlay-provider/#cameraselectoricon
