### ISSUE TITLE
Accessibility / ADA Compliance

### ISSUE THREAD

**Issue by neopit** [GetStream/stream-chat-react-native#1939]
**Motivation**
We need to make all of our apps fully accessible and ADA-compliant for legal reasons.

After a couple of tries, we are not able to access some parts of the app with the keyboard and changing some components for making them accessible.

Here is a list of items:
 - The controls to view the message threads do not expose the expected button role.
 -  When the actions modal is showing the user can still tab on the element behind the modal
 - The screen reader read some hidden elements
 -  The reactions are not accessible via the keyboard (focus)
 - The list of actions on a message (after a long press) is not accessible with the keyboard

**Proposed solution**
Updating components for making them accessible and ADA compliant for screen reader and keyboard

**Acceptance Criteria**
 - components have to be compliant with Accessibility rules (reader and keyboard) and Ada-compliant (use ADA analysis tools for testing and manual tests)

**Comment by vanGalilea** [comment]
@neopit, thanks for reaching out, we will refine this and add this to our backlog. Stay tuned for additional questions!

**Comment by Thenlie** [comment]
I have run into the same issue when trying to use TalkBack on Android. Here are the things I noticed (a lot of which have been noted above):

- Talkback will read elements behind the message action and reaction modal. Content hidden behind a modal should not be announced as it is not accessible until the modal is dismissed.
- The message action modal can be dismissed by clicking on the highlighted message. This is not announced by the screen reader so a visually impaired users would likely have no idea how to close the modal.
- The message action modal can not be dismissed with a keyboard. Escape should close the modal
- Message actions are not accessible via keyboard navigation
- Reactions are not accessible via screen reader or keyboard navigation.

I am happy to provide screen recordings, reproduction steps, or anything else that would aid in understanding this issue. Would love to see some accessibility improvement here as it is crucial for users that rely on assistive technologies!

**Comment by vanGalilea** [comment]
@Thenlie, thanks for your comprehensive answer. Making our components more accessible is on our backlog. The task is relatively big, and we're investing our resources in other places at the moment. 

Are they any low-hanging fruits that we can pick up immediately?

**Comment by Thenlie** [comment]
@vanGalilea thanks for the reply! I have been trying to make a patch for my own project and struggling to do so. I am not super experienced with this native accessibility stuff so that may be the problem, but I do not see any super low hanging fruit at the moment. 

I am trying to make reactions navigable by the screen reader and allow the MessageActions to close on 'Escape'. These IMO will make the biggest impact for an assistive technology user. If I am able to make a working patch I will be sure to share it here.

Also wanted to note, I am seeing the same issues on iOS, so this doesn't appear to be an OS specific issue.

**Comment by vanGalilea** [comment]
Hey @Thenlie, thanks for your answer,  it's good to know that we have some basic accessibility in most of our RN chat SDK.
A11y is very specific and hard to implement fully, especially in a customizable chat experience like we offer.

The guidelines, in general, are also widely different across platforms. For example, the sizes, talkback attributes are differently described on iOS and Android.

From what we've done with a11y in the past in apps and overall experience, chat is one of those places where it just doesn't work out of the box. The chat SDK's UI is way too complex for it to be adequately implemented.

That said, and as mentioned earlier, we can add a11y attributes for some of our elements on your request.

Let's leave this issue open to monitor future specific a11y requests from any integrator. Related contribution is always welcome!

**Comment by khushal87** [comment]
Hey,

Thanks for reaching out. We will add this to our backlog/wishlist assess its importance and have a plan for its implementation. We don't plan to add it in the near future. I will close this ticket from here, and we will try to pick this up later in the future.

Thanks for providing us with your valuable requests and input to improve our product. 😄
