### ISSUE TITLE
ChannelList is empty despite having channels

### ISSUE THREAD

**Issue by ArcherEmiya05** [GetStream/stream-chat-react-native#1941]
**Describe the bug**
Before the channels are showing in ChannelList component but now only the loader/shimmering is what we see and becomes empty afterwards. It should also show the default EmptyStateIndicator like before. We are not sure if something was being overwritten because before we tried to set a custom preview using the ChannelList Preview props to apply swipeable gesture but even after removing it the behavior still persist no matter how many try we clean and clear the build.

**Dev environment info (please complete/provide the following information):**

- Package version stream-chat-react-native ^5.7.0
- react-native 0.693
- Device/Emulator: Android SDK 22

**To Reproduce**
```
const filters = { members: { $in: [authReducer.getStreamUser.streamId] } };
<Chat client={chatClient}>
            <ChannelList
              // PreviewAvatar={CustomPreviewAvatar}
              // PreviewTitle={CustomPreviewTitle}
              // Preview={SwipeableChannelItem}
              filters={filters}
              // options={options}
              onSelect={async (channel) => {
                // channel.delete()
                // await chatClient.deleteChannels([channel.data.cid], {hard_delete: true})
                // console.log(JSON.stringify(channel.data))
                navigation.navigate('ChatRoom', {
                  channel: channel,
                  chatData: channel.data,
                })
              }}
            />
          </Chat>
```

**Expected behavior**
Shows the channel in ChannelList component.

**Additional context**
If there is any error/warning there should be a log which we are getting before whenever we make mistake such as with query, but now there is no any error nor warning that shows.

**Screenshots**

Only shimmering card is showing

https://user-images.githubusercontent.com/38008900/215658936-97982172-0775-4aa8-b8e3-a4f6bf71345a.mp4

This default EmptyStateIndicator no longer shows as well when there is no channel related to user.
![image](https://user-images.githubusercontent.com/38008900/215659233-8ddf151f-72a7-4486-94ab-7b8257a6f66a.png)

**Comment by luisgereda** [comment]
Hi, 

Thank you for sharing this information.
We have reserved the GH repository for bug reports only.
Please, send a support request by using our support center:
https://getstream.io/contact/support/

Some of our Support Engineers will be happy to help you.

Thanks,
Luis

**Comment by ArcherEmiya05** [comment]
> Hi,
> 
> Thank you for sharing this information. We have reserved the GH repository for bug reports only. Please, send a support request by using our support center: https://getstream.io/contact/support/
> 
> Some of our Support Engineers will be happy to help you.
> 
> Thanks, Luis

Wait what? We can't report issues in repo?

**Comment by ArcherEmiya05** [comment]
@vanGalilea still not solve and no support yet, please re open this ticket. We are dealing with this issue for almost 4 days already and became a total blocker to our sprint.
