### ISSUE TITLE
Sending two images in the ChannelScreen leads to incorrect grid calculation in the Gallery component.

### ISSUE THREAD

**Issue by donaldisufi** [GetStream/stream-chat-react-native#1946]
**Describe the bug**
We are encountering an issue where sending two images as a message in the ChannelScreen leads to incorrect grid calculation by the Gallery component. The first image is aligned vertically and the second one is aligned horizontally, resulting in empty space as shown in the screenshots ⬇️.
We have not set any properties that could cause this problem, and it only occurs the first time. After going back and re-opening the Channel, the correct grid is displayed

**Dev environment info:**
- Package version: "^5.7.0",
- expo ejected version
- any device

**Screenshots**
<img width="361" alt="Screenshot 2023-02-01 at 10 34 22" src="https://user-images.githubusercontent.com/49714904/216011063-de7210c4-0932-4436-9d7a-07c516ff1831.png">
![IMG_8984](https://user-images.githubusercontent.com/49714904/216011175-aaad2d3c-d41e-4b20-a9d7-236b95da1b05.jpg)

**Comment by vanGalilea** [comment]
@donaldisufi you haven't got back to us with a repro, that's all fine.
We'll be closing this issue for now.
Please don't hesitate to contact us in the future if this issue or any questions arise.
