### ISSUE TITLE
Support for react-native-quick-sqlite v8 

### ISSUE THREAD

**Issue by billnbell** [GetStream/stream-chat-react-native#1952]
v8 beta/etc needs to be tested with Getstream.

https://github.com/ospfranco/react-native-quick-sqlite/issues/107

**Comment by vanGalilea** [comment]
@billnbell true thing thanks, we need to support this in order to support our integrators that use offline support together with RN v0.71.x and higher.

**Comment by vanGalilea** [comment]
@billnbell I have tested v8 with our typescript messaging app see [PR](https://github.com/GetStream/stream-chat-react-native/pull/2067).

Did you have any specific issues with react-native-quick-sqlite v8 in combination with our SDK?
