### ISSUE TITLE
Adding Support for React Native Web by merging with the React SDK

### ISSUE THREAD

**Issue by chen-rn** [GetStream/stream-chat-react-native#1954]
**Motivation**
Universal apps that are built with React Native and can run on both web(RNW) + mobile are becoming better each day with new technologies like Solito and Tamagui. It would be fantastic for Stream to make the react-native package also be transpile-able by react-native-web.

**Proposal: add react-native-web support without rewriting**
It may take some time to look over the entire stream-chat-react-native package and ensure that it works with React Native Web. However, given that the React SDK and the React-Native SDK have very similar component APIs. Instead of rewriting the React Native code to make it work with web, it may be easier to simply reference the React SDK when ran on the web.

**I'm starting to build something like this internally.**
We have an internal package for our monorepo named universal-streamchat.
Inside of which are a list of abc.native.tsx and abc.web.tsx files, where I'll either import + export the web SDK or the native SDK. 
And in my app, instead of importing my components/functions directly from stream, I'll import it from universal-streamchat.
RNW is smart enough to know which file to use depending on the environment.

From an outsider's perspective, this seems to be a very low-hanging way of making stream work for both web + mobile on react native!

**Comment by khushal87** [comment]
Hey @chen-rn,

Thanks for reaching out. 

We are monitoring react-native-web closely and are excited about the new innovations around it. We will add this to our backlog/wishlist to see if this feature would be helpful to more customers. I will close this ticket as this is a particular use case, and we will try to pick this up later in the future.

Thanks for providing us with your valuable requests and input to improve our product.

**Comment by izakfilmalter** [comment]
Really need web support for our app.

**Comment by sreuter** [comment]
Came here to check if RNW is currently supported. Support would be pretty much a must for us to pick up Stream as our chat platform.

**Comment by vitorcamachoo** [comment]
Any new on this?
