### ISSUE TITLE
Play received attachment audio Failed on ANDROID

### ISSUE THREAD

**Issue by amir-ibrahim** [GetStream/stream-chat-react-native#1955]
Hello I applied voice chat on my app I have an error in the received chat voice on ANDROID " the voice chat I send worked fine" 
IOS worked perfectly fine 

this is the error:
{"error": {"extra": -1010, "what": 1}}

- Package version 
"stream-chat": "^8.1.3"
"stream-chat-react-native": "^5.8.0"

- react-native or expo version
"react": "17.0.2"
"react-native": "0.68.5"

- Device/Emulator (Just Andriod)
Galaxy S21 FE 5G

Send Voice Code:

```

  const sendVoiceMessage = async uri => {
    const message = {
      created_at: new Date(),
      attachments: [
        {
          asset_url: uri,
          file_size: 200,
          mime_type: 'audio/mp3',
          title: 'test.mp3',
          type: 'audio',
          audio_length: recordTime,
        },
      ],
      mentioned_users: [],
      id: `${uuidv4()}`,
      status: 'sending',
      type: 'regular',
      user: client.user,
    };

    // Add the message optimistically to local state first.
    updateMessage(message);

    // Upload the file to cdn.
    const res = await channel.sendFile(uri, `${uuidv4()}.mp3`, 'audio/mp3');
    const {
      created_at,
      html,
      type,
      status,
      user,
      ...messageWithoutReservedFields
    } = message;

    messageWithoutReservedFields.attachments[0].asset_url = res.file;

    // Send the message on channel.
    await channel.sendMessage(messageWithoutReservedFields);
  };

```

Play the Video:
```

  const onStartPlay = async () => {
    setPaused(false);
    setLoadingAudio(true);
    await audioRecorderPlayer.startPlayer(asset_url);
    setLoadingAudio(false);

    audioRecorderPlayer.addPlayBackListener(async e => {
      if (e.currentPosition === e.duration) {
        await onStopPlay();
      } else {
        setCurrentPositionSec(e.currentPosition);
        setCurrentDurationSec(e.duration);
        setPlayTime(audioRecorderPlayer.mmssss(Math.floor(e.currentPosition)));
        setDuration(audioRecorderPlayer.mmssss(Math.floor(e.duration)));
      }
      return;
    });
  };
```

![216813295-1cf43ae8-5794-44b4-bacc-aa260964eb0d](https://user-images.githubusercontent.com/41516271/217199480-0940b7e8-95ea-4fbd-ab33-8ff0504f6a88.jpg)

**Comment by vanGalilea** [comment]
@amir-ibrahim, thanks for reaching out can you please supply us with all of the information needed as stated in the bug rapport [template](https://github.com/GetStream/stream-chat-react-native/issues/new?assignees=&labels=Needs+Triaging&template=bug_report.md&title=)?

**Comment by vanGalilea** [comment]
I see you also try to play MP4s, was that intentional, are the MP3s do work, or do you get this error with all media players?

**Comment by amir-ibrahim** [comment]
I Update the bug as the template says, I try Mp3 with no success same error
LOG  {"error": {"extra": -1010, "what": 1}}

**Comment by amir-ibrahim** [comment]
hello @vanGalilea any update

**Comment by khushal87** [comment]
Hey @amir-ibrahim, which package are you using to support audio in your app?

**Comment by amir-ibrahim** [comment]
hello @khushal87  i use "react-native-video"

**Comment by khushal87** [comment]
This issue looks relevant to the package you are using and is unrelated to our implementation/package. Please feel free to raise this issue in the `react-native-audio-recorder-player` package. Let us know if you need any other help.

According to my intuition, this has to do with codec and is a well-known issue for android devices using both of the above packages.
