### ISSUE TITLE
[Android] Inverted empty state for message list 

### ISSUE THREAD

**Issue by 1987cr** [GetStream/stream-chat-react-native#1968]
**Describe the bug**
Since last update empty state is inverted for android, probably caused by this change https://github.com/GetStream/stream-chat-react-native/pull/1964/files#diff-9bc51e90b151dbcd57ae1bc8a631e07b1ae80368242e21faabe531aa69491383R78

**Dev environment info (please complete/provide the following information):**

- stream-chat-react-native 5.11.0
- react-native 0.70.7

**Screenshots**
<img src="https://user-images.githubusercontent.com/4684912/218517702-cd2291b6-556f-4cb1-a464-8487178700c6.png"  width="3200" />

**Comment by 1987cr** [comment]
@santhoshvai can we reopen this one? I think the android workaround it's kinda breaking for other props as well, if I pass `ListEmptyHeader` or `ListEmptyFooter` they are also inverted, but since those components are being declared on our side of things, I'd need to apply the android workaround manually on our side, which it's kind of leaky, because if we do it, the moment the workaround it's removed from stream code then we'd get inverted components again.

**Comment by 1987cr** [comment]
Also inline date separator appears out of order:

- Without workaround:
<img src="https://user-images.githubusercontent.com/4684912/219035794-15c720f1-6728-485b-8006-4a09807f44d9.png"  width="300" />

- With workaround
<img src="https://user-images.githubusercontent.com/4684912/219035840-b50a1d4f-d7a9-4ba5-88d9-2f65ade3274c.png"  width="300" />

**Comment by santhoshvai** [comment]
@1987cr will fix the ListEmptyHeader and ListEmptyFooter asap, thanks for mentioning here. These are stuff that we badly missed to verify
