### ISSUE TITLE
Message Copy in MessageList not working

### ISSUE THREAD

**Issue by TaharS** [GetStream/stream-chat-react-native#1969]
**Describe the bug**
On long press of a message, Copy isn't available.

**Dev environment info (please complete/provide the following information):**

```
➜  SampleApp git:(develop) ✗ yarn list | grep chat
├─ stream-chat-react-native-core@5.10.0
│  └─ stream-chat@8.2.1
├─ stream-chat-react-native@5.10.0
│  ├─ stream-chat-react-native-core@5.10.0
│  └─ stream-chat-react-native-core@5.10.0
│     └─ stream-chat@8.2.1
├─ stream-chat@8.2.1
```
- iOS 15 - iPhone 14 Emulator

**To Reproduce**

1. Open Sample App locally
2. Select a channel
3. Long press a message
4. Observe

**Expected behavior**
The `Copy` option is available on long press for a message

**Additional context**
n/a

**Screenshots**
<img width="944" alt="Screen Shot 2023-02-13 at 3 42 33 PM" src="https://user-images.githubusercontent.com/10080564/218599382-67a9ac30-43e1-4d28-bf26-487c21952615.png">

**Comment by khushal87** [comment]
Hey @TaharS, we made the `@react-native-clipboard/clipboard` dependency optional recently. Can you confirm if you have the dependency in your project locally? If not, please add it and the option for the Copy Message to start appearing.

**Comment by TaharS** [comment]
Yes! thank you for that.
As a heads up, I am using the example apps, which none of them has it as dependency :) might want to add it for the full experience
Thanks a lot
