### ISSUE TITLE
Crash caused by KeyboardAvoidingView

### ISSUE THREAD

**Issue by capacitivellc** [GetStream/stream-chat-react-native#197]
**Describe the bug**
Randomly while resuming our app using the standard Stream components we we get a crash caused by KeyboardAvoidingView.

![IMG-20200420-WA0001](https://user-images.githubusercontent.com/35151612/79774728-0e2bda80-82e8-11ea-90fa-a2c8bfe368ab.jpg)

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native/stream-chat-expo)
stream-chat-react-native

- react-native or expo version
RN 0.10.0

- Device/Emulator (android/ios) and OS version
Seen on a variety of phones.

**To Reproduce**

Difficult to repro but basically, background the app from a chat conversation, later resume.

**Expected behavior**
Adding or removing callbacks should always be handled withour crashing.

*Additional context**

**Screenshots**

**Comment by vishalnarkhede** [comment]
@capacitivellc thanks for brining it up. I will take a look and get back to you as soon as possible. Some extra checks around this functionality should fix the issue :)

**Comment by vishalnarkhede** [comment]
Hey @capacitivellc  fix has been published on `0.10.2`. Please reopen the issue if you still see the error :)
