### ISSUE TITLE
Profile Image & Group Image as React Native Element

### ISSUE THREAD

**Issue by JSimai** [GetStream/stream-chat-react-native#1975]
**Motivation**
First of all, Stream Chat is elite, love what you're doing here. This is a really niche problem and completely understand if it is just straight up disregarded. My users' profile images are not just singular images and neither are my group images in my app. Rather they are 5 images laid on top of eachother (it's a customisable outfit on a little character, each item is an image), and a colour background with an emoji on top respectively. Therefore, I can't replicate them as user and group images in the stream chat component of my app as it only supports a single image.

At the moment, the user image is just one of the 5 images that are laid on eachother, and the group image is blank!

**Proposed solution**
I was hoping that we could replace the images with React Native elements. Like a View with Text inside. Of course most would just be an Image, so it shouldn't make the usual process any harder, just pass in an Image element rather than just the source. This would be elite, but again I have no expectations! 

**Acceptance Criteria**
The ability to use React Native elements as user and group images. If this solution is unachievable, would love some suggestions on how to improve my situation!

**Comment by khushal87** [comment]
Hey @JSimai, are you open to using the component from React Native elements, or do you want us to implement the same on our SDK? I think it's possible to customize the channel avatar component by passing a custom component in the [PreviewAvatar](https://getstream.io/chat/docs/sdk/reactnative/core-components/channel-list/#previewavatar) prop to the ChannelList.

As far as I understand, you are looking to change the avatar for channels in the ChannelList. Please correct me if I am wrong.

**Comment by JSimai** [comment]
Hello! I'm so sorry for taking so long to reply. Some unexpected circumstances came up! I'm looking to change both the preview avatar and the group avatar in the chat screen, as well as potentially the user avatars. 

I was hoping that instead of putting in custom components as, like you said for example, the PreviewAvatar prop, we could pass a ReactNative element as the 'image' when creating both channels and users. Otherwise, if I were to store those ReactNative elements that I would like to input as the images, I would have to somehow link users and channels to my database and sort through them on each render to find the correct react native element to place in the PreviewAvater prop and the other applicable props. 

Does that make sense?

**Comment by khushal87** [comment]
Although I am not what exactly you are trying to achieve, from what I understand, we currently don't have a better way to go with this; we think `PreviewAvatar` should be self-sufficient for this case, and you can add your custom logic to achieve what you want unless something is complex in your use-case.

**Comment by JSimai** [comment]
PreviewAvatar and MessageAvatar worked a treat for me as I was able to use the context objects to find the details that related to my database and then fetched the relevant data and returned it in the components! Made it a little bit complicated but works just fine. Thanks!

**Comment by khushal87** [comment]
That is amazing @JSimai!
