### ISSUE TITLE
Slow and inconsistent KeyboardCompatibleView behavior

### ISSUE THREAD

**Issue by capacitivellc** [GetStream/stream-chat-react-native#198]
**Describe the bug**
KeyboardCompatibleView used by the MessageList, MessageInput components is slow to open (500ms) and very very frequently does not work. That is to say the MessageInput renders below the native keyboard. Some times navigation back from the conversation and opening it again helps, but not consistently.

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native/stream-chat-expo)
stream-chat-react-native

- react-native or expo version
RN 0.10.0

- Device/Emulator (android/ios) and OS version
Primarily ios

**To Reproduce**

1. Navigate to a channel with MessageList, MessageInput components

**Expected behavior**
KeyboardCompatibleView consistently and quickly renders above the native keyboard.

**Additional context**

**Screenshots**

**Comment by vishalnarkhede** [comment]
Hey @capacitivellc thanks for bringing this up. Keyboard functionality has always been a bit little crumbly. It heavily depends on keyboard events and layout calculations.

Please find more details [here](https://github.com/GetStream/stream-chat-react-native/blob/master/docs/cookbook.md#keyboard).

You can tweak the animation duration of KeyboardCompatibleView easily. Please checkout this example from cookbook - https://github.com/GetStream/stream-chat-react-native/blob/master/docs/cookbook.md#keyboard

As you said, it a little tricky to find pattern with this issue. I will try to spend some time on this either this week or next week and get back to you. I will let you know :)

**Comment by Ingibjorg** [comment]
@vishalnarkhede @capacitivellc I'm experiencing the same issue. This issue for when the keyboard hides the MessageInput only happens for me in Release mode. The KeyboardCompatibleView works fine in debug mode. @vishalnarkhede I'm able to reproduce the issue with your example code: https://github.com/GetStream/stream-chat-react-native/blob/master/examples/NativeMessaging/App.js#L103

**Comment by WitleyInc** [comment]
I'm having the same issue as well. The MessageInput component renders behind the native keyboard because the MessageList occupies too much space.

**Comment by vishalnarkhede** [comment]
Hey @capacitivellc @WitleyInc @Ingibjorg , I have published some improvements/fixes in keyboard functionality in `0.10.2`. Please let me know if this issue is fixed for you on the latest version :)

**Comment by Ingibjorg** [comment]
Thank you for the quick response @vishalnarkhede. I can confirm that version `0.10.2` fixes the issue.

**Comment by WitleyInc** [comment]
@vishalnarkhede Thank you for the quick response. However, the fix is still not working on the latest version. When I navigate to the screen with the `Channel Component` containing the `MessageList` and `MessageInput` components, the keyboard is still being pushed under the screen by the `MessageList`. However, I notice that if I click and drag the home indicator of the iPhone X, then the `MessageInput` component is being pushed back to its correct position and the keyboard functionality works perfectly fine.   
![Simulator Screen Shot - iPhone 11 - 2020-04-29 at 12 25 37](https://user-images.githubusercontent.com/47505922/80638345-24871400-8a15-11ea-9e87-20f149eceda0.png)
![Simulator Screen Shot - iPhone 11 - 2020-04-29 at 12 30 08](https://user-images.githubusercontent.com/47505922/80638382-323c9980-8a15-11ea-932b-7950e7119253.png)
![Simulator Screen Shot - iPhone 11 - 2020-04-29 at 12 30 16](https://user-images.githubusercontent.com/47505922/80638413-3c5e9800-8a15-11ea-9a87-32bbb3eeb329.png)

**Comment by capacitivellc** [comment]
@vishalnarkhede Thanks for the update. I can't really tell if this resolved our issue. To be clear I am using the CustomizedKeyboardView now with low 200ms animation delay. On all iphone simulators the keyboard seems to pop up quickly. However on real devices it is still very slow. I suspected something was causing re-renders on the chat screen but when I look at perf monitor the JS drops to 3 every time I open a chat, while the UI thread stays at 60. If I wait for the JS thread to return to 60, no keyboard issue is noticed.

**Comment by vishalnarkhede** [comment]
@WitleyInc I think you are referring to different issue than @capacitivellc . In @capacitivellc 's case, when you open the keyboard, channel height doesn't get adjusted properly. Please correct me if I am wrong. Just want to make sure I understand both of your issues correctly

**Comment by WitleyInc** [comment]
@vishalnarkhede I apologize for misunderstanding the issue. The channel height adjusts properly when I open the keyboard and the animation is fine as well. My issue is that the `MessageList` component's initial height when the component is mounted is larger than it is supposed to be, and the `MessageInput` component is being pushed outside of the screen. However, dragging the home indicator in iPhone 11 simulator (or double tapping the home button for devices like iPhone 6) will readjust the `MessageList` height properly so that the `MessageInput` is being pushed up to its correct position, which is a really strange bug.

**Comment by WitleyInc** [comment]
@vishalnarkhede One thing I have also noticed is that the`MessageInput` component is not being pushed out of the screen if there's no message in the channel.

**Comment by vishalnarkhede** [comment]
Hey @WitleyInc @capacitivellc we are investigating these issues. We will get back to you soonish.

**Comment by virdesai** [comment]
@WitleyInc I think the issue may be safe area view related. using the tutorial code, I was able to recreate your issue with the message input being at the bottom of the screen with the notch. I upgraded some packages and converted class to functional components but overall this made the render look correct

package.json
```
{
  "name": "StreamChatReactNativeExample",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/masked-view": "0.1.10",
    "@react-native-community/netinfo": "5.8.1",
    "@react-navigation/native": "5.3.0",
    "@react-navigation/stack": "5.3.3",
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-document-picker": "3.4.0",
    "react-native-gesture-handler": "1.6.1",
    "react-native-image-picker": "2.3.1",
    "react-native-reanimated": "1.8.0",
    "react-native-safe-area-context": "1.0.0",
    "react-native-screens": "2.7.0",
    "stream-chat-react-native": "0.10.2"
  },
  "devDependencies": {
    "@babel/core": "7.6.2",
    "@babel/runtime": "7.6.2",
    "@react-native-community/eslint-config": "0.0.5",
    "babel-jest": "24.9.0",
    "eslint": "6.5.1",
    "jest": "24.9.0",
    "metro-react-native-babel-preset": "0.58.0",
    "react-test-renderer": "16.11.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
```
and then App.js
```
import React from 'react';
import {View, YellowBox} from 'react-native';
import {StreamChat} from 'stream-chat';
import {
  Chat,
  Channel,
  MessageList,
  MessageInput,
  ChannelPreviewMessenger,
  ChannelList,
} from 'stream-chat-react-native';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
import {NavigationContainer} from '@react-navigation/native';
import {createStackNavigator} from '@react-navigation/stack';

YellowBox.ignoreWarnings([
  'componentWillReceiveProps has been renamed',
  'Non-serializable values were found in the navigation state',
]);

const chatClient = new StreamChat('jc5u46m9ayr9');
const userToken =
  'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiYW5jaWVudC1zbW9rZS04In0.IBmfP7tYYeNWrsla9J-r0tnCotLb9E1jJlOyP8d4_O8';

const user = {
  id: 'ancient-smoke-8',
  name: 'Ancient smoke',
  image:
    'https://stepupandlive.files.wordpress.com/2014/09/3d-animated-frog-image.jpg',
};

chatClient.setUser(user, userToken);

const ChannelListScreen = ({navigation}) => {
  const insets = useSafeAreaInsets();
  return (
    <View style={{paddingBottom: insets.top}}>
      <Chat client={chatClient}>
        <View style={{display: 'flex', height: '100%', padding: 10}}>
          <ChannelList
            filters={{type: 'messaging', members: {$in: ['ancient-smoke-8']}}}
            sort={{last_message_at: -1}}
            Preview={ChannelPreviewMessenger}
            onSelect={channel => {
              navigation.navigate('Channel', {
                channel,
              });
            }}
          />
        </View>
      </Chat>
    </View>
  );
};

const ChannelScreen = ({
  route: {
    params: {channel},
  },
}) => {
  const insets = useSafeAreaInsets();
  return (
    <View style={{paddingBottom: insets.top}}>
      <Chat client={chatClient}>
        <Channel client={chatClient} channel={channel}>
          <View style={{display: 'flex', height: '100%'}}>
            <MessageList />
            <MessageInput />
          </View>
        </Channel>
      </Chat>
    </View>
  );
};

const Stack = createStackNavigator();

export default class App extends React.Component {
  render() {
    return (
      <NavigationContainer>
        <Stack.Navigator initialRouteName='ChannelList'>
          <Stack.Screen
            component={ChannelListScreen}
            name='ChannelList'
            options={{
              headerTitle: 'Awesome Conversations',
              headerTitleStyle: {
                fontWeight: 'bold',
              },
            }}
          />
          <Stack.Screen
            component={ChannelScreen}
            name='Channel'
            options={({route}) => ({
              headerBackTitle: null,
              headerTitle: route.params.channel.data.name,
              headerTitleStyle: {
                fontWeight: 'bold',
              },
            })}
          />
        </Stack.Navigator>
      </NavigationContainer>
    );
  }
}
```

**Comment by vishalnarkhede** [comment]
@WitleyInc @capacitivellc do you still need help with this issue?

**Comment by WitleyInc** [comment]
Hello,

Yes, this item can be closed.

Cheers,
The Witley Team

On Jun 26, 2020, at 10:49 PM, Vishal Narkhede <notifications@github.com> wrote:

﻿

@WitleyInc<https://github.com/WitleyInc> @capacitivellc<https://github.com/capacitivellc> do you still need help with this issue?
