### ISSUE TITLE
Channel level customisation of the `OverlayReactions` component

### ISSUE THREAD

**Issue by aharwood9** [GetStream/stream-chat-react-native#1980]
**Motivation**

We have a use case when we want only group admins to be able to see the channel members for privacy reasons on certain channels. So far Stream provides the ability to do this in all the places that name/profile picture would appear with the exception of within the `OverlayReactions` component. You can currently customise the avatar but the name will still appear (to the best of my knowledge). 

We could always turn off Reactions all together to protect against this but reactions are super useful!

**Proposed solution**

We would like to be able to supply a custom `OverlayReactions` component to the `Channel` component, following a very similar pattern to the `OverlayReactionList` component. 

**Acceptance Criteria**

1. Supply a custom component that takes `OverlayReactionsProps` to the `Channel` component. 
2. See this custom component render in place of the default `OverlayReactions` component

**Comment by aharwood9** [comment]
P.S. I know you guys are v busy and have a lot of requests so if the proposed solution is reasonable, I am happy to do this myself and open a PR 👍

**Comment by khushal87** [comment]
Hey, @aharwood9, we already have the capability to override the overlay reactions using the `OverlayReactions` prop of the `OverlayProvider` component. You can find the documentation [here](https://getstream.io/chat/docs/sdk/reactnative/core-components/overlay-provider/#overlayreactions). I think this is what you are looking for. Please feel free to reach us with any queries.

**Comment by aharwood9** [comment]
Yes, you can customise at the `OverlayProvider` component level but you don't have access to `channel` properties. So you can't style it specifically for each `channel`. You can only style it globally. For our use case, we want to use the default for the majority of channels but for some, we want to hide the name and avatar for privacy reasons. 

Thus, I would imagine we need to have `OverlayReactions` as a prop to the `Channel` component.

**Comment by khushal87** [comment]
That's not possible at an SDK level, in my opinion, although I understand your use case; the OverlayProvider wraps the Channel and can provide all the context to the application. Most overlay-related props are confined to OverlayProvider, so this doesn't look like a feasible solution. And even if we do it at this stage it will be a big change. What do you think about this? @vanGalilea

**Comment by aharwood9** [comment]
Damn, I was hoping that it would be possible as `OverlayReactionList` is both a prop to `Channel` and `OverlayProvider`. So supply to the `Channel` and then pass through to the `useCreateMessagesContext` which (I think) updates the `useMessageOverlayContext` which is finally used within `MessageOverlay` to supply the custom component. 

This is how I understand it for the `OverlayReactionList` so I would want to repeat this pattern for `OverlayReactions`. I could be wrong tho?

**Comment by vanGalilea** [comment]
> That's not possible at an SDK level, in my opinion, although I understand your use case; the OverlayProvider wraps the Channel and can provide all the context to the application. Most overlay-related props are confined to OverlayProvider, so this doesn't look like a feasible solution. And even if we do it at this stage, it will be a big change at an API level. What do you think about this? @vanGalilea

Hey @aharwood9, you can achieve the behavior you want by doing the following:

Make sure you have app state by means of any kind of state management logic, I chose the simplest IMHO, which is Context.
```
const AppContext = React.createContext({} as AppContextType);
const useAppContext = () => React.useContext(AppContext);

const App = () => {
  const [channel, setChannel] = useState();

  return (
        <AppContext.Provider value={{ channel, setChannel}}>
         ...
        </AppContext.Provider>
  );
};
```
Make sure to use `setChannel` when selecting a spec. channel in the ChannelList
```
<ChannelList
     onSelect={(channel) => {
        setChannel(channel);
        // navigation if needed etc.
     }}
/>
```

Render the reactions list and apply some business logic by overriding the `OverlayProvider`'s `OverlayReactions` prop:

```
const App = () => {
  const [channel, setChannel] = useState();

  return (
        <AppContext.Provider value={{ channel, setChannel}}>
           <OverlayProvider
              OverlayReactions={({ reactions }) => {
                const { channel } = useAppContext();
               
                // every channel of a certain type will have a different reaction etc.

                if (channel?.type === 'some-type') {
                  return reactions.map((reaction) => {
                    return <Text>{reaction.image}</Text>;
                  });
                }
              }}
            >
              <Chat client={chatClient} i18nInstance={streami18n}>
                   {{YOUR_APP_SCREENS}}
              </Chat>
          </OverlayProvider>
        </AppContext.Provider>
  );
};
```

Please let me know if it works for you or may you have any questions!

**Comment by vanGalilea** [comment]
More info about how to customize reactions can be found in our [docs](https://getstream.io/chat/docs/sdk/reactnative/guides/message-customization/#message-with-custom-reactions)

**Comment by aharwood9** [comment]
Thanks, @vanGalilea. We have considered doing that but involved moving around a couple of our different contexts as our chatContext is much lower in the stack than the `OverlayProvider` and didn't want to add a whole new context just for this. 

We just thought the improved customisation may be something you are open to and others may find this helps as well, especially as I thought it might follow an existing pattern - plus we could contribute as well rather than adding to your ever-growing backlog 😄 

Happy to close this and we will figure out a solution if that works best for you. Appreciate your support 🙌

**Comment by khushal87** [comment]
Thanks @aharwood9 😄
