### ISSUE TITLE
How to filter channels and users at the same time

### ISSUE THREAD

**Issue by cleandevcode** [GetStream/stream-chat-react-native#1981]
Hello.

My work env:

```
"react-native" : "0.64.3",
"stream-chat": "7.1.0",
"stream-chat-react-native" : "^5.5.0"
```

My code:

```
import { ChannelList } from 'stream-chat-react-native';

...

const channelFilters = {
  type : `messaging`,
  members: { $in : [userID] },
  member_counts: { $eq: 2 },
  joined: { $eq: true }
}

<ChannelList 
  filters={channelFilters}
/>
```

Btw my goal is to filter channels by user name.
So filter the above lists by user name. 
When I checked the documentation, there is a way to filter by user name or name.

Btw `ChannelFilter` components seems only have the filter features by `Channel`, not by `User`.
But are there any ways to implement this feature in `ChannelList` Component in React native?
Or need to create a customized ChannelList component?

Thanks.

**Comment by khushal87** [comment]
Hey @cleandevcode, if I understand your question correctly are you looking for channels in which certain users are present? Sorry but the description you have added is unclear.

**Comment by cleandevcode** [comment]
@khushal87 Thanks for your response.
You are right. I am looking for channels in which certain users are present.

**Comment by khushal87** [comment]
Passing the `members` filter in the ChannelList will fetch you that. I see that you are already doing it; what issue are you facing?

An example:
```
members: { $in: [username] },
```

**Comment by cleandevcode** [comment]
You mean this?
```
const channelFilters = {
  type : `messaging`,
  **members: { $in : [userID, _searchKey_] },**
  member_counts: { $eq: 2 },
  joined: { $eq: true }
}
```

**Comment by khushal87** [comment]
Can you try?

```
const channelFilters = {
  type : messaging,
  members: { $in : [userID] }
  member_counts: { $eq: 2 },
}
```

where `userID` is the member user id for whose channels you are looking for.

**Comment by cleandevcode** [comment]
Yes, I already used the channel filter like your code.
Good so far.
Btw there is another feature to filter this current channels by search key.
<img width="349" alt="Screen Shot 2023-02-20 at 11 12 40 PM" src="https://user-images.githubusercontent.com/52365167/220273556-c24d10ae-78da-4bde-b94e-85da25838cf6.png">
<img width="351" alt="Screen Shot 2023-02-20 at 11 12 52 PM" src="https://user-images.githubusercontent.com/52365167/220273596-d616fd6c-edbf-4dc5-86c1-4859d709c78b.png">

**Comment by khushal87** [comment]
Search isn't supported by default for now, so you will have to implement it on your own. You can take the help of this guide to query the API to get the results:

https://getstream.io/chat/docs/javascript/query_channels/?language=javascript#channel-queryable-built-in-fields

**Comment by cleandevcode** [comment]
Okay thanks.

**Comment by khushal87** [comment]
> Okay thanks. Is there any plan to implement this user filter as well in the future?

This can be done by users easily, You can use the guide above to refer to the channel filters and get the data of relevant channels in the query and once you have the data the ChannelList will be updated automatically. I am not sure what's not working here. Its all about adding appropriate filters.
