### ISSUE TITLE
Import recycle warnings

### ISSUE THREAD

**Issue by neopit** [GetStream/stream-chat-react-native#1990]
**Describe the bug**

There is some recycling warning 

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: ../../node_modules/_pnpm/react-native-stream@0.1.9/node_modules/react-native-stream/src/stream.js -> ../../node_modules/_pnpm/react-native-stream@0.1.9/node_modules/react-native-stream/src/_stream_readable.js -> ../../node_modules/_pnpm/react-native-stream@0.1.9/node_modules/react-native-stream/src/stream.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: ../../node_modules/_pnpm/react-native-stream@0.1.9/node_modules/react-native-stream/src/stream.js -> ../../node_modules/_pnpm/react-native-stream@0.1.9/node_modules/react-native-stream/src/_stream_writable.js -> ../../node_modules/_pnpm/react-native-stream@0.1.9/node_modules/react-native-stream/src/stream.js

**To Reproduce**
Run an app with Stream Chat and check the logs

**Expected behavior**
No warning during the imports

**Package version**
v 5.11.2

**Comment by khushal87** [comment]
Hey @neopit, We do not have or support any package, namely - [react-native-stream](https://www.npmjs.com/package/react-native-stream). Why do you have it in your app?

From the version and the name from `/node_modules/_pnpm/react-native-stream@0.1.9,` I see you are using the package as mentioned above and is not related to Stream Chat React Native SDK.

**Comment by neopit** [comment]
Hi @khushal87, you are right, my bad. This is not the same library.
I am closing the issue.
