### ISSUE TITLE
Offline support breaks when using React Native Debugger

### ISSUE THREAD

**Issue by ChristopherGillis** [GetStream/stream-chat-react-native#1993]
**Describe the bug**
When using offline support, if you use Remote JS debugger, with React Native Debugger, you will see an error.

**Dev environment info (please complete/provide the following information):**

- Package version: stream-chat-react-native@5.11.2
- iOS

**Expected behavior**
Without Remote JS debugger, no errors. When I switch to remote debugger I see an error.

**Additional context**
```Error: Please install "react-native-quick-sqlite" package to enable offline support```

**Screenshots**
![IMG_2958](https://user-images.githubusercontent.com/8119548/222837576-35e01afa-0320-4e2c-9547-0a6137c71945.PNG)

**Comment by ChristopherGillis** [comment]
Related: https://github.com/GetStream/stream-chat-react-native/issues/1730#issuecomment-1345421310

**Comment by vanGalilea** [comment]
@ChristopherGillis, thanks for reaching out, just to be 100% sure. Have you installed `react-native-quick-sqlite`?

**Comment by ChristopherGillis** [comment]
Yes. As per docs

**Comment by vanGalilea** [comment]
I received the same issue when `react-native-quick-sqlite` v8 is installed, the issue might be related

**Comment by vanGalilea** [comment]
@ChristopherGillis we have triaged this issue.

This error is caused by an error that originates in `react-native-quick-sqlite`.

We have unintentionally suppressed it, which resulted in the above-mentioned error that has a misleading message.

This issue will be sorted in this [PR](https://github.com/GetStream/stream-chat-react-native/pull/2067)

N.B. The original error states:
```
ceptionsManager.js:158 Error: Failed to install react-native-quick-sqlite: React Native is not running on-device. QuickSQLite can only be used when synchronous method invocations (JSI) are possible. If you are using a remote debugger (e.g. Chrome), switch to an on-device debugger (e.g. Flipper) instead.
r
```

**Comment by ChristopherGillis** [comment]
Very helpful, thank you!
