### ISSUE TITLE
Android - Initial thread message rendered upside down

### ISSUE THREAD

**Issue by mishkeTz** [GetStream/stream-chat-react-native#1995]
**Describe the bug**
The initial message in thread view is rendered upside down.

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native): 5.11.2
- react-native: 0.63.4
- Device/Emulator (android/ios) and OS version: **android 13** emulator & real device
 
**To Reproduce**

- Thread reply onto the message
- Open thread

**Expected behavior**
A message is displayed correctly and not upside down.

**Additional context**
This affects all types of initial messages: text or attachment;

**Screenshots**
<img width="443" alt="Screenshot 2023-03-06 at 22 09 28" src="https://user-images.githubusercontent.com/15350199/223231428-00bbe554-5894-4168-a123-9d84d7515c60.png">

<img width="399" alt="Screenshot 2023-03-06 at 18 21 24" src="https://user-images.githubusercontent.com/15350199/223184167-666c2346-8751-4026-b134-5e043c727dcf.png">

**Comment by khushal87** [comment]
Hey @mishkeTz, is this android 13 only issue, or do you see this everywhere? If you see it everywhere, please share your snippet of the implementation/usage of the `Thread` component.

**Comment by mishkeTz** [comment]
@khushal87 Only Android 13.
On other versions looks fine, and also on iOS looks fine.

**Comment by santhoshvai** [comment]
Hey @mishkeTz I was not able to reproduce this on 5.11.2

[this bug should have been fixed on 5.11.2](https://github.com/GetStream/stream-chat-react-native/pull/1978#issuecomment-1431661832). Could you please clean your lock file and install again. Maybe you are stuck on a previous version.

**Comment by mishkeTz** [comment]
@santhoshvai Sorry, my bad. I had the wrong version in node modules. Thanks! :)
