### ISSUE TITLE
Error building my project when including flipper-plugin-stream-chat-react-native

### ISSUE THREAD

**Issue by dannyBies** [GetStream/stream-chat-react-native#1999]
**Describe the bug**

When I run `npx tsc --noEmit` I get the following error.
![image](https://user-images.githubusercontent.com/3967506/224027266-37f8ce69-85b2-42c1-829d-f74d3f241217.png)

**Dev environment info (please complete/provide the following information):**

- Package version stream-chat-expo - 5.11.2
- react-native or expo version - Expo SDK 48
- Device/Emulator (android/ios) and OS version - N/A

**To Reproduce**

1. Include  `<DebugContextProvider useFlipper={useFlipperStream}>`
2. Run `npx tsc --noEmit`

**Expected behavior**
No TypeScript errors.

**Additional context**
It seems `receiveEventParams` has been removed in this commit even though it's still referenced in `flipper-plugin-stream-chat-react-native`
https://github.com/GetStream/stream-chat-react-native/commit/268c99cd88b5740e6e1f5eeb6a4d7e731d21289b#diff-962412880f53a3c6af049a2312f67d20dc020c57f021ccde7aa9056c0ecd1769L7

**Comment by khushal87** [comment]
Hey @dannyBies, thanks for reporting this issue to us. This looks like a genuine issue, and we might have overlooked that the `receiveEventParams` was removed. This has been fixed in the dev tools repo through a PR. Lets wait for a merge and then i will create a release and ask you to test it. Thanks 😄

**Comment by khushal87** [comment]
I am closing this issue in favour of the `1.1.0` release in the repo https://www.npmjs.com/package/stream-chat-react-native-devtools.

**Comment by dannyBies** [comment]
That's great - thanks for fixing this so quickly, it's much appreciated!
