### ISSUE TITLE
Message List does not update

### ISSUE THREAD

**Issue by esha-konstant** [GetStream/stream-chat-react-native#2002]
**Describe the bug**
The real-time chat does not work properly. Often, the Message list of one of the user stops updating. The behaviour is seen on multiple devices including both Android and iOS.

**Dev environment info (please complete/provide the following information):**

- Package version - stream-chat-react-native - v5.11.2
- react-native version - v0.66.5
- Device/Emulator (android / iOS) and OS version - Pixel 4 Android 13, Pixel 3A Android 12, iPhone 14 Pro iOS 16, iPhone 8 iOS 16

**To Reproduce**
Steps to reproduce the behaviour:

1. Create a channel with 2 users.
2. Start chatting in that thread.
3. On one of the device, put the app to background, and re-open from background, and while it shows "Reconnecting", quickly send a message from the other device.
4. Repeat this process several times.
5. You should observe that the Channel List stops getting updated on one of the user.

**Expected behaviour**
The real-time chat should always work as expected. The users in the chat must immediately receive messages.

**Additional context**
The watcher and listeners remain connected, when this behaviour is observed.

**Videos**

https://user-images.githubusercontent.com/84867241/224680919-3a7546dc-9c69-4200-b85c-1fecc2699b49.mp4

https://user-images.githubusercontent.com/84867241/224680956-53a88cf8-558b-48ff-a3df-9769486a8b5d.mp4

**Comment by vanGalilea** [comment]
@esha-konstant tnx for reaching out. We solved a very similar [issue](https://github.com/GetStream/stream-chat-react-native/pull/1943) in the past ([v5.9.1](https://github.com/GetStream/stream-chat-react-native/releases/tag/v5.9.1)).

Yet you're using `v5.11.2` very peculiar 👀. can you please share

**Comment by MxBM** [comment]
I've been encountering this a few times as well. I've been wondering if this was a web socket issue?

**Comment by santhoshvai** [comment]
@esha-konstant @MxBM can you please let us know if  offline support enabled?

**Comment by ertucaglar** [comment]
My experience: if offline support is active, the message list is not updated or the unread count information is not updated. We also tried turning the WS connection on/off manually, but when we turn off offline support, everything goes back to normal.

react-native: 0.64.3
stream-chat-react-native: 5.12.0

**Comment by santhoshvai** [comment]
@ertucaglar 

Could you try out `v5.15.0-beta.6`, we have refactored how the message list updates on offline support and this should not be happening

**Comment by arthurgeron-work** [comment]
> v5.15.0-beta.6

It works for me on `5.13.0` but only for new messages, if the latest message is delete it does not update the listing.

**Comment by jckyeh** [comment]
Also experiencing this issue with inaccurate unread count when offline support is active.

**Comment by khushal87** [comment]
Is this issue still relevant?

**Comment by khushal87** [comment]
Closing this issue due to a long time of inactivity. Please feel free to reopen it if it's still relevant. Thanks 😄
