### ISSUE TITLE
MessageList does not allow caller to get the ref of the underlying FlatList

### ISSUE THREAD

**Issue by cenzovit** [GetStream/stream-chat-react-native#201]
**Describe the bug**
It is not possible to safely get a reference to the underlying FlatList of MessageList (in order to programmatically scroll the view).

**To Reproduce**

1. Attempt to pass additionalFlatList prop to MessageList with ref key set. 
2. Send a message and see that MessageList dangerously calls scrollToIndex on it's own internal (and now not defined) ref to the FlatList.

**Expected behavior**
I would expect the ability to get a reference to the FlatList without losing/overriding the default scroll functionality.

**Comment by vishalnarkhede** [comment]
@cenzovit I have added a prop `setFlatListRef` prop to ChannelList and MessageList. on `0.10.2` .Please use it instead to get access to ref of FlatList

```
<ChannelList
 setFlatListRef={(ref) => {
   // Use ref for your own good
 }}
/>
```
