### ISSUE TITLE
Performance is inversely proportional to number of active users

### ISSUE THREAD

**Issue by tj-mc** [GetStream/stream-chat-react-native#2013]
**Describe the bug**
Heavy use of contexts is triggering many expensive re-renders, even when nothing is visually changing.
The more users join the chat, the worse performance is. In our app, it is most busy on Saturdays, and users complains most about performance on Saturday.

From profiling, I can see that even though no new messages are received, the screen is re-rendering very often. I have checked our implementation thoroughly, and can see that the renders are triggered from inside the Get Stream components.

JS FPS is constantly between 0 and 5, even on powerful devices. This leads to freezing, animation stuttering, and sometimes the JS engine completely stops responding.

I believe may be due to context state that keeps track of whenever a user enters or leaves a channel, and when users start typing. Even though have no typing indicators or anything to show the number of users, re-renders still occur. Please see attached screenshots and profiling sample. I profiled for the shortest time possible, which was still a few seconds due to lag.

Unfortunately we had to implement our own chat due to these issues. Thought I could help out by passing these findings upstream 🙏 Thanks for your great API and product!

**Dev environment info (please complete/provide the following information):**

- Package version 
 - "stream-chat-react-native": "^5.9.1",
 -     "react-native": "0.69.7",

- Device/Emulator: All

**To Reproduce**

1. Go to Channel
2. Start Profliing
3. Start typing as another user
4. Observer re-renders that update nothing on screen

**Expected behavior**
Screen re-renders only when there is a visual change

**Additional context**

**Screenshots**
<img width="2142" alt="Screen Shot 2023-03-16 at 2 46 51 pm" src="https://user-images.githubusercontent.com/46665295/225517947-4339a3aa-cac6-47f0-977c-8d2b7366043e.png">
<img width="387" alt="Screen Shot 2023-03-16 at 2 49 14 pm" src="https://user-images.githubusercontent.com/46665295/225517960-fb2e60d5-959f-4299-a546-4ee7e8acb45a.png">

[profiling-data.16-03-2023.14-47-00.json.zip](https://github.com/GetStream/stream-chat-react-native/files/10986781/profiling-data.16-03-2023.14-47-00.json.zip)

**Comment by vanGalilea** [comment]
@tj-mc, thanks for reaching out and describing this performance issue so thoroughly. 

A few questions, just to assess the size of the problem:
- How many users (roughly) are in one channel?
- Can you share with us your app and organization ids?

In the meanwhile, it's essential to know we're constantly improving our SDK's performance. We would be more than happy to think about how we can solve the issue you're facing together.

**Comment by shodgetts** [comment]
Hi @tj-mc , thanks for the report. I run the Customer Success team at Stream. Can you drop me an email with your app_or key sometime please, stephen@getstream.io. I'd like to make sure this is tracked internally.

**Comment by tj-mc** [comment]
Thanks for the quick response @vanGalilea and @shodgetts; really appreciate it.

I have shared our App ID over email as I did not know if this was private.

In our Peak times, we see 3000+ plus unique users view the Get Stream channel, but I do not have stats for the number of active users at a single moment. It would be in the thousands in some cases. On certain days, we have close to 10,000. I think we are quite a large use-case of public channels so I think these performance only start to become really obvious at the extreme end of things.

We have overridden a few small components for the Avatar and Quoted messages, however the main structure of the chat remains stock. I can't share source code but I can share that our top level structure of chat looks like this.

```
  <OverlayProvider>
    <Chat client={chatClient}>
      <Channel>
        {children}
        <MessageList/>
        <MessageInput />
      </Channel>
    </Chat>
  </OverlayProvider>
```

However In the profiling dump I supplied, I can see that the renders are triggered from inside the internal contexts of the Get Stream components.

I've been thinking about the design and how these issues could be solved without too much development effort 🤔 

[In this article](https://preactjs.com/blog/introducing-signals/) by Preact, they introduce 'Signals' and explain a context problem almost identical to what is occurring here. Perhaps internally switching to signals would solve a lot of this "for free", as only components observing the actual value will re-render. However, I don't know how this would work with a library like this, as I'm not sure if @preact/signals-react would need to be installed for each user of the package 🤔 

As an alternative state could be managed with an internal Redux or MST store.

**Comment by tj-mc** [comment]
Perhaps we could also provide a way of disabling all typing / entering / leaving state, as I would imagine in most Channels of this size we are not worried about who is typing.

**Comment by vanGalilea** [comment]
> Thanks for the quick response @vanGalilea and @shodgetts; really appreciate it.
> 
> I have shared our App ID over email as I did not know if this was private.
> 
> In our Peak times, we see 3000+ plus unique users view the Get Stream channel, but I do not have stats for the number of active users at a single moment. It would be in the thousands in some cases. On certain days, we have close to 10,000. I think we are quite a large use-case of public channels so I think these performance only start to become really obvious at the extreme end of things.
> 
> We have overridden a few small components for the Avatar and Quoted messages, however the main structure of the chat remains stock. I can't share source code but I can share that our top level structure of chat looks like this.
> 
> ```
>   <OverlayProvider>
>     <Chat client={chatClient}>
>       <Channel>
>         {children}
>         <MessageList/>
>         <MessageInput />
>       </Channel>
>     </Chat>
>   </OverlayProvider>
> ```
> 
> However In the profiling dump I supplied, I can see that the renders are triggered from inside the internal contexts of the Get Stream components.
> 
> I've been thinking about the design and how these issues could be solved without too much development effort 🤔
> 
> [In this article](https://preactjs.com/blog/introducing-signals/) by Preact, they introduce 'Signals' and explain a context problem almost identical to what is occurring here. Perhaps internally switching to signals would solve a lot of this "for free", as only components observing the actual value will re-render. However, I don't know how this would work with a library like this, as I'm not sure if @preact/signals-react would need to be installed for each user of the package 🤔
> 
> As an alternative state could be managed with an internal Redux or MST store.

Thanks for thinking along. We're constantly working on improving and enhancing our SDK.
Rewriting our inner SDK state management so it will be more efficient and performant is a task of huge size with loads of complexities. We're currently experimenting and working on finding the right tool that will suit our solution.

Stay tuned.

**Comment by tj-mc** [comment]
We actually were not aware of this guide. From what I can see. I think these tweaks could have helped to solve the worst of our performance issues, particularly the exponential nature of the typing events. We did end up re-writing our own interface to offer a more custom experience but I think this would have helped a great deal. 👌

**Comment by vishalnarkhede** [comment]
Closing this for now, since there is not much to add at this point.
