### ISSUE TITLE
Is it possible to sort pinned messages to the top of a channel?

### ISSUE THREAD

**Issue by thallada** [GetStream/stream-chat-react-native#2017]
**Motivation**
It seems like the pinning feature will only highlight a message in the chronological order that messages were sent in a channel/thread. However, in my app, I would like to highlight pinned messages more prominently by sorting them to the top of a channel. This is how the pinned feature works in other forum software (aka. "sticky" posts), so I would imagine this is a common use case that other users would want.

**Proposed solution**
Ideally, I would like some sort of prop to the `<Channel>` component that would toggle sorting pinned messages to the beginning of the message list. I am rendering channel messages un-inverted (with `<MessageList inverted={false} />`), so for me, this would cause pinned messages to appear at the top of the list.

It seems like it should be possible to query pinned messages separately through the API with [`getPinnedMessages`](https://getstream.io/chat/docs/react-native/pinned_messages/#paginate-over-all-pinned-messages). Then that list could be concatenated with the normal channel messages with pinned messages filtered out.

**Acceptance Criteria**
I am able to render a channel message list with all pinned messages at the beginning (regardless of when they were sent) and then all non-pinned messages following.

**Comment by khushal87** [comment]
Hey @thallada, although I get what you mean an extent, can you show an example of the UI/prototype of your exact requirement? That will help me address the issue. Thanks 😄

Of what I understand you want a separate list of pinned messages on the top of your MessageList that are sorted in the order of their creation, right?

**Comment by thallada** [comment]
I have a custom `MessageSimple` renderer. This is an example mock of a channel with two pinned messages. Note that the pinned message was created 1 month ago while the last normal message was much sooner.

As for the order in the pinned list, I think sorting by the order of message creation would make the most sense.

![Multiple pinned messages](https://user-images.githubusercontent.com/1505923/226388238-773b06ba-d362-4a24-b119-d2827d4a7728.png)

In this mock, the pinned messages are in a separate horizontal scroll container from the normal message vertical scroll container.

The ideal API I'm imagining for this would look something like this:

```
<Channel channel={channel} threadList>
  <MessageList noGroupByUser inverted={false} additionalFlatListProps={{ horizontal: true }} onlyPinnedMessages />
  <MessageList noGroupByUser inverted={false} includePinnedMessages={false} />
</Channel>
```

The new imaginary props I've made here for `MessageList` are `onlyPinnedMessages` and `includePinnedMessages` which would filter whether pinned or non-pinned messages appear in the list (might be better prop names for that).

Ideally the regular vertical scroll list would not include the pinned messages, but it might be okay if they are also duplicated in that list if that would make it easier to implement.

**Comment by khushal87** [comment]
Hey @thallada, the one you are recommending is a great suggestion but is currently not supported in our SDK. You can build your UI as the one you have shared in the screenshot, with minimal effort. To do that, you can firstly query the pinned messages using [this guide](https://getstream.io/chat/docs/react-native/pinned_messages/?language=javascript&q=extra). And finally proceed to add your own UI with them. You can also sort the date of the pinned messages retrieved through the query and use it the order you want. I know this increases customization on the user side but this is the way to go for now. Thanks 😄

**Comment by thallada** [comment]
I ended up doing that and I was able to get it working.

The only gotcha I ran into was that the component needs to also listen to new/updated/deleted messages and reactions (with `channel.on`) and refetch the pinned messages so they are up to date.

**Comment by khushal87** [comment]
Hey, we expect that the new message handling will have to added separately and I think you have figured it out pretty well.

Closing this issue until then. Please let us know if anything doesn't work.
