### ISSUE TITLE
Touch box for long press is not aligned to the message when a reaction is present

### ISSUE THREAD

**Issue by TaharS** [GetStream/stream-chat-react-native#2021]
**Describe the bug**
On an Android device, when a user has reacted to a message (any emote), the next time it wants to long press on the message, the hit box is actually push to the bottom which stops an accurate selection of the message.
<img width="330" alt="Screen Shot 2023-03-20 at 2 15 42 PM" src="https://user-images.githubusercontent.com/10080564/226478659-d24a1e5f-b9e9-4230-a74e-d56fbf24e9b8.png">
On this screenshot, you can see that the hit box is actually lower by the size of the reaction. Which doesn't register long press is the user doesn't precisely hold press on the second half of the message. 
It is particularly annoying for 1 liner messages (less for 2+ lines)

**Dev environment info (please complete/provide the following information):**

- Package version
```
    "stream-chat": "8.2.1",
    "stream-chat-react-native": "^5.11.2",
```
- react-native or expo version
```
    "react-native": "0.70.3",
```
- Device/Emulator (android/ios) and OS version
Android Emulator Pixel 5 API 33

**To Reproduce**

1. Open the app on Android
2. Select a channel
3. Send a one liner message
4. Long press and add a reaction
5. Try to long press again while touching the top of the message (failure to open overlay)
6. Try to long press again while touching the lower part of the message (successfully open the overlay)

**Expected behavior**
Overlay should display properly on long press

**Additional context**
n/a

**Screenshots**
n/a

**Comment by vanGalilea** [comment]
Might be related to https://github.com/GetStream/stream-chat-react-native/issues/1982

**Comment by khushal87** [comment]
Hey @TaharS, thanks for pointing out the bug to us. We were able to reproduce this issue on our side and we will try to come up with a fix.
