### ISSUE TITLE
getPhotos doesn't work if you use compileSdkVersion 33  

### ISSUE THREAD

**Issue by aharwood9** [GetStream/stream-chat-react-native#2022]
**Describe the bug**

`getPhotos` on Android uses the `PermissionsAndroid.PERMISSIONS.READ_EXTERNAL_STORAGE` and will throw an error if this isn't granted. We had to update our app to use compileSdkVersion 33 which means `getPhotos` no longer works  as `READ_EXTERNAL_STORAGE` no longer has an impact. 

Here is a [link](https://developer.android.com/reference/android/Manifest.permission#READ_EXTERNAL_STORAGE) from the Android docs - 
```
Note: Starting in API level 33, this permission has no effect. If your app accesses other apps' media files, request one or more of these permissions instead: [READ_MEDIA_IMAGES](https://developer.android.com/reference/android/Manifest.permission#READ_MEDIA_IMAGES), [READ_MEDIA_VIDEO](https://developer.android.com/reference/android/Manifest.permission#READ_MEDIA_VIDEO), [READ_MEDIA_AUDIO](https://developer.android.com/reference/android/Manifest.permission#READ_MEDIA_AUDIO).
```
**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native/stream-chat-expo) - stream-chat-react-native
- react-native or expo version - 5.11.2
- Device/Emulator (android/ios) and OS version - Android 13 only (I think), Pixel 5 (only tested on this)

**To Reproduce**

1. Update `build.gradle` to use compileSdkVersion 33  within SampleApp
2. Boot Sample App on Android 13 device
3. Try to attach a photo
4. See Error or blank modal

**Expected behavior**

Repeat above but see photos from camerroll

**Additional context**

**Screenshots**

**Comment by santhoshvai** [comment]
@aharwood9 There is no api to get the target SDK on runtime... So I am going to make it so that if react native 0.71 version is used then to use the new permissions.. 

Just to be clear, you are using RN v0.71 right?

**Comment by aharwood9** [comment]
That sounds great @santhoshvai 🎉 merci for the quick response
