### ISSUE TITLE
Keyboard transition broken

### ISSUE THREAD

**Issue by nicobermudez** [GetStream/stream-chat-react-native#2024]
**Describe the bug**
There's an unusual transition when going from the media library back to the keyboard as shown in the video posted below. This is for iOS and Android on Simulator and on on a physical device.

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native/stream-chat-expo): 5.11.2
- react-native version: 0.70.5
- expo version: 47.0.0
- Device/Emulator (android/ios) and OS version: all

**Expected behavior**
A smooth transition from the media picker to the keyboard

**Screenshots**
https://user-images.githubusercontent.com/35746593/227387306-4a4c416c-05e8-471f-88e5-8e6876903b23.mov

**Comment by vanGalilea** [comment]
@nicobermudez we have registered this one, and added this to our low-prio list, stay tuned.
