### ISSUE TITLE
MessageSystem does not leave margin for typing indicators when they are the very last message

### ISSUE THREAD

**Issue by cenzovit** [GetStream/stream-chat-react-native#203]
**Describe the bug**
MessageSystem does not leave margin for typing indicators when they are the very last message. Probably MessageList itself should have a margin instead of individual messages checking if they are the very last message...

**To Reproduce**

1. Send a system message to a channel
2. See that no margin is left below the very last message and that the typing indicators show up on top of the system message when the message list is scrolled to the bottom

**Expected behavior**
The MessageList should always have margin at the bottom for the typing indicators

**Comment by vishalnarkhede** [comment]
Hey @cenzovit  fix has been published on `0.10.2`. Please reopen the issue if you still see the error :)
