### ISSUE TITLE
Text in International language appears when user sends combination of text

### ISSUE THREAD

**Issue by rpopovici** [GetStream/stream-chat-react-native#2033]
How to reproduce:
1. Type `1.New` followed by pressing the Send button
2. Text appear to be Chinese
3. If you tap the link it will take you to `wolai.com` a Chinese website..

<img width="350" alt="Screenshot 2023-03-31 at 18 39 35" src="https://user-images.githubusercontent.com/2832454/229166653-88df6735-4ed3-4591-b64f-727254835f4e.png">

**Comment by santhoshvai** [comment]
Hey @rpopovici , this is not a issue per se. [1.new](http://1.new/) is a valid domain pointing to wolai. The chat message parses all the valid domains that is the preferred use experience. 

Try `1. new` , which is the right wy. Rhe message will be parsed as markdown and you will get formatting.
