### ISSUE TITLE
Custom Attachment Issues With Card Component. 

### ISSUE THREAD

**Issue by MxBM** [GetStream/stream-chat-react-native#2035]
**Describe the bug**:
Currently, I'm attempting to implement Custom Attachments in a Channel utilizing the card prop in the Channel Component. I've followed the guide provided in the docs for this (Refer here: https://getstream.io/chat/docs/sdk/reactnative/guides/custom-attachment/). The issue arises whenever I send a message using the channel.sendMessage via my backend, the message with the custom attachment gets sent into the Channel but the function attached to the Card prop doesn't log out the message's custom type. In the case of sending a message using channel.sendMessage from the client, the custom attachment type is logged out by my function attached to the Card prop.

I'm aware that this shouldn't make a difference regardless of where the message is sent from, it should send the message to the same channel as long as the channelId and environment variables match. I've gone ahead and confirmed this via the dashboard:

Sending a message from a client resulted in this: 
![image](https://user-images.githubusercontent.com/96575525/229257133-53e0170f-5d12-43e9-9fdb-211606b2870b.png)

Sending a message from my backend resulted in this: 
![image](https://user-images.githubusercontent.com/96575525/229257203-6a1ddd98-6bfd-472e-bb08-d2c985f3feb4.png)

The main difference is that on my client the console log from the code below only logs the attachment type of "hai" not of "LiveStream", ever. For context, I was able to send the attachment type of "hai" on the same screen where this Channel Component lives via a button press that executed the sendMessage function to send a message with a custom attachment of "hai". 

Since the messages both got sent to the channel (confirmed via the dashboard), I've ruled out any environment variable issues with the stream keys. It also doesn't appear to be a rendering issue as I've re-rendered the Message List and I never received a log for the attachment type of "LiveStream".  I'm not sure what else it could be on my end. 

```
 const CustomCardComponent = ({ type, ...otherProperties }) => { //Taken Straight From Docs
    console.log(type);
    return <View />;
  };

  return (
    <ScreenComponent>
      <SafeAreaView style={tw`flex-1 bg-grey-10`}>
        <View style={tw`pb-16 bg-base-50`}>
          <ClubChatHeaderComponent
            onProfilePressHandler={onProfilePressHandler}
            onBackButtonPressHandler={onBackButtonPressHandler}
          />

          <Channel
            getMessagesGroupStyles={getGroupStyles}
            channel={channel}
            Card={CustomCardComponent}
          >
          </Channel>

```

- Package version (stream-chat-react-native/stream-chat-expo):    "stream-chat-react-native": "^5.11.2"
- react-native or expo version: React Native 
- Device/Emulator (android/ios) and OS version: iPhone 12 pro running I.OS 15.4.1

**Comment by khushal87** [comment]
Hey @MxBM, just to know more about your issue, are you sure you are using the same environment on both the backend and the client, and everything is the same? Did you find the sent attachment type for both the backend and client on the dashboard appropriately?

**Comment by MxBM** [comment]
Yes, the API's keys are matching, as well as messages are being sent to the proper channel correlated to that environment. I've gone ahead and also logged out all of the messages that are being sent to this specific channel on the client as well and the Livestream attachment type is being logged in the channel-message-simple component but not in the CustomCardComponent that I defined meaning that for whatever reason the attachment type isn't being recognized by the Card component somehow? To answer your question, yes both messages with custom attachment types sent from the client and backend respectively both appear on the dashboard to the appropriate channel.

**Comment by MxBM** [comment]
Update: The Message Simple component had been altered improperly and was messing with the Attachment.
