### ISSUE TITLE
Incorrect display of Custom avatar for replied message from sender

### ISSUE THREAD

**Issue by Sheleya** [GetStream/stream-chat-react-native#2040]
Incorrect display of Custom avatar for replied message from sender

stream-chat-react-native: 5.12.1
react-native: 0.68.2
Emulator iOS

**To Reproduce**

If you check screenshot you will understand everything.
You have to reply the message.

**Expected behavior**
Should be different avatars.
The avatar on message "Goood!" should be another

**Screenshots**
<img width="423" alt="Screenshot 2023-04-04 at 16 52 56" src="https://user-images.githubusercontent.com/42179511/229814733-4f1aff94-8585-40ca-941e-5983577246b7.png">

**Comment by Sheleya** [comment]
> Hey @Sheleya, can you please share the code you have used to customize the avatar? Also, if I understand the issue correctly, are you getting the receiver's avatar instead of the sender's?

Yes, it shows receiver's avatar instead of the sender's.

```
  const CustomAvatar = () => {
    const { message } = useMessageContext();
    const [groupStyle] = (message?.groupStyles || []) as GroupType;

    if (groupStyle === 'bottom' || groupStyle === 'single') {
      return (
        <Pressable
          style={styles.avatarContainer}
          onPress={onPressUser(message.user?.id)}
        >
          <UserAvatar
            width={30}
            height={30}
            avatarURISource={ImageRequestConfigService.getUserImageConfig(
              message.user?.id ?? '',
            )}
          />
        </Pressable>
      );
    } else {
      return <View style={styles.noAvatarContainer} />;
    }
  };
```

**Comment by khushal87** [comment]
Are you passing it to `MessageRepliesAvatar`? @Sheleya

**Comment by Sheleya** [comment]
> Are you passing it to `MessageRepliesAvatar`? @Sheleya

no, to MessageAvatar. MessageRepliesAvatar never renders for me

**Comment by Sheleya** [comment]
> Are you passing it to `MessageRepliesAvatar`? @Sheleya

btw, I sent you wrong code fragment. Below correct one

`const CustomAvatar = () => {
    const { message } = useMessageContext();

    const usedId = message?.quoted_message
      ? message.quoted_message?.user?.id
      : message.user?.id;

    return (
      <Pressable style={styles.avatarContainer} onPress={onPressUser(usedId)}>
        <UserAvatar
          width={30}
          height={30}
          avatarURISource={ImageRequestConfigService.getUserImageConfig(
            usedId ?? '',
          )}
        />
      </Pressable>
    );
  };`

**Comment by khushal87** [comment]
Can you verify if your `message.quoted_message?.user?.id` returns the appropriate user id of the sender?

**Comment by Sheleya** [comment]
yes, it returns correct user id

> Can you verify if your `message.quoted_message?.user?.id` returns the appropriate user id of the sender?

**Comment by khushal87** [comment]
In that case something might be wrong with `ImageRequestConfigService.getUserImageConfig(
        usedId ?? '',
      )`. Did you check?

**Comment by Sheleya** [comment]
no, everything is correct with this func. I'm not sure does it correctly renders replied message and what is the data there

**Comment by Sheleya** [comment]
it seems like it pass to the replied message the same userId as a sender message has

**Comment by khushal87** [comment]
If you see [this line](https://github.com/GetStream/stream-chat-react-native/blob/develop/package/src/components/Reply/Reply.tsx#L170) on our SDK, we also pass `message.quoted_message` on our SDK to render the avatar. It should be fine unless something is changed on your side.

**Comment by Sheleya** [comment]
> If you see [this line](https://github.com/GetStream/stream-chat-react-native/blob/develop/package/src/components/Reply/Reply.tsx#L170) on our SDK, we also pass `message.quoted_message` on our SDK to render the avatar. It should be fine unless something is changed on your side.

okay, will investigate further

**Comment by Sheleya** [comment]
> If you see [this line](https://github.com/GetStream/stream-chat-react-native/blob/develop/package/src/components/Reply/Reply.tsx#L170) on our SDK, we also pass `message.quoted_message` on our SDK to render the avatar. It should be fine unless something is changed on your side.

Can you show me the example of code that correctly renders avatars in 1-on-1 chat? 
As you said that reply message accepts `message.quoted_message` then avatar component should use `message.user?.id`, but it doesn't work for me. See an example.

`MessageAvatar={CustomAvatar}`

`const CustomAvatar = () => {
    const { message } = useMessageContext();

    return (
      <Pressable
        style={styles.avatarContainer}
        onPress={onPressUser(message.user?.id)}
      >
        <UserAvatar
          width={30}
          height={30}
          avatarURISource={ImageRequestConfigService.getUserImageConfig(
            message.user?.id ?? '',
          )}
        />
      </Pressable>
    );
  };`
  
<img width="409" alt="Screenshot 2023-04-06 at 10 53 42" src="https://user-images.githubusercontent.com/42179511/230311212-c385604b-3343-4e22-977c-095f0789966f.png">

**Comment by Sheleya** [comment]
@khushal87 is it correct? ☝️

**Comment by khushal87** [comment]
> Can you show me the example of code that correctly renders avatars in 1-on-1 chat?

You can check our example apps, TypeScriptMessagingApp or SampleApp, in the examples folder.
![simulator_screenshot_4CC077AA-57F1-4C55-9A70-C18B050BE82E](https://user-images.githubusercontent.com/39884168/232435209-cd66c82f-d5bd-448f-a603-0599c20cf2cf.png)

**Comment by Sheleya** [comment]
@khushal87 I absolutely don't understand how to handle Avatar of Replied message. `MessageAvatar` prop applies only to original message, not to replied one. How should I handle it?

**Comment by khushal87** [comment]
Hey @Sheleya, MessageRepliesAvatar won't work here. The MessageAvatar should be the one used to appropriately customize the avatar both for normal messages and quoted messages. Now, I just tested on my side. I got the appropriate user, who is the sender of the original message and his id when I console.log the message.quoted_message.user. I am not sure why it isn't the case for you. Can you debug and see what's the id and user details and if it's correct for the original message(the one to which the reply was added)?

**Comment by khushal87** [comment]
Does the above message help you @Sheleya? Can we close this issue?

**Comment by Sheleya** [comment]
no, it didn't help. Still works incorrectly, I tried almost everything.

**Comment by khushal87** [comment]
That's weird. Can you share a reproducible repo with us to test it on our side?

**Comment by Sheleya** [comment]
@khushal87 let's put it on hold. I will ping you later

**Comment by khushal87** [comment]
Closing it till then. Please feel free to open it back.

**Comment by tanishadandona** [comment]
Can you please provide me source code for this?

**Comment by tanishadandona** [comment]
@khushal87   replied message avatars are incorrect  .it shown  my avatar. rather then user's Avatar

**Comment by khushal87** [comment]
Did you try using `MessageAvatar` component to customize it?

**Comment by tanishadandona** [comment]
const CustomizedMessageAvatar = (props) => {
    const { message } = useMessageContext();
    const isLeader = squadDetail?.squad_leaders?.find(
      (leader) => leader.user_id === message?.user?.id
    );
    console.log('message.avatar', message?.quoted_message.user);
    return (
      <Pressable
        onPress={() => {
          /**
           * @Analytics
           */
          Analytics.gaTrackEvent('user_profile_clicked');
          if (message?.user?.id !== AdminAccountID) {
            stackNavigation(
              componentId,
              'MyProfileScreen',
              { userEmail: message?.user?.email },
              {
                bottomTabs: {
                  visible: false,
                },
                topBar: {
                  visible: true,
                  scrollEdgeAppearance: { noBorder: true },
                  elevation: 0,
                  backButton: {
                    color: '#000',
                    showTitle: false,
                  },
                  title: {
                    alignment: 'center',
                  },
                },
              }
            );
          }
        }}
      >
        <MessageAvatar />
        {(message?.groupStyles[0] === 'bottom' || message?.groupStyles[0] === 'single') &&
          isLeader && <StarIcon source={require('@assets/icons/star.png')} />}
      </Pressable>
    );
  };  i tried this

**Comment by tanishadandona** [comment]
const CustomizedMessageAvatar = (props) => {
    const { message } = useMessageContext();
    const isLeader = squadDetail?.squad_leaders?.find(
      (leader) => leader.user_id === message?.user?.id
    );
    console.log('message.avatar', message?.quoted_message.user);
    return (
      <Pressable
        onPress={() => {
          /**
           * @Analytics
           */
          Analytics.gaTrackEvent('user_profile_clicked');
          if (message?.user?.id !== AdminAccountID) {
            stackNavigation(
              componentId,
              'MyProfileScreen',
              { userEmail: message?.user?.email },
              {
                bottomTabs: {
                  visible: false,
                },
                topBar: {
                  visible: true,
                  scrollEdgeAppearance: { noBorder: true },
                  elevation: 0,
                  backButton: {
                    color: '#000',
                    showTitle: false,
                  },
                  title: {
                    alignment: 'center',
                  },
                },
              }
            );
          }
        }}
      >
        <MessageAvatar />
        {(message?.groupStyles[0] === 'bottom' || message?.groupStyles[0] === 'single') &&
          isLeader && <StarIcon source={require('@assets/icons/star.png')} />}
      </Pressable>
    );
  };

- > i tried this

**Comment by khushal87** [comment]
If you don't add any customization, does it work? Also, the code that you have shared is not readable. I would suggest you share a minimal snippet of what you are doing.

**Comment by tanishadandona** [comment]
would you please provide me  Code  i need to custom my  MessageAvatar which will  work for both. Normal and Replired message

**Comment by tanishadandona** [comment]
> If you don't add any customization, does it work? Also, the code that you have shared is not readable. I would suggest you share a minimal snippet of what you are doing.

i need quote reply only

**Comment by khushal87** [comment]
Something like this would ideally work if you pass it to the `MessageAvatar` prop of the Channel component.

```
const CustomAvatar = () => {
const { message } = useMessageContext();

const usedImage = message?.quoted_message
  ? message.quoted_message?.user?.image
  : message.user?.image;

  return (
      <UserAvatar
        width={30}
        height={30}
        avatarURISource={userImage}
      />
    </Pressable>
  );
};
``` 

Make sure you pass it to both Channel screen and Thread screen's Channel compoent.

**Comment by khushal87** [comment]
Hey @Sheleya @tanishadandona @magiusdarrigo, please do the following in your code:

```tsx
import {
  MessageAvatar,
  MessageAvatarProps,
  MessageType,
  Reply,
  ReplyProps,
  useMessageContext,
} from 'stream-chat-react-native';

const CustomMessageAvatar = (props: MessageAvatarProps) => {
  return (
    <Pressable onPress={() => console.log('Normal Avatar')}>
      <MessageAvatar {...props} />
    </Pressable>
  );
};

const CustomMessageReplyAvatar = (props: MessageAvatarProps) => {
  const { message } = useMessageContext();
  return (
    <Pressable onPress={() => console.log('Quoted Avatar')}>
      <MessageAvatar
        {...props}
        size={50}
        message={message.quoted_message as MessageType<StreamChatGenerics>}
      />
    </Pressable>
  );
};

const CustomReplies = (props: ReplyProps) => {
  return <Reply {...props} MessageAvatar={CustomMessageReplyAvatar} />;
};
```

Then pass the `CustomMessageAvatar` and `CustomReplies` to the `MessageAvatar` and the `Reply` prop of the `Channel` component and that should fix your problem.
