### ISSUE TITLE
attachment image picker error after upgrading expo 48 (android 13)

### ISSUE THREAD

**Issue by hotaryuzaki** [GetStream/stream-chat-react-native#2044]
**Describe the bug**
attachment image picker error after upgrading expo 48, the screen is dimming and showing an error permission
but the problem still exists, even though I allow the permissions manually in the settings.

you can check [here](https://www.loom.com/share/8d555f4a039747569d896241f4db9fa9)

**Dev environment info (please complete/provide the following information):**

expo: 48.0.0
"stream-chat-react-native": "^5.12.1"
"@react-native-camera-roll/camera-roll": "^5.3.1",
android 13

**To Reproduce**

1. upgrade to 48 version from 47
2. setup target SDK 33

**Expected behavior**
i think you should request the permission just like @react-native-camera-roll/camera-roll suggested

FYI:
we have a gallery on another screen, and it's okay.
if no permission we will request it.

**Comment by vanGalilea** [comment]
@hotaryuzaki, thanks for reaching out @khushal87 is working on making our components Expo 48 compliant, so please stay tuned.

**Comment by vanGalilea** [comment]
We will try to upgrade the image picker lib. and see if it's compliant

**Comment by vanGalilea** [comment]
We have fixed this issue in this [PR](https://github.com/GetStream/stream-chat-react-native/pull/2036); 
Check our latest [beta release v5.13.0-beta.3](https://www.npmjs.com/package/stream-chat-react-native/v/5.13.0-beta.3)and let us know if it works for you

**Comment by hotaryuzaki** [comment]
> We have fixed this issue in this [PR](https://github.com/GetStream/stream-chat-react-native/pull/2036); Check our latest [beta release v5.13.0-beta.3](https://www.npmjs.com/package/stream-chat-react-native/v/5.13.0-beta.3) and let us know if it works for you.

we tested this and it solved the issue

**Comment by vanGalilea** [comment]
That's lovely 🙌🏻
