### ISSUE TITLE
If user doesn't allow camera permissions, and clicks again on camera - nothing happens

### ISSUE THREAD

**Issue by Bogdastotel** [GetStream/stream-chat-react-native#2047]
**Describe the bug**

When the user click on the attachment button and presses  the camera button, it prompts the native alert for the user to allow the camera access. But if the user does not allow it and you click again, where is no feedback on that matter (like on image picker when you clikc on the gallery it says: "Allow access to your photos in your gallery" and that redirects to the phone permission settings for that app.

**Dev environment info (please complete/provide the following information):**
IOS

- Package version (stream-chat-react-native/stream-chat-expo)
stream-chat-react-native
- react-native or expo version  
- React native CLI
- Device/Emulator (android/ios) and OS version
IOS

**To Reproduce**

1. Go to chat channel
2. Click on 'attachement (file) button'
3. Click on 'camera icon'
4. DO NOT allow the camera access
5. Click again on the 'camera icon'
6. Nothing happens (modal is off)

**Expected behavior**

6. User should be prompted to open the iPhone settings and give the permissions manually)
7.  Would be nice to copy the logic from the gallery button press 

**Additional context**

**Screenshots**

![bb](https://user-images.githubusercontent.com/47041472/230451399-a7373422-ebf6-43a5-9c7b-0e6b1788e300.jpg)

**Comment by khushal87** [comment]
Thanks for reporting this bug to us; we will look into it and try to solve this soon.

**Comment by khushal87** [comment]
We will be happy if you can raise a pull request to fix this. Feel free to do so. Thanks 😄

**Comment by opeyemiagbeja** [comment]
any update on this?

**Comment by Bogdastotel** [comment]
Yes, sorry for late reply. Well, i did patch it on my own by checking the
permissions on my own, but this should be done differently, like it has
been done when checking the gallery permissions and notifying the user to
allow access to gallery in their phone settings and navigating them there.

**Comment by Bogdastotel** [comment]
If you can make something like this, but on your own way

[image: image.png]
