### ISSUE TITLE
When we change filter value then loader is not shown and also active channels remain same in stream client for sometime

### ISSUE THREAD

**Issue by 12varun12** [GetStream/stream-chat-react-native#2055]
**Describe the bug**
when we change the filter dynamically then loader is not visible and channel list is updated after some time.

**Dev environment info (please complete/provide the following information):**

- Package version 5.11.2
- react-native or expo version 0.70.3
- Device/Emulator (android/ios) and OS version >> this issue occours in both (android/ios)

**To Reproduce**
1) dynamically change the filter 
 In my case I changing hidden false to true on clicking on button
2) No loader appears and the prop loadingChannels does not change

**Expected behavior**
Either some prop value or context value must be changed or loader must appear automatically

**Additional context**

**Screenshots**
If applicable, add scr

https://user-images.githubusercontent.com/96221152/232010653-048632b1-312b-46b2-83eb-23814e4ae27c.mp4

**Comment by vanGalilea** [comment]
@12varun12, thanks for letting us know. It's debatable whether it's a bug or a feature.
Let me discuss this with our UX team and get back to you.

**Comment by khushal87** [comment]
Hey @12varun12, any update on the above? If this issue is no more relevant, can we close it?

**Comment by 12varun12** [comment]
No not yet.

**Comment by khushal87** [comment]
Is it working fine for you? If yes, please feel free to close it.

**Comment by 12varun12** [comment]
It's not working properly, it's work like previously work

**Comment by 12varun12** [comment]
Hey, Khushal Agrawal
I need your help, I am trying to customise hole message screen like
(message bubble, message thread avatar, Message Input and long press on
message thread)
so, please can you provide me a correct path to customise it because we
don't have enough time actually our stream chat is now live so we have do
customise on priority and live
it as soon as possible

**Comment by khushal87** [comment]
Hey Varun,

Please follow our [Message Customization guide ](https://getstream.io/chat/docs/sdk/reactnative/guides/message-customization/)for the same. Please feel free to reach out through support@getstream.io if something doesn't work. We cover most of the cases in our docs, so you will have to go through them to understand the flow.

Thanks and Regards,
Khushal
