### ISSUE TITLE
In Android 13 no permission is asked to upload photo or video

### ISSUE THREAD

**Issue by 12varun12** [GetStream/stream-chat-react-native#2056]
**Describe the bug**
when we click on attachment option np permission is asked for upload photo and video and attachment bottomsheet is open close automatically 

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native/stream-chat-expo) >> 5.11.2
- react-native version >> 0.70.3
- Device/Emulator (android/ios) and OS version >> issue in android 13

**To Reproduce**
1) click on add attachment 
attachment popup is open and close automatically and no permission popup is appear

**Expected behavior**
when we click on add attachment then a popup must be appear to as permission for access your camera and photos, videos
and then bottom sheet is open to select the attachments.

**Additional context**

**Screenshots**

https://user-images.githubusercontent.com/96221152/232015069-0259e5ae-bb00-4cf9-b59c-2afa31cd5764.mp4

**Comment by khushal87** [comment]
Hey @12varun12, we added some fixed on version 5.13.0 around android 13 permissions. Can you upgrade your version and try again? Thanks 😄

**Comment by vanGalilea** [comment]
I'll be closing this issue, please upgrade to v5.13.0 of our SDK and update your RN version to 0.71.X or higher

**Comment by 12varun12** [comment]
hi steve,
I have update my stream version to v5.13.0 and my react native version is
v0.70 but still i am facing same issue.
And one month ago i have updated my react native version 0.63 to 0.70, so
is there any other solution to fix it
