### ISSUE TITLE
MessageInput not working correctly in Android device and working fine in ios

### ISSUE THREAD

**Issue by 12varun12** [GetStream/stream-chat-react-native#2057]
**Describe the bug**
when we click on message input box then header is moving upward and visible to user and half input box is visible
but it is working fine in ios devices 

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native)  :-  "stream-chat-react-native": "^5.11.2",
- react-native :- "react-native": "0.70.3",
- Device/Emulator android and OS version :- for all android version

**To Reproduce**
1) click on message input box then half input box is visible
2) Header move upward and not visible to user but header is a separate component

**Expected behavior**
click on message input then show hole input box and header should not go upward and should not hide

**Additional context**

**Screenshots**

https://user-images.githubusercontent.com/96221152/232438845-d322c9b5-2e08-4876-a301-fb03c07efdea.mp4

**Comment by vanGalilea** [comment]
@12varun12 thanks for reaching out 👋🏻 , can you please check our troubleshooting documentation [Incorrect input position section](https://getstream.io/chat/docs/sdk/reactnative/basics/troubleshooting/#incorrect-input-position)?

May it not fix the issue, please share a full snippet of your channel screen implementation.

**Comment by 12varun12** [comment]
thanks @vanGalilea for helping out, This issue is fixed for me now

**Comment by 12varun12** [comment]
Hi  @vanGalilea I am facing an issue related to this fix
you had suggest me a solution {android:windowSoftInputMode="adjustResize"}
After applying this solution I am facing another issue

**Comment by 12varun12** [comment]
can you please help me out

**Comment by khushal87** [comment]
Hey @12varun12, please feel free to open an issue or reach us out with your exact issue with a proper description on support@getstream.io or create an issue on GitHub. Thanks 😄
