### ISSUE TITLE
How to set https://chat.stream-io-api.com ?

### ISSUE THREAD

**Issue by billnbell** [GetStream/stream-chat-react-native#2059]
How do you set URL to be https://chat.stream-io-api.com ?

Or use regional URL with React Native?

**Comment by gc0rtes** [comment]
Stream's new [Edge infrastructure](https://getstream.io/blog/chat-edge-infrastructure/) removes the need to specifically set a regional URL. The baseURL is https://chat.stream-io-api.com regardless of region.

If you need further assistance, please reach out to our support line here:
https://getstream.io/contact/support/

Best regards,
Guilherme
Support Engineer at Stream
