### ISSUE TITLE
react-native-web support

### ISSUE THREAD

**Issue by vishalnarkhede** [GetStream/stream-chat-react-native#206]
Support for RNW is currently work in progress at following PR - https://github.com/GetStream/stream-chat-react-native/pull/190

- [x]  Introduced a new NPM package - `stream-chat-react-native-web`
- [x] Move native dependencies such as react-native-document-picker, react-native-image-picker, NetInfo from core component library (stream-chat-react-native-core) to package level - stream-chat-react-native (native-package) and stream-chat-expo (expo-package)
- [ ] Build wrappers for native dependencies such as image picker, file picker, netinfo, actionsheet for `stream-chat-react-native-web` package
- [ ] Setup an example app.
- [ ] Docs

### Kindly upvote the issue if you need RNW support for your project, so depending on demand I can prioritise this task.

**Comment by fractalmarc** [comment]
Awesome to see this making progress! My company's Expo app runs on iOS, Android, and Web all with one codebase and we would love to try moving to stream if RN-web was supported.

**Comment by dcsena** [comment]
+1

**Comment by marcod1419** [comment]
My team and I would like to see support for this, is it still in development?

**Comment by vishalnarkhede** [comment]
Closing this for now. Will reopen once we get back to it!!

**Comment by alpfactory-alex** [comment]
Will RNW support be available anytime soon?

**Comment by nandorojo** [comment]
Also curious, is web working? Reanimated 2 now works on web, as does RNGH.

**Comment by nandorojo** [comment]
@vishalnarkhede are there plans to re-open this?

**Comment by chinesehemp** [comment]
Can I use this package with React Native Web? I'm using Expo 44 and I'd like to initially build it for Web before releasing it to iOS and Android.

**Comment by izakfilmalter** [comment]
Would be great to see this move forward. It's a huge pita to write an app with both react-native and react stream right now.

**Comment by fzf** [comment]
Bumping this thread, has there been any progress on this?

**Comment by alexmlong** [comment]
I would love this as well. In the meantime is there a way to disable Stream when building for web? I like deving on web just because it's easier than using the phone simulators but currently I can't test my app on web because including Stream breaks it.
