### ISSUE TITLE
mentions visually respond to tap on iOS, but dont do anything?

### ISSUE THREAD

**Issue by megantaylor** [GetStream/stream-chat-react-native#2063]
**Describe the bug**

Inconsistent behavior around mentions text fragments within a message (ex: hi @test!)
- on iOS, tapping or long pressing just the mention (@test) create a visual response in the UI
- tapping doesn't actually seem to do anything, long-pressing opens the regular message overlay as one would expect from long-pressing the message
- on android, there is no visual response, behavior is the same

**Dev environment info (please complete/provide the following information):**

├─ @stream-io/stream-chat-css@3.7.2
├─ stream-chat-expo@5.11.2
├─ stream-chat-react-native-core@5.11.2
│  └─ stream-chat@8.2.1
├─ stream-chat-react@10.6.0
└─ stream-chat@8.4.1
├─ expo@47.0.8

**To Reproduce**
create or see a message in chat that includes a mention
tap or long press the mention

**Expected behavior**

In a perfect world, when I long press on an @ mentioned name, i would get some other type of overlay or popup that let me interact with that user (DM, Flag, Mute, etc). Otherwise, if that interaction is just going to do the same thing as long-pressing on the message, then there shouldn't be a visual cue from a tap or long-press on an @ mentioned name.

**Additional context**
For my own use, I wrote a quick patch for this issue:
https://github.com/GetStream/stream-chat-react-native/blob/develop/package/src/components/Message/MessageSimple/utils/renderText.tsx#L247
remove the onPress and onLongPress props

**Comment by khushal87** [comment]
Hey @megantaylor, you can customize your mention overlay by using `onLongPressMessage` prop in `Channel`:

```tsx
<Channel
        onLongPressMessage={({ emitter }) => {
          if (emitter === 'textMention') {
            console.log('Hey Mention');
          }
        }}
        thread={selectedThread}
      >
```

Note: The `emitter` should be `textMention` for this case.

Feel free to add your overlay design here. Thanks 😄

**Comment by khushal87** [comment]
Hey @megantaylor, did the above solution work for you?

**Comment by megantaylor** [comment]
I didnt try the `onLongPressMessage` prop, because that doesn't really solve the problem. adding the `onLongPressMessage` prop would allow me to create a custom overly on the mention. that might be something we build in the future, but the short term problem was that the mention text was visually responding to both taps and long presses and i wanted to prevent that.

**Comment by vanGalilea** [comment]
It seems like we've assisted and you found a solution that suits your use case.
I'll be closing this issue for now.
Please don't hesitate to contact us in the future if this issue or any questions arise.
