### ISSUE TITLE
Not working with Expo 48 and expo router

### ISSUE THREAD

**Issue by Leqx** [GetStream/stream-chat-react-native#2065]
**Describe the bug**
When using the overlay provider  I get an Error: Cannot find native module 'ExpoMediaLibrary'. Even though I've setup expo media library correctly as per the expo docs. 

**Dev environment info (please complete/provide the following information):**

- stream-chat-expo version 5.13.0
- Expo version 48.0.9
- Device run with expo dev client
- Navigation with expo router

**To Reproduce**

1. Go to ' the app root _layout.tsx '
2. Add  'OverlayProvider'
3. App crashes  'when run'

**Expected behavior**
I expected it to work out of the box following the guides provided in the docs.

**Additional context**
I use the expo router for app navigation. Every file in the app directory automatically becomes a route in your mobile navigation, making it easier than ever to build, maintain, and scale your project. It's built on top of our powerful [React Navigation suite](https://reactnavigation.org/) enabling truly native navigation. The entire deep linking system is automatically generated live so that users can share links to any route in your app.

**Screenshots**
![issue](https://user-images.githubusercontent.com/30660258/233133072-56003773-e5e6-40ed-af3a-5d017981f4d9.png)

**Comment by vanGalilea** [comment]
This error should not be related to navigation. Something might be conflicting with the gesture handler.

We're going to work on integrating Expo router into our ExpoMessaging sample app and will inform you when up and running.

**Comment by khushal87** [comment]
Make sure you check out layout component.
