### ISSUE TITLE
Expo: No suitable URL request handler found for ph-upload://<ID>

### ISSUE THREAD

**Issue by farmstrong8** [GetStream/stream-chat-react-native#2068]
**Describe the bug**

on iOS when using Expo with offline mode enabled, an error pops up when trying to upload an image before it finishes loading.

**Dev environment info (please complete/provide the following information):**

- stream-chat-expo@5.12.0
- react-native@0.70.8
- expo@47
- expo-dev-client@~2.0.1
- iOS version 16.13

**To Reproduce**

1. enable offline mode
2. open the asset picker
3. select a photo or video and press send
4. error pops up

**Expected behavior**
The image to upload in chat and then resolve at a later time.

**Additional context**
If you wait for stream to resolve the url before sending the the message it will work.

The default behavior with offline mode disabled is to disable the send button and show the activity indicator on the assets before uploading, but that behavior is disabled with the offline mode enabled flag due to this bit of code.

```jsx
export const getIndicatorTypeForFileState = (
  fileState: FileStateValue,
  enableOfflineSupport: boolean,
): Progress | null => {
  const indicatorMap: IndicatorStatesMap = {
    [FileState.UPLOADING]: enableOfflineSupport
      ? ProgressIndicatorTypes.INACTIVE
      : ProgressIndicatorTypes.IN_PROGRESS,
    // If offline support is disabled, then there is no need
    [FileState.UPLOAD_FAILED]: enableOfflineSupport
      ? ProgressIndicatorTypes.INACTIVE
      : ProgressIndicatorTypes.RETRY,
    [FileState.NOT_SUPPORTED]: ProgressIndicatorTypes.NOT_SUPPORTED,
    [FileState.UPLOADED]: ProgressIndicatorTypes.INACTIVE,
    [FileState.FINISHED]: ProgressIndicatorTypes.INACTIVE,
  };

  return indicatorMap[fileState];
};
```

My guess for the issue was it had to do with the Image component trying to resolve the URI so I tried swapping out the Image component with `react-native-fast-image` in addition to `expo-image` but neither works.

**Screenshots**

### Example with error

https://user-images.githubusercontent.com/5731669/233407471-1fb6f206-d351-4338-8b78-a6c2ea031a58.MP4

### Example waiting for image to finish upload before pressing send

https://user-images.githubusercontent.com/5731669/233407668-d0e978aa-0d55-401e-9621-bbe78feabaef.MP4

**Comment by khushal87** [comment]
Hey @farmstrong8, we do not support offline support with the expo for now, although we are trying our best to support it in the future. You can go through [our documentation](https://getstream.io/chat/docs/sdk/reactnative/basics/offline-support/) to learn more about offline support. 

Please try this with `enableOfflineSupport` as false and see if you face this issue and let us know.

**Comment by farmstrong8** [comment]
Hi @vanGalilea ya it seems this issue should be fixed in you latest update https://github.com/GetStream/stream-chat-react-native/releases/tag/v5.14.0 . I havent been able to test yet because of a dependency update in 5.12.1 https://github.com/GetStream/stream-chat-react-native/pull/2029/files . Not sure if you guys have tested this with an expo sdk version other than latest but android builds fail and im using expo 47. The stream package says expo 44 and up is supported so we should maybe give that a look as well!

**Comment by farmstrong8** [comment]
still seeing this issue on 5.15.0
