### ISSUE TITLE
withKeyboardContext is missing

### ISSUE THREAD

**Issue by WitleyInc** [GetStream/stream-chat-react-native#208]
I am trying to dismiss the keyboard inside the `Channel` component when I press a customized button. I notice that it can't be done with the native `Keyboard.dismiss()` function. Therefore, I read the document and find out that I need to use the `withKeyboardContext` function to pass the `dismissKeyboard` function to props. However, `withKeyboardContext` is missing in v0.10.2. How should I dismiss the keyboard without the KeyboardContext?

**Comment by vishalnarkhede** [comment]
Hey @WitleyInc 

`withKeyboardContext` is exported from the library - https://github.com/GetStream/stream-chat-react-native/blob/master/src/index.js#L11

Can you please show me some code?

**Comment by WitleyInc** [comment]
Ok, it is being exported from the library. It's just Visual Studio not showing the `withKeyboardContext` function in the import {...} from 'stream-chat-react-native'.
However, I have run into an TypeError when I am trying to follow the document on how to use `withKeyboardContext`.
![Simulator Screen Shot - iPhone 11 - 2020-05-11 at 01 55 01](https://user-images.githubusercontent.com/47505922/81543503-febe1100-932a-11ea-9ac6-d5570456c54f.png)
 
How should I use the `withKeyboardContext` function properly so my custom component's prop has the `dismissKeyboard` function?

**Comment by vishalnarkhede** [comment]
Can you please share your code around `withKeyboardContext`?

**Comment by WitleyInc** [comment]
```import {
    Chat,
    Channel,
    MessageList,
    MessageInput,
    withKeyboardContext,
} from "stream-chat-react-native";
import { setAllChatsMuted } from "../../State/chats";
import theme from "../../Styles/Theme";
import GlobalStyles from "../../Styles/GlobalStyles";

const ConversationScreenWithKeyboardContext = withKeyboardContext(ConversationScreen);
class ConversationScreen extends Component {
    constructor(props) {
        super(props);
        this.state = {
            chatClient: props.navigation.getParam("chatClient"),
            loading: true,
            error: null,
            channel: props.navigation.getParam("channel"),
            members: [],
            owner: false,
            keyboardUp: false,
        };
        this.keyboardUpListener = Keyboard.addListener("keyboardWillShow", event => {
            this.setState({ ...this.state, keyboardUp: true });
        });
        this.keyboardDownListener = Keyboard.addListener("keyboardWillHide", event => {
            this.setState({ ...this.state, keyboardUp: false });
        });
    }
    componentDidMount() {
        console.log(this.props);
        const conversationMembers = this.state.channel.state.members;
        const members = [];
        let owner = false;
        Object.getOwnPropertyNames(conversationMembers).forEach(name => {
            const memberInfo = Object.getOwnPropertyDescriptor(conversationMembers, name).value;
            if (memberInfo.user && memberInfo.user.id !== this.props.user.id) {
                members.push(memberInfo.user);
            }
            if (memberInfo.user && memberInfo.user.id === this.props.user.id) {
                owner = memberInfo.role === "owner";
            }
        });
        this.setState({ ...this.state, members, owner, loading: false });
        this.state.channel.on("channel.updated", this.handleUpdatedChannel);
    }```

**Comment by virdesai** [comment]
@WitleyInc can you try adding `static themePath = '';` to the ConversationScreen 
 Component and seeing if that solves your issue?

**Comment by WitleyInc** [comment]
@virdesai It still returns the same error
![Screen Shot 2020-05-12 at 1 58 57 PM](https://user-images.githubusercontent.com/47505922/81744939-bdc41a80-9458-11ea-9b46-91d2eab3789a.png)

**Comment by virdesai** [comment]
@WitleyInc hmmm, from reading through these docs https://github.com/GetStream/stream-chat-react-native/blob/master/src/components/docs/withKeyboardContext.md and https://github.com/GetStream/stream-chat-react-native/blob/master/src/components/docs/KeyboardContext.md, can we confirm that this `ConversationScreen` component is embedded within a `Channel` as `withKeyboardContext` need to be used only with `KeyboardCompatibleView` at some parent level?

**Comment by WitleyInc** [comment]
@virdesai so there's no way to dismiss the keyboard manually without using the `KeyboardCompatibleView`?

**Comment by virdesai** [comment]
@WitleyInc so if the React Native `Keyboard.dismiss()` isn't working then I'd say maybe not as even if you override the MessageInput by passing in Input and taking that `dismissKeyboard` prop off of there, that prop only exists if the MessageInput is a consumer of the KeyboardContext. So because the `dismissKeyboard` prop is declared within the `KeyboardContext` (`KeyboardCompatibleView`), it is only able to be consumed by a component and used if it is within that context. `KeyboardCompatibleView` is a default prop within the `Channel` component (https://github.com/GetStream/stream-chat-react-native/blob/master/src/components/Channel.js#L135) so as long as the custom screen you are creating is within a `<Channel></Channel>`, it should have the dismissKeyboard prop available if you use the `withKeyboardContext`. I hope that made sense?

**Comment by vishalnarkhede** [comment]
Hey @WitleyInc , also can you share full code for `ConversationScreen` either here or via email? That will give us clearer picture where the error regarding `themePath` is coming from.

**Comment by vishalnarkhede** [comment]
@WitleyInc do you still need help with this?

**Comment by vishalnarkhede** [comment]
Closing this! Please reopen if needed!

**Comment by WitleyInc** [comment]
Hi,

Thank you for checking back. Yes, this can be closed.

Cheers,
The Witley Team

On Jun 29, 2020, at 7:55 AM, Vishal Narkhede <notifications@github.com> wrote:

﻿

Closing this! Please reopen if needed!
