### ISSUE TITLE
Android when the message is very long does not scroll correctly

### ISSUE THREAD

**Issue by hareshmabbly** [GetStream/stream-chat-react-native#2084]
**Describe the bug**
 Currently when we have long messages in message list then list scroll become laggy and this issue happens only on android in ios everything works fine from our side we tried to made few changes to optimize the performance one of them is changing FlatList to FlashList but no much improvement happen. 

**Dev environment info (please complete/provide the following information):**

- Package version  : "stream-chat-expo": "5.12.0",
- expo version : "expo": "^48.0.7",
- Device/Emulator : Android (any android device we tested in z4 fold and samsung S series)
- Offline support enabled No

**To Reproduce**
1. Create any group chat.
2. Add 50+ messages where most of the messages should be long like more then 1000 words.
3. Try to scroll list and then try to scroll only long message you will see the laggy behaviour.
4.  Make sure above all are performed in Android device only because in ios everything seems fine.

**Expected behavior**
 MessageList should not lag

https://user-images.githubusercontent.com/102948668/235060511-fa4f10c1-5dfb-4b8a-a23a-275e61b017fc.mp4

 in android device.

**Comment by vanGalilea** [comment]
@hareshmabbly thanks for reaching out. We will have a look at that!
Which RN version are you using?

**Comment by hareshmabbly** [comment]
Currently we are using 	"react-native": "^0.71.7", version
