### ISSUE TITLE
EAS build error when adding expo offline support (expo dev client)

### ISSUE THREAD

**Issue by andreaslydemann** [GetStream/stream-chat-react-native#2088]
**Describe the bug**
When trying to enable offline support in an expo app running expo dev client (ios simulator build), I get an EAS build error from adding react-native-quick-sqlite 8.0.2 and running the build in the simulator. I followed the example project and the docs to match the versions described.

<img width="1093" alt="Skærmbillede 2023-05-06 kl  09 11 32" src="https://user-images.githubusercontent.com/15194614/236612079-d80cd0dc-cfcb-460c-ab9d-a9f0d57db248.png">

**Dev environment info (please complete/provide the following information):**

"stream-chat-expo": "^5.14.0",
"react-native-quick-sqlite": "^8.0.2",
"react-native": "0.71.7",
"expo": "~48.0.11",

**To Reproduce**

1. Install mentioned package versions
2. Build expo dev client (ios simulator build)
3. See EAS build error

**Expected behavior**
I expect my app to build properly. I know expo offline support was just enabled so there might be some things that weren't properly documented about using it.

**Comment by vanGalilea** [comment]
@andreaslydemann, thanks for reaching out!

Please check our recently updated [ExpoMessaging](https://github.com/GetStream/stream-chat-react-native/tree/develop/examples/ExpoMessaging) the libs. are similar to yours, and offline support is enabled.

Focus on the deltas between your project and ours ;)

**Comment by andreaslydemann** [comment]
Thanks - I had set useFrameworks: 'static' in my app.json with expo-build-properties. Apparently react-native-quick-SQLite doesn’t work with that enabled.

**Comment by andreaslydemann** [comment]
@vanGalilea For context, i was setting useFrameworks: 'static' because it's a requirement by react-native-firebase according to docs, but that setting doesnt work  with react-native-quick-sqlite. I wonder if another sqlite library would be better...

**Comment by andreaslydemann** [comment]
@RRaideRR for now I've just had to opt out of offline mode until there's a solution
