### ISSUE TITLE
There is no option to skip the push notification. 

### ISSUE THREAD

**Issue by 12varun12** [GetStream/stream-chat-react-native#2097]
## Issue

Describe your issue here
when the user removed by other user form chat group then the removed user get push notification, but we have to hide push notification related to that group
---

### Steps to reproduce
1. Goto groupInfo screen and click on particular participants whom you have to remove and click on remove button
2. after remove user we get a push notification related to that user 
3. ex :- "user 1 removed user 2"
---

### Expected behavior

After the removed user push must be skiped for that group

---

### Customization

<details><summary>Click To Expand</summary>
<p>

```typescript jsx
# N/A
```
</p>
</details>

---

### Offline support

- [ ] I have enabled offline support.
- [ ] The feature I'm having does not occur when offline support is disabled. (stripe out if not applicable)

---

## Environment

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
    - [ ] iOS
    - [ ] Android
    - [ ] **iOS** but have not tested behavior on Android
    - [ ] **Android** but have not tested behavior on iOS
    - [ ] Both
- **`stream-chat-react-native` version you're using that has this issue:**
    - `e.g. 5.4.3`
- Device/Emulator info:
  - [ ] I am using a physical device
  - OS version: `e.g. Android 10`
  - Device/Emulator: `e.g. iPhone 11`

</p>
</details>

---

### Additional context

---

### Screenshots

<details><summary>Click To Expand</summary>
<p>

</p>
</details>

---

**Comment by santhoshvai** [comment]
Hello @12varun12 

Stream only sends push for new messages. I think in your own backend you have a logic to send message when a user is removed from a group. Please check there.

I am closing this issue due to non relevance. Feel free to open if you don't think so and please provide us details if so.
