### ISSUE TITLE
[🐛] Images are cut off

### ISSUE THREAD

**Issue by andreaslydemann** [GetStream/stream-chat-react-native#2101]
Describe the bug
When sending an image in portrait mode, the image is cut off until the screen is re-rendered (I leave the chat and open it again). This happens for landscape images as well if I send two images and they're stacked on top of each other. See screenshots below.

Example of a single cut off image:
<img width="400" alt="IMG_4444" src="https://github.com/GetStream/stream-chat-react-native/assets/15194614/bfa4d2a5-40af-49c1-a5e2-22e73437aa4e">

After re-render: 
<img width="400" alt="IMG_4445" src="https://github.com/GetStream/stream-chat-react-native/assets/15194614/e4a9b072-08b3-4cdb-9e55-e7fe7fee57b1">

Example with stacked images (notice the waterfall picture):
<img width="400" alt="Simulator Screenshot - iPhone 14 Pro - 2023-05-14 at 14 52 04" src="https://github.com/GetStream/stream-chat-react-native/assets/15194614/6ccc41bd-ada2-40da-b15a-31f0cd250cf4">

Dev environment info (please complete/provide the following information):

"stream-chat-expo": "^5.14.0",
"react-native": "0.71.7",
"expo": "~48.0.11",

To Reproduce

Install mentioned package versions
Send an image that is in portrait mode
See that it is cut off

Expected behavior
I expect the images to never be cut off. It's not an issue to the receiver of the image, but the user sending the image will this that the image upload failed.

**Comment by khushal87** [comment]
I was trying to reproduce this same behaviour in our [expo messaging app](https://github.com/GetStream/stream-chat-react-native/tree/develop/examples/ExpoMessaging), and it seems to be working fine. The version of the expo is `~48.0.18`, and the `stream-chat-expo` version is the latest one. Offline support is also enabled.
