### ISSUE TITLE
[🐛] Potential performance issue

### ISSUE THREAD

**Issue by nandorojo** [GetStream/stream-chat-react-native#2103]
Currently, `MessageSimple` receives the `channel` as a prop. However, it's only using it to check if the item is the very last message. Would it be better to call this inside of the flat list's `renderItem` and pass it down as a prop to avoid having to compare the `channel`? This way, we can also avoid passing down the entire channel object of all messages to each `MessageSimple`.

Code in question:

```tsx
 const {
    alignment,
    channel,
    enableMessageGroupingByUser,
    groupStyles,
    hasReactions,
    message,
    MessageAvatar,
    MessageContent,
    MessagePinnedHeader,
    ReactionList,
  } = props;

  const {
    theme: {
      messageSimple: { container },
    },
  } = useTheme();

  const [messageContentWidth, setMessageContentWidth] = useState(0);

  const isVeryLastMessage =
    channel?.state.messages[channel?.state.messages.length - 1]?.id === message.id;
```

I'm a bit new to the codebase, so maybe I'm missing something. But I'm considering going live with Stream and am inspecting all the internals before moving forward. Thanks!

**Comment by vanGalilea** [comment]
@nandorojo, thanks for reaching out. `MessageSimple` is [memoized](https://github.com/GetStream/stream-chat-react-native/blob/6294bad65c0c0a1d7e2565f98622f1b71776656b/package/src/components/Message/MessageSimple/MessageSimple.tsx#L175).

Follow the code and the `isEqual` func. it shouldn't re-render.
