### ISSUE TITLE
🔥 [🐛] "Unread Messages" component flickers in/out

### ISSUE THREAD

**Issue by nandorojo** [GetStream/stream-chat-react-native#2108]
## Issue

When I scroll up/down towards the bottom of the screen, I notice that the `Unread Messages` indicator shows up. It then flickers away as I scroll closer to the bottom.

I think the issue is, it's somehow not marking all messages as read. If you look at the `ScrollToBottomButton` in the bottom right, it always has a 1 badge on it. This is kind of odd – it's as if the messages aren't getting marked as read.

As a qualifier: the messages which it thinks are "unread" were sent from `stream-chat-react` (on **web**, not React Native). Could that be related?

---

### Steps to reproduce

Hard to say the exact steps. Add a bunch of messages, chat between web and native such that the messages span the height of multiple screens, and then scroll down.

---

### Expected behavior

The "Unread Messages" indicator either shouldn't show, or it shouldn't flicker. Most importantly, messages that get read should be marked as such.

---

### Customization

<details><summary>Click To Expand</summary>
<p>

 

I'm just editing the theme with custom colors and fonts. Nothing too crazy as far as component customization. I just set this up in a few hours, copying the base components from the docs and updating the styles.

</p>
</details>

---

### Offline support

- [ ] I have enabled offline support.
- [ ] The feature I'm having does not occur when offline support is disabled. (stripe out if not applicable)

Not using offline support

---

## Environment

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
  "dependencies": {
    "@bacons/link-assets": "1.1.0",
    "@beatgig-tickets/ds": "*",
    "@beatgig/analytics": "*",
    "@beatgig/api": "*",
    "@beatgig/api-hooks": "*",
    "@beatgig/api-services": "*",
    "@beatgig/app-forms": "*",
    "@beatgig/auth-hooks": "*",
    "@beatgig/calendars": "*",
    "@beatgig/components": "*",
    "@beatgig/constants": "*",
    "@beatgig/design": "*",
    "@beatgig/features": "*",
    "@beatgig/forms": "*",
    "@beatgig/helpers": "*",
    "@beatgig/hooks": "*",
    "@beatgig/modals": "*",
    "@beatgig/native": "*",
    "@beatgig/navigation": "*",
    "@beatgig/next-pages": "*",
    "@beatgig/payments": "*",
    "@beatgig/popover": "*",
    "@beatgig/providers": "*",
    "@beatgig/screens": "*",
    "@beatgig/search": "*",
    "@beatgig/seo": "*",
    "@beatgig/theme": "*",
    "@beatgig/ui": "*",
    "@beatgig/vendors": "*",
    "@expo/metro-runtime": "2.0.4",
    "@formatjs/intl-datetimeformat": "^4.1.6",
    "@formatjs/intl-displaynames": "^5.1.6",
    "@formatjs/intl-getcanonicallocales": "^1.7.1",
    "@formatjs/intl-listformat": "^6.2.6",
    "@formatjs/intl-locale": "^2.4.33",
    "@formatjs/intl-numberformat": "^7.1.5",
    "@formatjs/intl-pluralrules": "^4.0.28",
    "@formatjs/intl-relativetimeformat": "^9.1.7",
    "@logrocket/react-native": "1.11.4",
    "@react-navigation/bottom-tabs": "6.4.0",
    "@react-navigation/native-stack": "6.9.8",
    "@react-native-async-storage/async-storage": "1.17.11",
    "@react-native-community/datetimepicker": "6.7.5",
    "@react-native-community/netinfo": "9.3.7",
    "@react-native-community/slider": "4.4.2",
    "@react-native-firebase/app": "17.3.1",
    "@react-native-firebase/auth": "17.3.1",
    "@react-native-picker/picker": "2.4.8",
    "@rudderstack/rudder-sdk-react-native": "1.6.2",
    "@sentry/react-native": "4.9.0",
    "@shopify/flash-list": "1.4.1",
    "burnt": "0.10.0",
    "expo": "~48.0.15",
    "expo-analytics-segment": "~11.2.0",
    "expo-app-loading": "~2.1.1",
    "expo-application": "~5.1.1",
    "expo-asset": "~8.9.0",
    "expo-auth-session": "~4.0.3",
    "expo-av": "~13.2.1",
    "expo-background-fetch": "~11.1.1",
    "expo-blur": "~12.2.2",
    "expo-build-properties": "~0.5.1",
    "expo-clipboard": "~4.1.1",
    "expo-community-flipper": "46.0.1",
    "expo-constants": "~14.2.1",
    "expo-dev-client": "~2.1.4",
    "expo-device": "~5.2.1",
    "expo-document-picker": "~11.2.1",
    "expo-file-system": "~15.2.2",
    "expo-font": "~11.1.1",
    "expo-haptics": "~12.2.1",
    "expo-image": "~1.0.0",
    "expo-image-manipulator": "~11.1.1",
    "expo-image-picker": "~14.1.1",
    "expo-linear-gradient": "~12.1.1",
    "expo-linking": "~4.0.1",
    "expo-media-library": "~15.2.2",
    "expo-network": "~5.2.1",
    "expo-next-react-navigation": "^1.2.1",
    "expo-notifications": "~0.18.1",
    "expo-random": "~13.1.1",
    "expo-screen-capture": "~5.1.1",
    "expo-sharing": "~11.2.1",
    "expo-splash-screen": "~0.18.2",
    "expo-status-bar": "~1.4.4",
    "expo-store-review": "~6.2.1",
    "expo-system-ui": "~2.2.1",
    "expo-updates": "~0.16.3",
    "expo-web-browser": "~12.1.1",
    "lodash": "^4.17.21",
    "lottie-ios": "~3.4.0",
    "lottie-react-native": "5.1.4",
    "marked": "^4.2.12",
    "metro-minify-terser": "^0.75.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.71.3",
    "react-native-gesture-handler": "~2.9.0",
    "react-native-ios-context-menu": "1.15.3",
    "react-native-localize": "^2.1.1",
    "react-native-maps": "1.3.2",
    "react-native-mmkv": "2.6.3",
    "react-native-modal-datetime-picker": "14.0.1",
    "react-native-reanimated": "3.0.2",
    "react-native-safe-area-context": "4.5.0",
    "react-native-screens": "~3.20.0",
    "react-native-svg": "13.7.0",
    "react-native-vector-icons": "^9.2.0",
    "react-native-web": "~0.18.11",
    "react-native-webview": "11.26.0",
    "react-responsive-carousel": "^3.2.23",
    "rive-react-native": "4.0.3",
    "sentry-expo": "~6.0.0",
    "stream-chat-expo": "^5.14.1",
    "yarn": "^1.22.10",
    "zeego": "1.4.2"
  }
}
```

**`react-native info` output:**

I'm using Expo, so I'm not sure if this applies, but here:

```
System:
    OS: macOS 13.3.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 31.36 GB / 96.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    Yarn: 1.22.19 - ~/Developer/q1-2023/beatgig-playground/bg-dev/node_modules/.bin/yarn
    npm: 7.19.0 - ~/Developer/q1-2023/beatgig-playground/bg-dev/node_modules/.bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.12.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
 

- **Platform that you're experiencing the issue on**:
    - [ ] iOS
    - [ ] Android
    - [x] **iOS** but have not tested behavior on Android
    - [ ] **Android** but have not tested behavior on iOS
    - [ ] Both
- **`stream-chat-react-native` version you're using that has this issue:**
    - `e.g. 5.4.3`
- Device/Emulator info:
  - [] I am using a physical device
  - OS version: `iOS 16.4.1`
  - Device/Emulator: `iPhone 13 Pro Max`

</p>
</details>

---

### Additional context

---

### Screenshots

Here is a video of what happens:

<video src="https://github.com/GetStream/stream-chat-react-native/assets/13172299/24763564-e240-4ec2-a8a4-978ed718eedd" width="200" />

---

**Comment by nandorojo** [comment]
Additional context: this bug happens even after the "1" goes away from the scroll down button.

**Comment by santhoshvai** [comment]
I am tagging this as a bug because once unread  indicator shows up and seen, it shouldnt be seen again after channel being read.. this kind of flicker shouldnt be happening.. 

@nandorojo If you could please inform us anything specific that you did in your reproduction steps, would be very helpful

**Comment by vanGalilea** [comment]
> Thanks for reaching out @nandorojo that's suboptimal indeed. Those messages should be marked as read, can you validate the following: Does this behaviour occurs only happen when:
> 
> * messages are pinned?
> * sent from the web?

Unread becomes read in our Sample App, in any event...


https://github.com/GetStream/stream-chat-react-native/assets/25864161/cdeac3da-e971-49d8-b2f9-b5ae485097c7

**Comment by vishalnarkhede** [comment]
I am able to reproduce the issue

**Comment by vishalnarkhede** [comment]
@nandorojo @hdparmar28 could you please confirm if the channel that you are testing on is muted?

**Comment by vishalnarkhede** [comment]
I think ideally we shouldn't show that inline unread indicator at all if the channel is muted, since unread count will be 0 in that case.

**Comment by nandorojo** [comment]
I don't remember muting the channel myself ever, so I don't think it was. Unless it could default to being muted
