### ISSUE TITLE
[🐛] channel delete will delete avatars for all users inside the channel

### ISSUE THREAD

**Issue by Bogdastotel** [GetStream/stream-chat-react-native#2114]
Describe your issue here

If I assign a user profile image (avatar) to a user via  await chatClient.partialUpdateUser(update) avatars shows properly in a chatList and on a channel screen (see image below), but if I delete the channel via channel.delete() function then the avatar is deleted both for myself and the user in the channel? why is that so?

```
`const update = {
        id: loggedUser?.username,
        set: {
            image: profileImage
        },
    }
```

    await chatClient.partialUpdateUser(update)`

Steps to reproduce:

1. Go to 'channelList screen'
2. Swipe on the channel from the 'ChatList' screen, then click on delete icon from the swiped 'ChannelPreview' or enter 'OneOnOneChannelScreen' like from the https://github.com/GetStream/stream-chat-react-native/tree/develop/examples/SampleApp example on the ChatList screen
3. Modal for channel deletion will pop up ('Are you sure you want to delete this channel?') [
![image](https://github.com/GetStream/stream-chat-react-native/assets/47041472/66602a96-d4b0-4f13-82ff-dc5b7d9c9d7f)
](url)
4. Confirm delete channel
5. Go back to ChatList screen
6. Channel is no longer there, but if you create a new channel with the same users their avatar images are again the default ones (with the name initials)
  

---

### Expected behavior

channel deletion  action  in channel preview or channel or one on one details screen should NOT delete avatars for both logged in user and the user in a channel

` channel.delete()`

**`react-native info` output:**

```
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1 Pro
    Memory: 99.97 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.5.0 - /usr/local/bin/npm
    Watchman: 2023.01.16.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/bogdastotel/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 28, 29, 30, 31, 32, 33
      Build Tools: 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-32 | Google APIs ARM 64 v8a
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9477386
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.1.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.7 => 0.69.7 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
    - [x] iOS
    - [ ] Android
    - [x] **iOS** but have not tested behavior on Android
    - [ ] **Android** but have not tested behavior on iOS
    - [ ] Both
- **`stream-chat-react-native` version you're using that has this issue:**
    - `5.13.0`
- Device/Emulator info:
  - [ x] I am using a physical device
  - OS version: `ios 16.2`
  - Device/Emulator: `iPhone 14 Pro`

</p>
</details>

---

### Additional context

---

### Screenshots

<details><summary>Click To Expand</summary>
<p>

</p>
</details>

---

**Comment by vanGalilea** [comment]
Hey @Bogdastotel , thanks for reaching out.

The issue you've submitted is missing important information that will help us reproduce and help you solve this issue.
Please follow our [issue template](https://github.com/GetStream/stream-chat-react-native/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md?plain=1) entirely without skipping any parts.

**Comment by Bogdastotel** [comment]
Updated the issue above

**Comment by khushal87** [comment]
Hey @Bogdastotel, is the issue still relevant and reproducible?

**Comment by Bogdastotel** [comment]
Yes, this still happens when you delete the channel. The way around is to
use channel.hide() instead
