### ISSUE TITLE
[🐛] Clicking on the filepicker icon nothing happens

### ISSUE THREAD

**Issue by akilakavinda-ch** [GetStream/stream-chat-react-native#2115]
## Issue

Clicking on the filepicker icon nothing happens

Describe your issue here

I have tried out the gettting started tutorial and created an application, all the other features are working properly but once clicked on the filepicker icon the nothing happens, the expanded input gets closed. The image gallery and camera icons are working properly.
---

#### `package.json`:
{
  "name": "AwesomeProject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@react-native-camera-roll/camera-roll": "^5.4.0",
    "@react-native-community/netinfo": "^9.3.10",
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/stack": "^6.2.1",
    "@stream-io/flat-list-mvcp": "^0.10.3",
    "react": "18.2.0",
    "react-native": "0.71.8",
    "react-native-document-picker": "^9.0.1",
    "react-native-fs": "^2.20.0",
    "react-native-gesture-handler": "^2.10.1",
    "react-native-haptic-feedback": "^2.0.3",
    "react-native-image-crop-picker": "^0.39.0",
    "react-native-image-resizer": "^1.4.5",
    "react-native-reanimated": "^3.1.0",
    "react-native-safe-area-context": "^4.2.5",
    "react-native-screens": "^3.20.0",
    "react-native-share": "^8.2.2",
    "react-native-svg": "^13.9.0",
    "react-native-video": "^5.2.1",
    "stream-chat-react-native": "5.14.1"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native-community/eslint-config": "^3.2.0",
    "@tsconfig/react-native": "^2.0.2",
    "@types/jest": "^29.2.1",
    "@types/react": "^18.0.24",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.2.1",
    "eslint": "^8.19.0",
    "jest": "^29.2.1",
    "metro-react-native-babel-preset": "0.73.9",
    "prettier": "^2.4.1",
    "react-test-renderer": "18.2.0",
    "typescript": "4.8.4"
  },
  "jest": {
    "preset": "react-native"
  }
}

**`react-native info` output:**

System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz
    Memory: 1.40 GB / 7.77 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 30, 31, 33, 33
      Build Tools: 28.0.3, 30.0.3, 33.0.0, 33.0.2
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-221.6008.13.2211.9514443
    Visual Studio: Not Found
  Languages:
    Java: 11.0.16.1
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.8 => 0.71.8 
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

- **Platform that you're experiencing the issue on**:
    - [ ] iOS
    - [] Android
    - [ ] **iOS** but have not tested behavior on Android
    - [x] **Android** but have not tested behavior on iOS
    - [ ] Both
- **`stream-chat-react-native` version you're using that has this issue:**
    - `5.14.1`
- Device/Emulator info:
  - [x]I am using a physical device
  - OS version: `Android 11`
  - Device/Emulator: `Galaxy A21s`

</p>
</details>

**Comment by akilakavinda-ch** [comment]
any updates??

**Comment by khushal87** [comment]
Hey @akilakavinda-ch, did you follow our installation steps for the RN Document Picker library? Do you see any logs on the terminal when you click the button?

**Comment by khushal87** [comment]
I think this issue is related to the new version of `react-native-document-picker` you have in your project. I would recommend you downgrade the version of RN document picker to 8.2.0. There are a couple of API changes in the newer version that we didn't add to our SDK and that might be a crucial reason your document picker isn't working. Can you test it with v8.2.0, please? Thanks 😄

**Comment by akilakavinda-ch** [comment]
Sure will check and give a update!

**Comment by khushal87** [comment]
Any updates @akilakavinda-ch?
