### ISSUE TITLE
File Upload issue in android devices

### ISSUE THREAD

**Issue by 12varun12** [GetStream/stream-chat-react-native#2121]
## Issue

when we click on upload image option and select image for upload but after select image it shows 
"file type not supported"
---

### Steps to reproduce
1) click on file upload icon and after select image click on upload option then 
file not supported option comes

---
### Expected behavior

when we click on any file or image it should be upload successfully

---

### Customization

<details><summary>Click To Expand</summary>
<p>

```typescript jsx
# N/A
```
</p>
</details>

---

### Offline support

- [ ] I have enabled offline support.
- [ ] The feature I'm having does not occur when offline support is disabled. (stripe out if not applicable)

---

## Environment

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

**`react-native info` output:**

"react-native": "0.70.3",
"stream-chat-react-native": "5.6.1",

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
- it occurs in android only
    
- **`stream-chat-react-native` version you're using that has this issue:**
    - `e.g. 5.4.3`
- Device/Emulator info:
  all devices

</p>
</details>

---

### Additional context

---

### Screenshots

<details><summary>Click To Expand</summary>
<p>

</p>
<img width="456" alt="Screenshot 2023-05-25 at 2 51 09 PM" src="https://github.com/GetStream/stream-chat-react-native/assets/96221152/bf94679d-33a7-4111-bfac-e8a2242c0f77">

</details>

---

**Comment by vanGalilea** [comment]
@12varun12 tnx for reaching out, please share the file you're trying to upload and your upload configuration you have set via the dashboard (https://dashboard.getstream.io/app/{{FILL_IN_YOUR_APP_ID}}/chat/overview  >> Upload Configuration
\>> Files/Images)

**Comment by faisalkhan-dianapps** [comment]
hey @vanGalilea  Yes you are right, after updating configuration in dashboard its working fine

**Comment by 12varun12** [comment]
thanks  @vanGalilea for your help and support
