### ISSUE TITLE
App got crashed when we click on stream push notification

### ISSUE THREAD

**Issue by 12varun12** [GetStream/stream-chat-react-native#2122]
## Issue

Describe your issue here

when we click on stream push notification then app is crashing but it work proper before after we live chat feature after 2 days this issue happen .
when we click on notification we got some error :-
---error occ TypeError: parsedDate.calendar is not a function
    at MessageSystem (MessageSystem.tsx:80:20)
    at renderWithHooks (ReactNativeRenderer-dev.js:10768:18)
    at mountIndeterminateComponent (ReactNativeRenderer-dev.js:14700:13)
    at beginWork (ReactNativeRenderer-dev.js:16509:14)
    at beginWork$1 (ReactNativeRenderer-dev.js:22265:14)
    at performUnitOfWork (ReactNativeRenderer-dev.js:21413:12)
    at workLoopSync (ReactNativeRenderer-dev.js:21340:5)
    at renderRootSync (ReactNativeRenderer-dev.js:21311:7)
    at performSyncWorkOnRoot (ReactNativeRenderer-dev.js:20962:20)
    at flushSyncCallbacks (ReactNativeRenderer-dev.js:6262:22)

when we comment MessageList from our code then this issue not comes, so please can you help out from this issue this very urgent, because this issue happen in live.

### Steps to reproduce
1) click on stream push notification
2) we have implemented redirection on click on push notification
3) It redirect to Message screen where MessageList is implemented
4) redirection is done but due to MessageList app is crashing

---

### Expected behavior

when we click on stream push notification it redirect to particular group or one to one chat

---

### Customization
we have done some customization in MessageList
code :- 
<View style={styles.container}>
            <Channel
                channel={updatedChannel}
                SendButton={StreamButton}
                DateHeader={HandleDateHeader}
                EmptyStateIndicator={handleEmptyState}
                messageActions={handleMessageAction}
                disableIfFrozenChannel={false}
                initialScrollToFirstUnreadMessage={true}
                LoadingErrorIndicator={() => null}
                keyboardVerticalOffset={Platform.OS === 'ios' ? 90 : undefined}
                AutoCompleteSuggestionItem={({itemProps, triggerType}) => {
                    if (triggerType === 'mention') {
                        return null;
                    }
                }}
                AutoCompleteSuggestionList={({
                    data,
                    onSelect,
                    queryText,
                    triggerType,
                }) => {
                    if (triggerType === 'mention') {
                        return null;
                    }
                }}>
                <MessageList
                    InlineDateSeparator={handleDateSeperator}
                    isListActive={true}
                />
                <MessageInputHandling />
            </Channel>
        </View>

```typescript jsx
# N/A
```
</p>
</details>

---

### Offline support

- [ ] I have enabled offline support.
- [ ] The feature I'm having does not occur when offline support is disabled. (stripe out if not applicable)

---

## Environment

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

**`react-native info` output:**
"react-native": "0.70.3",
"stream-chat-react-native": "5.6.1",
```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
    - [ ] Both
- **`stream-chat-react-native` version you're using that has this issue:**
   "stream-chat-react-native": "5.6.1",
- Device/Emulator info:
in all physical devices
</p>
</details>

---

### Additional context

---

### Screenshots

<details><summary>Click To Expand</summary>
<p>

</p>
</details>
![BA8C0190-E681-4460-BFB2-7583A88F451D](https://github.com/GetStream/stream-chat-react-native/assets/96221152/8e32b3ba-ec2d-48be-a9a4-1fb007875070)

---

**Comment by santhoshvai** [comment]
Do you have moment or DayJs depdencies in your app? 

please look at https://getstream.io/chat/docs/sdk/reactnative/basics/translations/#overriding-datetime-format

If you use English language for date-times in Stream components, you can set `disableDateTimeTranslations` to true. And this might solve your crash

**Comment by 12varun12** [comment]
Yes we are using moment for dateheader and dateseperator in MessageList
component

**Comment by 12varun12** [comment]
where we have to add disableDateTimeTranslations in our code

**Comment by santhoshvai** [comment]
Please read our [docs](https://getstream.io/chat/docs/sdk/reactnative/basics/translations) to get a better understanding of how to implement translations 

The disableDateTimeTranslations is an option inside [Streami18n](https://getstream.io/chat/docs/sdk/reactnative/basics/translations/#disabledatetimetranslations).

**Comment by vanGalilea** [comment]
I'll be closing this issue for now.
Please don't hesitate to contact us in the future if this issue or any questions arise.
