### ISSUE TITLE
Message screen threads is not update when we open other channel

### ISSUE THREAD

**Issue by 12varun12** [GetStream/stream-chat-react-native#2124]
## Issue

Describe your issue here

when we open one channel and close it and then we open different channel then it is not updated at that time it shows the threads of previous one channel.

### Steps to reproduce
1) click on one channel and close it 
2) open another channel then the message threads is vissible but message thread is from previous channel not from currently opened channel

---

### Expected behavior

when we click on different channel then the message thread must be updated according to the channel

---

### Customization
I have customise the message screen, but not the whole screen we customise Empty screen state, date header, date separator that's it.

<details><summary>Click To Expand</summary>
<p>

```typescript jsx
# N/A
```
</p>
</details>

---

### Offline support

- [ ] I have enabled offline support.
- [ ] The feature I'm having does not occur when offline support is disabled. (stripe out if not applicable)

---

## Environment

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

**`react-native info` output:**

"react-native": "0.70.3",

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
    issue in Both devices

- **`stream-chat-react-native` version you're using that has this issue:**
   "stream-chat-react-native": "5.14.1"

- Device/Emulator info:
  for all devices in android and ios

</p>
</details>

---

### Additional context

---

### Screenshots

<details><summary>Click To Expand</summary>
<p>

</p>
</details>

---

**Comment by khushal87** [comment]
Hey @12varun12 we're not able to reproduce this behaviour on our side. Can you please check if you pass the correct channel and message id when navigating?

**Comment by 12varun12** [comment]
We are passing correct data before navigation, actually before MessageList
component i have applied console.log and we got correct channel but there
is no changes occurs in MessageList component
It show old channel

**Comment by 12varun12** [comment]
can you please provide me any solution because it's urgent

**Comment by khushal87** [comment]
Hey, can you share a video of what is happening so we can look into it further? Did you follow our [tutorial](https://getstream.io/chat/react-native-chat/tutorial/) while creating the app? Also, please check if your code and navigation logic looks similar to [this](https://github.com/GetStream/stream-chat-react-native/blob/develop/examples/TypeScriptMessaging/App.tsx#L131) and also don't forget to dismount the component like [this](https://github.com/GetStream/stream-chat-react-native/blob/develop/examples/TypeScriptMessaging/App.tsx#L172).

Documentation for `onThreadDismount` is present [here](https://getstream.io/chat/docs/sdk/reactnative/ui-components/thread/#onthreaddismount).

**Comment by faisalkhan-dianapps** [comment]
hey @khushal87 

This issue is coming for different cases as well.
1. Open any user chat thread >> Background/Foreground >> The chat thread is not updated when the user clicks on the push notification. Currently, only the user name is updated
https://drive.google.com/file/d/1SofMAeG8avszlTOahc_5duYPWG8ZYAyv/view?usp=sharing

2. Chat thread is not updated when the user opens the chat push notification
https://drive.google.com/file/d/1uLy049ceb0IEx2phw9VuT-ZlXHDQl1CR/view?usp=sharing

I am attaching videos for all three issues, Do let us know to incase you need any other information for the same

**Comment by 12varun12** [comment]
https://github.com/GetStream/stream-chat-react-native/assets/96221152/ca615164-2e79-4ff9-97dd-9abf097a32f6

I have added one video related to message thread issue, we are facing the issue where we pass the channel but the threads are not updated on the message detail screen. When we send the message then the screen gets updated and all the messages gets appear. 

Can you please look into it on high priority?

**Comment by 12varun12** [comment]
Hey team,
    Any update on it

**Comment by vishalnarkhede** [comment]
Hey @12varun12 @faisalkhan-dianapps to investigate this any further, we would need some code snippets of your implementation. You can share code snippets with support@getstream.io

- code around navigation from channel list to channel screen
- code around `Channel` component

**Comment by 12varun12** [comment]
ok will share with you
