### ISSUE TITLE
Keyboard taps not persisting android

### ISSUE THREAD

**Issue by arthurgeron-work** [GetStream/stream-chat-react-native#2125]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

While on Android I'm unable to select channels from channel list when the keyboard is up (e.g. filtering the list).

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `stream-chat-react-native-core@5.15.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/stream-chat-react-native-core/src/components/ChannelList/ChannelListMessenger.tsx b/node_modules/stream-chat-react-native-core/src/components/ChannelList/ChannelListMessenger.tsx
index 2993ef2..69183fa 100644
--- a/node_modules/stream-chat-react-native-core/src/components/ChannelList/ChannelListMessenger.tsx
+++ b/node_modules/stream-chat-react-native-core/src/components/ChannelList/ChannelListMessenger.tsx
@@ -190,6 +190,7 @@ const ChannelListMessengerWithContext = <
         renderItem={renderItem}
         style={[styles.flatList, { backgroundColor: white_snow }, flatList]}
         testID='channel-list-messenger'
+        keyboardShouldPersistTaps="always"
         {...additionalFlatListProps}
       />
       <StatusIndicator<StreamChatGenerics> />
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by vanGalilea** [comment]
Hey @arthurgeron-work thanks for reaching out no patching is needed.
Just specify it as part of the additionalFlatLIstProps- see [docs](https://getstream.io/chat/docs/sdk/reactnative/ui-components/message-list/#additionalflatlistprops)

In your case
```
const flatListProps = { keyboardShouldPersistTaps: true };

<MessageList additionalFlatListProps={flatListProps} />;
```
