### ISSUE TITLE
[🐛] Issues With Asset Mime Type Validations

### ISSUE THREAD

**Issue by MxBM** [GetStream/stream-chat-react-native#2131]
**Describe the bug**:
There are incredibly odd interactions occurring with my MessageInput component, particularly with the ImageUploadPreview component. It would appear that when offlineSupport is enabled in conjunction with uploading an asset with an invalid mime type, (denoted by the error "File type ____ not supported") still allows for the uploading of said failed asset. This leads to an interesting case where the asset appears to be actually uploaded as the Card component for the asset preview is rendered inside of the MessageList. Upon clicking the preview though, the user gets a crash (Refer below for video). There are various issues with mime type validations as well, for instance, my entire application utilizes a single Chat instance through context (as advised in the docs when upgrading to V5 refer here: https://getstream.io/chat/docs/sdk/reactnative/basics/upgrading-from-v4/) however different Channels have different mime type validations occurring. For instance on Channel A I can't upload an mov file and get the client side error on the preview stating "File type not supported" however I upload the same video on a different channel and it allows me to upload it with no error. The AppSettings set on the Dashboard doesn't block any specific mime types either. Any idea why this is occurring? 

App Crashing with offline mode enabled and bypassing mime type validation on asset:
https://github.com/GetStream/stream-chat-react-native/assets/96575525/9f43e17e-bc6e-4ab2-b768-8ee4615502ba

Mime Type Validation Issues On Different Channels:
![IMG_6403](https://github.com/GetStream/stream-chat-react-native/assets/96575525/6082d167-3318-4343-a2b9-3dee7bfd35dc)
![IMG_6404](https://github.com/GetStream/stream-chat-react-native/assets/96575525/25e10b68-f20f-4195-94fa-b9869cf540b9)

- Package version (stream-chat-react-native/stream-chat-expo):    "stream-chat-react-native": "^5.11.2"
- react-native or expo version: React Native 
- Device/Emulator (android/ios) and OS version: iPhone 12 pro running I.OS 15.4.1

**Comment by vanGalilea** [comment]
Hey @MxBM thanks for reaching out.

The issue you've submitted is missing important information that will help us reproduce and help you solve this issue.
Please follow our [issue template](https://github.com/GetStream/stream-chat-react-native/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md?plain=1) entirely without skipping any parts.

**Comment by khushal87** [comment]
Hello @MxBM just to know, can you provide us with your app id, so that we can have a look on our side?

And, are you sure both the channels are of same type?

**Comment by vanGalilea** [comment]
@MxBM hi there 👋🏻 can you elaborate on why you closed this issue? Did you manage to solve this matter?
