### ISSUE TITLE
Token Error:  {"code":5,"StatusCode":401,"message":"WS failed with code 5 and reason - JWTAuth error: json: cannot unmarshal number into Go struct field StreamJWTClaims.user_id of type string","isWSFailure":false}

### ISSUE THREAD

**Issue by theRealSheng** [GetStream/stream-chat-react-native#214]
**Describe the bug**
I get the following error after chatClient.setUser(user, token)

{
"code":5,
"StatusCode":401,
"message":"WS failed with code 5 and reason - JWTAuth error: json: cannot unmarshal number into Go struct field StreamJWTClaims.user_id of type string",
"isWSFailure":false
}

**Dev environment info (please complete/provide the following information):**
    "react": "16.9.0",
    "react-native": "^0.61.4",
    "stream-chat": "^1.11.0",
    "stream-chat-react-native": "^0.10.3",

     IOS

**To Reproduce**
1) Create ChatContext 

` export const ChatStreamContext = createContext(null);

  const ChatStreamContextProvider = (props) => {
  const [ chatClient, setChatClient ] = useState(null);
  const [ chatReady, setChatReady ] = useState(false);
  const [ filters, setFilters ] = useState({});

  const initChat = () => { setChatClient(new StreamChat('XXXXX')) };

  const setUser = async (user, userToken) => {
    try {
      await chatClient.setUser(user, userToken);
      setChatReady(true);
    } catch (e) {
      console.warn('ChatStreamContextProvider/setUser:', e)
    }
  }

  const onFilterChat = (filters) => {
    setFilters(filters);
  }

  return (
    <ChatStreamContext.Provider value={{ 
      theme: {},
      chatClient,
      chatReady,
      filters,
      initChat,
      setUser,
      onFilterChat
    }}>
      {props.children}
    </ChatStreamContext.Provider>
  )
}

export default ChatStreamContextProvider;`

2) Add ChatStreamContextProvider to Navigation so it can be access anywhere in app.
3) Import { ChatStreamContext } from './path to tile' to child route.
4) useContext for Funcion Component. Add static contextType = ChatStreamContext;
5) Call this.context.setUser(user, token)

**Expected behavior**
No errors.

**Comment by vishalnarkhede** [comment]
Hey @theRealSheng currently we don't support integer as user_id! Its in our backlog though!
