### ISSUE TITLE
[🐛] SampleApp Run Error

### ISSUE THREAD

**Issue by HLM-yumonnaing** [GetStream/stream-chat-react-native#2151]
### GetStream Sample App Err
> Task :react-native-quick-sqlite:buildCMakeDebug[arm64-v8a] FAILED

### Download Link
https://github.com/GetStream/stream-chat-react-native/tree/develop/examples/SampleApp

### Image
![image](https://github.com/GetStream/stream-chat-react-native/assets/123156566/8f6f90ab-527b-43d0-8c85-a098025ffe23)

Could you please support to me with this error solutions.
Looking for your favorable suggestions.

**Comment by vanGalilea** [comment]
Hello @HLM-yumonnaing thanks for reaching out, when did the error occur, can you please be more specific?

**Comment by HLM-yumonnaing** [comment]
Hello,

we are try to run getstream sampleApp but found this sqlite error and cannot build successful.

task :react-native-quick-sqlite:buildcmakedebug[arm64-v8a] failed

https://github.com/GetStream/stream-chat-react-native/assets/123156566/f8ffda59-aa1a-4008-ae7e-4f86ea476a9b

**Comment by vanGalilea** [comment]
This seems like a windows related error to me, let us get back to you on that.

**Comment by logan17** [comment]
Hi @HLM-yumonnaing, What is the solution for this issue?
