### ISSUE TITLE
🔥 [🐛] Android : OverlayReactions are unresponsive and cannot be tapped out of

### ISSUE THREAD

**Issue by matmartic** [GetStream/stream-chat-react-native#2152]
## Issue

Stream chat works normally on both ios/android, and on ios the reactions overlay works fine, reactions can be chosen, and the overlay can be dismissed. On Android nothing can be clicked and you need the native back button to close the overlay because tapping out does nothing. 

---

### Steps to reproduce

Open Stream chat on a RN app on Android
Long press until overlay appears 
Try clicking anything (see video at the bottom of the ticket)

---

### Expected behavior

I would expect the same behaviour as on ios, that it can be interacted with, and that it can be tapped out of.

---

### Customization

<details><summary>Click To Expand</summary>
<p>

```typescript jsx
MessageList
```
</p>
</details>

---

### Offline support

- [ ] I have enabled offline support.
~~- [ ] The feature I'm having does not occur when offline support is disabled. (stripe out if not applicable)~~

---

## Environment

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
    "expo": "~48.0.18",
    "stream-chat": "^8.9.0",
    "stream-chat-expo": "^5.15.1",
    "react-native": "0.71.8",

```

**`react-native info` output:**

```
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
    Memory: 72.78 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
    Watchman: 2023.02.27.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /opt/homebrew/lib/ruby/gems/3.1.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 28, 29, 30, 31, 32, 33
      Build Tools: 30.0.2, 30.0.3, 31.0.0, 33.0.0, 34.0.0
      System Images: android-31 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.8 => 0.71.7
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
    - [ ] iOS
    - [x] Android
    - [ ] **iOS** but have not tested behavior on Android
    - [ ] **Android** but have not tested behavior on iOS
    - [ ] Both
- **`stream-chat-react-native` version you're using that has this issue:**
    - `    "stream-chat-expo": "^5.15.1",`
- Device/Emulator info:
  Tested on multiple emulators and physical devices, android 11 and 12 for both

</p>
</details>

---

### Additional context

---

### Screenshots

<details><summary>Click To Expand</summary>
<p>

This video clip shows the behaviour, you don't see the clicking but I am clicking frantically just to get any reaction
https://github.com/GetStream/stream-chat-react-native/assets/15280410/96520afa-da2f-4b75-a72a-7c925099284a

</p>
</details>

---

**Comment by sidorchukandrew** [comment]
I'm experiencing this too. I'm on version `5.15.0`

**Comment by sidorchukandrew** [comment]
I fixed my issue. You need to make sure the `<OverlayProvider />` is inside the `<GestureHandlerRootView />`

```
<OverlayProvider>
   <GestureHandlerRootView>
      ...
   </GestureHandlerRootView/>
</OverlayProvider >
```

**Comment by matmartic** [comment]
hey @sidorchukandrew thanks that fixed the issue! But I think you typo'ed your example, bc your code puts GestureHandlerRootView inside OverlayProvider, whereas it's the opposite (just like what you wrote) :)

Thanks a lot!

**Comment by sidorchukandrew** [comment]
Oh you're right! Good catch!

**Comment by adenta-grandstand** [comment]
In case anyone else finds this thread while troubleshooting- My issues were solved by removing `import 'react-native-gesture-handler';` from my entrypoint. This is in direct contradiction to the docs on [this](https://getstream.io/chat/docs/sdk/reactnative/) page.
