### ISSUE TITLE
Customize size of send button icons

### ISSUE THREAD

**Issue by sidorchukandrew** [GetStream/stream-chat-react-native#2153]
**Motivation**
It is possible to specify the size of the send button through the theme, but setting width and height on the send button does not change the size of the icons inside (SendRight and SendUp). It is frustrating I have to create my own `<SendButton />` just so I can specify I want the icons to be 30 instead of 24. 

**Proposed solution**
Include additional theme overrides under `messageInput.sendButton` for `sendRight` and `sendUp`.

**Comment by khushal87** [comment]
Hey @sidorchukandrew, thanks for bringing this up. We were able to reproduce it and currently:

```
 messageInput: {
  sendButton: {
    height: 100,
    width: 100,
  },
},
```

this snipped only works on the container of those icons and not the icon, hence we will try to look into it soon and fix it.
