### ISSUE TITLE
[🐛] Keyboard Blocks half of text input field. [ANDROID ONLY]

### ISSUE THREAD

**Issue by prakashawal** [GetStream/stream-chat-react-native#2154]
## Issue
During chat, when trying to chat Keyboard blocks half of the input field. This happens only in Android. In iOS, it works fine.

### Steps to reproduce

1. Go to Chat Screen
2. Keyboard opens, and blocks half of the input field.

### Expected behavior
When the keyboard opens, the keyboard should not block the input field. The top of the keyboard view must be bottom of the message input.

### Customization

<details><summary>Click To Expand</summary>
<p>

```typescript jsx
# N/A
```
</p>
</details>

---

### Offline support

- [ ] I have enabled offline support.
- [ ] The feature I'm having does not occur when offline support is disabled. (stripe out if not applicable)

---

## Environment

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
    - [ ] iOS
    - [ ] Android
    - [ ] **iOS** but have not tested behavior on Android
    - [ ] **Android** but have not tested behavior on iOS
    - [ ] Both
- **`stream-chat-react-native` version you're using that has this issue:**
    - `e.g. 5.4.3`
- Device/Emulator info:
  - [ ] I am using a physical device
  - OS version: `e.g. Android 10`
  - Device/Emulator: `e.g. iPhone 11`

</p>
</details>

---

### Additional context

---

### Screenshots

<details><summary>Click To Expand</summary>
<p>

</p>
</details>

---

**Comment by KrushitaBhanderi** [comment]
I solved this problem by adding `android:windowSoftInputMode="adjustResize"` in AndroidManifst.xml file.

**Comment by prakashawal** [comment]
> 

Thank you. This works fine.
