### ISSUE TITLE
Allow to set message padding

### ISSUE THREAD

**Issue by scaraux** [GetStream/stream-chat-react-native#2158]
https://github.com/GetStream/stream-chat-react-native/blob/c64a6d5e8de335d2057f463b42fa460dc0f3c5bb/package/src/components/MessageList/MessageList.tsx#L86

It's currently impossible to style the `messagePadding` through the theme. What if we want to set a padding lesser than 8 pixels ? I'd like this to be configurable.

**Comment by khushal87** [comment]
Hey @scaraux, thanks for pointing it out. You are correct that, currently, there's no direct way of customizing the property. But to help you with this, the `messagePadding` property is passed to `MessageSystem` and `Message`. So, for `MessageSystem` you can use the following to customize the padding:
```
theme: {messageList:{messageSystem:{container:{padding:5}}}}
```
For Message, I think you will have to customize the component to achieve it. You can have a look into the implementation of the Message/MessageSimple component and use the property to improve the padding.

We will try to add the property to the theme in the future. Thanks for pointing it out. 😄
