### ISSUE TITLE
Mapping the searched lists to the context

### ISSUE THREAD

**Issue by cleandevcode** [GetStream/stream-chat-react-native#2162]
Hi.
I am working on filtering channels by search key.

With the help of `client.search`, seems I could get the lists where I wanna find the channel including the search query.

It's my code
```
const filter = {
    members: { $in: [user?.id] },
 }
const searchResults = await chatClient.search(filter, searchKey)
```

Btw I am using the default `ChannelList` from `stream-chat-react-native`. Then is there any way to map the searched results to the channel list?

**Comment by vanGalilea** [comment]
> Btw I am using the default ChannelList from stream-chat-react-native. Then is there any way to map the searched results to the channel list?

`ChannelList` internally fetches a list of channels using the [client's query channels function](https://getstream.io/chat/docs/javascript/query_channels/?language=javascript); to which you can pass the [filters](https://getstream.io/chat/docs/sdk/reactnative/core-components/channel-list/#filters), [sort](https://getstream.io/chat/docs/sdk/reactnative/core-components/channel-list/#sort) and [options](https://getstream.io/chat/docs/sdk/reactnative/core-components/channel-list/#options) parameters via props on `ChannelList`.

More info in our [docs](https://getstream.io/chat/docs/sdk/reactnative/core-components/channel-list/)

In your case, I will suggest using the `filters` prop to filter what's relevant for your use case.
More info about common filters can be found in our [docs](https://getstream.io/chat/docs/javascript/query_channels/?language=javascript#common-filters-by-use-case).

Thanks for reaching out and I'll be closing this issue. Feel free to ask more questions if needed 👋🏻

**Comment by cleandevcode** [comment]
@vanGalilea Thanks for your message. I already checked the filters props, but could not find the proper solution by using `filters`.
Can you show me an example `filters` to filter by content search?
