### ISSUE TITLE
[🐛] [Error: {"code":5,"StatusCode":401,"message":"WS failed with code 5 and reason - Connect failed with error: \"Token signature is invalid\"","isWSFailure":false}]

### ISSUE THREAD

**Issue by asRizvi888** [GetStream/stream-chat-react-native#2171]
## Issue

I got this error when connecting user with `connectUser()` method. I'm generating token using nodeJS backend. The token creation is behaving ok, but still the issue arises. Even using dev token is giving me the exact same error.
---

### Steps to reproduce

   etc...

---

### Expected behavior

It is expected to connect the user to chatClient and then I am supposed to create channel. But it fails to connect user raising this error.
---

### Customization

<details><summary>Click To Expand</summary>
<p>

```typescript jsx
# N/A
```
</p>
</details>

---

### Offline support

- [ ] I have enabled offline support.
- [ ] The feature I'm having does not occur when offline support is disabled. (stripe out if not applicable)

---

## Environment

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
    - [ ] iOS
    - [ ] Android
    - [ ] **iOS** but have not tested behavior on Android
    - [ ] **Android** but have not tested behavior on iOS
    - [x] Both
- **`stream-chat-react-native` version you're using that has this issue:**
    - "stream-chat": "^8.4.1",
    - "stream-chat-react-native": "^5.15.2",
    - "stream-chat-react-native-core": "^5.12.0"
- Device/Emulator info:
  - [ ] I am using a physical device
  - OS version: `e.g. Android 10`
  - Device/Emulator: `e.g. iPhone 11`

</p>
</details>

---

### Additional context

---

### Screenshots

<details><summary>Click To Expand</summary>
<p>

</p>
</details>

---

**Comment by kaustubhrastogi** [comment]
Getting this error while connecting with stream-chat 
Using: Stream chat v4
[Error: {"code":5,"StatusCode":401,"message":"WS failed with code 5 and reason - Connect failed with error: \"Token signature is invalid\"","isWSFailure":false}]

**Comment by icybergenome** [comment]
@mishkeTz and @kaustubhrastogi 
yes for now at least it starts to work again using `browser: false`:
```
const serverClient = StreamChat.getInstance(apiKey, apiSecret, {
        browser: false,
      });
```

**Comment by asRizvi888** [comment]
> 

In my case StreamChat.getInstance() was getting called multiple times. Make sure that it only gets called once.

**Comment by oslim4321** [comment]
Hello how was this issue resolve

**Comment by oslim4321** [comment]
const serverClient = StreamChat.getInstance(
    process.env.NEXT_PUBLIC_APP_KEY || '',
    process.env.NEXT_PUBLIC_APP_SECRET,
    {
      browser: false,
    },
  );

I fix mine now, i was misplacing the appKey and secret, the app id should come first then the secret

**Comment by Sayangenri** [comment]
{"code":43,"StatusCode":401,"message":"WS failed with code 43 and reason - JWTAuth error: signature is not valid. Make sure the token is created using the secret for API key \"adbnguxepj9k\"","isWSFailure":false}
    at StableWSConnection._callee$ (http://localhost:3000/static/js/bundle.js:41554:23)
    at tryCatch (http://localhost:3000/static/js/bundle.js:52486:16)
    at Generator.<anonymous> (http://localhost:3000/static/js/bundle.js:52574:17)
    at Generator.throw (http://localhost:3000/static/js/bundle.js:52515:21)
    at asyncGeneratorStep (http://localhost:3000/static/js/bundle.js:54211:17)
    at _throw (http://localhost:3000/static/js/bundle.js:54228:9)
