### ISSUE TITLE
🔥 Display users name in MessageFooter

### ISSUE THREAD

**Issue by fzf** [GetStream/stream-chat-react-native#2185]
## Issue

Describe your issue here

I am trying to follow [this](https://github.com/GetStream/stream-chat-react-native/wiki/Cookbook-(2.x.x)#message-bubble-with-name-of-sender) guide to add the users name to the footer for a message, preferably at the bottom of a group of messages. It seems like showing the user name should be default behavior if I look at examples like [social messaging](https://getstream.io/chat/demos/messaging/) from react examples or the [Message bubble with name of sender​](https://getstream.io/chat/docs/sdk/reactnative/guides/message-customization/) section for message customization shows users names in Standard Footer. I tried to follow the [MessageFooter](https://getstream.io/chat/docs/sdk/reactnative/ui-components/message-footer/) section but no matter what I do it does not have any reference to message which is where I would get the users name.
---

### Steps to reproduce

This code properly adds the users name to the header of the message.
```
              <Channel
                MessageHeader={(props) =>
                  <View
                    style={{ flexDirection: 'row' }}
                  >
                    {
                      props.message.user?.name ? (
                        <Text style={[{ color: 'grey', marginRight: 8 }]}>
                          {props.message.user.name}
                        </Text>
                      ) : null
                    }
                    <Text style={[{ color: 'grey', textAlign: props.alignment }]}>
                      {props.formattedDate}
                    </Text>
                  </View>
                }
                MessageFooter={() => null}
              />
```
This code fails because message is undefined:
```
              <Channel
                MessageFooter={(props) =>
                  <View
                    style={{ flexDirection: 'row' }}
                  >
                    {
                      props.message.user?.name ? (
                        <Text style={[{ color: 'grey', marginRight: 8 }]}>
                          {props.message.user.name}
                        </Text>
                      ) : null
                    }
                    <Text style={[{ color: 'grey', textAlign: props.alignment }]}>
                      {props.formattedDate}
                    </Text>
                  </View>
                }
              />
```
---

### Expected behavior

I would expect message to be passed into the MessageFooter through props.
---

### Customization

<details><summary>Click To Expand</summary>
<p>

```typescript jsx
# N/A
```
</p>
</details>

---

### Offline support

- [ ] I have enabled offline support.
- [ ] The feature I'm having does not occur when offline support is disabled. (stripe out if not applicable)

---

## Environment

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
    "sentry-expo": "~6.2.0",
    "stream-chat": "^8.10.0",
    "stream-chat-expo": "^5.15.1",
    "stream-chat-react": "^10.8.5"
```

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
    - [ ] iOS
    - [ ] Android
    - [ ] **iOS** but have not tested behavior on Android
    - [ ] **Android** but have not tested behavior on iOS
    - [ ] Both
- **`stream-chat-react-native` version you're using that has this issue:**
    - `e.g. 5.4.3`
- Device/Emulator info:
  - [ ] I am using a physical device
  - OS version: `e.g. Android 10`
  - Device/Emulator: `e.g. iPhone 11`

</p>
</details>

---

### Additional context

---

### Screenshots

<details><summary>Click To Expand</summary>
<p>

</p>
</details>

---

**Comment by khushal87** [comment]
Hey @fzf, I understand your problem but until then, you can also use the `message` data from the `useMessageContext` hook and use it to show the data for your message footer component.

**Comment by vishalnarkhede** [comment]
@fzf the guide that you are referring has been deprecated for quite some time now. Please refer to our official documentation website - https://getstream.io/chat/docs/sdk/reactnative/guides/message-customization/#message-bubble-with-name-of-sender

And as Khushal mentioned, you can access message data using useMessageContext hook.
