### ISSUE TITLE
[🐛] Bug Report Title - Cant Autoplay

### ISSUE THREAD

**Issue by adenta-grandstand** [GetStream/stream-chat-react-native#2186]
## Issue

When you tap on a video, you have to tap 'play' again. There should be a setting to autoplay videos after the first tap. I hacked together something in the demo app [here](https://github.com/adenta-grandstand/stream-chat-react-native/commit/66d1ea5f799d5e7989d1588b57636d9f50c34886) that _almost_ works. In the included repository, the video starts playing immediately, but the play/pause button is out of sync, until you tap play twice.

https://github.com/GetStream/stream-chat-react-native/assets/133894420/09bf1484-3ad8-4691-a198-10eb53656537

---

### Steps to reproduce
click on a video
notice how it does not autoplay

---

### Expected behavior

The videos should autoplay.
---

### Customization

<details><summary>Click To Expand</summary>
<p>

```typescript jsx
# N/A
```
</p>
</details>

---

### Offline support

- [ ] I have enabled offline support.
- [ ] The feature I'm having does not occur when offline support is disabled. (stripe out if not applicable)

---

## Environment

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
    - [ ] iOS
    - [ ] Android
    - [ ] **iOS** but have not tested behavior on Android
    - [ ] **Android** but have not tested behavior on iOS
    - [ ] Both
- **`stream-chat-react-native` version you're using that has this issue:**
    - `e.g. 5.4.3`
- Device/Emulator info:
  - [ ] I am using a physical device
  - OS version: `e.g. Android 10`
  - Device/Emulator: `e.g. iPhone 11`

</p>
</details>

---

### Additional context

---

### Screenshots

<details><summary>Click To Expand</summary>
<p>

</p>
</details>

---

**Comment by khushal87** [comment]
Hey @adenta-grandstand, we understand that the autoplay should work automatically, therefore, this issue seems more to be a feature request, than a bug. We will try to add this feature in the future. Meanwhile, you can try to raise a PR with a solution(if you have any) on your mind, making sure everything works as expected. We will be happy to look into it. Thanks 😄

**Comment by adenta** [comment]
Hey Khushal,

I probably should've made this a feature request. When it's 9PM on a Friday and you are banging your head against a keyboard, everything is a bug.

Want to close this out?

I'm not going to have time to make a PR to give everyone Autoplay, but found out I can override the built-in video controls with 

```
    <OverlayProvider
      imageGalleryCustomComponents={{
        footer: {
          videoControlElement: () => {
            return <Text>helllo, world!</Text>;
          },
        },
      }}
    >
...
```


This was so hard to suss out, so I'm glad the internet now has a documented example of how to go about solving this problem.
