### ISSUE TITLE
[🐛] The messageTextNumberOfLines works only for single paragraph and not for multiple paragraphs

### ISSUE THREAD

**Issue by khushal87** [GetStream/stream-chat-react-native#2188]
## Issue

The `messageTextNumberOfLines` currently only works for a single paragraph and doesn't apply to messages text with multiple paragraphs.

Describe your issue here

Ref - https://getstream.zendesk.com/agent/tickets/38841

---

### Steps to reproduce

1. Go to ChannelList Screen
2. Paste a long message with multiple paragraphs. 
3. Long press on the message.
4. With the messageTextNumberOfLines value added in the prop, the text truncation only applies to a single paragraph.

---

### Expected behavior

It should truncate the entire text.

---

### Customization

<details><summary>Click To Expand</summary>
<p>
Do not forget to add the value for the prop `messageTextNumberOfLines`.

</p>
</details>

---

### Offline support

- [ ] I have enabled offline support.
- [ ] The feature I'm having does not occur when offline support is disabled. (stripe out if not applicable)

---

## Environment

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
    - [ ] iOS
    - [ ] Android
    - [ ] **iOS** but have not tested behavior on Android
    - [ ] **Android** but have not tested behavior on iOS
    - [ ] Both
- **`stream-chat-react-native` version you're using that has this issue:**
    - `e.g. 5.4.3`
- Device/Emulator info:
  - [ ] I am using a physical device
  - OS version: `e.g. Android 10`
  - Device/Emulator: `e.g. iPhone 11`

</p>
</details>

---

### Additional context

---

### Screenshots

<details><summary>Click To Expand</summary>
<p>

</p>
</details>

---

**Comment by vishalnarkhede** [comment]
The fix is available in `5.18.1-beta.2` !!
