### ISSUE TITLE
How to fix this error

### ISSUE THREAD

**Issue by MuGGYStyle** [GetStream/stream-chat-react-native#22]
<img width="350" alt="Screen Shot 2019-05-31 at 12 31 40 PM" src="https://user-images.githubusercontent.com/12180195/58681714-304efe00-83a0-11e9-944b-28e1617c5310.png">

when i send link message

**Comment by vishalnarkhede** [comment]
@MuGGYStyle its fixed in latest versions. You can use v0.1.3 or latest one.
