### ISSUE TITLE
[🐛] RegExp bug (user name)

### ISSUE THREAD

**Issue by mishkeTz** [GetStream/stream-chat-react-native#2208]
## Issue

The app breaks if the user name contains special characters.

Line that breaks the code:

`useLatestMessagePreview.ts`

`
const mentionedUsers = getMentionUsers(message.mentioned_users);
const regEx = new RegExp(`^(${mentionedUsers})`);
`

example of ` message.mentioned_users` that will break the RegExp

`[{"banned": false, "created_at": "2023-04-25T09:19:40.933336Z", "id": "123123", "image": "https://some-url", "last_active": "2023-08-08T14:05:24.400094Z", "name": "Name :)", "online": false, "role": "user",  "updated_at": "2023-08-07T20:31:58.690778Z"}]`

**Error catch:**
`[SyntaxError: Invalid regular expression: unmatched parentheses]`

The tagged user needs to be in the last message of the channel. (or maybe even not)
When you open the channels list (when there's a channel rendered with that @mention last message) it will break the app and show a white screen.

---

### Steps to reproduce

1. Create a channel where there's a user with name i.e. "Name :)"
2. Mention that user in the message

---

### Expected behavior

The app doesn't break. [white screen]

---

## Project Related Information

- **Platform that you're experiencing the issue on**:
    - [ ] iOS
    - [ ] Android
    - [ ] **iOS** but have not tested behavior on Android
    - [ ] **Android** but have not tested behavior on iOS
    - [x] Both
- **`stream-chat-react-native` version you're using that has this issue:**
    - `5.11.2`
- Device/Emulator info:
  - [x] I am using a physical device
  - OS version: `e.g. Android 10`
  - Device/Emulator: `e.g. iPhone 11`

---

### Additional context

1. Either the application itself should not allow this kind of the name (we)
2. Or you should kind of handle cases where the name can contain special characters

**Comment by vishalnarkhede** [comment]
We will check and get back to you :)

cc @khushal87

**Comment by khushal87** [comment]
Umm, this will be easily reproducible since the name contains a special character `)` that isn't escaped.

**Comment by vishalnarkhede** [comment]
Thanks for brining this up. I am able to reproduce this issue and we will fix it as soon as possible.
