### ISSUE TITLE
[🐛] Crash when opening the file picker v5.16.0

### ISSUE THREAD

**Issue by 1987cr** [GetStream/stream-chat-react-native#2209]
## Issue

App crashes when opening the file picker

---

### Steps to reproduce

1. Open the file picker
2. See this error:

```
TypeError: Cannot read property 'includes' of undefined
```

Seems to be caused by this line on `AttachmentPickerItem.tsx`

```
const isVideoType = asset.type.includes('video');
```

I console logged the asset object on android and iOS and I get an object without the `type` property:

Android
```
{"extension": null, "fileSize": 144826, "filename": "IMG_20230810_115856.jpg", "height": 1280, "orientation": null, "playableDuration": null, "source": "picker", "uri": "file:///storage/emulated/0/Pictures/IMG_20230810_115856.jpg", "width": 960}
```

iOS
```
{"extension": null, "fileSize": 2505426, "filename": "IMG_0003.JPG", "height": 2002, "playableDuration": null, "source": "picker", "uri": "ph://9F983DBA-EC35-42B8-8773-B597CF782EDD/L0/001", "width": 3000}
```

---

### Expected behavior

No crash

---

### Customization

<details><summary>Click To Expand</summary>
<p>

```typescript jsx
# N/A
```
</p>
</details>

---

### Offline support

- [x] I have enabled offline support.
- [ ] The feature I'm having does not occur when offline support is disabled. (stripe out if not applicable)

---

## Environment

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
    - [x] iOS
    - [x] Android
    - [ ] **iOS** but have not tested behavior on Android
    - [ ] **Android** but have not tested behavior on iOS
    - [ ] Both
- **`stream-chat-react-native` version you're using that has this issue:**
    - `e.g. 5.16.0`
- Device/Emulator info:
  - [x] I am using a physical device
  - OS version: `e.g. Android 10`
  - Device/Emulator: `e.g. iPhone 11`

</p>
</details>

---

### Additional context

---

### Screenshots

<details><summary>Click To Expand</summary>
<p>

</p>
</details>

---

**Comment by khushal87** [comment]
Hey @1987cr, I get:

For iOS
-------
Image:
```
{"duration": null, "extension": null, "fileSize": 1852262, "filename": "IMG_0005.JPG", "height": 2002, "playableDuration": null, "source": "picker", "type": "image", "uri": "ph://ED7AC36B-A150-4C38-BB8C-B6D696F4F2ED/L0/001", "width": 3000}
```
Video:
```
{"duration": 10.24, "extension": null, "fileSize": 5485935, "filename": "sample-10s 2.mp4", "height": 1080, "playableDuration": 10.24, "source": "picker", "type": "video", "uri": "ph://164B312D-6262-4D3B-9249-44B26891354D/L0/001", "width": 1920}
```

For Android:
------------
Image:
```
{"duration": null, "extension": null, "fileSize": 144991, "filename": "IMG_20230704_120031.jpg", "height": 1280, "orientation": null, "playableDuration": null, "source": "picker", "type": "image/jpeg", "uri": "file:///storage/emulated/0/Pictures/IMG_20230704_120031.jpg", "width": 960}
```

Video:
```
{"duration": 8, "extension": null, "fileSize": 9510683, "filename": "VID_20230704_120035.mp4", "height": 1280, "orientation": null, "playableDuration": 8, "source": "picker", "type": "video/mp4", "uri": "file:///storage/emulated/0/Movies/VID_20230704_120035.mp4", "width": 720}
```

All of them have the `type` key in them. What's the version of cameraroll you are using?

**Comment by 1987cr** [comment]
Ok I see the issue now, we have a custom `registerNativeHandlers` that overrides the `getPhoto` method and was missing mapping the `type` prop, we did it a while ago to support android 13 permissions but I see stream handles that part now, I'll go ahead an remove the custom handler, thanks @khushal87

**Comment by khushal87** [comment]
> Ok I see the issue now, we have a custom `registerNativeHandlers` that overrides the `getPhoto` method and was missing mapping the `type` prop, we did it a while ago to support android 13 permissions but I see stream handles that part now, I'll go ahead an remove the custom handler, thanks @khushal87

Closing the issue in that case. Thanks 😄
