### ISSUE TITLE
How to detect when onEndReached 

### ISSUE THREAD

**Issue by cleandevcode** [GetStream/stream-chat-react-native#2211]
Hello.

My work env:

```
"react-native" : "0.64.3",
"stream-chat": "7.1.0",
"stream-chat-react-native" : "^5.5.0"
```

My code:

```
import { ChannelList } from 'stream-chat-react-native';

...

const channelFilters = {
  type : `messaging`,
  members: { $in : [userID] },
  member_counts: { $eq: 2 },
  joined: { $eq: true }
}

<ChannelList 
  filters={channelFilters}
/>
```

I need to get the limit and offset when `onEndReached` in the `ChannelList`.
Then how to detect `onEndReached` function? Or are there any ways to get changing query options like `limit` and `offset` from `ChannelList`?

**Comment by vishalnarkhede** [comment]
Could you please give a bit more details around business requirements for this?

**Comment by cleandevcode** [comment]
Its my UI and I used the different filtering options for Messages and Requests.

```
  const messageFilters = {
    type: `messaging`,
    members: { $in: [user?.id] },
    member_count: { $eq: 2 },
    joined: { $eq: true },
  };

  const requestFilters = {
    type: `messaging`,
    members: { $in: [user?.id] },
    last_message_at: { $lt: new Date() },
    member_count: { $eq: 2 },
    joined: { $eq: false },
    invite: { $eq: `pending` },
  };

...


<ChannelList 
  filters={ status === `messages` ? messageFilters : requestFilters}
/>
```

Let us assume there are 50 people in Messages List, and there is no Requests yet.
And I am gonna search the user by his name, and he is placed in 31th item in Messages List. (his name is `demo` now)
I can filter `demo` at first as 50 people are all rendered in Messages List.
But after changing tabs to Requests and come back to Messages, then can not find `demo` as chat List (message list) is already initialized with new filter options.

So I wanted to keep the messages list I got before switching tab.

<img width="346" alt="Screen Shot 2023-08-23 at 10 44 09 AM" src="https://github.com/GetStream/stream-chat-react-native/assets/52365167/07ded40b-42a9-48e2-93bd-6f80342d7fb2">

**Comment by cleandevcode** [comment]
any suggestions for my requirements?

**Comment by vishalnarkhede** [comment]
umm so basically you just need to NOT unmount component when you switch tabs, right? This sounds more navigation related thing

**Comment by cleandevcode** [comment]
I think it's not a navigation problem.

There would be 3 solutions for my situation.
1. Filter the list of chat previews by search string
2. Keep the list of chat previews on the state variable
3. Get the offset and limit when `onEndReached`

#1 is the best solution but could not find a way.
If possible, can you leave some examples or reference for those 3 ways?

**Comment by vishalnarkhede** [comment]
> Filter the list of chat previews by search string

Do you mean you want to be able to add search criteria on only the latest message in channels?

**Comment by vishalnarkhede** [comment]
> Keep the list of chat previews on the state variable

If you want to get access to current active channels in your app, you could use `client.activeChannels` object. Its supposed to be an internal property to keep track of all the watched channels within js client, so not recommended to used directly in app but can be used.

**Comment by vishalnarkhede** [comment]
> Get the offset and limit when onEndReached
This is not possible at the moment, and unfortunately we won't be able to prioritize this.

**Comment by cleandevcode** [comment]
> > Filter the list of chat previews by search string
> 
> Do you mean you want to be able to add search criteria on only the latest message in channels?

I want to filter the chat preview according to the user name by the search string.

**Comment by vishalnarkhede** [comment]
Please get in touch with support@getstream.io. This is more of an integration related request/question
