### ISSUE TITLE
🔥 Many images from the random_svg endpoint come back with 404 error

### ISSUE THREAD

**Issue by jeffbonasso-ambifi** [GetStream/stream-chat-react-native#2234]
## Issue

Internally the Avatar and GroupAvatar is using an random image lookup with the initials of the user. There are a lot of images missing from this lookup and it returns a 404 error which then causes the entire GroupAvatar to be gray.

An example...
https://getstream.imgix.net/images/random_svg/AS.png

returns a 404 error

For now, the workaround I did was to comment out the isLoadingImageError test in GroupAvatar.

```typescript jsx
{/*isLoadingImageError ? (
        <View
          style={{
            backgroundColor: '#ececec',
            borderRadius: size / 2,
            height: size,
            width: size,
          }}
        />
      ) : */
```

This has a better result, but obviously the proper fix is that random_svg brings back a proper image. There are many initials where a 404 is coming back.

### Steps to reproduce

Create a channel with multiple members and have one of the members with the initials AS.

### Expected behavior

It brings back a proper image for random_svg endpoint

### Customization

<details><summary>Click To Expand</summary>
<p>

I commented out this code in GroupAvatar.tsx. This problem shows visually in ChannelList when displaying group avatars.

```typescript jsx
{/*isLoadingImageError ? (
        <View
          style={{
            backgroundColor: '#ececec',
            borderRadius: size / 2,
            height: size,
            width: size,
          }}
        />
      ) : */
```
</p>
</details>

### Offline support

- [ ] I have enabled offline support.
- [ ] The feature I'm having does not occur when offline support is disabled. (stripe out if not applicable)

## Environment

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

**`react-native info` output:**

```
 N/A
```

- **Platform that you're experiencing the issue on**:
    - [ ] iOS
    - [ ] Android
    - [ ] **iOS** but have not tested behavior on Android
    - [ ] **Android** but have not tested behavior on iOS
    - [x] Both
- **`stream-chat-react-native` version you're using that has this issue:**
    Version 5.17.1
- Device/Emulator info:
  - [ ] I am using a physical device
  - OS version: `e.g. Android 10`
  - Device/Emulator: `e.g. iPhone 11`

</p>
</details>

### Screenshots

<details><summary>Click To Expand</summary>
<p>

</p>
</details>

---

**Comment by vishalnarkhede** [comment]
@jeffbonasso-ambifi please reach out to support@getstream.io, since this is not RN SDK related issue.
