### ISSUE TITLE
[🐛] Unable to change photos available to attachment picker after dismissing initial dialog

### ISSUE THREAD

**Issue by josh-** [GetStream/stream-chat-react-native#2240]
## Issue

When an iOS user has granted limited photo library access to an app, they are given the option to change the visible photos when opening the photo picker, however if this resulting dialog is then dismissed, there is no way to change the visible photos in-app again until the app is re-opened.

### Steps to reproduce

1. Provide limited library access to an app using `stream-chat-react-native`
    - the resulting screen in Settings.app > Privacy & Security > Photos > `APP_NAME` will look like this:
<img src="https://github.com/GetStream/stream-chat-react-native/assets/712727/7db0b0a3-3fb7-4be1-8ea2-fdfdc80e106d" width="250" />

3. Open a channel in your app
4. Click on the attachment icon
    - observe the following popup allowing you to select which photos should be visible:
<img src="https://github.com/GetStream/stream-chat-react-native/assets/712727/583ffd45-6469-4abb-8a56-d98be878addc" width="250" />

6. Press "Keep Current Selection"
7. Observe that there is now no way to change the selected photos from the photo library, until the app is re-opened and the popup from (4.) is shown again:

<img src="https://github.com/GetStream/stream-chat-react-native/assets/712727/611091d9-fbe5-47c1-9983-6d4e39bed1aa" width="250" />

### Expected behavior

Instead of always showing the popup when opening the attachment picker for the first time, I believe that the attachment picker should instead allow the user to trigger photo selection, which is what is done in other apps.

For example, Facebook Messenger:

<img src="https://github.com/GetStream/stream-chat-react-native/assets/712727/2806e1c4-e7dd-4c52-90a4-526cbe44348e" width="350" />

Or Slack:

<img src="https://github.com/GetStream/stream-chat-react-native/assets/712727/ed4c2d38-1ac4-4053-bff7-b553bac335bb" width="350" />

### Customization

<details><summary>Click To Expand</summary>
<p>

```typescript jsx
# N/A
```
</p>
</details>

### Offline support

- [ ] I have enabled offline support.
- [ ] The feature I'm having does not occur when offline support is disabled. (stripe out if not applicable)

## Environment

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
"expo-media-library": "15.4.1",
"@react-native-community/netinfo": "9.3.10",
"expo-file-system": "15.4.3",
"react-native-gesture-handler": "2.12.1",
"expo-image-picker": "14.3.2",
"expo-image-manipulator": "11.3.0",
"react-native-reanimated": "3.3.0",
"react-native-svg": "13.9.0",
"stream-chat-expo": "5.16.0",
```

**`react-native info` output:**

```
System:
  OS: macOS 13.5.2
  CPU: (10) arm64 Apple M1 Max
  Memory: 75.44 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.16.0
    path: /private/var/folders/9y/jsk3j2317c7bpdl61ldr05rc0000gp/T/xfs-6a747772/node
  Yarn:
    version: 3.6.3
    path: /private/var/folders/9y/jsk3j2317c7bpdl61ldr05rc0000gp/T/xfs-6a747772/yarn
  npm:
    version: 9.5.1
    path: ~/.nvm/versions/node/v18.16.0/bin/npm
  Watchman:
    version: 2023.09.04.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.9787799
  Xcode:
    version: 15.0/15A240d
    path: /usr/bin/xcodebuild
Languages:
  Java: Not Found
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

- **Platform that you're experiencing the issue on**:
    - x] iOS
    - [ ] Android
    - [x] **iOS** but have not tested behavior on Android
    - [ ] **Android** but have not tested behavior on iOS
    - [ ] Both
- **`stream-chat-react-native` version you're using that has this issue:**
    - `5.16.0`
- Device/Emulator info:
  - [x] I am using a physical device
  - OS version: `iOS 17`
  - Device/Emulator: `e.g. iPhone 13 Pro`

</p>
</details>

### Additional context

I believe the underlying code that triggers the initial access prompt is here:

https://github.com/GetStream/stream-chat-react-native/blob/b55d56147e387f2efebc4cc33aed16c02c528d65/package/src/components/AttachmentPicker/AttachmentPicker.tsx#L192-L200

### Screenshots

<details><summary>Click To Expand</summary>
<p>

Added above.

</p>
</details>

---

**Comment by vishalnarkhede** [comment]
Will take a look at get back to you :)

**Comment by josh-** [comment]
Thankyou @vishalnarkhede 🙌

**Comment by mayo7e** [comment]
Hello is this available to try me hands on? If not can you advise on available issues/PR? thanks

**Comment by josh-** [comment]
thanks so much @santhoshvai and @khushal87 🙌
