### ISSUE TITLE
ChannelList is too slow on real device

### ISSUE THREAD

**Issue by manhncse02926** [GetStream/stream-chat-react-native#225]
**Describe the bug**
 We are using ChannelList to load all user's channels but in the real devices, it's a bit slow. Can we choose the values needed to display instead of all as current to improve performance?  Or is there a way to improve the speed of loading data filters
Thank you.
**Dev environment info (please complete/provide the following information):**

- stream-chat-react-native 0.11.0
- react-native 0.62.2
- Device/Emulator (android/ios) and OS version Iphone 7: 12.4

**Comment by shodgetts** [comment]
Hello, What are the filters you are currently using please?

**Comment by manhncse02926** [comment]
> Hello, What are the filters you are currently using please?

Hi , here is my filter:
` inActivefilter: {
          type: 'messaging',
          members: {$in: [_.get(this.props, 'user.id')]}, // dynamic value
          muted: true, // dynamic value
          id: {$in: idList}, // dynamic value
        },`

Thank you

**Comment by vishalnarkhede** [comment]
> Can we choose the values needed to display 

@manhncse02926 you can do something like following!
```js
filters={cid: { $in: ['channel_id_1', 'channel_id_2''] }}
```

**Comment by manhncse02926** [comment]
Thank you. I found the solution

**Comment by lokewk** [comment]
@manhncse02926 Mind sharing the solution you found. I am having the same issues.

**Comment by manhncse02926** [comment]
> @manhncse02926 Mind sharing the solution you found. I am having the same issues.

Sorry for the late reply.
We have to save the channel name on our backend and search via our services before use Getstream's filter
