### ISSUE TITLE
🔥[🐛] Expo app crashes when adding OverlayProvider

### ISSUE THREAD

**Issue by TheLoser00** [GetStream/stream-chat-react-native#2268]
## Issue

Code before the OverlayProvider runs okay but crashes as soon as it is rendered. I am using stream-chat-expo

Below is the code for my bottom tab navigator using Tabs from expo-router:
  return (
    <>
      <OverlayProvider>
        <Tabs
          screenOptions={({ route }) => ({
            tabBarActiveBackgroundColor: "#F09F20",
            tabBarInactiveBackgroundColor: "white",
            tabBarStyle: [
              {
                display: "flex",
              },
              null,
            ],
            tabBarButton: (props) => (
              <TouchableOpacity
                {...props}
                onPress={() => handleTabPress(route.name)}
              />
            ),
          })}
        >
          <Tabs.Screen
            name="Home"
            options={{
              tabBarIcon: ({ focused }) => (
                <Ionicons name={focused ? "home" : "home-outline"} size={24} />
              ),
              tabBarShowLabel: false,
              initialParams: {
                isLoggedIn: isLoggedIn,
              },
            }}
          />
          <Tabs.Screen
            name="Messages"
            options={{
              tabBarIcon: ({ focused }) => (
                <Ionicons
                  name={focused ? "chatbubbles" : "chatbubbles-outline"}
                  size={24}
                />
              ),
              tabBarShowLabel: false,
              headerShown: false,
            }}
          />
          <Tabs.Screen
            name="Sell"
            options={{
              tabBarIcon: ({ focused }) => (
                <Ionicons
                  name={focused ? "pricetags" : "pricetags-outline"}
                  size={24}
                />
              ),
              tabBarShowLabel: false,
              headerShown: false,
            }}
          />
          <Tabs.Screen
            name="Profile"
            options={{
              tabBarIcon: ({ focused }) => (
                <Ionicons
                  name={focused ? "person" : "person-outline"}
                  size={24}
                />
              ),
              tabBarShowLabel: false,
              headerShown: true,
            }}
          />
        </Tabs>
      </OverlayProvider>
    </>
  );

### Steps to reproduce

1. Run the app

### Expected behavior

App renders the Tab component and not crashing

### Customization

<details><summary>Click To Expand</summary>
<p>

```typescript jsx
# N/A
```
</p>
</details>

### Offline support

- [ ] I have enabled offline support.
- [ ] The feature I'm having does not occur when offline support is disabled. (stripe out if not applicable)

## Environment

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

{
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@ptomasroos/react-native-multi-slider": "^2.2.2",
    "@react-native-async-storage/async-storage": "1.17.11",
    "@react-native-community/datetimepicker": "6.7.3",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-native-community/netinfo": "^9.4.1",
    "@react-native-community/viewpager": "5.0.11",
    "@react-navigation/drawer": "^6.6.3",
    "@react-navigation/material-bottom-tabs": "^6.2.16",
    "@react-navigation/material-top-tabs": "^6.6.3",
    "@react-navigation/native": "^6.1.7",
    "@react-navigation/stack": "^6.3.17",
    "axios": "^1.5.1",
    "date-fns": "^2.30.0",
    "expo": "^48.0.7",
    "expo-camera": "~13.2.1",
    "expo-constants": "~14.2.1",
    "expo-file-system": "~15.2.2",
    "expo-font": "~11.1.1",
    "expo-image-manipulator": "~11.1.1",
    "expo-image-picker": "~14.1.1",
    "expo-linear-gradient": "~12.1.2",
    "expo-linking": "~4.0.1",
    "expo-location": "^16.3.0",
    "expo-media-library": "~15.2.3",
    "expo-router": "^1.2.0",
    "expo-splash-screen": "~0.18.1",
    "expo-status-bar": "~1.4.2",
    "firebase": "^10.3.1",
    "nativewind": "^2.0.11",
    "pullstate": "^1.25.0",
    "react": "18.2.0",
    "react-bootstrap": "^2.9.0",
    "react-dom": "18.2.0",
    "react-native": "0.71.13",
    "react-native-deck-swiper": "^2.0.14",
    "react-native-dotenv": "^3.4.9",
    "react-native-element-dropdown": "^2.9.0",
    "react-native-gesture-handler": "~2.9.0",
    "react-native-image-crop-picker": "^0.40.0",
    "react-native-image-picker": "^5.6.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-maps": "1.3.2",
    "react-native-modal": "^13.0.1",
    "react-native-modern-datepicker": "^1.0.0-beta.91",
    "react-native-pager-view": "6.1.2",
    "react-native-paper": "^5.9.1",
    "react-native-safe-area-context": "4.5.0",
    "react-native-screens": "~3.20.0",
    "react-native-tab-view": "^3.5.2",
    "react-native-table-component": "^1.2.2",
    "react-native-vector-icons": "^9.2.0",
    "react-native-web": "~0.18.7",
    "react-router-dom": "^6.17.0",
    "stream-chat": "^8.12.1",
    "stream-chat-expo": "^5.17.1",
    "stream-chat-react-native": "^5.17.1",
    "tailwindcss": "3.3.2",
    "typescript": "^4.9.4",
    "react-native-reanimated": "~2.14.4",
    "react-native-svg": "13.4.0"
  },
  "devDependencies": {
    "@babel/core": "^7.19.3",
    "@babel/plugin-proposal-export-namespace-from": "^7.18.9",
    "@types/react": "~18.0.27"
  },
  "resolutions": {
    "metro": "^0.73.7",
    "metro-resolver": "^0.73.7"
  },
  "overrides": {
    "metro": "^0.73.7",
    "metro-resolver": "^0.73.7"
  },
  "name": "real-ease",
  "version": "1.0.0",
  "private": true
}

**`react-native info` output:**

```
     OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
    Memory: 8.68 GB / 19.79 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 9.6.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      Versions: 10.0.19041.0
  IDEs:
    Android Studio: AI-222.4459.24.2221.10121639
    Visual Studio: 17.7.34031.279 (Visual Studio Community 2022)
  Languages:
    Java: 17.0.6
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.13 => 0.71.13
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
    - [ ] iOS
    - [ ] Android
    - [ ] **iOS** but have not tested behavior on Android
    - [x ] **Android** but have not tested behavior on iOS
    - [ ] Both
- **`stream-chat-react-native` version you're using that has this issue:**
    - `5.17.1`
- Device/Emulator info:
  - [x] I am using a physical device
  - OS version: `Android 13`
  - Device/Emulator: `e.g. iPhone 11`

</p>
</details>

### Screenshots

<details><summary>Click To Expand</summary>
<p>

index.js
const App = () => {
  const [isLoading, setIsLoading] = useState(true);
  const isLoggedIn = AuthStore.useState((s) => s?.isLoggedIn);

  useEffect(() => {
    // Use an effect to wait for the state to be updated from the authentication process.
    const unsubscribe = AuthStore.subscribe((s) => {
      if (s.initialized) {
        setIsLoading(false);
      }
    });
  }, [isLoggedIn]);

  if (isLoading) {
    // Render a loading screen while waiting for isLoggedIn.
    return <LoadingScreen />;
  }

  console.log(isLoggedIn);
  if (!isLoggedIn) {
    return <Redirect href="./screens/Landing" />;
  }
  return (
    <GestureHandlerRootView>
      <SafeAreaView style={{ flex: 1 }}>
        <View style={{ flex: 1 }}>
          <Redirect href="./(tabs)/Home" />
        </View>
      </SafeAreaView>
    </GestureHandlerRootView>
  );
};
</p>
</details>

---

**Comment by vishalnarkhede** [comment]
Do you have any error stack?

**Comment by TheLoser00** [comment]
> Do you have any error stack?

App just crashes and doesn't provide an error stack

**Comment by vishalnarkhede** [comment]
Its hard for us to simply look at the code and provide a solution. Could you please share a min reproducible repository with us? That will help us speed up the issue resolution.

**Comment by TheLoser00** [comment]
When I created a new app, the OverlayProvider does not seem to crash. Is stream-chat v5 compatible with expo router sdk 48?

**Comment by vishalnarkhede** [comment]
> When I created a new app, the OverlayProvider does not seem to crash. Is stream-chat v5 compatible with expo router sdk 48?

In this new app (where you can't reproduce the crash), are you using expo 48?

**Comment by TheLoser00** [comment]
> > When I created a new app, the OverlayProvider does not seem to crash. Is stream-chat v5 compatible with expo router sdk 48?
> 
> In this new app (where you can't reproduce the crash), are you using expo 48?

I used expo 49

**Comment by vishalnarkhede** [comment]
In that I would recommend you to setup min reproducible example using expo 48 and please share it with us.
Our expo example app is based on Expo 48 - https://github.com/GetStream/stream-chat-react-native/tree/develop/examples/ExpoMessaging. So SDK is ideally compatible with expo 48 already.

**Comment by TheLoser00** [comment]
Hi, I do not know why but it suddenly started working when I revisited my code after trying to reproduce it in another Expo 48 app. Thank you for your help.
