### ISSUE TITLE
Add reaction make the top message become the bottom message

### ISSUE THREAD

**Issue by manhncse02926** [GetStream/stream-chat-react-native#228]
**Describe the bug**
This problem also occurs in your example (clone slack example). When we add a reaction to the top message, the user name and avatar will disappear.
Currently, I used the groupstyles[0] (top or bottom) property to set the location of the avatar and username (User and avatar only show for the top message). If we add a reaction, look the top message will become the bottom message. That why I hit the problem. If you have any idea to resolve this case, could you give me some information?
If you can handle this case, we will have more choices to custom the UI.
Thanks
**Dev environment info (please complete/provide the following information):**

-  "stream-chat": "^1.11.2",
-   "stream-chat-react-native": "^0.11.0",
- react-native  0.62.x
- Device/Emulator (android/ios) and OS version: Ios simulator 13.4

**To Reproduce**
open the clone slack example
1. Go to the group chat 
2. Long press on the top message of any user
3. Select reaction
4. click to any action (haha, sad, ...)
5. Avatar and username of the user will disappear

**Expected behavior**
Keep the user name and avatar

**Screenshots**
![image](https://user-images.githubusercontent.com/21988274/85942017-d2993680-b950-11ea-8c92-128be49641b8.png)

**Comment by vishalnarkhede** [comment]
Hey @manhncse02926 sorry for the delays. We will check and get back to you

**Comment by manhncse02926** [comment]
> Hey @manhncse02926 sorry for the delays. We will check and get back to you

Thank you for your hard work. Could you have a look at this error?
https://github.com/GetStream/stream-chat-react-native/issues/227

**Comment by vishalnarkhede** [comment]
@manhncse02926 we have fixed this in 1.3.0 which should be released by end of week :)

**Comment by manhncse02926** [comment]
> @manhncse02926 we have fixed this in 1.3.0 which should be released by end of week :)

cool !! Thank you.
