### ISSUE TITLE
Fix multiple mentions rendered incorrectly

### ISSUE THREAD

**Issue by VNDRN** [GetStream/stream-chat-react-native#2283]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `stream-chat-react-native-core@5.18.1` for the project I'm working on.

When rendering mentioned users, I noticed a bug. It's fine if you mention a single user in a message, but when you mention multiple, they get rendered as plain text. I dug into the code and noticed that the separator used between the mentions ` | ` is also being escaped. A fix for this is to escape the user names instead of the entire string. 

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/stream-chat-react-native-core/src/components/Message/MessageSimple/utils/renderText.tsx b/node_modules/stream-chat-react-native-core/src/components/Message/MessageSimple/utils/renderText.tsx
index e533655..bfaba5d 100644
--- a/node_modules/stream-chat-react-native-core/src/components/Message/MessageSimple/utils/renderText.tsx
+++ b/node_modules/stream-chat-react-native-core/src/components/Message/MessageSimple/utils/renderText.tsx
@@ -224,9 +224,9 @@ export const renderText = <
     ? mentioned_users.reduce((acc, cur) => {
         const userName = cur.name || cur.id || '';
         if (userName) {
-          acc += `${acc.length ? '|' : ''}@${userName}`;
+          acc += `${acc.length ? '|' : ''}@${userName.replaceAll(/[.*+?^${}()|[\]\\]/g, '\\$&')}`;
         }
-        return acc.replaceAll(/[.*+?^${}()|[\]\\]/g, '\\$&');
+        return acc;
       }, '')
     : '';
```

Hope this can get merged into an upcoming release.

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by vishalnarkhede** [comment]
@khushal87 could you please take care of this? Please make sure to use `replace` instead of `replaceAll`. https://github.com/GetStream/stream-chat-react-native/issues/2253

**Comment by khushal87** [comment]
Yes for sure @vishalnarkhede

**Comment by VNDRN** [comment]
Just wanted to mention (no pun intended) that when a username is an email address, it gets resolved as a link instead of a mention. Would be great if this could get fixed too 😄

**Comment by khushal87** [comment]
> username is an email address; it gets resolved as a link instead of a mention

Created a new issue for this as it will need some separate attention and should not block this original issue.
