### ISSUE TITLE
🔥 [🐛] Screenshots/long aspect ratio photos are sent as full images instead of thumbnails

### ISSUE THREAD

**Issue by jedyeo** [GetStream/stream-chat-react-native#2284]
## Issue

In our app:

- if a user sends a message with a `<Gallery>` with only a singular photo,
- and the photo is of skinny vertical aspect ratio (~1:2, e.g. a screenshot)
- the photo has margins added, which makes the image look misaligned
- This is inconsistent with the styling of other images

<img width="442" alt="Screenshot 2023-11-03 at 12 16 33 AM" src="https://github.com/GetStream/stream-chat-react-native/assets/33077039/86d39fb3-2429-4e93-bc9a-f7853ce173d2">

<img width="436" alt="Screenshot 2023-11-03 at 12 31 44 AM" src="https://github.com/GetStream/stream-chat-react-native/assets/33077039/22812cf6-fefd-4f39-aace-a36b350e1810">

This behavior is reproducible in the sample app. The first image of spotify is a screenshot. The second one is a regular photo taken by an iPhone 14 Pro.

![IMG_3109](https://github.com/GetStream/stream-chat-react-native/assets/33077039/c320e7d5-ec8f-48df-8975-51ce3a1f3e23)

### Steps to reproduce

1. Go to Stream Sample App
2. Enter any chat/channel
3. Send a device screenshot
4. Observe the margins added.

### Expected behavior

This seems like a design choice. Most chat apps (Messenger, WhatsApp, iMessage) show only a portion of the image (like a thumbnail). Even other photos with more lenient dimensions are sent in this thumbnail style.

I went into the actual Stream component and played around with the code. Seems like changing `resizeMode` to `'cover'` in `<Gallery>` does the trick. But obviously, we'd like to avoid changing the code under the hood in this way. Is there a better way to override this value? Does this require a new feature?

![Screenshot 2023-11-03 at 12 15 25 PM](https://github.com/GetStream/stream-chat-react-native/assets/33077039/f10da2b2-12b6-4c06-8948-1514db01d742)

## Project Related Information

A chat for users to communicate with each other and share images of different ratios/dimensions.

### Customization

<details><summary>Click To Expand</summary>
<p>

```typescript jsx
# N/A
```
</p>
</details>

### Offline support

- [ ] I have enabled offline support.
- [ ] The feature I'm having does not occur when offline support is disabled. (stripe out if not applicable)

## Environment

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
    - [x] iOS
    - [x] Android
    - [ ] **iOS** but have not tested behavior on Android
    - [ ] **Android** but have not tested behavior on iOS
    - [x] Both
- **`stream-chat-react-native` version you're using that has this issue:**
    - `e.g. 5.13.0`
- Device/Emulator info:
  - Reproducible on any mobile device, emulator or physical

</p>
</details>

### Screenshots

<details><summary>Click To Expand</summary>
<p>
See above.

</p>
</details>

---

**Comment by khushal87** [comment]
Hey @jedyeo, you can try passing this component prop in the `ImageComponent` prop of the `Chat` component. This might solve your issue. Let us know how it goes.

```
ImageComponent={(props) => {
    return <Image {...props} resizeMode='cover' />;
}}
```
