### ISSUE TITLE
🔥 React Native offline not working properly

### ISSUE THREAD

**Issue by ricardojmf** [GetStream/stream-chat-react-native#2314]
## Issue

Hello! I'm testing GetStream's React Native SDK and I'm having some trouble with the offline functionality.
I tested sending messages while being `offline` and after connecting the phone to internet the messages where not synced automatically (as they do on ios/android sdks).

Is this a bug? Or currently the offline feature for React Native does not allow for pending messages to sync automatically upon internet reconnection?

Kind regards,

Ricardo Figueiredo 

### Steps to reproduce

1. Go offline;
2. Send a few messages;
3. Go online;
4. The messages send offline **are not** being automatially synced.

### Expected behavior

1. Go offline;
2. Send a few messages;
3. Go online;
4. The messages send offline **are** being automatially synced.

### Customization

<details><summary>Click To Expand</summary>
<p>

```typescript jsx
# N/A
```
</p>
</details>

### Offline support

- [x] I have enabled offline support.
- [ ] The feature I'm having does not occur when offline support is disabled. (stripe out if not applicable)

## Environment

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
  "name": "HelloNativeWorld",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@react-native-camera-roll/camera-roll": "^6.0.2",
    "@react-native-clipboard/clipboard": "^1.12.1",
    "@react-native-community/netinfo": "^11.1.0",
    "@react-navigation/native": "^6.1.9",
    "@react-navigation/stack": "^6.3.20",
    "@stream-io/flat-list-mvcp": "^0.10.3",
    "react": "18.2.0",
    "react-native": "0.72.7",
    "react-native-document-picker": "^9.0.1",
    "react-native-fs": "^2.20.0",
    "react-native-gesture-handler": "^2.13.4",
    "react-native-haptic-feedback": "^2.2.0",
    "react-native-image-crop-picker": "^0.40.2",
    "react-native-image-resizer": "^1.4.5",
    "react-native-quick-sqlite": "^8.0.6",
    "react-native-reanimated": "^3.5.4",
    "react-native-safe-area-context": "^4.7.4",
    "react-native-screens": "^3.27.0",
    "react-native-share": "^10.0.1",
    "react-native-svg": "^14.0.0",
    "react-native-video": "^5.2.1",
    "stream-chat-react-native": "^5.21.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/eslint-config": "^0.72.2",
    "@react-native/metro-config": "^0.72.11",
    "@tsconfig/react-native": "^3.0.0",
    "@types/react": "^18.0.24",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.2.1",
    "eslint": "^8.19.0",
    "jest": "^29.2.1",
    "metro-react-native-babel-preset": "0.76.8",
    "prettier": "^2.4.1",
    "react-test-renderer": "18.2.0",
    "typescript": "4.8.4"
  },
  "engines": {
    "node": ">=16"
  }
}
```

**`react-native info` output:**

```
System:
  OS: macOS 14.0
  CPU: (8) arm64 Apple M1 Pro
  Memory: 9.29 GB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.16.0
    path: ~/.nvm/versions/node/v16.16.0/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.nvm/versions/node/v16.16.0/bin/yarn
  npm:
    version: 8.11.0
    path: ~/.nvm/versions/node/v16.16.0/bin/npm
  Watchman:
    version: 2023.11.06.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK:
    API Levels:
      - "22"
      - "30"
      - "32"
      - "33"
    Build Tools:
      - 30.0.3
      - 33.0.0
      - 33.0.1
    System Images:
      - android-22 | Google APIs ARM 64 v8a
      - android-31 | Google APIs ARM 64 v8a
      - android-33 | Google APIs ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10811636
  Xcode:
    version: 15.0.1/15A507
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 19.0.1
    path: /usr/bin/javac
  Ruby:
    version: 3.1.2
    path: /Users/ricardo.figueiredo/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.7
    wanted: 0.72.7
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

- **Platform that you're experiencing the issue on**:
    - [] iOS
    - [ ] Android
    - [x] **iOS** but have not tested behavior on Android
    - [ ] **Android** but have not tested behavior on iOS
    - [ ] Both
- **`stream-chat-react-native` version you're using that has this issue:**
    - `e.g. 5.4.3`
- Device/Emulator info:
  - [x] I am using a physical device
  - Device/Emulator: iPhone 11

</p>
</details>

### Screenshots

<details><summary>Click To Expand</summary>
<p>

https://github.com/GetStream/stream-chat-react-native/assets/4780289/ef85e9ef-4866-4340-b34b-3fcf357e4fe8

</p>
</details>

---

**Comment by vishalnarkhede** [comment]
@ricardojmf this feature is intentionally not implemented, to avoid load of js thread and too many api calls once the internet is back on.

**Comment by ricardojmf** [comment]
Thank you for the quick answer! Since this is not intentionally implemented, I suggest you to add this specific not implemented feature to the React Native offline documentation.

Kind regards,

Ricardo
