### ISSUE TITLE
Is there any documentation for jest testing?

### ISSUE THREAD

**Issue by parasfusemachine** [GetStream/stream-chat-react-native#2322]
Dear all, 
I am trying to do jest testing and is not able to mock or setup mock of any components of the stream-chat component, resulting unable to test the whole app.
Please kindly mention the doc if available and if not please provide information on how to do mocking of the Providers.

**Comment by khushal87** [comment]
Hey @parasfusemachine, to know more about our requirements, what are the components you are looking forward to testing from the SDK? Sadly, we don't have a direct doc for testing or mocking the components for now, so I can share the SDK tests for you for reference that we have within the SDK and you might be able to follow along.
