### ISSUE TITLE
[🐛] Image compression is not consistently applied

### ISSUE THREAD

**Issue by tao-qian** [GetStream/stream-chat-react-native#2327]
## Issue

We added the `compressImageQuality` setting to channels, but not all images sent are compressed. Specifically, if I attach an image from the image picker, then **wait for ~5 seconds** before pressing the send button, then the image that's sent will be compressed. However, if I press the send button right after attaching the image from the image picker, then the image that's sent will have the original size.

It seems like the send button isn't waiting for some async operation to finish, before the image is sent.

### Steps to reproduce

1. Attach an image from the image picker
2. Press Send button right away (or even after a couple seconds of wait)
3. The image that's sent will not be compressed

### Expected behavior

Image should always be compressed.

### Customization

<details><summary>Click To Expand</summary>
<p>

```typescript jsx
   <Channel
          LoadingErrorIndicator={() => <NetworkErrorScreenWithHeader/>}
          channel={channel}
          hideStickyDateHeader
          disableTypingIndicator
          enforceUniqueReaction
          hasFilePicker={true}
          hasImagePicker={true}
          messageActions={messageActions}
          AutoCompleteSuggestionList={() => null}
          giphyEnabled={false}
          initialScrollToFirstUnreadMessage
          // insets.top is applied to all screens in App.tsx, so we need to account for it here
          keyboardVerticalOffset={insets.top + (Platform.OS === 'ios' ?  0 : -300)}
          // Update this to change the style of the "Reconnecting..." banner
          // NetworkDownIndicator={() => null}
          CommandsButton={undefined}
          autoCompleteTriggerSettings={() => ({})}
          hasCommands={false}
          MoreOptionsButton={undefined}
          compressImageQuality={0.8}
        >
          {renderTopNavigation()}
          <Divider style={{height: 4}}/>
          <MessageList/>
          <MessageInput />
        </Channel>
```
</p>
</details>

### Offline support

- [X] I have enabled offline support.
- [X] The feature I'm having does not occur when offline support is disabled. (stripe out if not applicable)
 
I think without offline support, the image will be "uploaded" first while it is in the input box, this would introduce the few seconds of wait to allow the compression to behave properly.

## Environment

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
    - [ ] iOS
    - [X] Android
    - [ ] **iOS** but have not tested behavior on Android
    - [X] **Android** but have not tested behavior on iOS
    - [ ] Both
We tried to test the behavior on iOS simulator as well, but on iOS simulator, all uploaded images are never compressed (even when we wait for more than 5 seconds). It is unclear if it is a problem that's specific to the simulator. I will add more details once we are able to test this on an iOS device.

- **`stream-chat-react-native` version you're using that has this issue:**
    - `e.g. 5.4.3`
- Device/Emulator info:
  - [X] I am using a physical device
  - OS version: `e.g. Android 10`
  - Device/Emulator: `e.g. iPhone 11`

</p>
</details>

### Screenshots

<details><summary>Click To Expand</summary>
<p>

</p>
</details>

---

**Comment by khushal87** [comment]
Hey @tao-qian, thanks for bringing up this issue with us. So you mean this issue only happens when offline support is enabled by you?

**Comment by tao-qian** [comment]
> Hey @tao-qian, thanks for bringing up this issue with us. So you mean this issue only happens when offline support is enabled by you?

I haven't actually tested this without offline support, and I just assumed that the behavior there would be different. IIUC, without offline support, the image will be in an "uploading" state with a spinner on top, once they are added to the input box, and the "Send" button won't actually be enabled, until the upload finishes. I assumed the "uploading" state would allow the compression to finish properly.

Whereas when offline support is enabled, the send button can be pressed right away as soon as the image is added. And based on my observation, if it is pressed without waiting for ~ 5 seconds, then the image that's sent won't be compressed.

**Comment by khushal87** [comment]
Thanks for pointing this out to us @tao-qian. This indeed looks like an issue. We will investigate and get this fixed and reach out to you soon. Thanks 😄

**Comment by tao-qian** [comment]
> Thanks for pointing this out to us @tao-qian. This indeed looks like an issue. We will investigate and get this fixed and reach out to you soon. Thanks 😄

Thanks! Please keep us posted!

**Comment by khushal87** [comment]
Hey @tao-qian, we have fixed it in #2331 and its merged as well. Please wait for the next release and this should fix your issue. Do let us know if it doesn't work. Thanks 😄

**Comment by tao-qian** [comment]
> Hey @tao-qian, we have fixed it in #2331 and its merged as well. Please wait for the next release and this should fix your issue. Do let us know if it doesn't work. Thanks 😄

Thanks a lot for the quick turnaround! We will keep an eye out for the next release then try this out!

**Comment by tao-qian** [comment]
Verified on our end that image compression is now happening consistently! Thanks!

**Comment by tao-qian** [comment]
We are seeing additional cases of images not getting compressed :( 

This time it is harder to reproduce and I haven't figure out the consistent repro steps yet. However, it typically happens after I sent a few images in a row (e.g. 10). The worrying part for this bug is that once it happens, the subsequent images also won't be compressed. However, **this sometimes would reset, after a text message is sent**.

Here are two image messages for the same image. One of them is compressed as expected, but the other one is not:
- https://dashboard.getstream.io/app/1266909/chat/explorer?path=channels%2Cchannel~messaging%3Ahr_brightgo_254%2Cmessages%2Cmessage~254-781042d6-2b9d-4742-32f8-4257f070af0a
- https://dashboard.getstream.io/app/1266909/chat/explorer?path=channels%2Cchannel~messaging%3Ahr_brightgo_254%2Cmessages%2Cmessage~254-4240d9e7-365d-454c-0da5-aad937d06f25

Note that the two images **practically look the same**, but if you download them, one of them would be 400 kb while the other would be 1.5 mb.

We are still trying to figure out more consistent repro steps, but just want to share the findings so far in case the behavior rings a bell. Thanks!
