### ISSUE TITLE
[🐛] reactions does not reflect all reactions, only latest reactions

### ISSUE THREAD

**Issue by VNDRN** [GetStream/stream-chat-react-native#2340]
## Issue

reactions from useMessageContext() does not reflect all the reactions. Instead, it seems to reflect message.latest_reactions instead. 

Also, it would also be nice to have a way to fetch all reactions, with the user(name)s. Currently, there only seems to be latest_reactions, which only gives the latest 10 reactions

### Steps to reproduce

1. react with a reaction that is not the like reaction
2. react with 10 people with the like reaction (10 seems to be the limit of latest_reactions) (or one that you didn't use in step 1). 
3. the like reaction from step 1 is not in reactions array.

### Expected behavior

the like reaction is also in the reactions array. 

### Customization

<details><summary>Click To Expand</summary>
<p>

```typescript jsx
# N/A
```
</p>
</details>

### Offline support

- [ ] I have enabled offline support.
- [ ] The feature I'm having does not occur when offline support is disabled. (stripe out if not applicable)

## Environment

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
    "stream-chat": "8.14.3",
    "stream-chat-expo": "5.22.0",
```

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
    - [ ] iOS
    - [ ] Android
    - [ ] **iOS** but have not tested behavior on Android
    - [ ] **Android** but have not tested behavior on iOS
    - [x] Both
- **`stream-chat-react-native` version you're using that has this issue:**
    - `e.g. 5.22.0`
- Device/Emulator info:
  - [ ] I am using a physical device
  - OS version: `e.g. Android 10`
  - Device/Emulator: `iPhone 14`

</p>
</details>

### Additional context

It would also be nice to have a way to fetch all reactions, with the user(name)s. Currently, there only seems to be latest_reactions, which only gives the latest 10 reactions

### Screenshots

<details><summary>Click To Expand</summary>
<p>

</p>
</details>

---

**Comment by VNDRN** [comment]
> It would also be nice to have a way to fetch all reactions, with the user(name)s. Currently, there only seems to be latest_reactions, which only gives the latest 10 reactions

I've opened a feature request for this: https://github.com/GetStream/stream-chat-react-native/issues/2341

Let me know if I can provide any more context

**Comment by khushal87** [comment]
Since the feature request PR is open, I will be closing this issue. Thanks for reporting 😄

**Comment by VNDRN** [comment]
Thanks for looking into this! The feature request does not reflect this bug though? This bug states that message.reactions does not reflect all reactions, but only the latest 10. I would imagine that it should reflect all reactions?
