### ISSUE TITLE
Add an option to view all reactions (and their details)

### ISSUE THREAD

**Issue by VNDRN** [GetStream/stream-chat-react-native#2341]
**Motivation**
I'm implementing a slack-like feature, where we can see all the people who reacted on a certain message. It shows the reaction and below it all the users that sent that reaction. Currently, I'm unable to do so as it seems only message.latest_reactions from useMessageContext gives me the users with the reaction. The problem is that latest_reactions only gives the 10 latest reactions (which makes sense) I'd like a way to fetch all reactions with their users or all users for a certain reaction
**Proposed solution**
either: 
- a prop message.reactions, similar to what message.latest_reactions gives us, but without the limit. 
- a function to get all reactions (with users) for a message id
- a function to get all users for a reaction type of a message
**Acceptance Criteria**
As a developer, I have a clear way to access all the reactions of a message, including the users who sent that reaction. 

![image](https://github.com/GetStream/stream-chat-react-native/assets/60874935/b13be45c-977d-4264-b14c-b9978404f6ef)

This for example cannot be reliably built with the currently available options

**Comment by VNDRN** [comment]
I totally missed https://getstream.io/chat/docs/react-native/send_reaction/#paginating-reactions somehow. This call makes it possible to fetch more reactions!

An improvement to this function could be to have a filter for the reaction type?

**Comment by khushal87** [comment]
Hey @VNDRN, I have informed our product team about the improvement you suggested to carry forward the request until then the link that you shared around [paginating reactions](https://getstream.io/chat/docs/react-native/send_reaction/#paginating-reactions) is the only way to go. You can filter the reactions on your client side. 

I will be closing the issue until then. Please look for our product updates for this feature. Thanks 😄
