### ISSUE TITLE
🔥 [🐛] Bug Report Title - Crash at onlyEmoji regex

### ISSUE THREAD

**Issue by kanehara** [GetStream/stream-chat-react-native#2349]
## Issue
Our React Native app recently crashed in production due to the onlyEmoji regex in the `Message.tsx` component.  Here is the screen cap from the crash report.  Has anyone else reported this or is this known?  Is this regex something that can be bypassed?

<img width="1027" alt="Screenshot 2023-12-18 at 8 28 51 AM" src="https://github.com/GetStream/stream-chat-react-native/assets/5545166/d9e453c0-e52e-4682-8f1b-378fa17f65d1">

### Steps to reproduce
Having difficulty reproducing manually so hard to diagnose what the root cause was.

### Expected behavior
App does not crash.

### Customization

```typescript jsx
<MessageList
  additionalFlatListProps={{
    showsVerticalScrollIndicator: false,
    onScroll: handleScroll,
    onMomentumScrollEnd: handleMomentumEnd,
  }}
  setFlatListRef={(ref) => (flRef.current = ref)}
/>
```
</p>
</details>

### Offline support

- [ ] I have enabled offline support.
- [ ] The feature I'm having does not occur when offline support is disabled. (stripe out if not applicable)

## Environment

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
"stream-chat-react-native": "^5.11.0",
```

**`react-native info` output:**

```
System:
    OS: macOS 14.1.2
    CPU: (10) x64 Apple M1 Pro
    Memory: 30.98 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 17.4.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.3.1 - /usr/local/bin/npm
    Watchman: 2022.01.17.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, watchOS 10.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 15.1/15C65 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.11 => 0.71.11 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
info React Native v0.73.1 is now available (your project is running on v0.71.11).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.73.1.
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.71.11.
info To upgrade, run "react-native upgrade".
```

- **Platform that you're experiencing the issue on**:
    - [x] iOS
    - [x] Android
    - [ ] **iOS** but have not tested behavior on Android
    - [ ] **Android** but have not tested behavior on iOS
    - [x] Both
- **`stream-chat-react-native` version you're using that has this issue:**
    - `5.11.0`
- Device/Emulator info:
  - [x] I am using a physical device
  - OS version: `e.g. Android 10`
  - Device/Emulator: `e.g. iPhone 11`

</p>
</details>

**Comment by khushal87** [comment]
Hey, @kanehara, can you point us to how we can reproduce this issue on our side? This will help us assist you faster. We haven't seen this issue on our side in the past. Maybe send us the emoji where you saw this issue.

**Comment by kanehara** [comment]
@khushal87 we're not sure emoji was.  We believe it's happening when the chat gets spammed with emojis.  Our app users often promote content by asking people in the chat to send emojis and we believe this was caused by that.  Maybe a unit test that spams this code path that hits this regex may reproduce it but I'm not too familiar with this codebase.
