### ISSUE TITLE
[🐛] Offline Mode Unread Count Out of Sync

### ISSUE THREAD

**Issue by tao-qian** [GetStream/stream-chat-react-native#2377]
## Issue

Similar to https://github.com/GetStream/stream-chat-react-native/issues/1996, we are seeing the unread count in the `ChannelList` preview being out of sync when using `enableOfflineSupport`. 

### Steps to reproduce
1. close the app (both force close and normal close would work)
2. send a message from a different device
3. open the app 
4. the new message from step 2 would show up in the preview, but the unread count in the preview would be out of date. If there were unread messages previously in step 1, then that old number would be shown. If there weren't unread messages in step 1, then there would be no unread count badge.
5. force close and reopen the app will update the unread count (just closing wouldn't help)

Note that this is not reproducible if the app has been in the foreground the whole time.

### Expected behavior
The unread count should be updated.

### Customization

<details><summary>Click To Expand</summary>
<p>

```typescript jsx
<Chat
      enableOfflineSupport
      client={chatClient}
    >
      <Layout style={styles.parentLayout}>
        <ChannelList
          LoadingErrorIndicator={() => <NetworkErrorScreen/>}
          filters={searchFilter}
        />
      </Layout>
</Chat>
```
</p>
</details>

### Offline support

- [X] I have enabled offline support.
- [ ] The feature I'm having does not occur when offline support is disabled. (stripe out if not applicable)

## Environment

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

**`react-native info` output:**

```
system:
  OS: macOS 14.1.1
  CPU: (12) arm64 Apple M2 Pro
  Memory: 142.75 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.16.0
    path: ~/.nvm/versions/node/v18.16.0/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 9.5.1
    path: ~/.nvm/versions/node/v18.16.0/bin/npm
  Watchman:
    version: 2023.12.04.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.11.3
    path: /Users/tao/.rvm/gems/ruby-2.7.6/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.9971841
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.21
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/tao/.rvm/rubies/ruby-2.7.6/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.71.14
    wanted: 0.71.14
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

- **Platform that you're experiencing the issue on**:
    - [ ] iOS
    - [ ] Android
    - [ ] **iOS** but have not tested behavior on Android
    - [ ] **Android** but have not tested behavior on iOS
    - [x] Both
- **`stream-chat-react-native` version you're using that has this issue:**
    - `5.22.1`
- Device/Emulator info:
  - [X] I am using a physical device
  - OS version: `e.g. Android 10`
  - Device/Emulator: `e.g. iPhone 11`

</p>
</details>

### Screenshots

<details><summary>Click To Expand</summary>
<p>

</p>
</details>

---

**Comment by tao-qian** [comment]
Hi! Are there any updates on this issue? @khushal87 

This is one of the higher priority problems we have, because it is consistently reproducible and affects our users every time they open the app..

**Comment by khushal87** [comment]
Hey @tao-qian, we are actively looking into this issue. Hope to fix this issue soon. 😄
