### ISSUE TITLE
Theme for the FileUploadPreview component

### ISSUE THREAD

**Issue by wildvalcom** [GetStream/stream-chat-react-native#238]
**Describe the bug**
 Impossible to apply custom styles for the **FileUploadPreview** component.

**Dev environment info:**

- Package version 0.13 (stream-chat-react-native)
- react-native

**Expected behavior**
It should be possible to apply custom styles through the theme, as for the **ImageUploadPreview** component: 
https://github.com/GetStream/stream-chat-react-native/blob/a9f454bae06930138d4351cd3097815f8ebdbe57/src/components/ImageUploadPreview.js

**Additional context**
All the existed styles of the **FileUploadPreview** component are hardcoded:
https://github.com/GetStream/stream-chat-react-native/blob/a9f454bae06930138d4351cd3097815f8ebdbe57/src/components/FileUploadPreview.js

gz#4456

**Comment by shodgetts** [comment]
Agent comment from Stephen Hodgetts in <a href='https://getstream.zendesk.com/agent/tickets/4456'>Zendesk ticket #4456</a>:<br><br>Assigned to Vishal Narkhede​

**Comment by vishalnarkhede** [comment]
Hey @wildvalcom thanks for bringing this up. We will add custom style support as soon as possible and get back to you!

**Comment by virdesai** [comment]
@wildvalcom whenever the next release is made this should be resolved from the recently merged PR
