### ISSUE TITLE
[🐛] Reply count is not updated after coming back from a Thread screen

### ISSUE THREAD

**Issue by atsss** [GetStream/stream-chat-react-native#2395]
## Issue

Reply counts under a message are not updated after a user sends messages in a thread and returns to the parent channel. The counts are updated after the user gets new messages in the thread/channel or reloads the channel. Otherwise, the count keeps what it was before the user sends messages.

### Steps to reproduce

1. Go to a Channel screen
2. Go to a Thread screen
3. Send messages in the Thread screen
4. Return to the parent Channel screen

### Expected behavior

Reply counts should be updated soon after returning to the parent Channel screen from the Thread screen without any actions.

### Customization

<details><summary>Click To Expand</summary>
<p>

- Channel.tsx
```
import { View, SafeAreaView } from 'react-native';
import { useEffect, useContext, useCallback } from 'react';
import {
  Channel,
  Chat,
  MessageInput,
  MessageList,
  useAttachmentPickerContext,
} from 'stream-chat-expo';
import { useHeaderHeight } from '@react-navigation/elements';
import { useNavigation } from '@react-navigation/native';
import type { MessageType } from 'stream-chat-expo';
import { streamI18n } from '../../config/streamI18n';
import { AuthContext } from '../../contexts/AuthContext';
import { useStreamChatContext } from '../../contexts/StreamChatContext';
import type { NavigationProp } from '../../types/navigation';
import type { StreamChatGenerics } from '../../types/streamChat';

function Content() {
  const { setThread } = useStreamChatContext();
  const navigation = useNavigation<NavigationProp>();
  const onThreadSelect = useCallback(
    (message: MessageType<StreamChatGenerics> | null) => {
      setThread(message);
      navigation.navigate('Thread');
    },
    [setThread, navigation]
  );

  return (
    <View style={{ flex: 1 }}>
      <MessageList
        onThreadSelect={onThreadSelect}
      />
      <MessageInput />
    </View>
  );
}

export function Show() {
  const { chatClient } = useContext(AuthContext);
  const { channel, thread } = useStreamChatContext();
  const headerHeight = useHeaderHeight();
  const { setTopInset } = useAttachmentPickerContext();

  useEffect(() => {
    setTopInset(headerHeight);
  }, [headerHeight]);

  return (
    <SafeAreaView>
      <Chat client={chatClient} i18nInstance={streamI18n}>
        <Channel
          channel={channel}
          thread={thread}
        >
          <Content />
        </Channel>
      </Chat>
    </SafeAreaView>
  );
}
```

- Thread.tsx
```
import { SafeAreaView, View } from 'react-native';
import { useContext } from 'react';
import { Channel, Chat, Thread } from 'stream-chat-expo';
import { AuthContext } from '../../contexts/AuthContext';
import { useStreamChatContext } from '../../contexts/StreamChatContext';
import { streamI18n } from '../../config/streamI18n';

export function Index() {
  const { chatClient } = useContext(AuthContext);
  const { channel, setThread, thread } = useStreamChatContext();

  return (
    <SafeAreaView>
      <Chat client={chatClient} i18nInstance={streamI18n}>
        <Channel
          channel={channel}
          thread={thread}
          threadList
        >
          <View
            style={{
              flex: 1,
              justifyContent: 'flex-start',
            }}
          >
            <Thread
              onThreadDismount={() => setThread(null)}
            />
          </View>
        </Channel>
      </Chat>
    </SafeAreaView>
  );
}
```
</p>
</details>

### Offline support

- [ ] I have enabled offline support.
- [x] The feature I'm having does not occur when offline support is disabled. (stripe out if not applicable)

## Environment

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
  "dependencies": {
    "@expo/vector-icons": "^13.0.0",
    "@react-navigation/elements": "^1.3.3",
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/stack": "^6.2.1",
    "expo": "^48.0.0",
    "expo-application": "~5.1.1",
    "expo-av": "~13.2.1",
    "expo-clipboard": "~4.1.2",
    "expo-constants": "~14.2.1",
    "expo-dev-client": "~2.2.1",
    "expo-document-picker": "~11.2.2",
    "expo-file-system": "~15.2.2",
    "expo-haptics": "~12.2.1",
    "expo-image-manipulator": "~11.1.1",
    "expo-image-picker": "~14.1.1",
    "expo-keep-awake": "~12.0.1",
    "expo-linking": "~4.0.1",
    "expo-localization": "~14.1.1",
    "expo-location": "~15.1.1",
    "expo-media-library": "~15.2.3",
    "expo-sharing": "~11.2.2",
    "expo-splash-screen": "~0.18.2",
    "expo-status-bar": "~1.4.4",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.71.8",
    "react-native-safe-area-context": "4.5.0",
    "react-native-screens": "~3.20.0",
    "react-native-storage": "^1.0.1",
    "react-native-svg": "13.4.0",
    "react-native-web": "~0.18.7",
    "stream-chat-expo": "5.22.1",
  },
```

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
    - [ ] iOS
    - [ ] Android
    - [ ] **iOS** but have not tested behavior on Android
    - [ ] **Android** but have not tested behavior on iOS
    - [x] Both
- **`stream-chat-react-native` version you're using that has this issue:**
    - `"stream-chat-expo": "5.22.1"`
- Device/Emulator info:
  - [x] I am using a physical device
  - OS version: `iOS 16.1.1` , `Android13`, `Android14` , `Android15`
  - Device/Emulator: `iPhone 12` , `Pixel 3a` , `Pixel 4` , `Pixel6` 

</p>
</details>

### Screenshots

<details><summary>Click To Expand</summary>
<p>

<img width="226" alt="iPhone_13" src="https://github.com/GetStream/stream-chat-react-native/assets/17227480/143e0b4b-7669-4df4-a8d9-03d786197b11">

- iOS

https://github.com/GetStream/stream-chat-react-native/assets/17227480/51faf982-29da-4bab-b11a-504a44733cf3

- Android

https://github.com/GetStream/stream-chat-react-native/assets/17227480/77928c34-d4ac-41fc-b838-0494aefd23ab

</p>

</details>

---

**Comment by atsss** [comment]
@khushal87 Hi Thanks for the hard work to fix it. I've tested it with 5.23.2 but I think the issue still exists. Could you please let me know if I need to change something on my side?

**Comment by khushal87** [comment]
Hey @atsss, I tried the following issue on my iOS simulator and could not reproduce it as you mentioned. Do you have anything specific added as customization or props that causes a different behaviour for you?


https://github.com/GetStream/stream-chat-react-native/assets/39884168/b6620e26-b5c5-48ff-9a05-86e6709a153d

**Comment by santhoshvai** [comment]
@atsss Could you share your code of how you navigate to thread and back.. maybe that gives a clue of why we cant reproduce this from our side.. 

I am reponing this issue

**Comment by atsss** [comment]
@santhoshvai @khushal87 Hi! Thanks for responding. Basically, I followed the example app. The following links are the reference.

Channel: https://github.com/GetStream/stream-chat-react-native/blob/develop/examples/ExpoMessaging/app/channel/%5Bcid%5D/index.tsx
Thread: https://github.com/GetStream/stream-chat-react-native/blob/develop/examples/ExpoMessaging/app/channel/%5Bcid%5D/thread/%5Bcid%5D/index.tsx


I attached the whole code snippets of Channel and Thread in the Project Related Information of this issue. I mainly changed three things from the references.
1. Disable offline mode
2. Use `React Navigation` instead of expo-router
3. Add `thread` props to `Channel` component as reading [the troubleshooting guide](https://getstream.io/chat/docs/sdk/reactnative/basics/troubleshooting/)

Once I remove the `thread` props from `Channel` component, the count is updated as expected but it causes another issue, which is the message in a channel is sent to a thread.

- How to navigate to a thread
  - Set a thread in `OnThreadSelect` callback
  - Navigate with `React Navigation` in `OnThreadSelect` callback
```
  const onThreadSelect = useCallback(
    (message: MessageType<StreamChatGenerics> | null) => {
      setThread(message);
      navigation.navigate('Thread');
    },
    [setThread, navigation]
  );

  return (
    <View style={{ flex: 1 }}>
      <MessageList
        onThreadSelect={onThreadSelect}
      />
      <MessageInput />
    </View>
  );
```
- How to navigate back to a channel
  - Set `null` as `thread` in `onThreadDismount` callback
  - Navigate with `React Navigation` using `Back` in header
```
<Thread onThreadDismount={() => setThread(null)} />
```

**Comment by khushal87** [comment]
Hey @atsss, assuming you have a similar code as [this](https://github.com/GetStream/stream-chat-react-native/blob/develop/examples/TypeScriptMessaging/App.tsx), it works fine on our side with both offline support enabled and disabled. Also, we use react-navigation here in the example so can you check if there's something that you are doing differently? Thanks 😄

**Comment by atsss** [comment]
> ssuming you have a similar code as [this](https://github.com/GetStream/stream-chat-react-native/blob/develop/examples/TypeScriptMessaging/App.tsx), it works fine on our side with both offline support enabled and disabled. Also, we use react-navigation here in the example so can you check if there's something that you are doing differently? Thanks 😄

@khushal87 I've checked the example in my local and the count is updated properly. Do you know why mine is not updated based on shared code snippets in the description 😅 ?

**Comment by khushal87** [comment]
> > ssuming you have a similar code as [this](https://github.com/GetStream/stream-chat-react-native/blob/develop/examples/TypeScriptMessaging/App.tsx), it works fine on our side with both offline support enabled and disabled. Also, we use react-navigation here in the example so can you check if there's something that you are doing differently? Thanks 😄
> 
> 
> 
> @khushal87 I've checked the example in my local and the count is updated properly. Do you know why mine is not updated based on shared code snippets in the description 😅 ?

That's what confusing to me as well. Probably share your implementation snippet and we will try to find out something. 🙂

**Comment by khushal87** [comment]
Hey @atsss, are you still facing this issue or it can be closed?

**Comment by khushal87** [comment]
Even while using the code from our implementation?

**Comment by atsss** [comment]
It's working on the sample implementation but It's not working on my code snippets. I'll investigate more and come back if I need more help. Thank you
