### ISSUE TITLE
Bug Reports

### ISSUE THREAD

**Issue by aniciom** [GetStream/stream-chat-react-native#24]
Hello @jaapbakker88 i want to report some issues those are not working good in iPhone X OS 12.3 (I didn't try it on android or other iPhone versions)

I'm running example two

First one related to the initialization of the app, it shows the next error:
![unnamed](https://user-images.githubusercontent.com/5354596/60696995-770fa680-9ebe-11e9-9abf-ff958d351acc.jpg)

I fixed it upgrading to react native 0.59.10 and the error is gone

Second one, it happens randomly when i want to attach a photo
![unnamed (1)](https://user-images.githubusercontent.com/5354596/60697013-90b0ee00-9ebe-11e9-9ee2-29c743599c74.jpg)

I get the next error in the Xcode debugger
```
[LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x281cee850 UIView:0x113f45a50.width == - 16   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x281cee850 UIView:0x113f45a50.width == - 16   (active)>
```
The screen remains in grey and no interaction with the rest of the components.

I could got it working once but the spinner in the image kept working and seems the image was never getting uploaded (maybe backend issue)

This is my react-native info: 
 ```
 React Native Environment Info:
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      Yarn: 1.16.0 - ~/.nvm/versions/node/v10.16.0/bin/yarn
      npm: 6.10.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
      Android SDK:
        API Levels: 21, 22, 23, 24, 25, 26, 27, 28
        Build Tools: 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.0, 28.0.2, 28.0.3
        System Images: android-25 | Google APIs Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 11.0/11M336w - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.5 => 0.59.5 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native: 0.59.10
```

Thanks

**Comment by jaapbakker88** [comment]
i can't seem to replicate this issue: 

steps I took:
- `git clone repo`
- `yarn start`
- `cd native-package`
- `yarn start`
- `cd ../examples/two`
- `react-native run-ios`

Can you confirm these are the steps you took?

**Comment by aniciom** [comment]
Are you trying on iPhone X?

**Comment by jaapbakker88** [comment]
Yeah I was trying iOS. I'll try and test again today and see if I can get someone else to test as well.

**Comment by aniciom** [comment]
There's no warning about those contraints i posted on the XCode's debug? weird :(

**Comment by aniciom** [comment]
I just tried it with xcode 10.3 and got the same error

2019-07-30 08:16:18.011695-0300 two[2772:1122968] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x281134f50 UIView:0x1587428e0.width == - 16   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x281134f50 UIView:0x1587428e0.width == - 16   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.

**Comment by jaapbakker88** [comment]
@aniciom We can't seem to replicate this issue on our end. Can you give a step by step how you get to the error?

**Comment by aniciom** [comment]
Jaap i did the next steps:

git clone https://github.com/GetStream/stream-chat-react-native.git
cd stream-chat-react-native
make
cd examples/two

Then i open XCode and build it and run it in my real iphone X device, even i used the same react native version that the library is using

**Comment by jaapbakker88** [comment]
@aniciom I tried once more the way you've been running this, can't replicate the issue. I'm going to close this right now but I'll keep an eye out on this specific issue and I'll reopen if I find out more.

**Comment by aniciom** [comment]
Sure, no problem
