### ISSUE TITLE
Getstream Chat Error: AnimatedValue: Attempting to set value to undefined

### ISSUE THREAD

**Issue by AleenaJoseph426** [GetStream/stream-chat-react-native#240]
I am working with Getstream chat SDk in react native,
My package.json file looks like:
"dependencies": {
"@react-native-community/masked-view": "^0.1.10",
"@react-native-community/netinfo": "^5.9.4",
**"react": "16.13.1",
"react-native": "0.63.1",**
"react-native-device-info": "^5.6.2",
"react-native-document-picker": "^3.5.3",
"react-native-fast-image": "^8.1.5",
"react-native-gesture-handler": "^1.6.1",
"react-native-image-picker": "^2.3.2",
"react-native-safe-area-context": "^3.1.1",
"react-native-screens": "^2.9.0",
**"react-navigation": "4.1.0",
"react-navigation-stack": "^2.8.2",
"stream-chat-react-native": "^0.13.1"**
},
I am using the same react native code in the "native message example" provided in the link : https://github.com/GetStream/stream-chat-react-native

While running, The chat list screen is presenting , but on selecting a chat it shows an error as:
![Simulator Screen Shot - iPhone 11 - 2020-07-16 at 11 01 00](https://user-images.githubusercontent.com/68363600/87632399-f7feb080-c756-11ea-98c5-37d68e9dd951.png)

Do anyone has the same issue, Could you please help me to solve this.
Thanks in advance.

gz#4469

**Comment by plotic** [comment]
Same here with latest version 0.13.1

**Comment by vishalnarkhede** [comment]
Hey @plotic @AleenaJoseph426 this is only happening on react-native 0.63.

We are working on preparing the fix. Will update you soon :)

**Comment by vishalnarkhede** [comment]
Hey @plotic @AleenaJoseph426 

Please use stream-chat-react-native@0.14.0. It has been fixed :)

**Comment by AleenaJoseph426** [comment]
Yes. Its solved in stream-chat-react-native@0.14.0. Thanks for your timely update. :)
