### ISSUE TITLE
Crash on image upload - Missing request token on react-native 0.63

### ISSUE THREAD

**Issue by plotic** [GetStream/stream-chat-react-native#241]
**Describe the bug**
Crash on image upload

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native)
- react-native 
- Device/Emulator - ios
- stream version 0.13.1

**To Reproduce**
 ```
        const promises = [
            channel.sendImage(
                imageUri          
            )            
        ];
        const results = await Promise.all(promises);
    
        const attachments = results.map(response => {
            return {
                type: 'image',
                thumb_url: response.file,
                asset_url: response.file,
            };
        });
        
        const response = await channel.sendMessage({
            text: text,
            attachments,
        });
```

**Expected behavior**
Upload works without crashing 

**Additional context**
User token initialisation using - chat.devToken()

**Screenshots**
![Simulator Screen Shot - iPhone 11 - 2020-07-16 at 11 26 58](https://user-images.githubusercontent.com/6691567/87646962-d94ce980-c757-11ea-925d-94a6608f4d13.png)

gz#4473

**Comment by shodgetts** [comment]
Agent comment from Séni Gueye in <a href='https://getstream.zendesk.com/agent/tickets/4473'>Zendesk ticket #4473</a>:<br><br>Hi,

Thanks for the report.
I'm transferring this on to our React Native team.
They'll get back to you as soon as they possibly can.

Best regards,
Seni

**Comment by vishalnarkhede** [comment]
Hey @plotic , we are looking into this. Will get back to you shortly :)

**Comment by plotic** [comment]
> Hey @plotic , we are looking into this. Will get back to you shortly :)

Not sure if it helps, for me it's reproducible when upgrading "react-native" to "0.63.1"

**Comment by vishalnarkhede** [comment]
@plotic yeah I noticed that as well. Looks like it has already been raised by quite few people:

https://github.com/facebook/react-native/issues/29364
https://github.com/facebook/react-native/issues/29021

**Comment by anthony1110** [comment]
I also have same issue. I use hack for this https://github.com/facebook/react-native/issues/29021#issuecomment-662196480.
