### ISSUE TITLE
[🐛] Order of image picker images is incorrect

### ISSUE THREAD

**Issue by VNDRN** [GetStream/stream-chat-react-native#2410]
## Issue

When using the image picker (expo app), the images are not sorted from most recent to oldest, instead a random order seems to be used...

### Steps to reproduce

1. go to a chat in an expo app
2. add an image as an attachement
3. your images are in a random order

### Expected behavior

The images in the bottomsheet are ordered by newest to oldest

### Customization

<details><summary>Click To Expand</summary>
<p>

```typescript jsx
# N/A
```
</p>
</details>

### Offline support

- [ ] I have enabled offline support.
- [ ] The feature I'm having does not occur when offline support is disabled. (stripe out if not applicable)

## Environment

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
    - [ ] iOS
    - [ ] Android
    - [ ] **iOS** but have not tested behavior on Android
    - [ ] **Android** but have not tested behavior on iOS
    - [ ] Both
- **`stream-chat-react-native` version you're using that has this issue:**
    - `e.g. 5.4.3`
- Device/Emulator info:
  - [ ] I am using a physical device
  - OS version: `e.g. Android 10`
  - Device/Emulator: `e.g. iPhone 11`

</p>
</details>

### Screenshots

<details><summary>Click To Expand</summary>
<p>

</p>
</details>

---

**Comment by VNDRN** [comment]
I noticed now in the source code modificationTime is used, I'd think a better default would be creationTime, as the ios Photo library uses this sorting

**Comment by khushal87** [comment]
Hey @VNDRN, this behaviour is customizable. You can register your own native handler as per [the docs](https://getstream.io/chat/docs/sdk/reactnative/customization/native_handlers/). Copy the snippet and just change the `sortBy` param as per your requirement. We have kept it as modification time to keep it in parity with all SDKs so that's the default behaviour.

Here's the snippet:

```tsx
import { registerNativeHandlers } from 'stream-chat-react-native';

registerNativeHandlers({
 getPhotos: async ({
  after,
  first,
}: MediaLibrary.AssetsOptions): Promise<ReturnType> => {
  try {
    // NOTE:
    // should always check first before requesting permission
    // because always requesting permission will cause
    // the app to go to background even if it was granted
    const { accessPrivileges, status } = await MediaLibrary.getPermissionsAsync();
    if (status !== 'granted') {
      const { status: newStatus } = await MediaLibrary.requestPermissionsAsync();
      if (newStatus !== 'granted') {
        throw new Error('getPhotos Error');
      }
    }
    const results = await MediaLibrary.getAssetsAsync({
      after,
      first,
      mediaType: [MediaLibrary.MediaType.photo, MediaLibrary.MediaType.video],
      sortBy: [MediaLibrary.SortBy.creationTime],
    });
    const assets = results.assets.map((asset) => ({
      duration: asset.duration,
      height: asset.height,
      id: asset.id,
      name: asset.filename,
      source: 'picker' as const,
      type: asset.mediaType,
      uri: asset.uri,
      width: asset.width,
    }));

    const hasNextPage = results.hasNextPage;
    const endCursor = results.endCursor;
    return { assets, endCursor, hasNextPage, iOSLimited: accessPrivileges === 'limited' };
  } catch {
    throw new Error('getPhotos Error');
  }
};
});
```

**Comment by VNDRN** [comment]
Thanks! I had it changed with patch-package but this is a neater solution
