### ISSUE TITLE
[🐛] Missing channelQueries table on fresh install

### ISSUE THREAD

**Issue by szechyjs** [GetStream/stream-chat-react-native#2439]
## Issue

I receive the following error when loading the channel list on a new install when offline support is enabled. After receiving the error the channels do load from the api and everything works correctly, however it definitely seems like there is a race condition here. Similar to #2001 

```
WARN  Failed to get channels from database:  [Error: Query/queries failed: Error: [react-native-quick-sqlite] SQL execution error: no such table: channelQueries
Error: [react-native-quick-sqlite] SQL execution error: no such table: channelQueries
    at execute (native)
    at anonymous 
    at anonymous 
    at apply (native)
    at selectChannelIdsForFilterSort 
    at getChannelsForFilterSort 
    at loadOfflineChannels 
    at anonymous 
    at commitHookEffectListMount
```

### Steps to reproduce

1. Install app
2. Open channel list

### Expected behavior

Channel list loads without error

### Customization

<details><summary>Click To Expand</summary>
<p>

```typescript jsx
# N/A
```
</p>
</details>

### Offline support

- [x] I have enabled offline support.
- [x] The feature I'm having does not occur when offline support is disabled. (stripe out if not applicable)

## Environment

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
  "react-native": "0.73.4",
  "react-native-quick-sqlite": "^8.0.6",
  "stream-chat-react-native": "^5.22.1",
```

**`react-native info` output:**

```
System:
  OS: macOS 14.3.1
  CPU: (14) arm64 Apple M3 Max
  Memory: 62.36 MB / 36.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.19.1
    path: ~/.asdf/installs/nodejs/18.19.1/bin/node
  Yarn:
    version: 1.22.21
    path: ~/.asdf/installs/nodejs/18.19.1/bin/yarn
  npm:
    version: 10.2.4
    path: ~/.asdf/plugins/nodejs/shims/npm
  Watchman:
    version: 2024.01.22.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/jared/.asdf/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11330709
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 3.3.0
    path: /Users/jared/.asdf/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.4
    wanted: 0.73.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

- **Platform that you're experiencing the issue on**:
    - [ ] iOS
    - [ ] Android
    - [x] **iOS** but have not tested behavior on Android
    - [ ] **Android** but have not tested behavior on iOS
    - [ ] Both
- **`stream-chat-react-native` version you're using that has this issue:**
    - `5.22.1`
- Device/Emulator info:
  - [ ] I am using a physical device
  - OS version: `iOS 17.2`
  - Device/Emulator: `iPhone 15 Pro max`

</p>
</details>

### Screenshots

<details><summary>Click To Expand</summary>
<p>

</p>
</details>

---

**Comment by khushal87** [comment]
Hey @szechyjs, we have noticed a similar issue that seems to happen with the latest version of 0.73.4. We are working on the SDK's compatibility with the version, and it might take some time. Until then, you can downgrade the version to 0.72.* and use our SDK. It shouldn't be a problem. Thanks 😄
