### ISSUE TITLE
[🐛] Export namespace should be first transformed by `@babel/plugin-transform-export-namespace-from`.

### ISSUE THREAD

**Issue by 2531800823** [GetStream/stream-chat-react-native#2456]
## Issue

Web Bundling failed 7407ms
error: node_modules\react-native-reanimated\src\index.web.ts: D:\desktop\project3\stream-chat-react-native\examples\ExpoMessaging\node_modules\react-native-reanimated\src\index.web.ts: Export namespace should be first transformed by `@babel/plugin-transform-export-namespace-from`.
> 5 | export * from './reanimated1';
>  6 | export * from './reanimated2';
> 7 | export * as default from './Animated';

### Steps to reproduce

but the premise is <code>cd expo-package && yarn install</code> An error has occurred
![image](https://github.com/GetStream/stream-chat-react-native/assets/75556006/d7b4bc95-03e1-4e00-8ab5-1b8fa0248dae)

And then everything was fine.

Execute under file <b>ExpoMessaging</b>

<code>yarn run web</code>
![image](https://github.com/GetStream/stream-chat-react-native/assets/75556006/6ac0a1a1-bd2e-45f6-9586-9982dd4fa93b)

## Project Related Information

<code>git clone https://github.com/GetStream/stream-chat-react-native.git</code>
operate `examples\ExpoMessaging\README.md`

**Comment by khushal87** [comment]
Hey @2531800823, can you please brief me on where exactly you noticed this issue? The information above is not helpful for us to triage it. Thanks 😄

**Comment by 2531800823** [comment]
I ran into it by following `the examples\ExpoMessaging\README.md` file ,But I'm running `npm run web`

**Comment by khushal87** [comment]
Hey @2531800823, we do not support web with our React native SDK currently. Please use React SDK if you are looking forward to use stream sdk on web.
