### ISSUE TITLE
Customize background for MessageContent 

### ISSUE THREAD

**Issue by atsss** [GetStream/stream-chat-react-native#2461]
**Motivation**
- Want to customize the background color for URL attachment message
  - Want to make it white background color when the messages aren't `isMyMessage`
  - Want to make it `grey_gainsboro` background color when the messages aren't `isMyMessage`
<img width="226" alt="iPhone_13" src="https://github.com/GetStream/stream-chat-react-native/assets/17227480/2d26cff5-a2fe-424b-baf3-4aa0a5ef06cb">

**Proposed solution**
- Currently, the `backgroundColor` is computed in the `MessageContent` component and there is no params/configurations to change the logic 
> https://github.com/GetStream/stream-chat-react-native/blob/bacabd96482d40b1847bb57464b593a4c3798ed1/package/src/components/Message/MessageSimple/MessageContent.tsx#L222
- Add one prop to `MessageContent` component to override the computed `backgroundColor`

**Acceptance Criteria**
- Can override the backgroundColor

**Comment by khushal87** [comment]
Fixed by adding `receiverMessageBackgroundColor` and `senderMessageBackgroundColor` theme properties in the theme 
`messageSimple.content` object. That should help you. Please feel free to use it once the next release is done. Thanks 😄
