### ISSUE TITLE
Customise Chat Bubble for other user

### ISSUE THREAD

**Issue by soorajpandey** [GetStream/stream-chat-react-native#2467]
Hello Team,

We are using stream sdk in our app and it is awesome, no issues so far. Documentation is awesome, 
I have one query which I didn't get in the documentation. 

After adding dark mode in our app, we want to change background and text colour of the other user chat bubble, we are able to fix it for own message, but not able to solve it for other user.

Could you please help us? or if we are missing any documentation part please let us know.

Regards

### Steps to reproduce

nil

### Expected behavior

nil

### Customization

<details><summary>Click To Expand</summary>
<p>

nil
</p>
</details>

### Offline support

- [ ] I have enabled offline support.
- [ ] The feature I'm having does not occur when offline support is disabled. (stripe out if not applicable)

## Environment

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

**`react-native info` output:**

```
System:
  OS: macOS 14.4.1
  CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Memory: 546.51 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 21.6.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.21
    path: /usr/local/bin/yarn
  npm:
    version: 10.2.4
    path: /usr/local/bin/npm
  Watchman:
    version: 2024.01.22.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.4
      - iOS 17.4
      - macOS 14.4
      - tvOS 17.4
      - visionOS 1.1
      - watchOS 10.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11255304
  Xcode:
    version: 15.3/15E204a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: ^18.2.0
  react-native:
    installed: 0.73.4
    wanted: ^0.73.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

- **Platform that you're experiencing the issue on**:
    - [ ] iOS
    - [ ] Android
    - [ ] **iOS** but have not tested behavior on Android
    - [ ] **Android** but have not tested behavior on iOS
    - [ ] Both
- **`stream-chat-react-native` version you're using that has this issue:**
    - `e.g. 5.4.3`
- Device/Emulator info:
  - [ ] I am using a physical device
  - OS version: `e.g. Android 10`
  - Device/Emulator: `e.g. iPhone 11`

</p>
</details>

### Screenshots

<details><summary>Click To Expand</summary>
<p>

</p>
</details>

---

**Comment by khushal87** [comment]
Hey @soorajpandey,

So, I am assuming you are already using the [`myMessageTheme`](https://getstream.io/chat/docs/sdk/reactnative/core-components/channel/#mymessagetheme) property in the `Channel` component for the sender's message theme, right?

If not, I can help you with both the sender and receiver styling:

Sender:
Please pass the following on to the `myMessageTheme` property in the `Channel` component:
```
 messageSimple: {
            content: {
              containerInner: {
                backgroundColor: 'pink',
              },
            },
          },
```

For Receiver:
The above theme remains the same; instead of passing it to the `myMessageTheme', you would be passing it to the [SDK Theme](https://getstream.io/chat/docs/sdk/reactnative/customization/theming/).

I hope that helps.

Regards,
Khushal Agarwal

**Comment by soorajpandey** [comment]
I tried passing it to overlay providers as mentioned in the docs

const style = { style: myMessageTheme };

<OverlayProvider value={style}></OverlayProvider>

It is not working, also when I am using myMessageTheme in Channel component it works for own user theme.

**Comment by khushal87** [comment]
It should work, unless you have some other theme as well, that is conflicting with the behaviour. Can you please share your code?

**Comment by soorajpandey** [comment]
`
<OverlayProvider value={style}>
                <Chat client={client}>
                            <Navigation />
                </Chat>
</OverlayProvider>
`

`
<ThemeProvider style={theme}>
            <Channel
                MessageSimple={CustomMessage}
                channel={channel}
                additionalTextInputProps={additionalTextInputProps}
                animatedLongPress={false}
                enforceUniqueReaction={false}
                initialScrollToFirstUnreadMessage
                disableTypingIndicator
                deletedMessagesVisibilityType="sender"
                AudioAttachment={AudioAttachment}
                NetworkDownIndicator={() => <React.Fragment />}
                KeyboardCompatibleView={CustomKeyboardCompatibleView}
                InputReplyStateHeader={CustomInputReplyStateHeader}
                Card={VoiceMessageAttachment}
                Input={InputBox}
                thread={thread} threadList={!!thread}
                myMessageTheme={colorSchema === 'dark' ? myMessageThemeDark : myMessageTheme}
                onPressMessage={onPressInMessages}
                InputButtons={RenderNothing}
                SendButton={RenderNothing}
                doDocUploadRequest={customDoDocUploadRequest}
                UrlPreview={UrlPreview}
                onPressInMessage={RenderNothing}
                maxTimeBetweenGroupedMessages={30000}
            >
                <ChannelBackgroundView
                    channelId={channel?.id!}
                    style={{ flex: 1, backgroundColor: colorSchema === 'dark' ? darkMode.background : lightMode.background                 }}>
                    <>
                        <ChannelHeader channel={channel} currentUser={currentUser} onPress={handleMenuOnPress} />
                        {pinnedMessages.length > 0 &&
                            <View
                                // position at the top of the screen
                                style={{
                                    position: 'absolute',
                                    // top below the header
                                    top: insets.top + 50,
                                    width: '100%',
                                    zIndex: 100,
                                    backgroundColor: colorSchema === 'dark' ? darkMode.background : lightMode.background,
                                }}>
                                <PinnedMessagesComponent pinnedMessages={pinnedMessages} />
                            </View>
                        }
                        <MessageList
                            onThreadSelect={(thread) => {
                                navigation.navigate('ThreadScreen', {
                                    channelId: channelId,
                                    thread: thread,
                                });
                            }}
                            additionalFlatListProps={{
                                contentContainerStyle: {
                                    paddingHorizontal: 10,
                                    paddingTop: 10,
                                    paddingBottom: 10,
                                },
                            }
                            }
                        />
                        <MessageInput additionalTextInputProps={{ placeholder: 'Type a message' }} />
                        <View style={[styles.footerContainer]} />
                    </>
                </ChannelBackgroundView>
            </Channel>
 </ThemeProvider>
`

`
const CustomMessage = (props: MessageSimpleProps) => {
        const doubleTapRef = useRef(null);
        const { message, handleToggleReaction } = useMessageContext();

        const _onDoubleTap = useAnimatedGestureHandler<TapGestureHandlerGestureEvent>(
            {
                onActive: () => {
                    runOnJS(handleToggleReaction)('love')
                },
            },
            [message],
        );

        return (
            <TapGestureHandler
                waitFor={doubleTapRef}>
                <Animated.View>
                    <TapGestureHandler
                        ref={doubleTapRef}
                        numberOfTaps={2}
                        onHandlerStateChange={_onDoubleTap}>
                        <Animated.View>
                            <MessageSimple {...props} />
                        </Animated.View>
                    </TapGestureHandler>
                </Animated.View>
            </TapGestureHandler>
        );
    }

    const theme = {
        messageList: {
            container: {
                backgroundColor: 'transparent',
            },
        },
    };
`

here is the code which I am using.

**Comment by khushal87** [comment]
Curious why you are providing ThemeProvider separately?

**Comment by soorajpandey** [comment]
I tried providing theme the way you have mentioned but didn't work, I am using stream-chat-expo 5.25.0.

**Comment by soorajpandey** [comment]
thank you for looking into this issue, it seems other styles are working for other user component except chat bubble background colour. I saw an open issue where same mentioned so I am closing this and keeping an eye on that issue, thanks again.
