### ISSUE TITLE
Pasting images or files from clipboard into message input

### ISSUE THREAD

**Issue by krisnapy** [GetStream/stream-chat-react-native#2474]
How can we implement the ability for users to paste copied images or files directly into the message input field? This feature, commonly found in platforms like iMessage and Slack, is highly anticipated by our users.

**Comment by khushal87** [comment]
Hey @krisnapy, this is a limitation of React Native Native CLI overall, and the package we use for the same, which is `@react-native-clipboard/clipboard`, doesn't seem to allow it as per the API specs. 

If you are in an expo environment, I think this is allowed, so we can have a look into it in the near future.

We will keep this in mind for the future and see if adding it might create real value depending on the number of requests we get for the same. Until then, I will be closing this issue. Thanks 😄

**Comment by krisnapy** [comment]
Hey @khushal87 thanks for the answer 🙏🏼
