### ISSUE TITLE
[🐛] OverlayProvider is raising "Illegal invocation at Headers.has" on web when using Expo and Expo Router

### ISSUE THREAD

**Issue by abdalem** [GetStream/stream-chat-react-native#2476]
## Issue

We started this week the developement of a new app. So we decided to go with the latest version of expo with a template that implements the Expo Router. Everything was smooth until we imported the OverlayProvider which raises the following error:
![image](https://github.com/GetStream/stream-chat-react-native/assets/19971392/42d0ec39-9ee5-4c68-bc14-e60ed1d9e2e3)

### Steps to reproduce

1. Create a new expo project with `npx create-expo-app --template`
2. Follow carefully the tutorial here: https://getstream.io/chat/react-native-chat/tutorial/?language=Expo
3. Stop at this section: https://getstream.io/chat/react-native-chat/tutorial/?language=Expo#configure-overlayprovider-component 
4. When checking web, you'll notice the error

### Expected behavior

Not raising this error.

### Customization

<details><summary>Click To Expand</summary>
<p>

```typescript jsx
# N/A
```
</p>
</details>

### Offline support

- [ ] I have enabled offline support.
- [ ] The feature I'm having does not occur when offline support is disabled. (stripe out if not applicable)

## Environment

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
    - [ ] iOS
    - [ ] Android
    - [ ] **iOS** but have not tested behavior on Android
    - [ ] **Android** but have not tested behavior on iOS
    - [ ] Both
- **`stream-chat-react-native` version you're using that has this issue:**
    - `e.g. 5.4.3`
- Device/Emulator info:
  - [ ] I am using a physical device
  - OS version: `e.g. Android 10`
  - Device/Emulator: `e.g. iPhone 11`

</p>
</details>

### Screenshots

<details><summary>Click To Expand</summary>
<p>

</p>
</details>

---

**Comment by khushal87** [comment]
Hey @abdalem, are you trying to run the app on web?

**Comment by abdalem** [comment]
Hi @khushal87. Is there any way to use both on an expo stack ? React for web and RN for mobile ?  It will avoid me to split the apps just for stream.

**Comment by khushal87** [comment]
Hey @abdalem, you cane explore https://docs.expo.dev/router/advanced/platform-specific-modules/
