### ISSUE TITLE
Comply with new Google Play's Photo and Video Permissions policy - removal of READ_MEDIA_IMAGES and READ_MEDIA_VIDEO permissions

### ISSUE THREAD

**Issue by fabiendem** [GetStream/stream-chat-react-native#2486]
**Motivation**

Google announced a new Google Play's Photo and Video Permissions policy.
The full details are available at https://support.google.com/googleplay/android-developer/answer/14115180?hl=en

This is mainly about upcoming changes around the `READ_MEDIA_IMAGES` and `READ_MEDIA_VIDEO` permissions.

Quoting:
> - Mid 2024: Apps with one-time or infrequent use of photos requested to use a system photo picker and remove READ_MEDIA_IMAGES and READ_MEDIA_VIDEO permissions from their app manifest.
> - Early 2025: Only apps with broad access core functionality can use READ_MEDIA_IMAGES and READ_MEDIA_VIDEO permissions.

Apps using those permissions for the Stream Chat feature are likely to fall into this "one-time or infrequent use of photos" bucket.
See https://support.google.com/googleplay/android-developer/answer/14115180?hl=en#zippy=%2Cwhat-does-it-mean-to-have-a-one-time-or-infrequent-use-of-photos-or-video-files

> What does it mean to have a one-time or infrequent use of photos or video files?
> Examples of one-time or infrequent use of photos or video files include, but are not limited to, uploading a profile picture, uploading an image for a playlist, or uploading a photo of a check for banking purposes. Infrequent use infers that your app does not have a photo or video use case as its core functionality. If your app has a one-time or infrequent use case for photo or video files, you may not use the READ_MEDIA_IMAGES or READ_MEDIA_VIDEO permission, and we urge you to instead use a system picker to preserve user privacy.
 
**Proposed solution**

Google suggests using a system picker, such as [an Android photo picker](https://developer.android.com/training/data-storage/shared/photopicker).
See https://support.google.com/googleplay/android-developer/answer/14115180?hl=en# and https://developer.android.com/training/data-storage/shared/photopicker

**Acceptance Criteria**

Apps using the Stream SDK will stay compliant by 2024/Early 2025.
Stream SDK switches to a system picker or an alternative method, so we no longer use the READ_MEDIA_IMAGES and READ_MEDIA_VIDEO permissions.

**Comment by khushal87** [comment]
Hey @fabiendem, for this to happen, we will have to wait for our dependencies like [react-native-cameraroll](https://github.com/react-native-cameraroll/react-native-cameraroll/) and expo-media-library to be compliant first and then we can add the following support as well.

FYI: we use these libraries for our image picker.

**Comment by fabiendem** [comment]
Posted at https://github.com/react-native-cameraroll/react-native-cameraroll/issues/618

**Comment by fabiendem** [comment]
Timeline is clarified at https://support.google.com/googleplay/android-developer/answer/14115180?hl=en
![Screenshot 2024-06-27 at 14 32 58](https://github.com/react-native-cameraroll/react-native-cameraroll/assets/1186282/c9a65f8d-cf7d-4d46-8ac8-01f90218913e)

**Comment by khushal87** [comment]
Amazing!

**Comment by mishkeTz** [comment]
Hello @khushal87, are there any news on this? For react-native project?
