### ISSUE TITLE
[🐛]Not received firebase notification all the time.

### ISSUE THREAD

**Issue by krushita042023** [GetStream/stream-chat-react-native#2506]
## Issue

When multiple users connect with stream it's give me Too many requests error in QueryChannels and user not getting firebase notification in device, but in stream dashboard we show success push logs.

If you need any thing else please let me know.
## Project Related Information
 
```typescript jsx
"stream-chat-react-native": "^5.24.0"
 "stream-chat": "^8.14.3"
 "@react-native-firebase/app": "^18.5.0"
 "@react-native-firebase/messaging": "^18.5.0"
```
</p>
</details>

---

**Comment by gc0rtes** [comment]
Hey @krushita042023, thank you for reaching out.

Just so you know, the issues section is specifically for reporting bugs, feature requests, or vulnerability concerns related to the SDK. For implementation assistance, kindly direct your query to Stream support here:

https://getstream.io/contact/support/

When contacting support, please provide the following information:

1. App ID
2. The error code and the message you are receiving for query channels
3. Receiver user ID, which is not receiving the notification
4. Channel type and channel ID

We are more than happy to assist you through our support line. I'll go ahead and close this issue now.

Kind regards,
Guilherme
Integration Support Engineer
