### ISSUE TITLE
[🐛] Audio Recording - http: no such file. Can be upload

### ISSUE THREAD

**Issue by netoya** [GetStream/stream-chat-react-native#2513]
## Issue

Audio Record can't upload.

### Steps to reproduce

Create a new React Native project
Follow steps in getStream page for RN
Add .aac and mime audio/aac en Overview Panel
Enable audioRecording in the chat
Try to send audio
Audio upload file
See logs in GetStream Board: http: no such file. status 400

### Expected behavior

send the audio record

### Customization
no

### Offline support

- [ ] I have enabled offline support.
- [ ] The feature I'm having does not occur when offline support is disabled. (stripe out if not applicable)

#### `package.json`:

```json
# N/A
```

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
    - [ ] iOS
    - [X] Android
    - [ ] **iOS** but have not tested behavior on Android
    - [ ] **Android** but have not tested behavior on iOS
    - [ ] Both
- **`stream-chat-react-native` version you're using that has this issue:**
    - `e.g. 5.4.3`
- Device/Emulator info:
  - [ ] I am using a physical device
  - OS version: `e.g. Android 10`
  - Device/Emulator: `e.g. iPhone 11`

</p>
</details>

### Screenshots

<details><summary>Click To Expand</summary>
<p>

</p>
</details>

---

**Comment by netoya** [comment]
#2512 fix

**Comment by khushal87** [comment]
Fixed in #2312. Thanks @netoya. 😄
