### ISSUE TITLE
[🐛] App crash on open chat screen

### ISSUE THREAD

**Issue by krushita042023** [GetStream/stream-chat-react-native#2520]
## Issue

When i open group chat the screen goes blank or crash.

### Steps to reproduce

1. Go to channel list screen
2. Click on group channel
3. See error

## Project Related Information
"react-native": "0.72.5",
 "stream-chat": "^8.14.3",
 "stream-chat-react-native": "^5.24.0",

- **Platform that you're experiencing the issue on**:
    - [ ] iOS
    - [ ] Android
    - [ ] **iOS** but have not tested behavior on Android
    - [ ] **Android** but have not tested behavior on iOS
    - [X] Both
</p>
</details>

### Screenshots

<details><summary>Click To Expand</summary>
<p>

> https://we.tl/t-QOrSERP0aq

![Screenshot_1716354443](https://github.com/GetStream/stream-chat-react-native/assets/129855948/236f89f8-f4b3-41f3-b902-541c526a8b9e)
</p>
</details>

---

**Comment by khushal87** [comment]
Copy of #2499. This will be fixed in the upcoming release. Thanks 😄
