### ISSUE TITLE
How to check for blocked word?

### ISSUE THREAD

**Issue by billnbell3** [GetStream/stream-chat-react-native#2524]
We have a list of blocked words defined...

We are using React Native. How do we see the block? The front-end is not showing the ! when a message hits a blocked word.

How to handle.

**Comment by khushal87** [comment]
Hey @billnbell3, do you use moderation to block words in the channel?

**Comment by khushal87** [comment]
We will be closing this issue due to the lack of description. If it's a general question, please reach out through the [support URL](https://getstream.io/contact/support/) and our support team will be happy to address your questions.
