### ISSUE TITLE
[🐛] userTokenOrProvider is being called when offline enabled

### ISSUE THREAD

**Issue by vitorcamachoo** [GetStream/stream-chat-react-native#2535]
## Issue
By enabling the stream chat to work offline, the `userTokenOrProvider` when passed as a function that makes a request to get the token, the request is being made which will result in a 401 error. The expected behaviour was that the method could be bypassed when offline because in my opinion, since we are offline, we don't have any way to confirm the identity.

Describe your issue here

### Steps to reproduce
Steps to reproduce the behaviour:
```tsx
const userTokenOrProvider = async () => {
  const response = await request(...);
  return response.token;
};
await chatClient.connectUser({ id: userId }, userTokenOrProvider);
```

### Expected behaviour
When offline, the method that is responsible for getting the token should not be executed.

### Customization

<details><summary>Click To Expand</summary>
<p>

```typescript jsx
# N/A
```
</p>
</details>

### Offline support

- [X] I have enabled offline support.
- [X] The feature I'm having does not occur when offline support is disabled. (stripe out if not applicable)

## Environment

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
"expo": "~50.0.17",
    "expo-av": "~13.10.6",
    "expo-build-properties": "~0.11.1",
    "expo-clipboard": "~5.0.1",
    "expo-constants": "~15.4.6",
    "expo-dev-client": "~3.3.11",
    "expo-document-picker": "~11.10.1",
    "expo-file-system": "16.0.9",
    "expo-image-manipulator": "11.8.0",
    "expo-image-picker": "14.7.1",
    "expo-linking": "~6.2.2",
    "expo-media-library": "15.9.2",
    "expo-router": "^3.4.10",
    "expo-secure-store": "~12.8.1",
    "expo-sharing": "~11.10.0",
    "expo-splash-screen": "~0.26.5",
    "expo-status-bar": "~1.11.1",
    "expo-system-ui": "~2.9.4",
    "expo-updates": "~0.24.12",
"stream-chat-expo": "5.28.1",
 "react-native": "0.73.6",
    "react-native-compressor": "^1.8.24",
    "react-native-fast-image": "^8.6.3",
    "react-native-gesture-handler": "2.14.1",
    "react-native-qrcode-svg": "^6.3.0",
    "react-native-quick-sqlite": "^8.1.0",
    "react-native-reanimated": "3.6.3",
    "react-native-root-toast": "3.5.1",
    "react-native-safe-area-context": "4.8.2",
    "react-native-screens": "~3.29.0",
    "react-native-svg": "14.1.0",
    "react-native-uuid": "2.0.2",

```

**`react-native info` output:**

```
System:
  OS: macOS 14.4.1
  CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
  Memory: 1.14 GB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.12.2
    path: ~/.nvm/versions/node/v20.12.2/bin/node
  Yarn: Not Found
  npm:
    version: 10.5.0
    path: ~/.nvm/versions/node/v20.12.2/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/vitorcamacho/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK:
    Android NDK: 22.1.7171670
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11330709
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 3.1.1
    path: /Users/vitorcamacho/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.6
    wanted: 0.73.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

- **Platform that you're experiencing the issue on**:
    - [ ] iOS
    - [ ] Android
    - [ ] **iOS** but have not tested behavior on Android
    - [ ] **Android** but have not tested behavior on iOS
    - [X] Both
- **`stream-chat-react-native` version you're using that has this issue:**
    - `e.g. 5.4.3`
- Device/Emulator info:
  - [ ] I am using a physical device
  - OS version: `e.g. Android 10`
  - Device/Emulator: `e.g. iPhone 11`

</p>
</details>

### Screenshots

<details><summary>Click To Expand</summary>
<p>

</p>
</details>

---

**Comment by khushal87** [comment]
Hey @vitorcamachoo, I think this is something app specific and can be done easily at your end if you can track if the internet is off or on and call it as you would like. Its not coming that SDK can support since the `connectUser` is not done on the SDK side.
