### ISSUE TITLE
[🐛] Bug Report Title - Facing issue as Error: Cannot find native module 'ExpoMediaLibrary', js engine: hermes in Expo 50, using @react-navigation/stack

### ISSUE THREAD

**Issue by Raghu-M-S** [GetStream/stream-chat-react-native#2536]
## Issue

Hi i'm using expo 50.0.19, in which i need to integrate Video Stream and one on one chat system, So i'm trying to wrap my Stack within <OverlayProvider /> which i'm importing from "stream-chat-expo"

`import React, { useContext, useEffect, useState } from "react";
import { createStackNavigator } from "@react-navigation/stack";
import { SafeAreaView } from "react-native-safe-area-context";
import { Stack, YStack } from "tamagui";
import {
  StreamVideo,
  StreamVideoClient,
  User,
} from "@stream-io/video-react-native-sdk";
import CardSkeleton from "@components/skeleton/CardSkeleton";
import RoundedSkeleton from "@components/skeleton/RoundedSkeleton";
import BottomNavigation from "./BottomNavigation";
import { ApiContext } from "context/ApiContext";
import VideoCall from "@screens/VideoStream/VideoCall";
import { useQuery } from "react-query";
import { stream_key } from "@utils/globalConstants";
import { StreamChat } from "stream-chat";
import ChatSystem from "@screens/ChatSystem";
import { Chat, OverlayProvider } from "stream-chat-expo";
import { GestureHandlerRootView } from "react-native-gesture-handler";

const UserStack = createStackNavigator();

const AppStack = () => {
  const apiContext = useContext(ApiContext);
  if (!apiContext) {
    throw new Error("ApiContext is not available");
  }
  const { client, userData, setUserData } = apiContext;
  const chatClient = StreamChat.getInstance(stream_key);
  const [isLoading, setIsLoading] = useState(true);
  const [initialRouteName, setInitialRouteName] = useState("BottomNavigation");
  const [status, setStatus] = useState(null);
  const [clientStream, setClient] = useState<StreamVideoClient | null>(null);

  const fetchGetStreamToken = async () => {
    const response = await client.get(`telehealth/session/token`);
    return response.data.result;
  };

  const { data } = useQuery("fetchGetStreamToken", fetchGetStreamToken, {
    refetchOnMount: true,
  });

  useEffect(() => {
    const user: User = { id: String(userData?.user?.id ?? "") };

    const initializeClient = async () => {
      if (!data?.sessionToken) {
        console.log("Session token is not available.");
        return;
      }
      try {
        const client = new StreamVideoClient({
          apiKey: stream_key,
          user,
          token: data.sessionToken,
        });
        setClient(client);
        if (userData?.streamToken !== data.sessionToken) {
          setUserData({
            ...userData,
            streamToken: data.sessionToken,
          });
        }
      } catch (e) {
        console.log("Error creating client:", e);
      }
    };

    if (client && data) {
      initializeClient();
    }

    return () => {
      if (clientStream) {
        clientStream?.disconnectUser();
      }
    };
  }, [client, data]); // React to changes in client or data

  return (
    <UserStack.Navigator initialRouteName={initialRouteName}>
      <UserStack.Screen
        name="BottomNavigation"
        component={BottomNavigation}
        options={{ headerShown: false }}
        initialParams={{ status: status }}
      />
      {clientStream && (
        <UserStack.Screen name="VideoCall" options={{ headerShown: false }}>
          {(props) => (
            <StreamVideo client={clientStream}>
              <VideoCall {...props} />
            </StreamVideo>
          )}
        </UserStack.Screen>
      )}

      {chatClient && (
        <UserStack.Screen name="ChatSystem" options={{ headerShown: false }}>
          {(props) => (
            <OverlayProvider>
              <Chat client={chatClient}>
                <ChatSystem />
              </Chat>
            </OverlayProvider>
          )}
        </UserStack.Screen>
      )}
    </UserStack.Navigator>
  );
};

export default AppStack;
`
I Configured my "expo-media-library", in app.json and installed still facing issue

![Screenshot 2024-06-01 063740](https://github.com/GetStream/stream-chat-react-native/assets/68733675/50130b40-34e4-4286-b373-24b21cb7f94b)

Describe your issue here

### Steps to reproduce

   etc...

### Customization

<details><summary>Click To Expand</summary>
<p>

```typescript jsx
# N/A
```
</p>
</details>

### Offline support

- [ ] I have enabled offline support.
- [ ] The feature I'm having does not occur when offline support is disabled. (stripe out if not applicable)

## Environment

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
    - [ ] iOS
    - [ ] Android
    - [ ] **iOS** but have not tested behavior on Android
    - [ ] **Android** but have not tested behavior on iOS
    - [ ] Both
- **`stream-chat-react-native` version you're using that has this issue:**
    - `e.g. 5.4.3`
- Device/Emulator info:
  - [ ] I am using a physical device
  - OS version: `e.g. Android 10`
  - Device/Emulator: `e.g. iPhone 11`

</p>
</details>

### Screenshots

<details><summary>Click To Expand</summary>
<p>

</p>
</details>

---

**Comment by radelcom** [comment]
in the same boat. added plugins in app.json but still experiencing this issues as well.

**Comment by khushal87** [comment]
Hey @radelcom, do you also have our video SDK installed?

**Comment by radelcom** [comment]
@khushal87 no, just the stream chat dependencies

**Comment by khushal87** [comment]
We don't see any issues with our SDK on Expo 50. It seems you don't have the dependencies installed, or your native folders are not in sync with lib. Please try to clear the cache and run the app again. Do you use Expo Go, or do you have a development build?

**Comment by khushal87** [comment]
Is it still an issue, or can we close it?

**Comment by Raghu-M-S** [comment]
Issue resolved
