### ISSUE TITLE
[🐛] Unable to resolve optional module

### ISSUE THREAD

**Issue by mishkeTz** [GetStream/stream-chat-react-native#2542]
## Issue

I recently upgraded react-native version and I am getting an error when I try to run the iOS project with following error:

```
error: Error: Unable to resolve module react-native-quick-sqlite from /Users/user/user/testproject/app/node_modules/stream-chat-react-native/node_modules/stream-chat-react-native-core/lib/commonjs/store/QuickSqliteClient.js: react-native-quick-sqlite could not be found within the project or in these directories:
  node_modules/stream-chat-react-native/node_modules
  node_modules
  ../node_modules
  12 | var sqlite;
  13 | try {
> 14 |   sqlite = require('react-native-quick-sqlite').QuickSQLite;
     |                     ^
  15 | } catch (e) {
  16 |   var isRemoteDebuggerError = e instanceof Error && e.message.includes('Failed to install');
  17 |   if (isRemoteDebuggerError) {
    at ModuleResolver.resolveDependency (/Users/user/user/testproject/app/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:138:15)
    at DependencyGraph.resolveDependency (/Users/user/user/testproject/app/node_modules/metro/src/node-haste/DependencyGraph.js:231:43)
    at /Users/user/user/testproject/app/node_modules/metro/src/lib/transformHelpers.js:156:21
    at resolveDependencies (/Users/user/user/testproject/app/node_modules/metro/src/DeltaBundler/buildSubgraph.js:42:25)
    at visit (/Users/user/user/testproject/app/node_modules/metro/src/DeltaBundler/buildSubgraph.js:83:30)
    at async Promise.all (index 3)
    at async visit (/Users/user/user/testproject/app/node_modules/metro/src/DeltaBundler/buildSubgraph.js:92:5)
    at async Promise.all (index 1)
    at async visit (/Users/user/user/testproject/app/node_modules/metro/src/DeltaBundler/buildSubgraph.js:92:5)
    at async Promise.all (index 15)
```

### Expected behavior

I can run the mobile-app without optional dependencies installed.

### Offline support

Don't have offline support enabled.

## Environment

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
"stream-chat-react-native": "^5.31.1",
"react-native": "0.73.8",
"react": "18.2.0",
"typescript": "5.0.4"
```

- **Platform that you're experiencing the issue on**:
    - [x] iOS
    - [ ] Android
    - [ ] **iOS** but have not tested behavior on Android
    - [ ] **Android** but have not tested behavior on iOS
    - [ ] Both
- **`stream-chat-react-native` version you're using that has this issue:**
    - `^5.31.1`
- Device/Emulator info:
  - [ ] I am using a physical device
  - OS version: `iOS 17.0.1` - not tested with older versions but I assume it might be the same behavior
  - Device/Emulator: `iPhone 15 Pro`

</p>
</details>

### Screenshots

<details><summary>Click To Expand</summary>
<p>

</p>
</details>

---

**Comment by khushal87** [comment]
Do you have `enableOfflineSupport` prop as `true` in the `Chat` component?

**Comment by mishkeTz** [comment]
No, I don't pass that prop anywhere. The code hasn't been changed. I used RN 0.67.5 and updated RN to 0.73.8 as well as other dependencies required by RN. I am wondering if it could be something specific to metro configuration?

```
const { getDefaultConfig, mergeConfig } = require('@react-native/metro-config');

/**
 * Metro configuration
 * https://facebook.github.io/metro/docs/configuration
 *
 * @type {import('metro-config').MetroConfig}
 */

const config = {
  resolver: {
    sourceExts: ['js', 'jsx', 'ts', 'tsx', 'json'],
  },
};

module.exports = mergeConfig(getDefaultConfig(__dirname), config);

```

**Comment by khushal87** [comment]
Seems that your metro config might have broken in that case. There were a lot of changes in the metro config in version [0.73](https://reactnative.dev/blog/2023/12/06/0.73-debugging-improvements-stable-symlinks#stable-symlink-support-in-metro) of RN which has to be assessed and corrected in your app. Do you have a mono repo? If yes, you can follow our metro config as well in the example apps.

**Comment by mishkeTz** [comment]
It's not a monorepo project. Is there any specific metro configuration required for just regular app project structure? This can be marked as resolved - the solution was to just install optional dependencies.

**Comment by khushal87** [comment]
So, it works for you now @mishkeTz?

**Comment by mishkeTz** [comment]
It works after installing optional dependencies - yes (https://getstream.io/chat/docs/sdk/reactnative/basics/installation/).
