### ISSUE TITLE
Error on using UI components: "new NativeEventEmitter() requires a non-null argument.

### ISSUE THREAD

**Issue by mpinchover** [GetStream/stream-chat-react-native#2545]
## Issue

When using Stream UI components in a new Expo project, an uncaught error appears: 
```
Invariant Violation: `new NativeEventEmitter()` requires a non-null argument., js engine: hermes
```

I was unable to find any support online for how to get rid of this error.

Code for project:
````
import { SafeAreaView, Text } from "react-native";
import { StreamChat } from "stream-chat";
import { OverlayProvider } from "stream-chat-react-native";

const client = StreamChat.getInstance("my-api-key");

export default function HomeScreen() {
  return (
    <SafeAreaView>
      <OverlayProvider>
        <Text>Hello</Text>
      </OverlayProvider>
    </SafeAreaView>
  );
}

````
Dependencies
````
 "stream-chat": "^8.35.0",
 "stream-chat-react-native": "^5.31.1"
````

Describe your issue here

### Steps to reproduce

Expo has a new flow now where you can choose to create an Expo Go project or an Expo Development project. Expo Go is not meant for production builds, but more to quickly test out how Expo is used.

Make sure to choose iOS simulator, development build [here](https://docs.expo.dev/get-started/create-a-project/) and uncheck `Build with Expo Application Services (EAS)`.

Run app `npm run start`

### Expected behavior
App should be able to compile and open.

### Customization

<details><summary>Click To Expand</summary>
<p>

```typescript jsx
# N/A
```
</p>
</details>

### Offline support

- [ ] I have enabled offline support.
- [ ] The feature I'm having does not occur when offline support is disabled. (stripe out if not applicable)

## Environment
Running node v20.13.1
<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
    - [x] iOS
    - [ ] Android
    - [ ] **iOS** but have not tested behavior on Android
    - [ ] **Android** but have not tested behavior on iOS
    - [ ] Both
- **`stream-chat-react-native` version you're using that has this issue:**
    - `e.g. 5.4.3`
- Device/Emulator info:
  - [ ] I am using a physical device
  - OS version: `e.g. Android 10`
  - Device/Emulator: `e.g. iPhone 11`

</p>
</details>

### Screenshots
<img width="335" alt="Screenshot 2024-06-09 at 6 29 06 PM" src="https://github.com/GetStream/stream-chat-react-native/assets/28989086/c9819d3b-d5af-4294-8e35-efdee9dcb14d">

---

**Comment by khushal87** [comment]
Hey @mpinchover, if you are using expo to build your project, why are you using `stream-chat-react-native`? Instead you should use `stream-chat-expo`.

**Comment by khushal87** [comment]
Closing this issue in favour of not being able to reproduce it. Please reopen it if you still find it relevant. For expo please follow the [installation guide](https://getstream.io/chat/docs/sdk/reactnative/basics/installation/).
