### ISSUE TITLE
[🐛] Cannot use stream client in Expo

### ISSUE THREAD

**Issue by oddanderson** [GetStream/stream-chat-react-native#2562]
## Issue

I am using stream-chat with expo, following the installation instructions. 

If I do not explicitly install stream-chat, I am unable to access the chat client to import. If I do explicitly install stream-chat separately, which the docs say not to, I get a lot of type errors and collisions.

### Steps to reproduce

1. Create an expo project
2. Install stream chat via `npx expo install stream-chat-expo`
3. Try to import stream client via `import { StreamChat} from 'stream-chat';
4. See import error

### Expected behavior

I expect to be able to follow the docs for using Expo and connect a React Native app to the stream client, so that I can call required functions such as `StreamChat.getInstance` and `StreamChat.connectUser`

### Customization

<details><summary>Click To Expand</summary>
<p>

```typescript jsx
# N/A
```
</p>
</details>

### Offline support

- [ ] I have enabled offline support.
- [ ] The feature I'm having does not occur when offline support is disabled. (stripe out if not applicable)

## Environment

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
"stream-chat-expo": "^5.32.1",
```

**`react-native info` output:**

```
 N/A - using Expo 51.0.11
```

- **Platform that you're experiencing the issue on**:
    - [ ] iOS
    - [ ] Android
    - [ ] **iOS** but have not tested behavior on Android
    - [ ] **Android** but have not tested behavior on iOS
    - [X ] Both
- **`stream-chat-react-native` version you're using that has this issue:**
    - `e.g. 5.4.3`
- Device/Emulator info:
  - [ ] I am using a physical device
  - OS version: `e.g. Android 10`
  - Device/Emulator: `e.g. iPhone 11`

</p>
</details>

### Screenshots

<details><summary>Click To Expand</summary>
<p>

</p>
</details>

---

**Comment by khushal87** [comment]
Hey @oddanderson, I tried the same and couldn't reproduce the issue. Please try clearing your metro cache and do a fresh install and that should work fine. Thanks 😄

**Comment by nemrosim** [comment]
@khushal87 Thank you. But by "solving" **this** issue new one appeared:  

When user press on the "thread" and there are >1 messages -> those will be hidden. 
Solution if to make changes in the `stream-chat-react-native-core/src/components/MessageList/MessageList.tsx` component
```diff
- maintainVisibleContentPosition={maintainVisibleContentPosition}
+ maintainVisibleContentPosition={Platform.OS === 'ios' ? undefined: maintainVisibleContentPosition}
```

**NOTE**: Sometimes threads will show messages from the previously opened thread to. Check video from the `examples/ExpoMessaging` project:

https://github.com/user-attachments/assets/1744ee39-4754-4996-a5cb-5cf9eb8784ff
