### ISSUE TITLE
[🐛] 🔥 Photos taken by camera are not loading on Android

### ISSUE THREAD

**Issue by arekkubaczkowski** [GetStream/stream-chat-react-native#2570]
## Issue

On android after taking a photo from camera it shows on the list right above the chat input but they are not loaded properly. Initially I thought it's related to loosing connection when the app goes to the background due to navigating to image picker but I tried to set `closeConnectionOnBackground=false` and it didn't help.

I added a console log of image response from uploadImage method in MessageInputContext.tsx that you can see on the video.

### Offline support

- [ ] I have enabled offline support.
- [ ] The feature I'm having does not occur when offline support is disabled. (stripe out if not applicable)

## Environment

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

    "stream-chat": "8.31.0",
    "stream-chat-expo": "^5.31.1",

```json
# N/A
```

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
    - [ ] iOS
    - [x] Android
    - [ ] **iOS** but have not tested behavior on Android
    - [ ] **Android** but have not tested behavior on iOS
    - [ ] Both
- **`stream-chat-react-native` version you're using that has this issue:**
    - `e.g. 5.4.3`
- Device/Emulator info:
  - [ ] I am using a physical device
  - OS version: 12
  - Emulator: Pixel 3a API 32 arm64

</p>
</details>

https://github.com/GetStream/stream-chat-react-native/assets/18654447/4ff70df9-6439-4026-b995-65906f5e5f8b

---

**Comment by khushal87** [comment]
Hey @arekkubaczkowski, this has been fixed in #2559 and will be released in the next release(coming soon). I will be closing this issue until then.
