### ISSUE TITLE
[🐛] missing flagMessage method in MessageActionHandlers provided to onLongPressMessage

### ISSUE THREAD

**Issue by arekkubaczkowski** [GetStream/stream-chat-react-native#2572]
## Issue

It seems like `MessageActionHandlers` interface has missing certain message actions like `flagMessage`. I need to have an access to that method from onLongPressMessage callback but for some reason it is not included.

<img width="486" alt="Screenshot 2024-06-27 at 08 59 01" src="https://github.com/GetStream/stream-chat-react-native/assets/18654447/c0f60725-0e97-4198-9b5c-04f38f586c73">

```tsx
<Channel
    onLongPressMessage={({ message, actionHandlers }) => {
      actionHandlers.flagMessage()  // <-- not available
    }}
>
      {children}
</Channel>
```

**Comment by khushal87** [comment]
Hey @arekkubaczkowski, I don't think you have added the capability to flag a message for your channel, which is why you might not be able to see it. Please add it through the dashboard and you should be able to see it. Also, note that the flag message action is only visible for messages that are received by other users. 

You can check the flagged messages here - /app/`your app id`/moderation/messages?tab=flagged
You can edit permissions here - /app/`your app id`/chat/rolespermissions
On https://dashboard.getstream.io/

Please reach out through https://getstream.io/contact/support/ if you still were not able to do it and someone from the customer support team may guide you through it. 😄

**Comment by arekkubaczkowski** [comment]
@khushal87 how is it possible taking into account that interface is hardcoded?
https://github.com/GetStream/stream-chat-react-native/blob/5327cdebc58961155246a832b7c97b5dc56f1b4c/package/src/components/Message/Message.tsx#L115

**Comment by khushal87** [comment]
Hey @arekkubaczkowski, can you try to describe the issue briefly? Sorry, but I am not able to understand what exactly are you trying to achieve?

**Comment by arekkubaczkowski** [comment]
@khushal87 not sure how can I explain it better, I am just trying to access to the `flagMesage` action from onLongPressMessage callback which provides an `actionHandlers` prop that should contain that action, but it's not for some reason.

This code snippet specifically illustrates the issue:

```tsx
<Channel
    onLongPressMessage={({ message, actionHandlers }) => {
      actionHandlers.flagMessage()  // <-- not available
    }}
>
      {children}
</Channel>
```

`actonHandlers.flagMessage()` method does not exist on that interface.

**Comment by arekkubaczkowski** [comment]
please note that this callback is available in messageActions prop:

```<Channel
    messageActions={({flagMessage}) => [flagMessage]} // <-- it is there, but I need a reference to that action from onLongPressMessage. actionHandlers as well
>
      {children}
</Channel>
```

**Comment by khushal87** [comment]
So, by the same definition, you might be facing the same issue with `copyMessage`, right?

**Comment by arekkubaczkowski** [comment]
that's right, copyMessage is also missing as well as few others I guess. I believe the interface of actionHandlers should contain all of the actions:
``` 
  blockUser,
  copyMessage,
  deleteMessage,
  editMessage,
  flagMessage,
  pinMessage,
  quotedReply,
  retry,
  threadReply,
  unpinMessage
```

**Comment by khushal87** [comment]
For few of them, the names are different:

`blockUser` -> `toggleBanUser`
`retry` -> `resendMessage`

**Comment by khushal87** [comment]
Rest all are added in #2573

**Comment by arekkubaczkowski** [comment]
@khushal87 is there any way to access message actions imperatively?
I would like to create my own long press behaviour which would not be tightly coupled with `onLongPressMessage` prop from `GetStreamChannel` but this seems to be the only way to access that actions.

I noticed that you have the `useMessageActionHandlers` hook but it expects to provide some props that I would like to avoid providing on my own.

**Comment by khushal87** [comment]
Hey @arekkubaczkowski, the `action` prop here in the MessageActionListItem can help you with the same if you are planning to use the default action somewhere in the message action itself - https://getstream.io/chat/docs/sdk/reactnative/guides/customize-message-actions/#how-to-disable-a-message-action

**Comment by arekkubaczkowski** [comment]
@khushal87 unfortunately I don't want to use MessageActionListItem component, I have a completely custom UI and it is not coupled with action list.

**Comment by khushal87** [comment]
So, does that trigger on long press of the message?

**Comment by arekkubaczkowski** [comment]
@khushal87 sorry for late reply. No, that's the point. I would like to have a possibility for instance trigger a `quotedReply` action from outside the chat. I have some messages references out of the MessageList that I would like to couple with that list.

**Comment by khushal87** [comment]
Hey @arekkubaczkowski, we will take it as feedback and try to work on this in the future. Currently, there's no easier way than using the `messageActions` or the already available hooks like `useMessageActionsHandler`/`useMessageActions`.

**Comment by arekkubaczkowski** [comment]
thanks. I believe that above mentioned hooks are not prepared to be used externally, useMessageActionsHandler is not exported at all while useMessageActions expects a lot of things to be provided

**Comment by arekkubaczkowski** [comment]
I would be grateful for any improvement on that since we are kinda blocked with a lot of featured that we were going to implement since we cannot interact with the message list from outside.
