### ISSUE TITLE
[🐛] Push Notification on iOS not working

### ISSUE THREAD

**Issue by Harsh2110mishra** [GetStream/stream-chat-react-native#2584]
## Issue

Not receiving push notifications from stream chat on iOS device. 

Already completed the setup of push notifications with firebase for iOS devices and also, received test notifications from the Firebase console to iOS devices but stream notifications are not being sent. Stream chat notifications working on android but not on iOS.

### Expected behavior

After adding configurations of push on stream dashboard it should send notification to iOS devices.

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M3
    Memory: 51.25 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.20.3 - /opt/homebrew/opt/node@18/bin/node
    Yarn: Not Found
    npm: 10.7.0 - /opt/homebrew/opt/node@18/bin/npm
    Watchman: 2024.06.24.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2024.1 AI-241.15989.150.2411.11948838
    Xcode: 15.4/15F31d - /usr/bin/xcodebuild
  Languages:
    Java: 22.0.1 - /opt/homebrew/opt/openjdk/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.4 => 0.70.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
    - [x] iOS
    - [ ] Android
    - [ ] **iOS** but have not tested behavior on Android
    - [ ] **Android** but have not tested behavior on iOS
    - [ ] Both
- **`stream-chat-react-native` version you're using that has this issue: ^5.24.0**
    - `e.g. 5.4.3`
- Device/Emulator info:
  - [x] I am using a physical device
  - OS version: `e.g. Android 10`
  - Device/Emulator: `e.g. iPhone 15`

</p>
</details>

### Screenshots

<details><summary>APN Template added on stream push configs</summary>
<p>

```
{
	"aps": {
		"alert": {
			"title": "New message from {{ sender.name }}",
			"body": "{{ truncate message.text 2000 }}"
		},
		"mutable-content": 1,
		"category": "stream.chat"
	},
	"stream": {
      "sender": "stream.chat",
      "type": "message.new",
      "version": "v2",
      "id": "{{ message.id }}",
      "cid": "{{ channel.cid }}"
	}
}
```

</p>
</details>

---

**Comment by khushal87** [comment]
Hey @Harsh2110mishra, this doesn't look like a bug but something our support team can assist you with. Can you please raise a ticket on our support so that someone can assist you with the same.

Support URL - https://getstream.io/contact/support/

I will be closing this issue from here. Thanks 😄
