### ISSUE TITLE
Feature request: open a thread by id.

### ISSUE THREAD

**Issue by MatheoJaouen** [GetStream/stream-chat-react-native#2588]
**Motivation**

Possibility to open/get a thread by id (or by parent message id) that we can pass to the `thread` property of the `Channel` component.
In order to open a thread in an independent screen or from a (push) notification or from anywhere else.

The `thread` property of the Channel component takes a `MessageType` declared by the react-native api.
While the api provide a different object Type for the `getMessage` or `client.getThread` (a MessageResponse if I recall correctly).
https://getstream.io/chat/docs/react-native/threads/?language=javascript#g﻿et-thread-by-id
https://github.com/GetStream/stream-chat-react-native/blob/ea688c3096b368fb245b0d28671791b5c66b248e/package/src/contexts/threadContext/ThreadContext.tsx#L21

The channel property on his side matches the api type so we can fetch it independently unlike the thread prop.

The only way to open a thread currently seems to be via the `onThreadSelect` prop of the `MessageList`.

**Proposed solution**

**Acceptance Criteria**
Open a thread from id (or parent message id).

As code example, I can get the channel but I'm not able to open the thread without passing the entire object obtained by a previous
```
export const ThreadViewerScreen: React.FC<NativeStackScreenProps<AppStackParamList, ScreenName.Thread>> = (props) => {
    const { params } = props.route;
    
    const { thread } = params; // I would need to pass only the id of the thread/message & fetch it/get it another way, in order for instance to open a thread from notification

    const { channel } = useChatStoreValues(); // channel is a Channel from stream-chat which is ok, I can get it by id from the api
    
  

	
    if (!channel) {
        return null;
    }

    return (
        <SafeAreaView>
            <ChatLoadingAndErrorView>
                <Channel
                    Input={CustomMessageInput}
                    channel={channel}
                    thread={thread}
                    allowThreadMessagesInChannel
                    threadList
                >
                    <Thread />
                </Channel>
            </ChatLoadingAndErrorView>
        </SafeAreaView>
    );
};
```

**Comment by khushal87** [comment]
Copy of #2579
