### ISSUE TITLE
JWTAuth error: signature is not valid.

### ISSUE THREAD

**Issue by Ravinder-webonise** [GetStream/stream-chat-react-native#2602]
Hi team ,
When ever i tried to connect my user to the chat with  GetStreamToken which is provided by BackEnd , i am facing issue with the request.

message: \"JWTAuth error: signature is not valid. Make sure the token is created using the secret for API key \"fu6dye6sz9zr\"\", statusCode: 401)).")

Please help me here.. i have cross check my GET_STREAM_TOKEN value from Console. Still getting issue.
Help me here

**Comment by khushal87** [comment]
Hey @Ravinder-webonise, can you verify if you are using the correct secret and API key from the dashboard for your app? If yes, this shouldn't be a problem at all. Regardless if you still face any issues please reach out to us through https://getstream.io/contact/support/ and someone from the support team will assist you.

I will close this issue as it doesn't seem to be React Native SDK related. Thanks 😄

**Comment by tispratik** [comment]
Isn't it leaking an important secret in that log message? `fu6dye6sz9zr` ?

**Comment by ahmed-moha** [comment]
> Hi team , When ever i tried to connect my user to the chat with GetStreamToken which is provided by BackEnd , i am facing issue with the request.
> 
> message: "JWTAuth error: signature is not valid. Make sure the token is created using the secret for API key "fu6dye6sz9zr"", statusCode: 401)).")
> 
> Please help me here.. i have cross check my GET_STREAM_TOKEN value from Console. Still getting issue. Help me here

i got the same issue previous api credentails was working fine new ones i got this issue
