### ISSUE TITLE
🔥[🐛] Doubt about GestureHandlerRootView wrapping

### ISSUE THREAD

**Issue by quememo** [GetStream/stream-chat-react-native#2610]
## Issue

I had been using `stream-chat-expo` `5.17.1` for quite some time. Recently, I updated my Expo project from v49 to v50 and run into some issues regarding the Chat. Specifically, I updated to stream-chat-expo: `5.27.0` and encountered the error "PanGestureHandler must be used as a descendant of GestureHandlerRootView". 

After some research, it seems to be triggered by the use of `react-native-gesture-handler` as part of the `@gorhom/bottom-sheet` library that you use as a dependency. I was able to fix it by wrapping my entire app in `GestureHandlerRootView` as indicated in the [documentation](https://getstream.io/chat/docs/sdk/reactnative/basics/installation/). However, this caught my attention. Previously, I did not have the app wrapped in this component, and the chat worked perfectly, so I would think that this is something recently added for new versions. However, I do not understand the reason why this need arose, given that it seems the Chat did not require it some time ago. With that in mind, could you provide an explanation of why this is the case? One thing I think is that it is the Stream library that should be responsible for wrapping its components in GestureHandlerRootView and not delegate the responsibility to me. I imagine there must be technical reasons behind this that I would like to understand more deeply. I attached some images in the respective section of the issue. Thank you very much in advance for your time and attention. 

### Steps to reproduce

0. Update Expo v49 to v50
1. Update `stream-chat-expo` from `5.17.1` to `5.27.0` 
2. Try to use `OverlayProvider` and `ChatList` from `stream-chat-expo`

### Expected behavior

The chat list should work. Instead, I get an error.

### Customization

<details><summary>Click To Expand</summary>
<p>

```typescript jsx
# N/A
```
</p>
</details>

### Offline support

- [ ] I have enabled offline support.
- [ ] The feature I'm having does not occur when offline support is disabled. (stripe out if not applicable)

## Environment

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
...
  "dependencies": {
    "@clerk/clerk-expo": "^0.19.14",
    "@eva-design/eva": "^2.2.0",
    "@expo/config-plugins": "^7.8.0",
    "@expo/vector-icons": "^14.0.0",
    "@fawazahmed/react-native-read-more": "^3.0.4",
    "@logrocket/react-native": "^1.32.0",
    "@react-native-community/netinfo": "11.1.0",
    "@react-native-picker/picker": "2.6.1",
    "@react-navigation/native": "^6.0.2",
    "@react-navigation/native-stack": "^6.10.0",
    "@sentry/react-native": "~5.20.0",
    "@shopify/restyle": "^2.4.4",
    "@tanstack/react-query": "^4.35.3",
    "@types/base-64": "^1.0.0",
    "@types/js-quantities": "^1.6.6",
    "@types/react-native-dotenv": "^0.2.2",
    "@ui-kitten/components": "^5.3.1",
    "@ui-kitten/eva-icons": "^5.3.1",
    "@ui-kitten/moment": "^5.3.1",
    "base-64": "^1.0.0",
    "d3": "^7.8.5",
    "dayjs": "^1.11.10",
    "expo": "^50.0.19",
    "expo-application": "~5.8.4",
    "expo-build-properties": "~0.11.1",
    "expo-clipboard": "~5.0.1",
    "expo-constants": "~15.4.6",
    "expo-crypto": "~12.8.1",
    "expo-dev-client": "~3.3.12",
    "expo-device": "~5.9.4",
    "expo-file-system": "~16.0.9",
    "expo-font": "~11.10.3",
    "expo-image-manipulator": "~11.8.0",
    "expo-image-picker": "~14.7.1",
    "expo-linear-gradient": "~12.7.2",
    "expo-linking": "~6.2.2",
    "expo-media-library": "~15.9.2",
    "expo-module-scripts": "^3.1.0",
    "expo-router": "~3.4.10",
    "expo-secure-store": "~12.8.1",
    "expo-splash-screen": "~0.26.5",
    "expo-status-bar": "~1.11.1",
    "expo-system-ui": "~2.9.4",
    "expo-updates": "~0.24.13",
    "expo-web-browser": "~12.8.2",
    "formik": "^2.4.2",
    "getstream": "^8.3.1",
    "globals": "^15.8.0",
    "js-quantities": "^1.8.0",
    "js-tokens": "^8.0.2",
    "ky": "^1.3.0",
    "patch-package": "^8.0.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.73.6",
    "react-native-actions-sheet": "^0.9.2",
    "react-native-chart-kit": "^6.12.0",
    "react-native-date-picker": "^4.4.2",
    "react-native-dotenv": "^3.4.9",
    "react-native-error-boundary": "^1.2.3",
    "react-native-gesture-handler": "~2.14.0",
    "react-native-gifted-charts": "^1.4.26",
    "react-native-linear-gradient": "^2.8.3",
    "react-native-localize": "^3.2.0",
    "react-native-qrcode-svg": "^6.3.1",
    "react-native-reanimated": "~3.6.2",
    "react-native-safe-area-context": "4.8.2",
    "react-native-screens": "~3.29.0",
    "react-native-svg": "14.1.0",
    "react-native-toast-message": "^2.2.0",
    "react-native-user-avatar": "^1.0.8",
    "react-native-web": "~0.19.6",
    "react-native-webview": "13.6.4",
    "rn-faded-scrollview": "^1.0.13",
    "sentry-expo": "~7.2.0",
    "stream-chat-expo": "5.27.0",
    "terra-react": "^1.6.15",
    "yup": "^1.2.0",
    "zustand": "^4.5.4"
  },
...
}

```

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
    - [ ] iOS
    - [ ] Android
    - [x] **iOS** but have not tested behavior on Android
    - [ ] **Android** but have not tested behavior on iOS
    - [ ] Both
- **`stream-chat-react-native` version you're using that has this issue:**
    - `5.27.0`
- Device/Emulator info:
  - [ ] I am using a physical device
  - OS version: `ios 17.5`
  - Device/Emulator: `iPhone SE (third generation)`

</p>
</details>

### Screenshots

<details><summary>Click To Expand</summary>
<p>

![image](https://github.com/user-attachments/assets/63c33a7b-4d8e-4434-ad30-019c5c369b91)

![image](https://github.com/user-attachments/assets/856eb598-7bd5-4191-b794-1a1b9ef0544a)

</p>
</details>

---

**Comment by khushal87** [comment]
Hey @quememo, firstly, I would like to inform you that the need to wrap `GestureHandlerRootView` has been around for a long time and was not introduced post 5.17.0. It could be hard to answer why it was not an issue for you because you might have switched to a specific version of RNGH that caused a need for this in your application which might not have been the case previously. The RNGH docs provide a need for its usage in the installation docs [here](https://docs.swmansion.com/react-native-gesture-handler/docs/fundamentals/installation#js). Hope that helps! 😄
