### ISSUE TITLE
[v1] Missing export from MessageSimple

### ISSUE THREAD

**Issue by giautm** [GetStream/stream-chat-react-native#265]
In [MessageStatus.js](https://github.com/GetStream/stream-chat-react-native/blob/master/src/components/Message/MessageSimple/MessageStatus.js), export is using [`export default`](https://github.com/GetStream/stream-chat-react-native/blob/59618adbc238763cf7fd3d5ba3dd0304012877de/src/components/Message/MessageSimple/MessageStatus.js#L133). But, In Message.js everythings was exported as 
https://github.com/GetStream/stream-chat-react-native/blob/59618adbc238763cf7fd3d5ba3dd0304012877de/src/components/Message/MessageSimple/index.js#L423-L426

It must be
```ts
export { default as MessageStatus } from './MessageStatus';
export { default as MessageContent } from './MessageContent';
export { default as MessageAvatar } from './MessageAvatar';
export { default as MessageTextContainer } from './MessageTextContainer';
```

I think this issue was caused by this commit: https://github.com/GetStream/stream-chat-react-native/commit/7ba8bb4b1b3e1a77da443cd079305613a4857905

Please rewrite this module in typescript to consistent between code JS & TS types.

Thank you very much,

gz#4699

**Comment by vishalnarkhede** [comment]
Hey @giautm ,

This has been fixed as part of v1.1.0.
