### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by espadon54** [GetStream/stream-chat-react-native#272]
Hi,

Playing with getStream since 2/3 weeks and it's awesome. I just have an issue I can't fix. I have a "Unhandled JS Exception: RangeError: Maximum call stack size exceeded" when receiving a new message on a channel while I am in the channel screen.

I am suspecting one of the getStream component might be causing of this error.

![Screen Shot 2020-08-03 at 11 22 40 AM](https://user-images.githubusercontent.com/59118978/89156414-b6a23980-d57b-11ea-9ae9-5f20f4bd0c83.png)

Any idea?

EDIT:  I am using stream-chat@1.13.2, stream-chat-react-native@1.1.0,  react-native@0.62.2

gz#5115

**Comment by vishalnarkhede** [comment]
Hi @espadon54 could you please share some code around Stream's chat component from your side?

**Comment by espadon54** [comment]
Hi yes sure,
What I do is that I initialize the client once and then using redux the same client is used between the views which need it.

Can this kind of implementation be an issue?

<img width="458" alt="Screen Shot 2020-08-03 at 7 46 43 PM" src="https://user-images.githubusercontent.com/59118978/89201143-1ae7ec00-d5c2-11ea-9961-5bd2e5f65efa.png">

Lmehdi

**Comment by vishalnarkhede** [comment]
Hi @espadon54

I am not able to reproduce the issue unfortunately. Is it possible for you to setup [expo snack](https://snack.expo.io/) with reproducible issue? That will help us with debugging

**Comment by espadon54** [comment]
Ok I find out where this came from. It was actually from my implementation using the event listening part to update the number of unread messages.

<img width="421" alt="Screen Shot 2020-08-04 at 11 14 44 AM" src="https://user-images.githubusercontent.com/59118978/89264487-1237fa00-d644-11ea-93c1-feea77c81e0e.png">
