### ISSUE TITLE
How do I add to theming the MessageReplies.tsx color of replies?

### ISSUE THREAD

**Issue by billnbell3** [GetStream/stream-chat-react-native#2773]
file: src/components/Message/MessageSimple/MessageReplies.tsx

-        <Text style={[styles.messageRepliesText, { color: accent_blue }, messageRepliesText]}>
+        <Text style={[styles.messageRepliesText, { color: '#004750' }, messageRepliesText]}>

I want to not use accent_blue but use '#004750'. in replies? How do I do this? If this is not possible, how do I change accent_blue to '#004750'

**Comment by khushal87** [comment]
Hey @billnbell3, pass this to the theme object that you have for your app. If you don't have one, please go through our [theming guide](https://getstream.io/chat/docs/sdk/react-native/customization/theming/), and you will know how to set up the theme.

Below is the object you will have to pass to the theme.

```
messageSimple: {
    replies: {
      messageRepliesText: {
        color: '#004750',
      },
    },
  },
```
