### ISSUE TITLE
[🐛] TypeError: Cannot read property 'state' of undefined

### ISSUE THREAD

**Issue by luannguyenhealthli** [GetStream/stream-chat-react-native#2777]
## Issue
Describe your issue here
TypeError: Cannot read property 'state' of undefined

### Steps to reproduce

1. I'm using the "stream-chat-react-native" version "^5.41.1", and there’s no issue when getting the ChannelList.
```
<Chat client={chatClient}>
          <ChannelList
        filters={{
          joined: true,
          members: { $in: [userStream.userId] },
        }}
        additionalFlatListProps={{
          ListFooterComponent: FooterLoadMoreButton,
          onEndReached: () => null,
        }}
        onSelect={(channel) => {
          navigation.navigate("StreamChatDetail", {
            channel,
          });
        }}
        numberOfSkeletons={8}
        PreviewAvatar={({}) => <Fragment />}
        PreviewTitle={({ channel }) => (
          <Text
            style={{
              ...fonts.type.base(15, "#000000"),
              fontWeight: channel.countUnread() ? "600" : "400",
            }}
          >
            {channel.data?.name || channel.cid}
          </Text>
        )}
      />
     </ChannelList>
</Chat>
```
2. But when I use it in the ThreadList, it throws an error like in the screenshot.

`
<Chat client={chatClient}>
<ThreadList isFocused={isFocused} />
</Chat>
`
![Simulator Screenshot - iPhong 14 Pro 18 0 - 2024-11-13 at 13 59 58](https://github.com/user-attachments/assets/3028bf68-4e86-4891-b091-00751885079a)

### Expected behavior
The API and components  is more stable or the error is more descriptive.
Additionally, please help me handle the null cases. I’ve encountered many instances and had to add the '?' symbol. This is quite frustrating.

**Comment by luannguyenhealthli** [comment]
![Uploading Screenshot 2024-11-13 at 14.18.50.png…]()

**Comment by luannguyenhealthli** [comment]
![Screenshot 2024-11-13 at 14 18 50](https://github.com/user-attachments/assets/e275b5bf-7d97-49d0-9108-5bd10f801049)

**Comment by luannguyenhealthli** [comment]
![Screenshot 2024-11-13 at 14 23 34](https://github.com/user-attachments/assets/027c6596-42d7-4adf-88da-60c4fcf2b37a)

**Comment by isekovanic** [comment]
Hi @luannguyenhealthli ,

It seems to me like you're passing an uninitialised `client` to the `ThreadList` component. The `ThreadManager` encapsulated in `client.threads` is initialised whenever the `client` is initialised. 

Can you confirm that `client.threads` exists ?

If it does not, are you by any chance installing the `stream-chat` library as well for some reason ? If that's the case you would also need to bump it to reflect the version used in version `5.41.1` of the React Native SDK.

**Comment by luannguyenhealthli** [comment]
Hi @isekovanic, sorry for the delayed response. I’ve rechecked it, and it’s working again after I cleared the cache and reinstalled the app to load the updated library. Everything seems to be functioning properly now. Apologies for the inconvenience.
