### ISSUE TITLE
MessageList component gives Error while updating property "src" of a view managed by: RCTImageView (Android)

### ISSUE THREAD

**Issue by patriciam97** [GetStream/stream-chat-react-native#278]
**Describe the bug**
Not sure if there was a recent update but for the past 2 days I keep getting the following error: Error while updating property "src" of a view managed by: RCTImageView coming from the MessageList component.

This happens in all branches even older ones that didn't have a change for sometime.  This occurs only in the Android app. iOS works fine.

I tried the following things but nothing got fixed:

- Removing node modules and package-lock.json and running npm i
- Clean npm cache
- Wipe emulator
- Delete emulator and create another one
- Tried running the app from my Samsung s10 phone
- Uninstalling Android Studio and installing it again

**Dev environment info (please complete/provide the following information):**

- "stream-chat-react-native": "^0.9.2"
- react-native-cli: 2.0.1
- react-native: 0.60.5
- Android Pixel 3a Api 30 Android 10.00+

**To Reproduce**
The application has a home page that shows all of the chats the user has joined. Once I open a chat the app crashes giving me the above error. I debugged the code by removing all components and adding them back one by one. The app crashes when it renders <MessageList>

**Expected behavior**
Do not crash. Show me the chat content as before.

**Additional context**

**Screenshots**
<img width="389" alt="Screenshot 2020-08-08 at 09 45 00" src="https://user-images.githubusercontent.com/39942633/89704358-d5c61000-d95b-11ea-8c6c-2d00d4689c5e.png">

Hope there is a solution to this. Thank you

gz#5203

**Comment by patriciam97** [comment]
Hey @vishalnarkhede , is there something I can do to fix this?

**Comment by vishalnarkhede** [comment]
Hey @patriciam97 , we will look into this and get back to you soonish. Could you please share some code around chat components?

**Comment by patriciam97** [comment]
I attached this bit which is pretty much where the error occurs:

`
 <Chat client={this.props.chatClient} style={listTheme}>
            <View style={{ display: 'flex', height: '100%', padding: 10 }}>
              <ChannelList
                LoadingIndicator={customLoadingIndicator}
                LoadingErrorIndicator={this.customErrorIndicator}
                filters={{
                  type: 'messaging',
                  members: { $in: [this.props.chatClient.user.id] }
                }}
                sort={{ last_message_at: -1 }}
                Preview={ChannelPreviewMessenger}
                onSelect={channel => {
                  this.props.navigation.navigate('Chat', {
                    channel: channel,
                    isMember: true
                  });
                }}
              />
            </View>
          </Chat>
`


`const customLoadingIndicator = props => {
  return <LoadingIndicator {...props} loadingText=" " />;
};
`

**Comment by patriciam97** [comment]
Hi @vishalnarkhede !

It seems like the component was crashing because a url of a user's avatar was broken. We have removed that user and the problem has been fixed.
