### ISSUE TITLE
New Architecture of RN 0.76.3 not supported?

### ISSUE THREAD

**Issue by billnbell3** [GetStream/stream-chat-react-native#2812]
In RN 0.76.3 this module is not listed as supported.

https://reactnative.directory

Please verify you support the latest React Native.

**Comment by khushal87** [comment]
Hey @billnbell3, we are new architecture ready with v6 that is in rc phase right now. You can choose to test it out by running the command:

```
yarn add stream-chat-react-native@rc
```
The new version contains a lot of exciting changes, most notable of which are:
- React Native New Architecture support 🚀. Our SDK is still compatible with the old RN architecture as well.
- A refreshment of some of our dependencies.
- A revamp of our message menu/actions design, as well as a revamp of the reaction list design.

You can find the full extent of the changes (and a migration guide) here: https://getstream.io/chat/docs/sdk/react-native/v6-rc/basics/upgrading-from-v5/, as well as a new architecture migration guide found here: https://getstream.io/chat/docs/sdk/react-native/v6-rc/guides/new-architecture/.

However, there are some quirks on the SDK with new architecture, so you can keep them in mind - https://getstream.io/chat/docs/sdk/react-native/v6-rc/guides/new-architecture/. 

The stable v6 release should be out very soon.

**Comment by khushal87** [comment]
We have just released v6 for our RN SDK that supports new architecture, so I am closing this issue in favour of it. Thanks 😄 

Migration guide:- https://getstream.io/chat/docs/sdk/react-native/basics/upgrading-from-v5/
New architecture docs:- https://getstream.io/chat/docs/sdk/react-native/guides/new-architecture/
