### ISSUE TITLE
Which method I have to use for call auto focus on messageInput of stream-chat-react-native

### ISSUE THREAD

**Issue by panda919** [GetStream/stream-chat-react-native#283]
**Describe the bug**

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native: 1.1.1 )
- react-native : 0.63.2

**Expected behavior**
I gonna apply autofocus on stream-chat-react-native message input when open channel screen. But I couldn't find a matched function. In order apply focus as programmatically, what should I do?
**Screenshots**
![image](https://user-images.githubusercontent.com/25161426/90084608-5ca62e80-dd48-11ea-854b-a2cf0199a994.png)

gz#5285

**Comment by vishalnarkhede** [comment]
Hey @panda919 , you can try the following

```js
<MessageInput
    additionalTextInputProps={{
        autoFocus: true
    }}
/>
```

**Comment by vishalnarkhede** [comment]
Hey @panda919 please reopen the issue if you have more questions.
