### ISSUE TITLE
ReactionList does not show up after reaction is selected

### ISSUE THREAD

**Issue by kmanj-pixel** [GetStream/stream-chat-react-native#284]
**Describe the bug**

When selecting a reaction from the reaction picker, the reaction picker hides but reaction list does not show up.

From what I can tell, the reaction picker is still "visible" so the reaction list doesn't show up. Additional attempts to open the reaction picker (custom behavior is clicking the message) does not result in the picker re-opening.

Relevant code:
```
export const CustomMessage = memo((props: MessageUIComponentProps) => {
  const { message } = props;

  // Intercepting message actions for tracking analytics
  const handleReaction = (type: string) => {
    logChatMessageReaction(message.text, type, message.user.id);
    props.handleReaction(type);
  };

  const onPress = (contentProps: MessageContentUIComponentProps) => {
    console.log(contentProps.reactionPickerVisible); // This is true even if the modal isn't seen on clicks after the first
    logChatMessagePress(message);
    // Open reactions picker onPress
    contentProps.openReactionPicker();
  };

  return (
    <MessageSimple
      {...props}
      MessageText={KMessageText}
      handleReaction={handleReaction}
      supportedReactions={SUPPORTED_MESSAGE_REACTIONS}
      MessageContent={(props: MessageContentUIComponentProps) => {
        return (
          <MessageContent
            {...props}
            onPress={() => {
              onPress(props);
            }}
          />
        );
      }}
    />
  );
});


```

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native/stream-chat-expo): "stream-chat-expo": "^1.1.1"
- react-native or expo version: Expo 38

- Device/Emulator (android/ios) and OS version: iOS simulator, 13.5

**To Reproduce**

1. Click message to show reaction picker (this is the custom behavior we want).
2. Select a reaction.

**Expected behavior**

Reaction list shows after reaction picker hides.

**Additional context**

**Screenshots**

Video: https://imgur.com/a/reHHqdG

gz#5321

**Comment by vishalnarkhede** [comment]
Hey @kmanj-pixel this is a known issue. It happens when you try to use custom `MessageContent` component. I can suggest some alternative if you tell me the reason why you are using custom MessageContent component?

We are currently refactoring our react-native sdk to start using hooks. We will take care of this issue as part of that refactoring.

**Comment by kmanj-pixel** [comment]
1. What is the ETA on the refactor?

2. We want the reaction picker to open on message press. It seems like the only way to access `openReactionPicker` is via 'MessageContentUIComponentProps`.

**Comment by vishalnarkhede** [comment]
Hey,

1. ETA for refactor of message related components is around 2-3 weeks.
2. You can do it the following way:

```js
    <MessageSimple
      {...props}
      onPress={thisArg => thisArg.props.openReactionPicker()}
    />
```

**Comment by kmanj-pixel** [comment]
Alright thanks, that works for now. There is another use case where we use MessageContent, so please keep me posted on the more appropriate fix.
