### ISSUE TITLE
[🐛] react-native-quick-sqlite deprecated, won't build on Android

### ISSUE THREAD

**Issue by robsoden** [GetStream/stream-chat-react-native#2845]
## Issue

react-native-quick-sqlite is deprecated and no longer maintained.
additionally, there is a build issue with react-native-quick-sqlite on android using gradle plugin 4.0 and greater.

according to the link in the error (https://developer.android.com/r/tools/jniLibs-vs-imported-targets) the package would need to be reconfigured and re-released with an updated jni config, but with no maintainers, this is unlikely to happen.

as such, offline mode for stream-chat-react-native is effectively unusable.

error:
```
> 2 files found with path 'lib/armeabi-v7a/libreact_nativemodule_core.so' from inputs:
      - /Users/[redacted]/Projects/[redacted]/node_modules/react-native-quick-sqlite/android/build/intermediates/library_jni/debug/jni/armeabi-v7a/libreact_nativemodule_core.so
      - /Users/[redacted]/.gradle/caches/transforms-3/c14bf64b9e65ca1e329bda537892d56b/transformed/jetified-react-android-0.72.7-debug/jni/armeabi-v7a/libreact_nativemodule_core.so
     If you are using jniLibs and CMake IMPORTED targets, see
     https://developer.android.com/r/tools/jniLibs-vs-imported-targets
```

### Steps to reproduce

1. yarn add react-native-quick-sqlite
2. compile for android

### Expected behavior

app builds

### Customization

<details><summary>Click To Expand</summary>
<p>

```typescript jsx
# N/A
```
</p>
</details>

### Offline support

- [x] I have enabled offline support.
- [ ] The feature I'm having does not occur when offline support is disabled. (stripe out if not applicable)

## Environment

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```
"stream-chat-react-native": "^5.38.0",
```

**`react-native info` output:**

```
 System:
  OS: macOS 14.6.1
  CPU: (11) arm64 Apple M3 Pro
  Memory: 62.66 MB / 18.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 22.2.0
    path: /var/folders/1q/_jq0ql9j4932dn4f87gr224w0000gr/T/yarn--1733938378866-0.7049285481537415/node
  Yarn:
    version: 1.22.22
    path: /var/folders/1q/_jq0ql9j4932dn4f87gr224w0000gr/T/yarn--1733938378866-0.7049285481537415/yarn
  npm:
    version: 10.7.0
    path: ~/.nvm/versions/node/v22.2.0/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.15.2
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.1
      - iOS 18.1
      - macOS 15.1
      - tvOS 18.1
      - visionOS 2.1
      - watchOS 11.1
  Android SDK:
    API Levels:
      - "33"
      - "34"
    Build Tools:
      - 30.0.3
      - 33.0.0
      - 33.0.1
      - 34.0.0
    System Images:
      - android-34 | Google APIs ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2023.3 AI-233.14808.21.2331.11842104
  Xcode:
    version: 16.1/16B40
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.11
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.17
    wanted: 0.72.17
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

- **Platform that you're experiencing the issue on**:
    - [ ] iOS
    - [x] Android
    - [ ] **iOS** but have not tested behavior on Android
    - [ ] **Android** but have not tested behavior on iOS
    - [ ] Both
- **`stream-chat-react-native` version you're using that has this issue:**
    - `e.g. 5.4.3`
- Device/Emulator info:
  - [ ] I am using a physical device
  - OS version: `e.g. Android 10`
  - Device/Emulator: `e.g. iPhone 11`

</p>
</details>

### Screenshots

<details><summary>Click To Expand</summary>
<p>

</p>
</details>

---

**Comment by khushal87** [comment]
We have just released v6 for our RN SDK, where we have moved from react-native-quick-sqlite to op-sqlite, so I am closing this issue in favour of it. Thanks 😄

Migration guide - https://getstream.io/chat/docs/sdk/react-native/basics/upgrading-from-v5/

**Comment by jmoyers14** [comment]
Wow so we need to upgrade all the way to expo 52 and rn 75 to get this update? That's terrible
