### ISSUE TITLE
[🐛]Facing issue while update stream sdk

### ISSUE THREAD

**Issue by 12varun12** [GetStream/stream-chat-react-native#2859]
## Issue

I am upgrading my SDK from version 5.22.1 to version 6.0.1

### Steps to reproduce

   etc...

### Customization

<details><summary>Click To Expand</summary>
<p>

```typescript jsx
# N/A
```
</p>
</details>

### Offline support

- [ ] I have enabled offline support.
- [ ] The feature I'm having does not occur when offline support is disabled. (stripe out if not applicable)

## Environment

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
    - [ ] iOS
    - [ ] Android
    - [ ] **iOS** but have not tested behavior on Android
    - [ ] **Android** but have not tested behavior on iOS
    - [ ] Both
- **`stream-chat-react-native` version you're using that has this issue:**
    -  "stream-chat-react-native": "5.22.1",
    -  "react-native": "0.70.3",
- Device/Emulator info:
  - [ ] I am using a physical device
  - OS version: `e.g. Android 10`
  - Device/Emulator: `e.g. iPhone 11`

</p>
</details>

### Screenshots

<details><summary>Click To Expand</summary>
<p>

</p>
</details>

---

**Comment by khushal87** [comment]
Hey @12varun12, please explain what is the exact issue that you are facing while upgrading the version and did you follow the [migration guide](https://getstream.io/chat/docs/sdk/react-native/basics/upgrading-from-v5/)?

**Comment by 12varun12** [comment]
after upgrading the SDK my android and ios app is not running it shows error

**Comment by khushal87** [comment]
Hey @12varun12, please share your error log with us and provide us with more information about what you are facing. It's currently impossible to help without any information from your side. Thanks :) 

As a suggestion, firstly upgrade to the latest version 5, which is `5.44.2`, and then when it works for you, try to upgrade to v6 using the guide I shared. Simply jumping might not work for your use case.

**Comment by 12varun12** [comment]
[image: image.png]

**Comment by khushal87** [comment]
Hey, the image doesn't open.

**Comment by 12varun12** [comment]
@khushal Agarwal any update on it?

**Comment by khushal87** [comment]
The image you shared is not visible. We cannot help you this way. Please upgrade to the latest of the v5.44.2 and then follow the migration guide https://getstream.io/chat/docs/sdk/react-native/basics/upgrading-from-v5/ to upgrade to v6.
