### ISSUE TITLE
Android Styled ActionSheet on iOS

### ISSUE THREAD

**Issue by brandonhall** [GetStream/stream-chat-react-native#286]
**Describe the bug**

**Dev environment info (please complete/provide the following information):**

- "stream-chat-react-native": "^1.1.1",
- "react-native": "0.62.2",
- iOS Simulator running 13.6

**To Reproduce**

1. Add new message
2. Long press message to reveal action sheet
3. Notice the action sheet is the Android version

**Expected behavior**
An iOS specific action sheet

**Additional context**
This issue only appears with message action sheets. For choosing a photo, I'm not seeing the issue. We're also running `@expo/react-native-action-sheet": "^3.8.0` which has `ActionSheetProvider` at the top level of the app. Note: I'm not overriding action sheet styles anywhere.

**Screenshots**
![Screen Recording 2020-08-17 at 12 20 53 AM](https://user-images.githubusercontent.com/1144477/90357047-9fedef00-e01f-11ea-9933-711f903182a3.gif)

gz#5354

**Comment by vishalnarkhede** [comment]
Hey Brandon,

We use external library `react-native-actionsheet` for displaying action menu, which renders the UI (shown by you in video) on both iOS and android platform. We are currently going through major refactoring of our react-native components. And we will soon be replacing this actionsheet with platform specific menu (e.g. context menu for iOS).

**Comment by vishalnarkhede** [comment]
Stream is working on building new UI components. Revamp of actionsheet is part of that project.
