### ISSUE TITLE
MessageSimple can lose text if message is a certain length.

### ISSUE THREAD

**Issue by jjmcmillan** [GetStream/stream-chat-react-native#294]
**Describe the bug**

When writing and sending a new message, some words can be "cut-off" from MessageSimple. This seems to be an issue with displaying the full message, rather than the actual content of the message - it is clear once trying to edit the message, the full message still exists.

**Dev environment info (please complete/provide the following information):**

- "stream-chat-react-native": "^0.9.2"
- "react-native": "0.60.5",
- OnePlus 6t

**To Reproduce**

The following message will show in it's entirety: 

On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue.

The following message will cut-off the "test" placed at the end of the paragraph and this word isn't visibl:

On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue test.

**Expected behavior**
MessageSimple should display the entire message including the word "test" at the end of the paragraph. Thanks for your excellent support.

**Screenshots**
![Screenshot_20200821-163424](https://user-images.githubusercontent.com/18230292/90909485-b43e3d00-e3cd-11ea-83e4-449129203ec1.jpg)
![Screenshot_20200821-163434](https://user-images.githubusercontent.com/18230292/90909495-b7d1c400-e3cd-11ea-9c41-5a9a1b1f9d4e.jpg)

gz#5477

**Comment by vishalnarkhede** [comment]
Hey @jjmcmillan ,

Are you also setting some custom theme on Chat component? If yes, can you please show me the value of theme?

**Comment by jjmcmillan** [comment]
Hi @vishalnarkhede, yes we are setting custom theme:

```
const chatTheme = {
  colors: {
    primary: '#bababa'
  },
  'avatar.image': 'border-radius: 6px',
  'avatar.fallback': 'border-radius: 6px',
  'messageList.messageSystem.text': 'font-size: 11',
  'messageList.messageSystem.textContainer': 'flex: 6; margin-bottom: 20',
  'messageList.messageSystem.dateText': 'font-size: 0',
  'message.content.markdown': {
    text: {
      fontFamily: Platform.OS === 'ios' ? 'Helvetica Neue' : 'roboto',
      fontSize: 16
    }
  }
};
```
 I realised this is causing the issue, and after removing text styling it shows the full message. However, we would still like to increase the font size and use a custom font family in our messages - is it still possible to achieve this without text being "cut-off" from a message? Thank you for your help.

**Comment by virdesai** [comment]
@jjmcmillan hi, looking through our code, could you try putting `messageList.messageSystem.text.css` instead of `messageList.messageSystem.text`? if that's the issue you're having

**Comment by vishalnarkhede** [comment]
Hey @jjmcmillan could you confirm if the issue is only because of following style?

```
'messageList.messageSystem.textContainer': 'flex: 6; margin-bottom: 20',
```

**Comment by jjmcmillan** [comment]
Hey @virdesai and @vishalnarkhede, apologies for the delay in getting back to you. I've been doing some playing around using your suggestions, but noticed the issue of certain words being "cut-off" exists even when all styling is removed, and Stream's default styling is used. As you can see from the image below, I have removed all styling, but the message has still cut off the final word as the message is meant to end "come September."

![Screenshot_20200902-232328__01](https://user-images.githubusercontent.com/18230292/92043734-8b765a00-ed74-11ea-9da9-86213c642dc2.jpg)

Would you be able to confirm your versions are able to include the FULL message: 

"Hey guys, really sorry for interrupting. Just wanted to let you know Student+ University of Edinburgh is now available on the app stores. As current students, we’ve built an app that allows new students to connect into their classes, and have productive conversations with classmates come September."

Thanks for your ongoing support with this matter.

**Comment by virdesai** [comment]
@jjmcmillan seems like the whole message displays within our example app ![image](https://user-images.githubusercontent.com/9044436/92208527-64de1f00-ee59-11ea-86aa-46b211265de6.png)

**Comment by jjmcmillan** [comment]
@virdesai Okay thanks for confirming, I'll test on a few more devices to see if it might be a device issue. Thank you.

**Comment by jjmcmillan** [comment]
Hello, I've done some testing on different devices and we have narrowed this down to be an issue with android. We have been able to reproduce the issue on various different android devices without any theme applied, using Streams latest SDK. This is a message sent on an android device:

![Screenshot_20200911-181124](https://user-images.githubusercontent.com/18230292/92954612-9fe4e180-f45b-11ea-9d8d-467f0ee19a42.jpg)

And this is the same message sent on an iPhone 5 (showing the full message):

![IMG_0264](https://user-images.githubusercontent.com/18230292/92954624-a70bef80-f45b-11ea-899a-77b073b727ac.PNG)

As you can understand this is quite a frustrating bug. Please let me know if you are able to reproduce this bug, and have any suggestions or recommendations. Thanks for your ongoing support.

**Comment by shodgetts** [comment]
Agent comment from Vishal Narkhede in <a href='https://getstream.zendesk.com/agent/tickets/5477'>Zendesk ticket #5477</a>:<br><br>Hey,

Can you send us the complete code around Stream's chat components?

Thanks,
Vishal

**Comment by jjmcmillan** [comment]
Hi all, good news. After much frustration we have been able to narrow down the cause of this bug to two things:

1. I am running my development app on a OnePlus 6t and their OnePlus Slate font is problematic and was causing the text to be "cut off" even when all stream custom styling was removed.

2. Increasing the font size of messages also causes this bug.

We have solved number one, however, the second issues still remains a problem for us. We feel the default text size Stream uses is far too small, so when applying a fontSize of 16 this again causes the font to be cut off.

This is a message without any modification to the fontSize:

![Screenshot_20200918-173019](https://user-images.githubusercontent.com/18230292/93622609-56edd980-f9d5-11ea-8714-863bdf5d49ef.jpg)

And the same message with modification to the fontSize changed to 16:

![Screenshot_20200918-173004](https://user-images.githubusercontent.com/18230292/93622621-5b19f700-f9d5-11ea-82b8-f1cfe4259284.jpg)

Here is the code for the entire screen:

```
import React, { Component } from 'react';
import {
  View,
  SafeAreaView,
  Text,
  TouchableOpacity,
  StyleSheet,
  Dimensions,
  StatusBar,
  Linking
} from 'react-native';
import firebase from 'react-native-firebase';
import {
  Chat,
  Channel,
  MessageList,
  MessageInput,
  MessageContent
} from 'stream-chat-react-native';
import { connect } from 'react-redux';

const { width: WIDTH } = Dimensions.get('window');

const chatTheme = {
  'message.content.markdown': {
    // list of all available options are here: https://github.com/CharlesMangwa/react-native-simple-markdown/tree/next#styles-1
    text: {
      fontFamily: Platform.OS === 'ios' ? 'Helvetica Neue' : 'roboto',
    }
  }
};


class ChatScreen extends Component {
  render() {
    const { navigation, chatClient } = this.props;
    const channel = navigation.getParam('channel');

    return (
      <SafeAreaView>
        <Chat client={chatClient} style={chatTheme}>
          <Channel client={chatClient} channel={channel}>
            <MessageList />
            <MessageInput />
          </Channel>
        </Chat>
      </SafeAreaView>
    );
  }
}

function mapStateToProps(state) {
  const chatClient = state.login.chatClient;
  return {
    chatClient: chatClient
  };
}

export default connect(mapStateToProps, {})(ChatScreen);

```

**Do you have any suggestions regarding how we could increase the fontSize of messages, but still ensure the full text is included in the message's box?**

**Comment by jjmcmillan** [comment]
@vishalnarkhede @virdesai hope you are well. Have you managed to look into the query (increasing font size without losing text)? We're hoping to launch an update on Sunday so would be amazing to have this fixed by then. Thank you :)

**Comment by vishalnarkhede** [comment]
Hey @jjmcmillan sorry for the delay. I will check it today and get back to you!!

**Comment by jjmcmillan** [comment]
@vishalnarkhede awesome thank you

**Comment by vishalnarkhede** [comment]
@jjmcmillan So after some spending some hours of debugging, it turns out `paddingHorizontal`  causes issue on android. E.g., I can see same issue on following sample code (which is not related to Stream). If you remove paddingHorizontal, everything works fine.

```js
<View
  style={{
    borderColor: 'black',
    borderWidth: 1,
    paddingHorizontal: 17,
  }}>
  <Text>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
    eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
    ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
    aliquip ex ea commodo consequat. Duis aute irure dolor in
    reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
    pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
    culpa qui officia deserunt mollit anim id est laborum and also boo
  </Text>
</View>
```

I am not completely sure yet how to fix it. But atleast we know whats causing the issue. I will get back to you once I find a solution.

**Comment by jjmcmillan** [comment]
@vishalnarkhede thank you for taking the time to look into this - good to hear you're closer to a solution. Hopefully fixing this bug will be a great addition to the SDK. Let me know when it's solved :)

**Comment by vishalnarkhede** [comment]
@jjmcmillan Seems like this issue has been fixed on react-native's side in 0.63. What version are you using of react-native?

**Comment by jjmcmillan** [comment]
@vishalnarkhede Hi Vishal, great to hear you have identified a solution. Unfortunately we haven't got round to updating to that version of React Native just yet but hope to do so soon and will let you know if that resolves the issue. Thanks so much for your support throughout this issue.

**Comment by vishalnarkhede** [comment]
@jjmcmillan any update?

**Comment by jjmcmillan** [comment]
@vishalnarkhede so sorry for the long delay in getting back to you. It's been a very busy time for us and we had to hold off on upgrading react native to identify if it would resolve this bug. The good news is that it indeed seems to have fixed it! I'm closing this ticket. Thanks again for your support with this, I hope you are well.
