### ISSUE TITLE
Full screen "useNativeDriver" error when viewing an image attachment

### ISSUE THREAD

**Issue by amardeepranu** [GetStream/stream-chat-react-native#302]
On the latest version the `react-native-image-zoom-viewer` always throws a warning to set `useNativeDriver`. This can be fixed by updating the library to 3.0.1: https://github.com/ascoders/react-native-image-viewer/issues/398

![Simulator Screen Shot - iPhone 11 Pro - 2020-08-26 at 10 18 42](https://user-images.githubusercontent.com/7548096/91315298-85d1b080-e785-11ea-8322-904893f885f0.png)

gz#5571

**Comment by shodgetts** [comment]
Agent comment from Stephen Hodgetts in <a href='https://getstream.zendesk.com/agent/tickets/5571'>Zendesk ticket #5571</a>:<br><br>thanks for the report

**Comment by DanC5** [comment]
I see the latest version of `react-native-image-zoom-viewer` has added `useNativeDriver` to all the animated timings, upgrading in our library now!

**Comment by thegitparticle** [comment]
@DanC5 when can we expect the update for this? Or meanwhile is there any way to fix it for now?

**Comment by DanC5** [comment]
> @DanC5 when can we expect the update for this? Or meanwhile is there any way to fix it for now?

The upgrade has already been merged to master, so as soon as @vishalnarkhede makes a new release it'll be out in the wild.

**Comment by thegitparticle** [comment]
@DanC5 Also, the actionsheets keep throwing the same error. Is the package which manages them also add the native drive support and has been updated by you?

**Comment by DanC5** [comment]
> @DanC5 Also, the actionsheets keep throwing the same error. Is the package which manages them also add the native drive support and has been updated by you?

I just looked into this and the action sheet package we're using, `react-native-actionsheet`, doesn't specify the native driver in their animated timings. Revamping the action sheet is something that's on our to-do list though, so thanks for another ping on this.

**Comment by sclavijo93** [comment]
Hi, any news about this? 😅

**Comment by DanC5** [comment]
> Hi, any news about this? 😅

Hey Saul, while we haven't removed this package yet, we have allowed the ability to customize the action sheet component. If you use the `ActionSheet` prop on the `MessageSimple` component, you can create your own action sheet and override the default behavior which calls the `react-native-actionsheet` dependency.
