### ISSUE TITLE
Message object in notification template does not work as expected

### ISSUE THREAD

**Issue by haivle** [GetStream/stream-chat-react-native#307]
**Describe the bug**
Here is the template we are using in firebase data push notification template:
```
{
	"message": "{{ message.id }}",
	"type": "{{ message.type }}",
	"channel": "{{ channel.id }}",
	"parentId": "{{ message.parent_id }}"
}
```

Although the message is sent from a thread, the parentId and type field is still empty

**Dev environment info (please complete/provide the following information):**

- Package version stream-chat-react-native 1.2.x
- react-native 0.63.1
- Device: iOS

**To Reproduce**
- Change notification template on streamIO dashboard
- Reply to a message in a channel
- Receive and log notification data from a device

**Expected behavior**
- message.parent_id and message.type should have value

gz#5662

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/5662'>Zendesk ticket #5662</a>:<br><br>Hi Haivle

Thanks for reporting it to us.
We will investigate this issue and get back.

Cheers
Seetha

**Comment by ferhatelmas** [comment]
@haivle Missing fields were not a part of the context that is building the template, we added them and it will be deployed on Monday.

**Comment by ferhatelmas** [comment]
@haivle this is deployed so closing. Let us know otherwise.

**Comment by haivle** [comment]
Hi @ferhatelmas, looks like the bug is still there, I'm still receiving empty parentId from the data template mentioned above

**Comment by ferhatelmas** [comment]
@haivle I need your app details to investigate your case. Could you write to https://getstream.io/support mentioning this issue? Thanks!
