### ISSUE TITLE
MessageInput does not reposition after dismissing keyboard.

### ISSUE THREAD

**Issue by girish-trabacus** [GetStream/stream-chat-react-native#325]
**Describe the bug**
When the the user clicks on the MessageInput the keyboard opens and the MessageInput moves up to avoid being hidden by the keyboard. After the user is done typing, they dismiss the keyboard. At this point the MessageInput should go back to its original position, but it does not. It stays in the middle of the screen even after the keyboard is dismissed. Refer to the image below. Also this issue does not seem to be happening if an image is not selected for sending.

![WhatsApp Image 2020-09-12 at 1 40 14 PM](https://user-images.githubusercontent.com/56107027/92991123-00792a80-f4ff-11ea-97f1-24c2ab6cc646.jpeg)

**Dev environment info (please complete/provide the following information):**

"react-native": "0.61.5"
"stream-chat": "^1.14.0",
"stream-chat-react-native": "^1.1.1"
Issue is on android. Not sure if it's the same on iOS.

gz#5948

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/5948'>Zendesk ticket #5948</a>:<br><br>Hi Girish

Thanks for reaching out to us.
Will get this checked with our Engineer and let you know.
Meanwhile, can you please share your User ID and APP ID. Thanks.

Cheers
Seetha

**Comment by shodgetts** [comment]
Agent comment from Vishal Narkhede in <a href='https://getstream.zendesk.com/agent/tickets/5948'>Zendesk ticket #5948</a>:<br><br>Hey Girish,

Currently we are working on releasing 1.3.0 of stream-chat-react-native, where we have fixed lot of Keyboard related issues. So I would recommend you to kindly wait until end of this week (or maximum middle of next week) until we publish the stable version.

Thanks,
Vishal

**Comment by vishalnarkhede** [comment]
Hey @girish-trabacus Can you please upgrade to `stream-chat-react-native@1.3.3` and try following solution:

```js
import { KeyboardCompatibleView } from 'stream-chat-react-native'

// Define a custom keyboard view
const CustomKeyboardCompatibleView = ({children}) => (
    <KeyboardCompatibleView
      // You will need to fine-tune following keyboardVerticalOffset
      // as per your app UI
      // For iOS - its the height of your input box
      // For android - its some negative number, 
      keyboardVerticalOffset={Platform.OS === 'ios' ? 66.5 : -200}
      behavior={Platform.OS === 'ios' ? 'padding' : 'position'}>
      {children}
    </KeyboardCompatibleView>
  );

// And then use it in channel component
<Channel KeyboardCompatibleView={CustomKeyboardCompatibleView}>
      ...
</Channel>
```

**Comment by girish-trabacus** [comment]
@vishalnarkhede Thanks, updating the package has fixed the issue.
