### ISSUE TITLE
Gallery Not Wanted SafeAreaView for ImageViewer

### ISSUE THREAD

**Issue by jparksecurity** [GetStream/stream-chat-react-native#326]
**Describe the bug**
[SafeAreaVeiw in Gallery](https://github.com/GetStream/stream-chat-react-native/blob/014f4accc64ab93aa8bd5ddb98417d90ec3203d4/src/components/Attachment/Gallery.js#L124) doesn't work well for my case. I'd like an ImageViewer to be full screen not safe area screen when a user clicks a photo. I believe I can build a custom Gallery component, but I was wondering if it's something you'd like to add this feature.

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native/stream-chat-expo)
stream-chat-expo@0.14.0
stream-chat@1.13.2
- react-native or expo version
expo@38.0.8
- Device/Emulator (android/ios) and OS version
iOS Emulator iPhone 11 pro max(but it should be any OS)

**To Reproduce**

1. Go to any screen where you can see image preview
2. Click on an image
3. See the black background of ImageViewer is in safe area

**Expected behavior**
The gallery component has a prop to control whether the black area fits the safe area or the whole screen

**Screenshots**
How it is
<img width="438" alt="Screen Shot 2020-09-14 at 4 47 06 AM" src="https://user-images.githubusercontent.com/14362029/93073633-d3d12a00-f648-11ea-958c-0e2aea6a800b.png">
How I want it to be
<img width="438" alt="Screen Shot 2020-09-14 at 5 11 31 AM" src="https://user-images.githubusercontent.com/14362029/93073636-d764b100-f648-11ea-8169-7b774f95b90c.png">

gz#5967

**Comment by shodgetts** [comment]
Agent comment from Stephen Hodgetts in <a href='https://getstream.zendesk.com/agent/tickets/5967'>Zendesk ticket #5967</a>:<br><br>thank you for the request - we will look into this.

**Comment by virdesai** [comment]
@jparksecurity there are a lot of different scenarios we have to deal with for supporting this so it's on our roadmap to consider implementing but just with an unknown ETA. For now you are able to create and use your own custom Gallery component which can support this rendering until we have any progress on this from our end

**Comment by jparksecurity** [comment]
@virdesai Gotcha. Thank you for the comment! I'm gonna create a custom Gallery component for now.
