### ISSUE TITLE
[Question] how would I style the 'New Message' notification in the MessageList component. 

### ISSUE THREAD

**Issue by ZhymonNorman** [GetStream/stream-chat-react-native#327]
I would like to do things like change the background color, add padding or margin, font etc. I have already looked at using the CSS styling like for the message list and that did not work.

**Comment by virdesai** [comment]
@ZhymonNorman are these CSS styling overrides not working for you? https://github.com/GetStream/stream-chat-react-native/blob/master/src/components/MessageList/MessageNotification.js#L9:L27
