### ISSUE TITLE
How to render a custom component inside the MessageList View?

### ISSUE THREAD

**Issue by decamps-enmanuel** [GetStream/stream-chat-react-native#330]
I have a custom component that allows me to add coupons to my app and I would like to render it inside the MessageList component. I have fiddled with the Attachment component (still outside of MessageList) and achieved some semblance of functionality if all else fails. If it's possible I'd like to use mine, since it looks like a coupon and allows me to modify the coupon codes programmatically. If this is indeed possible it'd be great to add it to the cookbook. 

gz#6012

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/6012'>Zendesk ticket #6012</a>:<br><br>Hi

Thanks for reaching out to us.
I just noticed you are on an expired chat trial. Are you considering a paid plan?

Can you please give us a bit more detail about the use case?

Cheers
Seetha

**Comment by decamps-enmanuel** [comment]
Yes. I am actively developing an app and we're relying on GetStream to
reach our customer base on a more personal level. We currently have a list
of businesses that customers can subscribe to via our app and this enables
the chat functionality. Once this happens businesses (on the business app)
can chat with customers/send promotions/coupons/deals/changes in their menu
and so on. We work with react-native (Expo) and we already have a component
built for displaying the coupons programmatically and we would like to
display it inside the MessageList View. The documentation is a bit fuzzy
and I'm not sure how to proceed.

**Comment by vishalnarkhede** [comment]
Hey @decamps-enmanuel ,

How do you define a coupon? Does it contain some image or is it just a plain text (with some custom styling)?

**Comment by decamps-enmanuel** [comment]
> Hey @decamps-enmanuel ,
> 
> How do you define a coupon? Does it contain some image or is it just a plain text (with some custom styling)?

Hi! It's a react card component that may contain images, links, styling, buttons, basically any functionality available for a react component. If you need further information I can whip up an image.

**Comment by decamps-enmanuel** [comment]
Looking through your docs, I stumbled upon MML and that's exactly what I need. How do I enable them? My employer needs to see a working demo before commiting to GetStream and the documentation is very hit or miss.

**Comment by vishalnarkhede** [comment]
Hey @decamps-enmanuel MML part is currently in progress only for our react sdk, not for react-native sdk.

**Comment by vishalnarkhede** [comment]
@decamps-enmanuel please reopen if you have any more questions :)
