### ISSUE TITLE
Unable to select, copy, paste from messages, links sent as messages

### ISSUE THREAD

**Issue by thegitparticle** [GetStream/stream-chat-react-native#339]
Long press on messages typically gives options to copy the text or link. But here, when long pressed, only reply, reaction options popup as part of the action sheet without a copy option. How can the user copy text of messages? Or atleast copy links shared in the chat? 

gz#6120

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/6120'>Zendesk ticket #6120</a>:<br><br>Hi

Thanks for reaching out to us.
Unfortunately, this isn't actually supported in the SDK right now, according to our developers.  It will hopefully be coming later this year as we continue to add customizations to the SDK.

Please keep an eye on our git hub releases. Please let us know if you need anything else.

Cheers
Seetha

**Comment by vishalnarkhede** [comment]
Hey @thegitparticle we will  add some example of this usecase to our cookbook soon.

**Comment by thegitparticle** [comment]
@shodgetts Thanks, will try the library. @vishalnarkhede Sure, looking forward for it.

**Comment by vishalnarkhede** [comment]
@thegitparticle Actually you should definitely take a look at how we added custom action sheet in our slack-clone project. This will help your case - https://github.com/GetStream/slack-clone-react-native/blob/master/src/components/MessageSlack.js#L27

**Comment by vishalnarkhede** [comment]
@thegitparticle please reopen if the above example didn't help :)
