### ISSUE TITLE
uuid@8.3.0 required a polyfill, so it crash on Expo < 39

### ISSUE THREAD

**Issue by giautm** [GetStream/stream-chat-react-native#340]
@nhannah, @vishalnarkhede  This update crash Expo SDK 38, `uuid` require a polyfill for `crypto.getRandomValues `
(https://github.com/uuidjs/uuid#react-native)
But, `import 'react-native-get-random-values';` only support from SDK-39. So, This update crash SendMessage method.

_Originally posted by @giautm in https://github.com/GetStream/stream-chat-react-native/pull/282#discussion_r488437462_

gz#6132

**Comment by vishalnarkhede** [comment]
Hey @giautm thanks for bringing this up. We will investigate and fix this asap!!
