### ISSUE TITLE
Custom chat preview is not showing the name

### ISSUE THREAD

**Issue by sclavijo93** [GetStream/stream-chat-react-native#345]
**Describe the bug**
I'm using the doc's example for customizing the chat preview from [Customize channel preview](https://getstream.io/chat/react-native-chat/tutorial/#) but I can't get the channel name.

I've logged the channel.data prop in the console and this is the JSON I got:
```
{
   "id":"chat-xxxxxxx",
   "type":"messaging",
   "cid":"messaging:chat-xxxxxx",
   "last_message_at":"2020-09-19T03:09:33.478387Z",
   "created_at":"2020-09-18T18:13:33.25022Z",
   "updated_at":"2020-09-18T18:13:33.25022Z",
   "created_by":{
      "id":"xxxxxxx",
      "role":"user",
      "created_at":"2020-09-04T18:30:03.801623Z",
      "updated_at":"2020-09-21T22:50:38.574652Z",
      "last_active":"2020-09-21T22:50:38.574652Z",
      "banned":false,
      "online":true,
      "phone":"xxxxx",
      "playerId":null,
      "devices":null,
      "image":"xxxxxxx",
      "invisible":false,
      "mutes":null,
      "name":"xxxxx",
      "nick":"xxxxx"
   },
   "frozen":false,
   "member_count":2,
   "config":{
      "created_at":"2020-09-21T15:56:33.804648265Z",
      "updated_at":"2020-09-21T15:56:33.804651714Z",
      "name":"messaging",
      "typing_events":true,
      "read_events":true,
      "connect_events":true,
      "search":true,
      "reactions":true,
      "replies":true,
      "mutes":true,
      "uploads":true,
      "url_enrichment":true,
      "message_retention":"infinite",
      "max_message_length":5000,
      "automod":"disabled",
      "automod_behavior":"flag",
      "commands":[
         {
            "name":"giphy",
            "description":"Post a random gif to the channel",
            "args":"[text]",
            "set":"fun_set"
         }
      ]
   }
}
```

I can't find the channel's name. Could you help me please?

**Dev environment info (please complete/provide the following information):**

- Package version: stream-chat-react-native v^1.2.0
- react-native: 0.63
- Device: ios v13.7

### Update
Can't get the image too, channel.data.image doesn't exist

gz#6146

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/6146'>Zendesk ticket #6146</a>:<br><br>Hi

Thanks for reaching out to us.
I will get this checked for you.

Cheers
Stream Team

**Comment by vishalnarkhede** [comment]
Hey @sclavijo93 , `name` is a custom property on channel. Are you sure you have set this property on channel? If not, please update the channel using 

```
await channel.update({ 
  name: 'Dummy channel',
  ...
})
```

**Comment by sclavijo93** [comment]
Sorry, what a shame, I'll close this issue because I found my mistake. My backend team doesn't set that property so I would never find it 😅  sorry again @vishalnarkhede
