### ISSUE TITLE
Attachment styling

### ISSUE THREAD

**Issue by sclavijo93** [GetStream/stream-chat-react-native#356]
Hi, is there a way to change the style of the attachment image? I need to apply border radius to all the image corners not only the top two. 

The component is <Attachment ... />

gz#6304

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/6304'>Zendesk ticket #6304</a>:<br><br>This request was closed and merged into request #6305 "Component styling".
