### ISSUE TITLE
Docs refer to wrong/outdated react-native-push-notifications library

### ISSUE THREAD

**Issue by jackel119** [GetStream/stream-chat-react-native#376]
Whilst setting up push notifiications for my app, I followed the instructions [here](https://getstream.io/chat/docs/rn_push_initial/?language=js) and [here](https://getstream.io/blog/android-ios-push-notifications-with-stream-chat-and-react-native/). However, I simply could not get `react-native-push-notifications` token register handlers to work.

After a few hours, I encountered the issue: there are two separate, very similarly named libraries `react-native-push-notifications` and `react-native-push-notification`. The former, which is what is described in stream's docs, refers to an npm package which hasn't been updated in 3 years and no longer works (at least not for android), whilst the latter is a modern maintained version with 50k weekly downloads and actually works.

Please update the official stream docs to point to the correct choice of package (which is `react-native-push-notification` without the `s`).

gz#6511

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/6511'>Zendesk ticket #6511</a>:<br><br>Hi Jackel

Thanks for reporting this to us.
Apologies for the discrepancies, we will get them rectified.

Cheers
Seetha
