### ISSUE TITLE
Error occurs when trying to customize "message.content.textContainer.rightBorderWidth"

### ISSUE THREAD

**Issue by junminleeKS** [GetStream/stream-chat-react-native#377]
**Describe the bug**
I am getting an error when trying to customize `message.content.textContainer.rightBorderWidth`. I am passing an object into the style prop of the `Channel` component. I ran into the following error:
`Error: Unknown theme key message.content.textContainer.rightBorderWidth`

**Dev environment info (please complete/provide the following information):**

- Package version
  - stream-chat-expo: 1.3.3
- react-native or expo version
  - expo
- Device/Emulator (android/ios) and OS version
  - Android and iOS devices

**To Reproduce**

1. Pass the following object into the style prop of the `Channel` component:
```
const style = {
  "message.content.textContainer.rightBorderWidth": 1
};
```
2. The error will show when rendering `Channel`.

**Expected behavior**
No error should occur.

**Additional context**
The source of the error can be found on line 340 of `src/styles/theme.js`.
```
...
} else if (lodashGet(defaultTheme, k)) {
...
```

When looking at the `defaultTheme` object in the same file you'll see the following:
```
const defaultTheme = {
  ...
  message: {
    ...
    textContainer: {
        borderRadiusL: 16,
        borderRadiusS: 2,
        leftBorderColor: 'rgba(0,0,0,0.08)',
        leftBorderWidth: 0.5,
        rightBorderColor: 'transparent',
        rightBorderWidth: 0,
      },
    ...
  },
  ...
};
```

The above `if` check is false for `rightBorderWidth` because `lodashGet(defaultTheme, k)` will return 0. However we want the outcome of this to be true.

gz#6531

**Comment by vishalnarkhede** [comment]
Hey @junminleeKS can you try the object format?

```js
  message: {
    content: {
      textContainer: {
        rightBorderWidth: 10
      }
    }
  },
```

**Comment by junminleeKS** [comment]
That fixed it! Thank you.
