### ISSUE TITLE
 push notification via Expo.io

### ISSUE THREAD

**Issue by lokewk** [GetStream/stream-chat-react-native#382]
Hi, is there any sample of  push notification via Expo.io? 
or can this even possible at this moment?

gz#6624

**Comment by virdesai** [comment]
@lokewk unsure if these steps will work as the documentation states that you will need to eject from expo but you can first try to follow the expo push notification tutorial in their docs here: https://docs.expo.io/push-notifications/overview/ and then if you can retrieve a device token you can try to call `client.setDevice` with that token as shown here: https://getstream.io/chat/docs/rn_push_stream/?language=js

Once you have done this, you have to leave the app and have been off of the app for enough time for the websocket to close (maybe ~15-30 seconds) before attempting to receive a push notification on a device. The expo push notification tutorial states that this needs to be done on a physical device, not an emulator

also ensure that you register your appID and push certificates within the Stream dashboard

**Comment by lokewk** [comment]
> @lokewk unsure if these steps will work as the documentation states that you will need to eject from expo but you can first try to follow the expo push notification tutorial in their docs here: https://docs.expo.io/push-notifications/overview/ and then if you can retrieve a device token you can try to call `client.setDevice` with that token as shown here: https://getstream.io/chat/docs/rn_push_stream/?language=js
> 
> Once you have done this, you have to leave the app and have been off of the app for enough time for the websocket to close (maybe ~15-30 seconds) before attempting to receive a push notification on a device. The expo push notification tutorial states that this needs to be done on a physical device, not an emulator
> 
> also ensure that you register your appID and push certificates within the Stream dashboard

Thank you for your suggestion. 
I have test it out, we manage to get the device tokens.
But the push notification did not get tru. i got the error messages below.

from APN:
![Screenshot 2020-09-17 at 11 02 20 AM](https://user-images.githubusercontent.com/68896130/96095518-46138380-0f01-11eb-82df-5d29934d9b12.png)

from Firebase:
![Screenshot 2020-10-15 at 4 13 26 PM](https://user-images.githubusercontent.com/68896130/96095617-6cd1ba00-0f01-11eb-99a0-1eab6632ecd6.png)

**Comment by lokewk** [comment]
@vishalnarkhede @virdesai any idea? really need to resolve this.

**Comment by virdesai** [comment]
@lokewk have you tried ejecting as described here: https://getstream.io/chat/docs/rn_push_initial/?language=js

**Comment by lokewk** [comment]
@virdesai we do not have the options to eject. is it possible to do this without ejecting?

**Comment by melissafzhang** [comment]
I was also wondering the same thing. Someone from support told me that the only way to get this to work with non-ejected expo app is to use webhooks. Would love to know if there's another workaround since adding webhooks is not an option for us right now

**Comment by virdesai** [comment]
@lokewk @melissafzhang have you followed both of these guides? https://docs.expo.io/push-notifications/push-notifications-setup/ and https://docs.expo.io/push-notifications/using-fcm/

where are you seeing those errors? to me it reads like a response from the APN/FCM side not having registered the device or token that's trying to be used properly

**Comment by lokewk** [comment]
@virdesai  i am seeing those errors on my test devices (not simulator). 
registering the device is not done by getstream API?

**Comment by virdesai** [comment]
@lokewk the gestream API takes the device token which is returned to it from the push notification implementation in your code. it then uses that device token to tell the APN/FCM service that a push notification is trying to be sent to that device token. the push services recognizing that device as a valid device to send to (correct key, no previous failures, app IDs registered to allow push notifications, p12/p8 keys generated) is not handled by Stream. did you ensure you setup the APN p12/p8 and FCM server key on the getstream dashboard?

**Comment by lokewk** [comment]
@virdesai i have given up on direct push notification from getstream.io chat. i am using webhook method to my AWS SNS now. will be great if  push notification from getstream.io chat works with Expo apps moving forward. thanks.

**Comment by teeaaspoon** [comment]
@virdesai @lokewk @vishalnarkhede is there any fix to this currently? I want to use push notifications for expo as well without ejecting my app.

**Comment by jaydotcom** [comment]
@lokewk can you share with us what you have done for it ?

**Comment by sohailmadan** [comment]
Hi Any update on this i need to implement push notifications in my expo app. @vishalnarkhede
