### ISSUE TITLE
GIPHY buttons not working

### ISSUE THREAD

**Issue by junminleeKS** [GetStream/stream-chat-react-native#390]
**Describe the bug**
The GIPHY actions (Send, Shuffle, and Cancel) do not do anything after being pressed.

**Dev environment info (please complete/provide the following information):**
- stream-chat v2.6.0 (^2.2.2)
- stream-chat-expo v1.3.4
- Android and iOS devices

**To Reproduce**
1. Enter a channel
2. Type /giphy followed by any text and then send the message
3. Press Send, Shuffle, or Cancel when the actions pop up
4. Pressing on the buttons should do nothing

gz#6743

**Comment by melissafzhang** [comment]
I'm also experiencing this issue! Is there a way to turn off Giphy while this is getting fixed?

**Comment by melissafzhang** [comment]
This was fixed in the latest release fyi!

**Comment by vishalnarkhede** [comment]
@melissafzhang glad to head that its fixed :)
