### ISSUE TITLE
Encountered two children with the same key

### ISSUE THREAD

**Issue by melissafzhang** [GetStream/stream-chat-react-native#392]
**Describe the bug**
Messages are being displayed twice and causing the error `Encountered two children with the same key`

**Dev environment info (please complete/provide the following information):**

- stream-chat-expo v 1.3.4
- expo version 39.0.0, react native 39.0.3
- iOS Emulator

**To Reproduce**

1. Go to message list
2. Send message
3. Message shows up twice

**Expected behavior**
The expectation is that message shows up once and does not throw the error

**Additional context**
Refetching the messages displays the sent message only once. 

**Screenshots**

<img width="435" alt="Screen Shot 2020-10-20 at 4 07 49 PM" src="https://user-images.githubusercontent.com/38673112/96653707-894d6800-12ee-11eb-8ea9-5be8aba7bd84.png">

gz#6763

**Comment by mahboubii** [comment]
hey @melissafzhang, please use `stream-chat@v2.6.0` at the moment. It should be addressed in the next patch release.

**Comment by melissafzhang** [comment]
@mahboubii which `stream-chat-expo` version is that? Looks like there's only the beta version released.

**Comment by mahboubii** [comment]
> @mahboubii which `stream-chat-expo` version is that? Looks like there's only the beta version released.

Any version of `stream-chat-expo` should be fine. Currently, the last compatible version `stream-chat` is [v2.6.0](https://www.npmjs.com/package/stream-chat/v/2.6.0)

**Comment by melissafzhang** [comment]
I’m currently experiencing the issue with stream-chat-expo v2.6.0.

**Comment by melissafzhang** [comment]
@mahboubii I'm experience this issue with the latest `stream-chat-expo` v1.3.4. Do I need to install `stream-chat` in addition to `stream-chat-expo`?

**Comment by melissafzhang** [comment]
Installing `stream-chat` separately worked!
