### ISSUE TITLE
Attempted to remove more RCTKeyboardObserver listeners than added

### ISSUE THREAD

**Issue by radekcy** [GetStream/stream-chat-react-native#397]
**Describe the bug**
When I'm connected to chat channel using my local build, I send the app to background and bring it back to foreground. Doing it the second time causes an exception: _**Attempted to remove more RCTKeyboardObserver listeners than added**_

**Dev environment info (please complete/provide the following information):**

- Package version: stream-chat-react-native: ^1.3.4
- react-native: 0.63.3
- Device/Emulator: iOS simulator/device debug build

**To Reproduce**

1. Build an app with chat locally and connect with a channel
2. Send the app to background
3. Bring it back to foreground
4. Repeat steps 2 and 3
5. The error shows: **Attempted to remove more RCTKeyboardObserver listeners than added**

**Expected behavior**
An app built locally shouldn't cause exception when moving the app from background to foreground.

**Screenshots**
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-10-26 at 13 47 31](https://user-images.githubusercontent.com/33669425/97174045-d2d80000-1791-11eb-9833-450adc981855.png)

gz#6864

**Comment by shodgetts** [comment]
Agent comment from Stephen Hodgetts in <a href='https://getstream.zendesk.com/agent/tickets/6864'>Zendesk ticket #6864</a>:<br><br>Thanks for the bug report.

**Comment by vishalnarkhede** [comment]
Hey @radekcy , please upgrade to v1.3.5. We have fixed this issue in that patch.
