### ISSUE TITLE
Error uploading image

### ISSUE THREAD

**Issue by melissafzhang** [GetStream/stream-chat-react-native#398]
**Describe the bug**
When trying to upload an image on simulator, I get this error 
`StreamChat error code 4: UploadImage failed with error: "request Content-Type isn't multipart/form-data"`

**Dev environment info (please complete/provide the following information):**

-  "stream-chat": "2.6.0"
- "stream-chat-expo": "^1.3.4"
- "react-native": "39.0.3"
- "expo": "^39.0.0",
- iOS simulator

**To Reproduce**

1. Go to Chat
2. Click on + and add photo
3. Image preview is added
4. See error and unable to click send

**Expected behavior**
You can upload image

**Additional context**

**Screenshots**
<img width="1005" alt="Screen Shot 2020-10-26 at 11 46 44 AM" src="https://user-images.githubusercontent.com/38673112/97214852-ef1f7100-1780-11eb-8aed-ba20c601d087.png">

gz#6874

**Comment by shodgetts** [comment]
Agent comment from Stephen Hodgetts in <a href='https://getstream.zendesk.com/agent/tickets/6874'>Zendesk ticket #6874</a>:<br><br>Thanks for the report. An engineer will look into this shortly.

-Stephen

**Comment by melissafzhang** [comment]
Actually this is an issue with the debugger I use which doesn't work with image uploading. Thanks!
