### ISSUE TITLE
Unable to dismiss keyboard after typing

### ISSUE THREAD

**Issue by melissafzhang** [GetStream/stream-chat-react-native#399]
**Describe the bug**
There's no way to dismiss the keyboard after typing. We have tab navigation that show up behind the keyboard but there's no way to dismiss the keyboard. 

**Dev environment info (please complete/provide the following information):**

"stream-chat": "2.6.0"
"stream-chat-expo": "^1.3.4"
"react-native": "39.0.3"
"expo": "^39.0.0",
iOS simulator

**To Reproduce**

1. Go to chat screen
2. Click on message input
3. No way to dismiss keyboard

**Expected behavior**
Can tab outside to dismiss keyboard

gz#6879

**Comment by shodgetts** [comment]
Agent comment from Stephen Hodgetts in <a href='https://getstream.zendesk.com/agent/tickets/6879'>Zendesk ticket #6879</a>:<br><br>Hello, thank you for the report. The RN team will look into this shortly. Can you email support@getstream.io with future issues? We'd love to hear what you're building.

**Comment by melissafzhang** [comment]
Actually clicking on the chat messages dismisses the keyboard. However, if there are only a few messages, clicking above the messages does not dismiss the keyboard.

**Comment by vishalnarkhede** [comment]
@melissafzhang you can try the following:

```js
<MessageList
  additionalFlatListProps={{
    keyboardShouldPersistTaps: 'never'
  }}
/>
```

**Comment by melissafzhang** [comment]
Awesome that worked!
