### ISSUE TITLE
MessageInput not working correctly with SafeAreaView on Android

### ISSUE THREAD

**Issue by ian** [GetStream/stream-chat-react-native#40]
Working fine on iOS but on Android the message box gets covered by the keyboard.

![Screenshot_20190801-193458](https://user-images.githubusercontent.com/19853/62336054-1ad77c80-b494-11e9-8c08-196f52506e37.png)

Code is straight out of the example on https://getstream.io/chat/react-native-chat/tutorial/

```
<SafeAreaView>
  <Chat client={chatClient}>
    <Channel channel={channel}>
      <View
        style={{ display: "flex", height: "100%", background: "#FFF" }}
      >
        <MessageList />
        <MessageInput />
      </View>
    </Channel>
  </Chat>
</SafeAreaView>
```

**Comment by vishalnarkhede** [comment]
Hey @ian 

Can you give us following details about your dev environment?

- React native version
- Android emulator version
- Version of `stream-chat-react-native` that you are using

**Comment by ian** [comment]
Hey @vishalnarkhede 

- Android device, Google Pixel 3
- react-native@0.59.8
- expo@33.0.7
- stream-chat-expo@0.1.15
- stream-chat-react-native-core@0.1.15

**Comment by vishalnarkhede** [comment]
Hey @ian 

Thank you for information. Will look into it get back to you!!

**Comment by vishalnarkhede** [comment]
Hey @ian 

This issue is now fixed in **v0.1.18**. Thank you for brining this up. 

Please reopen the issue if it doesn't work for you :)

**Comment by ian** [comment]
Verified working, thanks for the fix.

**Comment by Drzaln** [comment]
Hi, i get this bug too in v^3.6.1
I have bottom navigation and keyboard covering half of the text input

![image](https://user-images.githubusercontent.com/33492469/128294264-1a003907-7fc3-4b17-8cae-f09824ee6cfd.png)

**Comment by vishalnarkhede** [comment]
Hey @Drzaln could you try this prop - https://getstream.io/chat/docs/sdk/reactnative/core-components/channel/#keyboardverticaloffset

**Comment by anandparmar-quark** [comment]
@vishalnarkhede - I found the same issue in v5.7.0. Any solution?

Attaching a screenshot for reference. 

![Screenshot_20230303-124640_CoFounder](https://user-images.githubusercontent.com/100852255/222656760-8b1ce2c2-73aa-4543-b4d9-a18862bb31d7.jpg)
