### ISSUE TITLE
When Cancelling add attachment app crashes 

### ISSUE THREAD

**Issue by lokewk** [GetStream/stream-chat-react-native#401]
https://github.com/GetStream/stream-chat-react-native/issues/110#issue-545695006

Hi folks, i still have this issue still. Anyone else still facing this issue? 

gz#6911

**Comment by vishalnarkhede** [comment]
What version of stream-chat-react-native are you on?

**Comment by lokewk** [comment]
![Screenshot 2020-10-28 at 3 20 19 PM](https://user-images.githubusercontent.com/68896130/97404467-1cab1c80-1931-11eb-815c-4db8d26c61d7.png)
@vishalnarkhede I am on expo.

**Comment by vishalnarkhede** [comment]
Hey @lokewk , we have fixed this issue on v2.x.x. Can you please try to upgrade and check?

Following links will help with upgrade:
- https://github.com/GetStream/stream-chat-react-native/blob/master/examples/ExpoMessaging/App.js
- https://github.com/GetStream/stream-chat-react-native/wiki/Upgrade-helper

**Comment by vishalnarkhede** [comment]
@lokewk any update?

**Comment by lokewk** [comment]
Is alright now, after upgrading. thanks
