### ISSUE TITLE
Reply message not response

### ISSUE THREAD

**Issue by lokewk** [GetStream/stream-chat-react-native#404]
can't reply messages from messageslist component. When select reply, nothing happens. Please advise.
i am on:
    "expo": "^39.0.0",
    "stream-chat": "2.6.0",
    "stream-chat-expo": "^1.3.4" 

![Screenshot 2020-10-29 at 1 27 32 PM](https://user-images.githubusercontent.com/68896130/97529273-820f1400-19ea-11eb-80f4-016ac3f964d0.png)

 

gz#6966

**Comment by vishalnarkhede** [comment]
You need to add prop on MessageList component:

```js
<MessageList
    onThreadSelect={(thread) => {
    setThread(thread);
        navigation.navigate('Thread', {channelId: channel.id});
    }}
/>
```

Please check the example app - https://github.com/GetStream/stream-chat-react-native/blob/master/examples/NativeMessaging/App.js

**Comment by lokewk** [comment]
@vishalnarkhede Thank you for your clear guide. I managed to recreate this function.

**Comment by tuneerclixlogix** [comment]
@vishalnarkhede I am having same issue, I don't want another thread to open. I wan't to reply to the message in the same channel like in whatsapp or facebook messenger

**Comment by vishalnarkhede** [comment]
@tuneerclixlogix We have added inline reply or quote message feature as part of v3!!

**Comment by lokewk** [comment]
@vishalnarkhede do you have a sample code in expo.io javascript?

**Comment by lokewk** [comment]
@vishalnarkhede i noticed the v3 example is on vanilla react native. is there an example on expo?

**Comment by vishalnarkhede** [comment]
@lokewk you can check this expo example app - https://github.com/GetStream/stream-chat-react-native/tree/master/examples/ExpoMessaging
