### ISSUE TITLE
Is forwarding messages available?

### ISSUE THREAD

**Issue by isabellaskc** [GetStream/stream-chat-react-native#406]
Long press a chat message enables users to edit / delete / add reaction to a message. Is forwarding message available? (Forwarding a message from the current channel to another existing channel).
Can't seem to find any working examples or information in the docs.

gz#7016

**Comment by vishalnarkhede** [comment]
@isabellaskc we currently don't have example of forward message UX.

**Comment by isabellaskc** [comment]
@vishalnarkhede will the function be available?

**Comment by vishalnarkhede** [comment]
@isabellaskc we don't currently have it on the roadmap to provide it OOTB.
