### ISSUE TITLE
Missing Readby Data

### ISSUE THREAD

**Issue by lokewk** [GetStream/stream-chat-react-native#429]
Describe the bug
When using a custom Message for MessageList, we want to show list of users that have read the message. We have lost this feature after following this Example "Message bubble with name of sender" from this link, https://github.com/GetStream/stream-chat-react-native/blob/master/docs/cookbook.md#message-bubble-with-name-of-sender

Dev environment info (please complete/provide the following information):

stream-chat-expo @^2.0.0(stream-chat-react-native/stream-chat-expo)
Expo SDK 39
iOS emulator and physical device as well as Android emulator and physical device
To Reproduce

1. Go to chat from MessageList view
2. Readby details is missing.

Expected behavior
Readby details should be shown next to current user avatar.

gz#7382

**Comment by vishalnarkhede** [comment]
@lokewk can you please show me the code of custom message component?

**Comment by lokewk** [comment]
here it is.
```
import React, { useState, useEffect } from 'react';
import { View, Text, StyleSheet, Image, Clipboard} from 'react-native';
import {
  Avatar,
  Chat,
  Channel,
  MessageList,
  MessageInput,
  ChannelList,
  IconBadge,
  MessageSimple,
  MessageContent,
} from 'stream-chat-expo' 
import moment from 'moment';
// import {Clipboard, useClipboard} from '@react-native-community/clipboard';
//import Clipboard from '@react-native-community/clipboard';
import SnackBar from 'react-native-snackbar-component';

import Colors from '../constants/Colors'

class MessageContentWithName extends React.PureComponent {
  render() {
    //console.log("Message is Selected: "+ this.props.message.selected);
    //console.log(this.props);
    return (
      <View style={
        this.props.message.selected==true
        ? { flexDirection: 'column', padding: 5,  
            backgroundColor: Colors.primaryColor,
          }
        : { 
          flexDirection: 'column', padding: 5,  
          backgroundColor: '', 
        }}> 
        <Text style={{fontWeight: 'bold', fontSize: 12}}>{this.props.message.user.name}</Text>
        <MessageContent 
        {...this.props}
         />
      </View>
    );
  }
}

const CustomMessagePreview = props => {
  //const [data, setString] = useClipboard();
  const [isVisible, setIsVisible] = useState(false);

  const copyToClipboard = (text) => {
    //console.log(text);
    Clipboard.setString(text);
  };
  return (
    <View>
      <MessageSimple
            {...props}  
            MessageContent={MessageContentWithName}  
            dismissKeyboardOnMessageTouch={true}
            onLongPress={(message, e) => {
              //console.log('['+ moment(message).format('DD/MM, HH:MM') +']'+message.user.name +': '+ message.text); 
              //console.log(message);
              //message.selected=(message.selected==null)?true:!message.selected;
              copyToClipboard('['+ moment(message).format('DD/MM, HH:MM') +']'+message.user.name +': '+ message.text);
              setIsVisible(true)
              setTimeout(function(){ 
                //Put All Your Code Here, Which You Want To Execute After Some Delay Time.
                setIsVisible(false)           
              }, 1000);
            }}
            onPress={(message, e) => {
              //props.openReactionPicker();
              // Or if you want to open action sheet
              props.showActionSheet();
            }}
          /> 
          <SnackBar visible={isVisible} textMessage="Message copied!" />
    </View>
  )
};

const styles = StyleSheet.create({
    text: {
        fontFamily: 'montserrat'
    }
});

export default CustomMessagePreview;
```

**Comment by shodgetts** [comment]
Agent comment from Stephen Hodgetts in <a href='https://getstream.zendesk.com/agent/tickets/7382'>Zendesk ticket #7382</a>:<br><br>Hello, what is the Stream AppID or key that you are using please?

**Comment by lokewk** [comment]
8j99xmpyrrtu
this is my AppID

**Comment by lokewk** [comment]
@shodgetts Any update on this?

**Comment by vishalnarkhede** [comment]
@lokewk are you setting `forceAlign` prop on `CustomMessagePreview` by any chance?

**Comment by Jeancpdamke** [comment]
I am getting the same issue, the avatars of the users that read the message are not showing, just the time of when the message was sent.

I investigated a bit and I saw that the MessageStatus component does a check to see if `message.id === lastReceivedId`, and then renders the avatars. In our case, both props from our CustomMessage (which renders MessageSimple) and our CustomMessageContent (which renders MessageContent) come with a lastReceivedId as undefined.

Could this be the issue? And if so, what could be causing it?

**Comment by lokewk** [comment]
@vishalnarkhede no i m not setting `forceAlign` prop on `CustomMessagePreview`

**Comment by vishalnarkhede** [comment]
Hey @Jeancpdamke thanks for the investigation. This in-fact is the issue it seems. I will check and get back to you why this is happening.

**Comment by isabellaskc** [comment]
Hi @vishalnarkhede , any updates on @Jeancpdamke 's investigation?

**Comment by vishalnarkhede** [comment]
@isabellaskc @Jeancpdamke We have fixed the issue - https://github.com/GetStream/stream-chat-react-native/commit/b6df565e2cc1f0a899aa6977c3a27bbe5c94854f

It will be released in next patch, early next week :)

**Comment by vishalnarkhede** [comment]
@Jeancpdamke @isabellaskc Please use `stream-chat-react-native@2.1.0` - https://github.com/GetStream/stream-chat-react-native/releases/tag/v2.1.0

**Comment by Jeancpdamke** [comment]
@vishalnarkhede  Thanks a lot, it's working again for me!
