### ISSUE TITLE
Red full screen error when viewing an image in chat

### ISSUE THREAD

**Issue by amardeepranu** [GetStream/stream-chat-react-native#433]
On the latest version (v2.0.2) I'm getting full red screen error when opening an image:

![IMG_40FA79921090-1](https://user-images.githubusercontent.com/7548096/99273574-3684a480-27f7-11eb-862a-a92b48f134dd.jpeg)

I believe this line is the culprit:
https://github.com/GetStream/stream-chat-react-native/blob/0985105e84fdb107ccf6ab385d16083e4bf4e02e/src/components/Attachment/Gallery.tsx#L101

gz#7392

**Comment by virdesai** [comment]
@amardeepranu that line isn't new to 2.0.2 however this issue seems more related to the installation setup you have with another 3rd party setup which requires a change to the iOS Info.plist build file

**Comment by vishalnarkhede** [comment]
@amardeepranu ping ^^

**Comment by amardeepranu** [comment]
Sounds good!
