### ISSUE TITLE
client.setUserAgent is undefined

### ISSUE THREAD

**Issue by megantaylor** [GetStream/stream-chat-react-native#441]
**Describe the bug**

When I try to open my app in Expo client, i get an error that `client.setUserAgent` is undefined in stream-chat-react-native-core/src/components/Chat.tsx and cannot finish loading the app.

**Dev environment info (please complete/provide the following information):**

- "stream-chat-expo" v2.0.2
- expo v39
- iOS Simulator iPhone 12 Pro Max v14.2

**To Reproduce**

Open app in Expo client

**Expected behavior**

 Expected app to load

**Additional context**

App loads and chat works if I add more null checking, ie 
`client && client.setUserAgent && client.setUserAgent(`stream-chat-react-native-${Platform.OS}-${version}`)`

gz#7501

**Comment by shodgetts** [comment]
Agent comment from Anders Lund in <a href='https://getstream.zendesk.com/agent/tickets/7501'>Zendesk ticket #7501</a>:<br><br>Hi There,

I'd like to explore this issue a bit further but will need some additional details. Would you mind emailing support@getstream.io with your app ID as well as a full code snippet of where the error is occurring?

**Comment by vishalnarkhede** [comment]
@megantaylor what version of `stream-chat` are you using?

**Comment by megantaylor** [comment]
@vishalnarkhede we have stream-chat-expo 2.0.2, stream-chat-react-native-core 2.0.2, stream-chat-react 1.2.5, stream-chat 2.7.0 and stream-chat 1.12.1...ooh, i bet thats the problem! will update if that resolves the issue.

**Comment by megantaylor** [comment]
@vishalnarkhede @shodgetts that did the trick! thanks! #monorepoProblems
