### ISSUE TITLE
Entire screen is unresponsive after sending a few messages

### ISSUE THREAD

**Issue by amardeepranu** [GetStream/stream-chat-react-native#444]
I'm using react navigation with stream chat react native 2.0.2, I just added a tab bar to my application, no other change. When I type a few messages the entire screen is frozen and the keyboard disappears, the entire app has to be force quit. No errors reported. I am using example code. I've attached a video:

![Image](https://user-images.githubusercontent.com/7548096/100349352-4d28b980-2fb6-11eb-84c9-3c126be933d2.gif)

This does not happen all the time.

gz#7605

**Comment by amardeepranu** [comment]
Disabling swipe to back gestures in react navigation for the channel screen fixes this issue FYI. I assume theres something conflicting there thats causing this lock up.

**Comment by vishalnarkhede** [comment]
@amardeepranu I would help us if you can setup an expo snack to reproduce the issue and share with us. Or if you can reproduce it on one of the example apps.

**Comment by vishalnarkhede** [comment]
@amardeepranu I would recommend you to to upgrade to v3 of our SDK. We have addressed this issue :)
