### ISSUE TITLE
Deleted a channel but messages were restored

### ISSUE THREAD

**Issue by isabellaskc** [GetStream/stream-chat-react-native#445]
A 1 to 1 conversation was created, upon deleting the channel, the channel is removed from the channel list. However, when the same party starts a new conversation, all old messages were being restored. 

The following method was used to delete the channel:
const destroy = await channel.delete();

![IMG_A35FDAA10BBD-1](https://user-images.githubusercontent.com/68898532/101117074-340cb200-3621-11eb-89d4-1215157e160c.jpeg)

Please advise on how to delete a channel without restoring old messages! Thanks

gz#7761

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/7761'>Zendesk ticket #7761</a>:<br><br>Hi

We would like to know how is the new conversation started? A video would be helpful.
Also, can we please know the version of stream-chat and stream-chat-react-native? Thanks.

FYI, If you delete a channel and try to recreate it, all the older messages will not be restored.

Cheers
Seetha

**Comment by LevanIlashvili** [comment]
@isabellaskc, you can use `truncate` method, which will remove all messages and then use `delete` 

Source: https://getstream.io/chat/docs/channel_delete/?language=js#truncating-a-channel

**Comment by vishalnarkhede** [comment]
@isabellaskc As mentioned @LevanIlashvili , you should truncate the channel before deleting in this case :)
