### ISSUE TITLE
How to take the blue dot component rendered on the right bottom corner in MessageList off

### ISSUE THREAD

**Issue by rodrigowpl** [GetStream/stream-chat-react-native#448]
**Describe the bug**
I was not able to figure out how to take off this blue dot in the corner (see print). Could you please help me?

Sorry to ask this here, but I did not find any reference on the doc and cookbook. Maybe  I've missed it. Appreciate your help!

**Dev environment info (please complete/provide the following information):**

- stream-chat-react-native version: 1.3.4
- react-native version: 0.63.2
- Tried several devices: Iphone XR, Iphone 7, 7 plus and android moto z

**To Reproduce**

Just follow the get started tutorial. This blue dot will appear in that default `MessageList`

**Expected behavior**
Just be able to take this blue component dot off

**Additional context**
No additional context. From my understanding, this blue dot component render in the default `MessageList`

**Screenshots**
This blue dot there on the right bottom corner:
![image](https://user-images.githubusercontent.com/18172307/101540800-4c613180-397f-11eb-9146-4a72ed03662f.png)

**Comment by virdesai** [comment]
@rodrigowpl For the messages you do not want to show the MessageAvatar, pass this `showAvatar` prop in as `false` to a customized `Message` component within the `MessageList`

**Comment by rodrigowpl** [comment]
@virdesai but is not about avatar right?, is about this dot here:
![image](https://user-images.githubusercontent.com/18172307/101547927-ceeeee80-3989-11eb-9198-45a6a7287f05.png)

**Comment by vishalnarkhede** [comment]
@rodrigowpl this should help :)
```js
<Channel Message={props => (
    <MessageSimple
        {...props}
        MessageStatus={() => null}
    />
)}
```

**Comment by rodrigowpl** [comment]
thank you @vishalnarkhede ! Is that what I was looking for
