### ISSUE TITLE
After some time using/talking the messages state stop to auto-refresh in MessageList

### ISSUE THREAD

**Issue by rodrigowpl** [GetStream/stream-chat-react-native#451]
**Describe the bug**
One issue starts to happen after some time connected (like some minutes) or totally periodic: 
- Messages simply stop to auto-increment automatically in the `MessageList` component

I've attached my code in the **To Reproduce** section.

**Dev environment info (please complete/provide the following information):**

- stream-chat-react-native version: 2.1.0
- react-native version: 0.63.2
- Tried several devices: Iphone XR, Iphone 7, 7 plus and android moto z

**To Reproduce**
- I basically have an app if tabs and one of them is the chat. 
- I and another user on another device start talking. 
- Everything works fine by then...
- And then out of the blue, navigating in the app, entering and leaving, and chat tab screen the messages state stop auto-refreshing. **I'm not even minimizing or quitting the app, this start to happen when I'm currently using...**

Here is a gist code example how is my approach, I basically have a global provider to store the stream chat instance. And the channel is initialized when the user enters in tab chat screen (where this chat component example is used).
https://gist.github.com/rodrigowpl/c7b10c64ff949686321c37fcd1d5e02f

**Expected behavior**
Messages auto-increment automatically.

**Additional context**
How can I make sure that this won't happen? Is there some way to do it manually or maybe some logs do track it? I'm really worried because this solution is expensive(I have a paid plan, so the connection limit is not a problem really) and we have here some important players depending on it. I really appreciate your support on this! Thank you in advance.

Edit: Just messages stop to auto-increment automatically. Unread events seem fine. 
It seems a state management issue. Is there a way to update manually using events?

gz#7977

**Comment by rodrigowpl** [comment]
@vishalnarkhede I saw in the docs we have [events](https://getstream.io/chat/docs/event_object/?language=js). Maybe is there a way to update messages state manually listen to `message.new`?

**Comment by rodrigowpl** [comment]
Another update: Trying debugging and looking for other alternatives and I've realized that channel events like `message.new` are stopping being received (the cause of the issue here). 

Any idea?

**Comment by vishalnarkhede** [comment]
@rodrigowpl Are you still facing this issue? Because we had an incident few days ago, and it caused some issues with websocket events. But it was fixed later - https://status.getstream.io/incidents/5b78zhwzpm9p

**Comment by rodrigowpl** [comment]
@vishalnarkhede and still facing. Just testing more I've realized that when I keep the chat screen opened everything keep working normally. The channel events stop listen to when the screen is unmounted and mounted (where channel is initialized)

**Comment by rodrigowpl** [comment]
Update: I've also tried to change the approach and move `setupChannel` to the same global provider and initialize only once. Since we just have one-to-one's conversation in our app we only need one channel always. 

But anyway I got the same result in the same scenario reproduced. It's seem a `Chat` or `MessageList` state issue when it's re-rendered maybe

**Comment by vishalnarkhede** [comment]
Hey @rodrigowpl thanks for the response. I am looking into your code now, I will get back soon :)

**Comment by vishalnarkhede** [comment]
@rodrigowpl could you please try following hook, and check if this fixes the issue for you?

```diff
  useEffect(() => {
    const setupChannel = async () => {
      const _channel = streamChatClient.channel('messaging', {
        members: [userData.uid.toString(), partnerData.partnerId.toString()],
      });

+      await _channel.watch()

      setChannel(_channel);
    };

    setupChannel();
  }, [streamChatClient]);
```

**Comment by 6ewis** [comment]
@rodrigowpl should you also have `await setChannel(_channel)` ?

**Comment by vishalnarkhede** [comment]
@6ewis no!!

**Comment by 6ewis** [comment]
@vishalnarkhede i see. Can you explain a bit about how channel.watch() works internally?

**Comment by rodrigowpl** [comment]
@vishalnarkhede yes I've already tried it. Same result

**Comment by vishalnarkhede** [comment]
@rodrigowpl Can you please try one more thing?

```js
  useEffect(() => {
    const setupChannel = async () => {
      const _channel = streamChatClient.channel('messaging', {
        members: [userData.uid.toString(), partnerData.partnerId.toString()],
      });

+      await _channel.watch()
+      streamChatClient.activeChannels[_channel.cid] = _channel;

      setChannel(_channel);
    };

    setupChannel();
  }, [streamChatClient]);
```

**Comment by rodrigowpl** [comment]
sure, testing here and I will let you know

**Comment by vishalnarkhede** [comment]
@rodrigowpl I have updated code above a little :)

**Comment by rodrigowpl** [comment]
ok testing and let you know, thanks!

**Comment by rodrigowpl** [comment]
@vishalnarkhede for now good news, by doing your last suggestion there I'm not able to reproduce the issue anymore! 
I will keep testing today afternoon but for now, everything is working normally.

If you don't mind could you please explain what your suggestion change?

**Comment by vishalnarkhede** [comment]
Hey @rodrigowpl 

Pardon me for delayed response. This could be a possible bug with our underlying js client (stream-chat-js). Although when you watch the channel, we add the channel to list of activeChannels list automatically. Its not yet clear to me, why it didn't work for your case. This is something I need to investigate in deeper. Hopefully I will do it this week and get you more explanation or a OOTB fix for this.

**Comment by rodrigowpl** [comment]
Hi @vishalnarkhede 

Maybe this can be related:

As I've said the original issue solved using your solution. But sometimes after the app, sometimes stays minimized the WS is losing the connection and is not recovered stopping to auto-refresh the message list.

**This only happens if keep the chat open(The channel component). If navigate away and open it again (unmount and mount the Channel component) the auto-refresh back to work normally.**

Once again:

I know that handle a chat logic, WS connections are tricky! What I'm suggesting is you need to provide a fallback to recover and get the messages list updated. Unfortunately currently is not trustable and we need a way to do it on our side manually. 

Suggestions?

**Comment by vishalnarkhede** [comment]
Hey @rodrigowpl could you please try this? https://github.com/GetStream/stream-chat-react-native/wiki/Cookbook-(2.x.x)#caveats

**Comment by rodrigowpl** [comment]
Thanks @vishalnarkhede tested and it's working.

We can close this issue. But I would kindly suggest to put this more clear in your documentation. Thanks!

**Comment by vishalnarkhede** [comment]
Thanks for the feedback @rodrigowpl :)
