### ISSUE TITLE
Push notification stop to being sent after some time

### ISSUE THREAD

**Issue by rodrigowpl** [GetStream/stream-chat-react-native#452]
**Describe the bug**
Push notification is configured and I've seemed working. But totally out of the blue stop being sent. 
Look at the logs:
![image](https://user-images.githubusercontent.com/18172307/101908108-5317c080-3b9a-11eb-9521-f4b1829777b9.png)

The setup really works, but after some time just stop sending them and nothing appears in the logs anymore.

I've attached my code in the **To Reproduce** section.

**Dev environment info (please complete/provide the following information):**

- stream-chat-react-native version: 2.1.0
- react-native version: 0.63.2
- Tried several devices: Iphone XR, Iphone 7, 7 plus and android moto z

**To Reproduce**

Just follow the same logic shown in the docs. Here is a gist code example how is my approach: 
https://gist.github.com/rodrigowpl/c7b10c64ff949686321c37fcd1d5e02f

**Expected behavior**
Push notifications don't stop sending out of the blue and no errors. Is that another way to implement that? For example, integrate with `OneSignal`?. I'm not confident that APN works well, maybe he is the problem.

gz#7977

**Comment by vishalnarkhede** [comment]
Hey @rodrigowpl we are in process of fixing this issue. I will update you once its fixed :)

**Comment by rodrigowpl** [comment]
Thank you @vishalnarkhede 

I know it's hard to ask that. But we are very close to release our beta version. So do you have an estimate for this? Just more or less to have an idea

**Comment by 6ewis** [comment]
@vishalnarkhede I second what @rodrigowpl said.

**Comment by vishalnarkhede** [comment]
@6ewis @rodrigowpl Can you please test the push notification issue now? We have deployed the fix!! I would recommend clearing app cache on test device

**Comment by rodrigowpl** [comment]
@vishalnarkhede do I need to update some dependency?

**Comment by vishalnarkhede** [comment]
@rodrigowpl No!! Fix was on backend side

**Comment by rodrigowpl** [comment]
great gimme some time to test it and I will let you know, thanks!

**Comment by rodrigowpl** [comment]
@vishalnarkhede it started worked again, but it was temportately and the stop to work again

**Comment by rodrigowpl** [comment]
@vishalnarkhede here is the logs:
![image](https://user-images.githubusercontent.com/18172307/102210759-6041f180-3eb1-11eb-8388-da57aebb34dc.png)

As you can see, it seems after you said it was fixed the pushes started triggering successfully again for some time. But then it stopped and now it does not work anymore

**Comment by vishalnarkhede** [comment]
@ferhatelmas ^^

**Comment by ferhatelmas** [comment]
@rodrigowpl can I get an apikey to investigate ?

**Comment by rodrigowpl** [comment]
@ferhatelmas send me your email so that I can send you

**Comment by ferhatelmas** [comment]
@rodrigowpl apikey is public information. However, it seems support is scheduling a call to debug it with you in realtime.

**Comment by rodrigowpl** [comment]
ok @ferhatelmas thanks, anyway the api key is: `bm8d5vnntp8x`

**Comment by ferhatelmas** [comment]
@rodrigowpl one thing to note is that if you expect to use dev endpoint, mark development: true in app config. Otherwise, devices will be marked as disabled.

**Comment by rodrigowpl** [comment]
I see. But anyway I've tested both in both ways, prod and dev

**Comment by ferhatelmas** [comment]
Sure but the order matters. If device is disabled, you need to readd it to clear disabled field. Otherwise it will stay disabled and won't be tried to send pushes and no log will be generated in dashboard. Since you don't see any logs, it looks likely.

**Comment by rodrigowpl** [comment]
@vishalnarkhede @ferhatelmas it seems started worked now, the p8 approach worked.

But I've realized another issue quite relevant. Currently, regarding receiving pushes I see two issues:

1 -  If I have the Channel component opened and the app minimized, the client understands I'm still online and it does not send a push. This might confuse the user. We can't require him to navigate away from the channel component to receiving a push.

2 - If I have the Channel component opened and the app minimized,  and then press the notification message, the message list is not refreshing because the state is not updated. Any ideas on how can I elaborate an approach for this?

Any idea? Thanks.

**Comment by vishalnarkhede** [comment]
@rodrigowpl Please check this section - https://github.com/GetStream/stream-chat-react-native/wiki/Cookbook-(2.x.x)#caveats

**Comment by rodrigowpl** [comment]
@ferhatelmas @vishalnarkhede The push notifications still seems unstable. It was working, for instance, yesterday and now it's not. And the weird thing is not all devices are receiving it. For ex: I'm talking to someone 1-1 chat, the other guy is receiving but I'm not.

Could you please check your internal logs? I'm not seeing anything in my side

**Comment by rodrigowpl** [comment]
@ferhatelmas @vishalnarkhede 

After our last call, we've tried some implementation details. But without success.

Here is my final feedback:

**StreamChat** is the better chat API I've ever seen, it works pretty well.

But unfortunately StreamChat API is not **reliable** for **push notifications**.
Is not possible to understand why some devices receive and some not. There's no log. Nothing.

Maybe could exist a fix or workaround on my side, but there’s no guarantee, no idea how I could do that since your documentation and existing example is not clear and doesn’t represent “the real-life”. 

Please provide a real example of working. I would appreciate it. 

Thanks!

**Comment by vishalnarkhede** [comment]
@rodrigowpl I am setting up an example now, to reflect the scenario of real-life application.

**Comment by 6ewis** [comment]
@vishalnarkhede when will the working example be available?

**Comment by vishalnarkhede** [comment]
Hey @6ewis @rodrigowpl It will be ready by end of week.

**Comment by 6ewis** [comment]
@vishalnarkhede any update on this one please?

**Comment by vishalnarkhede** [comment]
Hey @6ewis @rodrigowpl Due to ongoing projects, I couldn't yet do much progress on setting up push related resources. Really sorry about that. What I want to do is not just setup an example, but cover some production-app scenarios as @rodrigowpl mentioned and improve the docs around push to avoid the issues that you had in future. So this will need to wait another week. 

But I can imagine urgency on this, so I think we can just arrange another call and go through the push implementation again on Tuesday or Wednesday. Will that work for you?

**Comment by vishalnarkhede** [comment]
https://getstream.io/chat/docs/sdk/reactnative/guides/push-notifications/
