### ISSUE TITLE
App custom theme from styled-components gets mixed with the lib theme

### ISSUE THREAD

**Issue by XavierJ03** [GetStream/stream-chat-react-native#461]
**Describe the bug**
The app theme from `styled-components` can be mixed with the one used is the library component

**Dev environment info (please complete/provide the following information):**

- Package version -> stream-chat-react-native@^2.1.0
- react-native -> 0.63.2
- Device/Emulator -> iPhone 12 Pro Max 14.3

**To Reproduce**

1. [Create a fresh react native app](https://reactnative.dev/blog/2017/03/13/introducing-create-react-native-app)
2. Theme the new app with a custom theme using `styled-components` [doc](https://styled-components.com/docs/advanced#theming)
```javascript
const theme = {
  main: "mediumseagreen"
};

<ThemeProvider theme={theme}>
  // ... The app content
</ThemeProvider>
```
3. The new theme generated will be propagated to `stream-chat` components, so you'll have this error:
![Simulator Screen Shot - iPhone 12 Pro Max - 2020-12-20 at 18 40 30](https://user-images.githubusercontent.com/9474388/102727700-30ea1500-42f5-11eb-8863-ac9014b95032.png)

This error is generated because the app theme does not have `messageInput.container` property

4. Passing style prop to `Chat` component still seem to work since I also got this issue while following the tutorial:
![Simulator Screen Shot - iPhone 12 Pro Max - 2020-12-20 at 18 58 04](https://user-images.githubusercontent.com/9474388/102727723-642ca400-42f5-11eb-894c-48e775f4b935.png)

**Expected behavior**
Was expecting to get a message thread view as mentioned in the first section of the tutorial:
```javascript

import React from "react";
import { View, SafeAreaView } from "react-native";
import { StreamChat } from "stream-chat";
import {
    Chat,
    Channel,
    MessageList,
    MessageInput,
} from "stream-chat-expo";

const chatClient = new StreamChat('b8rx9j3vp24q');
const userToken =
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoib2xkLW1hdGgtMSJ9.vZbqNe8ZrzzITZlsoDqmU8nqRJPqyqmwp-ldUcrtWaQ';

const user = {
    id: 'old-math-1',
    name: 'Old math',
    image:
    'https://getstream.io/random_png/?id=old-math-1&amp;name=Old+math',
};

chatClient.setUser(user, userToken);
const channel = chatClient.channel("messaging", "curly-cake-8");

const ChannelScreen = React.memo(({ navigation }) => {
    return (
    <SafeAreaView>
        <Chat client={chatClient}>
        {/* Setting keyboardVerticalOffset as 0, since we don't have any header yet */}
        <Channel channel={channel} keyboardVerticalOffset={0}>
            <View style={{ flex: 1 }}>
            <MessageList />
            <MessageInput />
            </View>
        </Channel>
        </Chat>
    </SafeAreaView>
    );
});

export default function App() {
    return (
        <ChannelScreen />
    );
}
```

**Comment by vishalnarkhede** [comment]
@XavierJ03 can you please try following change?

```js
<Chat client={chatClient} style={{}}>
...
</Chat>
```

**Comment by XavierJ03** [comment]
@vishalnarkhede Thank you for your fast reply, unfortunately, the same error gets raised. Is the theme file used by stream-chat available somewhere? Maybe I can just add it to my app theme.

**Comment by XavierJ03** [comment]
Hey @vishalnarkhede , do you have any update on this one? Sorry

**Comment by nhannah** [comment]
Hi @XavierJ03 the `ThemeProvider` from `stream-chat-react-native` is not 1:1 with styled-components provider. Instead we take the provided theme (via the `style` prop) and merge it with ours giving the provided one preference. You can pass the the `style` prop into the `Chat` component and it will provided to the `ThemeProvider` internally for all child components. The [base theme](https://github.com/GetStream/stream-chat-react-native/blob/65d556d68cfd84a6537f524f8a2ab8bfdf138638/src/styles/themeConstants.ts#L327) should be able to be extended with any other keys you choose to provide to the app as well. We are moving away from styled components in the upcoming V2 version and will be just using a context and normal react native style types to provide the same theme functionality just FYI.

It appears to me you are likely importing `ThemeProvider` from `styled-components` directly instead of stream-`chat-react-native`, neither is needed if you wrap the components in `Chat`, but the error looks like it's due to the import being from `styled-components`. If this is not the case please provide me the full file you are seeing the issue with (including the import statements) and I will try to replicate the problem.

**Comment by XavierJ03** [comment]
Hi @nhannah, thank you for your feedback.

I've already wrapped components inside `Chat` and also added `style` prop to `Chat` component. Unfortunately, the same error is happening.
I've also tried to use the [base theme](https://github.com/GetStream/stream-chat-react-native/blob/65d556d68cfd84a6537f524f8a2ab8bfdf138638/src/styles/themeConstants.ts#L327) but it seems like its properties don't get recognized:
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-01-04 at 19 50 59](https://user-images.githubusercontent.com/9474388/103594394-98dc5600-4ec6-11eb-8235-82ebd0741e9f.png)

**Comment by XavierJ03** [comment]
@nhannah 
```javascript
import React from 'react';
import {LogBox, SafeAreaView, Text, TouchableOpacity, View} from 'react-native';
// import {NavigationContainer} from '@react-navigation/native';
// import {createStackNavigator, useHeaderHeight} from '@react-navigation/stack';
import {enableScreens} from 'react-native-screens';
import {StreamChat} from 'stream-chat';
import {
  Chat,
  Channel,
  MessageList,
  MessageInput,
} from 'stream-chat-react-native';

const chatClient = new StreamChat('<to_replace>');
const userToken = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoicGxhaW4tZGFya25lc3MtMSJ9.fbFEA4WYnWXEYp-K5pJikqLWYI_RBG-Jt-44N6guih4';

const user = {
  id: 'plain-darkness-1',
  name: 'Plain darkness',
  image: 'https://getstream.io/random_png/?id=plain-darkness-1&amp;name=Plain+darkness',
};

chatClient.setUser(user, userToken);
const channel = chatClient.channel("messaging", "curly-cake-8");

const ChannelScreen = React.memo(({ navigation }) => (
  <SafeAreaView>
    <Chat client={chatClient} style={{}}>
      {/* Setting keyboardVerticalOffset as 0, since we don't have any header yet */}
      <Channel channel={channel} keyboardVerticalOffset={0}>
        <View style={{ flex: 1 }}>
          <MessageList />
          <MessageInput />
        </View>
      </Channel>
    </Chat>
  </SafeAreaView>
));

export default ChannelScreen;
```

**Comment by XavierJ03** [comment]
@nhannah @vishalnarkhede` By digging further in the library, this is what I found.
In `ThemeContext.tsx` L19, the theme generated by `useTheme` misses some required properties like messageInput.
```javascript
  const theme = useTheme();
  const modifiedTheme = theme || defaultTheme;
```

By using defaultTheme directly, the errors mentioned before get cleared.

**Comment by josemak25** [comment]
@XavierJ03 

By using the default theme directly from the package file could lead to potential errors for new engineers when they try starting up the code on their machines.
A quick fix for this would be to extend stream-chat typings, for our infrastructure this is what we did to solve this issue

```javascript
// create a theme folder and touch a types.ts file and add the following code below (in your case your theme)

import { defaultTheme as streamChatTheme, Theme } from 'stream-chat-expo';

// All app colors
enum COLORS {
  // START OF STREAM COLORS
  light = '#EBEBEB',
  danger = '#EDD8DD',
  secondary = '#111',
  textLight = 'white',
  primary = '#006cff',
  textDark = 'rgba(0,0,0,1)',
  textGrey = 'rgba(0,0,0,0.5)',
  transparent = 'transparent',
  // END OF STREAM COLORS

 // START OF OUR APP DEFINED COLORS
  ONLINE = '#7ED321',
  WARNING = '#F6A609',
  PRIMARY = '#718CFB',
  // END OF OUR APP DEFINED COLORS
}

// All app font sizes
enum FONTS {
  // START OF OUR APP DEFINED FONTS
  SMALL_SIZE = 8,
  MEDIUM_SIZE = 12,
  LARGE_SIZE = 16,
  // END OF OUR APP DEFINED FONTS
}

declare module 'styled-components/native' {
  export interface DefaultTheme extends Theme {
    // All Global App Colors
    colors: {
      // START OF STREAM COLORS
      light: string;
      danger: string;
      primary: string;
      textDark: string;
      textGrey: string;
      textLight: string;
      secondary: string;
      transparent: string;
      // END OF STREAM COLORS

      ONLINE: string;
      WARNING: string;
      PRIMARY: string;
    };

    // All Global App Font Sizes
    fonts: {
      SMALL_SIZE: number;
      MEDIUM_SIZE: number;
      LARGE_SIZE: number;
    };
  }
}

// App theme
export const styledComponentTheme = {
  ...streamChatTheme,
  colors: COLORS,
  fonts: FONTS
};
```

```javascript
// then touch an index.tsx file and add the following code below

import React, { FunctionComponent, useContext } from 'react';
import {
  ThemeProvider as Provider,
  ThemeContext
} from 'styled-components/native';

import { styledComponentTheme } from './types';

const ThemeProvider: FunctionComponent = ({ children }) => {
  return (
      <Provider theme={styledComponentTheme}>{children}</Provider>
  );
};

export const useThemeContext = () => useContext(ThemeContext);

export default ThemeProvider;

```

```javascript
// then import and wrap your app navigation with the custom theme provider, as we did ours

import React from 'react';
import { RootToaster } from './components/rootToaster';
import { Host as PortalHost } from 'react-native-portalize';
import { SafeAreaProvider } from 'react-native-safe-area-context';
import GlobalErrorBoundary from './libs/error';
import { StatusBar } from 'expo-status-bar';
import ApolloProvider from './graphql';
import StreamProvider from './stream';
// ❗important note, import this file 👍
import ThemeProvider from './theme';
import Router from './router';

export default function AppRouter() {
  return (
    <GlobalErrorBoundary>
      <ApolloProvider>
        <SafeAreaProvider>
          <ThemeProvider>
            <StreamProvider>
              <StatusBar translucent animated style="dark" />
              <RootToaster />
              <PortalHost>
                <Router />
              </PortalHost>
            </StreamProvider>
          </ThemeProvider>
        </SafeAreaProvider>
      </ApolloProvider>
    </GlobalErrorBoundary>
  );
}

```

**Comment by XavierJ03** [comment]
Thank you for your feedback @josemak25, I don't clearly understand how this change would solve the issue. By the way, I'm not using expo nor typescript.

> By using the default theme directly from the package file could lead to potential errors for new engineers when they try starting up the code on their machines.

Got it! A quick fix would be to understand why the theme retrieved from `useTheme` lacks properties such as `messageInput.`

**Comment by XavierJ03** [comment]
> @nhannah @vishalnarkhede By digging further in the library, this is what I found.
> In `ThemeContext.tsx` L19, the theme generated by `useTheme` misses some required properties like messageInput.
> 
> ```js
>   const theme = useTheme();
>   const modifiedTheme = theme || defaultTheme;
> ```
> 
> By using defaultTheme directly, the errors mentioned before get cleared.

@nhannah @vishalnarkhede @josemak25 Do you have a fix for this issue, I can also request a PR.

**Comment by vishalnarkhede** [comment]
@XavierJ03 Will get back soon on this :)
