### ISSUE TITLE
Getting `message failed` on uploading more than 10 images

### ISSUE THREAD

**Issue by mayuri-pansuriya** [GetStream/stream-chat-react-native#467]
When uploading more than 10 images it just fails and return `message failed` how can we handle this smoothly.

gz#8241

**Comment by vishalnarkhede** [comment]
@mayuri-pansuriya Sorry for delays, do you still need help with this? If yes, could you please give versions of following packages you are using

- stream-chat-react-native
- stream-chat

**Comment by vishalnarkhede** [comment]
Please reopen if you still need help here :)
