### ISSUE TITLE
Possible incoming chat conversation bug

### ISSUE THREAD

**Issue by isabellaskc** [GetStream/stream-chat-react-native#473]
**Describe the bug**

When user1 is in a specific conversation ( with user2 ) and user2 sends a message to user1. User1 receives the message sent from user 2, upon receiving a notification, user1 gets redirected to the channelList screen. ( No action was made to be redirected to the screen ). Possible data loss?

Chat conversation gets updated before the user receives the notification, upon receiving the notification the redirection happen. (Notification not tapped)

Furthermore, it seems that even without messages being sent, by staying on the chat conversation screen, after a period of time, it automatically redirects the user to the channelList screen.

**Dev environment info (please complete/provide the following information):**

    "stream-chat": "2.6.0",
    "stream-chat-expo": "^2.1.0",
    "expo": "^39.0.0",
    iPhone X iOS 13.6.1

**Expected behavior**

When an incoming message comes in from user 2, user1 should see the message sent from user2. Upon receiving a notification on the sent message, user1 screen should remain in the specific conversation screen and not be redirected to the channelList screen

gz#8360

**Comment by vishalnarkhede** [comment]
Hey @isabellaskc ,

Could you please share some screen recording to demonstrate the issue. Its quite unclear to me from the description.

**Comment by isabellaskc** [comment]
Hi @vishalnarkhede ,

A video has been attached here. Please ignore the screen recording alert as it also happen when the screen is not recording.

https://user-images.githubusercontent.com/68898532/103629797-bb7c7680-4f7b-11eb-966c-784bc474de05.mp4

Extra detail:
The conversation updates nicely, notification comes in slightly later, after the notification comes in, almost immediately it redirects to the chatList screen

**Comment by isabellaskc** [comment]
Hi @vishalnarkhede ,

Is there any update on this?

**Comment by isabellaskc** [comment]
Hi? Is the video helpful? Were you able to get the gist of the mentioned issue?

@vishalnarkhede

**Comment by vishalnarkhede** [comment]
Hey @isabellaskc , sorry for the delays. Do you still need help with this?

**Comment by isabellaskc** [comment]
@vishalnarkhede I no longer need help with this. Thank you

**Comment by tpedersen123** [comment]
@isabellaskc I have a similar issue on an app I am building with Stream chat. 
Is it possible to connect to share some knowledge about this?
