### ISSUE TITLE
last_active Time inconsistency

### ISSUE THREAD

**Issue by damithsynapsys** [GetStream/stream-chat-react-native#480]
I'm having an issue with inconsistency. herewith have a use case :

User A is showing "5 mins back" to User B and we stop the application on user B and then start the application on user A send a message and stop it, it should show "few seconds or 1 min" back on user B but it shows "6 mins" back which means user A did not update the information to the server correctly, to reverify it we checked on server and it was not updated.

Dev environment info:
"react": "16.13.1",
"react-native": "0.63.4",
"stream-chat": "^2.8.0",
"stream-chat-react-native": "^2.1.1",

and it's not device issue because it's happening time to time on ios, android, ios simulator. 

I saw a similar issue reported on the flutter also
[Issue No: 50](https://github.com/GetStream/stream-chat-flutter/issues/50)

gz#8497

**Comment by shodgetts** [comment]
Agent comment from Stephen Hodgetts in <a href='https://getstream.zendesk.com/agent/tickets/8497'>Zendesk ticket #8497</a>:<br><br>Hello, this is related to our online presence which updates every 15 minutes internally. We have plans on our product roadmap to improve online presence in Q1 of this year, so we will try to address these sort of problems.

**Comment by vishalnarkhede** [comment]
Closing this issue for now!!
