### ISSUE TITLE
download image attachments

### ISSUE THREAD

**Issue by lokewk** [GetStream/stream-chat-react-native#484]
We noticed there is no function to download image attachment.
if there is, we may have over looked it.
Please advise.

gz#8559

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/8559'>Zendesk ticket #8559</a>:<br><br>Hi

Thanks for reaching out to us.
We will get back to you soon.

Cheers
Stream Team

**Comment by vishalnarkhede** [comment]
@lokewk Unfortunately we don't have image download functionality. So far we were dependent on this external library for image viewer - https://github.com/ascoders/react-native-image-viewer#readme

Last time I checked, `saveToLocalByLongPress ` prop on this component didn't work properly, so we kept this feature disabled - https://github.com/GetStream/stream-chat-react-native/blob/master/src/components/Attachment/Gallery.tsx#L194

We are current in process of releasing v3.0.0 of stream-chat-react-native, where we have our own image viewer and also added download image functionality there. It should be released at the end of this month.

**Comment by shodgetts** [comment]
Agent comment from Vishal Narkhede in <a href='https://getstream.zendesk.com/agent/tickets/8559'>Zendesk ticket #8559</a>:<br><br>Hey ,

I am going to go ahead and close this ticket for now. Please let us know if you have any more questions.

Thanks,
vishal

**Comment by tao-qian** [comment]
Hi! Are there any updates on this feature? It seems like you guys have moved off [react-native-image-viewer](https://github.com/ascoders/react-native-image-viewer), so I wonder what the best way to support this now?
