### ISSUE TITLE
How to send custom push notification template with custom title based on some if statement

### ISSUE THREAD

**Issue by rodrigowpl** [GetStream/stream-chat-react-native#489]
First of all, really sorry to break your PR template but I think it is for a good reason and it will also help others

I'm checking your docs related to push templates
https://getstream.io/chat/docs/push_template/?language=js

And I see you have support to if/else statements. But can you please provide more examples of how this works?

Let me show you one edge case that I need:

I need to send a customized push `title` to send a custom text based on a boolean value that lives where I send the message, let's see:

Seeding the message from server side like this:
```
 await channel.sendMessage({
       id: new Date().getTime().toString(),
       user: '...',
       html: '...',
       promptMessage: true // custom flag
   })
```

are you seeing that `// custom flag` there? I do need to catch it where I setup the push template in the panel, is that possible?

example:
```

{
    "aps" : {
        "alert" : {
            "title" : "IF message.promptMessage "SEND THIS TITLE" else  "SEND THAT TITLE"", // LOOK HERE
            "body" : "{{ message.text }}"
        },
        "badge": {{ unread_count }},
        "category" : "NEW_MESSAGE"
    }
}
```

Thanks in advance! 

gz#8684

**Comment by ferhatelmas** [comment]
dup

**Comment by ferhatelmas** [comment]
For the sake documentation, `{{#if message.promptMessage}}send X{{else}}send Y{{/if}}` because custom fields are accessible in the push context,

**Comment by ferhatelmas** [comment]
By the way, it seems you use time as id such that `id: new Date().getTime().toString()`. I suggest not doing it because time isn't trustful in distributed systems. If you don't have a good scheme to generate ids, let the server generate for you.

**Comment by rodrigowpl** [comment]
thanks @ferhatelmas
