### ISSUE TITLE
Double brackets break creating an empty bubble when entering the chat

### ISSUE THREAD

**Issue by Matti93GL** [GetStream/stream-chat-react-native#498]
**Describe the bug**
When a message is sent with [][] regardless of the content that is put into it, when it is sent an empty bubble is seen inside the chat

**Dev environment info 

- Package version `"stream-chat-react-native": "^2.1.0",`
- `"react-native": "0.62.2",`
- IOS and Android

**To Reproduce**

1. Enter to the chat
2. Write a message with [][]
3. Send the message

**Expected behavior**
the message looks correct

**Aditional**
The original text was copy from Wikipedia, `After the successful self-titled album released in 1987, which included one of Chayanne’s signature songs, “Fiesta en América”, a track that peaked at number 4 in the Billboard Hot Latin Tracks chart and also ranked 49th in the 2008 recap for the ’100 Greatest Songs of the 80’s in Spanish’ by VH1 Latin America,[2][3] the singer recorded in 1988 his second self-titled album under the Sony record label. The following year, Chayanne signed a contract with Pepsi to record the first Spanish language commercial aired in the United States on a major TV network without subtitles or dubbing, debuted during the Grammy Awards that year.[4] Chayanne received a Grammy Award nomination for Best Latin Pop Performance, which it lost to José Feliciano’s rendition of “Cielito Lindo”.[4][5] During this year, the singer also won the Lo Nuestro Award for Pop Male Artist and the album was nominated for Pop Album of the Year.[6][7] “Este Ritmo Se Baila Así“, the third single from this release, won the MTV Video Music Award in 1989 as the International Viewer’s Choice.[8] The album was re-released 1989 and then in 2000 with the same track list.`, after try to reproduce and see what happend we see that the [][] was the problem

**Screenshots**
![done](https://user-images.githubusercontent.com/62907714/105857153-c2ba0180-5fc8-11eb-8d50-7fd272776709.gif)

gz#8888

**Comment by SeniYG** [comment]
Hi,

Thanks for reaching out. 
Are you using the MessageInput and ChannelList default components?

Best,

**Comment by Matti93GL** [comment]
Hi @SeniYG yes, we are using the defaults

**Comment by Matti93GL** [comment]
@SeniYG the issue happend on the stream-chat-react-native expo example too

**Comment by vishalnarkhede** [comment]
@Matti93GL This has been fixed in `v2.1.3`
