### ISSUE TITLE
How can I disable "searching people" (Mention) in the Message Input?

### ISSUE THREAD

**Issue by rodrigowpl** [GetStream/stream-chat-react-native#500]
How can I disable this?
![image](https://user-images.githubusercontent.com/18172307/106074876-63084700-60eb-11eb-83dd-081820288ae8.png)

I don't want to appear that box when type '@'

Thanks!

gz#8939

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/8939'>Zendesk ticket #8939</a>:<br><br>Hi

Thanks for reaching out to us.
We will check this and come back to you.

Cheers
Stream Team

**Comment by vishalnarkhede** [comment]
@rodrigowpl Do you only want to turn off mentions, or commands as well?

**Comment by 6ewis** [comment]
@vishalnarkhede how to turn off mentions, and/or commands?

**Comment by rodrigowpl** [comment]
both @vishalnarkhede

**Comment by vishalnarkhede** [comment]
Hey @rodrigowpl , you will need to add a custom `Input` component on `MessageInput` and disable `triggerSetting` prop

```js
<MessageInput Input={(props) => {
    return (
        <>
            <AttachButton {...props}/>
            <AutoCompleteInput {...props} triggerSettings={{}} />
            <SendButton {...props}/>
        </>
    )
}} />
```

**Comment by vishalnarkhede** [comment]
@rodrigowpl Let me know if that works for you!!

**Comment by rodrigowpl** [comment]
@vishalnarkhede it worked! Thanks.

Suggestion to put this in your cookbook. Things like that are really hard to figure in your component reference docs :D 

Thanks for your help!

**Comment by vishalnarkhede** [comment]
Thanks @rodrigowpl , added to cookbook, for other's benefit ;)
