### ISSUE TITLE
Support offline mode

### ISSUE THREAD

**Issue by EJohnF** [GetStream/stream-chat-react-native#51]
I don't see it in the docs, but maybe you have some caching and offline support? 
So that once user loaded messages, he can access(see) them later without an internet connection?

I know that it's possible to do using such tools as Redux or Apollo. But I wonder might be there is support for that out of the box. Thanks!

**Comment by vishalnarkhede** [comment]
Hey @EJohnF,

Thanks for reaching out to us. Currently we don't have offline support OOTB. Its currently in pipeline, and will be available in future, although I can't really give any timeline about it.

**Comment by tbarbugli** [comment]
re-opening this so that people can +1 / subscribe to this for updates

**Comment by aleplusplus** [comment]
Any update on this?

**Comment by virdesai** [comment]
we're working to make this happen sometime in Q1

**Comment by vishalnarkhede** [comment]
Offline support has been moved to Q2!!

**Comment by nandorojo** [comment]
Is this planned with `AsyncStorage`?

**Comment by sealabcore** [comment]
+1 are you all still planning on a Q2 launch of caching messages and images in the client (offline mode)? Loading channels / messages in a channel / images on slower phone internet connections is quite painful. Thanks in advance! Happy to test a pre-release if available 😄

**Comment by madsroskar** [comment]
Just an update here, we're planning to include offline support in version `4.0.0`, which we expect to release by the end of the month. 🙂

**Comment by thomasyim02** [comment]
> @nandorojo we are going to leave it for users to make a choice on storage library ... mmkv or async-storage or anything else which supports simple get-set key value storage :)

This is exactly what I'm hoping for 💯 nice work!

**Comment by sealabcore** [comment]
> Just an update here, we're planning to include offline support in version `4.0.0`, which we expect to release by the end of the month. 🙂

Really looking forward to 4.0.0 🎉 Any update on release date? A beta branch we can test? Thanks!

**Comment by vishalnarkhede** [comment]
Hey guys!! So due to some technical limitations we had to abandon our development around offline caching layer on RN for stream chat. But we still have plenty of good performance fixes in v4.0.0. And we will plan on implementing offline database support soon.

**Comment by thomasyim02** [comment]
@vishalnarkhede 
Thank you for the update! Any info on the approx. release date for the offline database support? Will it include encryption?

**Comment by linhewinner** [comment]
While this is not supported out of the box, is there any way for me build a local storage layer myself and integrate with stream-chat-react-native?

Any timeline on when official support would be available?

**Comment by buneme** [comment]
Hello @vishalnarkhede , are there any updates on this? And are there any possible work around that we could use in the meantime?

**Comment by ato237** [comment]
Are there any updates for offline support?

**Comment by vishalnarkhede** [comment]
Hey guys, we don't have any solid update on this one yet. But we are re-picking this epic now so probably in a month or so we will have some specific timeline and plan for it.

**Comment by RRaideRR** [comment]
Just checking in a month later: what's the timeline or plan for it?

**Comment by vanGalilea** [comment]
Update: this feature is currently in the making and will be available in alpha prod in a few weeks.
Stay tuned for more info.

**Comment by andreibarabas** [comment]
hi @vanGalilea - any updates on this feature?

**Comment by vanGalilea** [comment]
@andreibarabas yes definitely more info can be found in this [discussion](https://github.com/GetStream/stream-chat-react-native/discussions/1611)

**Comment by andreibarabas** [comment]
Perfect! Will give the beta a try Today 👍

**Comment by vishalnarkhede** [comment]
Please feel free to add a comment on any questions you may have, on gh discussion thread. I am going to close this issue for now :)
