### ISSUE TITLE
UX Bug - styling of "searching people" (Mention) in the Message Input?

### ISSUE THREAD

**Issue by dakshbhardwaj** [GetStream/stream-chat-react-native#510]
How can i change the styling of searching people in Message input ?

<img width="832" alt="Screenshot 2021-02-03 at 10 00 04 PM" src="https://user-images.githubusercontent.com/22423684/106777838-5c3d7f00-666b-11eb-8e75-534c2211bcd4.png">

**Dev environment info

Package version "stream-chat-react-native": "2.1.2",
"react-native": "0.63.2",
IOS and Android

gz#9106

**Comment by vishalnarkhede** [comment]
Hey @dakshbhardwaj what kind of styling you want to do? 

fyi ... we don't promise landscape support on components

**Comment by dakshbhardwaj** [comment]
Hi @vishalnarkhede 

customising the styling of the search people for landscape , so that we can click on the first member.

**Comment by vishalnarkhede** [comment]
@dakshbhardwaj You can use customize the theme object

```js
const theme = {
    'messageInput.suggestions.container': 'height: 100px'
}

<Chat style={theme}>
</Chat>
```

**Comment by dakshbhardwaj** [comment]
it worked thanks
