### ISSUE TITLE
Cannot attach photos on Android

### ISSUE THREAD

**Issue by joseponsvega** [GetStream/stream-chat-react-native#511]
**Describe the bug**
Cannot upload photos on Android using stream/expo.

**Dev environment info (please complete/provide the following information):**

"expo": "^40.0.0"
"stream-chat-expo": "2.2.1"
"react": "16.13.1",
"react-native": "https://github.com/expo/react-native/archive/sdk-40.0.0.tar.gz",

Reproduced on:

Google Pixel (Android 10)
Galaxy A20 (Android 10)

**To Reproduce**

1. Implement an app with a `MessageList` and `MessageInput`.
2. Pick a photo from the photo gallery as an attachment.
3. The photo preview shows up in the input for a split second, but then disappears, hence you can't send an image to the chat.

**Expected behavior**
Should be able to send an image.

**Additional context**
Strangely enough, it seems to work fine on Android emulator running Android 10, but not on an actual device. Seems to work on iOS fine.

gz#9119

**Comment by joseponsvega** [comment]
@vishalnarkhede is there any other info that would help with this bug? Thanks!

**Comment by vishalnarkhede** [comment]
Hey @joseponsvega Could you please try to run our [ExpoMessaging](https://github.com/GetStream/stream-chat-react-native#expo-example) app and see if you are still able to reproduce the issue there as well?

**Comment by joseponsvega** [comment]
@vishalnarkhede that seems to work actually.

I did notice that the image picker on that example app is different than what shows up for mine (mine is in the screenshots here):

![Screenshot_20210222-163934](https://user-images.githubusercontent.com/15931897/108788410-bd4ec900-752c-11eb-8e8b-9d1110a0cc32.png)
![Screenshot_20210222-163929](https://user-images.githubusercontent.com/15931897/108788412-bf188c80-752c-11eb-8f55-1faab1ba9838.png)

**Comment by vishalnarkhede** [comment]
@joseponsvega Is it possible for you to upgrade to v3 of stream-chat-expo? It might be worth it at this point.
