### ISSUE TITLE
Opening camera NOT gallery

### ISSUE THREAD

**Issue by mikevercoelen** [GetStream/stream-chat-react-native#514]
Clicking the camera icon doesn't open the camera app to make a photo directly, but the gallery.

How do I make this work?

gz#9181

**Comment by XavierJ03** [comment]
Having the same issue, In `MessageInput` props, I receive `_pickImage` and `_pickDocument` but there is no function related to the user camera. We could add a custom behavior for this use case by using `ImagePicker` but we won't be able to display the same image preview that the sdk provides.

**Comment by sergeyzhukov** [comment]
The same issue. It looks like we need to use registerNativeHandlers and use another picker inside to achieve the needed behavior.

**Comment by sergeyzhukov** [comment]
@mikevercoelen 

you can use `uploadNewImage` prop and just use any picker you want. 

`export const AttachButton = memo(({ uploadNewImage }) => {
  const actionSheetRef = React.useRef<ActionSheet>()

  const openActionSheet = () => {
    actionSheetRef.current.show()
  }

  const handleSheetPress = React.useCallback(async index => {
    try {
      if (index === 0) {
        launchCamera({ mediaType: 'photo' }, ({ uri }) => {
          if (uri) {
            uploadNewImage({ uri })
          }
        })
      }
      if (index === 1) {
        launchImageLibrary({ mediaType: 'photo' }, ({ uri }) => {
          if (uri) {
            uploadNewImage({ uri })
          }
        })
      }
    } catch (error) {
      console.error(error)
    }
  }, [])

  return (
    <TouchableOpacity
      onPress={openActionSheet}
      hitSlop={{
        top: 8,
        left: 16,
        right: 16,
        bottom: 8,
      }}
    >
      <StyledAttachButton>
        <Icon color="#26262EB2" name="picture" />
      </StyledAttachButton>
      <ActionSheet
        ref={actionSheetRef}
        title="Select a Photo"
        options={['Take Photo...', 'Choose from Library...', 'Cancel']}
        cancelButtonIndex={2}
        onPress={handleSheetPress}
      />
    </TouchableOpacity>
  )
})
`

**Comment by vishalnarkhede** [comment]
@sergeyzhukov thanks alot for adding a example here, really appreciate it :) 

I will include this example in cookbook as well

**Comment by vishalnarkhede** [comment]
Also @sergeyzhukov we have quite a new UX and designs for attachment picker in v3 of this SDK - https://github.com/GetStream/stream-chat-react-native/wiki/Cookbook-v3.0#input-and-attachment-picker-components

Just in case if you would like to upgrade :)
