### ISSUE TITLE
Urgent: editing or reacting messages are NOT updated correctly

### ISSUE THREAD

**Issue by mikevercoelen** [GetStream/stream-chat-react-native#519]
Editing / reactions are working fine until the app is hidden, so no longer in focus, and wait for about 1 / 2 minutes and then open the app again and start editing / posting reactions.

The changes ARE being made, but they aren't updated in the UI.

These are the versions I'm on:

```
"stream-chat": "^2.12.0",
"stream-chat-react-native": "^2.2.2",
"react-native": "0.63.4",
```

Here's a video:

https://user-images.githubusercontent.com/3009836/107336082-b028e780-6af3-11eb-9b98-74e722b2820b.mp4

gz#9281

**Comment by mikevercoelen** [comment]
@vishalnarkhede can we please get some feedback? We're paying big bucks for GetStream, and it's crucial for our business that it works correctly.

**Comment by SeniYG** [comment]
Hi @mikevercoelen , sorry for the delay here. Our React-Native developers are kept busy with some pressing issues.
They'll jump here to help you shortly as soon as they can.
Best,

**Comment by mikevercoelen** [comment]
@SeniYG Understood, would be great if you can confirm that this is an issue on your end

**Comment by vishalnarkhede** [comment]
@mikevercoelen I am checking right now :)

**Comment by vishalnarkhede** [comment]
@mikevercoelen Could you please share some code around Chat components?

**Comment by mikevercoelen** [comment]
What exactly?

**Comment by mikevercoelen** [comment]
Got whatsapp: +31611186123

**Comment by vishalnarkhede** [comment]
- How you initiate chat client or channel
- Which components are you using from RN sdk
- Do you have any AppState related implementation
- What kind of custom components are you using etc.

**Comment by vishalnarkhede** [comment]
Basically I just want to replicate the issue that you are referring to!!

**Comment by mikevercoelen** [comment]
I can invite you to our repo, that would prob be easiest

**Comment by vishalnarkhede** [comment]
@mikevercoelen sure :)

**Comment by mikevercoelen** [comment]
Got slack / email / whatsapp to communicate directly, that makes it easier?

**Comment by vishalnarkhede** [comment]
support@getstream.io

**Comment by vishalnarkhede** [comment]
@mikevercoelen  Could you please point me to Chat related functionality in your repository? Or screen where you import components from stream-chat-react-native

**Comment by mikevercoelen** [comment]
Mailed

**Comment by vishalnarkhede** [comment]
Closing this, since conversation moved to other channel!! Please reopen if anyone is facing the same issue
