### ISSUE TITLE
How can i stop sending empty messages? 

### ISSUE THREAD

**Issue by dakshbhardwaj** [GetStream/stream-chat-react-native#520]
How can i stop sending empty messages? 

I have tried by triming the value but thats stop the attachement going on.

![Simulator Screen Shot - iPhone 11 - 2021-02-09 at 20 05 09](https://user-images.githubusercontent.com/22423684/107468802-ae603200-6b8e-11eb-85ae-e88e3e411e8a.png)

gz#9291

**Comment by shodgetts** [comment]
Agent comment from Anders Lund in <a href='https://getstream.zendesk.com/agent/tickets/9291'>Zendesk ticket #9291</a>:<br><br>Hi there,

Can you please send over which version of the SDK you're using?

**Comment by vishalnarkhede** [comment]
@dakshbhardwaj could you please also share code around Stream's chat components?

**Comment by dakshbhardwaj** [comment]
versions , 
"stream-chat": "2.11.1",
"stream-chat-react-native": "2.2.2",
"react-native": "0.63.2"


code around 


 [   <TouchableOpacity
          style={styles.sendButton}
          onPress={() => {
            props.sendMessage && props.sendMessage();
          }}>
          <Image source={sendMessage} />
        </TouchableOpacity>](url)
   
   using the props of messageInput

**Comment by dakshbhardwaj** [comment]
> Agent comment from Anders Lund in [Zendesk ticket #9291](https://getstream.zendesk.com/agent/tickets/9291):
> 
> Hi there,
> 
> Can you please send over which version of the SDK you're using?

ZenDesk link is not working

**Comment by vishalnarkhede** [comment]
@dakshbhardwaj Could you please show code around input box as well?

**Comment by dakshbhardwaj** [comment]
> @dakshbhardwaj Could you please show code around input box as well?

[<View style={styles.container}>
        <View style={styles.leftContainer}>
          <AutoCompleteInput
            {...props}
            additionalTextInputProps={{
              maxLength: maxTextLimit,
              multiline: true,
              style: styles.textInput,
              placeholder: props.placeholder,
              placeholderTextColor: 'rgba(0,60,67,0.6)',
              autoCapitalize: 'sentences',
              autoCorrect: false,
              cursorColor: '#003c43',
              selectionColor: Platform.OS === 'ios' ? '#003c43' : 'rgba(0,60,67,0.3)',
              textAlign: 'left',
            }}
          />
          <View style={styles.iconContainer}>
            <TouchableOpacity onPress={openImage} style={styles.imageAttachmentIcon}>
              <Image source={file} />
            </TouchableOpacity>
          </View>
        </View>

        <TouchableOpacity
          style={styles.sendButton}
          onPress={() => {
            props.sendMessage && props.sendMessage();
          }}>
          <Image source={sendMessage} />
        </TouchableOpacity>
      </View>](url)

**Comment by vishalnarkhede** [comment]
@dakshbhardwaj you can just disable send button, if text is empty

```js
<TouchableOpacity
  disabled={!props.value}
  onPress={...}
/>
```

**Comment by dakshbhardwaj** [comment]
@vishalnarkhede that is stopping the attachement to be send  if  put  the check for props.value

**Comment by krinish291** [comment]
https://github.com/GetStream/stream-chat-react-native/pull/534

**Comment by vishalnarkhede** [comment]
This will be published in next version, early next week :)
