### ISSUE TITLE
initialValue not working as expected in MessageInput component

### ISSUE THREAD

**Issue by jaredpiedt** [GetStream/stream-chat-react-native#522]
**Describe the bug**
When setting `initialValue` prop on the `MessageInput` component, it doesn't populate the input box with the provided text.

**Dev environment info (please complete/provide the following information):**

- stream-chat-expo: `2.2.2`
- expo: `40.0.0`
- iOS 14.2

**To Reproduce**

1. Set `initialValue` prop on `MessageInput` container:
```jsx
<Chat client={chatClient}>
  <Channel channel={channel}>
    <View style={{ flex: 1 }}>
      <MesageList />
      <MessageInput initialValue="hello world" />
    </View>
  </Channel>
</Chat>
```

**Expected behavior**
I expected the message input box to be prepopulated with `hello world`, but it was empty.

gz#9363

**Comment by shodgetts** [comment]
Agent comment from Anders Lund in <a href='https://getstream.zendesk.com/agent/tickets/9363'>Zendesk ticket #9363</a>:<br><br>Hi there,

You'll actually need to customize the autoCompleteInput component to achieve your desired results. I'll link you to that documentation here: https://getstream.github.io/stream-chat-react-native/#autocompleteinput.

**Comment by jaredpiedt** [comment]
@shodgetts will `initialValue` from the `MessageInput` component be propagated through in the `value` prop for `AutoCompleteInput`?

**Comment by vishalnarkhede** [comment]
@jaredpiedt This looks like a bug, is it the first integration of chat in your application? Or are you already using Stream chat in production?

**Comment by jaredpiedt** [comment]
@vishalnarkhede this is the first integration of chat in our application

**Comment by vishalnarkhede** [comment]
@jaredpiedt If you are not too far with chat integration, I would recommend you to upgrade to v3!!

**Comment by vishalnarkhede** [comment]
@jaredpiedt Next minor version will include this fix :)

**Comment by jaredpiedt** [comment]
> @jaredpiedt Next minor version will include this fix :)

@vishalnarkhede 🙌   thank you for the fix and building such an awesome library! We were able to integrate chat into our app in less than a week thanks to Stream and this library.

**Comment by vishalnarkhede** [comment]
Hey @jaredpiedt really glad to hear integration went well :)

Am curious to know which version of `stream-chat-expo` are you using?

**Comment by jaredpiedt** [comment]
@vishalnarkhede we're currently using `2.2.2` but planning to upgrade to v3 when we get the time.
