### ISSUE TITLE
Slowness while sending a new message

### ISSUE THREAD

**Issue by deepesh-kn** [GetStream/stream-chat-react-native#524]
**Describe the bug**
  The following actions take a long time when the items in the message list are large. 
  1. Sending a new message 
  2. Opening of the action sheet on long press

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native/stream-chat-expo)
  stream-chat-react-native: 2.2.2

- react-native or expo version
  React native: 0.63.2

- Device/Emulator (android/ios) and OS version
  OS: Android
  OS Version: 10
  Device Model: CPH1969 (Oppo F11 Pro)

**To Reproduce**

  1. Go to the MessageList page.
  2. Scroll up to load all the messages (should be large enough e.g: 1000 - 2000)
  3. Type a new message and send.
  4. The message gets sent after a 4-5 seconds delay.

**Expected behavior**
  The message should be sent instantly.

**Additional context**
    This log appears in the console.
    `VirtualizedList: You have a large list that is slow to update - make sure your renderItem function renders components that follow React performance best practices like PureComponent, shouldComponentUpdate, etc.`

  This is observed on iOS devices too but from the user perspective, the delay on Android is significant.

**Screenshots**
  NA

I can understand that this is more of an optimization-related thing, but the slowness is observed when we use the default components from the stream SDK. 

gz#9441

**Comment by deepesh-kn** [comment]
@vishalnarkhede , any suggestions?

**Comment by vishalnarkhede** [comment]
@deepesh-kn Could you try to check this issue on `strean-chat-react-native@2.0.2`?

**Comment by deepesh-kn** [comment]
> @deepesh-kn Could you try to check this issue on `strean-chat-react-native@2.0.2`?

@vishalnarkhede , its slow on `strean-chat-react-native@2.0.2` too.

**Comment by vishalnarkhede** [comment]
@deepesh-kn Is this the first implementation for react-native chat? How far are you in integration at this point? Is the chat feature already live in your app?

**Comment by deepesh-kn** [comment]
> @deepesh-kn Is this the first implementation for react-native chat? How far are you in integration at this point? Is the chat feature already live in your app?

Yes, the first version is live, we want to optimize it further.

**Comment by vishalnarkhede** [comment]
@deepesh-kn Would you be interested in upgrading to `[3.0.0-beta.x`](https://github.com/GetStream/stream-chat-react-native/wiki#v300-betax)?

**Comment by deepesh-kn** [comment]
> @deepesh-kn Would you be interested in upgrading to [`3.0.0-beta.x`](https://github.com/GetStream/stream-chat-react-native/wiki#v300-betax)?

Sure, if this will solve the issue we will upgrade it, when will be the stable version released?

**Comment by vishalnarkhede** [comment]
We are already in process of testing this version with few users and been going pretty well. We are planning to publish either rc or stable somewhere by the end of next week.

**Comment by vishalnarkhede** [comment]
Also if you don't mind me asking, are you integrating chat in OpenST product?

**Comment by deepesh-kn** [comment]
> Also if you don't mind me asking, are you integrating chat in OpenST product?

No this is for another project.

**Comment by vishalnarkhede** [comment]
Hey @deepesh-kn we have published v3.0.0. Please feel free to upgrade, we are going to keep it a high priority to help everyone with upgrade :)

**Comment by deepesh-kn** [comment]
> Hey @deepesh-kn we have published v3.0.0. Please feel free to upgrade, we are going to keep it a high priority to help everyone with upgrade :)
> 
> * [Release notes](https://github.com/GetStream/stream-chat-react-native/releases/tag/v3.0.0)
> * [Documentation](https://github.com/GetStream/stream-chat-react-native/wiki)

Thanks, @vishalnarkhede

**Comment by shodgetts** [comment]
Hello, did the upgrade help?

**Comment by deepesh-kn** [comment]
> Hello, did the upgrade help?

@shodgetts , the upgrade is in progress, we have encountered few issues while integrating it, I will raise the tickets and provide the reference here.

**Comment by shodgetts** [comment]
Agent comment from Vishal Narkhede in <a href='https://getstream.zendesk.com/agent/tickets/9441'>Zendesk ticket #9441</a>:<br><br>Hey Deepesh,

I am closing this ticket for now. Please feel free to raise the issues when you are ready. We are soon (today or tomorrow) going to release 3.1.0 of our SDK as well
Changelog for 3.1.0 is here - https://github.com/GetStream/stream-chat-react-native/blob/3ceaaa193443a1003c5cfacece570acb08de5830/CHANGELOG.md#310-unreleased

Thanks,
Vishal
