### ISSUE TITLE
StreamChat.createToken(id) throws `TypeError: Cannot read property 'sign' of null`

### ISSUE THREAD

**Issue by syntax-e** [GetStream/stream-chat-react-native#53]
Repro steps:
1) Create new react native project via react-native init
2) Add stream-chat-react-native per directions on this github repo
3) Create new StreamChat client via `const chatClient = new StreamChat(key, secret)`
4) Call `chatClient.createToken(userId)`

Result:
- Throws `TypeError: Cannot read property 'sign' of null` on line 2848 of `stream-chat/dist/browser.js`
- Debugger shows `jwt` is null in `jwt.sign(payload, apiSecret, opts)`
- It appears `var jwt = null` is declared on line 2831 but is never initialized to anything 

Expected:
- Token is generated without an exception

Note:
- The same exception is thrown when calling `chatClient.devToken(userId)` and subsequently calling `chatClient.setUser({id, name, image})`

```
react-native info
info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
      Memory: 13.37 GB / 32.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.9.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.2, 23.0.3, 24.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.3
        System Images: android-23 | Google APIs ARM EABI v7a, android-23 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.3 => 16.8.6 
      react-native: ^0.59.10 => 0.59.10 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-rename: 2.3.2
```

**Comment by vishalnarkhede** [comment]
Hey @harrisonschwartz,

Client generated using secret key is only meant to be used on serverside.  Seems like you are using it on clientside (on browser or mobile - react-native)

**Comment by vishalnarkhede** [comment]
@syntax-e ping. Any update on this?

**Comment by vishalnarkhede** [comment]
Closing this for now. Please reopen if you have more questions!!

**Comment by theRealSheng** [comment]
@vishalnarkhede how to I obtain the token by creating a user in the stream-CLI?

Thanks in advance!

**Comment by bgeisb** [comment]
## If someone has the same problem:

The following post solved my problem:
https://stackoverflow.com/questions/62054421/how-do-i-enable-devtokens-on-getstream-io

**Comment by thechaudharysab** [comment]
I'm getting `TypeError: null is not an object (evaluating 'jwt.sign')` and it's because of this code:

```
  useEffect(() => {
    const connectStreamUser = async () => {
      try {
        await chatClient.connectUser(
          {
            id: 'talha',
            name: 'Test User'
          }, chatClient.devToken('john'),
        );
      } catch (error) {
        console.log('----------ERROR-----------');
        console.log(err);
      }
    }

    if (!chatClient.userID) {
      console.log('------NO USER ID----------');
      connectStreamUser();
    }
  }, []);
```
Any solution or what I might do differently?
