### ISSUE TITLE
Android: Significant FPS drop when a channel contains five or more images

### ISSUE THREAD

**Issue by junminleeKS** [GetStream/stream-chat-react-native#537]
**Describe the bug**
The UI FPS observed in the Performance Monitor drops significantly when a channel has five or more images on Android. Deleting images to reduce the total number of images back to four or less fixes the issue.

**Dev environment info (please complete/provide the following information):**
- Package version (stream-chat-react-native/stream-chat-expo)
stream-chat-expo: 3.0.0
- react-native or expo version
Expo SDK 40
- Device/Emulator (android/ios) and OS version
Device (Pixel 4a): Android 11

**To Reproduce**

1. Create and navigate to a channel on Android
2. Send a total of five or more images
3. Scroll the message list and/or press on an image to expand it

**Expected behavior**
No FPS issues.

**Additional info**
I believe the issue stems from the ImageGallery component used in the OverlayProvider. Inside ImageGallery.tsx I edited the AnimatedGalleryImage component on line 1154 to the following:
```
                          <AnimatedGalleryImage
                            ...
                            shouldRender={Math.abs(selectedIndex - i) < 1 /* Changed from 4 to 1 */} 
                            ...
                          />
```
This fixed the performance issue for me.

gz#9905

**Comment by vishalnarkhede** [comment]
@junminleeKS do you see drop in FPS when you open the image or in general loading of channel?

**Comment by junminleeKS** [comment]
General loading of the channel. I found that loading a different channel that does not have five or more images will fix the FPS drop.

**Comment by vishalnarkhede** [comment]
@junminleeKS is it possible for you to share some screenrecording?

**Comment by junminleeKS** [comment]
https://youtu.be/izkH-fEoKXo

The video starts before loading the channel that will drop the FPS. After loading the channel with more than five images you will see the FPS drop. I then back out to show that the FPS issue persists outside of the channel. I end by loading a channel that has less than five images which fixes the FPS issue.

**Comment by vishalnarkhede** [comment]
Hey @junminleeKS could you please try upgrading to 3.2.0? We have introduced plenty of performance optimizations around MessageList.

**Comment by junminleeKS** [comment]
Unfortunately I am still experiencing the FPS drop on Android. For full transparency I only upgraded stream-chat-expo from 3.1.0 to 3.2.0 and have done nothing else. I will check to see if I have to make any additional changes but I wanted to report back with the results from only upgrading.

**Comment by vishalnarkhede** [comment]
@junminleeKS we are working on re-rendering optimizations with gallery this week. That should hopefully fix this issue!!

**Comment by nhannah** [comment]
@junminleeKS Also just for clarity is this running on the expo app or a production build? The performance difference is significant in production especially on Android with images on RN.

**Comment by junminleeKS** [comment]
@nhannah I was running it on the expo app. I definitely should have tried using a production build so I apologize.

**Comment by diegobugs** [comment]
@vishalnarkhede @nhannah we are facing the same issue with FPS drop when there are more more than 4 images attached.

I recorded an example video about our app in release mode.
https://drive.google.com/file/d/1yUMjiulUZWlTqdfCB0HvaQfH_VJy-TSC/view?usp=sharing

Our environment info:
React Native:
- Version 0.64.1
- Hermes enabled

Package:
- stream-chat-react-native@3.4.0
- stream-chat@3.9.0

Device:
- Samsung Galaxy S20 (Android 11)

**Comment by junminleeKS** [comment]
Is there any update on the status of this issue? I have not tested any of the newer versions past 3.2.0 but based off of @diegobugs comment I am assuming this issue has not yet been resolved.

**Comment by diegobugs** [comment]
For those having this same issue, I found a workaround.

Passing an empty component like this `() => null` to imageComponent on OverlayProvider fixes the FPS drop.

```js
<OverlayProvider
    imageGalleryCustomComponents={{
        // This line 
        grid: {
            imageComponent: () => null,
        },
    }}>
        <AppNavigation />
</OverlayProvider>
```

I will look into getStream code to try to find the issue and a possible fix.
@vishalnarkhede

**Comment by vishalnarkhede** [comment]
Hey @diegobugs @junminleeKS we are currently in process of addressing this issue. Please keep an eye on next few releases.

**Comment by vishalnarkhede** [comment]
Continuing here - https://github.com/GetStream/stream-chat-react-native/discussions/855
