### ISSUE TITLE
stream-chat-expo: takePhoto issues

### ISSUE THREAD

**Issue by junminleeKS** [GetStream/stream-chat-react-native#538]
**Describe the bug**
Pressing the camera button inside the message input does nothing. Two issues exist on the takePhoto function inside the registerNativeHandlers function in stream-chat-expo that cause this:
1. It uses `ImagePicker.getCameraPermissionAsync()` which means it only checks for the Camera permission and does not ask for it. Seems like `ImagePicker.requestCameraPermissionsAsync()` should be used instead.
2. `ImagePicker.getCameraPermissionsAsync()` is a promise and thus needs `await` inserted before it. 

**Dev environment info (please complete/provide the following information):**
- Package version (stream-chat-react-native/stream-chat-expo)
stream-chat-expo 3.0.0
- react-native or expo version
Expo SDK 40
- Device/Emulator (android/ios) and OS version
Android and iOS devices (Pixel 4a and iPhone 11): Android 11 and iOS 14.5

**To Reproduce**

1. Press the camera button inside of the message input.

**Expected behavior**
It opens the camera.

gz#9906

**Comment by vishalnarkhede** [comment]
@junminleeKS this issue has been fixed in `v3.1.0`!!
