### ISSUE TITLE
stream-chat-expo: getPhotos does not work for iOS

### ISSUE THREAD

**Issue by junminleeKS** [GetStream/stream-chat-react-native#540]
**Describe the bug**
getPhotos inside the registerNativeHandlers function only checks/asks for permission on Android. If the MediaLibrary permission has not been set elsewhere then the ImagePicker does not work on iOS.

**Dev environment info (please complete/provide the following information):**
- Package version (stream-chat-react-native/stream-chat-expo)
stream-chat-expo 3.0.0
- react-native or expo version
Expo SDK 40
- Device/Emulator (android/ios) and OS version
Device (iPhone 11): iOS 14.5

**To Reproduce**

1. Press the attachments button in the message input.
2. Press "Allow access to your Gallery".

**Expected behavior**
Should be asked for Camera permissions.

gz#9907

**Comment by vishalnarkhede** [comment]
@junminleeKS fyi, this will be released with next patch :) Early next week

**Comment by vishalnarkhede** [comment]
@junminleeKS this issue has been fixed in `v3.1.0`!!
