### ISSUE TITLE
Types errors on yarn workspaces monorepo

### ISSUE THREAD

**Issue by ericlifs** [GetStream/stream-chat-react-native#545]
**Describe the bug**
I have installed stream-chat-react-native into my monorepo project that uses yarn workspaces and I'm seeing a lot of types error on my console as you can see in the following screenshot:

![image](https://user-images.githubusercontent.com/7376892/110255646-8ab4bf80-7f73-11eb-812c-8f00d4298a52.png)

**Dev environment info**

- App architecture: Yarn Workspaces Monorepo
- Pacakges:

![image](https://user-images.githubusercontent.com/7376892/110247749-8aed9480-7f4c-11eb-9ffd-d23004e52b9a.png)

- iPhone 11 Emulator - 14.2

gz#9960

**Comment by nhannah** [comment]
@ericlifs what version of typescript are you using?

**Comment by ericlifs** [comment]
@nhannah I was using an old one, I upgraded it to the one from the tutorial and it worked!

Thank you very much!
