### ISSUE TITLE
Other member name and avatar is not displayed when using ChannelList with ChannelPreviewMessenger

### ISSUE THREAD

**Issue by harrisonschwartz** [GetStream/stream-chat-react-native#55]
Repro steps:
1) Create new react native project via react-native init
2) Add stream-chat-react-native per directions on this github repo
3) Set current user via: 
```
    const user = {
      id: userId,
      name: userName,
      image: userAvatarUrl
    }
    chatClient.setUser(user, userToken)
```
`userId` is a guid permanently associated with the current user that users will never see. `userName` and `userAvatar` are what we expect to see in the channel list channel preview
 
4) Create a channel via: 
```
chatClient.channel('messaging', {
          members: [user.id, recipientId]
        })
```
where `user.id` is the userId of the current user and `recipientId` is the userId of the other user in a 1:1 chat.

5) Display channel list via 
```
  <ChannelList
              filters={{ type: 'messaging', members: { $in: [userId] } }}
              sort={{ last_message_at: -1 }}
              Preview={ChannelPreviewMessenger}
              onSelect={channel => { Actions.streamChannel({ channel }) }}
            /> 
```
where `userId` is the userId of the current user.

Result:
* Channel previews display with:
   * No channel name (expected the name of the other participant in the channel)
   * A solid blue avatar (expected the avatar of the other participant in the channel)

<img width="426" alt="Screen Shot 2019-08-24 at 2 23 31 AM" src="https://user-images.githubusercontent.com/8315604/63635323-4d4d4300-c616-11e9-827d-7bb7288585b2.png">

Expected something like:
<img width="340" alt="Screen Shot 2019-08-24 at 2 29 26 AM" src="https://user-images.githubusercontent.com/8315604/63635422-4115b580-c617-11e9-9139-c3a8ee920086.png">

Note:
 * Mentions by name work properly within a channel
 * Other participant is typing indicator works properly by name within a channel
 * Avatars work properly within a channel

<img width="418" alt="Screen Shot 2019-08-24 at 2 23 48 AM" src="https://user-images.githubusercontent.com/8315604/63635327-55a57e00-c616-11e9-9777-0e2d2bdc5505.png">

**Comment by vishalnarkhede** [comment]
Hey @harrisonschwartz 

Thanks for bringing this up. This is now fixed  as part of `v0.1.19`. Please reopen the issue if it doesn't work for you :)
