### ISSUE TITLE
ChannelList sort props change does not query again

### ISSUE THREAD

**Issue by teeaaspoon** [GetStream/stream-chat-react-native#555]
**Describe the bug**
I'm trying to filter my messages by unread, but it doesn't seem like theres an option to filter by {has_unread: -1}

Instead, I have opted for sorting by {has_unread: -1} which does work.
However, when I change the props of my sort object from {last_message_at: -1} to {has_unread: -1} the component does not update.

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native/stream-chat-expo): 3.0.0
- react-native or expo version: expo 40.0.0
- Device/Emulator (android/ios) and OS version: ios

**To Reproduce**
`<ChannelList
            sort={sort}
          />`

change props of sort does not query update the component

**Expected behavior**
Being able to switch between last_message_at and has_unread

gz#10184

**Comment by vishalnarkhede** [comment]
Hey @teeaaspoon I have added this to our backlog. We will try to sort it out, in upcoming minor release either 3.2.0!!

Until then, you can simply force re-render the ChannelList component, when sort changes (by updating `key`)

e.g., here after 5 seconds, channellist will render with new sort object:

```jsx
const App = () => {
  const [sort, setSort] = useState(defaultSort);
  const [key, setKey] = useState(0);

  useEffect(() => {
    setTimeout(() => {
      setSort({ has_unread: -1 });
      setKey(k => k + 1);
    }, 5000)
  }, [])


  return (
      <ChannelList
        key={key}
        sort{sort}
        ...
      />
  )
}
```

**Comment by vishalnarkhede** [comment]
@teeaaspoon closing this for now. Please reopen if you have more questions :)

**Comment by decamps-enmanuel** [comment]
Has this been fixed? Custom sorting works until I send a message in any channel and the sort just forces last_message_at: -1.

**Comment by vishalnarkhede** [comment]
@decamps-enmanuel Please take a look at this guide for adding custom sorting on event based updates - https://getstream.io/chat/docs/sdk/reactnative/guides/customize-channel-list/#customizing-event-handlers
