### ISSUE TITLE
Disable thread reply in version 3.x

### ISSUE THREAD

**Issue by haivle** [GetStream/stream-chat-react-native#558]
I can't find a way to disable thread reply, i think that is possible in version 2.x

gz#10222

**Comment by ericzhou27** [comment]
Same here. It looks like it's in the documentation as a property of the Channel component, but the property doesn't work/show when I try it. https://getstream.github.io/stream-chat-react-native/v3/#messageActions

**Comment by ericzhou27** [comment]
Never mind! Upon further inspection, it looks like they added it back in four days ago. 
https://github.com/GetStream/stream-chat-react-native/commit/52a842c50a995ca47ef5c6c653d5f0d550b16f9c#diff-624046ce3fcb308fb7a7c3684e23408f7c045874cea00ca2f4183257a97415b6

**Comment by ericzhou27** [comment]
After working for a bit, I have two quick follow ups for anyone at Stream. My current implementation taken from the documentation:

`
         messageActions={({
              blockUser,
              muteUser,
              copyMessage,
              deleteMessage,
              editMessage,
              flagMessage,
              reply,
              retry,
              threadReply,
            }) => [
              {
                action: () => {
                  console.log('NAVIGATE TO USER');
                },
                title: 'View Profile',
                icon: <Icon name="person-outline" size={24} color="grey" />,
                titleStyle: {color: 'blue'},
              },
              editMessage,
              copyMessage,
              deleteMessage,
            ]}
`

First, as of right now, this results in the same message actions being displayed for both the user and the person they are talking with, allowing them to delete/edit the messages of other people. How can we have different messageActions between these two cases? 

Second, how can I get the user id of the person who sent the message? I would like to pass it as a prop to the action function for the custom messageAction.

**Comment by vishalnarkhede** [comment]
@ericzhou27 This is the exhaustive list of values, which you can access in `messageActions`:

```
{
        blockUser: MessageAction | null;
        canModifyMessage: boolean;
        copyMessage: MessageAction | null;
        deleteMessage: MessageAction | null;
        editMessage: MessageAction | null;
        error: boolean;
        flagMessage: MessageAction | null;
        isMyMessage: boolean;
        isThreadMessage: boolean;
        message: MessageType<At, Ch, Co, Ev, Me, Re, Us>;
        messageReactions: boolean;
        muteUser: MessageAction | null;
        reply: MessageAction | null;
        retry: MessageAction | null;
        threadReply: MessageAction | null;
        repliesEnabled?: boolean;
      }
```

So you can use `isMyMessage` value to decide which actions to render!!

**Comment by ericzhou27** [comment]
Thanks Vishal! After doing some digging I found the "canModifyMessage" prop and was using that but this is much better!

**Comment by vishalnarkhede** [comment]
Glad that it helped :)
