### ISSUE TITLE
Inline date separator?

### ISSUE THREAD

**Issue by ericzhou27** [GetStream/stream-chat-react-native#559]
Is there a way to add the date separator back in? It appears to be in older versions (i.e. the slack clone tutorial you guys have linked, and also at https://github.com/GetStream/stream-chat-react-native/blob/master/src/components/MessageList/DateHeader.tsx) but it's been taken out and replaced with a sticky header in the newest version. The sticky header is interesting, but we think that having the date separator there is better since the header only appears to reflect the date of the message at the very top. In addition, the date separator is standard on other messaging platforms that users are used to (i.e. iMessage, Discord, FB Messenger). We would like to use the old date separator in the MessageList. Is this possible?

gz#10229

**Comment by vishalnarkhede** [comment]
Hey @ericzhou27 we are already discussing this internally. We will mostly add these inline date separators next week. I will let you know :)

**Comment by ericzhou27** [comment]
Thanks so much! I'll stay tuned!
