### ISSUE TITLE
v3.1.0 breaks TypeScript imports

### ISSUE THREAD

**Issue by jehartzog** [GetStream/stream-chat-react-native#560]
**Describe the bug**
After upgrading from `3.0.0` to `3.1.0`, TypeScript fails to pull correctly types from `stream-chat-react-native`.

**Dev environment info (please complete/provide the following information):**

- `stream-chat-react-native` `v3.1.0`
- `TypeScript` `v4.2.3`
- `react-native` `v0.64`

**To Reproduce**

1. Have `stream-chat-react-native` at `v3.0.0` without TypeScript errors:
```
import { MessageList, MessageInput } from 'stream-chat-react-native';
```

1. Upgrade to `v3.1.0`

**Expected behavior**
- No TS errors

**Actual behavior**
- TS fails to find imports
![image](https://user-images.githubusercontent.com/14143246/111354844-5c5a7280-864c-11eb-9d14-2454092f942c.png)

gz#10255

**Comment by vishalnarkhede** [comment]
@jehartzog I will take a look and get back to you :)

**Comment by vishalnarkhede** [comment]
@jehartzog Please upgrade to `3.1.2`. We have fixed this issue!!

**Comment by jehartzog** [comment]
@vishalnarkhede Confirmed that `3.1.2` fixes the issue. Thanks for quick patch and release.
