### ISSUE TITLE
disable long press, or prevent overlay from showing.

### ISSUE THREAD

**Issue by teeaaspoon** [GetStream/stream-chat-react-native#561]
**Describe the bug**
I don't want the overlay at all. How do I stop it from coming up when it's long pressed?

I tried removing OverlayProvider from the root of my app but it will crash without it.

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native/stream-chat-expo) 3.1.0
- react-native or expo version 0.63.4
- Device/Emulator (android/ios) and OS version ios

**To Reproduce**

LongPress on any message

**Expected behavior**
No overlay at all. Long Press should do nothing.

**Additional context**

**Screenshots**

gz#10264

**Comment by vishalnarkhede** [comment]
@teeaaspoon We are already working on this in linked PR. We will release it in next minor version :)

**Comment by fedex995** [comment]
@vishalnarkhede do you have an estimated release date for this issue?

**Comment by leena-sharma** [comment]
@vishalnarkhede  Any update on this ?

**Comment by vishalnarkhede** [comment]
@leena-sharma @fedex995 you can use this prop to remove onLongPress handler - https://getstream.io/chat/docs/sdk/reactnative/core-components/channel/#onlongpressmessage
