### ISSUE TITLE
myMessageTheme does not work on 3.1.0

### ISSUE THREAD

**Issue by haivle** [GetStream/stream-chat-react-native#562]
Q1:
<Channel
    messageActions={messageActions}
    channel={channel}
    initialScrollToFirstUnreadMessage
    enforceUniqueReaction
    myMessageTheme={{ colors: { grey_gainsboro: 'red' } }}
/>

this code work on version 3.0.0 but does not work on 3.1.0

Q2:
We have hashtag in text message, but it keeps rendering that text into headings1, how can we avoid this situation?

gz#10265

**Comment by vishalnarkhede** [comment]
Hey @haivle let me check and get back to you :)

**Comment by vishalnarkhede** [comment]
@haivle could you show me rest of the code around chat component?

**Comment by vishalnarkhede** [comment]
@haivle 

> We have hashtag in text message, but it keeps rendering that text into headings1, how can we avoid this situation?

Please refer to this doc - https://github.com/GetStream/stream-chat-react-native/wiki/Cookbook-v3.0#message-bubble-with-custom-text-styles--fonts

**Comment by virdesai** [comment]
@haivle for Q2, if you look [here](https://github.com/GetStream/stream-chat-react-native/blob/master/src/components/Channel/Channel.tsx#L252) you can pass this prop into your `Channel` component to get rid of `heading1` if you want. [Here](https://github.com/GetStream/stream-chat-react-native/blob/master/src/components/Message/MessageSimple/utils/renderText.tsx#L200:L214) are some built-in custom markdown rules we currently use to show you a format of what you can do

**Comment by virdesai** [comment]
@haivle as for the `myMessageTheme` issue. could you please try on our latest version `3.2.0` and let us know if the problem still exists for you?

**Comment by haivle** [comment]
> @haivle as for the `myMessageTheme` issue. could you please try on our latest version `3.2.0` and let us know if the problem still exists for you?

thanks @virdesai it works

**Comment by haivle** [comment]
> @haivle for Q2, if you look [here](https://github.com/GetStream/stream-chat-react-native/blob/master/src/components/Channel/Channel.tsx#L252) you can pass this prop into your `Channel` component to get rid of `heading1` if you want. [Here](https://github.com/GetStream/stream-chat-react-native/blob/master/src/components/Message/MessageSimple/utils/renderText.tsx#L200:L214) are some built-in custom markdown rules we currently use to show you a format of what you can do

I'm trying to add a new rule to markdownRules but I could not get it running


`
import _ from 'lodash'
import { defaultRules, ParseFunction, parseInline, ReactNodeOutput } from 'simple-markdown'
import React from 'react'
import { Text } from 'react-native'

const regEx = new RegExp(`^(#\\S+)`, 'g')
const match = source => regEx.exec(source)

const hashTagReact: ReactNodeOutput = (node, output, { ...state }) => {
  return React.createElement(
    Text,
    {
      key: state.key,
      style: { color: 'red' },
    },
    Array.isArray(node.content) ? node.content[0]?.content || '' : output(node.content, state),
  )
}

const parse: ParseFunction = (capture, parse, state) => ({
  content: parseInline(parse, capture[0], state),
})

const hashtag = {
  match,
  order: 0.1,
  parse,
  react: hashTagReact,
}

const rules = _.extend({}, defaultRules, {
  hashtag: hashtag,
})

export default rules
`

`
<Channel
          channel={group}
          Card={AttachmentCard}
          markdownRules={MarkdownRules}
          // Message={Message}
          keyboardBehavior={Platform.OS === 'ios' ? 'padding' : 'height'}
          keyboardVerticalOffset={Platform.OS === 'ios' ? KEYBOARD_OFFSET_HEIGHT + insets.top : 0}
        >
`

**Comment by haivle** [comment]
I'm receiving this error when trying to run the above code

![Simulator Screen Shot - iPhone 11 - 2021-03-29 at 15 21 06](https://user-images.githubusercontent.com/52659811/112786726-a27af180-90a2-11eb-9270-1a6d815c65ed.png)

**Comment by haivle** [comment]
even <Channel markdownRules={SimpleMarkdown.defaultRules} /> gives the same error

**Comment by virdesai** [comment]
@haivle what is within `group` that you're passing to `channel`? specifically what's within `group.state.messages`?

**Comment by haivle** [comment]
@virdesai I've also tried to use default rules of simple-markdown, it also crashes and gives the same error as above

**Comment by haivle** [comment]
`<Channel markdownRules={SimpleMarkdown.defaultRules} />` gives the same error
