### ISSUE TITLE
Question: APNs provider API requirement starts March 31

### ISSUE THREAD

**Issue by rodrigowpl** [GetStream/stream-chat-react-native#563]
From apple regarding APN Push:

The HTTP/2-based Apple Push Notification service (APNs) provider API lets you take advantage of great features, such as authentication with a JSON Web Token, improved error messaging, and per-notification feedback. If you still send push notifications with the legacy binary protocol, make sure to upgrade to the APNs provider API as soon as possible. APNs will no longer support the legacy binary protocol after March 31, 2021.

https://developer.apple.com/news/?id=uzyxiriy

@vishalnarkhede @ferhatelmas As my understanding do we need to check it on your side?

gz#10282

**Comment by vishalnarkhede** [comment]
@rodrigowpl let me get back to you about it!!

**Comment by rodrigowpl** [comment]
@vishalnarkhede Thank you! 

Even if it's not ready now, we need at least know the plans about that since the date is very close. It's part of our sprint goal :)

**Comment by vishalnarkhede** [comment]
@rodrigowpl We are preparing notes for response for this question. Please bare with us.

**Comment by ferhatelmas** [comment]
@rodrigowpl We're already on new protocol, no change is needed.

**Comment by rodrigowpl** [comment]
Thank you!
