### ISSUE TITLE
DateSeparator not consistent

### ISSUE THREAD

**Issue by lokewk** [GetStream/stream-chat-react-native#575]
"expo": "^39.0.0"
    "stream-chat": "2.6.0"
    "stream-chat-expo": "^2.1.0"

Hi, we notice DateSeparator is not consistent shown in our chatlist.
Please advise.

gz#10478

**Comment by vishalnarkhede** [comment]
@lokewk Could you please provide more details around, what you mean by not-consistent?

**Comment by lokewk** [comment]
![Screenshot_chat](https://user-images.githubusercontent.com/68896130/112281046-9832af00-8cc0-11eb-86c3-7b149ecf7094.png)

the screenshot on the left is showing messages send in different day and is missing the DateSeparator.
but in the 2nd screenshot DateSeparator is shown. please advise.

**Comment by isabellaskc** [comment]
Hi, any update to this issue?

**Comment by virdesai** [comment]
@lokewk just so I try to reproduce this issue on the same version, within your lock file can you tell me which version of stream-chat-expo was actually installed? and have you done anything custom within your MessageList or DateSeparator components?

**Comment by lokewk** [comment]
@virdesai the stream-chat-expo installed is 2.1.0 (within lock file). No customisation has been done within the DateSeparator. However, for MessageList, 'Message={CustomMessagePreview}' has been added (Would this be considered as a customisation within a MessageList? Could this be a cause?)

**Comment by vishalnarkhede** [comment]
@lokewk Could you share code for `CustomMessagePreview`. My suspicion would be that there is a deleted message right before the message, where ideally there should be a date separator - https://github.com/GetStream/stream-chat-react-native/blob/v2-legacy/src/components/MessageList/utils/insertDates.ts#L101

If you could confirm, that would be great!!

**Comment by lokewk** [comment]
@vishalnarkhede nope, we have checked, there isn't any deleted messages right before the messages in the new day. even if there is the date separator needs to be shown too ya?

below is the request code for `CustomMessagePreview`

```
class MessageContentWithName extends React.PureComponent {
  render() {
    return (
      <View style={
        this.props.message.selected==true
        ? { flexDirection: 'column', padding: 5,  
            backgroundColor: Colors.primaryColor,
          }
        : { 
          flexDirection: 'column', padding: 5,  
          backgroundColor: '', 
        }}>
        <Text style={{fontSize: 9}}>{this.props.message.user.<=Redacted=>_role} </Text>
        <Text style={{fontWeight: 'bold', fontSize: 12}}>{this.props.message.user.name}</Text> 
        <MessageContent 
          {...this.props}
        />
      </View>
    );
  }
}



const CustomMessagePreview = props => {
  const [isVisible, setIsVisible] = useState(false);
  const [isImage, setIsImage] = useState(false);
  const [isFile, setIsFile] = useState(false);
  
  const copyToClipboard = (text) => { 
    Clipboard.setString(text);
  }; 
  
  
  const CustomMessageAvatar = props => {
    const [imageURL, setImageURL] = useState('')
  
    useEffect(() => { 
      const getChannelAvator = async () => { 
       let _signedURL = '';  
       if (props.message.user.image != null && props.message.user.image != '' ){
         _signedURL = <=Redacted=>
         }else{
            _signedURL = '../assets/appicon.png';
          }
          setImageURL(_signedURL); 
        };
  
     getChannelAvator();        
    },[props.message]) 
    return (
        <Avatar image={imageURL} name={props.message.user.name} size={35} />
    );
  };

  return (
    <View>
      <MessageSimple
            {...props}  
            MessageAvatar={() => <Avatar name={props.message.user.name} showAvatar={false}/>}
            MessageContent={MessageContentWithName}  
            dismissKeyboardOnMessageTouch={true}
            onLongPress={ async (message, e) => {
              if (message.attachments.length >0 ) {
                for (var i = 0; i<message.attachments.length; i++ ) {
                  if (message.attachments[i].type=='image') {
                    console.log('type is image')
                    downloadImage(message.attachments[i].image_url)
                  }   
                  else if (message.attachments[i].type=='file') {
                    console.log('type is file')
                    console.log(message.attachments[i].asset_url)
                    downloadFile(message.attachments[i].asset_url, message.attachments[i].title)
                  }           
                  
                }
              }
              else {
                copyToClipboard('['+ moment(message.created_at).format('DD/MM, HH:mm') +']'+message.user.name +': '+ message.text);
                setIsVisible(true)
                setTimeout(function(){ 
                  setIsVisible(false)           
                }, 1000);
              }
              
            }}
            onPress={(message, e) => {
              props.showActionSheet();
            }}
          /> 
          <SnackBar visible={isVisible} textMessage="Message copied!" />
          <SnackBar visible={isImage} textMessage="Image saved!" />
          <SnackBar visible={isFile} textMessage={Platform.OS=='ios'? 'Sharing file!' : 'File saved!'} />
    </View>
  )
};

const styles = StyleSheet.create({
    text: {
        fontFamily: 'montserrat'
    }
});

export default CustomMessagePreview;
```

**Comment by nhannah** [comment]
Hi @lokewk, Do you plan on updating to v3.x ? I have a PR open now that includes changes that I expect fix the issue you see. https://github.com/GetStream/stream-chat-react-native/pull/581 , 3.x is a large update to the SDK just FYI. 

If not could you send a log of the messages in that section? I want to check it against the 2.x logic to see where it could have failed to add a separator (a deleted message was the most likely suspect as Vish noted).

**Comment by lokewk** [comment]
Hi @nhannah, yes we have plans for updating but is not our top priority now also this update will take up a fair bit of our development resource, as this upgrade isn't as simple compare to "Upgrade from 0.x.x to 2.x.x".

**Comment by nhannah** [comment]
@lokewk could you still send the messages from that range of messages so I can compare them to the logic in the date separator for v.  2.x? I want to narrow down the cause so I can propose a solution. Thanks!

**Comment by vishalnarkhede** [comment]
@lokewk could you send a log of the messages in that section??
