### ISSUE TITLE
Refreshing channel after updateMessage

### ISSUE THREAD

**Issue by teeaaspoon** [GetStream/stream-chat-react-native#578]
**Describe the bug**
I'm using client.updateMessage to manually trigger a message edit from my code.
I went into explorer and saw that my message data was updated. 
However my react native application does not show the updated message until I either send a new message, or navigate to another page and come back.

Is there a command that will automatically trigger a channel refresh after I updateMessage?

EDIT: I built a custom MessageContainer component which takes the message as a prop, which could be the reason why it's not refreshing. I notice that it does update to all members if I did it on regular messages and not my custom MessageContainer component

EDIT2: I found out that the only an edit of the message "text" field triggers it. if i updated custom data i passed into the message it won't trigger anything

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native/stream-chat-expo): 3.0.0
- react-native or expo version: 40.0.0
- Device/Emulator (android/ios) and OS version: ios

**To Reproduce**

1. send a message
2. use client.updateMessage with the previous message's id and update some values

**Expected behavior**

all members in chat should see the updated message without having to leave the page or send a new message

**Additional context**

**Screenshots**

**Comment by virdesai** [comment]
@teeaaspoon you said you built a custom MessageContainer component. Did you mean MessageContent or MessageTextContainer? This is likely a memoization issue which we possibly need to provide customization to you for or you could fully override the necessary component to not use our component memoization and the data change should then trigger rerenders

**Comment by teeaaspoon** [comment]
@virdesai yes, i meant i built a custom MessageTextContainer that showed additional custom data that i provided to the message. I managed to work around by just updating the "text" value in the message too.

Are there any documents on how the memoization works. I would like to read more on it since I'm not too familiar.

**Comment by virdesai** [comment]
@teeaaspoon good to hear! we'll work on allowing this custom data rerender control soon. thanks for pointing it out!

as far as memoization goes, [here's](https://reactjs.org/docs/react-api.html#reactmemo) the React documentation about it. essentially it's the functional component equivalent of the class based PureComponent shouldComponentUpdate functionality to allow you to control of when your component renders based on the props being passed into it. So if you look [here](https://github.com/GetStream/stream-chat-react-native/blob/master/src/components/Message/MessageSimple/MessageTextContainer.tsx#L137:L174) we are creating that function to control when `MessageTextContainer` rerenders and that helps with performance to limit renders. The issue for yours is that you customized `MessageTextContainer` and so when we're using it within `MessageContent` we have no checks in our memoization for the seeing if the custom message data has changed that would cause `MessageContent` to rerender and therefore `MessageTextContainer` also does not.

I'm going to close this issue for now as you found a solution but feel free to keep the dialog going if you have other questions around memoization
