### ISSUE TITLE
Cannot custom SendButton

### ISSUE THREAD

**Issue by haivle** [GetStream/stream-chat-react-native#582]
Q1/
I try to custom SendButton using the following code, but it does not work
`<Channel
      channel={this.state.group}
      thread={this.state.thread}
      SendButton={props => <Button.Icon icon="send" onPress={props.sendMessage} />}
    >
       <Thread />
 </Channel>`

Q2/
Is there any reason you are using TouchableOpacity from 'react-native-gesture-handler' in this line? This causes the button not clickable in our project when we put the view inside a PanGestureHandler. Can you change this into `import {TouchableOpacity} from 'react-native'`?  
https://github.com/GetStream/stream-chat-react-native/blob/f833d4e0df90ea23522b4415e0f3de55687acab4/src/components/MessageInput/SendButton.tsx#L2

**Comment by vishalnarkhede** [comment]
@haivle 

Q1. As part of v3, we are moving away from prop drilling architecture. So all the values should be accessed from context.
For example in your case:

```js
import { useMessageInputContext } from 'stream-chat-react-native';

const CustomSendButton = () => {
  const {sendMessage} = useMessageInputContext();

  return <Button title={'send'} onPress={sendMessage} />
}

<Channel
  SendButton={CustomSendButton}
  ...
/>
```

Q2. We are using RNGH to utilise platform native touch system.

> This causes the button not clickable in our project when we put the view inside a PanGestureHandler.

I don't think this should be an issue. I tried in one of our sample app, and seems to be fine. Could you please share some code around your chat components and whats the logic in your `PanGestureHandler`

**Comment by vishalnarkhede** [comment]
Closing this issue for now. Please reopen if you have any more questions!!

**Comment by sterlingwes** [comment]
Why is `sendMessage` still on the prop type for SendButtonProps, then? If you're not going to document this properly, at least have the types reflect reality @vishalnarkhede
