### ISSUE TITLE
checkIcons is always double blue ticks

### ISSUE THREAD

**Issue by tuneerclixlogix** [GetStream/stream-chat-react-native#586]
1. I sent a message from one device and on another side the user was not online and has not seen the message but still in status of messages double blue ticks are visible.
2. To resolve first point I created my custom component to handle this and used MessageStatus prop in channel where i am using following code
`const messageContext = useMessageContext();
return (
        <>
            {messageContext.message.readBy === true ? <Image source={appImages.DOUBLE_TICK} /> : <Image source={appImages.GREY_DOUBLE_TICK} />}
        </>
    );
 `
 Now when i send message and the second user chat was already opened but messageContext.message.readBy is still false, when the second user go back and then open the chat again then the messageContext.message.readBy becomes true at first user's side.

**Comment by leena-sharma** [comment]
Hi,
@vishalnarkhede  Any update on this issue ?
