### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by elleryfamilia** [GetStream/stream-chat-react-native#587]
This latest version isn't building:

********************************************
src/components/MessageList/utils/getGroupStyles.ts:17:1 - error TS6133: 'FormatMessageResponse' is declared but its value is never read.

17 import type { FormatMessageResponse } from 'stream-chat';
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by vishalnarkhede** [comment]
The latest build has fixed it
