### ISSUE TITLE
Question: How can we configure auto-sizing in MessageInput when typing long messages?

### ISSUE THREAD

**Issue by rodrigowpl** [GetStream/stream-chat-react-native#588]
Question:
How can I modify the `MessageInput` component to have a custom size based on the text typed size?

Example:

How it looks like currently (long text):
![image](https://user-images.githubusercontent.com/18172307/113615525-5bed4000-962a-11eb-9d51-78170c348290.png)

My `MessageInput` code:
![image](https://user-images.githubusercontent.com/18172307/113615589-6f001000-962a-11eb-85bb-a8835da4422e.png)

**Comment by virdesai** [comment]
@rodrigowpl what version of the `stream-chat-react-native` SDK are you on? on the v3 of our SDK you have the ability to pass in `numberOfLines` as a prop here https://github.com/GetStream/stream-chat-react-native/blob/master/src/components/AutoCompleteInput/AutoCompleteInput.tsx#L124 and that should work more instead of passing it through `additionalTextInputProps`

**Comment by rodrigowpl** [comment]
@virdesai I'm on `2.1.0`. Will numberOfLines will make the input auto-resizable based on text size like my example? If so I could update it 

But anyway, is there a way to do this in the v2? (just checking)

**Comment by virdesai** [comment]
@rodrigowpl it's likely possible within v2 but may be a lot more involved with `styles` of the `MessageInput` and `AutoCompleteInput` components. As you can see [here](https://github.com/GetStream/stream-chat-react-native/blob/master/src/components/AutoCompleteInp ut/AutoCompleteInput.tsx#L436:L477) within the redone v3 version of this component we do a few things around making sure the border around the TextInput grows with proper spacing and such

**Comment by rodrigowpl** [comment]
Thanks, I gonna test it

**Comment by vishalnarkhede** [comment]
@rodrigowpl For v2, you can take a look at this example - https://github.com/GetStream/stream-chat-react-native/wiki/Cookbook-(2.x.x)#growing-input-box-with-content
