### ISSUE TITLE
Cannot read property 'length' of undefined. 

### ISSUE THREAD

**Issue by NikitaNesterove** [GetStream/stream-chat-react-native#589]
**Describe the bug**
After I've updated stream-chat-react-native to 3.2.0 using cookbook installation, I get the error: Cannot read property 'length' of undefined. 

**Dev environment info (please complete/provide the following information):**

- Package version stream-chat-react-native 3.2.0
- react-native
- Device/Emulator Android devise 10 QKQ1.190828.002 

**To Reproduce**
1. Upgrade package: 
yarn upgrade stream-chat-react-native --latest

2. Upgrade another modules: 
 yarn add @react-native-community/blur @react-native-community/cameraroll @react-native-community/netinfo @stream-io/flat-list-mvcp react-native-document-picker react-native-fs react-native-gesture-handler react-native-haptic-feedback react-native-haptic-feedback react-native-image-crop-picker react-native-image-resizer react-native-reanimated@2.0.0-rc.0 react-native-safe-area-context react-native-share react-native-svg

3. Go throw https://docs.swmansion.com/react-native-reanimated/docs/installation to upgrate  react-native-reanimated@2.0.0-rc.0

4. Clean all caches

**Expected behavior**
The app doesn't expect to crash

**Screenshots**
![Screenshot_2021-04-05-18-52-23-714_com TheJoggle](https://user-images.githubusercontent.com/78030854/113678396-40844280-96c7-11eb-99c7-3918b08263d1.jpg)

**Comment by vishalnarkhede** [comment]
Hey @NikitaNesterove Could you please share some code around Chat components?

**Comment by NikitaNesterove** [comment]
@vishalnarkhede 
import React, { FC, useEffect, useState } from 'react';
import {
  ImageSourcePropType,
  SafeAreaView,
  View,
  KeyboardAvoidingView,
  Platform,
  Keyboard,
  ActivityIndicator,
  TouchableOpacity,
} from 'react-native';
import { useIsFocused, useNavigation, useRoute } from '@react-navigation/native';
import { useDispatch, useSelector } from 'react-redux';
import * as Client from 'stream-chat';
import {
  MessageList,
  Channel,
  MessageInput,
  SendButtonProps,
  InputUIComponentProps,
} from 'stream-chat-react-native';
import { useGetstreamClient } from '_features/messenger/hooks/useGetstreamClient';
import { RootState } from '_store/types/system/systemTypes';
import StyledButton from '_components/StyledButton';
import MessageInputComponent from '_features/messenger/components/MessageInput';
import EmployeeCard from '_components/EmployeeCard';
import SofiaText from '_components/SofiaText';
import CustomMessage from '_features/messenger/components/CustomMessage';
import { getStreamMessageActions } from '_constants/index';
import { PushNotificationAPI } from '_services/API/PushNotification';
import styles, { theme } from './styles';
import TokenStorage, { TokenTypes } from '_services/AsyncStorage/token';
import { AmazonAPI } from '_services/API/Amazon';
import { v4 as uuidv4 } from 'uuid';
import { generateImageSourceFromUrl } from '_utils/stringUtils';
import { setFileName } from '_features/feed/screens/CreatePost';
import { sendFileRequest, sendFileResponse } from '_store/actions/messenger';

let _isColleage: boolean;
let _position: string | undefined;
let _userProfileId: string | undefined;
const DirectMessageScreen: FC = () => {
  const dispatch = useDispatch();
  const token = useSelector<RootState, string>(state => state.auth?.token?.token!);
  const navigation = useNavigation();
  const { clearEmptyChannels } = useGetstreamClient();
  const route = useRoute<ProfileScreenRouteProp>();
  const { name, channel, avatarSource, position, isColleague } = route.params;
  const [isDeletedUser, setIsDeletedUser] = useState<boolean>(false);
  _isColleage = isColleague;
  _position = useSelector<RootState, string | undefined>(
    (state) => state.user?.position,
  );
  const loadingFile = useSelector<RootState, boolean>(
    (state) => state.messenger?.loadingFile,
  );
  const [memberId, setMemberId] = useState<object | string>('');
  _userProfileId = useSelector<RootState, string | undefined>(
    (state) => state.user?.userProfileId,
  );

  useEffect(() => {
    const channelMembers = Object.values(channel.state.members);
    const userMember = channelMembers.find(
      (user) => user.user.userProfileId !== _userProfileId,
    );
    if (userMember && userMember.user) {
      if (userMember.user.deactivated_at){
        setIsDeletedUser(true);
      }
      setMemberId(userMember.user.userProfileId);
    } else {
      setMemberId('');
    }
  }, []);

  useEffect(() => {
    if (route.params.sharedUrl && route.params.sharedUrl.mimeType === 'application/pdf') {
      shareFile();
    }
  }, []);

  const shareFile = async () => {
    const name = setFileName(route.params.sharedUrl.data.substring(route.params.sharedUrl.data.lastIndexOf('/')+1));
    const uploadFile = { data: route.params.sharedUrl.data, name };
    dispatch(sendFileRequest());
    const res =  await AmazonAPI.sendFiles(uploadFile, token);
    await channel.sendMessage({
      id: uuidv4(),
      attachments: [{
        type: 'file',
        name: name,
        'thumb_url': generateImageSourceFromUrl(res.fileUrl, true),
        'asset_url': generateImageSourceFromUrl(res.fileUrl, true),
      }],
    });
    dispatch(sendFileResponse());
  };

  const goBack = async () => {
    try {
      await clearEmptyChannels();
    } catch (err) {
    } finally {
      if (isColleague && navigation.canGoBack()) {
        navigation.goBack();
      } else {
        navigation.navigate('Messages');
      }
    }
  };

  return (
    <SafeAreaView style={styles.container}>
      <View style={styles.header}>
        <StyledButton
          containerStyle={styles.leftArrowButton}
          onPress={goBack}
          image={require('_assets/images/ArrowLeft.png')}
        />
        <EmployeeCard
          isMessenger={true}
          colleagueId={memberId as string}
          avatarStyle={'rectangle'}
          name={name}
          role={position}
          avatarSource={avatarSource}
          avatarDimensions={styles.headerAvatar}
          customNameStyles={styles.name}
          customRoleStyles={styles.employeePosition}
        />
      </View>
      <KeyboardAvoidingView
        style={styles.containerChat}
        behavior={Platform.OS === 'ios' ? 'padding' : undefined}>
        <TouchableOpacity activeOpacity={1} onPress={Keyboard.dismiss}>
          <Channel
            channel={channel}
            EmptyStateIndicator={() => EmptyMessageList(name)}>
            <MessageList />
            <MessageInput />
          </Channel>
        </TouchableOpacity>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
};

const EmptyMessageList = (name: string | undefined) => (
  <SofiaText style={styles.emptyTextContainer}>
    Say hi to your colleague,
    <SofiaText style={styles.emptyName}> {name}</SofiaText>
  </SofiaText>
);

export const getSendButton: FC<CustomSendButtonProps> = (props) => {
  let channelMembers = [];
  let recipients: any = [];
  let sender: any = undefined;
  if (props.channel?.state?.members) {
    channelMembers = Object.values(props.channel?.state?.members);
    recipients = channelMembers.filter(
      (x) => x.user?.userProfileId !== props.userProfileId,
    );
    sender = channelMembers.find(
      (x) => x.user?.userProfileId === props.userProfileId,
    );
  }

  const sendMessage = async () => {
    if (props.value.trim()) {
      Keyboard.dismiss();
      props.sendMessage();
      if (props.channel?.data?.id && sender && recipients) {
        const jwt = await TokenStorage.getToken(TokenTypes.JwtToken);
        recipients.map((recipient: any) => {
          if (recipient?.user?.userProfileId) {
            if (jwt) {
              PushNotificationAPI.sendPushNotification(jwt.token, {
                userProfileIds: [recipient.user.userProfileId],
                title: sender.user.name,
                body: props.value ?? 'Sent you a message.',
                extraData: {
                  userProfileId: sender.user.userProfileId,
                  name: sender.user.name,
                  position: _position,
                  isColleague: _isColleage,
                  picture: sender.user.image,
                  activityObjectType: 'directmessage',
                  activityVerbType: 'send',
                  channelId: props.channel?.data?.id,
                },
              });
            }
          }
        });
      }
    }
  };

  return (
    <StyledButton
      containerStyle={styles.sendMessage}
      onPress={sendMessage}
      image={require('_assets/images/sendText.png')}
    />
  );
};

export interface CustomSendButtonProps extends SendButtonProps {
  value: string;
  members: object;
  typing: object;
  channel: Client.Channel;
}

export interface CustomInputUIComponentProps extends InputUIComponentProps {
  SendButton?: FC<CustomInputUIComponentProps>;
  onChange?: (arg0: string) => void;
  messages?: object[];
  sharedUrl?: string;
  disabled?: boolean;
}

export interface ProfileScreenRouteProp {
  key: string;
  name: string;
  params: {
    name: string;
    position: string;
    avatarSource: ImageSourcePropType;
    channel: Client.Channel;
    sharedUrl: string;
    isColleague: boolean;
  };
}

export default DirectMessageScreen;

**Comment by vishalnarkhede** [comment]
@NikitaNesterove Just to confirm, could you also please share the code around OverlayProvider component?

**Comment by NikitaNesterove** [comment]
@vishalnarkhede What component are you talking about?

**Comment by vishalnarkhede** [comment]
https://github.com/GetStream/stream-chat-react-native/wiki/Cookbook-v3.0#overlayprovider

**Comment by NikitaNesterove** [comment]
@vishalnarkhede Hi, I don't use this component, is it possible that the error appears because I don't have OverlayProvider?

**Comment by vishalnarkhede** [comment]
@NikitaNesterove We didn't have OverlayProvider in 2.2.1. But this component is necessary as part of v3. Please check our example and docs for OverlayProvider:

- https://github.com/GetStream/stream-chat-react-native/blob/master/examples/TypeScriptMessaging/App.tsx
- https://github.com/GetStream/stream-chat-react-native/wiki/Cookbook-v3.0#overlayprovider

**Comment by vishalnarkhede** [comment]
@NikitaNesterove Please let me know if that fixes this issue!!

**Comment by NikitaNesterove** [comment]
@vishalnarkhede Thank's, will try and the write you

**Comment by vishalnarkhede** [comment]
Ok great!! I am closing this issue for now, please reopen if you still face this issue :)

**Comment by NikitaNesterove** [comment]
Hi @vishalnarkhede I added OverlayProvider, for I receive error from channel screen:
![Screenshot 2021-04-16 at 16 38 44](https://user-images.githubusercontent.com/78030854/115032655-3685ef00-9ed2-11eb-88be-81d47114ec7d.png)

I send channel use navigation: 
![Screenshot 2021-04-16 at 16 41 06](https://user-images.githubusercontent.com/78030854/115032947-8bc20080-9ed2-11eb-8b3d-0e664ef806a9.png)
![Screenshot 2021-04-16 at 16 40 42](https://user-images.githubusercontent.com/78030854/115032891-7f3da800-9ed2-11eb-9d79-3f4ac59ac75c.png)

I removed all custom component.

Code around OverlayProvider: 
import React, { createRef, useEffect } from 'react';
import { useSelector } from 'react-redux';
import { NavigationContainer } from '@react-navigation/native';
import SplashScreen from 'react-native-splash-screen';
import Config from 'react-native-config';
import { StreamChat } from 'stream-chat';
import { Chat, OverlayProvider } from 'stream-chat-react-native';
import RootStackNavigator from '_navigators/RootStackNavigator';
import AuthStack from '_features/auth/navigator';
import { useUser } from '_store/hooks/user/useUser';
import { useRootNavigation } from '_store/hooks/rootNavigation/useRootNavigation';
import { ActiveRootNavigator } from '_store/types/rootNavigation/models';
import { useGetstream } from '_store/hooks/getStream/useGetstream';
import { useGetstreamClient } from '_features/messenger/hooks/useGetstreamClient';
import { useInitialisation } from './hooks/useInitialisation';
import { NavigationRef } from './types';
import { RootState, Token } from '_store/types/system/systemTypes';
import messaging from '@react-native-firebase/messaging';
import {
  listenForPush,
  setShouldIncrementNotificationBadge,
  shouldIncrementChatNotificationBadge,
  shouldIncrementNotificationBadge,
} from '_utils/pushNotificationUtil';
import PushStorage from '_services/AsyncStorage/push';
import { AuthorType } from '_features/feed/components/Author';
import { useGroups } from '_store/hooks/group/useGroups';
import { PushNotificationAPI } from '_services/API/PushNotification';

export const rootNavigationRef: NavigationRef = createRef();

export const chatClient = new StreamChat(Config.API_KEY);

const RootNavigator = () => {
  const store = useUser();
  const { getGroupRequest } = useGroups();
  const {
    id,
    token,
    setNotificationBadge,
    setNotificationChatBadge,
    setNotification,
  } = useGetstream();

  const {
    clearEmptyChannels,
    streamI18n,
    id: getstreamClientId,
  } = useGetstreamClient();
  const userProfileId = useSelector<RootState, string | undefined>(
    (state) => state.user?.userProfileId,
  );
  const userAccountId = useSelector<RootState, string | undefined>(
    (state) => state.user?.userAccountId,
  );

  const accessToken = useSelector<RootState, Token | undefined>((state) => {
    return state.auth?.token ?? undefined;
  });

  const notification = useSelector<RootState, number>((state) => {
    return state.getstream?.notification ?? undefined;
  });

  useEffect(() => {
    const setupClient = async () => {
      try {
        const user = {
          id: id,
          name: store.firstName + ' ' + store.lastName,
          image: store.profileImageUrl,
          userProfileId,
        };
        if (chatClient.user) {
          await chatClient.disconnect();
        }
        await chatClient.setUser(user, token?.token);
        await clearEmptyChannels();
        handleOpenFromNotification(notification);
      } catch (e) {}
    };
    setupClient();
    listenForPush(
      accessToken?.token,
      (count: number) => setNotificationBadge(count),
      (count: number) => setNotificationChatBadge(count),
    );
    const unsubscribe = messaging().onTokenRefresh(async (refreshedToken) => {
      // -- send to server
      const pushToken = await PushStorage.getPushToken();
      if (refreshedToken !== pushToken) {
        try {
          await PushStorage.setPushToken(refreshedToken);
          await PushNotificationAPI.registerPushDevice(
            accessToken?.token,
            refreshedToken,
          );
        } catch (err) {
          console.warn(err);
        }
      }
    });
    return unsubscribe;
  }, [id, token]);

  type NotificationData = {
    object: string;
    referenceId: string;
    verb: string;
    extraData: object;
  };

  const { currentNavigator } = useRootNavigation();
  const initialised = useInitialisation();

  async function handleOpenFromNotification(notifiation: any) {
    if (notifiation) {
      const notificationData = JSON.parse(JSON.stringify(notifiation.data));
      // -- navigate to relevant activity/feed/page
      goToReferenceScreen(notificationData as NotificationData);
    }
    if (shouldIncrementNotificationBadge) {
      try {
        setShouldIncrementNotificationBadge(false);
        const count = await PushStorage.getNotificationBadgeCount();
        count && setNotificationBadge(count);
      } catch (error) {}
    }
    if (shouldIncrementChatNotificationBadge) {
      try {
        setShouldIncrementNotificationBadge(false);
        const count = await PushStorage.getNotificationChatBadgeCount();
        count && setNotificationChatBadge(count);
      } catch (error) {}
    }
  }

  const goToReferenceScreen = async (data: NotificationData) => {
    if (data?.object?.toLowerCase() === 'post') {
      const user: AuthorType = {
        userProfileId,
        name: store.firstName + ' ' + store.lastName,
        image: { uri: store.profileImageUrl },
        position: store.position,
      };
      if (notification) {
        navigate('Post', {
          screen: 'PostInfo',
          params: {
            author: user,
            activityId: data.referenceId,
            previousScreen: 'MainScreen',
          },
        });
      }
      setNotification(undefined);
    } else if (data?.verb === 'Add') {
      if (notification) {
        getGroupRequest(data.referenceId, false);
      }
      setNotification(undefined);
    } else if (data?.activityObjectType === 'directmessage' && notification) {
      const name = data.name;
      const avatarSource = data?.picture;
      const position = data?.position;
      const channelId = data.channelId;
      const channels = await chatClient.queryChannels({
        type: 'messaging',
        $and: [
          { members: { $in: [getstreamClientId] } },
          { members: { $in: [userAccountId] } },
        ],
      });
      if (channels && channels.length > 0) {
        const channel = channels.find((x) => x.id === channelId);
        if (channel && notification) {
          navigate('DirectMessageScreen', {
            name,
            position,
            avatarSource: avatarSource ? { uri: avatarSource } : undefined,
            channel,
          });
          setNotification(undefined);
        }
      }
    }
  };

  if (!initialised) {
    return null;
  }

  if (initialised && chatClient.user) {
    handleOpenFromNotification(notification);
  }

  SplashScreen.hide();

  return (
    <OverlayProvider>
      <Chat client={chatClient} i18nInstance={streamI18n}>
        <NavigationContainer ref={rootNavigationRef}>
          {getNavigator(currentNavigator)}
        </NavigationContainer>
      </Chat>
    </OverlayProvider>
  );
};

const getNavigator = (screen: ActiveRootNavigator | undefined) => {
  if (!screen) return;
  switch (screen) {
  case ActiveRootNavigator.Auth:
    return <AuthStack />;
  case ActiveRootNavigator.Directory:
    return <RootStackNavigator />;
  }
};

export function navigate(name: string, params?: object) {
  if (rootNavigationRef) {
    rootNavigationRef.current?.navigate(name, params);
  }
}

export default RootNavigator;

**Comment by NikitaNesterove** [comment]
I fixed this, for now get error when open chat: message.type undefined
