### ISSUE TITLE
iOS App hangs on splash screen in debug mode

### ISSUE THREAD

**Issue by mogulist** [GetStream/stream-chat-react-native#593]
**Describe the bug**
When I turn on `Debug` mode to debug with react-native-debugger, following happens:
`Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary.`
iOS App stops at splash screen.

It is likely that this issue stems from react-native-reanimated v2.x
https://github.com/software-mansion/react-native-reanimated/issues/1127

Someone suggested upgrading Flipper version. But it didn't work.
Someone suggested downgrade reanimated from 2.x to 1.13.x. But I failed to run `Sample App` with following errors:
`error: node_modules/react-native-reanimated/src/core/AnimatedNode.js: Cannot find module 'react-native-reanimated/plugin'`

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native/SampleApp): v3.1.2
- react-native or expo version: react-native
- Device/Emulator (android/ios) and OS version: iOS simulator with iOS14.4, Xcode 12.4

**To Reproduce**

Run SampleApp in this repository with iOS simulator.
Run react-native-debugger.
When the app runs normally, enable `Debug`.
Then app restarts.
App will stop at splash screen and react-native-debugger console will show `Invariant Violation: TurboModuleRegistry.getEnforcing(...)...`

**Expected behavior**
Able to run iOS app with react-native-debugger

**Additional context**

**Screenshots**

Sample just shows white background
<img src="https://user-images.githubusercontent.com/25053780/113838391-afe25b00-97c9-11eb-85f0-72c37010aec4.png" width="240">

React Native Debugger shows following errors
![image](https://user-images.githubusercontent.com/25053780/113838472-bffa3a80-97c9-11eb-8f5b-75fb5ebb9ca9.png)

As soon as I stop debugging, Sample runs normally as below.
<img src="https://user-images.githubusercontent.com/25053780/113838531-d0121a00-97c9-11eb-909b-d804297f0537.png" width="240">  <img src="https://user-images.githubusercontent.com/25053780/113838567-d902eb80-97c9-11eb-9f75-cd881500b93f.png" width="240">

**Comment by virdesai** [comment]
@mogulist what didn't work about upgrading Flipper? when using Flipper you shouldn't need to use the RN Debug Menu to put that app into debug mode as Flipper will already pick up the logs and debug info necessary

**Comment by TrisKnightGamer** [comment]
Can you copy full your log when install 1.13.2 version ?

**Comment by TrisKnightGamer** [comment]
And how you had done when install 1.13.2 version ?

**Comment by mogulist** [comment]
> @mogulist what didn't work about upgrading Flipper? when using Flipper you shouldn't need to use the RN Debug Menu to put that app into debug mode as Flipper will already pick up the logs and debug info necessary

@virdesai , I was doing other things for a week. I will try and let you know next week what didn't work when I upgraded Flipper. I will also try using Flipper.

**Comment by mogulist** [comment]
@TrisKnightGamer  I was doing other things for a week. I will share the log early next week. Thanks.
