### ISSUE TITLE
MessageList scrollTo is not a function error v2.2.2

### ISSUE THREAD

**Issue by ericlifs** [GetStream/stream-chat-react-native#603]
**Describe the bug**
I'm accessing the chat screen and once the messages are loaded I'm getting the following error `this._scrollRef.scrollTo is not a function` (more info on the screenshot). As soon as I remove the `<MessageList ... />`, I don't get the error anymore. 

I have dived into the library code, and I figured out the issue is with this particular line:
![image](https://user-images.githubusercontent.com/7376892/114241869-4c3e6600-9960-11eb-856b-08ea5838d4a9.png)

This is the screen code:
![image-redacted_dot_app](https://user-images.githubusercontent.com/7376892/114273055-febd0a00-99ee-11eb-8b90-774e884e0168.png)

As you can see, there is no user connection code in the file because it's being done on the parent component.

**Dev environment info**

- Package version: 2.2.2
- react-native version: 0.63.3
- Device/Emulator and OS version: iOS Emulator (14.2)

**Screenshots**
![simulator_screenshot_66F32A85-FE5C-4BA3-84D6-98637B3D614B](https://user-images.githubusercontent.com/7376892/114241257-4300c980-995f-11eb-8306-7d40344eb7f3.png)

**Comment by nhannah** [comment]
Hi @ericlifs have you considered upgrading to V3? It is an overhaul of the library and will require some changes to integration, but I know this issue will not exist there. Based on checking that `.current` exists in the `if` check I am not sure offhand why you are getting this occurance.

**Comment by vishalnarkhede** [comment]
Do you still get this error if you remove following code?

<img width="270" alt="Screenshot 2021-04-23 at 11 51 59" src="https://user-images.githubusercontent.com/11586388/115854227-52d1e080-a42a-11eb-8ff9-ef960e6daae6.png">

**Comment by vishalnarkhede** [comment]
Closing this since there was no response. Please reopen if you still need help here.
