### ISSUE TITLE
Support for uploading videos via camera roll

### ISSUE THREAD

**Issue by ericzhou27** [GetStream/stream-chat-react-native#604]
I'm looking for a way to handle the uploading of videos from the camera roll. Videos show up in the  when I set this:

<img width="364" alt="Screen Shot 2021-04-10 at 11 56 28 AM" src="https://user-images.githubusercontent.com/43918217/114281549-ca981800-99f3-11eb-8ddb-ced99c7df79d.png">

but they don't process correctly and fail to get uploaded. Would it be possible to add this? 

<img width="826" alt="Screen Shot 2021-04-10 at 12 14 49 PM" src="https://user-images.githubusercontent.com/43918217/114282000-5c088980-99f6-11eb-92e9-e441e475418b.png">

From the Stream React Native documentation, it looks to be a thing.

Alternatively, does the team have any suggestions on how I could implement this on my end? As long as we could send videos from within the app (and not force users to have to go off the app and save videos as a file) we would be more than happy!

**Comment by nhannah** [comment]
Hi @ericzhou27; you are correct there is not a good way to upload videos at the moment from the camera roll, it is in our roadmap to fully support videos but currently they are uploaded as files as noted. Using the built in UI to pull from the gallery into the file upload (as would be needed at the moment) would not be possible using the current component. I have noted this to our product owner and as the basic setup aligns with another needed change I am hoping I can get it in soon (the simplified filed upload version). If you need this asap it is possible to build a solution yourself for this as `uploadNewFile` is exposed via the `MessageInputContext`.

**Comment by nextriot** [comment]
Any update on this feature? We're also very much in need of a standard way to do this.

**Comment by vishalnarkhede** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/604?planning-poker) with ZenHub @khushal87 @madsroskar @santhoshvai @Enigma-I-am
