### ISSUE TITLE
best way to know if user has unread messages

### ISSUE THREAD

**Issue by teeaaspoon** [GetStream/stream-chat-react-native#606]
**Describe the bug**

Not really a bug. I want to show on other pages of my app with a red dot indicating that they have unread messages. 

Currently I am fetching all the channels, and sorting them by unread and checking to see if the first channel has unread messages.

This is inefficient because everytime I load the page I need to fetch all channels. is there a more efficient way to just know that a user has unread messages?

**Comment by shodgetts** [comment]
Hello, the response from connectUser, which you'll be using at the top of your app somewhere is going to include two fields that will be useful to you. Please use these to render your unread indicators. 

```
    total_unread_count: 1,
    unread_channels: 1,
```

Then you will want to subscribe to changes in unread count in your app with an event handler such as this

```
  client.on((event) => {
    if (event.total_unread_count !== undefined) {
      console.log(`unread messages count is now: ${event.total_unread_count}`);
    }

    if (event.unread_channels !== undefined) {
      console.log(`unread channels count is now: ${event.unread_channels}`);
    }
  });
```

If you have any further questions, please email support@getstream.io with your support request and your app_id. The Issues sections of these GitHub repos are reserved for Bugs/Feature Requests/Improvements, etc and support requests may be removed. 

-Big Steve
