### ISSUE TITLE
When importing types, bundling failed, Unexpected token

### ISSUE THREAD

**Issue by builtbyproxy** [GetStream/stream-chat-react-native#609]
**Describe the bug**
When running my mobile app, the node_module `stream-chat-react-native-core` is failing to import types.
  
As soon as the dependency graph is loaded, I get the error: `bundling failed: SyntaxError <...> node_modules/stream-chat-react-native-core/src/utils/useStreami18n.ts: Unexpected token (3:12)` 

**Dev environment info (please complete/provide the following information):**
- **stream-chat Version:** 3.7.0
- **stream-chat-react-native Version:** 3.3.3
- **react-native:** 0.61.5
- **device:** iPhone X (IOS 12.4)
- **Node:** 12.10.0

**To Reproduce**

1. In a new folder run `npx create-react-native-app chat-test && cd chat-test`
2. run `yarn add stream-chat-react-native`
3. run `yarn`
4. run `npx pod-install`
5. run `npx react-native run-ios`
6. your terminal will error after bundling

**Expected behavior**
I would expect my build to load correctly regardless of where I use the packages.

**Additional context**
- If I have debugging on, the error is with the import of `TranslationContextValue`. However if it's off the error is with `LiteralStringForUnion`. I don't believe debugging matters here, however I can get further through the bundle.
- My project uses Flow, version `0.112.0`
- Am I missing a typescript requirement? Do I need a package locally somewhere? 

**Screenshots**

![image](https://user-images.githubusercontent.com/16897508/114806023-63a9a300-9de7-11eb-83f7-44f413bc3a10.png)

**Comment by nhannah** [comment]
Hi @builtbyproxy can you confirm your TypeScript version? It looks like it may be an older version that did not support import type (pre 3.8).

**Comment by nhannah** [comment]
I see you mention `Am I missing a typescript requirement? Do I need a package locally somewhere?` I think it is likely you already have an old TS version installed, or if I am wrong there you should install one. We use bob https://github.com/callstack/react-native-builder-bob for distro and therefore when running on `react-native` it uses the `index.ts` as an entry point to make debugging easier.

**Comment by vishalnarkhede** [comment]
@builtbyproxy ping ^^

**Comment by builtbyproxy** [comment]
Thanks @vishalnarkhede 
Sorry for the delay on this

**Comment by vishalnarkhede** [comment]
I will close this one for now. Please reopen whenever you are ready ;)

**Comment by builtbyproxy** [comment]
I've done a check locally and can confirm I do not have any typescript installed
![image](https://user-images.githubusercontent.com/16897508/117404579-82660a00-af4d-11eb-941b-da993a95071a.png)

Nor do I have typescript in the actual application as we use Flow

**Comment by builtbyproxy** [comment]
Disregard this for now ^ I believe it might be an issue with my babel version. I might need 7.9.0 of core yet have 7.4.0
