### ISSUE TITLE
Push notification preferences

### ISSUE THREAD

**Issue by EJohnF** [GetStream/stream-chat-react-native#61]
How the setup specific push notification preferences (like mute specific channel, or send push only when @mentioned)

**Comment by Nekuromento** [comment]
@EJohnF at the moment we do not support configuring notification conditions. We have plans to provide ways of configuring this but I am not aware if this is scheduled for next releases.
Please contact Stream support for feature requests.

**Comment by tbarbugli** [comment]
@EJohnF the current behavior is that we don't send push messages when the user is muted; when the message is added to a thread we only send the push message if the user has at least a message in the thread or if it was mentioned
