### ISSUE TITLE
[Questions] Different bubble style for me and others and change border radius

### ISSUE THREAD

**Issue by mogulist** [GetStream/stream-chat-react-native#610]
Hi,  I have two questions.
Firstly, I want to use blue background for my bubble and white background for others. I tried with my custom theme as below:
```
export const theme: DeepPartial<Theme> = {
    messageSimple: {
        content: {
            containerInner: {
                backgroundColor: '#055CF5',
            },
            container: {
                borderRadiusL: 6,
                borderRadiusS: 6,
            },
            markdown: {
                text: {
                    color: 'white',
                },
            },
        },
    },
};
```
I could change colors of bubbles, but couldn't find any way to apply different color for the bubbles on the left side.

Secondly, I would like to change borders of bubbles. However I was able to change only bottom left and bottom right borders.
![image](https://user-images.githubusercontent.com/25053780/115012625-04cd5200-9eeb-11eb-9d34-a3d302958526.png)

What I want is as below (very simple)
![image](https://user-images.githubusercontent.com/25053780/115012686-17e02200-9eeb-11eb-9419-5567de08cabb.png)

**Comment by vishalnarkhede** [comment]
Hey @mogulist You can provide `myMessageTheme` prop on Channel component.

**Comment by mogulist** [comment]
Dear @vishalnarkhede , it works. Left bubbles have white background. Thank you. Only now I found that `myMessageTheme` is stated in Cookbook v3.0. I missed that part. 
![image](https://user-images.githubusercontent.com/25053780/115042656-ab771a00-9f0e-11eb-87ae-9bbc14fb0f53.png)

**Comment by mogulist** [comment]
@nhannah Oops, border radius issue is not resolved yet!

**Comment by mogulist** [comment]
Since, this issue is closed, I posted my second question in discussion: 
https://github.com/GetStream/stream-chat-react-native/discussions/614
