### ISSUE TITLE
Problem with run sample 

### ISSUE THREAD

**Issue by swifterman** [GetStream/stream-chat-react-native#613]
I want to just add the  sample code which is from here:
https://github.com/GetStream/stream-chat-react-native/wiki/Tutorial-v3.0
but I'm facing with the error which I attached the screenshot here.
![Simulator Screen Shot - iPhone 11 - 2021-04-18 at 20 54 05](https://user-images.githubusercontent.com/80140790/115155462-bce43180-a088-11eb-9c0d-1da92cf30544.png)
![Simulator Screen Shot - iPhone 11 - 2021-04-18 at 20 54 08](https://user-images.githubusercontent.com/80140790/115155466-bf468b80-a088-11eb-86d6-0e72baee4cc1.png)

**Comment by vishalnarkhede** [comment]
Hey @swifterman could you confirm if you have added `OverlayProvider` as a wrapper around navigation?

**Comment by vishalnarkhede** [comment]
Closing this for now!! Adding OverlayProvider should solve this problem
