### ISSUE TITLE
Theming Message Text

### ISSUE THREAD

**Issue by earthlingstd** [GetStream/stream-chat-react-native#62]
How do we change message text color and font size? Looks like the text is render using a separate Markdown lib?

**Comment by vishalnarkhede** [comment]
Hey @earthlingstd , in our latest sdk `0.2.4`, I have added support for `MessageText` UI component as prop - https://github.com/GetStream/stream-chat-react-native/commit/1491461b2f3e5d81ac4babcf144c9241a345539d#diff-df86b4a4ee3e5ab9fd106229b6ae8b75R35

This prop is on `MessageSimple` level. I will soon move it to `MessageList` or `Channel` level, but for now you can just do the following:

```
import { MessageSimple, Channel, MessageList } from 'stream-chat-react-native';

export class App extends React.Component {
    render () {
        return (
            <Channel>
                <MessageList
                    ...
                    Message={CustomMessage}
                    />
            </Channel>
        )
    }
}

const CustomMessage = (props) => (
    <MessageSimple
        MessageText={CustomMessageTextComponent}
        {...props}
    />
)

 
// Add custom styling here
// There are some additional props available (other than message object), 
// check this https://github.com/GetStream/stream-chat-react-native/blob/master/src/components/MessageSimple/MessageTextContainer.js 
// if you need to use them. I will add docs for this component props soon.
const CustomMessageTextComponent = ({ message }) => {
    return <Text>{message.text}</Text>
}
```

**Comment by earthlingstd** [comment]
Thank you for your answer, it perfectly works. Is there anyway that I can handle custom tag and display Attachment as a Card before the message?

**Comment by vishalnarkhede** [comment]
Hey @earthlingstd  Glad to hear that it worked.

1. What do you mean by custom tag?

2. Attachment are handled by default by `MessageSimple` component, and will be displayed before the `MessageText` component. Images are displayed as gallery, files are displayed are list of files and rest (giphy, external url preview etc) are displayed as cards - 

MessageContent - https://github.com/GetStream/stream-chat-react-native/blob/master/src/components/MessageSimple/MessageContent.js#L346

Attachment - https://github.com/GetStream/stream-chat-react-native/blob/master/src/components/Attachment.js#L127


If you want to completely override `Attachment` component, then you can pass `Attachment` prop as UI component to `Channel` or `MessageList` or `MessageSimple`. It will accept all the props listed [here](https://github.com/GetStream/stream-chat-react-native/blob/master/src/components/Attachment.js#L65).

I am not completely sure if that was your question or if that answers your question about attachment.

**Comment by earthlingstd** [comment]
Thanks @vishalnarkhede it can solve my issue now
