### ISSUE TITLE
Attachment Picker does not resize after orientation change.

### ISSUE THREAD

**Issue by dhruvtailor7** [GetStream/stream-chat-react-native#622]
**Describe the bug**
When the attachment picker is opened after the orientation is changed, it does not resize itself according to the screen. It only works on the orientation in which the screen was opened.

**Dev environment info (please complete/provide the following information):**

- stream-chat-react-native : 3.3.2
- react-native : 0.64.0
- Any Android/iOS device

**To Reproduce**

1. Open the screen with message input in portrait mode.
2. Open the attachment picker from the attach button in the message input.
3. Expand the attachment picker.
3. Change the orientation of the device to landscape.
4. Some part of the attachment picker go outside the screen.

**Expected behavior**
Attachment picker should resize according to the screen size.

**Additional Context**
The same happens with the image in the image gallery.

**Screenshots**
<img width="325" alt="Screenshot 2021-04-19 at 7 41 31 PM" src="https://user-images.githubusercontent.com/32268377/115250922-a8b33980-a147-11eb-8ef7-ecc9bc4080ff.png">
<img width="450" alt="Screenshot 2021-04-19 at 7 42 17 PM" src="https://user-images.githubusercontent.com/32268377/115250960-b10b7480-a147-11eb-830a-84291378b18b.png">

**Comment by vishalnarkhede** [comment]
Hey @dhruvtailor7 Currently we don't support landscape mode on Chat components. Its in our roadmap though. I can't give you exact timeline about it at the moment, but I will say somewhere around Q4 this year.

**Comment by deepesh-kn** [comment]
Hi @vishalnarkhede,

This feature was working on the old version i.e. before **3.0.0**. So the functionality that was working is now broken. This is a bug and not a feature request. 

This will restrict us to upgrade to the new version of SDK.

Do you expect your users not to use SDK on Tablets? Given the nature of the product, restricting the orientation on tablets to portrait mode is not an option.

Not supporting the landscape mode is a major setback for us. Hope you understand the concern and provide us the solution ASAP.
