### ISSUE TITLE
Android devices stop receiving push notifications

### ISSUE THREAD

**Issue by rodrigowpl** [GetStream/stream-chat-react-native#625]
Android devices stop receiving push notifications since yesterday and we did not change anything in our code or Firebase configuration. I'm also not seeing anything in the push logs in the dashboard.

Could we make a call with the engineering team or could you check your internal logs to try to figure out? I've also submitted a support ticket couple of minutes ago

**Comment by rodrigowpl** [comment]
Could you please take a look here @vishalnarkhede ?. I just need to see, at least, more logs to understand what's going on.

My support ticket code: 11357

**Comment by vishalnarkhede** [comment]
Moving conversation to ZD, since issue is not related to RN sdk!!
