### ISSUE TITLE
user_id is undefined in messageActions

### ISSUE THREAD

**Issue by jamesholcomb** [GetStream/stream-chat-react-native#626]
Trying to add a custom message action.  `message.user_id` is always undefined when long pressing a message, then tapping on the custom action (View User).

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native/stream-chat-expo)
    "stream-chat": "3.7.0",
    "stream-chat-react-native": "3.3.1",
- react-native or expo version: 0.63.4
- Device/Emulator (android/ios) and OS version: iOS 14 Emulator

**To Reproduce**

```js
<Channel
	  messageActions={({
	    blockUser,
	    copyMessage,
	    deleteMessage,
	    editMessage,
	    flagMessage,
	    message,
	    muteUser,
	    reply,
	    retry,
	    threadReply
	  }) => [
      {
        action: () =>
          routeStore.push("Profile", { userId: message.user_id }),
        title: "View User",
        icon: <User pathOpacity={0.5} />
      },
      copyMessage,
      editMessage,
      flagMessage,
      muteUser,
      reply,
      retry,
      threadReply,
      deleteMessage,
      blockUser
    ]}
    channel={channel}
    keyboardVerticalOffset={headerHeight}
>
```
**Expected behavior**
The user_id of the message is available

**Additional context**

**Screenshots**

**Comment by vishalnarkhede** [comment]
Hey @jamesholcomb I will check with backend team about whats happening here. But meanwhile, please use `message.user.id`.
