### ISSUE TITLE
Could not receive push notification

### ISSUE THREAD

**Issue by earthlingstd** [GetStream/stream-chat-react-native#63]
Hi team,

I can receive push notification using stream CLI `stream chat:push:test --user_id 'user_123'`. But I could not receive any notification when a new message is sent to a channel that I'm a member. Can you suggest if there is any further step that I need to setup?

Regards.

**Comment by Nekuromento** [comment]
Hello @earthlingstd,

Could you provide your stream application ID?
I am looking into your issue and will get back to you as soon as possible.

Thanks.

**Comment by earthlingstd** [comment]
@Nekuromento the app ID is

**Comment by tbarbugli** [comment]
@earthlingstd can you post the full output that you get from the CLI test command here?

**Comment by earthlingstd** [comment]
@tbarbugli 
```
```

**Comment by earthlingstd** [comment]
ah, I understand now, it looks like that you only allow to modify the notification object. What I'am trying to do is add the **data** object to the notification message, so that the app can handle the notification while it's on foreground.

**Comment by earthlingstd** [comment]
can you change the notification template to

**Comment by earthlingstd** [comment]
```

**Comment by Nekuromento** [comment]
@earthlingstd we will be deploying a feature allowing users to specify `data` template along with `notification` template before the end of the week. Thank you for your patience

**Comment by earthlingstd** [comment]
> At the moment, im trying to do this, but it does not seem to work, the **eq** function does not work
> 
> ```
> {
>     "title": "{{#eq channel.spaceType "personal"}}{{sender.name}}{{else}}{{sender.name }} in {{channel.name}}{{/eq}}",
>     "body": "{{ message.text }}",
>     "subtitle": "{{ channel.spaceType }} {{ message.threadID }}",
>     "click_action": "OPEN_ACTIVITY_1",
> 	"sound": "default"
> }
> ```

@Nekuromento @tbarbugli can you advise on this?

**Comment by tbarbugli** [comment]
can you post the output of the test push based on a message and template?

**Comment by earthlingstd** [comment]
@tbarbugli 
Here is the rendered Firebase notification that will be sent to your devices:
```
{
    "notification": {
        "badge": 42,
        "body": "Bbsjdjdjdhd",
        "click_action": "OPEN_ACTIVITY_1",
        "sound": "default",
        "subtitle": "personal ",
        "title": "Hai Le in bTCiyBhbz0T5FdP4LygQ"
    }
}
```

**Comment by socceroos** [comment]
@Nekuromento What is the status of the `data` feature in push notifications?

**Comment by Nekuromento** [comment]
@socceroos Feature is ready and is going through QA at the moment

**Comment by earthlingstd** [comment]
@Nekuromento  have you looked at the issue with #eq tag in the template?

**Comment by Nekuromento** [comment]
@earthlingstd we have `if` tag for checking if value is true and `equal` tag for comparing values

**Comment by kusalshrestha** [comment]
What is the status of this issue? I'm facing this now

**Comment by vishalnarkhede** [comment]
@bogdan-getstream

**Comment by bogdan-getstream** [comment]
Hi @kusalshrestha, we did many changes to our internal push notifications system, I need more details from you if you still have same issue
