### ISSUE TITLE
Can the messages already sent to the chat thread  highlighted with some colors?

### ISSUE THREAD

**Issue by parakramadr** [GetStream/stream-chat-react-native#635]

**Comment by vishalnarkhede** [comment]
@parakramadr I don't think I understand the question correctly. Could you please share some more details or some screenshot?

**Comment by parakramadr** [comment]
![Simulator Screen Shot - iPhone 12 - 2021-05-04 at 14 34 28](https://user-images.githubusercontent.com/8720962/116982005-e8e8ef00-ace5-11eb-9fe8-2d3efc7615f7.png)

I want to highlight some of the past chats with colors. Can I do that?.

**Comment by vishalnarkhede** [comment]
@parakramadr Whats the criteria for highlighting?

**Comment by parakramadr** [comment]
ITs just a client requirement to highlight some message texts. and is there any way that we can get the user id once we tap the @mentionuser in the message body?.

**Comment by vishalnarkhede** [comment]
Hey @parakramadr please take a look at our docs about customing message bubble - https://github.com/GetStream/stream-chat-react-native/wiki/Cookbook-v3.0#How-to-customize-message-component
