### ISSUE TITLE
Once we click the mentioned user in the past message , can we redirect to that users profile screen like Slack?

### ISSUE THREAD

**Issue by parakramadr** [GetStream/stream-chat-react-native#636]

**Comment by vanGalilea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/636?planning-poker) with ZenHub @Enigma-I-am @khushal87 @madsroskar

**Comment by vanGalilea** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/636?planning-poker) with ZenHub @santhoshvai

**Comment by vanGalilea** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/636?planning-poker) with ZenHub @vishalnarkhede

**Comment by Enigma-I-am** [comment]
Is there a design for this??? CC: @vanGalilea

**Comment by Enigma-I-am** [comment]
> Is there a design for this??? CC: @vanGalilea

I've found it...

**Comment by vishalnarkhede** [comment]
## Description

Currently we allow user to set `onPressMessage` handler on Channel component. It looks something like following:

```
<Channel
 onPressInMessage={({
   actionHandlers: {
       deleteMessage, // () => Promise<void>;
       editMessage, // () => void;
       quotedReply, // () => void;
       resendMessage, // () => Promise<void>;
       showMessageOverlay, // () => void;
       toggleBanUser, // () => Promise<void>;
       toggleMuteUser, // () => Promise<void>;
       toggleReaction, // (reactionType: string) => Promise<void>;
   },
   defaultHandler, // () => void
   event, // any event object corresponding to touchable feedback
   emitter, // which component trigged this touchable feedback e.g. card, fileAttachment, gallery, message, textMention ... etc
   message // message object on which longPress occured
 }) => {
   // Your custom action
 }}
/>

```

`emitter` param tells you about which part of the message was pressed exactly, `textMention` being one of them. So basically you can already attach on press handler for mentioned user name. The limitation is that you don't have access to the id of user whose name was pressed exactly. E.g., in case of slack, when you press on mentioned user's name ... you see a pop up with user details.

## Objective

Provide information about the user, whose mentioned name was pressed ... as part of `onPressMessage` function payload [here](https://github.com/GetStream/stream-chat-react-native/blob/develop/package/src/components/Message/MessageSimple/utils/renderText.tsx#L210). During the markdown rendering we only have access to the name of the user, but we can use that name to find user in `message.mentioned_users`.

We can introduce additional param in `MessageTouchableHandlerPayload` - `additionalInfo` as an object. And pass this user object as one of the keys. In future we can provide additional info regarding other emitters within this object as well.

## Acceptance Criteria

- Customer should have access to user information as part of `onPressMessage`, if `emitter` is `textMention`
- Example in documentation about how to implement press handler for mentioned user.
