### ISSUE TITLE
App Crash with evaluating 'delete animationCopy.callBack'

### ISSUE THREAD

**Issue by thomas-shares** [GetStream/stream-chat-react-native#640]
**Describe the bug**
I just upgraded my Expo App to Expo 41 and then I start the app I am getting this error: 

undefined not an object (evaluating 'delete animationCopy.callBack')
This is the error I am getting on Android. On iOS I don't even get this error, the app just crashes and doesn't show anything.

**Dev environment info (please complete/provide the following information):**
I am running     "stream-chat-expo": "3.3.3",  and Expo 41 
I am getting this error on a Android simulator, on a real Android device and on a real iOS device.

Here is my package.json and a screenshot of the error with stacktrace.

`{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@expo-google-fonts/source-code-pro": "^0.1.0",
    "@react-native-community/datetimepicker": "3.2.0",
    "@react-native-community/masked-view": "0.1.10",
    "@react-native-community/netinfo": "6.0.0",
    "@react-navigation/bottom-tabs": "^5.11.1",
    "@react-navigation/drawer": "^5.9.0",
    "@react-navigation/material-bottom-tabs": "^5.2.16",
    "@react-navigation/material-top-tabs": "^5.2.16",
    "@react-navigation/native": "^5.7.3",
    "@react-navigation/stack": "^5.9.0",
    "aws-amplify": "^3.3.12",
    "aws-amplify-react-native": "^4.2.10",
    "core-js": "^3",
    "expo": "^41.0.0",
    "expo-app-auth": "~10.1.2",
    "expo-app-loading": "^1.0.1",
    "expo-av": "~9.1.2",
    "expo-blur": "~9.0.3",
    "expo-constants": "~10.1.3",
    "expo-document-picker": "~9.1.2",
    "expo-file-system": "~11.0.2",
    "expo-font": "~9.1.0",
    "expo-haptics": "~10.0.0",
    "expo-image-manipulator": "~9.1.0",
    "expo-image-picker": "~10.1.4",
    "expo-linear-gradient": "~9.1.0",
    "expo-localization": "~10.1.0",
    "expo-media-library": "~12.0.2",
    "expo-permissions": "~12.0.1",
    "expo-secure-store": "~10.1.0",
    "expo-sharing": "~9.1.2",
    "expo-sqlite": "~9.1.0",
    "expo-status-bar": "~1.0.4",
    "i18n-js": "^3.8.0",
    "lodash": "^4.17.20",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz",
    "react-native-base64": "^0.1.0",
    "react-native-collapsible": "^1.5.3",
    "react-native-gesture-handler": "~1.10.2",
    "react-native-get-random-values": "~1.7.0",
    "react-native-global-props": "^1.1.5",
    "react-native-htmlview": "^0.16.0",
    "react-native-indicators": "^0.17.0",
    "react-native-paper": "^4.1.0",
    "react-native-reanimated": "~2.1.0",
    "react-native-safe-area-context": "3.2.0",
    "react-native-screens": "~3.0.0",
    "react-native-svg": "12.1.0",
    "react-native-swiper": "^1.6.0",
    "react-native-tab-view": "^2.15.1",
    "react-native-web": "~0.13.12",
    "stream-chat-expo": "3.3.3",
    "uuid": "^8.3.1"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0",
    "babel-preset-expo": "8.3.0"
  },
  "private": true
}
`
![Screenshot_1620381280](https://user-images.githubusercontent.com/1236049/117436892-c6e2ad00-af2f-11eb-8c51-6a99943f4a97.png)

**Comment by thomas-shares** [comment]
oh, and I have tried cleaning everything up as well:

`npm cache clean --force  && rm -rf /tmp/metro-cache/ &&   rm -rf node_modules/ && npm install --legacy-peer-deps && npm start`

and that doesn't make the problem go away.

**Comment by thomas-shares** [comment]
After some more experimenting it turns out that the fix described in the react-native-reanimated issue solves the problem. And thank you for this great product, it really has helped us a lot. Thank you!

**Comment by vokhuyetOz** [comment]
@thomas-shares , could you share with me which issue solves the problem?
Thank you

**Comment by thomas-shares** [comment]
@vokhuyetOz  I have a fork which solves this issue: https://github.com/Blue-Feniks/react-native-reanimated
I will make a PR for this and hopefully this will get merged.

**Comment by vokhuyetOz** [comment]
thanks. i had been resolved it by myself.
