### ISSUE TITLE
PushNotifications stopped working on both ios and android

### ISSUE THREAD

**Issue by tuneerclixlogix** [GetStream/stream-chat-react-native#656]
Our application is live and the push notification suddenly stopped working. I have checked in the adb logcat and there is no event received for its push notifications.
We also tried the testPushSettings method from our server to send test push notification to specific id but in its response we are getting 
data: {
      code: 4,
      message: 'CheckPush failed with error: "User has no enabled devices associated"',
      StatusCode: 400,
      duration: '0.00ms',
      more_info: 'https://getstream.io/chat/docs/api_errors_response'
    }

**Comment by tuneerclixlogix** [comment]
@vishalnarkhede I just checked and i don't think our this code is getting used, but we were getting notifications till now. Is it something that is also done from the sdk itself ?

**Comment by vishalnarkhede** [comment]
No we don't add devices from RN sdk. It needs to be done on application side!!

**Comment by tuneerclixlogix** [comment]
Okay @vishalnarkhede , It was working before somehow so I didn't noticed that . I added this method and now in debug mode for android I am receiving push notifications but not for iOS.
I tried following methods for iOS :
1. I sent the token generated by firebase package and kept the second parameter  as firebase (not receiving push)
2. I sent the token generated by @react-native-community/push-notification-ios package and kept the second parameter  as apn  (not receiving push)
Is there anything else that could be wrong ?

**Comment by vishalnarkhede** [comment]
We are currently working on moving our docs to recommend firebase for both iOS and Android. You can take a peek at this draft for firebase implementation for iOS and Android - https://github.com/GetStream/stream-chat-react-native/blob/vishal/docu-markdown/docusaurus/docs/React%20Native/Guides/push_notifications.mdx

**Comment by tuneerclixlogix** [comment]
@vishalnarkhede This issue was fixed after adding the device push notifications started working fine.
