### ISSUE TITLE
Cannot receive push notification

### ISSUE THREAD

**Issue by hongsa** [GetStream/stream-chat-react-native#66]
First, stream chat document(ios push) need to update!! 
https://getstream.io/chat/docs/#rn_push_ios

Because push notification ios library is updated.
Android is also different code in Manifest.
So Document need to be updated or tell me version

I do all document. But I cannot receive push.

app id = 56395
user_id = chatdemo01

please help me..

**Comment by Nekuromento** [comment]
@hongsa We will investigate any inconsistencies in the notification setup for ios
Also we are aware that at the moment it is impossible to specify `data` for Firebase notifications and will be releasing a fix before the end of the week.

Could you specify which parts of our documentation were not clear or didn't work for you?

**Comment by hongsa** [comment]
<ios>
stream chat document: PushNotificationIOS(react native)
react-native-push-notification: @react-native-community/push-notification-ios
-> It is different
<android>
stream chat document AndroidManifest.xml and 
https://github.com/zo0r/react-native-push-notification#android-manual-installation
> It is different

**Comment by siddharthJadhav** [comment]
@Nekuromento Did you find any solution because I am also facing the same issue.

**Comment by vishalnarkhede** [comment]
Hey we have published a new documentation for push with react-native - https://getstream.io/chat/docs/sdk/reactnative/guides/push-notifications/
