### ISSUE TITLE
ImageGallery displays in reverse order

### ISSUE THREAD

**Issue by RBrNx** [GetStream/stream-chat-react-native#670]
**Describe the bug**
First of all, thank you for open sourcing these components, the ImageGallery is probably the best example of Pinch/Pan/Swipe gestures with Reanimated v2 I've found online!

I'm trying to implement the ImageGallery component in my own JS project, so I copied the code and removed all the types from it, but left everything else intact. I also added an `images` prop to it so that it can receive my image objects instead of via context.

[Here is a Gist](https://gist.github.com/RBrNx/50498d889c00820ff554c38a5e503283) containing my changes so you can see the files are mostly stock.

Unfortunately it seems that while the images display correctly, and the pinch/pan/swipe functionality all works well, the actual order of the images is reversed, including their swipe positions. i.e the images in order are `[0, 1, 2, 3, 4]` but when rendered they are displayed as `[4, 3, 2, 1, 0]` with `0` being the starting index (so I need to swipe left --> right to view the "next" image.

**Dev environment info (please complete/provide the following information):**

- Expo SDK41
- Samsung Note 20 Ultra, Android 11

**To Reproduce**

1. Pass array of images to ImageGallery component
2. View 1st image in ImageGallery
3. Other images are rendered to the left of the 1st image

**Expected behavior**
Images should be rendered left to right, in order - with swiping right --> left to move to the next image.

**Screenshots**

https://user-images.githubusercontent.com/1332314/118640229-a2f55600-b7d0-11eb-9aa3-1be627cab806.mp4

**Comment by RBrNx** [comment]
On another note, I believe there is also a small bug in the `onPan` handler. I think [Line 426](https://github.com/GetStream/stream-chat-react-native/blob/master/src/components/ImageGallery/ImageGallery.tsx#L426) should be a single equals `=` instead of an equality check `===`.

**Comment by nhannah** [comment]
> On another note, I believe there is also a small bug in the `onPan` handler. I think [Line 426](https://github.com/GetStream/stream-chat-react-native/blob/master/src/components/ImageGallery/ImageGallery.tsx#L426) should be a single equals `=` instead of an equality check `===`.

Good catch.

**Comment by nhannah** [comment]
> **Describe the bug**
> First of all, thank you for open sourcing these components, the ImageGallery is probably the best example of Pinch/Pan/Swipe gestures with Reanimated v2 I've found online!
> 
> I'm trying to implement the ImageGallery component in my own JS project, so I copied the code and removed all the types from it, but left everything else intact. I also added an `images` prop to it so that it can receive my image objects instead of via context.
> 
> [Here is a Gist](https://gist.github.com/RBrNx/50498d889c00820ff554c38a5e503283) containing my changes so you can see the files are mostly stock.
> 
> Unfortunately it seems that while the images display correctly, and the pinch/pan/swipe functionality all works well, the actual order of the images is reversed, including their swipe positions. i.e the images in order are `[0, 1, 2, 3, 4]` but when rendered they are displayed as `[4, 3, 2, 1, 0]` with `0` being the starting index (so I need to swipe left --> right to view the "next" image.
> 
> **Dev environment info (please complete/provide the following information):**
> 
> * Expo SDK41
> * Samsung Note 20 Ultra, Android 11
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Pass array of images to ImageGallery component
> 2. View 1st image in ImageGallery
> 3. Other images are rendered to the left of the 1st image
> 
> **Expected behavior**
> Images should be rendered left to right, in order - with swiping right --> left to move to the next image.
> 
> **Screenshots**
> 
>  Screen_Recording_20210518-114330_Expo.Go.mp4

So for the reversal you will need to change some stuff in the components, this reversal was done after the original to fit our needs. `scaleX:  -1` needs to be removed from everywhere, there will also be other math changes I believe. This is the commit it was added in, you should be able to see the changes that were done to the math there. https://github.com/GetStream/stream-chat-react-native/commit/6f17e5ac9ca15b50b54b70c4ba8457ddd15ca9d5

**Comment by RBrNx** [comment]
@nhannah Ah fantastic, that's a great help, thank you!

While I've got you, would you be able to shed any light on the `AnimatedGalleryImage` component and the reasoning behind the choice to scale the image by 8x before translating and then reverting the scale back down?

**Comment by nhannah** [comment]
> @nhannah Ah fantastic, that's a great help, thank you!
> 
> While I've got you, would you be able to shed any light on the `AnimatedGalleryImage` component and the reasoning behind the choice to scale the image by 8x before translating and then reverting the scale back down?

Sorry closed before your questions appeared. Yes, that is a key to the whole thing actually, if you just scale the image you will see a quality loss going up from 0 -> X, if you try to change the image dimensions dynamically you will see very bad performance as the image will re-render on size change, this trick results in a high res zooming because you start the image at the largest zoom you allow, scale it down, then zooming will scale it back up. You can change the amount if you want just need to adjust some math is likely the case. Also the image list is sort of virtualized (not all rendered) to prevent a bunch of large images from being drawn at once.

**Comment by RBrNx** [comment]
Ahh that makes sense, I didn't even think about it from an image quality perspective! That's really helpful, thank you.

Hoping to try and reduce the number of "magic numbers" in some of the math, happy to PR those changes back into this codebase if I'm successful 😄

**Comment by RBrNx** [comment]
@nhannah Apologies, wanted to go through the full code and pick out the numbers I wasn't totally sure on 😊 

[Line 439](https://github.com/GetStream/stream-chat-react-native/blob/master/src/components/ImageGallery/ImageGallery.tsx#L439) - I wasn't sure what the `< 3` check was doing? (3 also seems to be used in multiple other places, [518](https://github.com/GetStream/stream-chat-react-native/blob/master/src/components/ImageGallery/ImageGallery.tsx#L518), [545](https://github.com/GetStream/stream-chat-react-native/blob/master/src/components/ImageGallery/ImageGallery.tsx#L545), [646](https://github.com/GetStream/stream-chat-react-native/blob/master/src/components/ImageGallery/ImageGallery.tsx#L646), [652](https://github.com/GetStream/stream-chat-react-native/blob/master/src/components/ImageGallery/ImageGallery.tsx#L652), are these for the same reason?

```js
if (Math.abs(evt.translationX / evt.translationY) > maxXYRatio && (Math.abs(-halfScreenWidth * (scale.value - 1) - offset.x.value) < 3 || Math.abs(halfScreenWidth * (scale.value - 1) - offset.x.value) < 3))
```

[Line 484](https://github.com/GetStream/stream-chat-react-native/blob/master/src/components/ImageGallery/ImageGallery.tsx#L484) - I wasn't sure how the `(1 - (1 / 3` fit in to the calculation?

```js
if (currentImageHeight * offsetScale.value < screenHeight && translate.y.value > 0) {
    scale.value = offsetScale.value * (1 - (1 / 3) * (translate.y.value / screenHeight));
}
```

[Line 640](https://github.com/GetStream/stream-chat-react-native/blob/master/src/components/ImageGallery/ImageGallery.tsx#L640) - The `+8` seemed a bit magic? 😅 

```js
if (finalYPosition > halfScreenHeight && offset.y.value + 8 >= (currentImageHeight / 2) * scale.value - halfScreenHeight &&
```

I managed to work out the min/max scale factors, but thanks for letting me know about the 64 value, that makes more sense now! I think the velocity choices all work well, nothing feels too slow or fast, so good job on that!

Again, thank you for the help, I really appreciate it 🙏

**Comment by nhannah** [comment]
> @nhannah Apologies, wanted to go through the full code and pick out the numbers I wasn't totally sure on 😊
> 
> [Line 439](https://github.com/GetStream/stream-chat-react-native/blob/master/src/components/ImageGallery/ImageGallery.tsx#L439) - I wasn't sure what the `< 3` check was doing? (3 also seems to be used in multiple other places, [518](https://github.com/GetStream/stream-chat-react-native/blob/master/src/components/ImageGallery/ImageGallery.tsx#L518), [545](https://github.com/GetStream/stream-chat-react-native/blob/master/src/components/ImageGallery/ImageGallery.tsx#L545), [646](https://github.com/GetStream/stream-chat-react-native/blob/master/src/components/ImageGallery/ImageGallery.tsx#L646), [652](https://github.com/GetStream/stream-chat-react-native/blob/master/src/components/ImageGallery/ImageGallery.tsx#L652), are these for the same reason?)
> 
> ```js
> if (Math.abs(evt.translationX / evt.translationY) > maxXYRatio && (Math.abs(-halfScreenWidth * (scale.value - 1) - offset.x.value) < 3 || Math.abs(halfScreenWidth * (scale.value - 1) - offset.x.value) < 3))
> ```
> 
> [Line 484](https://github.com/GetStream/stream-chat-react-native/blob/master/src/components/ImageGallery/ImageGallery.tsx#L484) - I wasn't sure how the `(1 - (1 / 3` fit in to the calculation?
> 
> ```js
> if (currentImageHeight * offsetScale.value < screenHeight && translate.y.value > 0) {
>     scale.value = offsetScale.value * (1 - (1 / 3) * (translate.y.value / screenHeight));
> }
> ```
> 
> [Line 640](https://github.com/GetStream/stream-chat-react-native/blob/master/src/components/ImageGallery/ImageGallery.tsx#L640) - The `+8` seemed a bit magic? 😅
> 
> ```js
> if (finalYPosition > halfScreenHeight && offset.y.value + 8 >= (currentImageHeight / 2) * scale.value - halfScreenHeight &&
> ```
> 
> I managed to work out the min/max scale factors, but thanks for letting me know about the 64 value, that makes more sense now! I think the velocity choices all work well, nothing feels too slow or fast, so good job on that!
> 
> Again, thank you for the help, I really appreciate it 🙏

Ah ok, the `3` is t account for some rounding with the animations, when you hit an edge and bounce back in a perfect world  `Math.abs(halfScreenWidth * (scale.value - 1) - offset.x.value)` would equal `0`, but it does not always, so there is a buffer.

The 1/3 is just a visual choice for how much the image should shrink when dragging it down and "away".

The `+8` was another choice by feel, basically the image should be moved down already by 8 from the top of the screen before considering closing the viewer. If I recall I did this because when swiping fast at times you could accidentally swipe down too quick more than left or right and accidentally close the picker.
