### ISSUE TITLE
MessageInput not autofocus keyboad when appending .

### ISSUE THREAD

**Issue by parakramadr** [GetStream/stream-chat-react-native#674]
Hi,

When I append the text (using appendText method of Input) to the MessageInput component for IOS devices the keyboard appear but for android devices the key board not appearing . To appear the keyboard in android I need to touch the input filed. I tried the autocous as below but not working. I want to focus the keyboard when the appending the text .

I tried this 

  <MessageInput
          Input={InputBox}
          maxNumberOfFiles={3}
          sendImageAsync={true}
          compressImageQuality={0.5}
          additionalTextInputProps={{
            autoFocus: true,
.......
.....

**Comment by vishalnarkhede** [comment]
Have you tried following?

```tsx
const inputRef = useRef();
<Channel // or MessageInput
  setInputRef={ref => inputRef.current = ref}
/>

appendText('test text');
inputRef.focus();
```
