### ISSUE TITLE
Reactions in thread not reactive

### ISSUE THREAD

**Issue by lucaswhitman** [GetStream/stream-chat-react-native#676]
**Describe the bug**
Reactions are not immediately appearing in threads. You have to leave the thread and come back before they display. We've done a lot of customization but most of it is visual. Seems more like a reactivity problem.

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native/stream-chat-expo)
```
    "stream-chat": "3.9.0",
    "stream-chat-react-native": "3.4.0",
```
- react-native or expo version
```
"react-native": "0.64.1",
```

- Device/Emulator (android/ios) and OS version
<img width="159" alt="Screen Shot 2021-05-21 at 13 17 53" src="https://user-images.githubusercontent.com/7506979/119187723-f537b080-ba36-11eb-8237-9f5007e29b90.png">

**To Reproduce**

(full behavior in video)

1. Navigate to thread
2. React to parent message
3. See no reaction

**Expected behavior**
Reactions added to messages in threads should appear immediately.

**Additional context**
See video

**Screenshots**

https://user-images.githubusercontent.com/7506979/119188196-94f53e80-ba37-11eb-971f-66f14242c47a.mp4

**Comment by lucaswhitman** [comment]
@vishalnarkhede just checking in, any thoughts on this one before we dive in and try and patch it?

**Comment by vishalnarkhede** [comment]
Hey @lucaswhitman let me take a look at it next week. Thanks for bringing this up!!

**Comment by lucaswhitman** [comment]
@vishalnarkhede any progress?

**Comment by lucaswhitman** [comment]
Okay, figured this out and patched ourselves since no one was responding.

```
--- a/node_modules/stream-chat-react-native-core/src/components/Thread/components/ThreadFooterComponent.tsx
+++ b/node_modules/stream-chat-react-native-core/src/components/Thread/components/ThreadFooterComponent.tsx
@@ -163,6 +163,7 @@ const areEqual = <
   const threadEqual =
     prevThread?.id === nextThread?.id &&
     prevThread?.text === nextThread?.text &&
+    prevThread?.latest_reactions === nextThread?.latest_reactions &&
     prevThread?.reply_count === nextThread?.reply_count;
   if (!threadEqual) return false;
 ```

**Comment by vishalnarkhede** [comment]
Hey @lucaswhitman sorry for the delays. But ideally we want the thread parent message to be non-interactive. We have added this change as part of v3.6.0
