### ISSUE TITLE
Stale ChannelList after multiple quick renders with changing Filter prop

### ISSUE THREAD

**Issue by jehartzog** [GetStream/stream-chat-react-native#678]
**Describe the bug**
If the screen which creates the `filter` prop for `ChannelList` quickly renders two or more different `filters`, only the first filter will be fetched, with the subsequent filters being discarded. This results in a stale `ChannelList` until it is manually refreshed.

**Dev environment info:**

```
    "react-native": "0.64.1",
    "stream-chat": "3.9.0",
    "stream-chat-react-native": "3.4.0",
```

**To Reproduce**

1. Set up a screen with a `ChannelList`
2. Initially pass an empty filter prop, such as `{members: {$in: ['']}}`
3. Immediately (before the API call has completed) re-render with an updated filter prop, such as `{members: {$in: [userStore.user.streamUuid || '']}}`

**Expected behavior**
- You eventually end up with the channel list as rendered from the final `filter` prop provided

**Actual behavior**
- Only the first `filter` prop sent in the quick series is used, all other are discarded

**Additional context**
The error comes from [this line](https://github.com/GetStream/stream-chat-react-native/blob/accadd2c234c341943cd555a316d8eb8ed050d7a/src/components/ChannelList/hooks/usePaginatedChannels.ts#L74) which cancels calls if there are currently pending calls. I completely get why this sort of logic is needed, but it's pretty common for React to initially render a zero state, quickly followed by more data as it is retrieved asynchronously.

If the rate limiting is still desired (which I see why it should be), it could be done via `throttle` function which is always sure to execute the tailing update, but no more than `x` updates every `y` milliseconds, to avoid excessive calls.

**Comment by vishalnarkhede** [comment]
Hey @jehartzog I don't think you should render ChannelList component with filters - `{members: {$in: ['']}}`. You should simply show some loading indicator until `streamUuid` is ready. Otherwise you are requesting results, which don't belong to that user ... kinda security issue!!

**Comment by jehartzog** [comment]
@vishalnarkhede Thanks for quick response!

I simplified the code a little bit to try to keep the reproduction free of our specific business logic, but thanks for the heads up on how to do with zero state.

Let me shift over to a more realistic version to show why the line of code I mentioned above is problematic.
```
const filters = { members: {$in:  connectedPeopleStreamUuids } }
const memoizedFilters = React.useMemo(() => , [connectedPeopleStreamUuids]);
```
Repro goes like this:

1. App is loaded, state data hydrated from AsyncStorage, `connectedPeopleStreamUuids` has one entry in it.
2. On app load, our code sends API call to get any updates to `connectedPeopleStreamUuids`.
3. The first render of ChannelList fires with `connectedPeopleStreamUuids` having one entry.
4. Right after :this render, the our API call returns, adding another entry to `connectedPeopleStreamUuids`

The expectation here is the ChannelList will always stay in sync with the last `filter` applied, but if #4 happens while the stream API call is still pending, it will be dropped completely, resulting in stale state.

You're correct that there are many ways to mitigate this by the client app logic, but they all involving considering this edge base behavior any time `filters` is modified. And since the race conditions are non-deterministic, it's challenging to catch these consistently in testing. It would be much easier to use ChannelList if it always made sure to grab the latest lists of channels based on the very last `filter` prop sent to it.

**Comment by vishalnarkhede** [comment]
@jehartzog let me take a look at it next week. Thanks for detailed explanation :)

**Comment by vishalnarkhede** [comment]
For internal tracking purpose - https://stream-io.atlassian.net/browse/CRNS-447

**Comment by vishalnarkhede** [comment]
Hey @jehartzog we have published our next major version of RN Chat SDK - `v4.1.0` 🎉.

This release includes the fix for this issue. Please take a look at [**Release Notes**](https://github.com/GetStream/stream-chat-react-native/releases/tag/v4.1.0) for details.
