### ISSUE TITLE
Date format is invalid in a message list

### ISSUE THREAD

**Issue by YohaanYoon** [GetStream/stream-chat-react-native#680]
**Describe the bug**
I guess a date format or translation key of dayjs is invalid in a message list of stream-chat-react-native. 
The date is displayed an attached image as follow:

<img src = https://user-images.githubusercontent.com/59902686/110083811-800ef480-7dd2-11eb-8a51-9fe2d02efdcf.jpg width = "40%">

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native/stream-chat-expo)
stream-chat-react-native 3.2.0
- react-native or expo version
react-native
- Device/Emulator (android/ios) and OS version
All os and versions

**To Reproduce**

1. Go to channel list
2. Click on a channel
3. See error on a date

**Expected behavior**

**Additional context**

**Screenshots**

**Comment by vishalnarkhede** [comment]
@YohaanYoon Can you please try upgrading to 3.4.0? We have introduced inline date separators as part of latest releases which are better choice for message dates,

**Comment by vishalnarkhede** [comment]
@YohaanYoon Well the format definitely exists https://day.js.org/docs/en/display/format#list-of-all-available-formats

Probably it doesn't work with the given language. Could you please tell me which language are you using?

**Comment by YohaanYoon** [comment]
@vishalnarkhede 
I am using Korean.
Anyway, I guess 'LL'  is more common date format.

**Comment by nhannah** [comment]
LL is not the preferred structure for this as it gives long form month and year unnecessarily. You can replace any of these though....
```
const streami18n = new Streami18n({
  dayjsLocaleConfigForLanguage: {
    monthsShort: '1월_2월_3월_4월_IamMAYinKO_6월_7월_8월_9월_10월_11월_12월'.split('_'),
  },
  language: 'ko',
});
```

will display `IamMAYinKO 26` today doing this.

**Comment by YohaanYoon** [comment]
https://github.com/iamkun/dayjs/blob/06f88f425828b1ce96b737332d25145a95a4ee9d/src/locale/ko.js#L16

As you shown in github reference (the Korean translation for dayjs), D is needed one more character (일) in the Korean.
When you used `MMM D`, `MMM` looks fine, but, `D` looks very weird in the Korean.
If `LL` or `LLL` is too long, I recommend `L` format.
Please consider it and let me know the result of the consideration.

@nhannah @vishalnarkhede
