### ISSUE TITLE
Disabling Markdown

### ISSUE THREAD

**Issue by lucaswhitman** [GetStream/stream-chat-react-native#684]
This isn't a bug so much as a question. We're wanting to disable any markdown, the docs here say it's possible but I've yet to find the actual steps to do this and I'm not seeing options in the code:

https://getstream.io/chat/docs/react-native/markdown/

Can you point me in the right direction @vishalnarkhede? Thanks in advance.

**Comment by lucaswhitman** [comment]
Figured out how to override by passing in a set of `null` rules, I'd love to hear more if there's a better way to do it. Closing for now though.

**Comment by andrewbeckman** [comment]
@lucaswhitman I've tried passing null to markdownRules and it hasn't fixed it for me. Is that what worked for you? @vishalnarkhede any pointers on how to disable this? Supporting markdown by default was very surprising to us as we're building a social app for a non-technical consumer audience.

**Comment by lucaswhitman** [comment]
@andrewbeckman here's what we did:

```
const rulesOverride = {
  Array: null,
  heading: null,
  nptable: null,
  lheading: null,
  hr: null,
  codeBlock: null,
  fence: null,
  blockQuote: null,
  list: null,
  def: null,
  table: null,
  tableSeparator: null,
  image: null,
  reflink: null,
  refimage: null,
  em: null,
  strong: null,
  u: null,
  del: null,
  inlineCode: null,
  br: null,
};

<Channel<
  LocalAttachmentType,
  LocalChannelType,
  LocalCommandType,
  LocalEventType,
  LocalMessageType,
  LocalResponseType,
  LocalUserType
>
    channel={channel}
    thread={thread}
    ....
    // @ts-expect-error stream doesn't like it but it does the job
    markdownRules={rulesOverride}
    ....
 </Channel>
```

**Comment by andrewbeckman** [comment]
Thanks @lucaswhitman!
