### ISSUE TITLE
 Images not uploading for when use  onChange in AutoCompleteInput

### ISSUE THREAD

**Issue by parakramadr** [GetStream/stream-chat-react-native#691]
I use AutoCompleteInput like this. My prob is 

```jsx
<AutoCompleteInput
            {...props}
            setInputBoxRef={autoCompleteInput}
            additionalTextInputProps={additionalTextInputProps}
            value={value}
            {...additionalTextInputProps}
            onChange={(text) => onChangeText(text)}
            
          />
           <TouchableOpacity onPress={onPressSend}>
              <Image
                ref={sendButton}
                source={
                  value.length > 0 ? send_active_icon : send_inactive_icon
                }
                resizeMethod={"auto"}
                resizeMode={"contain"}
                style={styles.buttonIcon}
              />


    onPressSend = async () => {
    setMentionSelected(false);
    const sendVal = value;

    setValue("");
 

    await sendMessage(); // This not working for text messages .


//if i use it like below its working  but after that images not uploading.
  //await channel.sendMessage({
      //text: sendVal,
   // });



    console.log(props);
  };
```

@vishalnarkhede

**Comment by vishalnarkhede** [comment]
@parakramadr where are you accessing `sendMessage` function in following line?
```
    await sendMessage(); // This not working for text messages .

```

**Comment by parakramadr** [comment]
I use custom InputBox and access the get the sendMessage() method from there like below.

export const InputBox = forwardRef((props, ref) => {

  const {
    _pickFile,
    _pickImage,
    appendText,
    isValidMessage,
    sendMessage,
    updateMessage,
    _uploadImage,
  } = props;

after that once i click the custom send button it calls this method

onPressSend = async () => {
    setMentionSelected(false);
    const sendVal = value;

    setValue("");
 

    await sendMessage(); // This not working for text messages . But works for images.


//if i use it like below its working  but after that images not uploading.
  //await channel.sendMessage({
      //text: sendVal,
   // });



    console.log(props);
  };

**Comment by vishalnarkhede** [comment]
@parakramadr you should access sendMessage from `MessageInputContext`. E.g., https://github.com/GetStream/react-native-samples/blob/main/projects/slack-clone/src/components/SendButton.js

**Comment by parakramadr** [comment]
@vishalnarkhede I am using "stream-chat": "2.11.5", "stream-chat-react-native": "2.2.2". I cannot find MessageInputContext there. I cant upgrade to v3. how can I achieve that?

**Comment by vishalnarkhede** [comment]
Hey @parakramadr do you still need help with this?
