### ISSUE TITLE
react warning about state update on an unmounted component

### ISSUE THREAD

**Issue by giautm** [GetStream/stream-chat-react-native#693]
**Describe the bug**
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
```

I found the bug happened in: `useStreami18n.ts`, `usePaginatedChannels.ts` and `useIsOnline.ts`

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native/stream-chat-expo): 3.5.0
- react-native or expo version: 41.0.1
- Device/Emulator (android/ios) and OS version: iOS/Simulator

**To Reproduce**

Run the example then save to trigger fast refresh.

**Expected behavior**
No warning about state update.

**Comment by vishalnarkhede** [comment]
Hey @giautm we have added this to our backlog, and we will pick this up soon.
