### ISSUE TITLE
i18n: missing translation for _Message deleted_

### ISSUE THREAD

**Issue by giautm** [GetStream/stream-chat-react-native#694]
https://github.com/GetStream/stream-chat-react-native/blob/344442379e419ead818c09d15018f254f6bc977e/src/components/Message/MessageSimple/MessageDeleted.tsx#L135

**Comment by vishalnarkhede** [comment]
Thanks for bringing this up @giautm , we will fix it in next patch!!

**Comment by giautm** [comment]
Still not fix in the latest release 🥲

**Comment by tsirlucas** [comment]
@giautm will be in the next one. probably early next week.
