### ISSUE TITLE
ChannelList default onAddedToChannel prop ignores filters prop

### ISSUE THREAD

**Issue by jehartzog** [GetStream/stream-chat-react-native#697]
**Describe the bug**
If you apply a set of filters to `ChannelList`, these are ignored by the default `onAddedToChannel` event. After being added to a channel, it will show up in the `ChannelList`, even if the filters should remove it. After a `ChannelList` refresh, the newly added channel will go away.

**Dev environment info:**

```
    "react-native": "0.64.1",
    "stream-chat": "3.9.0",
    "stream-chat-react-native": "3.4.0"
```

**To Reproduce**

1.
```tsx
<ChannelList
  filters={{members: {$in: ['I_ABSOLUTELY_DO_NOT_EXIST']}}}
/>
```
2. See that no channels are loaded
3. Via API (in our case), add this client to a stream channel that we don't yet desire to show on the client.

**Expected behavior**
- `ChannelList` remains unchanged, empty

**Actual behavior**
- `ChannelList` immediately shows the newly added channel, despite the filter

**Additional context**
We were able to work around this quite simply once we figured out what was going on:

```tsx
<ChannelList
  filters={{members: {$in: ['I_ABSOLUTELY_DO_NOT_EXIST']}}}
  onAddedToChannel={() => {}}
/>
```

**Comment by vishalnarkhede** [comment]
Hey @jehartzog we generally send `notification.added_to_channel` to all members of channel. We don't keep track of filters applied. So the solution which you used, is correct.
