### ISSUE TITLE
Introduction of Reanimated 2 prevents remote debugging

### ISSUE THREAD

**Issue by jamesdunay** [GetStream/stream-chat-react-native#701]
** sorry for previous issue, made it under the company account. 

Hey guys, we've recently upgraded out stream-chat-react-native from 2.0.0 to 3.0.0. So far the team is really enjoying all of the new stuff we get out of the box. The UI is beautiful and its just as easy to implement as before.

However, one thing irking the team is the introduction of Reanimated 2, and specifically the introduction of Turbo Modules and the conflict that creates with remote debugging. It seems to me that this is a giant loss compared to the few animations that exist in the new stream chat version. I was wondering if this is something that you have discussed on your side?

We're currently using Flipper to attempt to bridge the gap but it's cumbersome. Do you guys have any suggestions or thoughts on the issue?

Thanks!

**Comment by nhannah** [comment]
Hi James,

Flipper is currently the only solution for full debugging. But there are many uses of Reaniamted 2 throughout the SDK to provide gesture based interactions, the image picker, the [image gallery](https://github.com/GetStream/stream-chat-react-native/blob/master/src/components/ImageGallery/ImageGallery.tsx), the swipe gestures on overlays, plus all the smaller animations as noted. So the use of it was not taken lightly. The JavaScript Interface (and Turbo Modules and Fabric) are the direction the React Native team is taking the project on the whole so it is inevitable there will be bumps in the transition. The [limitations are known](https://docs.swmansion.com/react-native-reanimated/docs/#known-problems-and-limitations). Reanimated 2 was released over a year ago now so sticking with reanaimeted 1 would have left us with a lot of tech debt on the major overhaul we did.
