### ISSUE TITLE
Trying to use a fork version. Native handler was not registered error.

### ISSUE THREAD

**Issue by FabDuarte** [GetStream/stream-chat-react-native#703]
Hi, 
I know there are several ways to customize the chats, through themes and specific components, but still, we need to do some small changes to the Reply component.

We did a fork on Github and then we tried to use the fork URL in the `package.json` but we are getting an error saying "Native handler was not registered (see image below)"

**Dev environment info:**

- Package version: v3.5.0
- react-native:  0.64.1
- Device: Emulator - iPhone 11 Pro Max

**To Reproduce**

1. Change the `package.json` dependency to use the github URL. For example: `"stream-chat-react-native": "https://github.com/GetStream/stream-chat-react-native.git#758cea0",`
2. Run a sample app
3. See error

**Screenshots**
![Simulator Screen Shot - iPhone 11 Pro Max - 2021-06-07 at 16 11 58](https://user-images.githubusercontent.com/32754430/121085177-ed5a6900-c7b7-11eb-989f-0ccbab7df0a8.png)

Does anybody know how to fix this? 

Thanks.

**Comment by vishalnarkhede** [comment]
@FabDuarte quick hint ... `stream-chat-react-native` package is this one https://github.com/GetStream/stream-chat-react-native/tree/master/native-package. The root directory is `stream-chat-react-native-core`

**Comment by FabDuarte** [comment]
Let me know If I understand how we should do it:
We fork this repository and then in the package.json we'll have these dependencies?

```json
"stream-chat-react-native": "3.5.0",
"stream-chat-react-native-core": "https://github.com/GetStream/stream-chat-react-native.git#758cea0"
```

Thanks

**Comment by FabDuarte** [comment]
@vishalnarkhede I did what I commented earlier, the app is working now, but I don't see my changes on the forked version.
Do you know why?

**Comment by vishalnarkhede** [comment]
@FabDuarte maybe this is helpful? https://github.com/GetStream/stream-chat-react-native/wiki/Dev-setup-for-contributing-to-the-library#-300

**Comment by FabDuarte** [comment]
@vishalnarkhede we couldn't make it work.
I think that document is outdated becasue if you run `yarn link;` inside the `stream-chat-react-native` folder, it will create a link for the core library instead. That's different on the documentation.

And when using the link reference on the package.json we are getting errors, the library is not found, even when we see it on the node_modules.

Are we missing something?
