### ISSUE TITLE
(0, _reactNativeReanimated.useSharedValue) is not a function. I was following this https://getstream.io/chat/react-native-chat/tutorial/#add-stream-chat-to-your-application tutorial to integration Stream Chat within my app. However I got this error.

### ISSUE THREAD

**Issue by liviavinci** [GetStream/stream-chat-react-native#704]
TypeError: (0, _reactNativeReanimated.useSharedValue) is not a function. (In '(0, _reactNativeReanimated.useSharedValue)(0)', '(0, _reactNativeReanimated.useSharedValue)' is undefined)

This error is located at:
    in Spinner{spinner} (at LoadingIndicator.tsx:32)
    in RCTView (at View.js:34)
    in View (at LoadingIndicator.tsx:31)
    in LoadingIndicatorWrapper (at LoadingIndicator.tsx:64)
    in LoadingIndicator{loadingIndicator} (at MessageList.tsx:948)
    in RCTView (at View.js:34)
    in View (at MessageList.tsx:947)
    in MessageListWithContext (at MessageList.tsx:1094)
    in MessageList (at NotificationScreen/index.js:39)
    in RCTView (at View.js:34)
    in View (at NotificationScreen/index.js:38)
    in RCTView (at View.js:34)
    in View (at Channel.tsx:1850)
    in MessageInputProvider (at Channel.tsx:1847)
    in SuggestionsProvider (at Channel.tsx:1846)
    in ThreadProvider (at Channel.tsx:1845)
    in MessagesProvider (at Channel.tsx:1842)
    in PaginatedMessageListProvider (at Channel.tsx:1839)
    in TypingProvider (at Channel.tsx:1838)
    in ChannelProvider (at Channel.tsx:1837)
    in RCTView (at View.js:34)
    in View (at KeyboardCompatibleView.tsx:257)
    in KeyboardProvider (at KeyboardCompatibleView.tsx:256)
    in KeyboardCompatibleView (at Channel.tsx:1831)
    in ChannelWithContext (at Channel.tsx:1895)
    in Channel (at NotificationScreen/index.js:37)
    in ThemeProvider (at Chat.tsx:214)
    in TranslationProvider (at Chat.tsx:213)
    in ChatProvider (at Chat.tsx:212)
    in ChatWithContext (at Chat.tsx:254)
    in Chat (at NotificationScreen/index.js:35)
    in ChannelScreen (at NotificationScreen/index.js:129)
    in RNCSafeAreaProvider (at SafeAreaContext.tsx:76)
    in SafeAreaProvider (at NotificationScreen/index.js:128)
    in NotificationScreen (at connectUser.js:36)
    in connectUser (created by Connect(connectUser))
    in Connect(connectUser) (at SceneView.tsx:122)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:115)
    in EnsureSingleNavigator (at SceneView.tsx:114)
    in SceneView (at useDescriptors.tsx:153)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:245)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:244)
    in RCTView (at View.js:34)
    in View (at CardSheet.tsx:33)
    in ForwardRef(CardSheet) (at Card.tsx:573)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:555)
    in PanGestureHandler (at GestureHandlerNative.tsx:13)
    in PanGestureHandler (at Card.tsx:549)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:544)
    in RCTView (at View.js:34)
    in View (at Card.tsx:538)
    in Card (at CardContainer.tsx:206)
    in CardContainer (at CardStack.tsx:623)
    in RCTView (at View.js:34)
    in View (at Screens.tsx:84)
    in MaybeScreen (at CardStack.tsx:616)
    in RCTView (at View.js:34)
    in View (at Screens.tsx:54)
    in MaybeScreenContainer (at CardStack.tsx:498)
    in CardStack (at StackView.tsx:462)
    in KeyboardManager (at StackView.tsx:458)
    in SafeAreaProviderCompat (at StackView.tsx:455)
    in RCTView (at View.js:34)
    in View (at StackView.tsx:454)
    in StackView (at createStackNavigator.tsx:87)
    in StackNavigator (at NotificationStack.js:14)
    in NotificationStack (at SceneView.tsx:122)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:115)
    in EnsureSingleNavigator (at SceneView.tsx:114)
    in SceneView (at useDescriptors.tsx:153)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:245)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:244)
    in RCTView (at View.js:34)
    in View (at CardSheet.tsx:33)
    in ForwardRef(CardSheet) (at Card.tsx:573)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:555)
    in PanGestureHandler (at GestureHandlerNative.tsx:13)
    in PanGestureHandler (at Card.tsx:549)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:544)
    in RCTView (at View.js:34)
    in View (at Card.tsx:538)
    in Card (at CardContainer.tsx:206)
    in CardContainer (at CardStack.tsx:623)
    in RCTView (at View.js:34)
    in View (at Screens.tsx:84)
    in MaybeScreen (at CardStack.tsx:616)
    in RCTView (at View.js:34)
    in View (at Screens.tsx:54)
    in MaybeScreenContainer (at CardStack.tsx:498)
    in CardStack (at StackView.tsx:462)
    in KeyboardManager (at StackView.tsx:458)
    in RNCSafeAreaProvider (at SafeAreaContext.tsx:76)
    in SafeAreaProvider (at SafeAreaProviderCompat.tsx:42)
    in SafeAreaProviderCompat (at StackView.tsx:455)
    in RCTView (at View.js:34)
    in View (at StackView.tsx:454)
    in StackView (at createStackNavigator.tsx:87)
    in StackNavigator (at Router/index.js:58)
    in RootNavigator (at connectUser.js:36)
    in connectUser (created by Connect(connectUser))
    in Connect(connectUser) (at Core/index.js:48)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:409)
    in ForwardRef(BaseNavigationContainer) (at NavigationContainer.tsx:91)
    in ThemeProvider (at NavigationContainer.tsx:90)
    in ForwardRef(NavigationContainer) (at Core/index.js:47)
    in PersistGate (at Core/index.js:46)
    in Provider (at Core/index.js:45)
    in App (at gestureHandlerRootHOC.tsx:13)
    in RCTView (at View.js:34)
    in View (at gestureHandlerRootHOC.tsx:12)
    in gestureHandlerRootHOC(App) (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)

**Comment by vishalnarkhede** [comment]
Hey @liviavinci you are missing the installationsteps for Reanimated package - https://docs.swmansion.com/react-native-reanimated/docs/2.0.0-rc.2/installation#installing-the-package
