### ISSUE TITLE
File Picker modal is cutoff at the bottom

### ISSUE THREAD

**Issue by jaredpiedt** [GetStream/stream-chat-react-native#719]
**Describe the bug**
File Picker modal is cutoff at the bottom.

**Dev environment info:**

- stream-chat-expo
- 3.6.0-rc.0
- iPhone 12 Pro, iOS 14.6

**To Reproduce**

1. Go to channel screen
2. Click on attachment icon
3. Click on file picker icon
4. Notice the "Recents" and "Browse" buttons are cut off

**Expected behavior**
Expect modal to not be cutoff

**Additional context**
This is reproducible in the `examples/ExpoMessaging` app.

**Screenshots**
<img src="https://user-images.githubusercontent.com/6234815/122956866-637dd480-d34f-11eb-8976-e60fbc99b72a.png" width="400px" />

**Comment by jaredpiedt** [comment]
This also happens on the camera screen as well:

<img src="https://user-images.githubusercontent.com/6234815/122957607-19e1b980-d350-11eb-8951-b138dc876a78.png" width="400px" />

**Comment by vishalnarkhede** [comment]
Hey @jaredpiedt this issues seems to be inherent with `expo-document-picker` package, which I can see in this example as well - https://snack.expo.dev/@vishalnarkhede/document-picker

So I don't think we can do much about it. Please raise it with Expo :)
