### ISSUE TITLE
Thread Screen align message as Top (as right now its bottom align)

### ISSUE THREAD

**Issue by kinjal34** [GetStream/stream-chat-react-native#722]
Image upload continue loading and pdf working fine, yes checked doc and also demo,
 
@AnatolyRugalev can you please check!
 
 Check attachment,

 also I am using react-native-steam-chat v 3.0.0

**Comment by vishalnarkhede** [comment]
Hey @kinjal34 Do you get some error in console?

**Comment by kinjal34** [comment]
@vishalnarkhede This is fixed now its working I changed customisation so working now!!

Now didn't find solution for emoji keyboard do you have any idea to open emoji keyboard ?

Below screen which contains button for emoji but not any solution for how to open emoji keyboard! 


![deskk](https://user-images.githubusercontent.com/86356067/123812614-d9ff7100-d911-11eb-901c-f39f000efa73.png)

**Comment by kinjal34** [comment]
@vishalnarkhede  can you please update as its minor UI change ?

how can we align thread all message align from top. right now its bottom align.

**Comment by vishalnarkhede** [comment]
Hey @kinjal34 we have added this feature to our backlog. This involves implementing pagination support in forward direction, instead of backwards direction (the default behavior), so can't simply be a UI change.
