### ISSUE TITLE
setImages undefined after attempted upgrade

### ISSUE THREAD

**Issue by russellsutt** [GetStream/stream-chat-react-native#732]
Trying to upgrade Stream Chat. Upgrade now produces setImage in MessageList is undefined.

- New Package version (stream-chat-react-native/stream-chat-expo)
        "stream-chat": "^3.11.0",
        "stream-chat-react-native": "^3.6.0",
        "react-native": "^0.62.0",

- Current, Working package versions:
         "stream-chat": "^1.7.0",
         "stream-chat-react-native": "^0.14.0",
         "react-native": "^0.62.0",

- Device/Emulator (android/ios) and OS version
        iOS Simulator: 12.5.1
        iOS: 14.5

**Expected behavior**

Render our existing chat rooms.

**Additional context**
Tried fresh installs of yarn, podfiles, and xcode build.

**Screenshots**

![Screen Shot 2021-07-01 at 5 18 49 PM](https://user-images.githubusercontent.com/66880560/124203137-e2ca8100-da90-11eb-8d53-80b0ba0850ea.png)

**Comment by nhannah** [comment]
Please check you have implemented the OverlayProvider.
