### ISSUE TITLE
ERROR: make: *** No targets specified and no makefile found.  Stop.

### ISSUE THREAD

**Issue by liviavinci** [GetStream/stream-chat-react-native#741]
I followed the example app instruction:

git clone https://github.com/GetStream/stream-chat-react-native.git
cd stream-chat-react-native
make

When I ran "make" it give me error: make: *** No targets specified and no makefile found.  Stop.

**Comment by tsirlucas** [comment]
Hey @liviavinci we are working on a few changes in the app structure on our development branch. If you're using it you can cd to `stream-chat-react-native/package` instead. Gonna keep this opened as a reminder to change the instructions on the README file. Let me know if things work out!

**Comment by liviavinci** [comment]
@tsirlucas thank you very much! it works great!
