### ISSUE TITLE
White space when sending an ordered list message.

### ISSUE THREAD

**Issue by dakshbhardwaj** [GetStream/stream-chat-react-native#745]
**Describe the bug**
White space when sending an ordered list message.

**Dev environment info (please complete/provide the following information):**
- stream-chat-react-native : 3.6.1
- react-native : 0.64.1
- Any Android/iOS device

**To Reproduce**
- Try to send any message in the ordered list.
   Ex - 1. abcd 
      
**Expected behavior**
Full message should be displayed in chat.

**Additional context**
The same happens in the sample app also.

**Screenshots**
<img src="https://user-images.githubusercontent.com/22423684/125447487-02b25e56-3899-4fb3-bfbd-c4e3769e66ef.png" width="350" height="550" />

**Comment by vishalnarkhede** [comment]
@dakshbhardwaj this has been fixed as part of v3.8.2
