### ISSUE TITLE
Error: Invalid hook call. Hooks can only be called inside of the body of a function component.

### ISSUE THREAD

**Issue by MilapKundalia** [GetStream/stream-chat-react-native#746]
Hello Team,

We are facing some weird issues when we try to fetch channel details using the chat id, please find more details below

**Error**: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app

**Code**

```
    this.chatClient = StreamChat.getInstance(Config.GET_STREAM_KEY);
    this.chatClient.connectUser(chatUser, chat_token);
    this.channel = this.chatClient.channel('messaging', chat_id)
    this.channel.watch();


   render() {
       if (!this.channel) {
        return null;
     }

       return (
      <SafeAreaView style={styles.channelScreenSaveAreaView}>
        <KeyboardAvoidingView behavior='padding' keyboardVerticalOffset={135}>
          <Chat client={this.chatClient}>
            <Channel channel={this.channel}>
              <View style={{ display: 'flex', height: '86%' }}>
                <MessageList messageActions={['reactions']} Message={CustomMessage} />
                <MessageInput channel={this.channel} hasFilePicker={false} hasImagePicker={false} />
              </View>
            </Channel>
          </Chat>
        </KeyboardAvoidingView>
      </SafeAreaView>

    );
```

**React native version**
    "react-native": "0.64.1",

**Stream chat version**
    "stream-chat-react-native": "^3.5.1",

**Comment by vishalnarkhede** [comment]
Have you added `OverlayProvider`?

**Comment by MilapKundalia** [comment]
Hello @vishalnarkhede  
Tried adding OverlayProvider but haveing same error 

```
return (
      <OverlayProvider>
      <SafeAreaView style={styles.channelScreenSaveAreaView}>
        <KeyboardAvoidingView behavior='padding' keyboardVerticalOffset={135}>
          {console.log(this.chatClient)}

          <Chat client={this.chatClient}>
            <Channel channel={this.channel}>
              <View style={{ display: 'flex', height: '86%' }}>
                <MessageList messageActions={['reactions']} Message={CustomMessage} />
                <MessageInput channel={this.channel} hasFilePicker={false} hasImagePicker={false} />
              </View>
            </Channel>
          </Chat>

        </KeyboardAvoidingView>
      </SafeAreaView>
      </OverlayProvider>


    );
```


Let me know if you need any other info

**Comment by BenHurMartins** [comment]
Hi, if I am not wrong hooks only can be used inside a functional component, and the code you posted is a class component.

**Comment by MilapKundalia** [comment]
yes @BenHurMartins we have used class components in the whole app we haven't used hooks in our class components

**Comment by nhannah** [comment]
I would check #1 and #2, is something else using React or React Native as a dependency instead of peer dependency? Also the `Channel` component has a built in keyboard avoiding view that will likely collide in your current setup.

**Comment by MilapKundalia** [comment]
@nhannah We solved the issue our react version was conflicting with the peer dependencies but now when I send a message we are getting **"TypeError: undefined is not an object (evaluating 'message.type)"**
![Simulator Screen Shot - iPhone 12 - 2021-07-14 at 20 13 16](https://user-images.githubusercontent.com/3378778/125641975-3b463a4f-e05c-401a-9fd8-1aa2380a01fc.png)

one more thing is we want to disable rich messaging from MessageInput  we have done hasFilePicker={false} hasImagePicker={false} giphyActive={false} in MessageInput component but we are unable to disable the rich messaging

my code looks something like this 

```

<OverlayProvider>
      <SafeAreaView style={styles.channelScreenSaveAreaView}>
          <Chat client={this.chatClient}>
            <Channel client={this.chatClient} channel={this.channel}>
              <View style={{ display: 'flex', height: '86%' }}>
                <MessageList messageActions={['reactions']} Message={CustomMessage} />
                <MessageInput channel={this.channel} hasFilePicker={false} hasImagePicker={false} giphyActive={false}/>
              </View>
            </Channel>
          </Chat>
      </SafeAreaView>
      </OverlayProvider> 
```

**Comment by vishalnarkhede** [comment]
Hey @MilapKundalia Please change the `Message` prop to `MessageSimple`. It looks like you are upgrading from v2 to v3. Some architectural changes were done between these version upgrades. I would recommend you to check our documentation for latest version - https://getstream.io/chat/docs/sdk/reactnative/basics/hello_stream_chat/
