### ISSUE TITLE
ImagePicker fails to open

### ISSUE THREAD

**Issue by cenzovit** [GetStream/stream-chat-react-native#78]
pickImage in registerNativeHandlers passes null to ImagePicker.showImagePicker which causes an error in React-Native-Image-Picker. For now, should probably pass and empty object or allow for users to pass their own options to the image picker.

**Comment by vishalnarkhede** [comment]
Hey @cenzovit this has now been fixed as part of `v0.3.12`

**Comment by vishalnarkhede** [comment]
Hey @cenzovit , can you confirm if the issue is fixed for you. In that case I would like to close this issue :)

Thanks

**Comment by cenzovit** [comment]
Appears to be fixed!
