### ISSUE TITLE
Upgrade regression on stream-chat-js 3.11.0: ChannelList fails to load first time after app launch

### ISSUE THREAD

**Issue by jehartzog** [GetStream/stream-chat-react-native#783]
We upgraded today and immediately noticed a blocking regression. After a fresh load of the app the ChannelList fails to load any changes, leaving the loading animation running.

We can bypass the error state by trigger a fast refresh in dev, or by backgrounding for a while then resuming, but the app is currently unusable after the upgrade.

## Reproduction

1. Hard kill app
2. Open app with authenticated user, land on screen w/ ChannelList

### Expected

1. ChannelList loads

### Actual

1. ChannelList sits displaying `Skeleton` loader infinitely.
2. A `connection.recovered` events flows through in the background

### Previous working versions (issue not present):
- stream-chat-react-native: 3.6.0
- stream-chat: 3.9.0

### Upgraded versions (issue present):
- stream-chat-react-native: 3.9.0
- stream-chat: 3.13.1

I went back downgrading `stream-chat` version by version until I isolated to changes introduced by `3.11.0` release.

`v3.12.1` - Issue present
`v3.12.0` - Issue present
`v3.11.0` - Issue present
`v3.10.0` - Issue not present

## Error Details

Due to previous troubleshooting, we carefully watch `connection.recovered` events. When we get the error triggered, we see this event happen. I logged all the events in order and here is what they look like:

```
{"event": {"online": true, "type": "connection.changed"}} 
{"event": {"online": true, "type": "connection.changed"}} 
{"event": {"cid": "*", "connection_id": "61042661-0a05-4bf7-0000-000000006661", "created_at": "2021-07-30T20:58:03.211905908Z", "me": {"banned": false, "channel_mutes": [Array], "created_at": "2021-07-23T16:28:13.7902Z", "devices": [Array], "id": "329627fb-79f6-493e-bed8-8add3763d31f", "image": "removed", "invisible": false, "language": "", "last_active": "2021-07-30T20:58:03.209507409Z", "mutes": [Array], "name": "user159", "online": true, "role": "user", "total_unread_count": 0, "unread_channels": 0, "unread_count": 0, "updated_at": "2021-07-28T16:43:16.437191Z"}, "received_at": 2021-07-30T20:58:03.204Z, "type": "health.check"}} 
{"event": {"type": "connection.recovered"}}
```

## Discussion

I'm guessing this condition was caused by https://github.com/GetStream/stream-chat-js/pull/698 .

**Comment by vishalnarkhede** [comment]
@jehartzog I will take a look at get back asap :)

**Comment by jehartzog** [comment]
I have confirmed GetStream/stream-chat-js#698 caused the regression we're seeing. We [forked and reverted that PR](https://github.com/ourfabriq/stream-chat-js/tree/fork/3.13.1-remove-regression), and the regression is gone.

**Comment by vishalnarkhede** [comment]
@jehartzog Do you receive some error regarding some failed api call?

**Comment by jehartzog** [comment]
@vishalnarkhede no, only differences noticed are those listed under 'Error Details' above. I didn't troubleshoot very far, after I confirmed https://github.com/GetStream/stream-chat-js/pull/698 was causing the issue, I forked and reverted that PR which restored basic functionality.

I suspect minor timing differences in your connection code is triggering a race condition in the hooks/effects you use in this lib to initialize and then render state. That's just speculation though.

**Comment by vishalnarkhede** [comment]
Hey @jehartzog could you please upgrade to `stream-chat@4.2.0` and check if you still face this issue?

**Comment by jehartzog** [comment]
@vishalnarkhede It seems to clear the issue on loading. I ran on a quick branch, as we won't be able to upgrade right now. When we upgrade I'll make sure to follow up if we see any more of the incorrect behavior. Thanks for the fix and the heads up.

**Comment by vishalnarkhede** [comment]
> @vishalnarkhede It seems to clear the issue on loading.

Thats great to hear. I am going to close the issue for now, let's reopen in future if you face any further issue.
