### ISSUE TITLE
OverlayProvider breaks react navigation createNativeStackNavigator on Android

### ISSUE THREAD

**Issue by Shaninnik** [GetStream/stream-chat-react-native#795]
**Describe the bug**
Following docs I have my navigators wrapped with OverlayContainer. In my case I am using react-navigation/react-native-screens/createNativeStackNavigator for performance gains and native feel. Works perfect on iOS but on Android whenever I try pushing new screen into stack it starts to behave unpredictable and completely unusable. It looks like entire app container opacity changes randomly, sometimes causing entire app to disappear or appear semi transparent.

**Dev environment info (please complete/provide the following information):**

"stream-chat-react-native": "^3.6.7",
"react-native": "0.64.1",
"@react-navigation/native": "^5.9.4",
"@react-navigation/stack": "^5.14.5",
"react-native-screens": "^3.4.0"

Moto g6, Android 8.0.0

**To Reproduce**
Create empty app and follow instructions to install react navigation and react-native-screens. Use createNativeStackNavigator to create stack with two screens, wrapped by OverlayProvider. Push new screen/go back, repeat until you see your app fully/semi-transparent (rarely, but sometimes it works OK).

**Expected behavior**
Navigation works as expected, app is transparent and is visible.

**Additional context**
Removing OverlayProvider completely fixes the issue, but makes me unable to use other GetStream components.

**Comment by Shaninnik** [comment]
After some more debugging I've found the culprit: <BlurView> in <OverlayProvider> component. It seems like it might be connected with this issue: Kureev/react-native-blur/issues/428
 
Doing something like this in OverlayProvider line 223 completely fixes it for me:

```
{ Platform.OS === "android" ? 
    <View
      style={[StyleSheet.absoluteFill, { height, width, backgroundColor: "#00000088" }]}/> : 
    <BlurView
      blurType={blurType}
      style={[StyleSheet.absoluteFill, { height, width }]}
    />
  }
```

As the side note I've noticed that BlurView is completely unpredictable on Android in general and I in my code I use it only on iOS.

**Comment by vishalnarkhede** [comment]
Hey @Shaninnik sorry for the delays but glad that its resolve. Additionally you can take a look at this - https://getstream.io/chat/docs/sdk/reactnative/basics/troubleshooting/#android-5

**Comment by Shaninnik** [comment]
@vishalnarkhede this is not resolved, I just found a solution/temp fix for the issue but you need to use `patch-package` to make changes in installed node_modules, it works but it is hardly ideal. The link you posted describes a NullPointerException/crash, my issue is different. Current implementation of `OverlayProvider` is completely unusable with `createNativeStackNavigator`. I am happy to make a PR with my changes, but as you can see it just completely replaces BlurView on Android with 50% opacity black overlay. I have not found a better solution yet.

**Comment by vishalnarkhede** [comment]
Hey @Shaninnik would you mind setting up a bare minimum example app to replicate the issue?

**Comment by yosukapro** [comment]
This issues still happen. Does anyone have solution for this?

**Comment by Shaninnik** [comment]
@yosukapro yes I've tried with updated version of react native blur and stream lib and still getting this issue in some Android device, so I am still applying my patch with `patch-package`:

```
diff --git a/node_modules/stream-chat-react-native-core/src/contexts/overlayContext/OverlayProvider.tsx b/node_modules/stream-chat-react-native-core/src/contexts/overlayContext/OverlayProvider.tsx
index a941fff..c98ff6c 100644
--- a/node_modules/stream-chat-react-native-core/src/contexts/overlayContext/OverlayProvider.tsx
+++ b/node_modules/stream-chat-react-native-core/src/contexts/overlayContext/OverlayProvider.tsx
@@ -1,5 +1,5 @@
 import React, { PropsWithChildren, useEffect, useRef, useState } from 'react';
-import { BackHandler, Dimensions, StyleSheet, ViewStyle } from 'react-native';
+import { BackHandler, Dimensions, Platform, StyleSheet, View, ViewStyle } from 'react-native';
 import Dayjs from 'dayjs';
 import Animated, {
   cancelAnimation,
@@ -220,10 +220,13 @@ export const OverlayProvider = <
                   pointerEvents={overlay === 'none' ? 'none' : 'auto'}
                   style={[StyleSheet.absoluteFill, overlayStyle]}
                 >
+                  { Platform.OS === "android" ? 
+                   <View style={[StyleSheet.absoluteFill, { height, width, backgroundColor: "#00000088" }]}/> : 
                   <BlurView
                     blurType={blurType}
                     style={[StyleSheet.absoluteFill, { height, width }]}
                   />
+                  }
                 </Animated.View>
                 <MessageOverlay<At, Ch, Co, Ev, Me, Re, Us>
                   MessageActions={MessageActions}
```

It replaces a blur view overlay with solid 50% opacity overlay, but that is not a big deal for me.
