### ISSUE TITLE
Can't add custom MessageOverlay

### ISSUE THREAD

**Issue by inbalvenn** [GetStream/stream-chat-react-native#801]
**Describe the bug**
Following docs, I want to change OverlayMessage alignment and padding. Since it's not a functional change, I turned to work with theme, but it wasn't enough for my needs, so I tried to add my own MessageOverlay, using OverlayProvider, like this:
    <OverlayProvider value={{ style: theme }} MessageOverlay={CustomMessageOverlay}>...</OverlayProvider>
My custom MessageOverlay didn't seem to be rendered, and when checking OverlayProvider code, I didn't see it takes MessageOverlay component from context, like inner overlay components.

Also, 
when trying to add custom theme with [overlay padding](https://github.com/GetStream/stream-chat-react-native/blob/5fa9f2946d56cb1a2e69e4bbae5f9d9f52754e4d/package/src/contexts/themeContext/utils/theme.ts#L448), I expected it to override inner styles of [overlayPadding](https://github.com/GetStream/stream-chat-react-native/blob/eab95f0be97226793f9bc8bc2bc2ad4cfe2c93aa/package/src/components/MessageOverlay/MessageOverlay.tsx#L74), but it doesn't seem to use it.

I also couldn't change styles and border radius of MessageActions container   

**Dev environment info (please complete/provide the following information):**

- stream-chat-react-native: 3.7.2
- react-native: 0.64.2

**Screenshots**
I want to achieve right/left alignment (according to myMessage/other) and a bit more control of element padding, but I could only change the actions styles and icons, and reactionList borderRadius.
<img width="376" alt="Group 1112" src="https://user-images.githubusercontent.com/47968487/129569888-96a5b9a1-6f93-43c2-98f3-990027672a4a.png">

**Comment by madsroskar** [comment]
The PR linked above is expected to be part of our `4.0.0` release planned for the end of this month. 🙁

**Comment by vishalnarkhede** [comment]
More broader customisation support for message action UI components and theming has been added to our planned v4 release. So I would recommend keeping an eye for it.

**Comment by ghiculescualexandru** [comment]
This issue shouldn't be close as it doesn't solve the request. I can't overwrite the MessageOverlay component and I would like to change it as a whole, not only the MessageActionList or the MessageActionListItem.

**Comment by testanib** [comment]
seconding this, the default overlay can make the selected message look pretty broken when you use custom styles/components for chat

**Comment by VNDRN** [comment]
A MessageOverlay custom component would indeed be a great added feature!
