### ISSUE TITLE
ReferenceError: Can't find variable: _stopObservingProgress

### ISSUE THREAD

**Issue by iMJumpmxn** [GetStream/stream-chat-react-native#815]
**Describe the bug**
Hello, i got the following error after upgrading to react-native: 0.65

```
 ERROR  ReferenceError: Can't find variable: _stopObservingProgress
 ERROR  Error: Requiring module "node_modules/stream-chat-react-native/src/index.js", which threw an exception: 
 ReferenceError: Can't find variable: _stopObservingProgress
```

**Dev environment info (please complete/provide the following information):**

- Package version: 3.7.2
- react-native: 0.65
- Device: android

gz#14461

**Comment by streamiosupport** [comment]
Agent comment from Cody Smith in <a href='https://getstream.zendesk.com/agent/tickets/14461'>Zendesk ticket #14461</a>:<br><br>Hi there,
Thanks for reporting this, I'll take a look with our react-native team to determine what this issue might be and get back to you as soon as I find anything out.

Regards,
Cody
<br><p><em><small>°°°</small></em></p>

**Comment by tsirlucas** [comment]
Hey @iMJumpmxn did a quick research at the error message and it seems like the _stopObservingProgress is being used from `react-native-reanimated`. Which version of that library are you using? Can you try to update to the newest one?

Found a lot of issues about RN 0.65 compatibility in their repo so maybe theyre not supporting it yet.

**Comment by vishalnarkhede** [comment]
@iMJumpmxn could you please try upgrading reanimated version to `2.3.0-alpha.2`?

**Comment by streamiosupport** [comment]
Agent comment from Cody Smith in <a href='https://getstream.zendesk.com/agent/tickets/14461'>Zendesk ticket #14461</a>:<br><br>Hello - did you have a chance to upgrade your reanimated version? If so did that solve your issue?
<br><p><em><small>°°°</small></em></p>

**Comment by streamiosupport** [comment]
Agent comment from Cody Smith in <a href='https://getstream.zendesk.com/agent/tickets/14461'>Zendesk ticket #14461</a>:<br><br>Hi - I'll close this out due to inactivity. Let us know if you have any further questions!

Regards,
Cody
<br><p><em><small>°°°</small></em></p>

**Comment by madsroskar** [comment]
This problem should be resolved when upgrading react-native-reanimated to [2.2.1](https://github.com/software-mansion/react-native-reanimated/releases/tag/2.2.1), which adds support for React Native 0.65.
