### ISSUE TITLE
Bug: when the connection is recovered, ChannelList did not update correctly

### ISSUE THREAD

**Issue by giautm** [GetStream/stream-chat-react-native#832]
**Describe the bug**

When the connection is recovered, ChannelList did not update correctly

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native/stream-chat-expo): 
```
    "stream-chat": "4.1.0",
    "stream-chat-expo": "3.7.3"
```
- react-native or expo version: SDK 41
- Device/Emulator (android/ios) and OS version: iPhone 12 mini.

**To Reproduce**

1. Filter/sort channels with `{ has_unread: -1 }`
2. Bring the app to the background.
3. Bring the app to the foreground.
4. See "Reconnecting..."
5. See Channel List doesn't sort/filter correctly

**Expected behavior**
The channel list should sort/filter correctly.

**Additional context**
I think it is related to the code below, it holds a reference to the first version of `refreshList`. And not updated during filter/sort changed.

https://github.com/GetStream/stream-chat-react-native/blob/00049f747173097baa2b25a71755895325a6e4e4/package/src/components/ChannelList/hooks/listeners/useConnectionRecovered.ts#L29-L52

**Screenshots**

https://user-images.githubusercontent.com/12751435/131223648-1d29d15e-ac8d-4c29-858d-49b4b7aa6409.MP4

gz#14665

**Comment by streamiosupport** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/14665'>Zendesk ticket #14665</a>:<br><br>Hi Giautm

Thanks for the details.
We will check this and come back to you soon.

Cheers
Seetha
<br><p><em><small>°°°</small></em></p>

**Comment by giautm** [comment]
Hi Seetha, any update on this issue? I really have a PR for this. Any blocking I can help?

**Comment by streamiosupport** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/14665'>Zendesk ticket #14665</a>:<br><br>Hi Giau

Sorry, I couldn't reproduce this issue in Expo and in Native. The channel list loads without any issues with `{has_unread: -1}`

Our Engineer will be taking a look at your PR today.

In the meantime, can I have your complete filters/sort along with your package.json so I can try reproducinging this? Thanks.

Cheers
Seetha
<br><p><em><small>°°°</small></em></p>

**Comment by giautm** [comment]
You need take your app to background. Then bring it on forceground to preproduce

**Comment by streamiosupport** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/14665'>Zendesk ticket #14665</a>:<br><br>Hi Giau

Ofcourse, I am taking the app to the background and then trying it, still no issues.


    const filters = {
    members: { $in: ['Seetha'] },
    type: 'messaging',
    };
    const sort = { has_unread: -1 };


This is how the ChannelListScreen looks like -


    const ChannelListScreen = ({ navigation }) => {
    const { setChannel } = useContext(AppContext);

    const memoizedFilters = useMemo(() => filters, []);

    return (
    <Chat client={chatClient} i18nInstance={streami18n}>
    <View style={{ height: '100%' }}>
    <ChannelList
    filters={memoizedFilters}
    onSelect={(channel) => {
    setChannel(channel);
    navigation.navigate('InAppChat', {Channel});
    }}
    options={options}
    sort={sort}
    />
    </View>
    </Chat>
    );
    };


I have also attached my package.json.

Cheers
Seetha<br><a href='https://getstream.zendesk.com/attachments/token/NyqGLkWR0cRSswROQCO8PfoL1' target='zd_attach'>package.json</a>
<br><p><em><small>°°°</small></em></p>

**Comment by giautm** [comment]
Hi Seetha, sorry because I don't explain clearly in the description. I just update your code with a  Button. Step by Step are:
1) Load the app.
2) Press "Update Sort" and see channel list changed.
3) Take the app to the background
4) Bring app to the foreground, see ChannelList not same as step 2), it reverted to step 1)

```tsx
const filters = {
  members: { $in: ["Seetha"] },
  type: "messaging",
};

import { Pressable, Text } from 'react-native'

const ChannelListScreen = ({ navigation }) => {
  const { setChannel } = useContext(AppContext);
  // Default sort, for first time render
  const [sort, setSort] = useState({ last_message_at: -1 });

  // We update sort after press button,
  // I expect ChannelList should keep this sort after comeback from background
  const handlePress = useCallback(() => {
    setSort({ has_unread: -1 });
  }, []);
  const memoizedFilters = useMemo(() => filters, []);

  return (
    <Chat client={chatClient} i18nInstance={streami18n}>
      <View style={{ height: "100%" }}>
        <Pressable onPress={handlePress}>
          <Text>Update Sort</Text>
        </Pressable>
        <ChannelList
          filters={memoizedFilters}
          onSelect={(channel) => {
            setChannel(channel);
            navigation.navigate("InAppChat", { Channel });
          }}
          options={options}
          sort={sort}
        />
      </View>
    </Chat>
  );
};
```

**Comment by giautm** [comment]
Hi Sêtha, do you preproduce the bug success?
