### ISSUE TITLE
Bug: OverlayProvider causes android app to crash when Updating to RN 0.65.1 and RN-reanimted 2.3.0-alpha.3 

### ISSUE THREAD

**Issue by PadovaY** [GetStream/stream-chat-react-native#839]
**Describe the bug**
android app crashes instantly when using OverlayProvider
**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native): 2.8.0
- react-native version: 0.65.1
- Device/Emulator (android/ios) and OS version: Pixel 3,  android 11

**To Reproduce**

1.  open the app while using the OverlayProvider HOC
2. see app crashes

**Expected behavior**
app running smoothly

**Additional context**
the crash started when migrating to react native 0.65.1 and using react-native-reanimated 2.3.0-alpha.3

**Screenshots**
error trace stack from flipper
![image](https://user-images.githubusercontent.com/38754615/132127067-5862fb34-b91c-4d03-9cde-c00d924a9d44.png)

gz#14828

**Comment by streamiosupport** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/14828'>Zendesk ticket #14828</a>:<br><br>Hi

Thanks for reaching out to us.
Overlay provider was introduced as part of v3 in stream-chat-react-native.
Looks like you are at v2.8.0  Can you please upgrade to v3 and test this?
https://getstream.github.io/stream-chat-react-native/v3/

Please refer to this upgrade helper for more details about upgrading to v3. https://getstream.io/chat/docs/sdk/reactnative/guides/upgrade-helper/

Please let us know how you go.

Cheers
Seetha
<br><p><em><small>°°°</small></em></p>

**Comment by PadovaY** [comment]
Sorry my bad, the actual version is 3.7.2

**Comment by streamiosupport** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/14828'>Zendesk ticket #14828</a>:<br><br>Hi

No worries, thanks for the details.
We will check this and come back to you soon.

Cheers
Seetha
<br><p><em><small>°°°</small></em></p>

**Comment by madsroskar** [comment]
This problem should be resolved when upgrading react-native-reanimated to [2.2.1](https://github.com/software-mansion/react-native-reanimated/releases/tag/2.2.1), which adds support for React Native 0.65.
