### ISSUE TITLE
Bug: AttachmentPicker overlap buttons on Android

### ISSUE THREAD

**Issue by giautm** [GetStream/stream-chat-react-native#843]
**Describe the bug**

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native/stream-chat-expo): 3.7.3
- react-native or expo version: SKDv41
- Device/Emulator (android/ios) and OS version: Android Simulator Pixel_4_XL_API_30

**To Reproduce**

1. Go to 'Channel'
2. Click on 'Attachment' icon
4. See the error

**Expected behavior**
AttachmentPicker picker should not overlap button and render like on iOS

**Additional context**

I added some debug code to printed bellow values:
```
statusBarHeight = 49.14285659790039
bottomBarHeight = 47.7142862592425
androidBottomBarHeightAdjustment = 0
```
https://github.com/GetStream/stream-chat-react-native/blob/afd84a9d7536f2e47ce1e7888ca29c46a9f81e32/package/src/components/AttachmentPicker/AttachmentPicker.tsx#L298-L321

**Screenshots**

| iOS  | Android |
| ------------- | ------------- |
| ![Simulator Screen Shot - iPhone 12 - 2021-09-08 at 17 28 38](https://user-images.githubusercontent.com/12751435/132493667-85929521-12c3-446d-9e80-89e8beb8ae12.png) | ![Screenshot_1631094771](https://user-images.githubusercontent.com/12751435/132493699-a50dc12d-7488-45fe-b084-b4502293cdd4.png) |

gz#14918

**Comment by streamiosupport** [comment]
Agent comment from Guilherme Cortes in <a href='https://getstream.zendesk.com/agent/tickets/14918'>Zendesk ticket #14918</a>:<br><br>Hello,

Thanks for reaching out.
Let me check this and come back to you soon.

Best,
Guilherme Cortes
Integration Support Engineer
<br><p><em><small>°°°</small></em></p>

**Comment by vishalnarkhede** [comment]
Hey @giautm please check this article - https://getstream.io/chat/docs/sdk/reactnative/basics/troubleshooting/#image-picker-incorrect-height. Let me know if thats helpful, otherwise we can reopen this issue.
