### ISSUE TITLE
Images don't display when openAttachmentPicker is clicked on MessageInput

### ISSUE THREAD

**Issue by evansibok** [GetStream/stream-chat-react-native#844]
**Describe the bug**
After hooking up the default MessageList component, I attempted to test the chat by sending an image. On press of the default clip icon to open the attachment picker, the image gallery doesn't display the available images. The images are actually there but not visible. After clicking on an invisible square, the image returned a [Network Failure] error and failed to upload to allow sending.

**Dev environment info (please complete/provide the following information):**
- stream-chat-react-native v3.8.0
- Android Emulator Pixel_3a_API_29 - OS v10

**Steps to reproduce the behavior:**
1. Setup a default Chat Interface with ChannelList and MessageList and MessageInput
2. Start a new chat with a new user
3. Tap on the clip icon to open the image gallery (openAttachmentPicker)

**Expected behavior**
On press of the clip icon to open gallery bottom sheet to pick an image, images should be visible so you can pick and when an image has been selected, it should upload successfully and make it possible to send the image in the chat as an attachment.

**Screenshots**
<img src="https://user-images.githubusercontent.com/16621400/132852591-55db0753-e90b-48ce-97e5-1cec69189ced.png" width="300">

<img src="https://user-images.githubusercontent.com/16621400/132852620-410a79d0-588b-463a-aa57-07d7b9ab14ce.png" width="300">

<img src="https://user-images.githubusercontent.com/16621400/132855098-d3126cf5-2487-49e0-a4e2-b40a258aaa5c.png" width="300">

gz#15014

**Comment by streamiosupport** [comment]
Agent comment from Ryan Kavanaugh in <a href='https://getstream.zendesk.com/agent/tickets/15014'>Zendesk ticket #15014</a>:<br><br>Hi,


Thanks for reaching out! I’m looking into this for you now and will be in touch shortly. Can you please also share the network error?


Best,
Ryan
<br><p><em><small>°°°</small></em></p>

**Comment by evansibok** [comment]
> Agent comment from Ryan Kavanaugh in [Zendesk ticket #15014](https://getstream.zendesk.com/agent/tickets/15014):
> 
> Hi,
> 
> Thanks for reaching out! I’m looking into this for you now and will be in touch shortly. Can you please also share the network error?
> 
> Best,
> Ryan
> 
> 
> _°°°_

I have updated the issue with a screenshot of the network error. Thank you

**Comment by streamiosupport** [comment]
Agent comment from Ryan Kavanaugh in <a href='https://getstream.zendesk.com/agent/tickets/15014'>Zendesk ticket #15014</a>:<br><br>Hi,

Thank you. Have you been able to test this on other emulators? Also, is there anything more descriptive related to the network error?

Best,
Ryan
<br><p><em><small>°°°</small></em></p>

**Comment by evansibok** [comment]
> Agent comment from Ryan Kavanaugh in [Zendesk ticket #15014](https://getstream.zendesk.com/agent/tickets/15014):
> 
> Hi,
> 
> Thank you. Have you been able to test this on other emulators? Also, is there anything more descriptive related to the network error?
> 
> Best,
> Ryan
> 
> 
> _°°°_

Hello,

I tested this on a real android device and the images show up, then I tested it again on the emulator and it still has the same issue.

The real device runs on Android OS 8.1.0

**Comment by vishalnarkhede** [comment]
Hey @evansibok so just to confirm, is it the emulator only issue? I would suggest testing attachment picker feature in release mode. Debuggers have well known issues with upload functionality in general on react-native

**Comment by vishalnarkhede** [comment]
Closing this since its not related to this library,
