### ISSUE TITLE
TypeScript error - v3.8.2

### ISSUE THREAD

**Issue by luisfcofv** [GetStream/stream-chat-react-native#857]
**Describe the bug**
TypeScript fails to pull correctly types from `stream-chat-react-native`.

**To Reproduce**
1. Import anything from `stream-chat-react-native`.

```ts
import { Channel } from 'stream-chat-react-native';
```

**Expected behavior**
No TS errors.

**Screenshots**

<img width="675" alt="CleanShot 2021-09-16 at 15 15 31@2x" src="https://user-images.githubusercontent.com/1128284/133638648-9c5ab901-bcc2-422a-976b-7c2b8e926d41.png">

**Comment by vishalnarkhede** [comment]
@luisfcofv whats the version of typescript?

**Comment by luisfcofv** [comment]
Sorry, forgot to mention it. we are using TS `4.3.2`.
The SDK version`3.8.0` works for us.

**Comment by vishalnarkhede** [comment]
Thanks. We are working on a fix, thanks for pointing this out

**Comment by tsirlucas** [comment]
Hey, this is fixed in 3.8.3!
