### ISSUE TITLE
Unable to close the ImageGrid popup in android

### ISSUE THREAD

**Issue by zT0Tz** [GetStream/stream-chat-react-native#859]
**Describe the bug**

In ImageGallery when click the grid button on the right bottom, the ImageGrid will popup. In ios click the close button will bring we back to the previous ImageGallery view, however in android the close button doesn't work. Only way to get back is using the back navigator button of android system, this will send me back to message list. After press on an image again, it will still be in ImageGrid, can't go back to ImageGallery view again.

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native/stream-chat-expo):  v3.8.0
- react-native or expo version:  v0.63.2
- Device/Emulator (android/ios) and OS version: emulator(android version 10), and real devices

**To Reproduce**

1. Go to ImageGallery,
2. Click on grid button on the right bottom to see ImageGrid
3. Click close button on top right corner
4. can not close or choose any image, it's stuck here

**Expected behavior**
ImageGrid should close

**Screenshots**
<img src="https://user-images.githubusercontent.com/26011653/133658359-7f5c62f1-af64-495e-8d29-9aea9c3eb805.png" width="350" height="700">  <img src="https://user-images.githubusercontent.com/26011653/133658387-a0a24483-d629-4663-b30c-6697d981d610.png" width="350" height="700">

gz#15175

**Comment by streamiosupport** [comment]
Agent comment from Cody Smith in <a href='https://getstream.zendesk.com/agent/tickets/15175'>Zendesk ticket #15175</a>:<br><br>This request was closed and merged into request #15173 "unable to save image on android".
<br><p><em><small>°°°</small></em></p>

**Comment by vishalnarkhede** [comment]
Hey @zT0Tz could you please check if you are able to reproduce the same issue on any one of these example apps?  https://github.com/GetStream/stream-chat-react-native/tree/develop/examples

If not, please check if you are using the right versions of dependencies.
