### ISSUE TITLE
DateHeader component not overriden by Channel prop

### ISSUE THREAD

**Issue by philippeauriach** [GetStream/stream-chat-react-native#873]
**Describe the bug**
DateHeader component is not used in `<Channel />`

```
<Channel
  channel={channel}
  DateHeader={() => <Text>hello</Text>}
  StickyHeader={() => <Text>hello</Text>}>
  <MessageList
    DateHeader={() => <Text>hello</Text>}
    StickyHeader={() => <Text>hello</Text>} />
</Channel>
```

The sticky header is replaced but the DateHeader is not taken into account? I tried setting on both Channel and MessageList.

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native/stream-chat-expo) 
`stream-chat-react-native-core@3.8.3`
`stream-chat@4.2.0`
- react-native @ 3.8.3
- Device/Emulator (android/ios) and OS version
iPhone 11 iOS 14.5

**Screenshots**
<img width="342" alt="Capture d’écran 2021-09-21 à 12 20 18" src="https://user-images.githubusercontent.com/920265/134154668-81424b64-4fe4-425a-8e51-b9e1f37d613d.png">

gz#15271

**Comment by philippeauriach** [comment]
Ok my bad, I was supposed to use the "InlineDateSeparator" component to replace the one I wanted to replace. Had trouble to find it as it is not displayed in the "indicator" tabs on the doc : https://getstream.io/chat/docs/sdk/reactnative/core-components/channel/

**Comment by streamiosupport** [comment]
Agent comment from Luis Gereda in <a href='https://getstream.zendesk.com/agent/tickets/15271'>Zendesk ticket #15271</a>:<br><br>Hi Philippe,

Thank you for reaching out.

Please do not hesitate to contact us again if you have any other questions,

Regards,
Luis Gereda
Integration Support Engineer
<br><p><em><small>°°°</small></em></p>
