### ISSUE TITLE
Does stream support iOS 13 push notifications?

### ISSUE THREAD

**Issue by EJohnF** [GetStream/stream-chat-react-native#89]
Push notifications were working on friday. Today morning we updated testing phone to iOS 13+ and push notifications stops working:
seems to be related to https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns?language=objc

In the dashboard I see that push notification claims to be delivered, but I don't see them on the phone

copied from: 
https://github.com/GetStream/stream-chat-js/issues/191#issue-527940906

**Comment by EJohnF** [comment]
Some my findings which might be helpfull:
I don't see in dashboard push notification logs the entities for Push notifications to ios 13 (no error, not row for this user)
And I made sure that this user is offline - I killed the app where he was logged.

**Comment by EJohnF** [comment]
from this issue: https://github.com/GetStream/stream-chat-swift/issues/31

I tried to add `"apns-push-type":"alert"` to the template. 

And now I see logs, but it says:

<img width="574" alt="Screenshot 2019-11-26 at 10 47 34" src="https://user-images.githubusercontent.com/8780514/69618449-30bc0f00-103a-11ea-8f20-c0d268774178.png">


I thought it's because of the wrong key or team ID -> double-checked that it's correct

**Comment by Bogdan-D** [comment]
Hi, @EJohnF, we are having support for new apns push type. It shoudn't be added to the template directly, it's done on backend side.

Are you using development or production push settings?

**Comment by EJohnF** [comment]
Hi @Bogdan-D, thanks for looking up
okey, I've removed this field from the template 

I'm uploading .p8 auth key -> which should work for both, development and productions
And the toggle in ios settings -> I tried in both states (on and off for development toggle)

for testing, I'm using AdHoc production build


One more I've noticed, that I'm receiving logs now, about the error during push sending, but the message is different within the same set-up (the app is killed, and certificates/settings are the same):
- publishing the message failed with error: BadDeviceToken
- publishing the message failed with error: InvalidProviderToken

**Comment by Bogdan-D** [comment]
Hi @EJohnF 

We are currently having the issue with p8 keys you are talking about, working on fix for that.
I recommend you temporary to use .p12 key instead.

Can you check push notifications are working now?

**Comment by EJohnF** [comment]
Hm, I did nothing special (all settings still the same, and still with p8 key) - and notification start to come on ios13 as expected :/

Seems the issue with p8 is resolved? Or I shouldn't rely on this way?

**Comment by Bogdan-D** [comment]
Issue with p8 is different issue, not related to the topic.

Closing this one
