### ISSUE TITLE
Crazy long network calls to channels API

### ISSUE THREAD

**Issue by gilbertl** [GetStream/stream-chat-react-native#897]
**Describe the bug**
We're seeing some network calls to stream chat that takes _minutes_ to finish responding

![image](https://user-images.githubusercontent.com/37179/135585484-0b694a97-d3a1-4920-8519-d1aaccf44382.png)

Note that 473691ms ~= 8 minutes

Same user has also complained about battery draining quickly

**Dev environment info (please complete/provide the following information):**

- stream-chat-react-native 3.6.0
- react-native or expo 0.65.1
- android: samsung SM-G973U1

**To Reproduce**
It's not clearly how this can be reproduced. However, not network call should last 8 minutes!

**Expected behavior**
The server should be more responsive AND the client should set a reasonable timeout on these API calls.

gz#15523

**Comment by vishalnarkhede** [comment]
Hey @gilbertl we keep the github issues only for bug reports. Please contact support@getstream.io for this issue. We will help you there with the network latency.
