### ISSUE TITLE
 Is it possible to translate Actions into another language?

### ISSUE THREAD

**Issue by RomanBob123** [GetStream/stream-chat-react-native#902]
Hi!

Is it possible to translate only the context menu and other static labels without touching user messages?

Regards!

![Screenshot from 2021-10-05 15-56-25](https://user-images.githubusercontent.com/91616406/136026930-caf63958-ddc7-4294-ade2-b4acf9a40594.png)

gz#15602

**Comment by vishalnarkhede** [comment]
Hey @RomanBob123 yes it is possible. Please take a look at our internationalization documentation - https://getstream.io/chat/docs/sdk/reactnative/basics/translations/

**Comment by RomanBob123** [comment]
Thanks for the quick help!
![Screenshot from 2021-10-05 16-28-40](https://user-images.githubusercontent.com/91616406/136032364-bccb9f26-9e8e-4ca8-ac3a-922c2411af30.png)
!
