### ISSUE TITLE
App Crashing on React Native 0.66 with "react-native-reanimated": "2.3.0-beta.2"

### ISSUE THREAD

**Issue by ericzhou27** [GetStream/stream-chat-react-native#911]
We recently upgraded to React Native 0.66 to accommodate iOS 15 and were forced to upgrade to "react-native-reanimated": "2.3.0-beta.2" as well. We found that streamchat is now consistently crashing and freezing in busy chat rooms as a result - we suspect that this has to do with the beta version of react-native-reanimated and Streamchat's use of it, which has many issues. We need a solution quickly.

We are using:
    "stream-chat": "^3.11.0",
    "stream-chat-react-native": "^3.6.0",
    "react-native-reanimated": "2.3.0-beta.2",

We are using XCode 13 and simulators running iOS 15. Happy to provide info on our streamchat account and channels if necessary.

gz#15735

**Comment by madsroskar** [comment]
Hi again, Eric.

Unfortunately, I haven't been able to reproduce the same error yet on my end with React Native 0.66.0 and reanimated 2.3.0-beta.2.

If you encounter the same crash again in the future, don't hesitate to reopen this issue. I'll keep an eye out for similar crashes and give an update if I can reproduce it with our sample app.
