### ISSUE TITLE
No real time theme change on messageSimple-content-markdown

### ISSUE THREAD

**Issue by thomasyim02** [GetStream/stream-chat-react-native#924]
**Describe the bug**
When switching theme system-wise (aka. Dark Mode on/off), messageSimple-content-markdown won't apply to the change. Non-markdown stylings are okay.

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native - 3.9.0)
- react-native 0.66.0
- Device/Emulator (android 11)

**To Reproduce**

1. Click the dark mode switch (os/system-wise) such as the one located at notification bar
2. messageSimple-content-markdown did not apply theme change

**Expected behavior**
messageSimple-content-markdown should apply to corresponding theme (e.g. theme === 'dark')

**Comment by vishalnarkhede** [comment]
We will soon publish a patch release for this.

**Comment by thomasyim02** [comment]
@madsroskar @vishalnarkhede 
Thank you for the update!
