### ISSUE TITLE
Disabling opacity animation when users tap messages

### ISSUE THREAD

**Issue by dmigach** [GetStream/stream-chat-react-native#929]
Hello!
We'd like to disable opacity animation when users tap messages, at the moment this behaviour is hardcoded [here](https://github.com/GetStream/stream-chat-react-native/blob/584eb94cd95acec909661037b96f0539b3579880/package/src/components/Message/MessageSimple/MessageContent.tsx#L244)
Would be great to have a way of disabling it or passing custom values for `activeOpacity`.

**Dev environment info**

We're using 
├─ stream-chat-react-native-core@3.8.3
├─ stream-chat-react-native@3.8.3
├─ stream-chat@3.13.1

Just in case the largest message in the center describes the behaviour I'm referring to:
<img src="https://user-images.githubusercontent.com/7489425/137315620-27fdea89-0845-4521-8a69-7df46f334922.png" height=500>

gz#15831

**Comment by vishalnarkhede** [comment]
Hey @dmigach actually you can just provider `additionalTouchableProps` on Channel component to override any props on underlying TouchableOpacity component - https://getstream.io/chat/docs/sdk/reactnative/core-components/channel/#additionaltouchableprops
