### ISSUE TITLE
Deleting channel while on channel screen causes error

### ISSUE THREAD

**Issue by dariuscosden** [GetStream/stream-chat-react-native#930]
Hey! I have encountered a bug, or at the very least I am not sure how to properly handle this case. This happens when a channel is deleted while a user has the app open and is on that channel screen. In my case, the deletion is triggered by another user in the channel (user deletes their account, all their channels get deleted)

This is the error thrown

<img src="https://user-images.githubusercontent.com/44454168/137479145-3a33443c-c92c-4b22-9385-e6c4b0a7ab8d.png" width="300" />

There is an event `channel.deleted` that one can subscribe to, but it does not prevent the error above. How do you handle a channel being deleted while a user is on the channel screen?

Ideally, I would like to implement my own `navigation.goBack` functionality if a channel is deleted. That's what I had hoped for with the `channel.deleted` event, but it does not work. Curiously enough, if a user is on the `ChannelList` screen, then the channel simply disappears without error.

Any thoughts?

gz#15875

**Comment by madsroskar** [comment]
Hey @dariuscosden, thanks for raising the issue.

I'll try this out and get back to you on how you can handle this and trigger your navigation.

**Comment by vishalnarkhede** [comment]
We will soon publish a patch release for this issue.

**Comment by skam22** [comment]
bug is still present:

```
    "stream-chat": "^6.8.0",
    "stream-chat-react-native": "^4.14.0",
```

if a user is in a Channel when it is deleted by another user, Render Error is thrown

**Comment by dimaBaseBlocks** [comment]
Bug is still present: 
`   "stream-chat": "^8.4.1",
    "stream-chat-react": "^10.6.0",`
if a user is in a Channel when it is deleted by another user, Render Error is thrown
