### ISSUE TITLE
flagging a message twice results in error message

### ISSUE THREAD

**Issue by racsmith277** [GetStream/stream-chat-react-native#933]
**Describe the bug**
When a user tries to flag a message that has already been flagged they get an alert with a "Something went wrong" error message.

**Dev environment info (please complete/provide the following information):**

-stream-chat-react-native ^3.7.2
- react-native 0.64.1

**To Reproduce**

1. Create a message in a channel in the prebuilt UI
2. Flag the message using the prebuilt MessageAction
3. Attempt to flag the message a second time

**Expected behavior**

[P1] Change the text on the alert to say something along the lines of "You already flagged this message" instead of an error message. 

[P2] Ideally, the Message object has the context of whether it has already been flagged by the current user, so that we can customize the UI for this scenario (for example, we'd like to be able to conditionally show the flagMessage action based on whether the user has/has not already flagged the message).

gz#15917

**Comment by madsroskar** [comment]
Hi @racsmith277, thank you for reporting this. 

I'll look into it, and get back to you as soon as we have a fix for this.

**Comment by vishalnarkhede** [comment]
Hey @racsmith277 we have updated this error message and it will be released as part of v4.0.0. Please keep an eye for release :) Hey @racsmith277 we have updated this error message and it will be released as part of v4.0.0. Please keep an eye for release :)
