### ISSUE TITLE
React-native-web dependencies

### ISSUE THREAD

**Issue by DobritoiuBogdan747** [GetStream/stream-chat-react-native#96]
Yo GetStream!
Kudos to your Sass.

I am trying to make a react-native-web app with stream-chat-react-native. I know there is a separate react-web repo for the chat but I am trying to use only the react-native implementation for my needs.

My problem is one dependencies which I'm trying to use for the rest of the app which is 
styled-components that tells this:

"It looks like there are several instances of 'styled-components' initialized in this application. This may cause dynamic styles not rendering properly, errors happening during rehydration process and makes your application bigger without a good reason." (this happens only on the web)

"Invariant Violation: NetInfo has been removed from React Native. It can now be installed and imported from 'react-native-netinfo' instead of 'react-native'. See https://github.com/react-native-community/react-native-netinfo" (this happens in react-native, only after upgrading expo sdk to 36, on 35 it worked fine)

How can I keep using styled-components and fix the react-native-netinfo dependency for stream-chat-react-native.

"react": "16.9.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
"stream-chat-expo": "^0.3.12",
"styled-components": "4.2.1"

**Comment by vishalnarkhede** [comment]
Hey @DobritoiuBogdan747 , Thanks for reporting this.

Tbh I haven't yet tried using our sdk with react-native-web app. I will give it a try soon to see if I can resolve these issues. I am aware of Expo issue regarding netinfo package, and I will fix it as priority by end of this week or in next week. But styled components issue may need some deeper investigation.

If you can publish small/sample react-native-web app on GitHub somewhere, that would be awesome. That will make it easier for me to reproduce/investigate the issue.

**Comment by vishalnarkhede** [comment]
Continuing on https://github.com/GetStream/stream-chat-react-native/issues/206
