### ISSUE TITLE
[Urgent] Replies not working

### ISSUE THREAD

**Issue by ericzhou27** [GetStream/stream-chat-react-native#960]
We are receiving the following error in production when sending a reply in a chat room. We haven't changed our channel settings at all - why are "quotes not enabled for this channel"? 

[Error: StreamChat error code 19: SendMessage failed with error: "SendMessage failed with error: "SendMessage failed with error: "SendMessage failed with error: "SendMessage failed with error: "SendMessage failed with error: "SendMessage failed with error: "SendMessage failed with error: "SendMessage failed with error: "quotes are not enabled for this channel"""""""""]

I don't see anything disabled in our dashboard:
<img width="1323" alt="Screen Shot 2021-11-01 at 11 23 47 AM" src="https://user-images.githubusercontent.com/43918217/139721484-cb9a82e1-5ff0-4332-8b51-07a27ab24605.png">

gz#16315

**Comment by vishalnarkhede** [comment]
Hey @ericzhou27 thanks for bringing this up. Our backend team is currently working on fixing this and will get back to you as soon as possible. They will respond back on the ZD ticket!
