### ISSUE TITLE
doSendMessageRequest memoization

### ISSUE THREAD

**Issue by sergeyzhukov** [GetStream/stream-chat-react-native#962]
**Describe the bug**

I have following code 

```
 <Channel
      client={client}
      channel={newMessageChannel}
      doSendMessageRequest={async (cid, message) => {
        const [createdMessage, channels] = await onSend(message)
        return message
      }}
/>
```

Purpose of this code - do some actions before sending the actual message. The problem is that looks like doSendMessageRequest function is heavily over-memoized, because variables from other contexts inside onSend function not updating. You can even try this simple scenario and it will not work. 

```
const [someVar, setSomeVar] = useState(false)

return <Channel client={client} channel={someChannel}  doSendMessageRequest={async (cid, message) => {
    console.log(someVar);   will be always false
    return sendMessage(message)
}} />
```

**Dev environment info**

- Package version (stream-chat-react-native 3.9.0)
- react-native 0.65.1
- iOS simulator 14.5

**Expected behavior**
doSendMessageRequest should catch updated variables inside

gz#16321

**Comment by vishalnarkhede** [comment]
Hey @sergeyzhukov heavy memoizations have been added to avoid un-necessary re-rendering of contexts, which results in re-rendering of heavy components. 

If you would like to access some variables from other contexts within `doSendMessageRequest` you should make it a ref.

```tsx
const testValueRef = useRef(0);

<Channel
  doSendMessageRequest={(cid, message) => {
    console.log(testValueRef.current);
    return channel?.sendMessage(message)
  }}
/>
```

**Comment by vishalnarkhede** [comment]
I am closing this issue for now. I can imagine this is not a ideal solution, but it works. We will try to improve our context structure in future to accept `useCallback`ed function for `doSendMessageRequest` like prop functions.
