### ISSUE TITLE
Chat not working with Expo SDK 36.0.0 due to missing NetInfo dependencies

### ISSUE THREAD

**Issue by familywiser1** [GetStream/stream-chat-react-native#97]
`
Invariant Violation: NetInfo has been removed from React Native. It can now be installed and imported from 'react-native-netinfo' instead of 'react-native'. See https://github.com/react-native-community/react-native-netinfo
This error is located at:
    in Chat (created by Context.Consumer)
    in ThemeProvider (created by Context.Consumer)
    in ThemedChat (at ChannelScreen.js:31)
    in RCTSafeAreaView (at SafeAreaView.js:55)
    in SafeAreaView (at ChannelScreen.js:30)
 
 `
I am following the tutorial at https://getstream.io/chat/react-native-chat/tutorial/
This happens with latest expo sdk 36.

I think the problem is here - https://github.com/GetStream/stream-chat-react-native/blob/master/expo-package/src/index.js

```
{
import { NetInfo } from 'react-native';
}
```

**Comment by vishalnarkhede** [comment]
Hey @familywiser1 , thanks for brining this to our attention. We have fixed this issue and made the sdk compatible with Expo36 as part of  [v0.5.0](https://github.com/GetStream/stream-chat-react-native/releases/tag/v0.5.0). Cheers :)

Please let us know if that works for you!!

**Comment by familywiser1** [comment]
Yes, it works!!! thanks so much for fixing before holidays :)
