### ISSUE TITLE
Query by phone number

### ISSUE THREAD

**Issue by mfbx9da4** [GetStream/stream-chat-react-native#973]
Sorry if this question is asked in the wrong repo, if so please direct me to the correct repo / comms channel.

Quick question around user management.

Our users sign in to our app by phone number. When Alice is adding members to a channel she should be able to see users who are both in her local phone contacts and on stream. What is the recommended way to do this setup?

Possible options
1. Use phone number as user_id and query users where id: { $in: [...] }
2. Paginate all remote contacts and filter them locally. Enable enforce_unique_username. Save phoneNumber in the username field. 
3. Paginate local contacts and check if the user is a stream user one by one. Enable enforce_unique_username. Save phoneNumber in the username field. 

Both option 1 and 2 have trade offs. Is there a better way of doing this?

gz#16395

**Comment by vishalnarkhede** [comment]
Hello and thanks for submitting an issue to our GitHub repository. We’re glad you’re getting hands on with the product. The Issue section of this Github repo is now reserved only for bug reports and feature improvements and suggestions. It looks like what you’re looking for is technical support using the product. For this support, we would suggest emailing our Customer Success and Engineer support team at support@getstream.io with your application key or ID and we’ll be able to help you out. Thanks for your understanding, we’re going to mark this issue as closed.
