### ISSUE TITLE
Still getting notification from muted user

### ISSUE THREAD

**Issue by farukyazici** [GetStream/stream-chat-react-native#98]
Hi,

There is an issue with the muted users. The documentations says that the messages from muted users are not sent. However a user is still receiving messages and push notifications from a user that he muted.

The **muteUser** function provided in the API is used and it's successfully called. Is there anything else needed to mute a user? Because this function is called and still messages and notifications are coming from the muted user.

**Comment by Bogdan-D** [comment]
it's not fully correct. 
From muted users you are not receiving notifications, but messages are coming as usual.
Is this issue related to react-native only?

**Comment by tbarbugli** [comment]
@farukyazici can you provide more information on this? probably best if you can reach out to our support so that you can share more info about your setup (sharing api keys and user ids on Github is not OK)

**Comment by JJ-Kidd** [comment]
@tbarbugli if you want to stop communication from a user you can use something like 
`channel.update({
        frozen: true,
      })`

Apologies if that isn't what you are looking for
