### ISSUE TITLE
Multiple screens with ChannelList and filters adds newly created channel to list where it doesn't comply with configured filters

### ISSUE THREAD

**Issue by mishkeTz** [GetStream/stream-chat-react-native#984]
**Describe the bug**
I have two different screens where I want to render different type of chats i.e. on the first screen (X) I set the filters to type: 'messaging' and on another screen (Y) I have type: 'group'.
When I create the new channel from screen Y it gets added to the channel list on that screen, when I navigate to screen X then I also see that newly added channel - but it shouldn't be there because of the filters set on that channel list. When I pull-down to refresh the list on screen X then that channel is no longer rendered. Why this happens and how can this be solved? I want to have multiple screens on the app where I render different channels based on different filters.

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native): 3.9.2
- react-native: 0.63.4
- Device/Emulator (android/ios) and OS version: BOTH

**Expected behavior**
When new channels gets created it shouldn't be rendered in ChannelList where it doesn't fulfil specified filters.

**Additional context**
I have two different screens that should render the ChannelList and each screen has different filters.

**Screenshots**
(Channel with name "8" shouldn't be there)
<img width="413" alt="Screenshot 2021-11-09 at 19 05 27" src="https://user-images.githubusercontent.com/15350199/140979705-3b11275c-fa6b-426e-a893-8e88b47ac3de.png">

(Correct one)
<img width="410" alt="Screenshot 2021-11-09 at 19 06 04" src="https://user-images.githubusercontent.com/15350199/140979777-71331d2d-f604-424c-8851-262d4ec20370.png">

(After the reload - pull down - to refresh the list, Channel "8" is not rendered which is correct)
<img width="413" alt="Screenshot 2021-11-09 at 19 06 22" src="https://user-images.githubusercontent.com/15350199/140979812-fb6edfff-d1a9-4fb0-b976-1090ebfd92bd.png">

gz#16576

**Comment by vishalnarkhede** [comment]
Hey @mishkeTz Please take a look at this guide - https://getstream.io/chat/docs/sdk/reactnative/guides/customize-channel-list/#customizing-event-handlers

**Comment by mishkeTz** [comment]
Thank you, that solved it!
