### ISSUE TITLE
Re-render custom input

### ISSUE THREAD

**Issue by mishkeTz** [GetStream/stream-chat-react-native#997]
Is there a way to re-render the Input component?
What I want to do is initially provide my custom input component and then on state change (in my component) render the default input component.

It looks like that initial component that's passed to the Channel gets memoized and it's hard to trigger the re-rendering? 

gz#16703

**Comment by vishalnarkhede** [comment]
@mishkeTz you could do something like this:

```tsx
<Channel
  ...
>
  {
    stateValue
    ? <MessageInput Input={CustomInput} />
  ) : <MessageInput />
  }
</Channel>```

**Comment by mishkeTz** [comment]
Nice! Works, thank you!
